### ISSUE TITLE
Ability to select a software adapter

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1003]
**Is your feature request related to a problem? Please describe.**
Sometimes, you just want to check if something runs in software, be it `lavapipe` or WARP. We currently have no controls to expoes this, other than by enumerating the adapters.

**Describe the solution you'd like**
Perhaps, we could have a `PowerPreference::Virtual` or something like that?

**Describe alternatives you've considered**
environment vars

**Additional context**
Example in question is https://github.com/gfx-rs/wgpu/issues/1002, which appears to only be visible on WARP.

**Comment by cwfitzgerald** [comment]
I think this is also a good feature to have, but in the mean time, you can force warp from `dxcpl.exe` on windows.
