### ISSUE TITLE
Creating incompatible texture view incorrectly reports OutOfMemory

### ISSUE THREAD

**Issue by kazimuth** [gfx-rs/wgpu#1006]
**Description**
Attempting to create a texture view of dimension `D2Array` from a texture of dimension `D3` results in `wgpu_core::resource::CreateTextureViewError::OutOfMemory`, when in fact the true cause of the error was a `hal::image::ViewCreationError::BadKind`. However, `wgpu_core::CreateTextureViewError` has no variant to reflect this situation.

The relevant line is here:
https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/mod.rs#L1540
The unconditional error replacement suppresses the true error cause.

**Repro steps**
Create an 3d texture and attempt to create a 2d array view of it. You'll get an incorrect OOM panic, instead of a texture view kind mismatch panic.

**Platform**
wgpu 0.6, wgpu-core 0.6.5, wgpu-types 0.6.1

**Comment by cwfitzgerald** [comment]
Duplicate of #952, going to bump priority on getting this one fixed.
