### ISSUE TITLE
Storage Image Binding Issue with DX12

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1013]
**Description**

Pipeline creation fails with a storage image with a binding issue:

```
D3D12 ERROR: ID3D12Device::CreateGraphicsPipelineState: Root Signature doesn't match Pixel Shader: Shader UAV descriptor range (BaseShaderRegister=0, NumDescriptors=1, RegisterSpace=1) is not fully bound in root signature [ STATE_CREATION ERROR #690: CREATEGRAPHICSPIPELINESTATE_PS_ROOT_SIGNATURE_MISMATCH]
```

I'm not too familiar with how D3D12 works in this regard.

**Repro steps**

Run this example on a windows machine. Make sure you're on the `dx12-bug` branch. https://github.com/cwfitzgerald/dx11-bug-repro/tree/dx12-bug

**Platform**
Win 10/NVidia

**Comment by kvark** [comment]
Fixed in gfx-backend-dx12-0.6.12
