### ISSUE TITLE
Invalid surface/swapchain destruction sequence

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1030]
**Description**
Running on Vulkan results in a spew of errors on exit.

**Repro steps**
Closing any wgpu-rs examples.

**Expected vs observed behavior**
No spew is expected

**Extra materials**
Regressed by #1023

**Platform**
Windows 10, Vulkan, Intel

**Comment by kvark** [comment]
I believe what we need here is having the swapchain to hold the surface alive. When surface is destroyed by the user, we have no access to any device-specific resources it has, so we can't forcefully clean them up.

**Comment by cwfitzgerald** [comment]
Seems to have been fixed at some point.
