### ISSUE TITLE
Empty window in MacOS 10.12

### ISSUE THREAD

**Issue by kbarros** [gfx-rs/wgpu#104]
**Observed behavior**:

On MacOS **10.12**: Compiling the `hello_triangle` example succeeds, but executing the binary brings up an empty window (gray background).

After upgrading to MacOS **10.14** the previously compiled `hello_triangle` executable works fine! (No recompilation necessary.)

**Expected behavior**:

Perhaps wgpu could be made to work on MacOS 10.12. Alternatively, if wgpu is incompatible with MacOS 10.12, I would expect it to report an error.

**Comment by seivan** [comment]
My guess is this a bug in winit more wgpu. 
Happens with Glium as well. I could be wrong but I got the same behavior even with Mojave as well. Can you test with SDL instead, I don’t got .12 to test with.

**Comment by kbarros** [comment]
Unfortunately after upgrading my machine I don't have access to 10.12 either.

**Comment by kvark** [comment]
I believe this is fixed since we switched to the new swapchain model (a while ago).
