### ISSUE TITLE
[DX11] Memory leak on resize

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu#105]
The examples all leak memory on windows with the dx12 backend. The dx11 backend appears to be fine at first, but leaks when you resize the window. Making the window smaller also breaks rendering with dx11.

The vulkan backend does not exhibit this behavior.

**Comment by kvark** [comment]
Let's leave DX12 memory leak for #1228 and make this issue about the resize in dx11

**Comment by cwfitzgerald** [comment]
The DX11 doesn't leak as of 2-3 days ago, so this can be closed.
