### ISSUE TITLE
Buffer write issue with DX11 + IntelHD 

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1060]
Bug originally filed as https://github.com/gfx-rs/wgpu-rs/pull/585 against wgpu-rs by @qthree, resubmitting for ease of tracking. The referenced branch was https://github.com/qthree/wgpu-rs/tree/double-rect. The body of the issue was left unchanged.

# Original Issue

Demonstration of buffer write issue with DX11 + Intel HD. Not intended for merging.
Frame rendering starts before the end of uniform buffer update.
That results in a glitches.
If you see only one rectangle then you're OK.
![RUIqXmDZge](https://user-images.githubusercontent.com/9898555/95089313-3308f280-074e-11eb-9704-8308e140fc58.png)
`main.rs` has constants at the top for tweaking:
```
SUBMITS - how many times to redraw using different render pass, command buffer and separate submit
DRAWCALLS - how many times to call draw inside one render pass
AFTER_SUBMIT_DELAY_MS - sleeping between different submits.
```
I have this issue with:
```
SUBMITS = 10
DRAWCALLS = 1
AFTER_SUBMIT_DELAY_MS = 10
```
or
```
SUBMITS = 1
DRAWCALLS = 1000
AFTER_SUBMIT_DELAY_MS = 0
```
This demonstration is done using modified `hello-triangle` example.

**Comment by kvark** [comment]
Needs to be registered in https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues

**Comment by cwfitzgerald** [comment]
Added.

**Comment by qthree** [comment]
I'm not sure if it's the same issue, or something else, but it was reported that HD5570 has issue that looks the same. Though it's with old wgpu version from last autumn. I'll update this example to the last wgpu release and send it to person who has issue. Here's his adapter info:
```rust
AdapterInfo {
    name: "AMD Radeon HD 5570",
    vendor: 4098,
    device: 26841,
    device_type: DiscreteGpu,
    backend: Dx11,
}
```

**Comment by cwfitzgerald** [comment]
Funky. Note DX11 is still not supported on master.

**Comment by qthree** [comment]
Nope, not the same issue, he has just static image without running rectangle. But I blame ancient gpu and buggy drivers.
![image](https://user-images.githubusercontent.com/9898555/126348826-d5c3ad7f-6568-4890-a55b-75c6febc819f.png)

**Comment by cwfitzgerald** [comment]
Closing this as this was on gfx-hal
