### ISSUE TITLE
Window resizing weirdness with dx12

### ISSUE THREAD

**Issue by Diggsey** [gfx-rs/wgpu#1061]
On windows 10, I see this after I resize the window:
![image](https://user-images.githubusercontent.com/451321/100491711-c262ce80-311d-11eb-8359-012b0445824b.png)

The text is my terminal somehow showing through the window in front of it...

When I run the "hello" example, it prints:
> AdapterInfo { name: "Intel(R) UHD Graphics 620", vendor: 32902, device: 22807, device_type: IntegratedGpu, backend: Vulkan }

If I move the window by dragging the titlebar, the issue fixes itself until I next resize.

I tested all the examples, and strangely the issue *only* happens on the cube example. This seems to be because the other examples default to using vulkan as the backend, but the cube example uses dx12 instead?

Furthermore, this issue does not occur if I manually change the backend to "dx11" or "vulkan".

**Comment by cwfitzgerald** [comment]
@Diggsey if I'm correct this was fixed by updating your intel graphics drivers? I think we can likely close this as there's not much we can do if intel was misbehaving behind window's back. Feel free to re-open if that's not satisfactory.

**Comment by Diggsey** [comment]
Yep - this is now listed here: https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues#intel--directx-12
