### ISSUE TITLE
Tracking Issue for Wgpu on Raspberry Pi 4

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1069]
**Description**

Summary of all current issues and todos for a seamless raspbery pi 4 experience. Most of these will be driver issues and will also be found on https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues. Links to upstream issues will be added as they are filed.

Unless listed otherwise, this was tested on mesa commit `a1976e1cb2d817a4d5229994b83c87d82485af9b`.

## Shadow

There is sporatic corruption of the shadows that pops in weird ways. Video here: https://cwfitz.com/zFpfee.mp4.

Upstream bug filed: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3916

## Water

Water works fine until you resize it, then the water looks to have some sort of block-based corruption. If you get lucky when you resize it'll go back to normal. This might be caused by https://github.com/gfx-rs/wgpu-rs/issues/665 as the issue doesn't show up on a pre gfx-master version of wgpu.

## Cube

Cube works correctly most of the time, but random frames will have the vertex order reversed so the lines go the other way through the square faces.

**Comment by andrewdavidmackenzie** [comment]
I am currently (master, Dec 15 2022) on Pi4 seeing:

'No suitable GPU adapters found on the system!'

Am I right in assuming this is the correct open issue to track?

**Comment by cwfitzgerald** [comment]
It is, but if you have a vulkan implementation it should at least find an adapter.

**Comment by Lokathor** [comment]
`sudo apt install vulkan-tools mesa-vulkan-drivers` will now install the vulkan drivers on raspberry pi. If you run a vulkan using program it'll print a message as it loads that technically the driver isn't fully conformant and it's for testing only, but the program will render.

I didn't test any of the examples from this repo specifically (i was checking out the `minimal-winit` example from `pixels`, which uses `wgpu`). If you want I can possibly check more soon.

**Comment by anselanza** [comment]
Indeed, `pixels` does work on the Raspberry Pi 4 as mentioned, after installing the Vulkan V3D driver, but I cannot get the built-in examples from WGPU to run.

The following error is typical:
```
WARNING: v3dv is neither a complete nor a conformant Vulkan implementation. Testing use only.
Using V3D 4.2 (Vulkan)
[2023-05-25T13:39:35Z ERROR wgpu::backend::direct] Error in Adapter::request_device: Not enough memory left
thread 'main' panicked at 'Unable to find a suitable GPU adapter!: RequestDeviceError', wgpu/examples/cube/../framework.rs:236:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The **Not enough memory** part seems important. I have tried running this on both a standard 4GB Pi 4 as well as an 8GB model - both with GPU RAM set to 256MB rather than the default 64MB. Same error on both.

**Comment by anselanza** [comment]
These errors only occur on v0.16.0 and v0.16.1.

If I check out v0.15, the same version Pixels appears to depend on, then the built-in WGPU examples do indeed run using Vulkan on the Pi 4.

**Comment by sfjohnson** [comment]
I'm currently testing on Raspberry Pi CM4. I have the wgpu examples working, but I'm getting the following errors:

```
ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineLayoutCreateInfo-descriptorType-03023 (0xf26ac9dd)]
    	Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03023 ] Object 0: handle = 0x55ab3d03a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xf26ac9dd | vkCreatePipelineLayout(): max per-stage uniform buffer bindings count (1) exceeds device maxPerStageDescriptorUpdateAfterBindUniformBuffers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER and VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindUniformBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03023)
[2024-08-03T11:33:03Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x55ab3d03a0, name: ?)
[2024-08-03T11:33:03Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineLayoutCreateInfo-descriptorType-03024 (0xeb2bfadc)]
    	Validation Error: [ VUID-VkPipelineLayoutCreateInfo-descriptorType-03024 ] Object 0: handle = 0x55ab3d03a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xeb2bfadc | vkCreatePipelineLayout(): max per-stage storage buffer bindings count (2) exceeds device maxPerStageDescriptorUpdateAfterBindStorageBuffers limit (0). The Vulkan spec states: The total number of descriptors with a descriptorType of VK_DESCRIPTOR_TYPE_STORAGE_BUFFER and VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC accessible to any given shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxPerStageDescriptorUpdateAfterBindStorageBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-descriptorType-03024)
[2024-08-03T11:33:03Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x55ab3d03a0, name: ?)
[2024-08-03T11:33:03Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03037 (0x498f6d17)]
    	Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03037 ] Object 0: handle = 0x55ab3d03a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x498f6d17 | vkCreatePipelineLayout(): sum of uniform buffer bindings among all stages (1) exceeds device maxDescriptorSetUpdateAfterBindUniformBuffers limit (0). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxDescriptorSetUpdateAfterBindUniformBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03037)
[2024-08-03T11:33:03Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x55ab3d03a0, name: ?)
[2024-08-03T11:33:03Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03039 (0x777b1b8e)]
    	Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03039 ] Object 0: handle = 0x55ab3d03a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x777b1b8e | vkCreatePipelineLayout(): sum of storage buffer bindings among all stages (2) exceeds device maxDescriptorSetUpdateAfterBindStorageBuffers limit (0). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_STORAGE_BUFFER accessible across all shader stages and across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceDescriptorIndexingProperties::maxDescriptorSetUpdateAfterBindStorageBuffers (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-03039)
```

These 4 limits are indeed 0 in `vulkaninfo`, so not supported by the current driver. Is there a way to set them to 0 in wgpu? I'm trying to get [Vello](https://github.com/linebender/vello) to work and I'm getting a black screen on all of their examples.

**Comment by cwfitzgerald** [comment]
As there's no active work in this space, I'm going to close this issue. If someone wants to re-own this, please file a new tracking issue with up to date todos.
