### ISSUE TITLE
Encoder is submitted more than once

### ISSUE THREAD

**Issue by infinitesnow** [gfx-rs/wgpu#1089]
I observed in RenderDoc some buffer values being incorrect, and I realized that [this encoder](https://github.com/infinitesnow/fractal/blob/main/src/kneader.rs#L647) seems to be submitted more than once. The WebGPU trace looks clean, but the Vulkan API trace seems to confirm it.

[WebGPU trace](https://github.com/gfx-rs/wgpu-rs/files/5685090/trace.tar.gz)

[Vulkan API trace](https://github.com/gfx-rs/wgpu-rs/files/5685087/trace.log)

[Vulkan Info](https://github.com/gfx-rs/wgpu-rs/files/5685098/vkinfo.txt)

I'm on wgpu-rs master patched to use the latest bugfix on wgpu-core (`01733a2f45143ee43d2a3473bc618fd06cfc076d`)

**Comment by kvark** [comment]
See #1088, it includes a fix to pipeline names.

**Comment by infinitesnow** [comment]
Took a trace with your change, labels still look wrong although they look better. `Particles Variation Init Encoder` is still in the renderpass, where it shouldn't be: [trace.log](https://github.com/gfx-rs/wgpu/files/5698938/trace.log)

**Comment by kvark** [comment]
#1090 will take care of the render pass names that leaked

**Comment by kvark** [comment]
It got accidentally closed. Please re-open if any issues remain!

**Comment by infinitesnow** [comment]
I'm still seeing the issue though. Here is the [renderdoc capture](https://github.com/gfx-rs/wgpu/files/5699142/capture.rdc.gz).

I tried to make the example as minimal as possible. Here is what I see. Here I have run my counters, but I haven't run the command which writes my buffer, in fact it's zero (cool):
![2020-12-15-235110_1920x1080_scrot](https://user-images.githubusercontent.com/8825313/102282269-a12d1b00-3f30-11eb-8852-9a337f0ab79b.png)
Then it assumes the expected value, computed from the counters (cool):
![2020-12-15-235114_1920x1080_scrot](https://user-images.githubusercontent.com/8825313/102282273-a25e4800-3f30-11eb-8b11-a8b20430b59f.png)
Then, here's the issue. It seems that everything was run from the beginning! It counted all over again (counters are doubled) and wrote the buffer 
![2020-12-15-235121_1920x1080_scrot](https://user-images.githubusercontent.com/8825313/102282275-a2f6de80-3f30-11eb-8510-abc9474d4077.png)

I made two traces, one with and one without the issue. The only difference is that I comment out [this line](https://github.com/infinitesnow/fractal/blob/debug/src/kneader.rs#L653), which just wipes the counters with `write_buffer`, in the clean one:
[wgpu trace / clean](https://github.com/gfx-rs/wgpu/files/5699170/trace.clean.tar.gz)
[wgpu trace / dirty](https://github.com/gfx-rs/wgpu/files/5699171/trace.dirty.tar.gz)
[Vulkan trace / clean](https://github.com/gfx-rs/wgpu/files/5699174/trace.clean.log)
[Vulkan trace / dirty](https://github.com/gfx-rs/wgpu/files/5699175/trace.dirty.log)

There is one thing I find suspicious:
```
   1524 vkBeginCommandBuffer(commandBuffer, pBeginInfo) returns VkResult VK_SUCCESS (0):
   1525     commandBuffer:                  VkCommandBuffer = 0x560c0dc84610
   1526     pBeginInfo:                     const VkCommandBufferBeginInfo* = 0x7fff1db9c820:
   1527         sType:                          VkStructureType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO (42)
   1528         pNext:                          const void* = NULL
   1529         flags:                          VkCommandBufferUsageFlags = 1 (VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT)
   1530         pInheritanceInfo:               const VkCommandBufferInheritanceInfo* = UNUSED
...
   4269 Thread 0, Frame 0:
   4270 vkBeginCommandBuffer(commandBuffer, pBeginInfo) returns VkResult VK_SUCCESS (0):
   4271     commandBuffer:                  VkCommandBuffer = 0x560c0dc83190 [Particles Variation Init Encoder]
   4272     pBeginInfo:                     const VkCommandBufferBeginInfo* = 0x7fff1db9ca40:
   4273         sType:                          VkStructureType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO (42)
   4274         pNext:                          const void* = NULL
   4275         flags:                          VkCommandBufferUsageFlags = 1 (VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT)
   4276         pInheritanceInfo:               const VkCommandBufferInheritanceInfo* = UNUSED
...
   4435 vkCmdDispatch(...
...
   4544 vkCmdDispatch(...
...
   4554 Thread 0, Frame 0:
   4555 vkEndCommandBuffer(commandBuffer) returns VkResult VK_SUCCESS (0):
   4556     commandBuffer:                  VkCommandBuffer = 0x560c0dc84610
   4557 
   4558 Thread 0, Frame 0:
   4559 vkEndCommandBuffer(commandBuffer) returns VkResult VK_SUCCESS (0):
   4560     commandBuffer:                  VkCommandBuffer = 0x560c0dc83190 [Particles Variation Init Encoder]
...
   4688 Thread 0, Frame 0:
   4689 vkQueueSubmit(queue, submitCount, pSubmits, fence) returns VkResult VK_SUCCESS (0):
   4690     queue:                          VkQueue = 0x560c0dbc1ee8
   4691     submitCount:                    uint32_t = 1
   4692     pSubmits:                       const VkSubmitInfo* = 0x7fff1db9b530
   4693         pSubmits[0]:                    const VkSubmitInfo = 0x7fff1db9b530:
   4694             sType:                          VkStructureType = VK_STRUCTURE_TYPE_SUBMIT_INFO (4)
   4695             pNext:                          const void* = NULL
   4696             waitSemaphoreCount:             uint32_t = 0
   4697             pWaitSemaphores:                const VkSemaphore* = 0x8
   4698             pWaitDstStageMask:              const VkPipelineStageFlags* = NULL
   4699             commandBufferCount:             uint32_t = 3
   4700             pCommandBuffers:                const VkCommandBuffer* = 0x560c0dd014a0
   4701                 pCommandBuffers[0]:             const VkCommandBuffer = 0x560c0dc84610
   4702                 pCommandBuffers[1]:             const VkCommandBuffer = 0x560c0dc81d10
   4703                 pCommandBuffers[2]:             const VkCommandBuffer = 0x560c0dc83190 [Particles Variation Init Encoder]
   4704             signalSemaphoreCount:           uint32_t = 0
   4705             pSignalSemaphores:              const VkSemaphore* = 0x8
   4706     fence:                          VkFence = 0x4c000000004c
```
It seems to be recording dispatch commands on both `0x560c0dc84610` and `0x560c0dc83190`, and dispatching both?

**Comment by infinitesnow** [comment]
Labels fixed now!

**Comment by kvark** [comment]
Looked at this on both Metal and Vulkan now, and I think it's just RenderDoc playing tricks on you. It doesn't actually capture all the intermediate data. When you click switching between "Buffer Data Init Command Pass" and the neighbor "API Calls", RenderDoc will happily re-run the dispatch, and your counters will seem to grow. That's just how RenderDoc works, it's a technical limitation. But there is nothing in the command stream suggesting that any of the command encoders get submitted twice. You can see that the only command happening after the dispatches is `vkCmdCopyBuffer`, which is what you'd expect from that `write_buffer` call.

On that note, I'm going to close the issue. Please feel free to re-open if you find my reasoning unsound!
