### ISSUE TITLE
MatN 'VertexFormat's

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu#1091]
It would be great to be able to do this (in this case for an instance vertex buffer):
```rust
wgpu::vertex_attr_array![4 => Mat4]
```
instead of:
```rust
wgpu::vertex_attr_array![4 => Float4, 5 => Float4, 6 => Float4, 7 => Float4]
```
At the moment, the above is currently broken (at least on the `gecko` branch of wgpu-rs) because the [`is_subtype_of`](https://github.com/gfx-rs/wgpu/blob/42a8dc5b343b1c882d7c5bb03b0718602ea03915/wgpu-core/src/validation.rs#L648) check fails.

**Comment by cwfitzgerald** [comment]
This would need to be an native-only extension, upstream WebGPU doesn't support this.

**Comment by expenses** [comment]
Wow, I wrote this a while ago ;) My opinion now is that we don't want to support this. You should probably be passing instance transforms as a `Float4x4` translation + scale and a `Float4x4` quaternion/rotor. If you absolutely need matrices instanced like this then you should either split them up into 4 `Float4x4` rows/columns or use a storage buffer.

Happy to close this.

**Comment by cwfitzgerald** [comment]
Heh, sounds good
