### ISSUE TITLE
Shader compilation failure when using push constants on DX12 backend

### ISSUE THREAD

**Issue by Herschel** [gfx-rs/wgpu#1108]
**Description**
When using a shader with push constants, shader compilation fails with:
```
[2020-12-26T05:27:05Z ERROR gfx_backend_dx12::device] D3DCompile error 80004005: D:\projects\ruffle\Shader@0x000001C2BEEE8830(22,18-30): error X3004: undeclared identifier '_13_add_color
```

**Repro steps**
```
git clone -b wgpu-dx12-push-constant https://github.com/Herschel/ruffle
cd ruffle
cargo run --bin ruffle_desktop -- -g dx12 heroes_of_cybertron.swf
```

**Expected vs observed behavior**
The shader should compile and function successfully, as it does on the vulkan and metal backends.

**Extra materials**
Shaders are in ruffle/render/wgpu/shaders. The push constant block is a block containing a mat4 and two vec4s.

**Platform**
Windows 10 Pro 64-bit
Nvidia Geforce 2080 Ti
rustc 1.48.0 (7eac88abb 2020-11-16)
wgpu-rs @ c0418b1b8ae22e86fd0e7a7eb486e04dcb0bd6f5

**Comment by Herschel** [comment]
The vertex and fragment shaders are using different ranges of push constants; however, for both shaders, I was using the same uniform block:
```
// Push constants: matrix + color
layout(push_constant) uniform PushConstants {
    mat4 world_matrix;
    vec4 mult_color;
    vec4 add_color;
};
```
and passing the proper ranges and stage to `RenderPass::set_push_constant`. This worked correctly in vulkan and metal, but gives the shader compilation error in dx12.

If I instead split the uniform blocks up between vert and frag and specify the offset:
```
// vertex shader
layout(push_constant) uniform VertexPushConstants {
    mat4 world_matrix;
};

// fragment shader
layout(push_constant) uniform FragmentPushConstants {
    layout(offset = 64) vec4 mult_color;
    vec4 add_color;
};
```
This works in DX12.

**Comment by teoxoy** [comment]
When this issue was first opened, the DX12 backend was using `spirv_cross`

Since wgpu 0.8 all backends are using `naga` and push constants are not yet implemented for the HLSL backend (see https://github.com/gfx-rs/naga/issues/1782).
