### ISSUE TITLE
[Question/Feature Request] Headless render/render to offscreen buffer

### ISSUE THREAD

**Issue by TheButlah** [gfx-rs/wgpu#1110]
I'd like to use WebGPU to render to a frame buffer without needing any windowing to be set up or displaying the results. Is that possible? If not I'd like to request it as a feature

My specific use case, in case the context is helpful, is that I want to write a WebXR application but would rather learn WebGPU than WebGL. WebXR only supports WebGL to my knowledge, so I plan to do something very hacky - write all my rendering code in WebGPU, use it to get out a final framebuffer or texture, and then read the bytes of the frame and pass it to WebGL as a texture. This would probably be really stupid for a real game, but I'm just doing tech demos and this hack would be worth it to me to be able to use WebGPU.

**Comment by JMS55** [comment]
I believe you could do this right now. See the capture example https://github.com/gfx-rs/wgpu-rs/tree/master/examples/capture.

**Comment by TheButlah** [comment]
Yep, thats exactly what I was looking for. Thanks!
