### ISSUE TITLE
`triage_suspected` / `texture_create_view` deadlock

### ISSUE THREAD

**Issue by ccbrown** [gfx-rs/wgpu#1118]
**Description**

Running `device_poll` on one thread and rendering from another can deadlock.

Thread A gets stuck here:

```rust
        if !self.suspected_resources.textures.is_empty() {
            let mut trackers = trackers.lock();
            let (mut guard, _) = hub.textures.write(token);
```

It acquires the `trackers` lock then deadlocks trying to acquire a write lock on hub textures.

Thread B gets stuck here:

```rust
        let (device_guard, mut token) = hub.devices.read(&mut token);
        let (texture_guard, mut token) = hub.textures.read(&mut token);
        let error = loop {
            let texture = match texture_guard.get(texture_id) {
                Ok(texture) => texture,
                Err(_) => break resource::CreateTextureViewError::InvalidTexture,
            };
            let device = &device_guard[texture.device_id.value];

            let view = match device.create_texture_view(texture, texture_id, desc) {
                Ok(view) => view,
                Err(e) => break e,
            };
            let ref_count = view.life_guard.add_ref();

            let id = hub.texture_views.register_identity(id_in, view, &mut token);
            #[cfg(feature = "trace")]
            if let Some(ref trace) = device.trace {
                trace.lock().add(trace::Action::CreateTextureView {
                    id: id.0,
                    parent_id: texture_id,
                    desc: desc.clone(),
                });
            }

            device
                .trackers
                .lock()
                .views
                .init(id, ref_count, PhantomData)
                .unwrap();
            return (id.0, None);
        };
```

It acquires a read lock on hub textures, then deadlocks trying to acquire the `trackers` lock.

**Repro steps**

Run `device_poll` on one thread and manipulate texture views from another. I'm really hoping the problem / fix is obvious to someone familiar with the codebase. It seems like a textbook deadlock to me, but I'm not sure what the established rules are for acquiring these locks elsewhere.

**Expected vs observed behavior**

Obviously I don't expect a deadlock. :P

**Platform**

macOS. I'm using wgpu 0.6.5 but I believe this still applies to master.

**Comment by kvark** [comment]
Thank you for reporting! Locking the device trackers is one of the few unprotected things we got left. We'll get it sorted out ASAP!
