### ISSUE TITLE
Dx12 backend panics with: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated

### ISSUE THREAD

**Issue by Zazck** [gfx-rs/wgpu#1133]
[wgpu-trace.zip](https://github.com/gfx-rs/wgpu-rs/files/5774864/wgpu-trace.zip)

graphic card: sapphire rx580 2048sp
os: win10 20H2 19042.630

the dx12 env is working fine(not a driver issue).
running "the talos principle" using dx12 backend (beta) longer than 10 minutes without problem.
reboot does not fix this.
vulkan backend works good.

I tested servral examples
cube, boids, skybox, shadow
all affected.
they all panics after about 240secs, except the "shadow" only alives 131 secs
windows would raise an alert of "unknown software exception(0xc000001d)"

details are in the trace file attachment, only contains trace file of "boids" example.
I could provide more trace files and remote control access if needed

**Comment by kvark** [comment]
Thank you for filing!
I find it suspicious that the problem only occurs on DX12. The descriptor allocator does not depend on the backend.

**Comment by cwfitzgerald** [comment]
Closing as stale, please refile if it's still an issue.
