### ISSUE TITLE
draw calls with no vertex buffers and fake vertex ranges now trigger validation errors

### ISSUE THREAD

**Issue by kyren** [gfx-rs/wgpu#1138]
Sorry for not being precise with the bug description here, I'm coming into this bug via `wgpu-rs` and filing it here after discussion on matrix.

We use a common SSBO trick to do "fake instances" where you bind an SSBO containing vertex data to the vertex shader and don't set any vertex buffers on the render pass at all, then use `gl_VertexIndex` in the shader to get data out of the SSBO. In the version of wgpu-rs we are using (ab8b0e3), we now get a validation error on finishing the render pass:

```
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(5, 3, Vulkan)>`
    In a draw command
    vertex 96 extends beyond limit 0
```

I don't have a reproducible test case and I'm not even *100%* sure what I said is the cause though I'm somewhat confident and it seemed not too far fetched when discussed in matrix so I'm filing this issue as instructed.

**Comment by cwfitzgerald** [comment]
Is this still an issue? I feel like this would fail for any case where people are doing vertex pulling.

**Comment by kyren** [comment]
Oh, I believe we identified an issue on our end that was causing it. There was an entry for a vertex buffer that was left in the VertexStateDescriptor after switching to vertex pulling that started failing (correctly) after some wgpu update. After removing it it works again, I'm sorry for the noise!
