### ISSUE TITLE
How does set_vertex_buffer handle the size field of buffer slices internally?

### ISSUE THREAD

**Issue by chaynabors** [gfx-rs/wgpu#1139]
The top bound on the buffer_slice argument within RenderPass::set_vertex_buffer appears to have no effect on visual output when drawing indexed geometry, doesn't panic, and outputs no validation errors when given arbitrary values. I'm assuming the length of my vertex data in bytes is a safe bet for the top bound but is there anything I'm missing?

**Comment by cwfitzgerald** [comment]
I'm going to close this - this is the issue of index buffer validation, and it's an expensive and complicated one. We currently don't deal with it, but we will, likely through switching to vertex pulling on platforms that need it.
