### ISSUE TITLE
Add SHADER_FLOAT64 native feature

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu#1143]
**Is your feature request related to a problem? Please describe.**
For most computer graphics use cases 32-bit floats work well enough, but there are specific situations where they don't. For example, the earth has a radius of about 6000km so if the origin were placed at the center of the planet, positions on the surface can only be expressed with 50cm precision. There are many ways around these sorts of limitations, but the simplest all rely on being able to do at least a small amount of 64-bit float computations on the GPU. 

Currently when using SPIR-V shaders, wgpu does allow usage of 64-bits floats ("doubles") provided that the underlying driver also does. Unfortunately there is no way to probe whether this will work and this may stop being supported once shader validation is fully implemented.

**Describe the solution you'd like**
Add a SHADER_FLOAT64 native feature to mirror the one exposed by gfx-hal.

**Describe alternatives you've considered**
A software float64 implementation would enable this feature to be implemented everywhere (which sounds somewhat ridiculous, but is actually the strategy that Mesa uses).

**Comment by DasEtwas** [comment]
Regarding planet rendering precision issues, one would rather resort to using a sparse representation of terrain (chunks) whose individual transforms are calculated using double precision relative to the camera. Then this transform is converted to single floats. Thus, a view matrix with large translations can be omitted and precision is just fine for small enough chunks (<10km). Double floats can have significant performance impacts on many cards (testing needed).

**Comment by fintelia** [comment]
You are correct that double precision is often much slower than single precision. Looking at the GFLOPS numbers from [here](https://www.techpowerup.com/gpu-specs/) the factor seems to be 16x slower for AMD and 32-64x for NVIDIA. However, that still translates to several hundred billion floating point operations per second. You can fit a lot of work into that budget: it is enough to do the chunk generation on the GPU (my preferred solution) or even just the vertex transformations themselves.
