### ISSUE TITLE
DX12 crash on create_pipeline_layout: Can't serialize root signature: -2147024809

### ISSUE THREAD

**Issue by DasEtwas** [gfx-rs/wgpu#1146]
Windows 10, wgpu 0710a7a9116ffca8039ce7d8fc58197b93e02d3c

HRESULT: -2147024809 = 0x80070057

I'm using a fairly complex bind group layout. [A `panic!` is triggered inside the dx12 gfx-rs backend when calling RootSignature.](https://github.com/gfx-rs/gfx/blob/84e3c87bbf9c3c668d651ae19a963972999ac079/src/backend/dx12/src/device.rs#L1762)

wgpu device features: 
```
Features::PUSH_CONSTANTS|
Features::SAMPLED_TEXTURE_BINDING_ARRAY|
Features::SAMPLED_TEXTURE_ARRAY_NON_UNIFORM_INDEXING|
Features::NON_FILL_POLYGON_MODE,
```

[Copy of PipelineLayoutDescriptor and PipelineLayoutDescriptor::bind_group_layouts](https://gist.github.com/DasEtwas/8328b4129e39c289551604eeeadb1798)

**Comment by DasEtwas** [comment]
Wouldn't this apply to OpenGL as well?

**Comment by kvark** [comment]
This is DX12-specific, it's in the binding model implementation, which is very different from OpenGL.

**Comment by cwfitzgerald** [comment]
Closing as out of date as we're using the new hal
