### ISSUE TITLE
map_read_async is never called

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#117]
I setup a map_read_async callback like this:
```rust
framebuffer_out.map_read_async(0, width as u32 * height as u32 * 4, |result: wgpu::BufferMapAsyncResult<&[u32]>| {
        if let wgpu::BufferMapAsyncResult::Success(data_u32) = result {
            println!("SUCCESS");
            for data in data_u32 {
                println!("{:x}", data);
            }
        }
        else {
            println!("ERROR");
        }
    });
```

And the callback is never called.

Nothing is hit in the validation layers.

Full example [here](https://github.com/gfx-rs/wgpu/files/3033395/full_example.txt), where I attempt to draw to a texture, then copy the texture to a buffer. and then display it:

**Comment by kvark** [comment]
Thanks for filing this! cc @swiftcoder 
I assume this is a blocker? Will be able to look at it tonight.

**Comment by torss** [comment]
Just FYI: Here <https://github.com/torss/wgpu/commit/519822aada0cfe4f5d1ec3cdcd0e5140c424f3be> is my fork with a **very hackish** API-extending "solution", in case anyone urgently needs to get this working.
_(Re. the callback not being called, the fork solves it with the solution propsed in PR #123, but it also seems that `map_read_async` currently can read data too soon, i.e. obtain corrupt data, so my temporary solution in that fork is to allow users to manually wait for a fence.)_
