### ISSUE TITLE
Vulkan Validation errors when creating swapchain without TextureUsage::COPY_SRC

### ISSUE THREAD

**Issue by LPGhatguy** [gfx-rs/wgpu#1172]
**Description**
The Vulkan validation errors report errors when a swapchain is created with only `TextureUsage::RENDER_ATTACMENT`:

```
[ERROR gfx_backend_vulkan]
        VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-03210 (-872316813)] : Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-03210 ] Object 0: h
andle = 0xbaa068000000004d, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xcc018073 | vkCmdBeginRenderPass(): Image view #0 created from an image with usag
e set as 0x11, but image info #0 used to create the framebuffer had usage set as 0x10 The Vulkan spec states: If framebuffer was created with a VkFramebufferCr
eateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure
 included in the pNext chain must be a VkImageView of an image created with a value of VkImageCreateInfo::usage equal to the usage member of the corresponding
element of VkFramebufferAttachmentsCreateInfo::pAttachments used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.2.162.0/windows/1.2-extensions/vks
pec.html#VUID-VkRenderPassBeginInfo-framebuffer-03210)
        object info: (type: RENDER_PASS, hndl: 13447862836537589837)
```

I am using wgpu-rs HEAD alongside wgpu HEAD and creating a swapchain like this:

```rust
let swap_chain_descriptor = wgpu::SwapChainDescriptor {
    usage: wgpu::TextureUsage::RENDER_ATTACHMENT,
    format: wgpu::TextureFormat::Bgra8UnormSrgb,
    width: initial_size.x,
    height: initial_size.y,
    present_mode: wgpu::PresentMode::Fifo,
};

let swap_chain = core
    .device
    .create_swap_chain(&surface, &swap_chain_descriptor);
```

The error seems to indicate that however the swapchain image is being used, it is also expecting to have Vulkan's `COLOR_ATTACHMENT | TRANSFER_SRC` bits set, but only has `COLOR_ATTACHMENT` set.

Changing the usage to include `COPY_SRC` fixes the validation error, but breaks other backends like DX12:

```diff
-     usage: wgpu::TextureUsage::RENDER_ATTACHMENT
+     usage: wgpu::TextureUsage::RENDER_ATTACHMENT | wgpu::TextureUsage::COPY_SRC,
```

**Platform**
* Windows 10 v1909
* Vulkan SDK 1.2.162.0
* wgpu c2c8d2203ed312e3b63354096ec90634b8f9b0b5
* wgpu-rs b04cc289e84e0a754c9059a23970d8204f367cd8

**Comment by LPGhatguy** [comment]
The other member of my team gets a different validation error, using the Vulkan SDK v1.2.162.1:

```
[ERROR gfx_backend_vulkan]
        VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-03210 (-872316813)] : Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-03210 ] Object 0: handle = 0x1385b20000000057, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xcc018073 | vkCmdBeginRenderPass(): Image view #0 created from an image with usage set as 0x19, but image info #0 used to create the framebuffer had usage set as 0x11 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView of an image created with a value of VkImageCreateInfo::usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachments used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03210)
        object info: (type: RENDER_PASS, hndl: 1406726171692892247)
```

This seems to be involving storage textures. Let me know if there are any other details I can provide here or if this is a separate bug entirely.

**Comment by kvark** [comment]
Are you able to run the wgpu-rs examples? Does the validation error also show there?

**Comment by LPGhatguy** [comment]
Yes! I was able to reproduce the same issue with the wgpu-rs cube example, with the same validation error message. My partner also got a validation error on her machine, the same one as in our game but different than my machine.

**Comment by kvark** [comment]
So just running the examples? I'm totally puzzled. I'm running the cube example on Windows on Vulkan, with SDK 1.2.162.1 installed and Vulkan Configurator in the "Validation - Standard" setting, and nothing shows up.

**Comment by kvark** [comment]
Ok, maybe this is too much to ask. One thing that would make it clear if we are wrong is - having a https://github.com/LunarG/gfxreconstruct trace. It would show that we are creating those flags, where we shouldn't be. So far, I'm failing to see any issue with the relevant code in either wgpu-core or gfx-backend-vulkan.

**Comment by kvark** [comment]
Let's close it in favor of https://github.com/gfx-rs/wgpu/issues/1175#issuecomment-767702911, which has a runnable test case with an API trace and a RenderDoc capture.
