### ISSUE TITLE
Binding misbehaves when switching between incompatible pipelines

### ISSUE THREAD

**Issue by Imberflur** [gfx-rs/wgpu#1188]
**Description**
I recently changed the first binding group of one of our pipelines to have an incompatible layout with the others by adding a few entries to the bind group specific to that pipeline. Now when switching to that pipeline and binding the alternative bind group at `0` a vulkan validation error that set `#1` isn't bound occurs along with a segfault.
```
VALIDATION [UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound (-840888189)] : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x5639ca32d5f0, name = first pass, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | VkPipeline 0x390000000039[] uses set #1 but that set is not bound.
object info: (type: COMMAND_BUFFER, hndl: 94806205453808, name: first pass)
```
Interestingly, keeping the call to switch the pipeline but omitting `self.render_pass.set_bind_group(0, &globals.bind_group, &[]);` which switches to the bind group that's incompatible with the other pipelines makes the issue go away (the draw call for this pipeline also has to be omitted since the bind groups are incompatible without the switch but only omitting the draw call does not eliminate the issue). 

The bind group set at `1` is set at the beginning of the pass and isn't changed.

Inserting numerous calls to `set_bind_group` for the sets at `0` and `1` around all the pipeline switches does not resolve the issue.

**Repro steps**
This isn't a minimal example:

- clone https://gitlab.com/Imbris/veloren (git-lfs needed)
- checkout `wgpu-bind-error`
- for quickest startup, in a separate terminal or in the background, run a server with `cargo test-server --no-auth`
- start voxygen with `cargo r`
- type in random username, set the server to `localhost`, and click the multiplayer button
- create a character and enter the world
- observe bug

**Expected vs observed behavior**
Expected: Bind groups remain bound after switching pipelines, rebinding with `set_bind_group` works, and a wgpu level error occurs when bind groups aren't configured properly.
Observed: Vulkan validation error and segfault

**Extra materials**

[wgpu-binding-error-trace.zip](https://github.com/gfx-rs/wgpu/files/5916033/wgpu-binding-error-trace.zip)

**Platform**
Currently on `ab8b0e3766558d541206da2790dfd63f15b13bc4` using the vulkan backend

**Comment by kvark** [comment]
After a bit of tweaking to get this running on Vulkan player, I'm seeing a different validation error:
> [0.947500 ERROR]()(no module): 
VALIDATION [VUID-vkCmdDraw-None-02699 (369680064)] : Validation Error: [ VUID-vkCmdDraw-None-02699 ] Object 0: handle = 0x1e300000001e3, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x1608dec0 | VkDescriptorSet 0x1e300000001e3[] encountered the following validation error at vkCmdDraw() time: Descriptor in binding #5 index 0 requires FLOAT component type, but bound descriptor format is VK_FORMAT_R16G16_UINT. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDraw-None-02699)
object info: (type: DESCRIPTOR_SET, hndl: 531064116216291)

**Comment by Imberflur** [comment]
@kvark I believe that error is completely unrelated. But if it is causing too much noise I can try to get rid of it.

**Comment by kvark** [comment]
@Imberflur looks like a legitimate issue that wasn't caught by our validation, possibly because Naga wasn't able to parse the shaders. You are right that it's not related, but I'm curious on why the replaying doesn't show the issue you reported in the first place. Hmm...

Here is what we can do:
  - I filed https://github.com/gfx-rs/naga/issues/410 to bring the validation to this level.
  - you can try running on a newer wgpu-rs. I was replaying on https://github.com/gfx-rs/wgpu/commit/7f52bea027d2dcb655b72b0581ec595c8be11244 fwiw.
  - I'll try running the Veloren case directly
  - That other validation issue may easily make your driver crash, you need to fix this on your side anyway

**Comment by kvark** [comment]
Got some extra logging to see what's going on:
```
Set pipeline = (3, 1, Vulkan)
	Expect bind group [0] to have layout Valid((0, 1, Vulkan))
	Expect bind group [1] to have layout Valid((2, 1, Vulkan))
	Expect bind group [2] to have layout Valid((1, 1, Vulkan))
	Expect bind group [3] to have layout Valid((6, 1, Vulkan))
	Compatible = false
Set bind group[0] = (21, 1, Vulkan) (layout Valid((0, 1, Vulkan))) with 0 offsets
Set bind group[1] = (10, 1, Vulkan) (layout Valid((2, 1, Vulkan))) with 0 offsets
Set bind group[2] = (25, 1, Vulkan) (layout Valid((1, 1, Vulkan))) with 0 offsets
Set pipeline = (5, 1, Vulkan)
	Expect bind group [0] to have layout Valid((0, 1, Vulkan))
	Expect bind group [1] to have layout Valid((2, 1, Vulkan))
	Compatible = true
Set bind group[0] = (21, 1, Vulkan) (layout Valid((0, 1, Vulkan))) with 0 offsets
Set bind group[1] = (10, 1, Vulkan) (layout Valid((2, 1, Vulkan))) with 0 offsets
```

**Comment by Imberflur** [comment]
trace with updated wgpu and the unrelated validation error fixed
[wgpu-trace-updated.zip](https://github.com/gfx-rs/wgpu/files/5923087/wgpu-trace-updated.zip)
