### ISSUE TITLE
SamplerDescriptor::border_color should maybe not exist

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#1193]
Unless I misunderstand this field, I think it should be removed, and AddressMode should be changed to:
```rust
pub enum AddressMode {
    ClampToEdge,
    Repeat,
    MirrorRepeat,
    ClampToBorder(SamplerBorderColor),
}
```
The only functional difference is that you can have a different SamplerBorderColor per address_mode_{u/v/w}, which might not be possible. But if it is, this would be a better api.

**Comment by kvark** [comment]
I don't think this would be better, for the following reasons:
  1. forcing users to repeat the color value for each u/v/w.
  2. diverging further from WebGPU upstream.
  3. extra validation needed to check that the u/v/w values match.

I think we should close this, unless anybody has strong feelings.
