### ISSUE TITLE
panic in wgpu-core/src/command/allocator.rs with multiple threads

### ISSUE THREAD

**Issue by ccbrown** [gfx-rs/wgpu#1196]
**Description**

When using multiple threads, there is a panic in wgpu-core/src/command/allocator.rs:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/ssm-user/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c788b1c/wgpu-core/src/command/allocator.rs:167:41
stack backtrace:
[2021-02-05T01:50:21Z INFO  vision::output::decklink] frame software latency 71.279361ms
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: wgpu_core::command::allocator::CommandAllocator<B>::allocate_for_thread_id
   4: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_command_encoder
   5: <wgpu::backend::direct::Context as wgpu::Context>::device_create_command_encoder
   6: wgpu::Device::create_command_encoder
```

`device_create_command_encoder` relies on the assumption that it can `device.cmd_allocator.allocate` then `device.cmd_allocator.extend` a buffer. My guess as to why this panic occurs is that another thread is invoking `maintain` on the allocator and removing the first thread's entry from `pools` before the `extend`.

**Repro steps**

Invoke the above functions from multiple threads. Sorry, I don't have minimal runnable repro at the moment that I can submit.

**Expected vs observed behavior**

Expected: No panic.
Observed: Panic.

**Extra materials**
-

**Platform**

Ubuntu, wgpu c788b1cef630fa5b5f0a86132fe84551d4149fb6

**Comment by kvark** [comment]
Thank you! This is a very detailed bug, love it!
