### ISSUE TITLE
Add ARCHITECTURE document

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1202]
See https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html

**Comment by Wumpf** [comment]
Started a thing here a while ago. Too incomplete to so far to put it in
https://demo.hedgedoc.org/HkuLdWaTRdOviyfJDDty-w?both

**Comment by Wumpf** [comment]
decided to put into the wiki what we have, better place even for a draft
https://github.com/gfx-rs/wgpu/wiki/Architecture
