### ISSUE TITLE
Align wgt::ColorTargetState to GPUColorTargetState 

### ISSUE THREAD

**Issue by crowlKats** [gfx-rs/wgpu#1204]
`wgt::BlendState` is the same as `GPUBlendComponent` in the spec, while `BlendState` is a different dictionary in the spec.
Maybe restructure `wgt::ColorTargetState` to act like in the spec, so split blend_alpha & blend_color into a `wgt::GPUBlendState`.

**Comment by cwfitzgerald** [comment]
Is this still an issue after the pipeline refactor?

**Comment by kvark** [comment]
Pretty sure this is aligned now
