### ISSUE TITLE
Validation Error when a bind group isn't directly used in the entry point

### ISSUE THREAD

**Issue by nasso** [gfx-rs/wgpu#1208]
**Description**
I have a WGSL shader using a bind group with a single binding. The group is only used in a function called by my entry point function, but isn't referred to in my entry point directly.

I get a validation error saying that the `number of bindings in bind group descriptor (1) does not match the number of bindings defined in the bind group layout (0)`. Refactoring my shader code to read the value of the first binding group in the entry point function, and give it to the other function through an argument, fixes this error.

**Repro steps**
1. Create a render pipeline using the following shader, with the `vs_main` entry point.
    ```wgsl
    [[location(0)]]
    var<in> in_position: vec2<f32>;
    [[builtin(position)]]
    var<out> out_pos: vec4<f32>;
    
    [[block]]
    struct Canvas {
        size: vec2<f32>;
    };
    [[group(0), binding(0)]]
    var r_canvas: Canvas;
    
    fn project(p: vec2<f32>) -> vec2<f32> {
        return p / r_canvas.size;
    }
    
    [[stage(vertex)]]
    fn vs_main() {
        out_pos = vec4<f32>(project(in_position), 0.0, 1.0);
    }
    
    [[location(0)]]
    var<out> out_color: vec4<f32>;
    
    [[stage(fragment)]]
    fn fs_main() {
        out_color = vec4<f32>(1.0, 1.0, 1.0, 1.0);
    }
    ```
2. Try assigning a bind group to the `r_canvas` variable.

**Expected vs observed behavior**
I expect the code to run as if I had replaced the `project(in_position)` function call with the value it returns.
Instead, I get the following validation error:

```
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    number of bindings in bind group descriptor (1) does not match the number of bindings defined in the bind group layout (0)
```

**Extra materials**
N/A

**Platform**
- Windows 10
- `wgpu 0.7.0` from crates.io
- NVIDIA GeForce GTX 970 with GeForce Game Ready Driver 456.71

**Comment by kvark** [comment]
I believe this was fixed in https://github.com/gfx-rs/naga/pull/440
Is it an option for you to use wgpu-rs from github instead of crates? We'll pick up the fix in the next Naga update train (will be `gfx-11` tag).

**Comment by nasso** [comment]
Of course!

I just tried using wgpu-rs from github, and it doesn't seem to have fixed the issue.
That's probably because the master branch doesn't depend on naga's master branch, so I patched naga with [your analyzer branch](https://github.com/kvark/naga/tree/analyzer) and I confirm it fixed my issue :).
