### ISSUE TITLE
Invalid documentation link "Features::STORAGE_TEXTURE_ACCESS_READ_WRITE"

### ISSUE THREAD

**Issue by jakobhellermann** [gfx-rs/wgpu#1213]
The documentation for `StorageTextureAccess::ReadWrite` references `Features::STORAGE_TEXTURE_ACCESS_READ_WRITE`, which doesn't exist. Which feature should be enabled here?

https://github.com/gfx-rs/wgpu/blob/c71091b2e6b3636724196eaa314638079c490cb5/wgpu-types/src/lib.rs#L2575

**Comment by Systemcluster** [comment]
It [seems](https://github.com/gfx-rs/wgpu/blob/b1b44ca78c6a55e200f25da38f7b47b4c90928e9/wgpu-core/src/device/mod.rs#L1431) this now needs `TextureFormatFeatureFlags::STORAGE_READ_WRITE` which in turn needs `Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`.
