### ISSUE TITLE
SIGSEV when constructing (invalid) pipeline

### ISSUE THREAD

**Issue by Nehliin** [gfx-rs/wgpu#1216]
**Description**
As far as I can tell this is caused by me not knowing the limitations of glsl but I think regardless that we don't want incorrect behavior to result in a segmentation fault. Basically I tried to reuse an already compiled Spir-V fragment shader module but use a different entry point other than main (the other entry point had the same signature as main). This caused a segmentation fault in in [this call ](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/mod.rs#L2306), more specifically in ibnvidia-glvkpirv.so.450.102.04 which presumably is or belongs to my gpu driver

**Repro steps**
Create two piplines from the same precompiled fragment shader specifying different endpoints where one is called `main()` (works fine) and the other is called something else which should cause a segmentation fault during that pipeline construction. 

**Expected vs observed behavior**
Some sort of pipeline construction error panic message instead of a segmentation fault which are harder to debug.

**Platform**
Ubuntu 20.04 using libnvidia-glvkpirv.so.450.102.04

**Comment by cwfitzgerald** [comment]
Does this reproduce on the latest wgpu master?

**Comment by Nehliin** [comment]
@cwfitzgerald I don't seem to be able to repro this any longer even when not testing on latest master, I think I might have updated to wgpu-core 0.7.1 inbetween though so probably the fix was part of that, but I don't remember exactly. Anyways we can close this for now since it seems to have been fixed.
