### ISSUE TITLE
Segfault when using non-float texture sampler and WGSL

### ISSUE THREAD

**Issue by igowen** [gfx-rs/wgpu#1217]
**Description**
Setting up a sampler with `TextureSampleType::Uint` (or `Sint`) and `texture_2d<u32>` (or `<i32>`) causes a segfault. It's possible (and, indeed, very likely) that i'm doing something incorrectly, but it should result in an error, not a segfault.

**Repro steps**
I can reproduce this with minimal changes to the `cube` example: [patch](https://gist.github.com/igowen/faf0efa31525ae85793f089f958bdc42)

**Expected vs observed behavior**
Expected: either this works, or results in an error of some sort (validation or otherwise)
Observed: segmentation fault

**Platform**
OS: Linux (NixOS)
GPU: Intel
wgpu: 0.7
Backend: Vulkan

**Comment by kvark** [comment]
This is a part of missing expression validation in Naga.

**Comment by igowen** [comment]
specifically, the root cause here appears to be assigning `textureSample(...)` to a `vec4<f32>` when the sampled texture format is not `f32`.

**Comment by kvark** [comment]
Naga has expression validation now, closing
