### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by ylc-website** [gfx-rs/wgpu#1222]
Hi, I know this is a feature that has been requested a few times, and I'm wondering how close we are to WebGL support. I'd be keen to help out if I can.

**Comment by kvark** [comment]
See https://github.com/gfx-rs/wgpu-rs/wiki/Running-on-the-Web-with-WebGPU-and-WebGL
Also, there was a recent fix in https://github.com/gfx-rs/gfx/pull/3646, which is yet to reach wgpu-rs as a dependency.
If you want to help, set up the local dependency patch for gfx-rs and try to run the examples in the browser on WebGL, fixing issues in gfx-backend-gl as they arise.
