### ISSUE TITLE
Memory usage keeps growing on the backend of dx12 of AMD R5-4600U

### ISSUE THREAD

**Issue by linkstar0513** [gfx-rs/wgpu#1228]
On the version 0.7. I set ` WGPU_BACKEND="dx12"` and run the cube example `cargo run --example cube` on my notebook( the cpu is R5-4600U). The memory usage keeps growing fast. But it remained stable on the backend of vulkan.

On the other GPU like 1050Ti 1080TI, dx12 backend can work well.   There is an issue in `bevy` about this  [Memory usage keeps growing](https://github.com/bevyengine/bevy/issues/1488)

I think it's something wrong on the amd gpu when the backend is dx12.

**Comment by yzsolt** [comment]
I'm sure it's caused by the DX12 command allocator leak in `gfx`: https://github.com/gfx-rs/gfx/issues/3505
Haven't had time recently to implement a fix, but I think the issue is well documented if anyone would like to take a stab at it.
