### ISSUE TITLE
Pipeline creation does some shader validation, ignoring wgpu::ShaderFlags::VALIDATION

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#1230]
**Description**
During pipeline creation the call to `check_stage` does shader validation independently of the validation flag passed to `create_shader_module`. In particular, it checks for entry points in the shaders.

Hit in the context of https://github.com/gfx-rs/naga/issues/518

**Repro steps**
Don't have anything out-of-the-box runnable at the moment. May provider later if required.

**Comment by kvark** [comment]
Are you providing the WGSL source or the SPV? One of the recent changes was force-enabling validation if you provide the WGSL, since otherwise we can't generate anything from it.

**Comment by Wumpf** [comment]
Source provided as SPV.
Will provide more details and do some investigation myself later today

**Comment by Wumpf** [comment]
Quite odd! I was sure I was seeing this with VALIDATION turned on, but today I'm trying again with latest wgpu master and it works fine. Must have messed something up and it was still running with VALIDATION on.
Going to reopen if necessary
