### ISSUE TITLE
[meta] Discord server?

### ISSUE THREAD

**Issue by Birbe** [gfx-rs/wgpu#1232]
I think it'd be quite nice to have a Discord server for wgpu/WebGPU discussion and development. What do you think?

**Comment by kvark** [comment]
If this is meant to be a place for users to hang out and share knowledge (similar to our `#wgpu-users:matrix.org`), then there are no blockers there. It doesn't have to be an official server of the team in this case.
If it's meant to be official, we need to ensure that at least some people are committed to represent the team there (and it's unlikely going to be me). @grovesNL or @cwfitzgerald how do you feel about this?

**Comment by Birbe** [comment]
I think official would be better, as many many people use Discord and it's much more attractive to be able to get support or discuss something when you can just click a button and join the chat without having to create an a new (to you) service.

**Comment by grovesNL** [comment]
@Birbe there are already a few (unofficial) Discord servers/channels that people use for WebGPU and wgpu discussion:
- Rust Programming Language Community Server (mostly in #games-and-graphics)
- Game Development in Rust (multiple channels)
- Graphics Programming (mostly in #webgpu)

I'm a bit hesitant to add our own Discord server unless those channels aren't working well for some reason.

**Comment by Birbe** [comment]
Fair enough, I wasn't able to easily find any with a Google search, but thanks for the resources

**Comment by grovesNL** [comment]
That’s a good point, maybe we could make this more discoverable by mentioning these resources somewhere (next a link to our official Matrix channels), e.g. in the README or somewhere else

**Comment by Birbe** [comment]
Sounds good!
