### ISSUE TITLE
QueueSubmitError and QueueWriteError not exported

### ISSUE THREAD

**Issue by lucacasonato** [gfx-rs/wgpu#1233]
**Description**

`wgpu_core::device::queue::QueueSubmitError` and 
`wgpu_core::device::queue::QueueWriteError` are not accessible publicly because `wgpu_core::device::queue` is private.

These errors are returned from `queue_write_buffer`, `queue_write_texture`, and `queue_submit`.

**Platform**
wgpu_core: 0.7.0
rustc: 1.50.0 (cb75ad5db 2021-02-10)

**Comment by kvark** [comment]
This is fixed in master - the `queue` module is public. For the purposes of `deno`, I assume you need to use the `master` anyway, so no need to publish an update to crates?

**Comment by lucacasonato** [comment]
We can't use master, because we only allow crates from crates.io. (We can't publish to crates.io if we use crates from GitHub directly).

**Comment by kvark** [comment]
Published wgpu-core-0.7.1 in #1234
