### ISSUE TITLE
Per-object uniform data

### ISSUE THREAD

**Issue by cloudhead** [gfx-rs/wgpu#125]
I may be misunderstanding the API, but it doesn't seem like it's possible to have uniform data (eg. transformations) per object/draw call. I'm *guessing* this can be done if offsets were passed in to `RenderPass::set_bind_group`:
```rust
            pass.raw.bind_graphics_descriptor_sets(
                &&pipeline_layout_guard[pipeline_layout_id].raw,
                index as usize,
                bind_groups,
                &[], // <--------- here
            );
```
or if there was access to push constants.

Is there another way to have per-draw uniform data?

I'm refering to this for vulkan: https://github.com/nvpro-samples/gl_vk_threaded_cadscene/blob/master/doc/vulkan_uniforms.md

**Comment by kvark** [comment]
@cloudhead the group has not yet accepted any push constants semantics. In short, it wasn't clear how to best expose them, and in all cases we've seen using push constants wasn't required to get the job done. One workaround is to use the dynamic offsets like you mentioned. The draft spec does have them: https://github.com/gpuweb/gpuweb/blob/15dadf3f218f1c51ff31ce1976653a99189b41d1/spec/index.bs#L595

wgpu-rs hasn't been updated to reflect that yet. It has to be done before we release 0.3.

**Comment by cloudhead** [comment]
Ah amazing! Yeah I don't think push constant support is necessary if we have dynamic offsets. Good to know they are coming :+1: 

In the time being I'll try to work around it with vertex buffers :thinking:

**Comment by cloudhead** [comment]
I'm happy to look into it also.

**Comment by kvark** [comment]
You are welcome to make a PR introducing the dynamic offsets, if willing to help ;)
