### ISSUE TITLE
'internal error: entered unreachable code' on Windows if the vulkan driver is unable to load

### ISSUE THREAD

**Issue by francesco-cattoglio** [gfx-rs/wgpu#1261]
**Description**
When trying to open a wgpu program I wrote, two of my users reported the following error:
```
C:\Users\UserName\Desktop\franzplot_replay>.\trace_replay tracing_colored_points
[25.594451 ERROR]()(no module):
GENERAL [Loader Message (0x0)] : terminator_CreateDevice: Failed in ICD C:\WINDOWS\System32\DriverStore\FileRepository\nvhm.inf_amd64_cf870258cf3f0c7f\.\nvoglv64.dll vkCreateDevicecall
object info: (type: INSTANCE, hndl: 0x196ad150f60)
 
[25.599339 ERROR]()(no module):
GENERAL [Loader Message (0x0)] : vkCreateDevice:  Failed to create device chain.
object info: (type: INSTANCE, hndl: 0x196ad150f60) 
 
thread 'main' panicked at 'internal error: entered unreachable code', C:\Users\Franz\.cargo\git\checkouts\gfx-e86e7f3ebdbc4218\cd96e77\src\backend\vulkan\src\physical_device.rs:781:30
```

**Repro steps**
This happened when trying to replay an API trace, but I think this would happen every time the Vulkan backend is used on any PC with some driver issues.

**Expected vs observed behavior**
The failure should be handled in some way, instead of the panic on a "entered unreachable code".

**Extra materials**
Unfortunately I have no extra material for now, I can ask my user to provide a stacktrace if needed, but I do not have access to the actual machine where the error arised.

**Platform**
I only have the following informations for now:
Windows 10,
Laptop with integrated intel graphics, from "2015 or earlier".

**Comment by kvark** [comment]
Thank you for filing!
Let's see if it's still a problem after https://github.com/gfx-rs/gfx/pull/3674 arrives to wgpu

**Comment by kvark** [comment]
Considering this fixed
