### ISSUE TITLE
Render pass validation error

### ISSUE THREAD

**Issue by HalfVoxel** [gfx-rs/wgpu#1271]
**Description**
Three simple render passes cause a validation error:

```rust
encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
    label: Some("some msaa pass"),
    color_attachments: &[wgpu::RenderPassColorAttachmentDescriptor {
        attachment: multisample_target,
        ops: wgpu::Operations {
            load: wgpu::LoadOp::Clear(wgpu::Color::WHITE),
            store: true,
        },
        resolve_target: None,
    }],
    depth_stencil_attachment: None,
});

encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
    label: Some("resolve pass pass"),
    color_attachments: &[wgpu::RenderPassColorAttachmentDescriptor {
        attachment: multisample_target,
        ops: wgpu::Operations {
            load: wgpu::LoadOp::Load,
            store: true,
        },
        resolve_target: Some(framebuffer_target),
    }],
    depth_stencil_attachment: None,
});

encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
    label: Some("non-msaa pass"),
    color_attachments: &[wgpu::RenderPassColorAttachmentDescriptor {
        attachment: framebuffer_target,
        ops: wgpu::Operations {
            load: wgpu::LoadOp::Load,
            store: true,
        },
        resolve_target: None,
    }],
    depth_stencil_attachment: None,
});
```

```
VALIDATION [VUID-VkRenderPassBeginInfo-renderPass-00904 (861854874)] : Validation Error: [ VUID-VkRenderPassBeginInfo-renderPass-00904 ] Object 0: handle = 0x2f000000002f, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0x2b000000002b, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x335edc9a | vkCmdBeginRenderPass(): RenderPasses incompatible between render pass w/ VkRenderPass 0x2f000000002f[] and framebuffer w/ VkRenderPass 0x2b000000002b[] Attachment 0 is not compatible with 0: They have different samples.. The Vulkan spec states: renderPass must be compatible with the renderPass member of the VkFramebufferCreateInfo structure specified when creating framebuffer (https://vulkan.lunarg.com/doc/view/1.2.170.0~rc2/linux/1.2-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-renderPass-00904)
object info: (type: RENDER_PASS, hndl: 51677046505519), (type: RENDER_PASS, hndl: 47278999994411)
```

**Repro steps**

Full code: https://github.com/HalfVoxel/wgpu-replicate/commit/7ab16e4784e7bd88880a1a7bf3e573ade373ba09

**Expected vs observed behavior**
Either a wgpu error or no validation errors. In this case I *think* it shouldn't lead to any validation errors.

**Extra materials**
Api trace: https://github.com/HalfVoxel/wgpu-replicate/raw/de60de77987234f00c25638d3e7cc293969124ed/trace.zip

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
wgpu` 0.7
platform: 
```
Ubuntu 20.04.2 LTS
Intel® Core™ i9-9900K CPU @ 3.60GHz × 16 
NVIDIA Corporation GM204 [GeForce GTX 970]
```

CC: @kvark

**Comment by kvark** [comment]
Replaying on v0.7 gives me a WebGPU validation error:
> `Err` value: RenderPassError { scope: Pass((0, 1, Metal)), inner: InvalidSampleCount(8) }'

Are you not seeing this when replaying? I wonder why it's not visible when running your case.

**Comment by HalfVoxel** [comment]
Nope. I'm not seeing that.

**Comment by kvark** [comment]
Possible that we are just not validating the sample count properly in v0.7.

**Comment by HalfVoxel** [comment]
What is the bug in my code though? From what I can tell this should all work. But then again I am not that familiar with all rules.

**Comment by kvark** [comment]
WebGPU today doesn't like any sample count other than 1 or 4. It's overly strict, but we haven't found a good way to expose the rest yet.

**Comment by HalfVoxel** [comment]
Ah. I'm getting the same validation error with sample count of 4 though.
[trace.zip](https://github.com/gfx-rs/wgpu/files/6157667/trace.zip)

**Comment by HalfVoxel** [comment]
I saw that you merged a fix for this. However, I can't quite figure out if the fix will:
1. Make this usage log a wgpu validation error?
2. Make this usage work without any vulkan validation errors?

**Comment by HalfVoxel** [comment]
Thanks! :)
