### ISSUE TITLE
Wrong result for `atan2(1.0, 0.0)` in compute shader on MacOS 11

### ISSUE THREAD

**Issue by francesco-cattoglio** [gfx-rs/wgpu#1277]
**Description**
As per title, the `atan2` function returns a wrong result for specific inputs. In particular, I was able to consistently get wrong results for `atan2(1.0, 0.0)` under MacOS.

**Repro steps**
To reproduce, refer to this repository: https://github.com/francesco-cattoglio/compute_atan2_testing
It is a modified `hello-compute` example from `wgpu-rs`. To use it, pass in floats in pairs that represent the x and y coords to be fed to the `atan2()` function, or run it without inputs to test the following 3 pairs: (0.01, 1.0), (0.0, 1.0), (-0.01, 1.0).

**Expected vs observed behavior**
When computing `atan2(1.0, 0.0)` I would expect the returned angle to be `pi/2`, but the actual returned result is `pi/2 + pi`. As a bonus, `atan2(1.0, -0.0)` correctly returns `pi/2`. I have the feeling this might be a bug in Metal, but I am reporting it here first in the hope of getting some help with investigating it.

**Extra materials**
Since the shader is written in GLSL, the function that I call is actually named `atan()`, but when the shader gets translated to MSL, this is the output:
```
[0.136047 DEBUG]()(no module): SPIRV-Cross generated shader:
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PrimeIndices
{
    float values[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

kernel void main0(device PrimeIndices& _22 [[buffer(0)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint index = gl_GlobalInvocationID.x;
    float x_coord = _22.values[2u * index];
    float y_coord = _22.values[(2u * index) + 1u];
    float atan2_angle = atan2(y_coord, x_coord);
    _22.values[2u * index] = atan2_angle;
    _22.values[(2u * index) + 1u] = atan2_angle;
}
```
Which shows clearly that the `atan2` function is correctly called. I was also able to translate the shader via Naga, and the result is pretty much the same:
```
[0.129823 DEBUG]()(no module): Naga generated shader:
#include <metal_stdlib>
#include <simd/simd.h>

typedef uint type;

typedef metal::uint3 type1;

typedef float type2;

typedef type2 type3[1];

struct PrimeIndices {
    type3 values;
};

typedef int type4;

kernel void main1(
    type1 gl_GlobalInvocationID [[thread_position_in_grid]],
    device PrimeIndices& _ [[buffer(0)]]
) {
    type index;
    type2 x_coord;
    type2 y_coord;
    type2 atan2_angle;
    index = gl_GlobalInvocationID[0];
    x_coord = _.values[2 * index];
    y_coord = _.values[2 * index + 1];
    atan2_angle = metal::atan2(y_coord, x_coord);
    _.values[2 * index] = atan2_angle;
    _.values[2 * index + 1] = atan2_angle;
}
```
I have no idea on how to shed any light on what is going on. Any suggestion is welcome.

**Platform**
I was able to reproduce this bug on 2 different MacOS Big Sur laptops, both with Intel processor, one model from 2020, the other one a bit older. To reproduce I used `wgpu-rs` rev `517ce3e`

**Comment by kvark** [comment]
The spec says the following:
<img width="403" alt="Screen Shot 2021-03-23 at 13 24 20" src="https://user-images.githubusercontent.com/107301/112190149-1d439880-8bdb-11eb-8e4c-f8c31bccf182.png">

So it looks like they *always* compute it via `y/x` ratio, one way or another.
And their last sentence turns out to be the case when "x == 0.0".

Created https://github.com/gfx-rs/naga/issues/604 to follow-up in Naga.

**Comment by Diggsey** [comment]
Which spec is that? It seems very broken, for two reasons...

1) This case (y=1, x=0) is not covered by any line in the spec.
2) The entire point of `atan2` being a distinct function from `atan` is to compute the angle between two points without any corner cases...

**Comment by kvark** [comment]
it's Metal Shading Language spec. Clearly, this case is not handled well.
I'm also going to file an issue to Apple, just in case.
