### ISSUE TITLE
WGSL parsing failed with no detail.

### ISSUE THREAD

**Issue by 5nefarious** [gfx-rs/wgpu#1295]
Ever since I updated to master, I've been getting the following error:
```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
    Failed to parse WGSL


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/REDACTED/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/09d6be1/src/backend/direct.rs:1889:5
```
There's no detail on which line in the shader or even which shader caused the error. I've been able to fix a number of these errors by referencing the examples and by trial and error, but now I'm stuck. I believe this is the shader file that's causing the issue:
```wgsl
struct VertexOutput {
    [[builtin(position)]] position: vec4<f32>;
    [[location(0)]] tex_coords: vec2<f32>;
};

[[stage(vertex)]]
fn vs_main([[builtin(vertex_index)]] index: u32) -> VertexOutput {
    const triangle = array<vec2<f32>, 3u>(
        vec2<f32>(-1.0, -1.0),
        vec2<f32>( 3.0, -1.0),
        vec2<f32>(-1.0,  3.0)
    );
    var out: VertexOutput;
    out.position = vec4<f32>(triangle[index], 0.0, 1.0);
    out.tex_coords = 0.5 * triangle[index] + vec2<f32>(0.5, 0.5);
    return out;
}

[[group(0), binding(0)]]
var r_color: texture_2d<f32>;
[[group(0), binding(1)]]
var r_sampler: sampler;

[[stage(fragment)]]
fn fs_main(in: VertexOutput) -> [[location(0)]] vec4<f32> {
    return textureSample(r_color, r_sampler, in.tex_coords);
}
```

I've tried stepping through with a debugger, but it seems to be parsing the shader just fine and then failing inside the `Device.raw.create_shader_module_from_naga()` method. The only thing I could find that seemed off is that the `naga::ShaderStage` for the entry point is _always_ set to `Vertex`, even for the fragment and compute shaders.

**Comment by kvark** [comment]
Marked as blocked upstream - https://github.com/gfx-rs/naga/issues/635

**Comment by 5nefarious** [comment]
Changed the array declaration and now it works:
```wgsl
var triangle: array<vec2<f32>, 3u> = array<vec2<f32>, 3u>(
    vec2<f32>(-1.0, -1.0),
    vec2<f32>( 3.0, -1.0),
    vec2<f32>(-1.0,  3.0)
);
```

**Comment by kvark** [comment]
yes, right. This would be indexing a local variable, which is more flexible than indexing constants
