### ISSUE TITLE
[WebGL] strange rendering on Firefox.

### ISSUE THREAD

**Issue by VincentFTS** [gfx-rs/wgpu#1298]
Here is what I get in Firefox for the cube example.
![cube](https://user-images.githubusercontent.com/4997068/113163346-5c5b9480-9240-11eb-8318-897cadc6b957.png)

Seems the texture memory is shifted …
Tested on master branch.
No problemo with chromium.

**Comment by kvark** [comment]
Interesting. So this is WebGL? And Firefox behaves differently?
You might want to file it to https://bugzilla.mozilla.org/ then, but I'd bet it's a problem with gfx-backend-gl, just surprised it's not showing up in Chrome.
You could try SpectreJS and investigate why the rendering is bonkers.

**Comment by VincentFTS** [comment]
This is fixed in the current nightly, so wait&see !
