### ISSUE TITLE
example programs give fatal errors: "unknown type name 'uint'"

### ISSUE THREAD

**Issue by blakej11** [gfx-rs/wgpu#1299]
I just pulled down the `wgpu-rs` repository and built it on my laptop running MacOS 10.13.6 (which supports Metal 2.0). I have XCode 10.1 installed, and a built-in Intel Iris 550 GPU.

Several of the examples from `wgpu-rs` (namely `boids`, `hello-compute`, `hello-triangle`, `mipmap`, `shadow`, and `skybox`) gave me fatal errors when I tried to run them, mostly starting with the following:

```
wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
    Internal error: Error compiling the shader: Compilation failed:

program_source:13:9: error: unknown type name 'uint'; did you mean 'int'?
typedef uint type;
        ^~~~
        int
```

Looking at the line numbers of subsequent errors, it appears that this came from some code that was prepended to the WGSL file being compiled (e.g. `examples/boids/compute.wgsl` in this case).

I gathered some more data after discussion in the wgpu-users Matrix forum:

- I ran `boids` with logging turned up to TRACE, took the generated shader file from the log, and compiled it with `xcrun metal test.metal`. That did not show the `uint` error message (or any error at all).
- `opensnoop` showed that `xcrun metal` was compiling using headers from `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/902.1/include/metal/`. In contrast, `boids` was apparently doing the compilation via `MTLCompilerService`, which was getting its headers from `/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3802/Libraries/lib/clang/802.4/include/metal/` (and, in particular, from `metal_stdlib.2_0.fast-relaxed-math-64.pch` within that directory).

Happy to gather more data if it would be helpful for diagnosis.

**Comment by kvark** [comment]
I wonder if on that tools version the `uint` typedef ends up inside `metal` namespace... We don't import it, but most do, so Apple wouldn't necessarily notice this.

**Comment by kvark** [comment]
Let's see if https://github.com/gfx-rs/naga/pull/638 (could be tested with a cargo patch) fixes this.
