### ISSUE TITLE
Naga path is flickering in imgui-wgpu-rs with Vulkan backend

### ISSUE THREAD

**Issue by qthree** [gfx-rs/wgpu#1316]
I've updated `imgui-wgpu-rs` to latest master and it works OK with Dx11 and Dx12 backends, but with Vulkan backend there's flickering glitch when some triangles disappear in random fashion, which somewhat looks like Z-fighting (but `depth_stencil: None,` so it shouldn't be possible).
I went back a week and managed to pin down exact commit that introduced it: gfx-rs/wgpu-rs#826 
So, if I enable "cross" feature manually on the latest master this issue is also goes away.
Tested on Windows 10 with gtx840.
![image](https://user-images.githubusercontent.com/9898555/114026715-c27b9380-98a0-11eb-834f-67baeab04d48.png)
To reproduce this bug you can use [my imgui-gpu-rs fork](https://github.com/qthree/imgui-wgpu-rs/tree/track_wgpu_master) with `track_wgpu_master` branch. Just execute `cargo run --example hello_world`.

**Comment by kvark** [comment]
Fixed now in naga-0.4.1
