### ISSUE TITLE
Crashes on cmd_begin_render_pass for Windows 10

### ISSUE THREAD

**Issue by mvlabat** [gfx-rs/wgpu#1317]
**Description**

`wgpu-rs` examples crash for me. `hello-triangle` example works, but `shadow`, for instance, doesn't. I don't have any guesses about what's going on on the lower level, so I'm here just to report that something is wrong. I discovered this when trying to upgrade to Bevy 0.5, which now uses wgpu 0.7, and every example there stopped working as well. I've attached the console output and Clion's debugger stack (whichever debugger it uses internally). If there are any other details I could provide, let me know - I'll be happy to do so.

I can reproduce the problem both on `master` and `v0.7` branches.

**Repro steps**
Run `shadow` example (likely, there are more that crash) from the `wgpu-rs` repo.

**Expected vs observed behavior**
Shouldn't crash.

**Extra materials**

```
D:/Programming/wgpu-rs/target/debug/examples/shadow.exe
Using NVIDIA GeForce RTX 2080 (Vulkan)
[2021-04-10T09:19:28Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-03209 (0x0)] : VkRenderPassBeginInfo: Image view #0 created from an image with flags set as 0x400, but image info #0 used to create the framebuffer had flags set as 0x0 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView of an image created with a value of VkImageCreateInfo::flags equal to the flags member of the corresponding element of VkFramebufferAttachmentsCreateInfoKHR::pAttachments used to create framebuffer (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03209)
    object info: (type: RENDER_PASS, hndl: 0xc1547b000000003e)
    
[2021-04-10T09:19:28Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-03210 (0x0)] : VkRenderPassBeginInfo: Image view #0 created from an image with usage set as 0x11, but image info #0 used to create the framebuffer had usage set as 0x10 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView of an image created with a value of VkImageCreateInfo::usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachments used to create framebuffer (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-03210)
    object info: (type: RENDER_PASS, hndl: 0xc1547b000000003e)
    
Exception: Exception 0xc000041d encountered at address 0x7ffcbec86b59
```

Stack:
[paste.txt](https://github.com/gfx-rs/wgpu/files/6289578/paste.txt)

![image](https://user-images.githubusercontent.com/2943388/114265334-e8b44700-99f8-11eb-8d7f-bf0caa891206.png)

**Platform**
OS: Microsoft Windows 10 Pro (10.0.19041 Build 19041)
GPU: NVIDIA GeForce RTX 2080
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz

**Comment by mvlabat** [comment]
Upgrading Vulkan SDK from `1.2.131.2` to `1.2.170.0` has fixed the issue.

**Comment by kvark** [comment]
It appears to be a crash in validation layers, so nothing we do wrong.

**Comment by toastmod** [comment]
Hi, I think I'm having this issue. This might seem like a dumb question but how does one upgrade their Vulkan SDK for wgpu? I was thinking the SDK would come from the wgpu crate's vulkan backend code or something like that.
