### ISSUE TITLE
Annotating functions with [profiling::function]

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1318]
We aren't currently doing this, maybe we should?

**Comment by kvark** [comment]
Also, "register_thread" and "finish_frame" could be useful.

**Comment by cwfitzgerald** [comment]
Re the proc macro: there doesn't seem to be much benefit from using it over what we're doing now, and now we can customize the name of the scope to match with the wgpu-rs function name (vs the wgpu-core function)

Re register thread/finish frame: These are both things that imo should be handled by the user. They may have some work to do after presentation that they want to include in a frame, and we don't actually own any threads, so we shouldn't be registering any of them.

**Comment by kvark** [comment]
agreed, let's close it then
