### ISSUE TITLE
Queue `write_buffer` issue with Vulkan backend on NVidia

### ISSUE THREAD

**Issue by simast** [gfx-rs/wgpu#1323]
After upgrading wgpu from 0.7 to latest master I am seeing really strange issue with `Queue::write_buffer()` calls. This issue happens only when Vulkan backend is used - cannot reproduce with DX12 and Metal backends.

Some background how I render a scene.

1. When renderer starts I pre-allocate a large buffer using `Device::create_buffer()`. I do this to not allocate memory during subsequent render calls.
2. When changes are detected I update vertex instance data in this buffer using `Queue::write_buffer()` calls.
3. I then render vertices using instance drawing with `RenderPass::draw_indexed()`.

The strange issue is that when I write, for example, 5 items with `write_buffer()` - only 4 are actually written to the buffer. So one item is lost somehow.. Here are some screenshots:

Debugger active just before `write_buffer()` call showing 5 items:

![debugger-output](https://user-images.githubusercontent.com/433527/113737240-87455d00-9706-11eb-89dd-741b5222f290.png)

And afterwards RenderDoc view for the same buffer showing only 4 items.

![renderdoc-output](https://user-images.githubusercontent.com/433527/113737620-ddb29b80-9706-11eb-8d2b-6a65034d29cd.png)

Since this started only after upgrading wgpu and only while Vulkan backend is used - I don't think the bug is in my code. There must be some issue in wgpu or any dependencies?

**Comment by kvark** [comment]
Reported to NVidia level 2 support team, ticket 210412-000661
Also added to our driver [issue list](https://github.com/gfx-rs/wgpu/wiki/Known-Driver-Issues#nvidia--vulkan)

**Comment by cwfitzgerald** [comment]
Closing as out of date
