### ISSUE TITLE
Missing draw op, depending on subsequent draw in render pass

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#1326]
Following discussion with @kvark in #1314, I have this report:

[kas-gallery-trace.tar.gz](https://github.com/gfx-rs/wgpu/files/6311307/kas-gallery-trace.tar.gz)

There *should* be a squashed image of the Ferris rustacean drawn at the bottom; there isn't.

But: comment out lines 2068..=2085 of the trace, and it appears (while some other stuff isn't drawn).

Code is here, for now: https://github.com/kas-gui/kas/pull/184

**Comment by kvark** [comment]
Looks like you are just overwriting the ferris? I can change the instance count to 0 (at line 2082), and the ferris is still there. This means, it's not about anything `wgpu` does, it's just about what this draw call does.

**Comment by dhardy** [comment]
Confirmed, my app is drawing the background over the image (a hack added to set the depth buffer which I forgot about).

Thanks for teaching me some debugging tools!
