### ISSUE TITLE
[meta] Performance analysis on 3000 cubes

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1338]
We've had the first round of benchmarks in https://github.com/gpuweb/gpuweb/discussions/1640#discussioncomment-616344 . This is an extreme case, it's not idiomatic WebGPU, and is pretty naive. It stresses command encoding and resource tracking most.

I've also talked to a few folks within Mozilla about the recorded profiles. Here I'd like to post the conclusions (to be extended):

Client side:
  1. growing the command vector (in a render pass) is slow
    - try `copyless`?
    - reserve space or re-use the previous lists?
    - reduce the size of `RenderCommand`
  2. bincode serialization is slow
    - try [rkyv](https://github.com/djkoloski/rkyv)
    - convince it to do 2 passes: to figure out the size, and then to avoid checking it

Server side:
  1. Add performance markers (for Gecko profiler)
    - can we integrate `profiling` with Gecko?
  2. `RefCount` cloning is heavy
    - can we integrate refcounts into the `Storage` as atomic ints?
  3. `Hub::get()` ends up being expensive
    - let's check the assembly to see if anything is wrong there

**Comment by cwfitzgerald** [comment]
So much has changed this isn't really relevant anymore.
