### ISSUE TITLE
Try out rkyv for pass serialization

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1345]
As a part of performance action plan in #1338, we should try [rkyv](https://github.com/djkoloski/rkyv). See [benchmarks](https://github.com/djkoloski/rust_serialization_benchmark).

I imagine it to be an unconditional dependency (!), replacing `serial-pass` feature. It would also replace some of the `serde::Serialize` by `rkyv::Serialize` on our pass-related types.

The motivation for it is - having a single optimized path for command recording. With zero-cost deserialization, operating on the serialized form should be nearly free in cost. As for the serialization cost - see the arena idea below, which is expected to be faster than the vector growing we have today.

Why `rkyv`? In Gecko, we need to be able to get `[u8]` in order to write it into shared memory during serialization. And then we'd want to read the data from that shmem on the GPU side, preferably not copying it around. Currently, we have `Vec` growing followed by `bincode`. Each stage grows heap, reallocates, and copies data around. This shows up in profiles.

For serialization, we'd need to implement our own serializer, similar to `AlignedSerializer`, but using the allocation scheme similar to `TypedArena`. That is, it will have a sequence of chunks, each exponentially larger than the previous one. Chunks are never resized.

Edit: it appears to lack a way to stream-encode commands. So today it would still require us to have `Vec<Command>`, which makes it much less of a solution, unfortunately. We'll track https://github.com/djkoloski/rkyv/issues/109

Edit2: we'll have to enable `validation` feature in Gecko, but not in wgpu-rs, which is kind of elegant. I just hope that the cost of this feature is not going to blow all the perf gains away. Turns out `rkyv` is still a few times faster than `bincode` even with this feature enabled.

Edit3: issue about serialization perf and general feedback - https://github.com/djkoloski/rkyv/issues/108

Things to consider:
  - safety of `rkyv` - needs an audit!
  - performance metrics
  - dependency tree
  - compile times
  - reliance on `rkyv` authors to help us with issues

**Comment by delbonis** [comment]
>needs an audit!

As I understand it, rkyv has an issue where data can be leaked because of unused bytes in cases of types like this:

```rust
enum Foo {
    Bar,
    Baz([u8; 32])
}
```

**Comment by kvark** [comment]
There is a new alternative - https://github.com/zakarumych/alkahest
Although, the whole thing is blocked on @pythonesque epic change of removing the Hubs.

**Comment by cwfitzgerald** [comment]
This will soon-ish not have any serialization at all.
