### ISSUE TITLE
Wgpu 0.8 "Failed to parse WGSL" when passing wgpu::include_spirv!() to function

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/wgpu#1359]
I'm working on migrating my tutorial to wgpu version 0.8 and my code panics when I try to pass the result of the `include_spirv` macro to a function. Here's the function in question.

```rust
fn create_render_pipeline(
    device: &wgpu::Device,
    layout: &wgpu::PipelineLayout,
    color_format: wgpu::TextureFormat,
    depth_format: Option<wgpu::TextureFormat>,
    vertex_layouts: &[wgpu::VertexBufferLayout],
    vs_src: wgpu::ShaderModuleDescriptor,
    fs_src: wgpu::ShaderModuleDescriptor,
) -> wgpu::RenderPipeline {
    let vs_module = device.create_shader_module(&vs_src);
    let fs_module = device.create_shader_module(&fs_src);

    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some("Render Pipeline"),
        layout: Some(&layout),
        vertex: wgpu::VertexState {
            module: &vs_module,
            entry_point: "main",
            buffers: vertex_layouts,
        },
        fragment: Some(wgpu::FragmentState {
            module: &fs_module,
            entry_point: "main",
            targets: &[wgpu::ColorTargetState {
                format: color_format,
                blend: Some(wgpu::BlendState {
                    alpha: wgpu::BlendComponent::REPLACE,
                    color: wgpu::BlendComponent::REPLACE,
                }),
                write_mask: wgpu::ColorWrite::ALL,
            }],
        }),
        primitive: wgpu::PrimitiveState {
            topology: wgpu::PrimitiveTopology::TriangleList,
            strip_index_format: None,
            front_face: wgpu::FrontFace::Ccw,
            cull_mode: Some(wgpu::Face::Back),
            // Setting this to anything other than Fill requires Features::NON_FILL_POLYGON_MODE
            polygon_mode: wgpu::PolygonMode::Fill,
            // Requires Features::DEPTH_CLAMPING
            clamp_depth: false,
            // Requires Features::CONSERVATIVE_RASTERIZATION
            conservative: false,
        },
        depth_stencil: depth_format.map(|format| wgpu::DepthStencilState {
            format,
            depth_write_enabled: true,
            depth_compare: wgpu::CompareFunction::Less,
            stencil: wgpu::StencilState::default(),
            bias: wgpu::DepthBiasState::default(),
        }),
        multisample: wgpu::MultisampleState {
            count: 1,
            mask: !0,
            alpha_to_coverage_enabled: false,
        },
    })
}
```

I'm not sure why wgpu is trying to interpret the spirv as wgsl in this case. It may be that there is a typo in the spirv validation, and wgpu is having trouble parsing the spirv that I'm passing in. The spirv I'm passing in is coming from `shaderc` currently, so I'm not sure that's the issue.

I've attached the link to the code and a zip of the trace. Let me know if you need any more details.

Full code: https://github.com/sotrh/learn-wgpu/tree/0.8/code/intermediate/tutorial10-lighting
Panicking file: https://github.com/sotrh/learn-wgpu/blob/0.8/code/intermediate/tutorial10-lighting/src/main.rs
Vertex shader: https://github.com/sotrh/learn-wgpu/blob/0.8/code/intermediate/tutorial10-lighting/src/shader.vert

[spv_wgsl_bug_trace.zip](https://github.com/gfx-rs/wgpu-rs/files/6410700/spv_wgsl_bug_trace.zip)

**Comment by kvark** [comment]
It's a SPIR-V parsing error, but the message is wrong saying that it's about WGSL.
You can get more info by enabling `RUST_LOG=warn`.
You can work around by not passing `VALIDATION` flag in (so not using `include_spirv!`).
In the meantime, we'll work on better error messages.

**Comment by cwfitzgerald** [comment]
Closing as out of date, feel free to re-open if this is still an issue on 0.10
