### ISSUE TITLE
Missing validation error that does show up in renderdoc

### ISSUE THREAD

**Issue by mtsr** [gfx-rs/wgpu#1361]
WGPU version 0.7.1.

I just found a validation error in renderdoc that doesn't show up as a wgpu warning:

`Core 16676 06:52:12 vk_core.cpp(3830) Warning [VUID-vkCmdDrawIndexed-None-02699] Validation Error: [ VUID-vkCmdDrawIndexed-None-02699 ] Object 0: handle = 0x6390b9000000030d, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa44449d4 | VkDescriptorSet 0x6390b9000000030d[] encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in binding gfx-rs/wgpu-rs#15 index 0 requires an image view of type VK_IMAGE_VIEW_TYPE_CUBE_ARRAY but got VK_IMAGE_VIEW_TYPE_2D_ARRAY. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-02699)`

Exactly what it says on the tin, my view is incorrect for how I'm binding it.

If you need any other info, please let me know.

**Comment by kvark** [comment]
Needs to be checked on latest master.

**Comment by mtsr** [comment]
0.8 indeed gives an error! Thanks!
