### ISSUE TITLE
Support dvec2 (double precision) in shaders

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#1362]
This time I have an actual bug (regression) to report!
```
$ cargo run --example mandlebrot
   Compiling kas-wgpu v0.7.0 (/home/dhardy/projects/gui/kas/kas-wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 12.42s
     Running `/home/dhardy/.cache/cargo/debug/examples/mandlebrot`
[2021-05-01T08:55:18Z INFO  kas_wgpu::shared] Using graphics adapter: AMD RADV POLARIS10 (ACO)
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `mandlebrot/shader.frag.spv`
    Failed to parse WGSL
```
See [this PR](https://github.com/kas-gui/kas/pull/193) ([this commit](https://github.com/kas-gui/kas/pull/193/commits/a8139e1db9f46a61eda66e46f6cdeddc8e153d27) — [this shader](https://github.com/kas-gui/kas/blob/a8139e1db9f46a61eda66e46f6cdeddc8e153d27/kas-wgpu/examples/mandlebrot/shader.frag)): `mandlebrot/shader.frag.spv` fails to load.

Cause: use of `dvec2` / `double` in shader. Confirmed that dropping everything to 32-bit floats works.

This was working in v0.7.

**Comment by dhardy** [comment]
Sorry for the delay: I actually [enabled that flag three weeks ago](https://github.com/kas-gui/kas/commit/e61cea1284872f3ef6265e59f42549dce8a353c9), before updating to v0.8.

**Comment by kvark** [comment]
Right, we haven't connected this feature to the validator yet. We should!

**Comment by kvark** [comment]
There are more issues preventing f64 to work properly on Naga side. Basically, it's a medium-sized chunk of work to support. I'm looking into it.

**Comment by kvark** [comment]
Got your shader working with https://github.com/gfx-rs/naga/pull/839
