### ISSUE TITLE
Different behavior between Intel/Vulkan/Linux and Nvidia/Vulkan/Linux - mesh drawing

### ISSUE THREAD

**Issue by ashpil** [gfx-rs/wgpu#1366]
I have one Intel/Vulkan/Linux machine (i7-1065G7 integrated graphics), where, as far as I can tell, my program works perfectly. On another machine of mine, an Nvidia/Vulkan/Linux machine (GTX 1080), my program doesn't work - the meshes are just not being drawn, but as far as I can tell, everything else is identical.

This weird behavior is in Renderdoc as well:
![image](https://user-images.githubusercontent.com/9152478/117318179-2f5e5b00-ae58-11eb-814d-10ce81640d5e.png)
As you can see, it says the vertex positions are set to `0.0, 0.0, 0.0, 0.0` - yet in the shader debugger, they are clearly set to a value.

Unfortunately it doesn't seem Renderdoc supports Wayland, so I can't run it on my working machine (this is another difference between working/non-working - working machine is on Wayland, non-working is on X11, though I can't see this causing the issue).

The one different thing between this build and a working-everywhere build stems from me multiplying the vertex position by another matrix, which is constructed from vertex attributes and a matrix array uniform. 

[API trace for working, Intel/Vulkan/Linux machine](https://github.com/gfx-rs/wgpu/files/6435489/trace.zip)
[API trace for non-working, Nvidia/Vulkan/Linux machine](https://github.com/gfx-rs/wgpu/files/6435493/trace.1.zip)

Please let me know if this difference between platforms is considered a wgpu issue/other avenues I might use to debug.

**Comment by kvark** [comment]
Looks like we are causing this error here:
> VALIDATION [VUID-VkGraphicsPipelineCreateInfo-layout-00756 (0x45717876)] : Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-layout-00756 ] Object 0: handle = 0x55befac92318, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x45717876 | Type mismatch on descriptor slot 1.2 (expected VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC) but descriptor of type VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER The Vulkan spec states: layout must be consistent with all shaders specified in pStages (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-00756)
object info: (type: DEVICE, hndl: 0x55befac92318)
