### ISSUE TITLE
Panic on buffer with uninitialized range not aligned to 4 

### ISSUE THREAD

**Issue by lucacasonato** [gfx-rs/wgpu#1373]
**Description**

```
thread 'main' panicked at 'Buffer Buffer { raw: Some((Buffer { raw: 0x565099c3da90 }, MemoryBlock(MemoryBlock { memory_type: 7, props: DEVICE_LOCAL, offset: 1939456, size: 2048, atom_mask: 0, mapped: false, flavor: Buddy { chunk: 0, index: 283, ptr: None, memory: Memory { raw: 0x565099a3bb80 } }, relevant: Relevant }))), device_id: Stored { value: Valid((0, 1, Vulkan)), ref_count: RefCount(0x5650999ea6b0) }, usage: COPY_SRC | COPY_DST, size: 1544, initialization_status: MemoryInitTracker { uninitialized_ranges: [] }, sync_mapped_writes: None, life_guard: LifeGuard { ref_count: Some(RefCount(0x565099aa1700)), submission_index: 635, label: "" }, map_state: Idle } has an uninitialized range with a start not aligned to 4 (start was 1543)', /mnt/starship/Projects/github.com/gfx-rs/wgpu/wgpu-core/src/device/queue.rs:600:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::initialize_used_uninitialized_memory
             at /mnt/starship/Projects/github.com/gfx-rs/wgpu/wgpu-core/src/device/queue.rs:600:17
   3: wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_submit
             at /mnt/starship/Projects/github.com/gfx-rs/wgpu/wgpu-core/src/device/queue.rs:626:9
   4: deno_webgpu::queue::op_webgpu_queue_submit
             at /mnt/starship/Projects/github.com/denoland/deno/extensions/webgpu/queue.rs:47:5
```

**Repro steps**

The `webgpu:api,operation,command_buffer,copyTextureToTexture:color_textures,non_compressed,non_array:format="r8unorm";textureSize={"srcTextureSize":{"width":32,"height":32,"depthOrArrayLayers":1},"dstTextureSize":{"width":63,"height":61,"depthOrArrayLayers":1}};copyBoxOffsets={"srcOffset":{"x":0,"y":0,"z":0},"dstOffset":{"x":0,"y":0,"z":0},"copyExtent":{"width":0,"height":0,"depthOrArrayLayers":0}};srcCopyLevel=0;dstCopyLevel=3` CTS test. Do not have a smaller reproduction at this time. If needed I can give you a rundown on how to run this CTS test in Deno (which uses wgpu-core).

**Expected vs observed behavior**

If this is a legitimate error, it should gracefully error, not panic.

**Platform**

Nvidia GTX 1070 / Linux / Vulkan
wgpu-core 629f01d7dcf3008cf67efab278253d4fab4b40c3

**Comment by kvark** [comment]
@Wumpf what is the guarantee here, as in - who is responsible for aligning these ranges: the side that pushes them, or the queue flushing them?

**Comment by Wumpf** [comment]
Not sure, I'll have a look at times!

**Comment by Wumpf** [comment]
Looking at it a bit I think the pushing side should take care of it. But don't quite understand how this ends up in an unaligned operation in the first place.
@lucacasonato I'd be interested in how to run this CTS test, just point me in the general direction if possible thx :)

**Comment by kvark** [comment]
@Wumpf hey, this appears to be a real showstopper. Would you be interested in fixing this?
Running tests now is easy because it's a part of CI. Just follow the test: https://github.com/gfx-rs/wgpu/blob/60142b56da21a704b1267358de3d7d59f6141284/.github/workflows/ci.yml#L154

Example invocation:
```bash
../wgpu/target/debug/cts_runner ./tools/run_deno "webgpu:api,operation,command_buffer,image_copy:*"
```

**Comment by Wumpf** [comment]
@kvark can do, but can't count on me short term, I'm traveling over this and next week, maybe I can get to it on a train
