### ISSUE TITLE
DX12 doesn't respect alpha for the window

### ISSUE THREAD

**Issue by wez** [gfx-rs/wgpu#1375]
If you take the triangle example and set the alpha to be 0.5, when using Vulkan on both linux and Windows, the window is partially transparent (as expected).

When running on Windows with DX12 the alpha value has no effect.

Example demonstrating what I set for the color/alpha:
https://github.com/wez/wezterm/blob/altwin/window/examples/wgpu.rs#L156-L160
https://github.com/wez/wezterm/blob/altwin/window/examples/shader.wgsl#L12

This is with wgpu=0.8

**Comment by cwfitzgerald** [comment]
You need use DComp to get any transparency working with windows I believe. Take a look at https://docs.rs/wgpu/latest/x86_64-pc-windows-msvc/wgpu/struct.Instance.html#method.create_surface_from_visual
