### ISSUE TITLE
BackendBit::all() causes segmentation fault

### ISSUE THREAD

**Issue by konall** [gfx-rs/wgpu#1376]
OS: Pop!_OS 20.10
GPU: XFX AMD Radeon RX570
<br>

Hi there,

While getting started, I cloned the repository and ran each of the examples, and they all worked as expected except that "Hello Triangle" crashed with a segmentation fault.

I narrowed it down to the [instance creation](https://github.com/gfx-rs/wgpu-rs/blob/69be1ff88a073b3a7f9470044834e75c22f7b4ad/examples/hello-triangle/main.rs#L10) and found that after changing the backend specification from all() to VULKAN or PRIMARY, it then worked as expected.

I tested METAL, DX12, and GL out of curiosity and discovered that it was the GL backend causing the crash, both METAL and DX12 exited with the proper error of being an unsupported backend on my machine.

I tried to find the documentation for BackendBit::all() to investigate further but couldn't find it [on docs.rs](https://github.com/gfx-rs/wgpu/blob/79fcfaa11aff59f208dd37441c9774e5e9ccc272/wgpu-types/src/lib.rs#L94), so I'm not sure what the underlying issue is beyond it mistakenly invoking a GL backend at some point.

Not sure if this is known behaviour but wanted to flag it in case anyone else came across the same issue!

Everything's been working great besides that, thanks for the great project!

**Comment by timothee-haudebourg** [comment]
@konall do you know what version of EGL is installed on your machine?

**Comment by konall** [comment]
> @konall do you know what version of EGL is installed on your machine?


I'm not sure which is the relevant library in this case so I've included them all:

```
$ apt list --installed '*egl*'
Listing... Done
gir1.2-geocodeglib-1.0/groovy,now 3.26.2-2 amd64 [installed,automatic]
libegl-dev/groovy,now 1.3.2-1 amd64 [installed]
libegl-mesa0/groovy,now 21.0.0-1pop0~1616205663~20.10~73b50a1 amd64 [installed]
libegl1-amdgpu-mesa-drivers/now 1:20.1.0-1109583 amd64 [installed,local]
libegl1-amdgpu-mesa-drivers/now 1:20.1.0-1109583 i386 [installed,local]
libegl1-amdgpu-mesa/now 1:20.1.0-1109583 amd64 [installed,local]
libegl1-amdgpu-mesa/now 1:20.1.0-1109583 i386 [installed,local]
libegl1-amdgpu-pro/now 20.30-1109583 amd64 [installed,local]
libegl1-amdgpu-pro/now 20.30-1109583 i386 [installed,local]
libegl1-mesa-dev/groovy,now 21.0.0-1pop0~1616205663~20.10~73b50a1 amd64 [installed]
libegl1-mesa/groovy,now 21.0.0-1pop0~1616205663~20.10~73b50a1 amd64 [installed]
libegl1/groovy,now 1.3.2-1 amd64 [installed]
libwayland-egl1/groovy,now 1.18.0-2~exp1.1 amd64 [installed,automatic]
libwayland-egl1/groovy,now 1.18.0-2~exp1.1 i386 [installed,automatic]
```

**Comment by cwfitzgerald** [comment]
Closing as stale, please refile if it's still an issue.
