### ISSUE TITLE
Scissor test

### ISSUE THREAD

**Issue by snuk182** [gfx-rs/wgpu#138]

**Comment by kvark** [comment]
This is a fairly straightforward state. Basic steps to get there are:
  1. add `gpu_render_pass_set_scissor` method, like [this one](https://github.com/gfx-rs/wgpu/blob/ee3025c4d8e9e63bf24dbbe081eddcbc66716258/wgpu-native/src/command/render.rs#L91)
  2. the implementation would call into gfx-hal's `set_scissor` on the current command buffer
  3. expose it in `wgpu-rs` as a public method of `struct RenderPass`
  4. run `make` (or invoke `wgpu-bindings` manually) to update C-generated headers
