### ISSUE TITLE
Listen to D3D Validation Messages

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1383]
**Is your feature request related to a problem? Please describe.**

It is inconvenient and sometimes impossible to run applications in visual studio to get D3D validation messages. The way we handle vulkan validation is obvious and simple to use.

**Describe the solution you'd like**

Hook into the debug information through [ID3D12InfoQueue](https://docs.microsoft.com/en-us/windows/win32/api/d3d12sdklayers/nn-d3d12sdklayers-id3d12infoqueue) and [ID3D11InfoQueue](https://docs.microsoft.com/en-us/windows/win32/api/d3d11sdklayers/nn-d3d11sdklayers-id3d11infoqueue)

**Describe alternatives you've considered**

Leave things the way they are.

**Additional context**

Situations like #1382 might be difficult to debug remotely without this.

**Comment by kvark** [comment]
Thanks for filing! This should be in gfx-backend-dx12

**Comment by helikopterodaktyl** [comment]
https://docs.microsoft.com/en-us/sysinternals/downloads/debugview can be used to view D3D debug layer output as an alternative to Visual Studio

**Comment by cwfitzgerald** [comment]
Solved with the new hal
