### ISSUE TITLE
Creating a non-square texture array with 6 layers crashes on Metal

### ISSUE THREAD

**Issue by leops** [gfx-rs/wgpu#1386]
**Description**
Creating a texture array with exactly 6 layers results in the texture object being created internally as a cube texture, however if the texture width and height are not equal this results in a validation error on Metal since non-square cube textures are not supported.

**Repro steps**
```rust
async fn main() {
    let instance = wgpu::Instance::new(wgpu::BackendBit::PRIMARY);

    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::HighPerformance,
            compatible_surface: None,
        })
        .await
        .expect("adapter");

    let (device, _queue) = adapter
        .request_device(
            &wgpu::DeviceDescriptor {
                label: None,
                limits: wgpu::Limits::default(),
                features: wgpu::Features::default(),
            },
            None,
        )
        .await
        .expect("device");

    let _texture = device.create_texture(&wgpu::TextureDescriptor {
        label: None,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8Unorm,
        usage: wgpu::TextureUsage::SAMPLED,
        size: wgpu::Extent3d {
            height: 1024,
            width: 2048,
            depth_or_array_layers: 6,
        },
        mip_level_count: 1,
        sample_count: 1,
    });
}
```

**Expected vs observed behavior**
Running the above example will result in the following abort:

```
-[MTLTextureDescriptorInternal validateWithDevice:]:1248: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor width must equal height for cube textures.
```

As for the expected behavior, I'm guessing non-square textures should be created as plain texture arrays instead of cube textures

**Platform**
This has been tested using the `v0.8` branch of `wgpu-rs` on macOS 11.2.3 and iOS 14.4.2

**Comment by kvark** [comment]
Thanks for filing! This makes sense. A naive workaround would be to only consider this to be cube-compatible if the sizes match. Not sure if there is a better way here.

**Comment by cwfitzgerald** [comment]
Closing as stale due to backend rewrite, please refile if it's still an issue.
