### ISSUE TITLE
Fill Out Downlevel Feature Flags

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1392]
**Is your feature request related to a problem? Please describe.**

We assume quite a few gfx-hal features always exist. Most of these should likely be marked as downlevel features as we will likely want to try to run without them anyway.

**Describe the solution you'd like**

A good chunk of the features we require should be turned into downlevel features. See https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/instance.rs#L454-L460 for a list. Not all of them (like NDC_Y_UP) are needed.

**Comment by kvark** [comment]
Sub-meta: downlevel flags for GLES3 - #1510:
 - [x] indirect execution
 - [x] base vertex
 - [x] independent blending

Unresolved: GLES3 doesn't quite allow a texture view to be pointing to a specific range of mipmap levels and array layers. These properties can be configured on the texture object itself, but then it can't be re-used independently for other bindings, so it is unique, and it's hard to manage in the code.
  - minor addition: GLES3 doesn't support a "base array layer" for storage textures specifically

**Comment by cwfitzgerald** [comment]
This has been largely solved my the re-writing of the Dx11 backend
