### ISSUE TITLE
Implement command buffer GPU execution timing

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1395]
See https://gpuweb.github.io/gpuweb/#dom-gpucommandencoderdescriptor-measureexecutiontime
A proper implementation would need changes in gfx-backend-dx12 and gfx-backend-metal.
This is very important for benchmarking, also a core part of WebGPU API.

**Comment by cwfitzgerald** [comment]
This is going to be especially spicy as it just totally won't work for dx11/gl due to the query apis. Another downlevel feature!

**Comment by cwfitzgerald** [comment]
This seems to have not happened.
