### ISSUE TITLE
Incremental presentation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1397]
**Is your feature request related to a problem? Please describe.**
Presenting full screen is wasteful if the user knows only a portion of the screen is changed.

**Describe the solution you'd like**
A native-only feature that allows the user to specify a rectangle to present.
This isn't a security concern, but a portability one.

**Describe alternatives you've considered**
No incremental present

**Additional context**
It's not clear if this is possible, given that the user of a swapchain doesn't know about the number of textures there. So there is no good way for the user to know the baseline, from which the changes were made.

**Comment by cwfitzgerald** [comment]
I highly suspect we will have to expose to the user the amount of images in the swapchain. It also implies letting people render to the swapchain without a clear, something that is currently disallowed.

**Comment by cwfitzgerald** [comment]
Closing in favor of #2869, this isn't as widespread as it seems.
