### ISSUE TITLE
Warnings when using DX12 backend

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu#1405]
**Description**

When the DX12 backend is selected, I get this warning when a device is created:

```
Missing internal features: INDEPENDENT_BLENDING | SAMPLE_RATE_SHADING | FRAGMENT_STORES_AND_ATOMICS
```

**Repro steps**
Create a device using the DX12 backend.

**Expected vs observed behavior**

I am surprised to see warnings like this, because my machine has a modern NVidea GPU.

**Platform**

Windows 10, with an NVidia GeForce RTX 2070. Using wgpu-native master (which targets wgpu-core of a few days ago).

**Comment by cwfitzgerald** [comment]
This is just caused by the gfx-backend-dx12 not properly setting those flags, dx12 supports all of those even at its lowest tier of support (iirc). We should do another pass to make sure all these flags are set.
