### ISSUE TITLE
 On windows, initializing a buffer with mapped_at_creation: true allocates ~130mb first time it's called

### ISSUE THREAD

**Issue by Dispersia** [gfx-rs/wgpu#1407]
**Description**
  On windows, both dx12/vulkan, initializing a buffer with mapped_at_creation: true allocates 130mb on windows the first time it is called.

**Repro steps**
```
use wgpu::util::DeviceExt;

fn main() {
    let instance = wgpu::Instance::new(wgpu::BackendBit::PRIMARY);
    let adapter =
        futures::executor::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
            ..Default::default()
        }))
        .unwrap();

    let (device, _) = futures::executor::block_on(
        adapter.request_device(&wgpu::DeviceDescriptor::default(), None),
    )
    .unwrap();

    let contents = &vec![0, 1, 0, 2, 0, 3];
    let _buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        contents,
        label: None,
        usage: wgpu::BufferUsage::UNIFORM | wgpu::BufferUsage::COPY_DST
    });

    let _buffer2 = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        contents,
        label: None,
        usage: wgpu::BufferUsage::UNIFORM | wgpu::BufferUsage::COPY_DST
    });

    loop {}
}
```

**Expected vs observed behavior**
 On windows I do not expect it to allocate that much memory, on linux, it does not allocate seemingly any extra amount. After _buffer is called, it allocates the ~130mb of memory, but _buffer2 doesn't allocate any extra.

**Platform**
Windows 10, wgpu 0.8.1.

Some notes, I have narrowed it down to this line: https://github.com/gfx-rs/wgpu/blob/7ce535cc97958d8e224247764f3d57c162594504/wgpu-core/src/device/mod.rs#L2888

that's where the massive memory spike happens, but I don't understand why past that point. I see a buffer is allocated already above it, and then it create a new one with the same device_id here, but sorry I don't really understand why it does these things or whats happening past it

**Comment by Dispersia** [comment]
Researching a bit more, more specifically it's this flag: https://github.com/gfx-rs/wgpu/blob/7ce535cc97958d8e224247764f3d57c162594504/wgpu-core/src/device/mod.rs#L554 commenting it out makes it not jump, but it still seems like everything works?

**Comment by kvark** [comment]
I think this will be used for all the uploads and buffers mapped for creation, so 130Mb may be appropriate. Could you clarify why you think this is a bug?

**Comment by Dispersia** [comment]
it's always 130mb regardless of usage, even uploading just a few bytes. If that were expected behavior, wouldn't it be the same across platforms, and unallocated after the buffers are uploaded?

**Comment by kvark** [comment]
> it's always 130mb regardless of usage, even uploading just a few bytes.

Right, so trivial applications would get that 130mb allocated but not used much. At the same time, trivial applications aren't going to suffer from this allocation. Non-trivial applications will be using this memory extensively, possibly growing beyond 130Mb.

> wouldn't it be the same across platforms

I don't know the details on how gpu-alloc operates (we can look at the source), but it may consider the total available memory as reported by the platform, and take a fraction of it. In this case, different platforms report different numbers.

> unallocated after the buffers are uploaded

It will likely be freed at some point if nothing uses this staging memory for a few frames. Are you seeing it stay even if you aren't doing anything relevant (`mapped_at_creation=true`, `write_buffer`, `write_texture`)?

**Comment by Dispersia** [comment]
in the example above i just have it loop {} forever and correct, it never deallocates that memory. Are you saying if I do other things such as finish encoding without doing any mapped_at_creation etc it might go away?

**Comment by kvark** [comment]
We can't possibly free any memory if you are hanging in an infinite loop. wgpu doesn't do any secret thread: everything that's happening is tied to something you do. So if you have a proper frame loop, and you submit stuff to the queue, then I believe this memory will be freed if not used.

**Comment by Dispersia** [comment]
Uploaded a more full example: https://github.com/Dispersia/test_wgpu
 Creates a buffer a single time up front, then just loops redrawing the same triangle over and over. Do I need to be modifying a buffer (without mapped_at_creation: true) as well, or would this be expected to release as well?

I let it run for ~10 minutes and it never dropped below 165mb

**Comment by kvark** [comment]
@zakarumych is this expected?

**Comment by zakarumych** [comment]
Current behavior is following: for first memory block it allocates one chunk of memory, size of this chunk is configured on allocator creation and limited by fraction of heap size.
While there are at least one block allocated from chunk, it cannot be freed.
Allocator will free chunks of memory when total size of free blocks exceeds certain amount. Which currently equals two chunk sizes.

If buffer is created only once and then no allocations are expected in future, gpu-alloc won't have a chance to know that, as no calls to gpu-alloc would happen.

**Comment by kvark** [comment]
@zakarumych  Ok, thanks for explanation!
In this case, the application allocates a small block inside staging memory, and then it's freed once the GPU is done with the copy. Does it not fit under "total size of free blocks exceeds certain amount" criteria?

**Comment by zakarumych** [comment]
Certain amount currently is two chunk size. Adding configuration field is possible with next minor version.

Freeing the only chunk as soon as last block is freed would bring significant overhead in case of repeated uploads (once per few frames).

**Comment by cwfitzgerald** [comment]
This is a damned if we do, damned if we don't situation. If we use smaller blocks, we need to allocate more and things slow down, if we use bigger blocks we waste more memory, but hit the allocator less. I'm going to call this a non-issue as a bit of memory waste is better than slow allocation, but if there are more concrete suggestions on how we could make this better, please refile!
