### ISSUE TITLE
Dynamic binding at index 0 with offset 256 would overrun the buffer

### ISSUE THREAD

**Issue by MrMarnic** [gfx-rs/wgpu#1408]
I have created a buffer like this:

`let buffer = device.create_buffer(&BufferDescriptor {
        label: None,
        size: BIND_BUFFER_ALIGNMENT * 10,
        usage: BufferUsage::UNIFORM | BufferUsage::COPY_DST,
        mapped_at_creation: false
    });`

Then a layout:
`let color_group_layout = device.create_bind_group_layout(&BindGroupLayoutDescriptor { label: None, entries: &[BindGroupLayoutEntry {
            binding: 0,
            visibility: ShaderStage::FRAGMENT,
            ty: BindingType::Buffer { ty: BufferBindingType::Uniform,has_dynamic_offset: true, min_binding_size: None },
            count: None
        }] });`

and the bind group:
`let color_group = device.create_bind_group(&BindGroupDescriptor {
            label: None,
            layout: &color_group_layout,
            entries: &[BindGroupEntry { binding: 0, resource: BindingResource::Buffer(BufferBinding {
                buffer: &color_buffer,
                offset: 0,
                size: None
            })}]
        });`

But if I use it like this:
`render_pass.set_bind_group(0,&color_group,&[256]);`

I have written to the buffer like this:
`queue.write_buffer(&self.color_shader.color_buffer,256,data);`

This error occurs:
dynamic binding at index 0 with offset 256 would overrun the buffer (limit: 0)

I don't know what I am doing wrong. I hope you can help me

**Comment by kvark** [comment]
The problem is here:
> BufferBinding { buffer: &color_buffer, offset: 0, size: None }

You are saying that the binding sees the whole buffer (`size: None` part). So you can't move it by the offset.
Instead, tell it the actual size of your shader structure.
