### ISSUE TITLE
SPIR-V validation fails on utexture2D

### ISSUE THREAD

**Issue by dzil123** [gfx-rs/wgpu#1409]
**Description**
I am trying to use a `TextureFormat::Rgba8Uint` texture in my fragment shader as a texture + sampler, but the shader is not validating.

**Repro steps**
Compile the following glsl fragment shader as SPIR-V, then create a wgpu shader module with `ShaderFlags::VALIDATION` enabled.
```glsl
#version 450

layout(set = 0, binding = 0) uniform utexture2D input_tex;
layout(set = 0, binding = 1) uniform sampler input_smp;

void main() {
    uvec4 data = texture(usampler2D(input_tex, input_smp), vec2(0));
}
```

**Expected vs observed behavior**
As `TextureFormat::Rgba8Uint.describe()` shows that `TextureUsage::SAMPLED` is a valid usage for this format, I expect `utexture2D` to work.
In reality, the following error occurs:
```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `shader.frag`
    Function [1] 'main' is invalid
    Expression [10] is invalid
    Unable to operate on image class Sampled { kind: Uint, multi: false }
```

**Extra materials**
Here is a small Rust program demonstrating this issue: https://gist.github.com/rust-play/90063ad169e7f3834c19769a1182b8db

**Platform**
Linux native, Vulkan
wgpu 0.8.1

**Comment by kvark** [comment]
Thank you for filing this issue!
In WebGPU, integer textures can't be sampled. This limitation comes from HLSL/DX land.
Closing this, but feel free to continue discussing.

**Comment by cwfitzgerald** [comment]
If that's the case we need to change the description to not include sampling as a valid usage.

**Comment by kvark** [comment]
@cwfitzgerald that's an interesting idea! I don't think we can do this, though, for these reasons:
  1. on the API side, the binding is still "GPUTextureBindingLayout", not "GPUStorageTextureBindingLayout".
  2. if we disallow `SAMPLED`, this would force `STORAGE`, which in turn disables color compression on some platforms. Dunno how much integer colors can be compressed by the driver, but still a concern.
  3. the usage is passed to texture creation, but once we allow creating views with a different format, we'd not be able to tell ahead of time if the texture creation is invalid.

**Comment by dzil123** [comment]
Why then does `TextureSampleType` have integer types and sample shader code? https://github.com/gfx-rs/wgpu/blob/7ce535c/wgpu-types/src/lib.rs#L2802-L2817

Is integer texture sampling possible with `Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`, to sidestep non-Vulkan limitations?

**Comment by kvark** [comment]
There are 2 issues here:
  1. the spec uses "sampling" in 2 distinct meanings (one is for just reading from textures, aka `SAMPLED`, and another is for using a sampler with it), and that's something WebGPU editors are going to discuss soon.
  2. the example code of GLSL is on the way out, will be replaced with WGSL any moment now.

**Comment by cwfitzgerald** [comment]
So the way to use GLSL to sample this is through `texelFetch` + `GL_EXT_samplerless_texture_functions` so that you can directly fetch a pixel from the texture without a sampler. `texelFetch(texture, ivec2(...), 0)` to get from LOD 0.
