### ISSUE TITLE
Optimize TrackerSet memory allocation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1411]
**Is your feature request related to a problem? Please describe.**
See profile in https://share.firefox.dev/3oYh7DG
We are spending significant time merging and extending the trackers.

**Describe the solution you'd like**
Not completely sure. I'm not seeing an obvious way to do less merging in general.
But we can be better at re-using the tracker memory.

**Describe alternatives you've considered**
keep all the pass trackers separately, only merging at `finish()` or `submit()`

**Additional context**
Shows up in Gecko performance profiles

**Comment by cwfitzgerald** [comment]
Fixed by #2662
