### ISSUE TITLE
Resource tracking overhead

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1413]
Related to #1411
Firefox profile - https://share.firefox.dev/3fvytEz
If you look at `run_render_pass_impl` in the flamegraph view, the Vulkan driver is taking less than half of that time.
The rest is spent on barriers and tracking (everything related to `TrackerSet`), so clearly this is a hot spot.

Ideas:
  1. Most buffers and textures are immutable after they got the initial contents transferred into them. It would be wonderful to find a way to avoid tracking them entirely, or at least up to the point where they do get mutated.
  2. Today the tracker has `(init, current)` states per subresource. We could extend it to `(init, current, next)`, so that the sync scope (of, say, a render pass) will be accumulated in the `next`. This would mean - no need to allocate/free tracker sets per pass. Everything would be done right in the command buffer tracker. Related to #443

**Comment by kvark** [comment]
Assembly for the following functions need to be looked at under a microscope:
  - `gfx_backend_vulkan::command::CommandBuffer::bind_descriptor_sets`: roughly 1/9 of it is actually spent in `ash::vk::features::DeviceFnV1_0::cmd_bind_descriptor_sets`. The rest includes boilerplate an inlined pipeline compatibility logic.
  - `wgpu_core::command::CommandBuffer::insert_barriers` seems quite heavy, also does some refcount stuff (unexpectedly?)
  - `wgpu_core::command::bind::Binder::assign_group` does refcounting. I don't think it should?
  - `wgpu_core::track::TrackerSet::merge_extend` and `wgpu_core::track::ResourceTracker::use_extend`: maybe we can make them cache friendlier?
  - `wgpu_core::hub::Storage::get` shows up a bit everywhere, but a lot in `submit()`

**Comment by kvark** [comment]
Another idea (3) - a merge of 1) and 2) but without any heavy changes. If we know something doesn't have a state (but just needs to be added to the lifetime tracker), then adding it to the render pass tracker is a waste. We could make it so only buffers and textures are tracked per pass (or per usage scope), and everything else goes straight to the command buffer tracker. For the animometer benchmark, it would cut the costs by almost the factor of 2.

**Comment by kvark** [comment]
New profile after (3) is merged - https://share.firefox.dev/3pjq2Qa
There are still things to address here. Also there is a gap not annotated by anything.

**Comment by cwfitzgerald** [comment]
Closing after #2662
