### ISSUE TITLE
Backend selection is not always Vulkan > Metal > DX12

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu#1416]
This is a bit of a follow-up on https://github.com/gfx-rs/wgpu-native/issues/101

It was [mentioned there](https://github.com/gfx-rs/wgpu-native/issues/101#issuecomment-845538586) that the backend selection priority is Vulkan > Metal > DX12. However, I have experienced DX12 being selected even though Vulkan is available (and confirmed to work if I force Vulkan being selected). I can consistently reproduce this on my machine, with Windows 10 and an NVidea GPU, by selecting in the NVidea control panel to use the high performance GPU (and not integrated graphics). 

(This issue was problematic for me due to certain problems with the DX12 backend, but now that we can force the selection of Vulkan, we have a simple workaround for now).

**Comment by kvark** [comment]
What might be happening here is that DX12 adapters matched your preferences better. For example, if you request HighPerformance, and the Vulkan adapters are all low-power, then you can end up with a DX12 adapter. This is by design.
Could you provide all the details about the system you are testing this on (with `vulkaninfo`), `RUST_LOG=debug` output, and the options you request from the adapter selection?

**Comment by almarklein** [comment]
## Details on my system

<details>
<summary>λ vulkaninfo --summary</summary>
WARNING: [Loader Message] Code 0 : loaderAddLayerProperties: C:\VulkanSDK\1.2.176.1\Bin\VkLayer_api_dump.json invalid layer manifest file version 1.2.0.  May cause errors.
WARNING: [Loader Message] Code 0 : loaderAddLayerProperties: C:\VulkanSDK\1.2.176.1\Bin\VkLayer_device_simulation.json invalid layer manifest file version 1.2.0.  May cause errors.
WARNING: [Loader Message] Code 0 : loaderAddLayerProperties: C:\VulkanSDK\1.2.176.1\Bin\VkLayer_gfxreconstruct.json invalid layer manifest file version 1.2.0.  May cause errors.
WARNING: [Loader Message] Code 0 : loaderAddLayerProperties: C:\VulkanSDK\1.2.176.1\Bin\VkLayer_khronos_synchronization2.json invalid layer manifest file version 1.2.0.  May cause errors.
WARNING: [Loader Message] Code 0 : loaderAddLayerProperties: C:\VulkanSDK\1.2.176.1\Bin\VkLayer_khronos_validation.json invalid layer manifest file version 1.2.0.  May cause errors.
WARNING: [Loader Message] Code 0 : loaderAddLayerProperties: C:\VulkanSDK\1.2.176.1\Bin\VkLayer_screenshot.json invalid layer manifest file version 1.2.0.  May cause errors.
==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.162


Instance Extensions: count = 15
-------------------------------
VK_EXT_debug_report                    : extension revision 9
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_win32_surface                   : extension revision 6
VK_NV_external_memory_capabilities     : extension revision 1

Instance Layers: count = 10
---------------------------
VK_LAYER_KHRONOS_synchronization2 Khronos Synchronization2 layer             1.2.176  version 1
VK_LAYER_KHRONOS_validation       Khronos Validation Layer                   1.2.176  version 1
VK_LAYER_LUNARG_api_dump          LunarG API dump layer                      1.2.176  version 2
VK_LAYER_LUNARG_device_simulation LunarG device simulation layer             1.2.176  version 1
VK_LAYER_LUNARG_gfxreconstruct    GFXReconstruct Capture Layer Version 0.9.7 1.2.176  version 36871
VK_LAYER_LUNARG_monitor           Execution Monitoring Layer                 1.2.176  version 1
VK_LAYER_LUNARG_screenshot        LunarG image capture layer                 1.2.176  version 1
VK_LAYER_NV_optimus               NVIDIA Optimus layer                       1.2.168  version 1
VK_LAYER_VALVE_steam_fossilize    Steam Pipeline Caching Layer               1.2.136  version 1
VK_LAYER_VALVE_steam_overlay      Steam Overlay Layer                        1.2.136  version 1

Devices:
========
GPU0:
        apiVersion         = 4202664 (1.2.168)
        driverVersion      = 1955315712 (0x748bc000)
        vendorID           = 0x10de
        deviceID           = 0x1f10
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = NVIDIA GeForce RTX 2070 with Max-Q Design
        driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
        driverName         = NVIDIA
        driverInfo         = 466.47
        conformanceVersion = 1.2.5.2
GPU1:
        apiVersion         = 4202644 (1.2.148)
        driverVersion      = 1647081 (0x1921e9)
        vendorID           = 0x8086
        deviceID           = 0x3e9b
        deviceType         = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName         = Intel(R) UHD Graphics 630
        driverID           = DRIVER_ID_INTEL_PROPRIETARY_WINDOWS
        driverName         = Intel Corporation
        driverInfo         = Intel driver
        conformanceVersion = 1.2.0.2

</details>

## Tests with requesting a LowPower adapter

wgpu-native does not provide a way to specify the power preference ATM - it uses the default, [which is low power](https://docs.rs/wgpu-types/0.8.0/src/wgpu_types/lib.rs.html#81-86).

When I select "Auto select" in control panel, and request LowPower:
```
Expected wgpu-native version (0, 8, 0, 1) but got (0, 0, 0)
Adapter Vulkan AdapterInfo { name: "Intel(R) UHD Graphics 630", vendor: 32902, device: 16027, 
    device_type: IntegratedGpu }
AdapterProperties: IntegratedGPU Vulkan
```

When I select "High performance NVIDIA processor" in control panel, and request LowPower:
```
Adapter Dx12 AdapterInfo { name: "Intel(R) UHD Graphics 630", vendor: 32902, device: 16027,
    device_type: IntegratedGpu }
AdapterProperties: IntegratedGPU D3D12
```
This is strange. Why is it selecting the integrated GPU? And why D3D12? If I force using the Vulkan backend I get what I'd expect:
```
Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 2070 with Max-Q Design", vendor: 4318, device: 7952,
    device_type: DiscreteGpu }
AdapterProperties: DiscreteGPU Vulkan
```

When I select "Integrated Graphics" in control panel, and request LowPower:
```
Adapter Vulkan AdapterInfo { name: "Intel(R) UHD Graphics 630", vendor: 32902, device: 16027,
    device_type: IntegratedGpu }
AdapterProperties: IntegratedGPU Vulkan
```

## Tests with requesting a HighPerformamnce adapter 

I can change the source of wgpu-native to select HighPerformance instead.

When I select "Auto select" in control panel, and request HighPerformance:
```
Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 2070 with Max-Q Design", vendor: 4318, device: 7952, 
    device_type: DiscreteGpu }
AdapterProperties: DiscreteGPU Vulkan
```

When I select "High performance NVIDIA processor" in control panel, and request HighPerformance:
```
Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 2070 with Max-Q Design", vendor: 4318, device: 7952,
    device_type: DiscreteGpu }
AdapterProperties: DiscreteGPU Vulkan
```

When I select "Integrated Graphics" in control panel, and request HighPerformance:
```
Adapter Dx12 AdapterInfo { name: "NVIDIA GeForce RTX 2070 with Max-Q Design", vendor: 4318, device: 7952,
    device_type: DiscreteGpu }
AdapterProperties: DiscreteGPU D3D12
```

This is strange. If I do the same, but force the Vulkan backend:
```
Adapter Vulkan AdapterInfo { name: "Intel(R) UHD Graphics 630", vendor: 32902, device: 16027,
    device_type: IntegratedGpu }
AdapterProperties: IntegratedGPU Vulkan
```

## Discussion

From the above results, it looks like the D3D12 backend ignores the settings of the NVidia control panel, and therefore is better able to match the power preference. I don't know if this is how it's supposed to work, but its surprising to me :)

**Comment by kvark** [comment]
I think this is all within expectations. I don't know exactly what the NV control panel does, but I assume it can filter out the Vulkan adapters. So if you force NVidia, then the only Vulkan adapter wgpu sees is the discreet GPU. Since the power preference was "low power", it prefers the D3D12's view of Intel adapter instead.
I don't know why NV control panel doesn't affect D3D12 adapters, that would be a separate (loosely related) question to resolve.

We should expose the power preference setting to the user of wgpu-native.

**Comment by almarklein** [comment]
> I don't know why NV control panel doesn't affect D3D12 adapters, that would be a separate (loosely related) question to resolve.

Yeah, it's very strange. Sounds like a problem that lies deeper, maybe gfx-hal, or maybe simply out of our reach?

> We should expose the power preference setting to the user of wgpu-native.

Yes, that would be good. But that should go via webgpu.h, right?

**Comment by kvark** [comment]
I don't think there is anything tricky gfx-hal doing here. Each backend sees a list of adapters, wgpu builds a combined list and chooses an appropriate.

> Yes, that would be good. But that should go via webgpu.h, right?

Correct, yes.
