### ISSUE TITLE
texture array interpreted as cube texture array 

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#1418]
Short info header:
It seems that repeated growing of a texture 2d array can be reinterpreted as a cube texture array, which can cause failures on systems that don't support cube texture arrays (e.g., MTFGPUFamilyApple3).
For example, repeated uploads of https://github.com/hecrj/iced/blob/e292821c3780fc5a57c835815efc7a232ce4dc32/wgpu/src/shader/image.wgsl#L8 can exhibit this behavior.
- GFX version: wgpu-rs 0.8
- OS: iOS/macOS
- GPU: a10x

**Comment by kvark** [comment]
Technically, this device is non-conformant, since it doesn't support cube arrays.
