### ISSUE TITLE
Move wgpu-rs back home

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1422]
https://github.com/gfx-rs/wgpu-rs could be moved back into this repo.
Born in https://github.com/gfx-rs/gfx/discussions/3768
Indirectly depends on #1421

Question to resolve: what would be the location? Currently we have `wgpu-core` and `wgpu-types` folders, which match the crate names. Choices:
  - `wgpu-rs` - matches the current repo name
  - `wgpu` - matches the crate name
  - `rust` - just a try at something else

**Comment by cwfitzgerald** [comment]
I think we should just go by crate name. I think this follows the principle of least surprise, and I personally found it surprising that the wgpu crate was in a repository of a different name.

**Comment by kvark** [comment]
That's what I was leaning to, as well. Glad we are synced up :)

**Comment by kvark** [comment]
We just merged the commits in-tree, into `wgpu` subfolder, see a6ff3ea08694779143250b633fedd7d91b7c150c
