### ISSUE TITLE
Add help for std140 and std430 layouts

### ISSUE THREAD

**Issue by Yamakaky** [gfx-rs/wgpu#1428]
vertex_attr_array is mainly usefull when passing vertex data from rust to the shader. It would be nice to add helpers for structs following the std140/std430 GLSL layouts, including vertex input layout. In my app, I generate vertices with normals in a compute shader and use the buffer as input for the vertex buffer, and I had some trouble with having matching layouts. Long term, maybe a `#[std140]` macro? It could be added as a separate crate (does one already exist?).

**Comment by teoxoy** [comment]
WGSL's [memory layout](https://gpuweb.github.io/gpuweb/wgsl/#memory-layouts) is now in the spec. For helpers, you can use [`encase`](https://github.com/teoxoy/encase), [`crevice`](https://github.com/LPGhatguy/crevice) or [`glsl-layout`](https://github.com/rustgd/glsl-layout).

**Comment by cwfitzgerald** [comment]
Closing as basically out of scope, this is something for wgpu tutorials more than us ourselves.
