### ISSUE TITLE
[meta] Naga Compilation Status Overview for the Examples

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/wgpu#1429]
Tracking issue for what examples work.

Legend

* Working = :heavy_check_mark: 
* Not working (yet) = :x: 
* Unknown/Not tested = :question:
* Inapplicable = :heavy_exclamation_mark:

# Overview

| Example                                                                                 | Status                                                            | Note                  |
| --------------------------------------------------------------------------------------- | ----------------------------------------------------------------- | --------------------- |
| [Boids](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/boids)                   | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Capture](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/capture)               | :heavy_exclamation_mark:                                          | Doesn't use a shader. |
| [Cube](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/cube)                     | `naga-glsl-to-spirv` - :x: <br> `naga_wgsl-to-spirv` - :question: |                       |
| [Hello](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/hello)                   | :heavy_exclamation_mark:                                          | Doesn't use a shader. |
| [Hello-compute](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/hello-compute)   | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Hello-triangle](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/hello-triangle) | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Hello-windows](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/hello-windows)   | :heavy_exclamation_mark:                                          | Doesn't use a shader. |
| [Mipmap](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/mipmap)                 | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Msaa-line](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/msaa-line)           | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Shadow](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/shadow)                 | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Skybox](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/skybox)                 | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Texture-arrays](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/texture-arrays) | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |
| [Water](https://github.com/gfx-rs/wgpu-rs/tree/master/examples/water)                   | `naga-glsl-to-spirv` - :x: <br> `naga-wgsl-to-spirv` - :question: |                       |

# Issues
| Description                                                                                        | Framework      | Affected Shader(s)                                                                                                   | Issue                                                      |
| -------------------------------------------------------------------------------------------------- | -------------- | -------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| "unsupported layout qualifier(s)"                                                                  | `naga-glsl-in` | Boids - boids.comp <br> Hello-compute - shader.comp <br> Water - terrain_shader.frag                                 | [#Naga-282](https://github.com/gfx-rs/naga/issues/282)     |
| "Expected number of constituents to be at least 2"                                                 | `naga-spv-out` | Boids - shader.frag <br> Shadow - bake.vert                                                                          |                                                            |
| Not implemented "Function Call"                                                                    | `naga-glsl-in` | Boids - shader.vert <br> Cube - shader.frag <br> Mipmap - blit.frag                                                  |                                                            |
| Not implemented "Subtract"                                                                         | `naga-spv-out` | Hello-triangle - shader.vert                                                                                         | ~~[#Naga-274](https://github.com/gfx-rs/naga/pull/274)~~   |
| Not implemented "unary_op"                                                                         | `naga-glsl-in` | Mipmap - blit.vert <br> Skybox - shader.vert                                                                         |                                                            |
| Not implemented "Add"                                                                              | `naga-spv-out` | Mipmap - draw.vert                                                                                                   | [#Naga-286](https://github.com/gfx-rs/naga/issues/286)     |
| "Expected Constituents to be scalars or vectors of the same type as Result Type components"        | `naga-spv-out` | Msaa-line - shader.vert <br> Texture-arrays - shader.vert <br> Hello-triangle - shader.vert                          | ~~[#Naga-283](https://github.com/gfx-rs/naga/issues/283)~~ |
| "Invalid token 'const'"                                                                            | `naga-glsl-in` | Shadow - forward.frag <br> Water - terrain_shader.vert <br> Water - water_shader.frag <br> Water - water_shader.vert | [#Naga-285](https://github.com/gfx-rs/naga/issues/285)     |
| "Duplicate non-aggregate type declarations are not allowed. Opcode: TypeVector"                    | `naga-spv-out` | Shadow - forward.vert                                                                                                |                                                            |
| "Invalid token 't_Cubemap' - Missing the textureCube function                                      | `naga-glsl-in` | Skybox - shader.frag                                                                                                 |                                                            |
| "ParseError { kind: InvalidToken(LeftBracket(TokenMetadata { line: 6, chars: 57..58 })) }"         | `naga-glsl-in` | Texture-arrays - constant.frag <br> Texture-arrays - uniform.frag                                                    |                                                            |
| "ParseError { kind: InvalidToken(Interpolation((TokenMetadata { line: 5, chars: 35..39 }, Flat)))" | `naga-glsl-in` | Texture-arrays - nonuniform.frag <br> Texture-arrays - unsized-non-uniform.frag                                      |                                                            |
| Not implemented "And"                                                                              | `naga-spv-out` | Hello-triangle - shader.vert                                                                                         | ~~[#Naga-275](https://github.com/gfx-rs/naga/pull/275)~~   |
| Missing cast expression implementation (Expression::As)                                            | `naga-glsl-in` | Hello-triangle - shader.vert                                                                                         | ~~[#Naga-277](https://github.com/gfx-rs/naga/issues/277)~~ |

**Comment by cwfitzgerald** [comment]
Closing as we're fully Naga based now.
