### ISSUE TITLE
Slow/Artifacting Resize on Windows

### ISSUE THREAD

**Issue by kobutri** [gfx-rs/wgpu#1448]
I tested the cube example in release mode.
My integrated GPU is a Intel UHD Graphics 620 and I also have a Nvidia MX150.

Vulkan + Intel: does not work it uses the Nvidia card anyways
Vulkan + Nvidia: resize does not show artifacts, but is extremely slow.
openGL + Intel: does not find a suitable adapter
openGL+ Nvidia: same as with Intel
DX11 + Intel: flawless. The corner of my window is glued to my mouse cursor and there are absolutely no artifacts
DX11 + Nvidia: same as with Intel
DX12 + Intel: a little slower than DX11 and there are some small artifacts at the edges
DX12 + Nvidia: almost the same as Intel, but the artifacts are a bit more severe

It think it is also worth pointing out, that creating the windows with `builder.with_no_redirection_bitmap(true);` fixes the artifact problem with DX12, but breaks DX11 and Vulkan in the sense that the window remains transparent.

**Comment by cwfitzgerald** [comment]
Closing as stale due to hal rewrite.
