### ISSUE TITLE
[Documentation] Took me 30 min to get started

### ISSUE THREAD

**Issue by eliemichel** [gfx-rs/wgpu#1449]
It is way too much. Sorry if this sounds abrupt. ^^ Running the examples was fairly straightforward, but the [usage](https://github.com/gfx-rs/wgpu-rs#usage) section of the readme is only talking about the examples, and going from there to a simple standalone project relying on wgpu took me like 30 min.

I am not very fluent in Rust yet, so maybe there is a magic "convert example to standalone project" command available in cargo, idk. The thing is I come from the graphics community so I feel pretty much like the intended target of such a library, I must not be the only person coming with experience of graphics libraries but less experience of Rust so it might be worth recalling the basics, if "converting an example into a project" is a basic.

I want to quickly start a new project, so I copy one of the example folders, rename it `src` and create a `Cargo.toml` next to it. I started over with hello-triangle because the one I had choosed first was relying on some additional `framework.rs` that I could not locate. After a lot of trial error I figured out I need this in the `Cargo.toml` dependency section:

```
[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
winit = "0.24.0"
wgpu-subscriber = "0.1.0"
pollster = "0.2.1"
```

(Using last wgpu crate wasn't compatible with the hello-triangle example from the repository.) This is nothing obvious, it would have saved me much time to have this available already somewhere. And I am not even sure it is the most idiomatic solution (hence I am not doing a pull request cause documentation written by beginner is sometimes worst than no documentation... I don't feel legit.)

**Comment by cwfitzgerald** [comment]
We've now added a section for tutorials to the readme.
