### ISSUE TITLE
Wayland HiDPI: winit decoration overhangs the contents by 2x in examples

### ISSUE THREAD

**Issue by valpackett** [gfx-rs/wgpu#1450]
Something is not right about the hidpi factor handling:

![cube-fs8](https://user-images.githubusercontent.com/208340/62121915-3e03ff80-b2cd-11e9-90bf-3a483332666c.png)

**Comment by kvark** [comment]
I'm seeing this issue on Gnome+Wayland now with #2076
What's particularly interesting is that it's not exactly 2x. If I change the window size with mouse, the rendered portion stays the same size!

**Comment by cwfitzgerald** [comment]
This feels out of scope to us.
