### ISSUE TITLE
Non-blocking API

### ISSUE THREAD

**Issue by LaylBongers** [gfx-rs/wgpu#1451]
I'm honestly not sure entirely where I should post this, given the different projects that cover what goes into wgpu, but I figured I would put it here, even if perhaps it needs to be delegated upstream.

I've been working with projects that require rendering across multiple windows, as well as trying to fit the entire project on an async runtime (tokio in my case) to parallelize my projects better, and make better use of worker threads.

At this time WGPU has a function that prevents me from rendering to multiple windows efficiently without creating a thread per window, or putting WGPU rendering code on the tokio runtime. Specifically the function `SwapChain::get_next_texture`.

On native platforms, this function will block until the next texture is available. This means that, without using 1 thread per window, all rendering and updating of all windows will stall whenever an attempt is made to render to one window, without any way to in advance detect if it will block.

This also means it can't be used on a tokio runtime, as multiple windows being rendered to will effectively stall worker threads until it's done blocking.

It would be nice if there was an alternative function, or a feature on this function, to never block but instead poll. At the very least the Vulkan backend supports this behavior on acquiring the next swapchain image. This would also make it possible to implement a `Future` around the SwapChain and use WGPU on a tokio runtime without blocking the worker thread.

Currently, I don't know if there's any other functions in WGPU that have similar issues, but if there are it would be nice to, where possible, have similar non-blocking APIs available.

**Comment by cwfitzgerald** [comment]
I'm going to close this as stale as so much has changed, there are still similar issues open - the current idea is to move get_current_texture onto another thread. There will also be ways to control frame timing such that get_current_texture never waits. See #2650 for another tool that will help you achieve this.
