### ISSUE TITLE
Dynamically uniform expression (`.length()` for arrays in SSBOs) not working

### ISSUE THREAD

**Issue by grtlr** [gfx-rs/wgpu#1452]
This might be related to the following issues: gfx-rs/wgpu-rs#36, gfx-rs/wgpu-rs#53. I'm aware that `wgpu` is not concerend with shader compilation yet, I still hope there might be somebody who can shed some light on this issue. Thank you!

In the following code snippet, the `.length()` call does not work:

```glsl
layout(std430, set = 0, binding = 1) buffer History {
    uint history[];
};

void main() {
    ...
    uint len = history.length();
    ...
}
```
However, if I set `uint history[1000];` it works as expected. As far as I can tell from the GLSL specification this should work. [An example can be found here.](https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)#Shader_storage_blocks)

I'm runnning `wgpu-rs` on macOS with `shaderc-rs` to create SPIR-V from GLSL files. The initial buffer is created using the following code (the `range` is set accordingly):

```rust
let history_buffer_size = 1000 as u64 * 4;

let history_buffer = device.create_buffer(&wgpu::BufferDescriptor{
    size: history_buffer_size,
    usage: wgpu::BufferUsage::STORAGE |
           wgpu::BufferUsage::STORAGE_READ |
           wgpu::BufferUsage::COPY_DST,
    });
```

**Comment by kvark** [comment]
This has been implemented on Vulkan and Metal. Still needs to be done on D3D and GL.

**Comment by cwfitzgerald** [comment]
This is implemented everywhere now.
