### ISSUE TITLE
Compute shader performance gains missing from examples.

### ISSUE THREAD

**Issue by Ben-PH** [gfx-rs/wgpu#1454]
There are a lot of use case for GPU acceleration for general purpose computing. The principals used to calculate fractals such as the mandelbrot transfers directly to areas such as physics simulations, neural network iterations, video compression, etc.

One use case that I see wgpu showing a lot of promise for, is distributed computing. Folding at Home produces incredible value to to medical research, with people freely donating phenominal amounts of GPU computing power to COVID-19 research efforts. By enabling these GPU intensive general computing tasks in the browser, it opens some very interesting doors.

By demonstrating a wgpu being put to use to make better use of the GPU through browsers, the utility that it offers is showcased more comprehensively, and empowers devs to make better use of this tool.

**Comment by Cactice** [comment]
Latest compute shader blog from raphlinus:
https://raphlinus.github.io/gpu/2021/11/17/prefix-sum-portable.html

**Comment by cwfitzgerald** [comment]
I'm going to close this as basically out of scope, we could use additional compute examples, but especially with the issues that come with heterogeneous compute on PCI-based devices, we likely can't show it off on speed alone.
