### ISSUE TITLE
Examples: The winit::EventLoop should not be run in wasm_bindgen_futures::spawn_local

### ISSUE THREAD

**Issue by dragly** [gfx-rs/wgpu#1457]
Running the event loop inside of an async function in spawn_local appears to block new JS promises from being run if they are created in an event callback:

https://github.com/rustwasm/wasm-bindgen/issues/2246

I am not sure exactly how to restructure the examples, but figured I would post this here in case anyone knows the right way to do this or comes across the same issue as I did.

**Comment by kvark** [comment]
@grovesNL should this be closed by #1469 ?

**Comment by grovesNL** [comment]
@kvark yeah, the wgpu examples should be ok now, so we can close this.

We'll also track the upstream fix for winit in https://github.com/rust-windowing/winit/issues/1714
