### ISSUE TITLE
Integrate with Basis Universal format

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1458]
When we start supporting gfx-rs/wgpu#852 , we'll have this problem that no compressed format is supported everywhere. It would be nice to still provide *some* way to have compressed textures to the user, way that would work everywhere. [Basis Universal](https://github.com/BinomialLLC/basis_universal) is a good candidate to solve this. There is even a crate in rust that implements it - https://github.com/JakubValtar/basisu_rs (cc @JakubValtar). We should explore an opportunity to depend on that crate, optionally, so that we can hide the differences between compressed formats at wgpu-rs level.

**Comment by cwfitzgerald** [comment]
What would this actually manifest as? Afaik there are no real plans to support basisu on gpus, so it would have to be decoded before being uploaded anyway and that seams like it would be external crate's job not ours.

**Comment by kvark** [comment]
I guess the goal of this task is to use the Basis and see. Maybe it's feasible to have a native-only feature exposing the "BasisXxx" texture formats. Or maybe it's better off as `crate_texture_basis` utility function. Or something else entirely.

**Comment by fintelia** [comment]
I don't think it is feasible for wgpu to expose support for texture formats that hardware couldn't natively handle. How would you deal with texture <---> buffer copies on the GPU? However, I think something like a `Queue::write_texture_basis` seems completely viable.

**Comment by cwfitzgerald** [comment]
This is why I think this shouldn't really be our responsibility. Let the user (or another library) deal with decoding basis into something the underlying API supports, but we shouldn't be doing that conversion.

**Comment by kvark** [comment]
As with any other convenience thing, if it's possible to poly-fill this with the same efficiency, then we can close it and let the ecosystem figure it out. This issue is there to investigate/see if this poly-fill is possible, or maybe there is a better integration path somewhere that changes wgpu.

**Comment by cwfitzgerald** [comment]
Given the current state of the vulkan ecosystem with no real basis support, there is nothing that we could do that would be more efficient than something a user could do, so I'm going to close the issue.
