### ISSUE TITLE
Demonstrate TypedArena use in an example

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1462]
There are cases where resources are:
  - temporarily created
  - borrowed from a temporary `Arc<T>`

In these cases, a `TypedArena` can help extending the lifetimes of these structures. We should show it in one of the examples.

**Comment by kvark** [comment]
We just added the `bunnymark` example, which could demonstrate this.

**Comment by cwfitzgerald** [comment]
This will soon be unneeded.
