### ISSUE TITLE
Raspberry Pi 4 support

### ISSUE THREAD

**Issue by DKolter** [gfx-rs/wgpu#1467]
Hello guys, 

I have recently installed the vulkan broadcom driver for the raspberry pi 4 and tested it by running the Sascha-Willems demos. They ran without issue at high performance, the ImGui example ran at ~200 FPS. Relieved to move away from old OpenGL 2.1 to your modern library using the vulkan backend, I launched an example from imgui-wgpu-rs. It runs at 20 FPS with visual artifacts such as shapes flickering or tearing. I don't know where to start searching for the bug, whether the driver is to blame or the ash vulkan loader, so please help me fix that issue. 

These examples were run on a fresh build from the recommended OS (32-bit) using the latest cargo and mesa driver available. I was able to reproduce the same effects using my other raspberry pi with an old build, so it doesn't seem to be local to my device.

Thanks in advance!

**Comment by FranLMSP** [comment]
I managed to get Pixels working on a Raspberry Pi 4 by setting this device descriptor parameters
```rust
    PixelsBuilder::new(width, height, surface_texture)
        .device_descriptor(wgpu::DeviceDescriptor {
            limits: wgpu::Limits {
                max_storage_textures_per_shader_stage: 4,
                max_texture_dimension_2d: 4096,
                max_texture_dimension_1d: 4096,
                ..wgpu::Limits::default()
            },
            ..wgpu::DeviceDescriptor::default()
        })
        .build()
```

**Comment by cymen** [comment]
The issue for winit adding support for xcb is here https://github.com/rust-windowing/winit/issues/5 (just adding to link these two issues together).

**Comment by cwfitzgerald** [comment]
I think, from reading this, this is closable.
