### ISSUE TITLE
Use persistent mapping when possible on the StagingBelt

### ISSUE THREAD

**Issue by siriux** [gfx-rs/wgpu#1468]
Wgpu currently doesn't support persistent mapping because the current webgpu specification doesn't do it.

But given that the StagingBelt is an internal utility of wgpu-rs intended for general use outside the web, couldn't it use it internally from gfx-rs when possible? With a fallback to the current implementation otherwise.

I'm not sure exactly how it compares in performance against the current StagingBelt implementation, but persistent mapping apparently has much less overhead on mobile platforms than the traditional ways of uploading.

**Comment by OlegOAndreev** [comment]
With current advice generally being "do not unmap buffers ever" is there any particular reason for unmap() to actually unmap the buffer?

FWIW, currently backends differ in this regard: Metal never unmaps, D3D12 always unmaps and Vulkan unmaps dedicated allocations (tens or hundreds of megabytes). Also interesting that Dawn D3D12 backend does unmap, but Vulkan backend never unmaps.

**Comment by kvark** [comment]
This is an internal implementation detail, I don't think a feature is needed for this. We try to unmap when possible, so that less memory is kept resident.

**Comment by cwfitzgerald** [comment]
I don't think this is going to happen anytime soon - persistent mapping may happen internally in wgpu-hal at some point though.
