### ISSUE TITLE
Huge memory usage on m1 soc

### ISSUE THREAD

**Issue by ghost** [gfx-rs/wgpu#1480]
**Description**
After a few seconds the program is running the memory usage becomes more and more until macOS kills the process because it goes out of memory

**Repro steps**
I'm just following the tutorial on [this page](https://sotrh.github.io/learn-wgpu) but I see a similar behavior with the Bevy engine that uses wgpu

**Screenshot**
<img width="383" alt="Schermata 2021-06-06 alle 12 26 53" src="https://user-images.githubusercontent.com/52113626/120921191-cec67600-c6c2-11eb-9b7e-f95191cdde32.png">

**Platform**
I'm on macOS Big Sur 11.3.1, using `wgpu` 0.8, on a 8G MacBook Pro with the M1 SoC

**Comment by cwfitzgerald** [comment]
Thanks for filing this! If you can provide either a wgpu trace or a repo that we could try to reproduce this, it would be extremely helpful.

**Comment by LolzDEV** [comment]
> Thanks for filing this! If you can provide either a wgpu trace or a repo that we could try to reproduce this, it would be extremely helpful.

Sure, [this](https://github.com/EditsFrameGames/yave) is the repo, how can I get the wgpu trace?

**Comment by cwfitzgerald** [comment]
Thanks! You can find instructions here: https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure

**Comment by kvark** [comment]
@LolzDEV that's pretty worrying! It would also help if you could run some of the wgpu-rs examples and see if it reproduces there. To run them, you can check out this repo and do `cargo run --example xx`, where `xx` is "cube", "skybox", etc

**Comment by LolzDEV** [comment]
@cwfitzgerald this is the trace generated: 
[YAVE_TRACE.zip](https://github.com/gfx-rs/wgpu/files/6756467/YAVE_TRACE.zip)

**Comment by LolzDEV** [comment]
> @LolzDEV that's pretty worrying! It would also help if you could run some of the wgpu-rs examples and see if it reproduces there. To run them, you can check out this repo and do `cargo run --example xx`, where `xx` is "cube", "skybox", etc

@kvark it seems that the examples are not having this behavior but on my x86 machine this doesn't apply to yave too

**Comment by kvark** [comment]
So it sounds like something fixed between wgpu-0.8 and master. Bevy has a port in progress on master, would you want to check it on M1 as well to confirm?

**Comment by LolzDEV** [comment]
I'll give a try soon

**Comment by LolzDEV** [comment]
> So it sounds like something fixed between wgpu-0.8 and master. Bevy has a port in progress on master, would you want to check it on M1 as well to confirm?

So, tried out, it seems to not be fixed yet...

**Comment by kvark** [comment]
Hmm. If examples aren't showing this, then we need to understand what Bevy is doing.

**Comment by LolzDEV** [comment]
I'm not using bevy at the moment, just wgpu, following step by step [this tutorial](https://sotrh.github.io/learn-wgpu) and also as I said on x86 machines it works just well

**Comment by jinleili** [comment]
@kvark Tested bevy 0.6 all 3D examples on M1 Max, each running for about 10 minutes with no memory leaks observed.

**Comment by AcrylicShrimp** [comment]
Same issue here. I'm using M1 Max on macOS Ventura, and my application consumes about 5GiB of memory. My application just writes small data(48 bytes) per frame, and does not render anything. On Windows 11 it is not happen on same configuration. It consumes about 280 MiB on Windows.

**Comment by cwfitzgerald** [comment]
@AcrylicShrimp could you file a separate issue with a reproduction case if you have one?

**Comment by AcrylicShrimp** [comment]
@cwfitzgerald I managed that issue. My case was I didn't call `StagingBelt::finish`. Please ignore my case, thanks.
