### ISSUE TITLE
Performing pipeline creation in the background or in parallel is inhibited by locks

### ISSUE THREAD

**Issue by Imberflur** [gfx-rs/wgpu#1485]
I previously moved our pipeline creation to background threads since the time spent there on the Dx12 backend is very noticeable but it looks like there are potentially locks taken during pipeline creation that prevent this from running concurrently with the main render loop.

### Examining  [`create_render_pipeline`](https://github.com/gfx-rs/wgpu/blob/a92b8549a8e2cb9dac781bafc5ed32828f3caf46/wgpu-core/src/device/mod.rs#L2106):

The first two are on the pipeline and bind groups layout storages.
```rust
        //TODO: only lock mutable if the layout is derived
        let (mut pipeline_layout_guard, mut token) = hub.pipeline_layouts.write(token);
        let (mut bgl_guard, mut token) = hub.bind_group_layouts.write(&mut token);
```
These are mutably used to pre-emptively insert errors in case there is a failure in creation of derived layouts.
```rust
        if let Some(ref ids) = implicit_context {
            pipeline_layout_guard.insert_error(ids.root_id, IMPLICIT_FAILURE);
            for &bgl_id in ids.group_ids.iter() {
                bgl_guard.insert_error(bgl_id, IMPLICIT_FAILURE);
            }
        }
```

They are also used to read the layouts for shader validation.
```rust
                        let pipeline_layout = pipeline_layout_guard
                            .get(pipeline_layout_id)
                            .map_err(|_| pipeline::CreateRenderPipelineError::InvalidLayout)?;
                        Some(Device::get_introspection_bind_group_layouts(
                            pipeline_layout,
                            &*bgl_guard,
                        ))
```
And again in the case of implicit layouts they are used to insert the successfully derived layouts.
```rust

        let pipeline_layout_id = match desc.layout {
            Some(id) => id,
            None => self.derive_pipeline_layout(
                self_id,
                implicit_context,
                derived_group_layouts,
                &mut *bgl_guard,
                &mut *pipeline_layout_guard,
            )?,
        };
```

Finally, just the pipeline layout storage is borrowed in a reference that is used in the pipeline description passed to the backend's `create_graphics_pipeline`.
```rust
        let layout = pipeline_layout_guard
            .get(pipeline_layout_id)
            .map_err(|_| pipeline::CreateRenderPipelineError::InvalidLayout)?;
            
         //...
         let pipeline_desc = hal::pso::GraphicsPipelineDesc {
            //...
            layout: &layout.raw,
```
The third lock is taken on the render passes and also used in the pipeline description. It looks like mutability is only needed here for inserting new entries if a matching render pass entry doesn't already exist.
```rust
let mut rp_lock = self.render_passes.lock();
```

### Where I anticipate most time is spent while holding locks during pipeline creation
The call to `create_graphics_pipeline` https://github.com/gfx-rs/wgpu/blob/a92b8549a8e2cb9dac781bafc5ed32828f3caf46/wgpu-core/src/device/mod.rs#L2577 (e.g. this is where the Dx12 driver spends a lot of time compiling the shaders for the pipeline)

I would need further profiling to identify if any of the other sections are significant.

### Where else are these resources locked mutably?
While it seems like would be easily possible to constrain  the mutable locks to brief sections during pipeline creation, it is less straightforward to work around the read access needed for the descriptor passed to `create_graphics_pipeline`.

These are sites that would be blocked by any long lived read access during pipeline creation:

- The main sites of mutable access I found for `pipeline_layouts` and `bind_group_layouts` are locks taken briefly during creation of new layouts and for dropping layouts.

- For `device.render_passes` I only found one other site where it is used which is in `RenderPassInfo::start` https://github.com/gfx-rs/wgpu/blob/eadaa1b7d8f585761e28445904fe619b180aca0d/wgpu-core/src/command/render.rs#L774 which follows a similar pattern of needing to potentially insert a render pass if it doesn't already exist.

- And of course if another pipeline is being created in parallel it would want at least brief mutable access to these resources.

### Another concern
There could also potentially be some conflict between shader module creation and the main render loop but I have not examined this.

**Comment by Imberflur** [comment]
Shader module creation doesn't appear to have any conflict with the main rendering loop.

However, it does need to mutably access the `shader_modules` to insert the new value:
https://github.com/gfx-rs/wgpu/blob/7978df83ef2be0835a621804958582358f398a95/wgpu-core/src/device/mod.rs#L3881
Which also has a long lived read lock during pipeline creation:
https://github.com/gfx-rs/wgpu/blob/7978df83ef2be0835a621804958582358f398a95/wgpu-core/src/device/mod.rs#L2008


This should not be an issue for my current use case though.

**Comment by Imberflur** [comment]
Here is a visualization of the current behavior using Tracy (sections where the thread is waiting on a lock are dimmer):
![image](https://user-images.githubusercontent.com/2002109/121632824-b2726280-ca4f-11eb-8e72-7325133043fd.png)

**Comment by Imberflur** [comment]
I fixed the minimum needed to get pipeline creation working in parallel with render passes. But I have now discovered that at least queue submission, swap chain presentation, and Queue::write_buffer all take a mutable lock on devices which causes a conflict between them and pipeline creation.
![image](https://user-images.githubusercontent.com/2002109/121646823-b314f400-ca63-11eb-98bb-69fe6bd8fd41.png)
![image](https://user-images.githubusercontent.com/2002109/121646893-c922b480-ca63-11eb-826e-2f476e30cc8f.png)

**Comment by cwfitzgerald** [comment]
Obsoleted by #2710
