### ISSUE TITLE
Make VertexBufferLayout own its VertexAttribute

### ISSUE THREAD

**Issue by FredrikNoren** [gfx-rs/wgpu#1490]
**Is your feature request related to a problem? Please describe.**
This is a tiny thing, but it's a bit hard to work with VertexBufferLayout's because I also have to keep the VertexAttribute's somewhere. This is mostly a problem when trying to generate shader_location's on the fly for different pipelines. I think this would be preferable in general as well (for instance BindGroupLayoutDescriptor; would be easier if it just owned its entires so that it can be returned from a function).

**Describe the solution you'd like**
It would be better if the VertexBufferLayout just owned them.

**Comment by FredrikNoren** [comment]
What I'm trying to do is this basically:
```
    fn position_desc<'a>(loc: u32) -> wgpu::VertexBufferLayout<'a> {
        wgpu::VertexBufferLayout {
            array_stride: 3 * 4,
            step_mode: wgpu::InputStepMode::Vertex,
            attributes: &[wgpu::VertexAttribute {
                offset: 0,
                shader_location: loc,
                format: wgpu::VertexFormat::Float32x3,
            }],
        }
    }
```
But I'm getting an error since `VertexAttribute` dies at the end of the function. If there's some other way this is intended to be accomplished I'd love to hear it

**Comment by kvark** [comment]
`wgpu-core` API uses `Cow`-based APIs for this reason. Cow allows to make this decision arbitrary on the user side.
But wgpu-rs doesn't have Cows any more. Introducing `Cow` just for this specifically is too exceptional, and introducing it for everything in wgpu-rs is too cumbersome to use.

For this reason, I recommend just using a typed arena on your end. Adding a list of `VertexAttribtue` to it returns a reference with the lifetime of the arena - https://docs.rs/typed-arena/2.0.1/typed_arena/struct.Arena.html#method.alloc_extend
So as long as your arena overlives the `RenderPipelineDescriptor`, you are good.

**Comment by FredrikNoren** [comment]
@kvark Thanks! I didn't know of typed arena, that does look like it could come in handy.

I can see the dilemma with how to design the interface. My gut feeling is that anything that is a descriptor/POCO would probably be easier to work with as owned, and using clone when/if necessary. But maybe there are places where that wouldn't work.

**Comment by erlendp** [comment]
I would tend to agree with @FredrikNoren regarding the layout just owning the attribute. Is there a compelling reason not to change this?

**Comment by kvark** [comment]
@erlendp the major reason is API consistency. We don't want to decide on a case by case basis if a particular thing is passed in a Vec/Cow/or slice. We want the API to be regular. So we aren't going to make an exception for this, especially since there are ways to work around it.

**Comment by FredrikNoren** [comment]
Hi, I'm getting stuck on this issue again. How would I for instance do something like this:

```
struct MyStruct {
  vertex_buffer_layouts: Vec<wgpu::VertexBufferLayout>
}
```

That won't compile since `VertexBufferLayout` requires a lifetime param, so I would need:

```
struct MyStruct<'a> {
  vertex_buffer_layouts: Vec<wgpu::VertexBufferLayout<'a>>
}
```

But now anything that holds MyStruct would need a lifetime parameter and so on. Is there a way to use the typed arena to solve this issue too?

**Comment by kvark** [comment]
I recently encountered this issue myself, and I still think it would be weird to bend the API for this particular case at the expense of consistency. Here is how I worked around it - https://github.com/kvark/baryon/blob/25a15992e6624ee1e863c49daf86fb536ae23255/src/lib.rs#L15
Does this help?

**Comment by FredrikNoren** [comment]
@kvark Hm no not really. I've tried to used `'static` too, but it quickly gets really complex to try to define everything upfront. For instance I'd have to define one static VertexBufferLayout for each texture coordinate set (1, 2, 3, 4 and so on).

Tbh as a user of the API I would definitely prefer the inconsistency over the hurdle of trying to marshal these objects the way I'm doing now :) I don't think it's just for VertexBufferLayout, I think almost anything which is `<'a>` now, if it can be removed it would make it easier to work with. The only place where I would prefer `<'a>` is where there's a performance reason to do so.

**Comment by FredrikNoren** [comment]
@kvark Sorry I was a bit tired and completely missed that you had solved the texture set problem by using const generics. That does help a little bit yeah, but I would still argue for getting rid of the `<'a>` if at all possible.

**Comment by kvark** [comment]
I'd be happy to provide a way to not deal with `'a` here, but this has to be consistent with the rest of the API.

**Comment by rocket-matt** [comment]
Why does it have to be consistent with the rest of the API, when clearly having it owned is a MUCH better interface decision.  I feel you're just cutting your nose off to spite your face here.  To insist on workarounds for a common use case just because of "consistency" is not a great reason IMHO.  This is clearly a good case where you break from the rest of the API.

Although I agree that consistency is very important in API design, but where it damages the ease of use, I believe consistency must fall down lower in the priority list.

**Comment by grovesNL** [comment]
@rocket-matt This doesn't usually come up for typical use cases, and there are also downsides to making it owned (e.g., extra heap allocations per layout if we used `Vec<VertexAttribute>` here for convenience) so it's not clearly a net benefit overall. Maybe there's another natural way to model your renderer that fits the current API while avoiding the need for workarounds like typed arena?

**Comment by cwfitzgerald** [comment]
This has since been fixed by advancements in rust const evaluation allowing these to be promoted to const more easily
