### ISSUE TITLE
Create an API for managing fences

### ISSUE THREAD

**Issue by Xaeroxe** [gfx-rs/wgpu#1498]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to determine when the GPU has finished submitted work. This can pose a problem when one needs to, for example, resize the swapchain without triggering a panic. It can also pose a problem when rendering to a Texture, as there is no way to determine when the work is done.

**Describe the solution you'd like**
Similar to how Textures or Buffers are managed, fences ought to be a managed resource too.

**Describe alternatives you've considered**
It may be possible to use a `Future` returned from the submission of the command buffer. However I don't think this will have the desired performance characteristics. A future being returned would require wgpu to do one of two things

1. Hold a collection of blocked threads internally which would be responsible for notifying the waker.
2. Frequently check the internal fences and notify the corresponding waker when a fence is found in a signaled state.

The first solution would result in more threads than the application strictly needs, and the second solution runs the risk of introducing a significant delay between the fence signal and the future being resolved. So it seems the best solution would be to pass this choice onto the user. They can either block a thread, or frequently check the fence state, depending on what performance characteristics they want.

**Additional context**
I am using this information in the construction of a multi-stage pipeline with support for multiple frames in-flight. I must build the feature described here. The decision for wgpu is only if they wish to accept my PR.

**Comment by kvark** [comment]
Hi @Xaeroxe !

In WebGPU upstream, the way to know if GPU is done is by using [onSubmittedWorkDone](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-onsubmittedworkdone). We are missing this part of the API, and we need it.

> This can pose a problem when one needs to, for example, resize the swapchain without triggering a panic.

Is this really a problem? wgpu-rs examples can be resized just fine, last time I checked.

> It's currently not possible to determine when the GPU has finished submitted work

There *is* actually a way, it's just not the most convenient one. You'd basically have a staging buffer (`COPY_DST | MAP_READ`), and in the submission you'd copy something into this buffer. After submitting the work, you'd request it to be mapped. The request will come back after GPU is done with the submission.

**Comment by Xaeroxe** [comment]
> Is this really a problem? wgpu-rs examples can be resized just fine, last time I checked.

Yes, you can demonstrate this panic by resizing the window a lot. Just shake the triangle example back and forth a few times, it might take a few seconds but it should eventually panic. Of course this isn't a common usage but it does demonstrate there is likely an infrequent panic problem here associated with resizing. If you're having difficulty reproducing this try using Windows 10.

**Comment by Xaeroxe** [comment]
> onSubmittedWorkDone

This sounds like the 'Future' approach I described. How were you expecting this future to be notified?

**Comment by kvark** [comment]
> How were you expecting this future to be notified?

Through the same mechanism as the [mapping](https://wgpu.rs/doc/wgpu/struct.BufferSlice.html#method.map_async) today. It's not completely free of issues - see https://github.com/gfx-rs/wgpu-rs/pull/727, but it's in the same bin as other things we have to do anyway.

> Yes, you can demonstrate this panic by resizing the window a lot.

I'm tempted to just say it's a backend issue, not the user issue. If the backend has no other means of making resizes safe than waiting for the GPU to finish, it can wait. But the user shouldn't try to carefully work their way around a panic - the panic shouldn't be happening occasionally, anyway. wgpu-rs aims to be safe and portable, the code should just work.

**Comment by Xaeroxe** [comment]
> Through the same mechanism as the mapping today.

I see, so the second solution I described. Since you let downstream dictate how often poll is called this might actually work pretty well. Would you like me to implement it?

**Comment by kvark** [comment]
If you can help getting it in, this would be great! I think it should be fairly straightforward: we already have the callback mechanism and fence tracking. Just need to piggy back on it.
