### ISSUE TITLE
Merge Surface and Swapchain

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1499]
See https://github.com/gpuweb/gpuweb/pull/1810

**Comment by niklaskorz** [comment]
I might be interested in implementing this. I suppose this involves all three layers of wgpu, i.e. `wgpu-hal`, `wgpu-core` and `wgpu`? Or only the last two?

**Comment by kvark** [comment]
Wgpu-hal already has them merged, so this is just wgpu-core and wgpu-rs

**Comment by niklaskorz** [comment]
Great :) Shouldn't be too complicated then, I will give it a try

**Comment by kvark** [comment]
Fixed by #1786
