### ISSUE TITLE
Use `naga::Module` as a `ShaderSource` for non web targets

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/wgpu#1507]
**Is your feature request related to a problem? Please describe.**
Use `naga::Module` as a `ShaderSource` for non web targets like spv.

**Describe the solution you'd like**
Accept `naga::Module` in ShaderSource. `wgpu-core` already accept it.
https://github.com/gfx-rs/wgpu/blob/0c76819ef76fd25a7faa619059290cd8b2687980/wgpu/src/lib.rs#L732-L745

**Describe alternatives you've considered**
Use `naga` to produce `wgsl` or `spv` from IR in user projects.

**Comment by kvark** [comment]
I think that would be fine from the API point of view. Now that there is a WGSL backend, we can generate the shader for the web target internally.
However, it may be less usable than it seems: naga modules are not clone-able. So if @Frizi wants to try it out and report back, we can use this input to figure out if this can be reasonably exposed.

**Comment by daxpedda** [comment]
This can be closed I believe.
Has been implemented by #2801. I also made `Module` cloneable in https://github.com/gfx-rs/naga/pull/2013.
