### ISSUE TITLE
Unintended feature unification leads to failed compile if used as a dependency

### ISSUE THREAD

**Issue by ElectronicRU** [gfx-rs/wgpu#1517]
**Description**
When specifying git master dependency on wgpu crate, it fails to compile successfully on non-macOS platforms.

**Repro steps**
Create an empty project.

Add `wgpu = {git="https://github.com/gfx-rs/wgpu.git", branch="master"}` to dependencies

`cargo build`

**Expected vs observed behavior**
Observed behaviour: an explosion of `unresolved crate mtl` errors.

Expected behaviour: none of that business.

**Extra materials**
According to https://github.com/rust-lang/cargo/issues/1197, target-specific dependencies participate in feature resolution by merging their feature sets.

Since `wgpu-core` depends on `wgpu-hal` with features=vulkan and features=metal, feature set for `wgpu-hal` gets unified to vulkan AND metal.

Since metal feature is enabled, metal module tries to compile.

But it cannot, since extern crate mtl is only available on macOS.

Boom.

**Possible solutions**

- Drag `vulkan` and `metal` features throughout the dependency stack, into `wgpu` proper. Chickening out - the user would have to specify the backend.
- Guard module `metal` of gfx-hal by `cfg`. Do away with feature flags, possibly, since they turn out useless in this situation. Duplication of cfg flags but probably the cleanest solution.
- Maybe something else?

**Comment by ElectronicRU** [comment]
It has been brought to my attention that it's intended to be used with resolver=2. However, you can still enable a feature that completely breaks compilation -- maybe guarding mod metal behind a cfg anyway is a good idea.

**Comment by kvark** [comment]
We could technically guard the features by platforms, but it has a nasty downside. On macOS, we still want Vulkan and Gles backends to compile, but we don't want wgpu-core to use them. So if we gate the wgpu-hal backends per platform, macOS users would still see Gles and Vulkan backends compiling, even though they can't be used. It seems to me that we'd much rather have a strong signal to them that "resolver=2" is required, instead of pretending that it's OK otherwise, and have longer compile times.

> However, you can still enable a feature that completely breaks compilation

I think that's totally fine in Rust. You don't have to be able to enable features. The only thing about features that needs to be preserved is composability.

**Comment by ElectronicRU** [comment]
Here's the patch I propose, then:
```diff
From a6c584589d9ce0558aea2b5b59d0429e3dd7b255 Mon Sep 17 00:00:00 2001
From: Alex S <alex0player@gmail.com>
Date: Sat, 19 Jun 2021 14:19:39 +0300
Subject: Better compile error for not using resolver=2.

---
 wgpu-hal/src/lib.rs | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/wgpu-hal/src/lib.rs b/wgpu-hal/src/lib.rs
index 97e3c7c4..1c35134a 100644
--- a/wgpu-hal/src/lib.rs
+++ b/wgpu-hal/src/lib.rs
@@ -44,9 +44,12 @@
     // We don't match on a reference, unless required.
     clippy::pattern_type_mismatch,
 )]
+#[cfg(all(feature="metal", not(any(target_os="macos", target_os="ios"))))]
+compile_error!("Metal backend enabled on non-Apple OS. Is your project using resolver=2?");
+

 mod empty;
-#[cfg(feature = "metal")]
+#[cfg(all(feature = "metal", any(target_os="macos", target_os="ios")))]
 mod metal;
 #[cfg(feature = "vulkan")]
 mod vulkan;
--
2.24.1.windows.2
```

**Comment by kvark** [comment]
That seems like a good compromise!
