### ISSUE TITLE
wgpu logs about downlevel limits on my device

### ISSUE THREAD

**Issue by LPGhatguy** [gfx-rs/wgpu#1529]
**Description**
Starting in 0.9, wgpu mentions downlevel feature support on my device, which is not a downlevel device. From a Discord conversation in the Rust gamedev server, this sounds like it could be related to using `enumerate_devices`. Log output:

```
[INFO  cyrtanthus::renderer::core] Available adapters:
[INFO  cyrtanthus::renderer::core] GeForce GTX 1050 Ti on Vulkan
[INFO  cyrtanthus::renderer::core] NVIDIA GeForce GTX 1050 Ti on Dx12
[INFO  cyrtanthus::renderer::core] Microsoft Basic Render Driver on Dx12
[INFO  cyrtanthus::renderer::core] Chose GeForce GTX 1050 Ti on Vulkan
[WARN  wgpu_core::instance] The underlying API or device in use does not support enough features to be a fully
compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program
on native and not in a browser and wish to limit the features you use to the supported subset, call
Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform
supports.
```

**Repro steps**
Enumerate devices and create one. I use this code:

```rust
log::info!("Available adapters:");
for adapter in instance.enumerate_adapters(wgpu::BackendBit::PRIMARY) {
    let info = adapter.get_info();
    log::info!("{} on {:?}", info.name, info.backend);
}

let adapter = instance
    .request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        compatible_surface: Some(surface),
    })
    .await
    .unwrap();

let adapter_info = adapter.get_info();
log::info!("Chose {} on {:?}", adapter_info.name, adapter_info.backend);
```

**Expected vs observed behavior**
I should get no output, but wgpu tells me my platform is downlevel.

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**
* Windows 10 20H2
* Nvidia drivers v456.71
* GTX 1050 Ti
* wgpu 0.9

**Comment by cwfitzgerald** [comment]
An additional problem here is that all of those adapters offer aniso, so this means that dx12 isn't properly exposing aniso. I would patch gfx-hal but...
