### ISSUE TITLE
[Metal] Memory leak in imgui-wgpu-rs

### ISSUE THREAD

**Issue by sanbox-irl** [gfx-rs/wgpu#1537]
**Description**
There appears to be something like a memory leak in <https://github.com/Yatekii/imgui-wgpu-rs>'s example `custom_textures`. You can run it with:
```
cargo run --examples custom_textures
```
That repo is on version 0.8.1 but on a local, I updated it to 0.9.0 (it updates without issue) and the issue persists.

Specifically, we start out at about 80mgs of memory, which seems about right, and then skyrocket somewhere near a gig. Sometimes much more than that, other times less than that. I'm not sure what's causing it.

I have chosen the file the issue here because looking through imgui-wgpu-rs, there doesn't seem to be anything obviously leaky that's occurring, so I suspect the problem is in WGPU or lower.

**Platform**
M1 Mac mini, Big Sur. I don't believe this has anything to do with the arm nature of this Mac, but I am available to run tests if asked at any time 9-5 EST.

**Comment by kvark** [comment]
Interesting! I wouldn't expect the memory usage to skyrocket like this. At least gfx-backend-metal is not leaking, or otherwise Dota2 wouldn't run. So if there is a leak, it's something about wgpu-core, or how it uses gfx.

**Comment by sanbox-irl** [comment]
okay not to be a crazy person here, but to absolutely be crazy, it seems to have something to do with the window being in the background not correctly clearing the submitted data within the queue?

I can currently reproduce by running imgui-wgpu-rs...

```
cargo run --examples hello_world
```

and then navigate within the Demo window that comes up to the `Widgets` and then `Plot Widgets` tab (which generates a lot of geometry).

I'm not sure why in my own application though, this happens MUCH faster. Still will investigate though

**Comment by cwfitzgerald** [comment]
Making as superceded by #1782
