### ISSUE TITLE
Clean up device resources properly

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#155]
We are currently not destroying everything (in the right order) upon termination of a device/adapter/instance. This may be one of the reasons we can't create more than 64 devices in #152

**Comment by GabrielMajeri** [comment]
How could we investigate what's still not properly cleaned up?

**Comment by kvark** [comment]
I suppose the test here is - run `wgpu-rs` examples under Vulkan with validation, and see if any shutdown-related warnings are printed on exit.

**Comment by GabrielMajeri** [comment]
I've run each of the examples with validation layers enabled, and there was no error printed upon closing.

**Comment by kvark** [comment]
Thank you!
