### ISSUE TITLE
Buffer gets cleared after it has already been used

### ISSUE THREAD

**Issue by AnotherNathan** [gfx-rs/wgpu#1555]
**Description**
A Buffer gets cleared in the subsequent frame after its creation even though it has already been used in the previous frame.

**Repro steps**
The provided example creates a buffer every other frame, fills it using a compute shader and then uses this buffer to draw a colored triangle (the buffer is the source for the color).

**Expected vs observed behavior**
The triangle should always be colored since the buffer gets filled and then not touched anymore for 2 frames. After these 2 frames the buffer gets replaced with a new one.
However the triangle flickers in color and black. Running it in RenderDoc shows that a vkCmdFillBuffer commands gets emitted in the subsequent frame after the buffers creation and first use.

**Example**
[wgpu-buffer-clear-bug.zip](https://github.com/gfx-rs/wgpu/files/6718642/wgpu-buffer-clear-bug.zip)

**Platform**
Windows 10
wgpu-0.9 vulkan backend
AMD RX570 driver version 21.4.1

**Comment by AnotherNathan** [comment]
For anybody experiencing this issues as well, as a workaround you can manually call CommandEncoder::clear_buffer after the creation of the buffer.

**Comment by kvark** [comment]
@Wumpf you know the buffer initialization well. Just cc-ing you in case you have time or ideas. I'm currently trying to finish GLES support, so will only be able to look at this some time later next week.

**Comment by Wumpf** [comment]
No flickering on master, but a steady stream of validation errors instead
```
[2021-06-27T10:01:42Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DESCRIPTOR_SET, hndl: 0x3d660300000001df, name: ?)
[2021-06-27T10:01:42Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkFreeDescriptorSets-pDescriptorSets-00309 (0xbfce1114)]
        Validation Error: [ VUID-vkFreeDescriptorSets-pDescriptorSets-00309 ] Object 0: handle = 0x9b7d4000000001e6, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xbfce1114 | Cannot call vkFreeDescriptorSets() on VkDescriptorSet 0x9b7d4000000001e6[] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to any element of pDescriptorSets must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.176.1/windows/1.2-extensions/vkspec.html#VUID-vkFreeDescriptorSets-pDescriptorSets-00309)```

**Comment by Wumpf** [comment]
validation errors I'm seeing on master are most likely same as in #1552

**Comment by kvark** [comment]
@Wumpf so this issue can be closed now, right?

**Comment by Wumpf** [comment]
Yep!
