### ISSUE TITLE
Command buffer execution aborted after buffer deleted (OSX)

### ISSUE THREAD

**Issue by FredrikNoren** [gfx-rs/wgpu#1556]
**Description**
I'm getting the following error on OSX: `Execution of the command buffer was aborted due to an error during execution. Invalid Resource (IOAF code 9)`. This happens only after I remove entities in my application, which results (in my application code) in a buffer getting deleted. When I just let that buffer live on I don't get the error.

**Repro steps**
Render something, then delete an instancing buffer right after the commands are submitted.

**Expected vs observed behavior**
Would expect the buffer to live on long enough internally for the render to complete.

**Extra materials**
None

**Platform**
OSX BigSur, m1 chip. wgpu 0.9.0.

**Comment by kvark** [comment]
Possibly related to #1547 and #1550, which didn't get back-ported to wgpu-0.9 yet.
If you can test your app on master, that would be most useful!

**Comment by FredrikNoren** [comment]
@kvark Just tested it here. I was getting the error sporadically on 0.9.0, but never saw it on master, so I'll assume it's fixed on master. Closing this. I'll re-open if I see it again on master though.
