### ISSUE TITLE
Bunnymark Screenshot is Empty Screen

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#1557]
**Description**
Bunnymark shows an empty screen. The official screenshot is empty as well, indicating this happens on ci just the same (i.e. cementing whatever underlying bug there is into the new (?) image comparison tests)

**Repro steps**
cargo run --example bunnymark

**Expected vs observed behavior**
expected: something
observed: nothing

**Platform**
Windows, Vulkan

**TODO:**
- [ ] Update test framework to automatically tick to get things on the screen.
- [ ] Add readme with instructions to hit spacebar to see bunnies.

**Comment by kvark** [comment]
It requires you to hit "space" to spawn bunnies.
@cwfitzgerald I think we should exclude it from snapshot testing

**Comment by Wumpf** [comment]
I see :). Needs a readme then I guess.
Also it doesn't spawn bunny, but flipped wgpu logos. I feel betrayed!

**Comment by cwfitzgerald** [comment]
@kvark i was planning on adding a way to have the snapshot automatically tick X times so that there is something visible, just didn't do it yet.
