### ISSUE TITLE
map_read_async never returns after submitting ~30 command buffers

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#156]
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver, version 418

Occurs on both master and https://github.com/gfx-rs/wgpu/pull/154

It also makes my machine unresponsive for ~30s

https://github.com/rukai/wgpu/blob/map_read_async_never_returns/examples/repro/main.rs

**Comment by kvark** [comment]
Thanks @rukai ! The tests you are doing, even if artificial, are hugely helpful. I'm excited to get this fixed and integrated as a test into the project.

**Comment by rukai** [comment]
The issue still occurs but now I get a sad face
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(false)`,
 right: `Ok(true)`: GPU got stuck :(', wgpu-native/src/device.rs:186:13
```

Is this closed because the issue is due to a driver bug?
