### ISSUE TITLE
QuerySet size limit off-by-one

### ISSUE THREAD

**Issue by HalfVoxel** [gfx-rs/wgpu#1560]
**Description**
According to the documentation, the number of queries in a single QuerySet object is limited to at most 8192. However, the code will currently throw an error if the number of queries is *equal or higher* to 8192. So it is my understanding that having exactly 8192 queries should be allowed, but currently this throws an error.

Relevant code in wgpu:
![image](https://user-images.githubusercontent.com/1144597/123542465-1da77e80-d74a-11eb-9934-c5e9825efec7.png)

**Repro steps**

```
device.create_query_set(&wgpu::QuerySetDescriptor {
     ty: wgpu::QueryType::Timestamp,
     count: 8192,
})
````

**Expected vs observed behavior**
Expected: no error
Observed: `Validation error: 8192 is too many queries for a single QuerySet. QuerySets cannot be made more than 8192 queries`.

If everyone agrees that this is indeed a bug, I can make a PR.

**Comment by kvark** [comment]
Indeed a bug, thank you for detecting this!
