### ISSUE TITLE
Warnings when using Metal backend

### ISSUE THREAD

**Issue by berendkleinhaneveld** [gfx-rs/wgpu#1566]
**Description**
When running with the Metal backend, I get the following warning:
`Missing internal features: ROBUST_BUFFER_ACCESS | SAMPLE_RATE_SHADING`

**Repro steps**
Create a device using the Metal backend.

**Expected vs observed behavior**
Did not expect to see such a warning.

**Platform**
macOS 11.4 (Big Sur), MacBook Air M1 (running with Rosetta). Version of wgpu: 0.8.0.2 (which is included in wgpu-py 0.5.4)

@almarklein

**Comment by cwfitzgerald** [comment]
This is an old version of wgpu and has since been fixed. It is a superficial issue only where the metal backend didn't label features correctly.
