### ISSUE TITLE
Create Common Interface for Validation Warnings

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1567]
**Is your feature request related to a problem? Please describe.**

We want to validate that all tests pass without any validation issues. The best way to do this would be to communicate validation issues to the tests via a common callback. This needs to be built into wgpu because there are 4 different backends we need to listen to validation errors from and they all need different code to listen to them.

**Describe the solution you'd like**

An interface like:

```
impl Device {
    pub fn register_validation_callback(&self, function: Box<dyn Fn(...));
}
```

This would allow the outside to listen to validation. We can easily paper over the native vs non-native thing because we can just ignore the callback on web or in release.

**Describe alternatives you've considered**

Listening to stdout. This gets very nasty once parallel testing is involved and is basically abusing side-effects in a way I'm not really comfortable with.

**Additional context**

Related: #1383

**Comment by kvark** [comment]
That sounds pretty interesting! Here are two edits:
  1. We'd also need to pass the priority filter (error/warning/info). We can use `log::Level` for this
  2. We'd probably want to pass this callback in the `InstanceDescriptior` instead of a method on the device.

**Comment by cwfitzgerald** [comment]
Solved with new hal

**Comment by cwfitzgerald** [comment]
Closed the wrong issue

**Comment by cwfitzgerald** [comment]
Solved with validation canary.
