### ISSUE TITLE
Using wgpu with GLFW causes system freeze on window close

### ISSUE THREAD

**Issue by caelunshun** [gfx-rs/wgpu#1570]
**Description**
A `wgpu` application using GLFW instead of `winit` will occasionally hang my system for ~10 seconds when shutting down. The issue also happens with `minifb`, and possibly other window management crates.

Additionally, resizing the window freezes the application, and the whole system hangs when I kill the process. 

Possibly related to #318, except changing the present mode does not solve the problem.

**Repro steps**
Run the `hello-triangle` example ported to GLFW: [source here](https://gist.github.com/caelunshun/b0a52181361799d358a849b30fe2d30b). Then terminate the process with ctrl-C.

**Platform**
Ubuntu 18.04 running an NVIDIA GPU with driver version 460. The issue happens on the master branch as well as versions 0.9, 0.8, and 0.7. I haven't tested further back.

**Comment by cwfitzgerald** [comment]
Is there any way to test where it is hanging? If this is also happening with minifb, this feels like an issue at another layer in the stack (maybe glfw).

**Comment by caelunshun** [comment]
Here's the stacktrace in a debugger:
![wgpu_stacktrace](https://user-images.githubusercontent.com/25177429/124314108-1e1b8d00-db2f-11eb-86f6-bd466d55c879.png)

**Comment by cwfitzgerald** [comment]
So it seems we're literally just waiting for the gpu to finish whatever it is doing. I'm not sure what we can do about that 🤔

**Comment by kvark** [comment]
I think this particular `wait` isn't really needed, since we are at the end of destruction clean-up, and we waited previously before starting it. But it is also deep in the stack (in wgpu-hal/vulkan), and it should be totally valid to do as long as the Vulkan device is not corrupted. Not sure what to do about this.

@caelunshun do you hook up env_logger? I wonder if Vulkan validation says anything.

**Comment by caelunshun** [comment]
> do you hook up env_logger? I wonder if Vulkan validation says anything.

No validation errors in the logs—the last message that gets printed is
```
[2021-07-03T20:55:50Z INFO  wgpu_core::hub] Dropping Global
```
before the program hangs.

**Comment by kvark** [comment]
Maybe we are trying to destroy the surface, and GLFW has already deleted the window our surface was created from.
This is related to the concept of Window/Surface API safety - #1463

**Comment by teoxoy** [comment]
It has been some time, @caelunshun is this still an issue?

**Comment by Wumpf** [comment]
closing as stale.
Please re-open if more information surfaces
