### ISSUE TITLE
Support SamplerArray

### ISSUE THREAD

**Issue by igaryhe** [gfx-rs/wgpu#1572]
**Is your feature request related to a problem? Please describe.**
Currently wgpu supports `BufferArray` and `TextureViewArray`. It would be great if the API could also have `SamplerArray`.

**Describe the solution you'd like**
I'm not sure if it could work by simply adding `SamplerArray` at places where `BufferArray` appears.

**Describe alternatives you've considered**
I don't have an alternative solution yet.

**Additional context**

**Comment by cwfitzgerald** [comment]
Done
