### ISSUE TITLE
WGSL storage texture compute shader incorrectly transpiling to Metal buffer

### ISSUE THREAD

**Issue by superdump** [gfx-rs/wgpu#1581]
**Description**

Rust wgpu code to make the BindGroupLayout and BindGroup, WGSL source code (ported from GPLv3-licensed code, fyi), the full transpiled metal code and the error are here: <https://gist.github.com/superdump/d3409f9d32b322e98f746674eca3f2bf>

program_source:192:3: error: type 'metal::texture2d<float, metal::access::read>' is not valid for attribute 'buffer'
, metal::texture2d<float, metal::access::read> b_texture_r [[buffer(0)]]

**Repro steps**

Try to use the above shader on macOS. It's from this repository: https://github.com/TheRawMeatball/bevy-compute Just `cargo run --release`.

**Expected vs observed behavior**

I guess the problem is that the `buffer(0)` in the metal code should be `texture(0)` and the indices of the subsequent 2 textures should be one higher.

**Platform**

This issue happens with wgpu 0.8.1 and wgpu 0.9 on macOS.

**Comment by kvark** [comment]
Thank you for filing!
I think what's happening here is that we are trying to include an entry point (with its bindings) that is not compatible with the pipeline layout as specified in the `Options`. Currently, the layout is only checked for the presence of bindings, but not for their types.

**Comment by kvark** [comment]
@superdump thank you for filing this!
For the future, please just record an [API trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure) and attach it zipped. (no need for this issue now)
Setting up `zld`, nightly compiler, and building bevy is somewhat non-trivial :)

**Comment by kvark** [comment]
Actually, I give up, I can't build that example. I'll still merge the fix though.

**Comment by kvark** [comment]
We'll update Naga dependency ASAP

**Comment by superdump** [comment]
Just to note that I've managed to cobble things together across all the renaming that happened in wgpu and this works for me. :) Thanks!
