### ISSUE TITLE
-2005270523 on queue.write_buffer() on DX12

### ISSUE THREAD

**Issue by MrMarnic** [gfx-rs/wgpu#1601]
**Description**
When I use queue.write_buffer() on my non-dynamic uniform buffers I get the error in the headline.

**Repro steps**
Write to a uniform buffer.

**Expected vs observed behavior**
Should not crash vs crashes

**Extra materials**
Stacktrace: https://gist.github.com/MrMarnic/acd1a275e9562241e9d077e860461cea
Visual Studio log: https://gist.github.com/MrMarnic/a4e09b39b272fe7f087f2af1f5018a67

Code:
`queue.write_buffer(&self.buffers[0],0,&data);`

**Platform**
OS: Windows 10
GPU: NVIDIA GeForce GTX 1080 Ti
Device-Type: DiscreteGpu
wgpu-version: 0.8.1

**Comment by cwfitzgerald** [comment]
This is another device removal. Could you make sure you are running in debug? Note that wgpu 0.8 is old and is no longer maintained.

**Comment by MrMarnic** [comment]
That was the problem. It is working now with wgpu-version 0.9.0
