### ISSUE TITLE
 VUID-vkAcquireNextImageKHR-fence-01287 when running multiple instances

### ISSUE THREAD

**Issue by ben-wallis** [gfx-rs/wgpu#1605]
**Description**
When running multiple instances of [Veloren ](https://gitlab.com/veloren/veloren/) (a game using wgpu for rendering) the game freezes and both instances log the following vulkan validation error at a rate of one per second:

> Jul 05 22:17:37.760 ERROR gfx_backend_vulkan:
> VALIDATION [VUID-vkAcquireNextImageKHR-fence-01287 (0xc64a2b7)] : Validation Error: [ VUID-vkAcquireNextImageKHR-fence-01287 ] Object 0: handle = 0x5b450900000006cc, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0xc64a2b7 | vkAcquireNextImageKHR(): VkFence 0x5b450900000006cc[] is already in use by another submission. The Vulkan spec states: If fence is not VK_NULL_HANDLE it must be unsignaled and must not be associated with any other queue command that has not yet completed execution on that queue (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkAcquireNextImageKHR-fence-01287)
> object info: (type: FENCE, hndl: 0x5b450900000006cc)

**Repro steps**
Run two instances of `veloren-voxygen`. Veloren's master branch is currently on a commit inbetween wgpu 0.8 and 0.9 but I have confirmed the same behavior on wgpu 0.9 as well.

**Expected vs observed behavior**
Multiple instances of the game should be able to run side by side, but doing so causes both to lock up. A possibly unrelated issue happens when running multiple instances under DX12, and the issue is not present at all on DX11. The issue is apparently not present on the Linux build of Veloren.

**Extra materials**
voxygen log showing wgpu log output and validation errors: [voxygen log.txt](https://github.com/gfx-rs/wgpu/files/6766233/voxygen.log.txt)
zip containing two wgpu API traces of two clients running simultaneously that locked up: https://drive.google.com/file/d/19DeJYDzN2wXU3TjbBRzPNAX_lgvj0CJU/view?usp=sharing
DX12 panic that occurs when running multiple instances: [dx12_panic.txt](https://github.com/gfx-rs/wgpu/files/6766244/dx12_panic.txt)

**Platform**
Windows 10 21H1 Build 19043.1052
NVidia GeForce GTX 970

**Comment by kvark** [comment]
Honestly sounds like a driver issue to me...

**Comment by ben-wallis** [comment]
For reference, the NVidia driver in use when reproducing this is 471.11 (06/22/2021)

**Comment by cwfitzgerald** [comment]
Closing to the new hal rewrite. If it's still an issue, refile
