### ISSUE TITLE
Reduce Example Dep Set

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1610]
**Is your feature request related to a problem? Please describe.**

Wgpu's examples have a lot of deps, which can likely be culled down.

**Additional context**

When testing on weak systems (like the rpi) building the examples an be a 30 minute affair. While a lot of this is needed, we definitely can improve this.

We might also look at the wgpu non-dev dep tree to see if there are any gains to be had.

**Comment by Craig-Macomber** [comment]
I took a quick look at this. I don't have a workflow for measuring the impact, but I made a PR that should help a little: #1692

**Comment by cwfitzgerald** [comment]
Not really a priority right now.
