### ISSUE TITLE
Building wgpu client with trace enabled for wasm fails

### ISSUE THREAD

**Issue by blakej11** [gfx-rs/wgpu#1619]
**Description**
I have a project based on current wgpu (commit e27fbb821bb3397069d0a82ef8da8e151feb0647).  When building it for wasm, I compile it with `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --no-default-features --target wasm32-unknown-unknown`.  When I try to build it with the "trace" feature enabled in its wgpu dependency, it fails while trying to build `libloading 0.7.0`; the errors are of the form:

```
error[E0433]: failed to resolve: use of undeclared crate or module `imp`
  --> /Users/blakej/.cargo/registry/src/github.com-1ecc6299db9ec823/libloading-0.7.0/src/lib.rs:63:20
   |
63 | pub struct Library(imp::Library);
   |                    ^^^ use of undeclared crate or module `imp`

```

The problem is presumably that libloading is being compiled at all, which doesn't seem to make sense for a wasm target. 

I wasn't able to figure out exactly what was inducing it to be compiled, but I noticed that if I removed the `"wgc/trace"` entry in the `trace` feature in `wgpu/wgpu/Cargo.toml` (in a local copy of `wgpu`), it stopped trying to pull in that dependency.

**Platform**
macOS 11.4, wgpu snapshot listed above.

**Comment by kvark** [comment]
Hmm, nothing obvious here:
https://github.com/gfx-rs/wgpu/blob/e27fbb821bb3397069d0a82ef8da8e151feb0647/wgpu-core/Cargo.toml#L17

At the same time, `trace` feature isn't usable in wasm at all, so this isn't a blocker for anyone.

**Comment by RodogInfinite** [comment]
I got the same issue when trying to run the examples [on the web](https://github.com/gfx-rs/wgpu/wiki/Running-on-the-Web-with-WebGPU-and-WebGL) with a local copy of this repo. It looks like this might be solved with libloading 0.7.2 according to [ Fails to build to wasm32-unknown-unknown target #91 ](https://github.com/nagisa/rust_libloading/issues/91). I'm not sure where exactly the solution should be implemented though since I'm just getting started by running examples.

**Comment by kvark** [comment]
we could just require libloading 0.7.2 in the dependencies (instead of 0.7)

**Comment by teoxoy** [comment]
There has recently been some work improving which features get enabled depending on platform.

@blakej11 @RodogInfinite is this still an issue on current master (try forcing libloading 0.7.0)?
