### ISSUE TITLE
Add a C compute example

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#162]
As a follow-up to #160 we should have a minimal compute example in C (aka `hello_compute`), so that the shaders can stay here.

**Comment by Napokue** [comment]
Will look into this one, if that is okay.

**Comment by kvark** [comment]
@Napokue awesome, looking forward to it!

**Comment by Napokue** [comment]
Will continue this week with this issue now that #188 is fixed

**Comment by kvark** [comment]
Fixed by #203
