### ISSUE TITLE
`device.create_texture_with_data` implicitly requires `COPY_DST`

### ISSUE THREAD

**Issue by HalfVoxel** [gfx-rs/wgpu#1621]
**Description**
The documentation for `device.create_texture_with_data` doesn't mention that the usage must contain `COPY_DST`, but it also doesn't implicitly add that flag. I think it should either mention that `COPY_DST` is required or add it implicitly. Not sure which is the desired way to go though.

Right now it fails with:
```
thread 'main' panicked at 'Error in Queue::write_texture: destination buffer/texture is missing the `COPY_DST` usage
```

**Comment by cwfitzgerald** [comment]
We should just implicitly add this as there is no performance downside to having COPY_DST.
