### ISSUE TITLE
Update ImageDataLayout's rows_per_image documentation to document what units are expected.

### ISSUE THREAD

**Issue by StarArawn** [gfx-rs/wgpu#1626]
The wording currently is:
> Rows that make up a single "image". Each "image" is one layer in the z direction of a 3D image. May be larger than copy_size.y. Required if there are multiple images (i.e. the depth is more than one)

Which is a little confusing because I assumed the value should be a row count in the image. Instead it seems to be a Texel size value of how large each row is? If the documentation could be updated to better explain the units expected here it would help out a ton!

**Comment by kvark** [comment]
FYI, both `rows_per_image` and `bytes_per_row` talk about texel block rows, where texel block can be 2x2 or 4x4 for compressed textures.
