### ISSUE TITLE
Support BindGroups with fewer elements in Binding Array than in BindGroupLayoutEntry

### ISSUE THREAD

**Issue by igaryhe** [gfx-rs/wgpu#1635]
**Is your feature request related to a problem? Please describe.**
Current wgpu could support unsized binding array via `Features::UNSIZED_BINDING_ARRAY`. However, users still have to manually set the array size of the binding in `BindGroupLayoutEntry`. Is it possible for wgpu to fully support unsized binding array?

**Describe the solution you'd like**
Maybe we could provide an API to let users specify a maximum array size

**Describe alternatives you've considered**

**Additional context**

**Comment by cwfitzgerald** [comment]
Unfortunately that requirement is there because that's what vulkan (I'd need to check dx12) requires, so we actually can't implement it.

**Comment by igaryhe** [comment]
As far as I know, if descriptor indexing feature is enabled in Vulkan, the `descriptorCount` field in a `VkDescriptorSetLayoutBinding` means the maximum possible count

**Comment by kvark** [comment]
@igaryhe 
> Maybe we could provide an API to let users specify a maximum array size

There is already `count` in `BindGroupLayoutEntry`. Is anything else needed?

**Comment by cwfitzgerald** [comment]
@kvark it would be loosening validation to allow the bind group to be smaller than the BGL. It would be quite the improvement in usability actually, as it would mean shader recompiles wouldn't be necessary when your bind group count changes. On the other hand, it does mean that when we bounds check the access into the descriptor array, the bound would have to be a push constant vs a compile time constant.

**Comment by cwfitzgerald** [comment]
I just realized this would vastly reduce the complexity of rend3. Currently I need to be able to deal with JIT pipeline recompiles to adjust the BGL size, but if I could just automatically max it out then use the BG to set the real size (which has to be recreated anyway), it would mean I would never need to do JIT recompiles.

**Comment by cwfitzgerald** [comment]
We should check to see if this is portable to both DX12 and metal.

**Comment by cwfitzgerald** [comment]
Metal doesn't support unsized binding arrays anyway. DX12 should support this feature fine, so we can go ahead and implement this on Vulkan.

**Comment by kvark** [comment]
Why are we talking about "unsized" here? I thought it's still sized, just with a maximum instead of the exact value. In Metal, the argument buffer would just have some uninitialized textures in there. Seems like it should work.
