### ISSUE TITLE
Vulkan Backend Not Doing Gamma Correction/sRGB Conversion

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#1646]
_This was first reported in #1627, initially misinterpreted as a bug with the GL backend not being colored correctly_

**Description**
Vulkan backend is not doing sRGB conversion or gamma correction resulting in a darker-than-normal image:

**Repro steps**
Run any of the examples such as `cube` or `shadow` using the Vulkan backend. Reproduced so far on:

- Linux Nvidia Vulkan
- Linux Intel Vulkan
- Windows Intel Vulkan

**Expected vs observed behavior**

**Expected:**

![screenshot-lines](https://user-images.githubusercontent.com/25393315/125490755-900e8b18-5141-4286-9e1d-7dad9d8157c0.png)

**Observed:**

![image](https://user-images.githubusercontent.com/25393315/125490797-800b9226-7b91-4059-bdef-637158f8fc13.png)

**Extra materials**
None applicable so far.

**Platform**
WGPU @ 4b4e393e on Linux with:
- Intel(R) UHD Graphics (CML GT2) 
- Using GeForce GTX 1650

**Comment by kvark** [comment]
I checked Vulkan code, and it seems alright. Wgpu-core is asking for SRGB first, and Vulkan backend is expected to allow that. Would you be able to step through `fn surface_capabilities` on Vulkan adapter to see why SRGB isn't getting through?

**Comment by zicklag** [comment]
Adding debug prints shows that the `Bgra8UnformSrgb` format is selected as the only available format:

```
[wgpu-hal/src/vulkan/adapter.rs:1057] format = Rgba8Unorm
[wgpu-hal/src/vulkan/adapter.rs:1063] supported = false
[wgpu-hal/src/vulkan/adapter.rs:1057] format = Rgba8UnormSrgb
[wgpu-hal/src/vulkan/adapter.rs:1063] supported = false
[wgpu-hal/src/vulkan/adapter.rs:1057] format = Bgra8Unorm
[wgpu-hal/src/vulkan/adapter.rs:1063] supported = false
[wgpu-hal/src/vulkan/adapter.rs:1057] format = Bgra8UnormSrgb
[wgpu-hal/src/vulkan/adapter.rs:1063] supported = true
[wgpu-hal/src/vulkan/adapter.rs:1068] formats = [
    Bgra8UnormSrgb,
]
```

But... I took a quick look at `PrivateCapabilities::map_texture_format` and I found that the `Bgra8UnormSrgb` was mapped to vulkan's `B8G8R8_UNORM`, not `B8G8R8_SRGB`! Fixing that works!

![image](https://user-images.githubusercontent.com/25393315/125545537-b29bb65d-9d1a-4117-8040-c9e0a41206c5.png)

Thanks for telling me where to look @kvark !

I'll have a PR in a minute.
