### ISSUE TITLE
Dx12 artifacts (Bevy game engine) + wgpu trace provided

### ISSUE THREAD

**Issue by adsick** [gfx-rs/wgpu#1649]
Hi, guys, I'm not sure if it is the right time for this, but there was (and still is) an issue in Bevy game engine.
[See it here](https://github.com/bevyengine/bevy/issues/1941)

**Description**
artifacts appears on 3d models when using Bevy engine. 

**Repro steps**
If you want to reproduce it you have to get Bevy game engine and run examples that are 3D on a windows machine with Dx12 as a backend (note, Vulkan works well in this case). I'm not sure if it repeatable, but that is what makes it for me.

**Expected vs observed behavior**
expected: cool modern 3d pbr graphics 
got: red glitchy mess

**Extra materials**
[wgpu_trace.zip](https://github.com/gfx-rs/wgpu/files/6811088/wgpu_trace.zip)

**Platform**
Windows 10, amd Ryzen 5 3500U (Apu) with Vega 8 graphics.

**Comment by kvark** [comment]
Thank you for filing!
As I'm currently rewriting DX12 entirely in #1602, I don't want to spend too much effort figuring out the issue with gfx-backend-dx12. But if somebody wants to investigate, it may still be useful, at least to avoid this mistake in the future.

**Comment by cwfitzgerald** [comment]
Closing due to the hal rewrite
