### ISSUE TITLE
Using `queue.write_buffer` multiple times on the same buffer writes all of them at once

### ISSUE THREAD

**Issue by granitrocky** [gfx-rs/wgpu#1650]
I don't know if this is a bug or intended behavior, but the queue puts all buffer writes in the same location during execution time.

Is there a way to intersperse buffer writes among other commands using the command encoder?

Here's some output from RenderDoc. In the first image, all the `write_buffer`s got merged together.
![image](https://user-images.githubusercontent.com/5321817/125515543-0d467760-e563-4592-b092-5f9a6554d2a6.png)

I would like for them to be in between each of these draw calls
![image](https://user-images.githubusercontent.com/5321817/125515662-dd168ea4-057d-4cf2-ba4a-ddc447af491c.png)

**Comment by granitrocky** [comment]
The queue puts all the `write_buffer` commands together to be executed at the start of the next `submit()`. Is there a way for me to write `&[u8]` directly to a buffer using the command encoder?

**Comment by kvark** [comment]
Everything that you do on a `Queue` is done in the order you are doing. There is not really anything else to this. If you do `write_buffer`, `write_buffer`, `submit()`, then your writes happen before the submit.

If you want any data to be changed within a command encoder, then you can use the commands like `copy_buffer_to_texture`, assuming you can put data into the buffer before executing this.

**Comment by cwfitzgerald** [comment]
For what it's worth, this behavior of the queue is pushing you towards a usage pattern that the gpu likes better. If you constantly intersperse transfers with drawing, you're going to get many pipeline stalls, which leads to poor performance. If you do all your data transfers ahead of time, you only have to stall once.

**Comment by granitrocky** [comment]
Okay. Thanks everyone. Guess it comes down to wanting features that would be a bad idea to implement anyway.

Thank you.
