### ISSUE TITLE
sRGB Conversion Not Done for EGL < 1.5

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#1667]
**Description**
I think sRGB converison is not currently working for the GL backend with EGL < 1.6 on Linux. The issue was originally found in #1627.

( https://github.com/gfx-rs/wgpu/issues/1627#issuecomment-878602534 )

@cwfitzgerald said:
> Yeah my haswell rig has srgb issues on both vk and gl.

We have fixed the vulkan issue, but haven't done anything about GL yet.

**Repro steps**

**Expected vs observed behavior**
All of the examples appear darker in color than the vulkan ones. ( after we fixed vulkan in #1651 )

**Extra materials**

**Platform**
I was unable to reproduce this on my machine using `Mesa Intel(R) UHD Graphics (CML GT2)`, but @cwfitzgerald mentioned having issues on his haswell rig.

**Comment by cwfitzgerald** [comment]
This isn't actually a driver bug because EGL doesn't support SRGB surfaces until 1.5, and all GL devices (including my RPI) with 1.4 are having colorspace issues.

**Comment by kvark** [comment]
@cwfitzgerald does RPi support https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_gl_colorspace.txt ? 
Adding support for it in wgpu-hal/GLES should be trivial.

**Comment by kvark** [comment]
... and if neither EGL-1.5 or this extension are present, then we'll just no report SRGB formats as available for the swapchain.

**Comment by cwfitzgerald** [comment]
It seams like both my haswell and the rpi support it, so that should be good to use.

**Comment by cwfitzgerald** [comment]
Lemme see if I can toss together a PR for this.
