### ISSUE TITLE
Support PrimitiveID when possible

### ISSUE THREAD

**Issue by initial-algebra** [gfx-rs/wgpu#1669]
**Is your feature request related to a problem? Please describe.**
Sometimes, it's useful for a fragment shader to be aware of which primitive it is currently working on.  [Here's one use case.](https://github.com/initial-algebra/texint)  Normally, this ID is available through a shader builtin (`gl_PrimitiveID`/`SV_PrimitiveID`) that `wgpu` currently does not support.

**Describe the solution you'd like**
A flag should be added to `Features` that supports it when available.

**Describe alternatives you've considered**
Currently, this limitation can be worked around, at least on Vulkan when supplying SPIR-V, by disabling shader validation and ignoring the other validation warnings.  I suspect the situation on OpenGL is similar.  On DirectX, the program panics with the message, "There was a compiler error: Unsupported builtin in HLSL: 7".  It can also be worked around in general by supplying the ID as an uninterpolated vertex attribute, but indexed drawing then becomes difficult.

**Additional context**
It may be easier to get this working on Vulkan (and maybe OpenGL) first, because it already *partially* works there.

**Comment by cwfitzgerald** [comment]
Seems pretty easy to support:

- DX10+ has SV_PrimativeID
- GL has supportes gl_PrimativeID since GLSL 1.5 but GLES requires GLES 3.2
- Vulkan requires the geometryShader feature to use gl_PrimativeID which corresponds with the spirv geometry capability. (I think this is correct, but the spirv spec is kinda confusing)

If you want to support this safely, it would have to be piped through naga. If you're willing to use the unsafe spirv path, the wgpu work to check if you can use it should be very minimal.

**Comment by kvark** [comment]
So this can be an optional native-only feature, indeed. My only worry is that it provides very poor performance portability. Essentially, it relies on the geometry stage, which changes your whole graphics pipeline. There is an anecdotal evidence that just using this bultin in a fragment shader may slow down your execution by a half. I understand that some platforms can expose it better than the others, but there is still this portability danger.

See also an [SO answer](https://computergraphics.stackexchange.com/a/9451).

**Comment by cwfitzgerald** [comment]
Sounds like the documentation for this feature would need some ALL CAPS warnings about performance.

**Comment by initial-algebra** [comment]
I wrote a quick and dirty patch to support it in `naga`'s validator (it only checks if the capability is enabled and if the variable has the correct type) and SPIR-V backend and in `wgpu-core` (for 0.9).  I couldn't get it working on DirectX, although I understand that 0.9 still uses SPIRV-Cross to generate HLSL.  In any case, it should be a simple matter of mapping `PrimitiveID` to `SV_PrimitiveID` like with the other builtins, assuming that `naga` is used.  I would be happy to help with a proper implementation.

Another question is whether this feature might be expanded upon to support other `Geometry` features without going so far as to support actual geometry shaders.  However, as far as I can tell, `PrimitiveID` is the only thing that it adds support for in the stages relevant to `wgpu`.

**Comment by kvark** [comment]
I think we mostly in agreement that this can be exposed as a native-only feature with some big fat warnings in the documentation.
So please turn your patches into PRs, and we'll go from there.

**Comment by initial-algebra** [comment]
See also https://github.com/gfx-rs/naga/pull/1097.

**Comment by kvark** [comment]
Fixed by #1676
