### ISSUE TITLE
usage of `textureStore` in wasm code leads to error

### ISSUE THREAD

**Issue by blakej11** [gfx-rs/wgpu#1677]
**Description**
A WGSL file that invokes `textureStore()`, when run via wasm, generates an error like the following:

`Function [1] '' is invalid, caused by: Expression [10] is invalid, caused by: Used by a statement before it was introduced into the scope by any of the dominating blocks`

**Repro steps**
[Here](https://github.com/gfx-rs/wgpu/files/6833853/texture-store.tar.gz) is a compressed tarball with some code that exhibits the problem. It has some Rust that uses a slightly modified version of the `wgpu` example framework; that just creates a texture, binds it appropriately, and invokes a trivial entry point.

When run in native mode, it doesn't exhibit any errors. When compiled for wasm (using the `./build-wasm` script included in the tarball) and run under Firefox Nightly with the console open, it exhibits a stream of errors. The recurring errors are presumably from the framework calling `render()` over and over, but the initial error (shown above) is the relevant one.

When I tried to gather a trace of the wasm by running Firefox Nightly with WGPU_TRACE enabled, the WGSL source was saved as SPIR-V. There was some discussion in the `wgpu` Matrix channel a week or so ago about passing the source straight through to `web-sys` without translating it, but it doesn't appear that that's happened yet. But notably, both the original WGSL source as well as the SPIR-V I get from running `naga` on it validate successfully.

**Platform**
MacOS 11.4, Firefox Nightly 92.0a1 (2021-07-15), recent snapshot of `wgpu`.

**Comment by grovesNL** [comment]
#1618 will pass WGSL directly (instead of going through SPIR-V)
