### ISSUE TITLE
Slow SwapChain with Metal Backend

### ISSUE THREAD

**Issue by JoepKneefel** [gfx-rs/wgpu#1685]
Can someone explain why "get_current_frame" takes 12ms on average? The cpu + gpu load takes around 1ms.
The swap chain descriptor is set on Immediate mode. I would expect it to be faster.
It doesn't seem to be falling back to Fifo mode, because it would be 16ms otherwise (60FPS monitor).

Im running wgpu on ARM Mac OS with Metal backend enabled.

EDIT:
Frame takes 0ms then 20-30ms then 0ms etc.

**Comment by kvark** [comment]
Maybe you can help diagnosing this? I don't have an ARM Mac. You could try profiling with Metal System Trace.

**Comment by JoepKneefel** [comment]
I'll try tommorow

**Comment by JoepKneefel** [comment]
> Maybe you can help diagnosing this? I don't have an ARM Mac. You could try profiling with Metal System Trace.

I removed all my application logic and the same problem occurs. I also tested on windows and everything works just fine. It seems to be a bug in wgpu.

In the profile you can see it skips every odd frame and it still waits for vsync. So one frame ~16ms then 0ms then ~16ms etc...
<img width="1277" alt="Screenshot 2021-07-18 at 12 42 18" src="https://user-images.githubusercontent.com/57983732/126064220-e7e21534-03ed-4350-927b-43e4d7ad7490.png">

**Comment by kvark** [comment]
>  So one frame ~16ms then 0ms then ~16ms etc...

The swaptime duration in your picture shows 16.67ms consistently for each frame.

Just out of curiosity, do you also see this on wgpu-rs cube example?

**Comment by JoepKneefel** [comment]
The cube example seems to work fine. But it is set on MailBox:
<img width="1383" alt="Screenshot 2021-07-19 at 12 43 35" src="https://user-images.githubusercontent.com/57983732/126148602-fcdfac27-ff4b-4e27-ba1b-0411c22ccd8a.png">

If I set it on Immediate mode it also works (it doesn't skip frames):
<img width="1385" alt="Screenshot 2021-07-19 at 12 48 11" src="https://user-images.githubusercontent.com/57983732/126148925-59c3d5a9-52a1-4f8b-b822-e9830f5a37ef.png">

I also tested the pipeline example from "https://sotrh.github.io/learn-wgpu/beginner/tutorial3-
And it skips again:
<img width="1378" alt="Screenshot 2021-07-19 at 12 55 46" src="https://user-images.githubusercontent.com/57983732/126150184-17e12b04-9c9a-487f-840f-d72d39bdf26b.png">

**Comment by JoepKneefel** [comment]
It actually doesn't skip frames it is just below 1ms. Waiting for vsync is a problem though...

**Comment by kvark** [comment]
Metal backend doesn't implement `Mailbox` at all:
```rust
        let display_sync = config.present_mode != wgt::PresentMode::Immediate;
        if caps.can_set_display_sync {
            let () = msg_send![*render_layer, setDisplaySyncEnabled: display_sync];
        }
```
And the `can_set_display_sync` detection looks like it would trigger:
```rust
let os_is_mac = device.supports_feature_set(MTLFeatureSet::macOS_GPUFamily1_v1);
...
can_set_display_sync: os_is_mac && Self::version_at_least(major, minor, 10, 13),
```
Ideally, we'd confirm this on an ARM mac. Maybe there is something weird about the way it exposes the feature set, so that our Metal backend is confused?
Or maybe there are more knobs to push for disabling VSync, and we just don't know them all.

**Comment by cwfitzgerald** [comment]
I think we're finding out that metal is only double buffered, and turing off sync likely behaves more like FIFO_RELAXED more than Immediate. We should double check this, but this should be clarified by #2711
