### ISSUE TITLE
Rendering to multiple layers of a texture produces garbage

### ISSUE THREAD

**Issue by initial-algebra** [gfx-rs/wgpu#1690]
**Description**
I'm rendering a cube map.  To do so, I create a texture with 6 layers.  For 0 <= i < 6, I create a texture view referring to the ith layer of the texture, begin a render pass with that view attached, and render something.  Layer 0 is rendered correctly, but the other layers end up filled with garbage.  The garbage seems to be a corrupted form of the expected output as opposed to random noise.  I tried splitting each render pass into its own submission, and polled the device with `Maintain::Wait` between each submission in an attempt to rule out synchronization issues, but I'm not sure if `Device::poll` is supposed to be able to do something like that, and in any case there was no change.  When I switched to using 6 textures with 1 layer and view each, I got the expected output!

**Repro steps**
1. Create a texture with `depth_or_array_layers` = n
2. Create N views, each with a different 0 <= `base_array_layer` < n and with `array_layer_count` = 1
3. Render something to each view

**Extra materials**
![garbage](https://user-images.githubusercontent.com/67286231/126157734-b2ca149a-0266-4eba-9af6-75df4a12bd26.png)
[trace.zip](https://github.com/gfx-rs/wgpu/files/6840681/trace.zip)

**Platform**
Latest `master` of `wgpu` on Vulkan
RX 590 with Radeon Software Adrenalin 21.5.1 on Windows 10

**Comment by kvark** [comment]
Thank you for filing!
We actually have a similar case in the shadow example - the shadow map is a 2D array, and we render to each layer individually. Needless to say, this works as expected.
I'll take a closer look at your trace.

**Comment by cwfitzgerald** [comment]
Idk why, this smells like a lack of an image transition

**Comment by kvark** [comment]
Hmm, I'm a bit confused about this bug. The API trace contains rendering to all 6 faces, and then copying the data into a buffer. All of this appears to work correctly when looking through RenderDoc (perhaps, you could do it on your end?). All the data in cube faces looks good.
How did you look at the result? Did you render something (an environment cube) with the texture on it?

**Comment by initial-algebra** [comment]
I must say that I feel a bit silly now.  I tried out the shadow mapping example, which worked fine.  I then changed my code back to use one texture with multiple views to try to get some more details, but now it's working fine as well.  I wish I knew where I had gone wrong originally!
