### ISSUE TITLE
Doc Test on `TextureDescriptor::mip_level_size` is Failing

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#1693]
Just noticed that this doc test is failing locally:

https://github.com/gfx-rs/wgpu/blob/1090110edb007e3036394f74aaf6b3d249e459b0/wgpu-types/src/lib.rs#L2588-L2608

Are we running doc tests on CI? It initially fails because `wgpu::Extent3d` was not imported, but then the assertions fail after adding the import and I don't know what this is doing exactly yet so I don't know how to fix it.

**Comment by cwfitzgerald** [comment]
No we aren't, we're running tests for `player`, `wgpu`, and running `wgpu-info`. I forgot we even had doctests there. We should also run tests for `wgpu-types`.

**Comment by cwfitzgerald** [comment]
Since been fixed.
