### ISSUE TITLE
[Android] Limit 'max_storage_textures_per_shader_stage' value 4 is better than allowed 0'

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/wgpu#1695]
**Description**
Limit 'max_storage_textures_per_shader_stage' value 4 is better than allowed 0'.

**Repro steps**
Run examples on Android.

**Extra materials**
max_storage_textures_per_shader_stage on GL:
```rust
max_storage_textures_per_shader_stage: vertex_shader_storage_textures
                .min(fragment_shader_storage_textures),
```

```
[wgpu-hal/src/gles/adapter.rs:193] vertex_shader_storage_textures = 0
[wgpu-hal/src/gles/adapter.rs:193] fragment_shader_storage_textures = 8
```

**Platform**
Android 8.0 (Another device with 11.0), wgpu master.

**Comment by Gordon-F** [comment]
Same for `max_storage_buffers_per_shader_stage`:
```
[wgpu-hal/src/gles/adapter.rs:207] vertex_shader_storage_blocks = 0
[wgpu-hal/src/gles/adapter.rs:208] fragment_shader_storage_blocks = 35
```

**Comment by kvark** [comment]
Thank you for filing! We need to change `max_storage_textures_per_shader_stage` computation to account for some of them could be zeroes (and it's already captured by other downlevel flags).
