### ISSUE TITLE
Graphical corruption with OpenGL

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#1699]
Status: KAS as of https://github.com/kas-gui/kas/pull/220 works with with wgpu v0.9 with at least Vulkan and Metal backends, and with GL using `wgpu/cross` feature.

Using wgpu master updated for https://github.com/gfx-rs/naga/pull/1119 (plus minor compatibility hacks to KAS), the GL backend runs without `wgpu/cross` and initial draws look fine, but some redraws show graphical corruption:
![gallery-corrupt](https://user-images.githubusercontent.com/134893/126466695-3344752d-47f5-4ca5-8fa5-573f61e7100d.png)

Any hints how I can further debug this?

**Comment by dhardy** [comment]
I was able to still produce graphical corruption after disabling all actual drawing, which just leaves multiple render passes each with scissor rects. Using only the first pass (with full screen scissor) or removing the `set_scissor_rect` call appears to stop the corruption.

Re-enabling everything and removing only the `set_scissor_rect` call seems to fix everything (except some overlap-outside-scroll-area issues the scissor-rect is used for).

**Comment by kvark** [comment]
Thank you for filing!
Would you be able to make a RenderDoc capture of this? Or our API trace?
It does sound like the scissor set/reset is at fault in the GLES backend, although looking at the code now, I'm not seeing why it would fail.

**Comment by dhardy** [comment]
This issue appears to be fixed using the latest `wgpu` code (at least, I cannot currently reproduce).
