### ISSUE TITLE
iOS aarch64-apple-ios compilation fails

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#170]
Attempting to build on macos for iOS fails in a native library, glsl-cross.

Is targeting iOS with the metal backend supported ?

**Comment by kvark** [comment]
GLSL is *not* a part of either `wgpu-native` implementation (which this project is about) or WebGPU the API. Only the examples in [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) depend on it for convenience, it's not something you have to use as a client of the library.

**Comment by m4b** [comment]
Ah I see. I think I attempted to just naively compile an example. So is there a simple example that targets iOS? But sounds like there isn’t anything in wgpu-rs itself that will fail when targeting arm64 iOS, yes?

**Comment by kvark** [comment]
@seivan was running stuff successfully on iOS. Maybe they can chime in?

**Comment by seivan** [comment]
As of today:
 glslang needs to be used at compile time via macros. I’m working on figuring it cross platform. Could use help here 

Glsl-cross compiles cross platform today via @grovesNL crate however you need to add some linker flags - I’m hoping we can work around not needing them and have glsl-cross just work as part of they larger project static lib. 

SDL works cross platform but unfortunately existing crates have poor bindings. I’m working on this as of today and will soon be done. You want to disable iOS pump events and also avoid using sdl main. 

Wgpu-rs itself works on iOS out of the box. At least my outdated fork. There’s some issues for macOS like maximize and hidden will leak memory but afaik it works fine on iOS with rotation/transitions but I haven’t tested window events much. 


Hope it helped.

**Comment by m4b** [comment]
I suggest the glsl-spirv-cross dev dev be removed and precompiled shaders are byte_included, but yea, this is off topic. and thanks @seivan will read your overview, going to close this though!

**Comment by seivan** [comment]
@m4b You need `spirv-cross` to translate `spirv` to `msl` (metal shader language) 
Maybe you mean `glsl-to-spirv`
One approach here is to use the macro so you get it at compile time (since it runs on macOS, but not iOS) - until I finish my crate for both.
