### ISSUE TITLE
CUDA backend support possible?

### ISSUE THREAD

**Issue by chachi** [gfx-rs/wgpu#1706]
Amazing project! Thanks for all the hard work. I didn’t see this raised elsewhere but apologies if I missed it. 

Is it possible or planned to support a CUDA backend? It would be amazing to leverage the power of the CUDA ecosystem directly from the safety of Rust.

**Comment by kvark** [comment]
We have not considered this, and personally I haven't used CUDA to any extent. How would that look like? Would this backend be incapable of doing any rendering operations (i.e. render passes), but still do compute?

**Comment by chachi** [comment]
It would not be able to do any render passes, so perhaps it's not a fit for this crate? I don't know how the implementation would look but if it's a possibility for a backend to only support compute shaders, this could be very cool.

**Comment by cwfitzgerald** [comment]
My main question would be what would a cuda backend give over directly using vulkan/GL compute?

**Comment by cwfitzgerald** [comment]
Going to close this as out of scope, it's theoretically possible but wouldn't really be much of a benefit and unless a lot of interest materializes, it will be a large extra maintenance burden.
