### ISSUE TITLE
Enable GPU validation on DX12 and Vulkan

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1709]
**Is your feature request related to a problem? Please describe.**
Quite often, DX12 can fail without any clear validation error. It would help a ton if we could get more information about those.

**Describe the solution you'd like**
See https://docs.microsoft.com/en-us/windows/win32/direct3d12/using-d3d12-debug-layer-gpu-based-validation
We'll need a separate instance flag for this, since the perf penalty is greater.

**Describe alternatives you've considered**
Shoving this behind the existing `VALIDATION` flag

**Additional context**
Similar change will be needed in Vulkan. Distantly related to #1708

**Checklist**

- [x] #5146
- [ ] #5046

**Comment by ErichDonGubler** [comment]
I've edited the OP to contain a checklist of PRs I've filed to resolve this issue.
