### ISSUE TITLE
Access Violation during pipeline creation on Intel Windows Vulkan

### ISSUE THREAD

**Issue by Imberflur** [gfx-rs/wgpu#1711]
**Description**
```
error: process didn't exit successfully: `target\debug\veloren-voxygen.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

**Repro steps**
Run veloren on Windows with Vulkan and integrated Intel graphics, also a trace is provided below, not sure if anyone tested this with `debug_assertions` off so that may be a factor...

**Expected vs observed behavior**
No crash

**Extra materials**
![](https://cdn.discordapp.com/attachments/464698017283440640/866679669851291648/veloxyraptor_err.JPG)
[log](https://github.com/gfx-rs/wgpu/files/6866124/run_output.txt)
[log2](https://github.com/gfx-rs/wgpu/files/6866127/message.txt)
[trace](https://github.com/gfx-rs/wgpu/files/6866130/WGPU_TRACE_DIR.zip)

**Platform**
Reproduced on 2 different Windows machines with the same integrated intel graphics
```
OS: Windows
GPU: Intel(R) UHD Graphics 630
wgpu commit: a92b8549a8e2cb9dac781bafc5ed32828f3caf46
```

**Comment by kvark** [comment]
I believe this was fixed by https://github.com/gfx-rs/naga/pull/997 on June 20th, while the wgpu revision you used was from June 5th
