### ISSUE TITLE
Using D3DCompile is problematic

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1712]
For DX12 shaders compiled with `D3DCompile` internally, we are seeing problems.
It doesn't allow fixed-array sizes to be larger than 65K, and it doesn't like to dynamically index into them. It considers itself "forced" to unroll a loop that just iterates elements in fixed-size arrays.

**Comment by kvark** [comment]
A more detailed [issue 998 on Tint](https://bugs.chromium.org/p/tint/issues/detail?id=998&q=label%3AFXC&can=2), thanks @ben-clayton for the link!

**Comment by cwfitzgerald** [comment]
#2722 will break our hard dep on FXC, though it will always be there for a fallback.

**Comment by teoxoy** [comment]
We are tracking dynamic indexing in https://github.com/gfx-rs/naga/issues/1702.

> doesn't allow fixed-array sizes to be larger than 65K

Not sure what we can do about this though, split them?

**Comment by cwfitzgerald** [comment]
This should be covered by
- Already finished DXC work
- #4155 
- https://github.com/gfx-rs/wgpu/issues/4302
