### ISSUE TITLE
WARP Water Example is Totally Wonky

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1730]
**Description**

The water example running on warp looks totally wrong.

**Repro steps**

`WGPU_BACKEND=dx12 WGPU_ADAPTER_NAME=basic cargo test --example water`

**Expected vs observed behavior**

![screenshot-actual](https://user-images.githubusercontent.com/7861353/127103331-a4f65273-1c1d-4f3f-a588-3ac83a4899f8.png) is very much not what the water example should look like.

@kvark said this might be a known warp bug we worked around on gfx-hal but haven't ported the workarounds on.

**Comment by kvark** [comment]
Could be related to #1002, which was previously addressed in https://github.com/gfx-rs/gfx/pull/3434

**Comment by cwfitzgerald** [comment]
This is fixed in windows 11/windows server 2022
