### ISSUE TITLE
Video camera input support

### ISSUE THREAD

**Issue by stephanemagnenat** [gfx-rs/wgpu#1733]
Many applications, notably video conferencing, augmented reality, and video/image capture require access to the device's camera, which are numerous and high-resolution in modern mobile devices.

I originally filled an issue discussing this question in [wgpu-rs](https://github.com/gfx-rs/wgpu-rs/issues/170). Since then, there were progress in WebGPU with support for things such as [`importExternalTexture`](https://gpuweb.github.io/gpuweb/#dom-gpudevice-importexternaltexture).

The goal of this issue is to discuss and keep track of the support for video camera input in wgpu. This would certainly require quite some system-specific glue code, and maybe it belongs to a sister library, but given the effort required and the user benefit of a close integration with wgpu I am under the impression that it makes sense to talk about it here.

Here are the references currently found so far:
* Vulkan on Android: There is an extension, [VK_ANDROID_external_memory_android_hardware_buffer](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VK_ANDROID_external_memory_android_hardware_buffer) allowing Vulkan to access [Android's native hardware buffer](https://developer.android.com/ndk/reference/group/a-hardware-buffer). There is some [code samples here](https://github.com/ktzevani/native-camera-vulkan).
* On Mac/iOS, Metal seems to have tight integration with [AVFoundation](https://developer.apple.com/library/mac/documentation/AudioVideo/Conceptual/AVFoundationPG/Articles/00_Introduction.html#//apple_ref/doc/uid/TP40010188), there is already a [tutorial on how to do the link](https://navoshta.com/metal-camera-part-1-camera-session/).
* On Windows, it is probably possible to use [DirectShow](https://docs.microsoft.com/en-us/windows/win32/directshow/video-capture) to capture to a [DirectX texture](https://docs.microsoft.com/en-us/windows/win32/medfound/direct3d-12-video-apis), probably through an [Enhanced Video Renderer](https://docs.microsoft.com/en-us/windows/win32/directshow/choosing-the-right-renderer), although it is surprisingly difficult to find recent samples. No idea if there is a way to do camera-to-texture directly with Vulkan on Windows.
* Non-Android Linux, I did not find anything, I'm afraid one has to get the [V4L2](https://linuxtv.org/downloads/v4l-dvb-apis/index.html) stream in software and then send it to the texture.

It is probably interesting to see how the browsers do it, Chromium has a [design document](https://www.chromium.org/developers/design-documents/video-capture).

**Comment by unrelentingtech** [comment]
> Non-Android Linux, I did not find anything, I'm afraid one has to get the V4L2 stream in software and then send it to the texture

[v4l2 can export dmabufs](https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/dmabuf.html) actually so you want `VK_EXT_external_memory_dma_buf`. (Which there's plenty of other reasons to support…)

**Comment by cwfitzgerald** [comment]
I don't think this is really in-scope for wgpu. We do want to support interop with raw textures on all backends, so this is the wgpu mechanism that would make this possible.

**Comment by stephanemagnenat** [comment]
Maybe this camera use case could be a good candidate for a demo on how to support interop with raw textures on various backends? If you agree, I can create a wish issue for that.

**Comment by cwfitzgerald** [comment]
My main concern would be that the infrastructure for capturing the webcam will be annoying enough to maintain that we wouldn't want it in the repository. We would be willing to link to external examples though, and then have a more basic example in repo for the flow of importing an image
