### ISSUE TITLE
GL Backend Doesn't Support Cube Map Arrays

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#1746]
**Description**
GLES backend does not appear to support cube map array textures. This is more of a discussion to see how we might be able to support cube arrays if that is possible at all.

**Repro steps**
I ran into this while trying to run the new Bevy renderer on the GL backend. I don't have a small example, to test unfortunately.

**Expected vs observed behavior**
Expected that I could create a cube map array, but got an invalid operation error:

```
Jul 29 19:20:22.748 ERROR submit_graph_commands: wgpu_hal::gles::egl: GLES: [API/Error] ID 1 : GL_INVALID_OPERATION in glFramebufferTexture2D(invalid textarget GL_TEXTURE_CUBE_MAP_ARRAY)    
```

**Extra materials**
None

**Platform**
Ubuntu 20.04 WGPU@master (bbeb30a2c982ac9a7bdc6f7815d46eb311678b7a)

---

**Edit:** A quick check seems to show that cube map arrays are supported in GLES 3.2. Also there is this extension for ES 3.1 [`EXT_texture_cube_map_array`](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_cube_map_array.txt). I'd bet that this is impossible to support in WebGL. :frowning: 

**Edit 2:** From what I see, it looks like we already have a downlevel flag for this, and I'm actually running GLES 3.2 so it should work. I'll look more into what the problem might be.

**Comment by teoxoy** [comment]
Closing as this should be resolved.

The only way to run into this at the time was:

- if any attachment was a `GL_TEXTURE_CUBE_MAP_ARRAY`; this wasn't validated before but now is https://github.com/gfx-rs/wgpu/pull/3410
- copy texture to texture where the src was `GL_TEXTURE_CUBE_MAP_ARRAY`; which https://github.com/gfx-rs/wgpu/pull/2139 fixed
