### ISSUE TITLE
Creating a render pipeline for point lists results in a validation error

### ISSUE THREAD

**Issue by phoekz** [gfx-rs/wgpu#1752]
**Description**
Creating a `RenderPipeline` for rendering point sets such as: 

```rust
let pipeline = device.create_render_pipeline(&RenderPipelineDescriptor {
    primitive: PrimitiveState {
        topology: PrimitiveTopology::PointList,
        ..
    },
    ..
});
```

with any WGSL shader results in this validation error:

```
[2021-08-01T19:53:31Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-Shader-PointSizeMissing (0xf3693078)] : Validation Error: [ UNASSIGNED-CoreValidation-Shader-PointSizeMissing ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0xf3693078 | Pipeline topology is set to POINT_LIST, but PointSize is not written to in the shader corresponding to VK_SHADER_STAGE_VERTEX_BIT.
    object info: (type: PIPELINE, hndl: 0x0)
```

**Expected vs observed behavior**
According to https://www.w3.org/TR/WGSL/#builtin-variables, WGSL doesn't have a builtin for `pointsize`. As far as I know, there is currently no way to avoid this validation error.

This issue was also reported here: https://github.com/gfx-rs/naga/issues/1070.

I guess the solution is to have the vertex stage always output `PointSize=1.0`?

**Platform**
Running on Windows 10, wgpu 0.9.

**Comment by kvark** [comment]
Seen this in Gecko's webGPU now in the wild. Gotta prioritize fixing.
