### ISSUE TITLE
Pipeline overrides

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1762]
**Is your feature request related to a problem? Please describe.**
See https://github.com/gpuweb/gpuweb/pull/886

**Describe the solution you'd like**
Just follow the spec

**Describe alternatives you've considered**
?

**Additional context**

**Comment by kvark** [comment]
Adding a milestone tentatively, let's see how difficult this is going to be.

**Comment by kvark** [comment]
Too much work for this milestone, actually

**Comment by aloucks** [comment]
Any update on this? It would be really nice to avoid string replacement on the shader source.

It looks like the syntax has changed since the linked PR:
https://gpuweb.github.io/gpuweb/#dictdef-gpuprogrammablestage

**Comment by kvark** [comment]
Yep, that's why I'm not in a rush. The topic has been actively discussed recently. I think the main approach is figured out now, and just some details are missing.

**Comment by adeline-sparks** [comment]
I'd really like to use this too! Do you think the spec is stable enough to implement it? I have some free time upcoming and might give it a try if so.

**Comment by teoxoy** [comment]
@adeline-sparks I'm working on it.
