### ISSUE TITLE
More information in layout missmatch errors

### ISSUE THREAD

**Issue by FredrikNoren** [gfx-rs/wgpu#1765]
**Is your feature request related to a problem? Please describe.**
Currently when a bind group doesn't match a layout we get this error:
```
Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 7, Metal)>`
    In a draw command, indexed:true indirect:false
      note: render pipeline = `<RenderPipeline-(1, 1, Metal)>`
    current render pipeline has a layout which is incompatible with a currently set bind group, first differing at entry index 2
```
But it's hard to tell what the underlying problem is from this. It's not even clear to me what "entry index 2" refers to here (is it group 2? Or group 0, entry 2?).

**Describe the solution you'd like**
It would be great if this error just gave me some more information to be able to debug the problem. At least showing me both group index and entry index would be a good start. (But if it can show more it would be great).

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kvark** [comment]
Thank you for filing! I've seen myself wanting more information there as well.
This is also one of the simpler things to contribute, in case you want to try.

**Comment by FredrikNoren** [comment]
@kvark I tried to take a look but I don't think I'll have time to figure this out. Some other suggestions though:

* It would be great if the debug groups were shown in the error as well (preferably in a stack, like `my_first_group/my_second_group`)
* It would also be great if there was a way to connect which draw call triggered the error. Perhaps `RenderPass::draw` could return an id or something, so I could print that while debugging and connect it with the error. Or even better; if there's a way to actually throw the error at `RenderPass::draw` instead, that would be ideal.

**Comment by cwfitzgerald** [comment]
This error has since been improved.
