### ISSUE TITLE
iOS app panics

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#177]
if you change the `wgpu-rs` cube example to byte include the precompiled spv shaders, one can target `aarch64-apple-ios`, and then run the cube demo, for example, by exporting something like:
```
#[no_mangle]
pub fn extern "C" wgpu_init() {
  framework::run::<Example>("cube");
}
```

and then writing a `main.swift` file with:
```
let () = wgpu_init()
```

this will run and display the cube, but after about a minute it crashes with:
```
2019-05-14 20:24:23.547176-0700 cube_test[1362:313208] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
2019-05-14 20:24:23.547191-0700 cube_test[1362:313208] Execution of the command buffer was aborted due to an error during execution. Ignored (for causing prior/excessive GPU errors) (IOAF code 4)
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Ok(false)`,
 right: `Ok(true)`: GPU got stuck on a frame (image 1) :(', /Users/foo/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/0edf927/wgpu-native/src/swap_chain.rs:160:5
```

**Comment by m4b** [comment]
Seems this only seems to crash when multiple rotations happen; each rotation stalls the renderer for quite some time, and the above error message like `Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)` is printed. If one rotates several times in sequence, application will crash like above.

**Comment by kvark** [comment]
Thank you for filing the issue!
We should make the timeout to scale with the number of times the swapchain was recreated.

**Comment by seivan** [comment]
@kvark I don't think this is a bug. 
@m4b Do you recreate the swapchain on transition callbacks? 
Rotations should trigger a `willTransitionTo` function that winit should capture and let you know about. 

I rotate several times at start without any issues.

**Comment by m4b** [comment]
I don't know much about winits internals and whether its handling this correctly, but:

since an assert is firing I think this is a bug, or the code should be refactored to return a user handalable error. Assertion violations are fundamental program errors, e.g., a pre/post condition is violated, or at least should be. If not, as I suggested, it needs to be refactored to be a user visible error, so client code can gracefully recover (or not, up to them).

**Comment by kvark** [comment]
@m4b part of the problem is that error handling today is nearly non-existing in the project. This is one of the major missing pieces, and the reason being that spec itself is fairly complex around error handling.

@seivan can you clarify if you mean that "this is not a bug in a way @kvark suggests it is" or that "it's not a bug at all"?

**Comment by seivan** [comment]
@kvark I mean I want compile time error instead of assertion as much as the next person, but certain things are hard to catch I presume (missing filed loaded at runtime, etc) 

My take here is that the issue is with Winit not engaging very well with iOS and that might be related to e.g how it sets up the Metal stuff. 

From my experience getting gfx-hal running on iOS was possible with SDL2 and never with Winit - except my old fork of winit trying to get ggez and gfx-pre-ll running.

**Comment by seivan** [comment]
@m4b You're building a static lib out of everything and executing the main function of the example in a `main.swift` file hoping Winit sets everything up and plays ball with the rest of the system.

I've read the Winit source code, the way it sets up its own AppDelegate and UIApplicationMain is not perfect, not to mention the event loop issues I had (they might have changed that recently) 

There's a lot that can go wrong there and not necessarily the fault of wgpu or gfx-hal. 
I strongly suggest looking at SDL2 for iOS as of now. 
Works out of the box with wgpu and gfx-hal. 
I've written my own crate for SDL2 bindings, but the existing sdl2-rs crate works fine to.

**Comment by m4b** [comment]
> @m4b You're building a static lib out of everything and executing the main function of the example in a `main.swift` file hoping Winit sets everything up and plays ball with the rest of the system.

If you're using SGDL2 or any other library which isn't the standard objective-C/swift application lifecycle, this is always true that one is "hoping X sets up everything and plays ball with the rest of the system". Maybe SGDL2 does this better, probably?

I don't think there should be any crashes in this gpu library though

**Comment by m4b** [comment]
Also I would like to add that building an application with winit is explicitly added in _this_ crate; if the suggested solution is "to not use the winit entry point", then it should be removed imho, otherwise more bugs will get filed about why this is crashing, etc.

**Comment by kvark** [comment]
@m4b don't take that offensively please. @seivan just pointed out that `winit` may be problematic, and that SDL2 is guaranteed to work better, that's all. We still need to understand where exactly is the problem in our interaction with winit and fix it.

**Comment by m4b** [comment]
I'm not offended at all, sorry if it came off that way.

I don't think bringing up SDL2 is really relevant here, and feel like it's derailing this bug report. This library exposes an iOS winit entry point, and in certain runs, it causes `wgpu` (not winit, or iOS system code) to crash with an assert failure.

Maybe winit is behaving badly, but, so what? It doesn't mean it has to crash `wgpu`, that's all I'm trying to say here :)

**Comment by kvark** [comment]
@m4b we don't know what exactly is wrong with `winit` interaction. This is still pending investigation, no resolution has been made. But mentioning SDL2 in this context *is* relevant for helping to narrow down the cause, as well as to provide a workaround path for those who suffer from the issue.

**Comment by seivan** [comment]
@m4b If you try to load a file that doesn't exist at runtime, what should the library do?

This is sorta the error you're getting - Wgpu is expecting something that Winit isn't setting up and it crashes, it's hard to defend at that. 

My point is, the issue isn't Wgpu related but Winit.

**Comment by m4b** [comment]
> you try to load a file that doesn't exist at runtime, what should the library do?

100% not assert. This is what fuzzing is testing: all external inputs to a program library do not cause assertions or other crashes but handled errors.

But I shouldn’t belabor this point since if I understood correctly @kvark already stated the error handling story isn’t great so maybe the assert firing isn’t really an assert, ie unrecoverable pre/post condition violation.

I don’t know the code well enough to say either way.

**Comment by m4b** [comment]
And as I already said, if the answer I’m hearing here is “it’s winits fault, they are violating fundamental assumptions when we run with them”, then... don’t run with them? The iOS winit endpoint should be removed if it’s that broken ? I’m not sure what we’re discussing at this point.

I want to know why the assert is firing; is it really an assert or is it a user level error ? And if the latter what is the story for converting it to be that ?

**Comment by seivan** [comment]
Have you tried using that https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/instance.rs#L113 for iOS. 

I'd say it's a real issue if that particular endpoint fail, because by then - once everything is setup to the point of you giving a metal layer to Wgpu and it **still** fails - then it's a real problem, but until now my personal stance is that this is a Winit issue more than a wgpu one. 

You're passing a Winit window instance to https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/instance.rs#L79 and it fails and the expectation is that it shouldn't - that's unresonable because it's under the assumption that Winit hasn't itself failed setting everything up - which is my *suspicion* - in which case, assertion is the only approach. Bubbling the error all the way up is pointless.

**Comment by seivan** [comment]
@m4b Since it seems like Winit might set up everything already I think I was wrong earlier and there is an issue with Wgpu acquiring next drawable failing.

**Comment by cwfitzgerald** [comment]
Closing as stale due to the new hal
