### ISSUE TITLE
Failed to parse WGSL when specifying var access mode 

### ISSUE THREAD

**Issue by gliderkite** [gfx-rs/wgpu#1777]
If I specify the `storage` access mode (read/write/read_write) in a WGSL shader:

```
[[block]] struct PositionsBuffer {
  pos: array<vec2<f32>>;
};

[[group(0), binding(0)]]
var<storage,read_write> pbuf: PositionsBuffer;
```

Example taken from [www.w3.org/TR/WGSL](https://www.w3.org/TR/WGSL/#module-scope-variables).

when I call `Device::create_shader_module` as:

```rust
device.create_shader_module(&ShaderModuleDescriptor {
   label: Some("Shader"),
   flags: ShaderFlags::all(),
   source: ShaderSource::Wgsl(shader.into()),
});
```

I get the following error:

```
ERROR: ValidationError { source: ContextError { string: "Device::create_shader_module", cause: Parsing, label_key: "label", label: "Shader" }, description: "Validation Error\n\nCaused by:\n    In Device::create_shader_module\n      note: label = `Shader`\n    Failed to parse WGSL\n" }'
```

Note, I've just started learning about computer graphics, so my knowledge is very limited. However, I seem to understand that the above should be valid syntax, also when I run the validation using [naga](https://github.com/gfx-rs/naga) it is successful.

I'm on Ubuntu 20.04 using `wgpu` version `0.9`.

**Comment by kvark** [comment]
wgpu-0.9 doesn't have this WGSL syntax supported. Since WGSL is a moving target, our stable releases can't update its API.
It's best for us if you use `master`, but if you have to use `v0.9`, then take a look at the relevant example code - https://github.com/gfx-rs/wgpu/tree/v0.9/wgpu/examples
