### ISSUE TITLE
hello-triangle example panics in fullscreen on DX12

### ISSUE THREAD

**Issue by codeflo** [gfx-rs/wgpu#1781]
**Description**

The hello-triangle example, modified to use DX12 and to go fullscreen, panics during swapchain initialization. Only tested on one machine.

The exact message is

* on 0.9: thread 'main' panicked at 'failed to configure swap chain on creation: Swapchain can't be created for an unknown reason'

* on master: thread 'main' panicked at 'Error in Device::create_swap_chain: invalid surface'

I'm calling winit's `window.set_fullscreen` directly before initializing wgpu. If something else needs to be done, it's not obvious to me. It's curious that every other combination works fine (both 0.9 and master):

* fullscreen/Vulkan: works
* windowed/Vulkan: works
* fullscreen/DX12: PANICS
* windowed/DX12: works

Full backtraces for both 0.9 and master are included in this gist: https://gist.github.com/codeflo/a8b5dc92a5de2e177ff765ad9240aafb

I also included the source code in the gist (scroll down a bit), though the only changes I made to hello-triangle are:

* setting fullscreen
* explicitly setting the backend to DX12
* including the shader directly in the source, for easier testing
* removing the WASM codepath (to rule out a weird configuration issue)

**Platform**
Windows 10, NVIDIA 3080, reasonably current drivers, Rust nightly

**Comment by codeflo** [comment]
After some research, I get the impression that fullscreen exclusive mode might not exist anymore in DirectX 12, and borderless windowed has now been optimized to be equally fast. It’s surprisingly hard to find information on this that’s not from confused people on gaming forums, but see e.g. https://stackoverflow.com/a/66144592 and the articles it links to.

Can anyone with more DirectX knowledge than me confirm? Because if that’s true, this bug can probably be closed.

**Comment by cwfitzgerald** [comment]
Correct, dx12 does not have the ability to go exclusive fullscreen, and dx9/11 will lie about going exclusive on modern windows machines.

That being said we _might_ be doing something wrong here, so it's worth double checking.

**Comment by codeflo** [comment]
I’m not sure if this is more related to winit then, but the main reason I want to use exclusive fullscreen is the ability to select a video mode with a higher refresh rate (e.g. 144 Hz). Where in the stack would that come in?

**Comment by cwfitzgerald** [comment]
This is likely fixed, but if it not, please ping to re-open.
