### ISSUE TITLE
Images in README are unreadable in dark theme

### ISSUE THREAD

**Issue by kotx** [gfx-rs/wgpu#1784]
![image](https://user-images.githubusercontent.com/33439542/128765772-ad4de250-650b-4858-825d-4c3c4f59e221.png)
![image](https://user-images.githubusercontent.com/33439542/128765752-903c96bd-a153-4f78-b5d8-651bdaf2a4e6.png)
There should be an outline or background of some sort.
They're also almost invisible on the high contrast theme.

**Comment by cwfitzgerald** [comment]
This was fixed in a recent PR.
