### ISSUE TITLE
D3DCompile error 80004005: unrecognized identifier 'Camera_Uniform'

### ISSUE THREAD

**Issue by metasophiea** [gfx-rs/wgpu#1791]
Hello everyone;

I've ran into some trouble with running on Windows10. My program works fine on MacOS, but I encounter the following error when I attempt to run it on Windows

Caused by:
In Device::create_render_pipeline
note: label = Rectangle Regular Pipeline
Internal error in VERTEX shader: D3DCompile error 80004005: C:\Users\metasophiea\Desktop\19\main\Shader@0x000002C4D6F16960(47,37-50): error X3000: unrecognized identifier 'Camera_Uniform'

[I have attached the shader file I'm using too.](https://github.com/gfx-rs/naga/files/6962510/shader.txt) I've set things up so that each shape type has its own wgsl shader file - in this case the Rectangle shape - which is accessed from two entry points.

Thanks for your help!
Brandon

**Comment by teoxoy** [comment]
Closing since we removed SPIRV-Cross in v0.10.
