### ISSUE TITLE
Triple-Sampler Bind Group Causes Descriptor Table Mismatch

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1798]
**Description**

> CGraphicsCommandList::SetGraphicsRootDescriptorTable: The currently set root signature declares parameter [3] as a descriptor table in a descriptor heap of type D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV, but the specified BaseDescriptor parameter is from a different descriptor heap type: D3D12_DESCRIPTOR_HEAP_TYPE_SAMPLER. [ EXECUTION ERROR #708: SET_DESCRIPTOR_TABLE_INVALID]

**Repro steps**

```
git clone https://github.com/BVE-Reborn/rend3.git
git checkout e1a4c702c0affba4c3d1e3fafc01eb2d88290320

cargo run --bin scene-viewer -- -m cpu -b dx12
```

**Extra materials**

BGL defined here: https://github.com/BVE-Reborn/rend3/blob/render-list-removal/rend3/src/routines/common/interfaces.rs#L34-L65
Bind group defined here: https://github.com/BVE-Reborn/rend3/blob/render-list-removal/rend3/src/routines/common/samplers.rs

[trace.zip](https://github.com/gfx-rs/wgpu/files/6984320/trace.zip)

**Comment by kvark** [comment]
Could you please attach an API trace?

**Comment by cwfitzgerald** [comment]
Attached.
