### ISSUE TITLE
Indexing by constant no longer works since updating to version 0.9

### ISSUE THREAD

**Issue by wrnrlr** [gfx-rs/wgpu#1799]
**Description**

Indexing by constant no longer works on version 0.9.
Maybe this is intentional but since it broke my code I'd figure to ask if this is a regression.
If so what can I do to re-enable it?

**Repro steps**

I was creating a shadertoy like util to quickly develop shaders.
Best way is to clone the [slimshader](https://github.com/wrnrlr/slimshader) repo and bump the version up to `0.9`.

run the program like this:

```
cargo run -- src/demo.wgsl
```

After updating it fails to compile this vertex shader:

```
let vertices: array<vec2<f32>, 3> = array<vec2<f32>, 3>(
    vec2<f32>(-1.0, 1.0),
    vec2<f32>(1.0, 1.0),
    vec2<f32>(-1.0, -1.0),
);

struct VertexOutput {
    [[builtin(position)]] clip_position: vec4<f32>;
    [[location(0)]] coord: vec2<f32>;
};

[[stage(vertex)]]
fn main([[builtin(vertex_index)]] in_vertex_index: u32) -> VertexOutput {
    var out: VertexOutput;
    out.coord = vertices[in_vertex_index];
    out.clip_position = vec4<f32>(out.coord, 0.0, 1.0);
    return out;
}
```

Wgpu complains about the line `out.coord = vertices[in_vertex_index];`, but it works on version 0.8

**Expected vs observed behavior**

Run vertex shader with wgpu version 0.9 result in this error

```
2021-08-13T22:36:35Z ERROR wgpu::backend::direct] wgpu error: Validation Error

Caused by:
        In Device::create_shader_module
          note: label = `Vertex Shader`
        Entry point main at Vertex is invalid
        Expression [5] is invalid
        The expression [1] may only be indexed by a constant
```

**Platform**
OSX Big Sur, 11.1
`rustc` version is `rustc 1.55.0-nightly (74ef0c3e4 2021-07-16)`
works on wgpu version 0.8.1 but not on 0.9

**Comment by kvark** [comment]
This is by design, according to WGSL specification (which got this restriction added since our 0.8 release).
Basically, if you are indexing an array, it has to be in *some* memory. Your array is declared like a constant, it's not backed by memory.
You can work around this by declaring it as `var<private>` instead.
