### ISSUE TITLE
Validation error due to X11 tiling window manager (?)

### ISSUE THREAD

**Issue by jonas-schievink** [gfx-rs/wgpu#1821]
**Description**
I'm getting the following error when running any wgpu example that opens a window:

```
[2021-08-18T18:50:41Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
    	Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x55e5726d8fe0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (800,600), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (956,526), minImageExtent = (956,526), maxImageExtent = (956,526). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2021-08-18T18:50:41Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x55e5726d8fe0, name: ?)
```

**Repro steps**
Run any example, might require a specific window manager behavior.

**Expected vs observed behavior**
There should be no scary errors.

It looks like wgpu expects the requested window size to actually be the one it ends up with (`vkCreateSwapchainKHR() called with imageExtent = (800,600)`). On X11, this is not a valid assumption, since the window manager ultimately decides what window the application will get, which in this case is `currentExtent = (956,526)` which is slightly less than a quarter of a 1080p display, which matches the actual window size it ends up with.

**Platform**
This is on x86-64 X11 Linux with i3 as the window manager, wgpu 80ec65e8922713176ddd07c78db7c64b62183237.

**Comment by cwfitzgerald** [comment]
This is a race with window resizing, and the validation is now suppressed.
