### ISSUE TITLE
Compiling to WASM wiki page has outdated reference to "cross" cargo feature

### ISSUE THREAD

**Issue by gpaulu** [gfx-rs/wgpu#1824]
[The compiling to WASM instructions](https://github.com/gfx-rs/wgpu/wiki/Running-on-the-Web-with-WebGPU-and-WebGL#compiling-for-wasm) mention disabling the "cross" default cargo feature, but the "cross" feature no longer exists.

```
# Build with the wasm target
# Since "cross" is enabled by default but useful for this target, we disable default features
RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --no-default-features --target wasm32-unknown-unknown --example hello-triangle
```

**Comment by kvark** [comment]
We need to rip out everything related to `cross` or SPIRV-Cross from that document.

**Comment by cwfitzgerald** [comment]
Fixed
