### ISSUE TITLE
Missing Features::PUSH_CONSTANTS for Metal

### ISSUE THREAD

**Issue by lordnoriyuki** [gfx-rs/wgpu#1825]
It looks like PUSH_CONSTANTS support accidentally got dropped in all the recent changes for the Metal driver.

I'll open a pull request adding it back. It seems it's working fine, and just needed the device to return that it was a supported feature.

**Comment by Herschel** [comment]
The DX11 and DX12 backends also had PUSH_CONSTANTS feature removed.

**Comment by kvark** [comment]
Right. It's not accidental. We rewrote the backends, and push constants weren't essential. We can implement them as a follow-up.

**Comment by Herschel** [comment]
Only posting as an FYI for others as it's not explicitly mentioned in the changelog, and I stumbled upon it as well 😃

**Comment by Xaeroxe** [comment]
I also ran into this for DX12. The documentation explicitly states push constants are supported on DX12 so this was surprising.

**Comment by cwfitzgerald** [comment]
So this is a documentation problem as a result of the hal switch. These are the platforms that we could support them. We should update the documentation to say that it is unimplemented on non-vulkan
