### ISSUE TITLE
Cannot use adapter specific formats for storage textures

### ISSUE THREAD

**Issue by kocsis1david** [gfx-rs/wgpu#1827]
**Description**
`Rg16Float` cannot be used as a storage texture, but it is supported by the adapter when enabling `TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`

**Repro steps**
Add a storage texture binding (with the `Rg16Float` format) to the shader and bing group layout.

**Expected vs observed behavior**
Pipeline creation ends with a validation error, but it's valid to use the that format, because it's supported by the adapter.

**Extra materials**
https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/validation.rs#L440
`map_storage_format_to_naga` fails here, because the match statement doesn't contain the `Rg16Float` format.

**Platform**
version of `wgpu`: 0.10.0

**Comment by kvark** [comment]
Thank you for filing! If you want to make a PR that expands `map_storage_format_to_naga` to more formats, that would be great! I believe the validation already check if a format supports storage, so this mapping shouldn't be concerned about what's available and what's not.

**Comment by kocsis1david** [comment]
Yes, it's already checked when you create the texture. So it shouldn't be possible to create a texture with a storage usage, if the device doesn't support that. I'll create a PR in a moment.

**Comment by kocsis1david** [comment]
But I don't know if it's a problem that you can create a BingGroupLayout with a storage binding that is unsupported.

**Comment by kvark** [comment]
BGL creation should check for it as well. If this check is not fully correct, we'll address this separately.

**Comment by kvark** [comment]
Let's consider this closed by #1829
