### ISSUE TITLE
Output of egui_wgpu_backend looks really dark with wgpu 0.10

### ISSUE THREAD

**Issue by niklaskorz** [gfx-rs/wgpu#1828]
**Description**
The frames rendered by https://github.com/hasenbanck/egui_wgpu_backend look really dark after upgrading to wgpu 0.10.
Related pull requests:
- https://github.com/hasenbanck/egui_wgpu_backend/pull/32
- https://github.com/hasenbanck/egui_example/pull/10

**Repro steps**
Clone and run https://github.com/hasenbanck/egui_example/pull/10

**Expected vs observed behavior**
Expected behavior (egui_wgpu_backend 0.10 with wgpu 0.9):

<img width="1072" alt="egui with wgpu 0.9" src="https://user-images.githubusercontent.com/590517/130075120-5a771323-b5ff-4271-8238-f7450bd09fcc.png">

Observed behavior (my pull request with wgpu 0.10):

<img width="1072" alt="egui with wgpu 0.10" src="https://user-images.githubusercontent.com/590517/130074816-a7d268d1-d32c-4838-8bdb-b5d5b8494543.png">

**Platform**
Tested and verified on:
- macOS 11.5.2 with Metal
- Windows 10 with Vulkan

**Comment by niklaskorz** [comment]
Removing the sRGB conversion performed in the egui_wgpu_backend shader doesn't look right either:

<img width="1072" alt="grafik" src="https://user-images.githubusercontent.com/590517/130077164-4dee624c-54eb-4524-b6f0-0412eaedda4f.png">

**Comment by kvark** [comment]
What swapchain format is being used?

**Comment by niklaskorz** [comment]
`surface.get_preferred_format` is used and returns `Bgra8UnormSrgb` on both platforms

**Comment by niklaskorz** [comment]
@Gordon-F found the issue, it was the reversed order of arguments in WGSL `select` :)
