### ISSUE TITLE
Attachments only support sample counts 1 and 4

### ISSUE THREAD

**Issue by phoekz** [gfx-rs/wgpu#1832]
**Description**
When starting a render pass which has multisampling enabled, I get this validation error:

```
[2021-08-19T16:28:25Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In a RenderPass
          note: encoder = `Encoder`
        In a pass parameter
          note: command buffer = `Encoder`
        attachment's sample count 2 is invalid
```

Sample counts 1 and 4 work, while 2 and 8 do not, even though my GPU definitely supports those. I looked around and I suspect this condition is the problem:

https://github.com/gfx-rs/wgpu/blob/0b1657fa03f0cb4ceb1e5fdecbbc63e25d72970d/wgpu-core/src/command/render.rs#L679-L681

**Comment by kvark** [comment]
That's what WebGPU exposes today. We can think of a way to expose this in a non-portable native-only way.

**Comment by phoekz** [comment]
Ah my bad. I was actually trying to look up from the spec if this was intentional. Looks like I missed this under section 6.1.1:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/712560/130110609-84125326-4d40-406e-971f-ca997ff12150.png">

**Comment by phoekz** [comment]
To avoid further confusion, it might be a good idea to throw a more specific error which states that only 1 and 4 are valid values.

Or you can go down Vulkan path of defining enums for sample counts, and only allowing for 1 and 4 for example.

**Comment by daxpedda** [comment]
Is this not fixed by https://github.com/gfx-rs/wgpu/pull/3140?

**Comment by cwfitzgerald** [comment]
It was!
