### ISSUE TITLE
Read-only Depth/Stencil (RODS) in the water example fails on using Depth24PlusStencil8 instead of Depth32Float

### ISSUE THREAD

**Issue by ivovanderlans** [gfx-rs/wgpu#1835]
**Description**
In a project, I used a Depth24PlusStencil8 buffer as depth/stencil-buffer target in a first pass and read from that same texturebuffer in a second pass. With the transition from Wgpu 0.9.0 to 0.10.1, it stopped working, mentioning: "bound texture views can not have both depth and stencil aspects enabled", I found that the "water" example in this wgpu repository does the same by approximation and that uses a Depth32Float buffer instead and it works. But I need to write to the stencil part in the first pass because I use its output in a third pass. So in a local wgpu clone, I replaced all Depth32Float by Depth24PlusStencil8 in the water example *) and modified the TextureViewDescriptor on main.rs::228 to have aspect: wgpu::TextureAspect::DepthOnly and presto: "bound texture views can not have both depth and stencil aspects enabled". I have added the example main.rs as a zip in this report below.

*) I also removed the wgpu::TextureUsages::COPY_DST on line 214 because it interferes and the example-with-Depth32Float runs fine without it.

**Repro steps**
See the description

**Expected vs observed behavior**
I get the message "bound texture views can not have both depth and stencil aspects enabled" in "device.create_bind_group" from water::Example::initialize_resources at .\examples\water\main.rs:231. I expect the example to run fine because the stencil bits from the depth/stencil buffer are not used anywhere and I have set the texture view aspect to DepthOnly. It seems that wgpu internally uses Depth+stencil anyhow.

**Extra materials**
[main.zip](https://github.com/gfx-rs/wgpu/files/7021308/main.zip)

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
win10 / Vulkan / wgpu 0.10.1

**Comment by Pauan** [comment]
I'm getting this same error with the latest version of wgpu (commit e47dc2adadbf040c8cdb0ee21e602d8d772f8515).

I ran the water example using `cargo run --bin water`, and it worked fine.

Then I changed all uses of `Depth32Float` to `Depth24PlusStencil8`, and it gave me this error:

```
Using AMD Radeon RX 6800 XT (RADV NAVI21) (Vulkan)
[2023-08-30T08:38:00Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `Water Bind Group`
    Bound texture views can not have both depth and stencil aspects enabled

', wgpu/src/backend/direct.rs:3095:5
```

(I found out about this bug in my real app, which needs to read from the depth buffer in a postprocess pass).

**Comment by teoxoy** [comment]
That is intended, the texture view you bind for the shader must have only one aspect depth or stencil, not both.

You should be easily able to fix it by creating a new view with just the depth aspect and binding that for the shader.

**Comment by Pauan** [comment]
@teoxoy I also need the stencil information in the postprocess shader. Why does that restriction exist?

**Comment by teoxoy** [comment]
You need to then create 2 extra views, one for the depth aspect and one for the stencil.

> Why does that restriction exist?

I think it makes sense, if you bind the combined texture, how would you read from each individual aspect in the shader?

**Comment by Pauan** [comment]
> You need to then create 2 extra views, one for the depth aspect and one for the stencil.

Thanks, that worked! Setting the `format` gave errors, but setting the `aspect` works:

```
let depth_view = texture.create_view(&wgpu::TextureViewDescriptor {
    aspect: wgpu::TextureAspect::DepthOnly,
    ..wgpu::TextureViewDescriptor::default()
});

let stencil_view = texture.create_view(&wgpu::TextureViewDescriptor {
    aspect: wgpu::TextureAspect::StencilOnly,
    ..wgpu::TextureViewDescriptor::default()
});
```

> I think it makes sense, if you bind the combined texture, how would you read from each individual aspect in the shader?

I didn't realize that you could create multiple views with different formats for the same texture.
