### ISSUE TITLE
Only enable compressed texture feature ```wgpu::Features::TEXTURE_COMPRESSION_BC``` cause ```STORAGE_BINDING``` validation error

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/wgpu#1856]
my app use a ```R16Float``` format texture and run correctly, but if only enable compressed texture feature ```wgpu::Features::TEXTURE_COMPRESSION_BC```,  got this validation error:
```
[2021-08-24T03:04:39Z ERROR wgpu::backend::direct] wgpu error: Validation Error
    Caused by:
        In Device::create_texture
        The texture usages STORAGE_BINDING are not allowed on a texture of type R16Float
```
texture creation code:
```
let texture = device.create_texture(&wgpu::TextureDescriptor {
    size: extent,
    mip_level_count: 1,
    sample_count: 1,
    dimension: wgpu::TextureDimension::D2,
    format: wgpu::TextureFormat::R16Float,
    usage: Some(wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::STORAGE_BINDING),
    label: None,
});
let tex_view_descriptor = wgpu::TextureViewDescriptor {
    label: None,
    format: Some(wgpu::TextureFormat::R16Float),
    dimension: Some(wgpu::TextureViewDimension::D2),
    aspect: wgpu::TextureAspect::All,
    base_mip_level: 0,
    mip_level_count: None,
    base_array_layer: 0,
    array_layer_count: std::num::NonZeroU32::new(1),
};
let texture_view = texture.create_view(&tex_view_descriptor);
```

OS: macOS 11.5.2, wgpu: 0.10.1

**Comment by kvark** [comment]
On master, I see this error both with and without `TEXTURE_COMPRESSION_BC` feature. It behaves as expected. Could you provide both test cases, please? Either as code, or API traces.

**Comment by jinleili** [comment]
[WGPU_TRACE.zip](https://github.com/gfx-rs/wgpu/files/7043257/WGPU_TRACE.zip)

**Comment by jinleili** [comment]
[WGPU_TRACE 2.zip](https://github.com/gfx-rs/wgpu/files/7043263/WGPU_TRACE.2.zip)

**Comment by jinleili** [comment]
WGPU_TRACE.zip is about validation error, WGPU_TRACE2.zip is about running correctly

**Comment by jinleili** [comment]
Just tested with master and got the same result

**Comment by kvark** [comment]
You aren't enabling `TEXTURE_COMPRESSION_BC`. It's the opposite. In the case that "works", you are enabling all the features:
```
[
Init(
    desc: (
        label: None,
        features: (
            bits: 18324586499,
        ),
```

One of the enabled features is `TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`, which is what makes the validation go away. In the case that fails validation, as expected (!), you are only enabling "TEXTURE_COMPRESSION_BC".
