### ISSUE TITLE
WebGL example broken

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [gfx-rs/wgpu#1862]
**Description**
Unable to run examples using WebGL target.

**Repro steps**
I have followed:
https://github.com/gfx-rs/wgpu/wiki/Running-on-the-Web-with-WebGPU-and-WebGL

And in the browser I get:
```
panicked at 'expected to get context from canvas', /Users/marco/dev/luminvent/wgpu/wgpu/src/backend/web.rs:954:18
```

**Platform**
- Master of wgpu repository
- MacOS and Linux, target Wasm with GL rendering

**Comment by cwfitzgerald** [comment]
Closing due to hal rewrite
