### ISSUE TITLE
Semantics of MapMode

### ISSUE THREAD

**Issue by xq-tec** [gfx-rs/wgpu#1869]
When mapping a `BufferSlice`, we need to provide a `MapMode`, which is **either** `Read` **or** `Write`. But sometimes, we need to map a buffer as read _and_ write, for example:

1. Copy to a staging buffer
2. Map the staging buffer read+write
3. Modifying some of the data in the staging buffer, but not everything
4. Copy from the staging buffer

Is this behavior included in `MapMode::Write`? If yes, then it should probably be renamed to `ReadWrite`. What do you think?

Besides, at least in my very limited experiments, the `MapMode` parameter doesn't seem to have any effect: Even with `MapMode::Read`, the buffer is mapped read/write, and modifications are reflected in the buffer's content. But maybe that's different for non-Vulkan backends, or for discrete GPUs?

**Comment by xq-tec** [comment]
I see. Is there a particular reason why `MAP_READ` and `MAP_WRITE` are mutually exclusive when creating a `GPUBuffer`? I.e., are there backends which don't support mapping a buffer read+write?

(Oh, by the way: thank you for your awesome work on wgpu!)

**Comment by kvark** [comment]
Yes, there are reasons, coming not only from native backends, but also from the Web side of things. Browsers tend to separate the GPU operations into a process, so the data needs to go through an IPC barrier in addition to going through the JS/native barrier. I can dig up more concrete details if interested.
For native-only, we have `MAPPABLE_PRIMARY_BUFFERS` feature, which lifts this restriction.

**Comment by teoxoy** [comment]
Closing as it seems this has been answered.
