### ISSUE TITLE
Using two encoders in hello-triangle example causes hang 

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu#1877]
**Description**
Wgpu hangs when rendering a frame that involved multiple consecutive command encoders. [This patch](https://github.com/fintelia/wgpu/commit/1568d8577cb4e4e10b4df45fbf62e2f7dd87e619) to the hello-triangle example is enough to trigger the bug.  

**Repro steps**

```
$ git clone https://github.com/fintelia/wgpu && cd wgpu
$ git checkout double-encoder-hang
$ cd wgpu
$ cargo run --example hello-triangle
```

**Expected vs observed behavior**
Expected hello-triangle example to run normally. Instead it displays all black and the window cannot be closed.

**Platform**
* Arch Linux
* Intel integrated GPU
* wgpu commit 39e8921fe8ebda314edf5c4787cdbb82281a50de

**Comment by fintelia** [comment]
Via `git bisect` the this is caused by a regression in 5419947095853ee3b91c04f74f0e4193d0d061a8:

```
$ git checkout 39e8921
$ git bisect start
$ git bisect bad
$ git bisect good 91437ea7
$ git bisect test.sh
```



<details><summary>test.sh</summary>

```bash
#!/bin/bash

cat >test.patch << EOF
diff --git a/wgpu/examples/hello-triangle/main.rs b/wgpu/examples/hello-triangle/main.rs
index 4d27af83..25cfef21 100644
--- a/wgpu/examples/hello-triangle/main.rs
+++ b/wgpu/examples/hello-triangle/main.rs
@@ -95,6 +95,11 @@ async fn run(event_loop: EventLoop<()>, window: Window) {
                     .get_current_frame()
                     .expect("Failed to acquire next swap chain texture")
                     .output;
+
+                *control_flow = ControlFlow::Exit;
+                let e2 = device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
+                queue.submit(Some(e2.finish()));
+
                 let mut encoder =
                     device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
                 {
EOF

cd wgpu/examples
if git apply test.patch && cargo build --example hello-triangle
then
	# run project specific test and report its status
    timeout 15 cargo run --example hello-triangle
	status=$?
else
	# tell the caller this is untestable
	status=125
fi
cd ../..

# undo the tweak to allow clean flipping to the next commit
git reset --hard

# return control
exit $status
```

</details>

**Comment by kvark** [comment]
Thank you for investigating!
I wonder if our use of the relay semaphore is incorrect. Vulkan validation has a new experimental option for synchronization, so that could be the next step to enable and see.

**Comment by fintelia** [comment]
I just tried running with the validation layers included with SDK version 1.2.182.0, but they produced no output. Here is a copy of the API dump. The hang seems to be happening during the call to `vkQueuePresentKHR`, which matches the backtrace I got when pausing in a debugger. 

[api_dump.txt](https://github.com/gfx-rs/wgpu/files/7077864/api_dump.txt)

**Comment by mrk-its** [comment]
Ubuntu 20.04.2,  HD Graphics 630 (KBL GT2)

I just tried to reproduce this and I have black window not reacting on events for 8 seconds, then triangle is displayed (and window can be closed). But it seems it is not related to 'using two encoders', I have the same behavior also on current wgpu master.

**Comment by fintelia** [comment]
I'm using an Intel® HD Graphics 520 iGPU with mesa 21.2.1-1. There's no other GPU so the linked PR doesn't seem applicable. 

However reading #1672, I think this might be a duplicate of that given that the hang in `vkQueuePresentKHR` is during an `ioctl`
