### ISSUE TITLE
Cannot call vkDestroyRenderPass on VkRenderPass 0x120000000012[] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to renderPass must have completed execution

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/wgpu#1878]
**Description**
I'm trying to migrate my tutorial to 0.10, and the code compiles just finebut I'm getting a lot of validation on master. 

**Repro steps**
My repo is at https://github.com/sotrh/learn-wgpu. If you checkout the `0.10` branch on Linux and run `cargo run --bin tutorial2-swapchain` a window will pop up and the terminal will be spammed with validation errors.

**Expected vs observed behavior**
No validation errors, or a compile time error / panic.

**Extra materials**
```
Validation Error: [ VUID-vkDestroyRenderPass-renderPass-00873 ] Object 0: handle = 0x5568a5630858, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x473619ad | Cannot call vkDestroyRenderPass on VkRenderPass 0x120000000012[] that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to renderPass must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.148.0/linux/1.2-extensions/vkspec.html#VUID-vkDestroyRenderPass-renderPass-00873)
[2021-08-28T23:03:47Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x5568a5630858, name: ?)
[2021-08-28T23:03:47Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkDestroyFramebuffer-framebuffer-00892 (0xdb308312)]
```
Trace: 
[0-10_trace.zip](https://github.com/gfx-rs/wgpu/files/7071613/0-10_trace.zip)

**Platform**
Linux Mint 19.1
cargo 1.51.0 (43b129a20 2021-03-16)
rustup 1.23.1 (3df2264a9 2020-11-30)
rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by kvark** [comment]
I'm a bit confused to see the subject of this issue being different from the body.
Speaking about the body, the problem is that the swapchain frame is dropped too early.
This is the proper code:
```rust
        let frame = self.surface.get_current_frame()?;
        let view = frame.output.texture.create_view(&wgpu::TextureViewDescriptor::default());
```

It's still our bug to miss this in validation. I'll add something.
