### ISSUE TITLE
"hello-compute" example fails on Windows 10/Intel HD Graphics 630

### ISSUE THREAD

**Issue by Matthew-Maclean** [gfx-rs/wgpu#1881]
Edit: This issue is actually not present on my 1050Ti, it's present when the shader runs on the CPU's integrated graphics, Intel HD Graphics 630, with the most up-to-date driver version (that windows can find) 22.20.16.4749 (published 2017-07-24).

**Description**
Running the "hello-compute" example from this repo produces an output of `[0, 0, 0, 0]` no matter the input. This is the output to stdout:

    No numbers were provided, defaulting to [1, 2, 3, 4]
    Steps: [0, 0, 0, 0]

**Repro steps**
Copy the "hello-compute" example and run it.

**Expected vs observed behavior**
As near as I can tell, it should produce the numbers `[0, 1, 7, 2]`

**Extra materials**
I simplified the example shader so that instead of computing anything it just set the output buffer to ones, the new `main` looks like this:

    [[stage(compute), workgroup_size(1)]]
    fn main([[builtin(global_invocation_id)]] global_id: vec3<u32>) {
        v_indices.data[global_id.x] = u32(1);
        //v_indices.data[global_id.x] = collatz_iterations(v_indices.data[global_id.x]);
    }

However this also fails, outputting `[0, 0, 0, 0]`, so I don't think this is a shader issue.
This is on the crates.io version 0.10.1, I would like to try this on the master git version but there's a dependency resolution issue with web-sys right now so I'll have to wait for that to be fixed to try.

My GPU itself works fine, as far as I can tell. Games work correctly with no graphical glitches and I have even developed some small games successfully with bevy on this computer, which I believe uses wgpu for it's rendering.

**Platform**
Windows 10 64-bit Version 10.0.19042 Build 19042
Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz, 2808 Mhz, 4 Core(s), 8 Logical Processor(s)
~~Nvidia 1050TI Driver 471.68 (latest at time of writing)~~
Intel HD Graphics 630, driver version 2017-07-24

**Comment by cwfitzgerald** [comment]
This passes on my intel gpu locally, so going to mark this as fixed by someone
