### ISSUE TITLE
gles3 issue with multisampled texture

### ISSUE THREAD

**Issue by whiterabbit42k** [gfx-rs/wgpu#1883]
**Description**
Running has error:
```
[2021-08-30T02:46:19Z ERROR wgpu_hal::gles::egl] GLES: [API/Error] ID 1 : GL_INVALID_ENUM in glTexStorage2DMultisample(target=GL_TEXTURE_2D)
```
**Repro steps**
Not sure what is causing it. I have this in a wgsl shader:
```
[[group(0), binding(0)]]
var depth: texture_multisampled_2d<f32>;
```

**Expected vs observed behavior**
Expect to run without error.

**Platform**
wgpu 0.10, linux, x11.

**Comment by kvark** [comment]
What are you running, exactly?

**Comment by Aaron1011** [comment]
I encountered a similar issue. It appears to be caused by creating a texture with `sample_count > ` and `usage` flags of `wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::COPY_SRC`. Using a `usage` flags of just `wgpu::TextureUsages::RENDER_ATTACHMENT` fixes the error.

**Comment by Wumpf** [comment]
I haven't validated myself, but according to this issue it's not possible to have anything but pure render targets for textures with MSAA on WebGL https://github.com/gfx-rs/wgpu/issues/2117
which pretty much implies that you need to do a standard resolve first and can't use an MSAA target for anything else

**Comment by cwfitzgerald** [comment]
Closing in favor of #2117
