### ISSUE TITLE
Cannot create Adapter when Backends is DX11

### ISSUE THREAD

**Issue by eaglekindoms** [gfx-rs/wgpu#1886]
**Description**
 When I create the instance with wgpu::Backends::DX11 and I call the API: instance.request_adapter() to create adapter,
 there is a panic thrown.
( It can work well with dx11 on wgpu-0.9. )

**Repro steps**
Also, I cloned the master branch of wgpu.
Then I run the example of "hello-triangle" with changing the backend from wgpu::Backends::all() to wgpu::Backends::DX11.
It also throws a panic.

**Extra materials**
code: 
```
    let instance = wgpu::Instance::new(wgpu::Backends::DX11);
    let surface = unsafe { instance.create_surface(&window) };
    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::default(),
            // Request an adapter which can render to our surface
            compatible_surface: Some(&surface),
        })
        .await
        .expect("Failed to find an appropriate adapter");
```
log: 
```
Running `target\debug\examples\hello-triangle.exe`
thread 'main' panicked at 'Failed to find an appropriate adapter', wgpu\examples\hello-triangle\main.rs:20:10
stack backtrace:
   0: std::panicking::begin_panic_handler
```
**Platform**
win10, wgpu-0.10.1, rtx2060

**Comment by kvark** [comment]
This is expected. In 0.10 we rewrote the graphics abstraction, and DX11 is simply not (re)written yet.
