### ISSUE TITLE
Creating a buffer and calling copy_buffer_to_buffer every frame causes issues with RenderDoc

### ISSUE THREAD

**Issue by AnotherNathan** [gfx-rs/wgpu#1902]
**Description**
If your create a buffer every frame and use this buffer to upload data to another buffer via CommandEncoder::copy_buffer_to_buffer, using the target buffer seems to confuse RenderDoc.
When using this target buffer, its contents are displayed with all zeros in RenderDoc. In addition any RenderPass attachments that are used in conjunction with that buffer are displayed black.

The application itself seems to work just fine, only what RendeDoc captures seems to be wrong.

This makes debugging with RenderDoc pretty much useless which is very annoying.

**Repro steps**
Run the provided example and capture a frame in RenderDoc. Select the draw call and switch to the Mesh Viewer tab, where you can see that the inputs are all zeros.
Go to the Texture Viewer tab and select the output textures, where you can see that attachment is black.

**Expected vs observed behavior**
I expected to see my buffers contents and what gets rendered to the attachments in RenderDoc.

**Extra materials**
[renderdoc-bug.zip](https://github.com/gfx-rs/wgpu/files/7107114/renderdoc-bug.zip)

**Platform 1**
Windows 10
wgpu-0.10 vulkan backend
AMD RX570 driver version 21.6.1
RenderDoc v1.15

**Platform 2**
Windows 10
wgpu-0.10 vulkan backend
NVIDIA GTX 860M driver version 471.68
RenderDoc v1.15

**Comment by kvark** [comment]
Similar to DX12 issue in https://github.com/baldurk/renderdoc/issues/2323, but here you are running Vulkan.
It may be a sign that our memory mapping (and/or flush+invalidate) are not done correctly, or it may be just a bug in RenderDoc. It's hard to say. Perhaps, you could file it on RenderDoc and hear out the author's thoughts?

**Comment by AnotherNathan** [comment]
Are you sure it is an issues with mapping? If i slightly change the example to create the staging buffer once, and then map it in the render loop, the issue goes away. Moving the buffer creation back into to the loop and therfore recreating the staging buffer every frame, brings the issue back.

[renderdoc-bug.zip](https://github.com/gfx-rs/wgpu/files/7109372/renderdoc-bug.zip)

**Comment by kvark** [comment]
Generally speaking, mapping has the highest chance to confuse RenderDoc. I don't know what exactly the problem is here.

**Comment by AnotherNathan** [comment]
Ok I reworked my engine to map staging buffers instead of recreating them every frame. This seems to work fine with RenderDoc. I will therefore close this issue now.

**Comment by gardell** [comment]
I also ran into this, so I created https://github.com/baldurk/renderdoc/issues/2372 and made a small commit that reproduces the issue: https://github.com/gardell/wgpu/commit/c65681bb33ccd4726d5f173a838edc49148b700e :slightly_smiling_face:
