### ISSUE TITLE
wgpu build with deno is slow and large git fetch

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#1913]
**Is your feature request related to a problem? Please describe.**
wgpu depends on deno, which has several submodules totally  > 1 GB of data to fetch and resolve.

**Describe the solution you'd like**
Option to not build deno when e.g., building examples.

**Describe alternatives you've considered**
Have not tried (it was not a dep in the past)

**Additional context**
Time to build shadow example was completely dominated by git deno dep and it's submodule fetches; normally this machine can build example in release in about 1 minute or so, but it took:
```
    Finished release [optimized] target(s) in 17m 23s
```
on my not great internet connection.

**Comment by kvark** [comment]
One option here is to just move deno stuff out of the workspace.
