### ISSUE TITLE
Hal/Dx12: D3DCompile Error when WGSL fragment shader contains the function: textureDimensions

### ISSUE THREAD

**Issue by flowjo-isaach** [gfx-rs/wgpu#1927]
I get a validation error when WGPU attempts to compile a WGSL fragment shader containing the function `textureDimensions`. This happens only when I run my app on Windows, this error does not happen on MacOS. The error goes away if I stub in a value this function should return. The version of WGPU I'm using is 10.0.1.

line that causes error:
`var tex_width: i32 = textureDimensions(my_texture).x;`

error message:
```
[2021-09-08T21:55:47Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_render_pipeline
          note: label = `Render Pipeline`
        Internal error in FRAGMENT shader: D3DCompile error (0x80004005): C:\path\to\repo): error X3000: syntax error: unexpected token 'texture'
    C:\path\to\repo): error X3086: untyped textures are deprecated in strict mode
```

**Platform**
OS: Windows
WGPU: 10.0.1

**Comment by kvark** [comment]
Could you please provide the full shader? We have this tested, I'm surprised something slipped through.

**Comment by cwfitzgerald** [comment]
Closing as stale.
