### ISSUE TITLE
wgpu exhausts NSDrawable resources from CAMetalLayer when window isn't visible

### ISSUE THREAD

**Issue by xacrimon** [gfx-rs/wgpu#1936]
**Description**
wgpu exhausts NSDrawable resources from CAMetalLayer when window isn't visible. Every frame, wgpu calls `nextDrawable` on `CAMetalLayer` in the Metal API to fetch a backbuffer to render onto. When the window isn't in focus or visible, the pool gets exhausted and wgpu panics.

**Repro steps**
- Create any example that unconditionally renders on `WindowEvent::MainEventsCleared`.
- Run the program.
- Hide it or put another window over it and remove focus.

**Expected vs observed behavior**
I expected wgpu stop rendering when the window isn't visible (when `NSWindowOccludedState`) is false. This is because one of the power saving optimizations on M1 is to stop some of Metal's housekeeping tasks such as object reclaiming when the window isn't in focus. The observed behaviour is that wgpu doesn't not respect this or expose an option to find out when the window is visible or not. This quickly exhausts the pool and causes a panic.

**Extra materials**
![Screen Shot 2021-09-10 at 19 42 21](https://user-images.githubusercontent.com/21025159/132895353-fed798b5-246f-48c2-b9b8-edd844e4ccda.png)

**Platform**
M1 MacBook Air with Big Sur

**Comment by xacrimon** [comment]
Filed https://github.com/rust-windowing/winit/issues/2022 so the user can conditionally render.

**Comment by kvark** [comment]
#1938 was merged, but now I realize the solution needed to be a little different. @xacrimon would you be able to change it?

**Comment by kvark** [comment]
closed by #1946
