### ISSUE TITLE
dvec3 division broken

### ISSUE THREAD

**Issue by timokoesters** [gfx-rs/wgpu#1941]
**Description**
Dividing a dvec3 by a number seems to make components NaN:

```
#version 450

layout(location = 0) in vec3 fragColor;
layout(location = 0) out vec4 outColor;

void main() {
    dvec3 diff = dvec3(0, 0, 1);
    if (isnan((diff / 1.0).x)) { outColor = vec4(1.0, 0.0, 0.0, 1.0); }
    else { outColor = vec4(0.0, 1.0, 0.0, 1.0); }
}
```

This will mark all points red. If you try the same with vec3 or inline it like this: `isnan((dvec3(0, 0, 1) / 1.0).x)` it shows them as green.

**Extra materials**
I compiled the shader using `glsl_to_spirv::compile(fs, glsl_to_spirv::ShaderType::Fragment).unwrap();` and am using these features: SHADER_FLOAT64 | BUFFER_BINDING_ARRAY | STORAGE_RESOURCE_BINDING_ARRAY | VERTEX_WRITABLE_STORAGE,

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

AdapterInfo { name: "Intel(R) HD Graphics 620 (KBL GT2)", vendor: 32902, device: 22806, device_type: IntegratedGpu, backend: Vulkan }
wgpu 0.10.1
naga 0.6.3

**Comment by danwilhelm** [comment]
The [documentation](https://github.com/gfx-rs/wgpu/blob/master/wgpu-types/src/lib.rs#L2314) suggests it might also require the feature `VERTEX_ATTRIBUTE_64BIT`?

**Comment by cwfitzgerald** [comment]
@danwilhelm That's only needed if you have `dvec*` in the `in/out` to a shader. This example uses normal floats.

**Comment by timokoesters** [comment]
You should be able to test this on https://github.com/timokoesters/nbodysim/tree/wgpu-bug (the wgpu-bug branch)

**Comment by kvark** [comment]
@timokoesters could you run the shader through Naga cli to see what the output looks like? Using `spirv-dis` on the output should show us interesting things.

**Comment by timokoesters** [comment]
If you are still interested in this I can run `spirv-dis` on the output tomorrow.

**Comment by kvark** [comment]
Tried to run it on TigerLake GT2 and got an initialization error:
```
Using default config.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

AdapterInfo { name: "Intel(R) Xe Graphics (TGL GT2)", vendor: 32902, device: 39497, device_type: IntegratedGpu, backend: Vulkan }
 ERROR wgpu_hal::vulkan::instance > GENERAL [Loader Message (0x0)]
        terminator_CreateDevice: Failed in ICD /nix/store/dgixgl68gaicsc5i7wj2chbrjgc5rdvp-mesa-21.2.3-drivers/lib/libvulkan_intel.so vkCreateDevicecall
 ERROR wgpu_hal::vulkan::instance >     objects: (type: INSTANCE, hndl: 0x55f2b4503ac0, name: ?)
 ERROR wgpu_hal::vulkan::instance > GENERAL [Loader Message (0x0)]
        vkCreateDevice:  Failed to create device chain.
 ERROR wgpu_hal::vulkan::instance >     objects: (type: INSTANCE, hndl: 0x55f2b4503ac0, name: ?)
 ERROR wgpu::backend::direct      > Error in Adapter::request_device: connection to device was lost during initialization
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RequestDeviceError', src/render.rs:75:10
```

That's quite worrying. It doesn't really tell me what went wrong, and wgpu's examples initialize fine.

**Comment by timokoesters** [comment]
> You should be able to test this on https://github.com/timokoesters/nbodysim/tree/wgpu-bug (the wgpu-bug branch)

I ran into panic as well on one of my machines. Now I updated the wgpu-bug branch and disabled the fullscreen mode. That got rid of the panic for me. Also see  https://github.com/gfx-rs/wgpu/issues/2155

**Comment by kvark** [comment]
I can't run your example because FLOAT64 aren't supported on my platform, see #2159

**Comment by timokoesters** [comment]
Ok, I will build a minimal example to reproduce this tomorrow

**Comment by teoxoy** [comment]
@timokoesters do you have any updates on this?

**Comment by timokoesters** [comment]
No, sorry. My old wgpu-bug branch also doesn't work anymore on my laptop and I don't have time to upgrade the nbodysim project to a newer winit and wgpu version.

**Comment by cwfitzgerald** [comment]
Closing as out of date, we don't currently support f64 in naga.
