### ISSUE TITLE
Stencil texture causing weird behavior when updating from 0.9 to 0.10

### ISSUE THREAD

**Issue by HolgerGottChristensen** [gfx-rs/wgpu#1943]
**Description**
When I updated my project from wgpu 0.9 to wgpu 0.10, I started seeing some glitchy rendering behavior on MacOS. This seems to happen when drawing to and reading from the stencil texture. I have below included traces and screenshots of the behavior.

**Repro steps**
I have not created a minimum example, but have included the traces both using wgpu 0.9 and 0.10. Hopefully this is enough :)

**Expected vs observed behavior**
I expect to see the same rendered output for both versions.
https://youtu.be/eXKrGu2HvM0 (The correctly working version using wgpu 0.9)
vs
https://youtu.be/GFsP1rLP2_g (The version I see strange behavior using wgpu 0.10)

**Extra materials**
I tried doing some digging using your debugging with xcode tutorial (quite nice tutorial), but I am not sure what exactly I should be looking for (I have not really used the debugger before). I seem to not have metal validation available, maybe because I am using an older mac.

From what I did find it seems like it is rendering to 1 in 4 pixels, and that might cause everything to show up strangely. 
The first screenshot is what I see when running with wgpu 0.9:
<img width="1506" alt="Skærmbillede 2021-09-12 kl  11 15 36" src="https://user-images.githubusercontent.com/11473146/132982381-57b03be2-e255-4bd3-b67e-67ae4a63351b.png">
It looks as expected having nice white pixels where I have my stencil texture.
The second screenshot is what I see when running with wgpu 0.10 and the texture looks like it has been rendered wrong.
<img width="1506" alt="Skærmbillede 2021-09-12 kl  11 04 51" src="https://user-images.githubusercontent.com/11473146/132982486-20408096-80ba-4832-8c55-f3dce79bff45.png">
An export of the stencil texture can be seen below:
![Stencil: Depth texture descriptor](https://user-images.githubusercontent.com/11473146/132982693-da481c83-5031-4dd6-88a8-29da8f477293.png)

There are some warnings that I am binding the same texture multiple times but these errors exist in both versions.

Below I have included traces for both versions.
[trace0_9.zip](https://github.com/gfx-rs/wgpu/files/7149353/trace0_9.zip)
and
[trace0_10.zip](https://github.com/gfx-rs/wgpu/files/7149355/trace0_10.zip)

**Platform**
Wgpu v0.10
MacOS 10.15 Catalina
Intel Iris Pro 1536 MB
Rust 1.51

**Comment by kvark** [comment]
So far it looks to me that the on some frames the stencil load op is Load instead of Clear. So after the stencil is resized with the window, it's all garbage. Related to #1102

**Comment by HolgerGottChristensen** [comment]
The glitchyness is fixed, but I still think there is a problem because it is still drawing the second triangle without taking into account for the stencil map.

Here is a gputrace from xcode: [shapes.gputrace.zip](https://github.com/gfx-rs/wgpu/files/7154579/shapes.gputrace.zip)

I think this is the most important part:
<img width="1506" alt="Skærmbillede 2021-09-13 kl  15 26 58" src="https://user-images.githubusercontent.com/11473146/133091950-c89905e4-4eae-4d08-a025-7aff34a4496a.png">

I read it as drawing all the 6 vertices at in the same call and all within the stencil.
