### ISSUE TITLE
Re-align hal::FenceValue with SubmissionIndex

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1953]
It turns out we can't use `AtomicU64` because not all platforms have it - #1935
But `hal::FenceValue` is currently `u64`. So there is a bit of disconnect happening on platforms where `usize` != `u64`.
```rust
    fn use_at(&self, submit_index: SubmissionIndex) -> bool {
        self.submission_index
            .store(submit_index as _, Ordering::Release);
```
Code like this should not be there. We need to either avoid conversion, or handle it carefully.

**Comment by cwfitzgerald** [comment]
No longer a thing.

**Comment by cwfitzgerald** [comment]
(AtomicFenceValue is a u64)
