### ISSUE TITLE
Clean up ConsumeIterator

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#198]
The iterator was introduced in #195 as a means to enforce that the internal state of the tracker gets updated regardless of whether the caller iterates the iterator or not. This has been considered unsound and should be refactored.

**Comment by kvark** [comment]
Talked to @Gankro about this issue, and to my surprise a similar behavior is well exposed by the standard library in the form of `Drain` iterator: it also has side effects, and it also cleans up after itself.

Another voiced suggestions where to put `#[must_use]` on either the return type or the function, although I think these are less feasible in our API.

With this in mind, I'm going to close this with the conclusion that `ConsumeIterator` is good enough.

**Comment by Gankro** [comment]
relevant links: 

https://doc.rust-lang.org/src/alloc/vec.rs.html#2519-2538

https://github.com/rust-lang/rust/blob/5d20ff4d2718c820632b38c1e49d4de648a9810b/src/libcore/cmp.rs#L192

https://github.com/rust-lang/rust/blob/316a391dcb7d66dc25f1f9a4ec9d368ef7615005/src/libcore/fmt/builders.rs#L79

**Comment by Gankro** [comment]
also just be sure you aren't worried about mem::forget: https://doc.rust-lang.org/nightly/nomicon/leaking.html#drain

**Comment by kvark** [comment]
Fortunately, this type isn't exposed to the outside world, and we have no intention to forget about it :)
