### ISSUE TITLE
Validation error rejects storage formats

### ISSUE THREAD

**Issue by HeroicKatora** [gfx-rs/wgpu#1980]
That may let you investigate on your own, or provide additional information that helps us to assist.-->

**Description**
Validation Complains about requiring `TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES` but it shouldn't. If we look at [WebGPU](https://www.w3.org/TR/webgpu/#plain-color-formats) draft then R32Uint must be allowed for read-write storage bindings.

**Repro steps**

Created such a layout entry:

```
BindGroupLayoutDescriptor { label: None, entries: [BindGroupLayoutEntry { binding: 2, visibility: FRAGMENT, ty: StorageTexture { access: ReadWrite, format: R32Uint, view_dimension: D2 }, count: None }] 
```

**Expected vs observed behavior**
Expect: The pipeline entry is accepted without an enabled feature.
Observed: Validation error which makes non-native use impossible.

**Extra materials**

**Platform**

`wgpu = 0.10.1`
[Cargo.lock.gz](https://github.com/gfx-rs/wgpu/files/7193060/Cargo.lock.gz)

**Comment by cwfitzgerald** [comment]
Currently webgpu only supports write only storage textures. In not sure if this is reflected in either main draft of webgpu.

As such this is expected behavior.
