### ISSUE TITLE
Web backend crashes when initialized within a worker

### ISSUE THREAD

**Issue by strax** [gfx-rs/wgpu#1986]
**Description**
The web backend [uses `web_sys::window`](https://github.com/gfx-rs/wgpu/blob/master/wgpu/src/backend/web.rs#L954) to obtain a handle to the global `Navigator` object. This does not work when called from a worker scope since there is no `window` global variable nor a `Window` interface.

**Repro steps**
Create a `Worker` that executes a Rust program compiled to WebAssembly calling `wgpu::Instance::new`. Unfortunately I don't have a minimal repro available at the moment.

**Expected vs observed behavior**
Observed behavior: the web backend tries to obtain a handle to the `window` object and performs an `instanceof` check against the `Window` interface, which does not exist in the worker scope. This results in an error:
```
Uncaught (in promise) ReferenceError: Window is not defined
```

Expected behavior: 
In a worker scope, a [`web_sys::WorkerGlobalScope`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WorkerGlobalScope.html) could be used instead to obtain the `Navigator` handle, but this might be tricky in practice (https://github.com/rustwasm/wasm-bindgen/issues/1046). Since the program will crash and not return `None` when `window` is not available, it is not enough to use `Option::or` to fall back to, say, `web_sys::global()`. Based on https://github.com/rustwasm/wasm-bindgen/issues/1982#issuecomment-579131489, this is a problem with other `web_sys` consumers too and might require some glue code like [this](https://github.com/rustwasm/gloo/blob/f9b1727481125f1f2e3d052137f92d1e6de9af93/crates/timers/src/callback.rs#L19-L38).

**Platform**
* `wgpu` version: master

**Comment by codeart1st** [comment]
Can confirm this for me. Tried an experiment with OffscreenCanvas and run into the same problem.

**Comment by teoxoy** [comment]
I believe this was fixed by https://github.com/gfx-rs/wgpu/pull/2858, closing.

**Comment by codeart1st** [comment]
`self.Window = WorkerGlobalScope` is still needed for me.

https://github.com/codeart1st/wgpu-layers/blob/main/demo/src/worker.js#L9
