### ISSUE TITLE
failed to create buffer in a mapped state: The requested mapping access did not match the expected usage

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#199]
Just a heads up that sometime in between me testing https://github.com/gfx-rs/wgpu/pull/197 and it getting merged this started happening:
```
[2019-05-31T14:33:39Z ERROR wgpu_native::device] failed to create buffer in a mapped state: The requested mapping access did not match the expected usage
Segmentation fault (core dumped)
```

I'll try to follow this up with a repro when I get the chance.

**Comment by kvark** [comment]
What is your platform? Do the examples run for you?
We've had another report of this problem on Linux/Vulkan. I'm investigating, but I can't repro it locally on Intel, so I'd need your help.
Also cc @omni-viral
