### ISSUE TITLE
`Queue::write_texture` appears to require row padding for `Texture`s with depth > 1 on Linux/Vulkan

### ISSUE THREAD

**Issue by mitchmindtree** [gfx-rs/wgpu#1990]
**Description**

Partly to workaround #1672 and partly to achieve better efficiency, I rewrote nannou's `Texture` constructor short-hand functions to use `Queue::write_texture`, rather than creating and submitting a command buffer each time. One of these updated functions loads a 3D texture from a sequence of image buffers with equal dimensions (see [here](https://github.com/nannou-org/nannou/blob/4f797869fca282f3dac756227c091c768a8e7886/nannou_wgpu/src/texture/image.rs#L590-L664)).

After changing this function to use `Queue::write_texture`, I noticed that our `wgpu_image_sequence.rs` example began to show strange behaviour. The example loads a sequence of small PNGs into a single texture to demonstrate how a single 3D texture can be used for animation. When creating an texture view from any layer other than the first, the view appears vertically offset, which suggested to me that the texture's image data layout might be incorrect. Here's example of how the offset looks:

![Screenshot from 2021-09-22 10-52-00](https://user-images.githubusercontent.com/4587373/134301791-a7fc0a64-03a8-482a-9633-26e51d1fd775.png)

Curiously, this only occurs on Linux + Vulkan and doesn't seem to occur on the default macOS and Windows backends.

I noticed that if I manually pad the rows to meet the multiple-of-256-bytes requirement mentioned [in the docs of the `bytes_per_row` field](https://docs.rs/wgpu/0.10.1/wgpu/struct.ImageDataLayout.html#structfield.bytes_per_row), the problem goes away, however the same docs also mention that the requirement should not apply when using `Queue::write_texture`. I can confirm that the requirement doesn't apply when creating single layer textures (these appear to work fine across platforms) - it only appears to be Linux/Vulkan that's the issue.

**Repro steps**

Fetch the branch of [this PR](https://github.com/nannou-org/nannou/pull/795) and `cargo run --example wgpu_image_sequence` from the workspace root on Linux+Vulkan (haven't yet tried Windows+Vulkan).

**Platform**

Linux, GNOME, Wayland, Intel iGPU, Vulkan, wpgu 0.10.1 ([this PR](https://github.com/nannou-org/nannou/pull/795)).

**Comment by kvark** [comment]
If found a problem that would explain what you are seeing but haven't confirmed on the same platform. If you can check #1992 locally, that would be the best :)

**Comment by mitchmindtree** [comment]
> If you can check #1992 locally, that would be the best :)

Nice one @kvark, can confirm that fixes the issue!
