### ISSUE TITLE
on A8 | A9 chip iOS devices, read-only storage buffer causes irregular random values to be queried within the shader

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/wgpu#1997]
**Description**
After repeated debugging, it is confirmed that if the storage buffer is set to read_only: true, the above problem occurs when running on A8 | A8X | A9 chip's iOS device, and the problem disappears after changing to read_only: false.

Not verified on the A10 | A11 devices, A12 to A14 can confirm that there are no such problem.

[iOS demo](https://github.com/jinleili/wgpu_on_ios)

**Comment by kvark** [comment]
Could you give #1998 a shot?

**Comment by jinleili** [comment]
Run ```ios-storage``` branch test on A8 device, the problem remains and there is no output of the validation error logs.
Cargo.toml config:
 ```
wgpu = {git = "https://github.com/kvark/wgpu", rev="97cfdc363f0f84460e305e0e8c31d0ea956c207b"}
```

**Comment by kvark** [comment]
Thanks for giving it a shot! I thought that setting the mutability makes the driver confuse things, but it appears to be something else. On the API side there is no other difference between read-only and read-write buffers. So the only thing left is how the shader code is generated. Maybe we are missing something from Metal spec...

**Comment by cwfitzgerald** [comment]
A8/A9 are no longer supported formally under WebGPU. I would consider this out of scope now.
