### ISSUE TITLE
wgpu readme on crates.io has broken examples link

### ISSUE THREAD

**Issue by stephanemagnenat** [gfx-rs/wgpu#2007]
**Description**
Once published on crates.io, the wgpu crate's readme has a broken link to examples. Indeed, the link becomes https://github.com/gfx-rs/wgpu/tree/v0.10/blob/HEAD/examples which does not exist.

The problem is that the crate is not at the top level of the repository. I do not know whether that is actually a bug in cargo's publication process or if there is something to specify to get that right, but as a user it appears as a bug.

**Repro steps**
Go here: https://crates.io/crates/wgpu, browse to the usage section, click on the "examples" link and see the 404.

**Expected vs observed behavior**
I expect the links on the crates.io page to work, especially the example one.

**Comment by teoxoy** [comment]
Link works now, seems to have been fixed upstream (https://github.com/rust-lang/crates.io/issues/3484).
