### ISSUE TITLE
How is WARP activated?

### ISSUE THREAD

**Issue by Korijn** [gfx-rs/wgpu#2010]
I noticed in #1739 and the README that you are running tests on Windows CI with WARP, but I don't see any explicit steps where WARP is activated. Does that happen automatically?

**Comment by cwfitzgerald** [comment]
WARP manifests as just another adapter on windows, so if we're running on a headless box like ci, WARP will just be the only adapter you get.

**Comment by kvark** [comment]
Also, @Korijn reminded me that we needed to catch up on the upstream adapter selection, which allows forcing the software, if needed. This is now implemented in #2011.

**Comment by Korijn** [comment]
Thanks for the swift reply!
