### ISSUE TITLE
Web backend fails to extract context from HTML canvas

### ISSUE THREAD

**Issue by Kiomarou** [gfx-rs/wgpu#2013]
**Description**
Passing a canvas element (made via winit or web-sys) to create_surface on an Instance object results in the error "panicked at 'expected to get context from canvas" in console log.
```C:\Users\Shaymus.Pony\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.10.2\src\backend\web.rs:954:18```

The wgpu.rs examples page also produces the same error:
https://wgpu.rs/examples/?example=hello-triangle
I am getting this error on the latest version of Chrome Canary and Firefox Nightly, webgpu is enabled and
https://austin-eng.com/webgpu-samples/samples/helloTriangle works for me (javascript webgpu) just not wgpu

**Repro steps**
1. Init wgpu
2. Make a HTML5 canvas within rust via winit (window.canvas) or web-sys directly.
3. Invoke create_surface() on the instance, supplying the canvas.
4. The error occurs on run.
e.g. as in https://github.com/gfx-rs/wgpu-rs/blob/master/examples/framework.rs

**Expected vs observed behavior**
Clearly describe what you get, and how it goes across your expectations.

**Extra materials**
![image](https://user-images.githubusercontent.com/25067779/135679511-484fe2ba-7340-4fd4-b707-6e084f64f6ba.png)

Note: I'm not sure if it's the cause but I noticed that the context "gpupresent" is deprecated and should be "webgpu" but 0.10 (current e.g. 0.10.2) crate source still uses "gpupresent".
https://crates.io/crates/wgpu points to
https://github.com/gfx-rs/wgpu/blob/83461389d6ada2e45d5fb5679564f8249a220669/wgpu/src/backend/web.rs#L952

While current master states the version is the previous version, 0.10.1:
https://github.com/gfx-rs/wgpu/blob/master/wgpu/Cargo.toml and appears to use "webgpu" correctly:
https://github.com/gfx-rs/wgpu/blob/master/wgpu/src/backend/web.rs

**Platform**
Windows 10.

**Comment by djsell** [comment]
I believe WebGL just isn't supported yet after a transition of backend libraries a while back.

Current in progress pull request for re-adding support is here:
https://github.com/gfx-rs/wgpu/pull/1686

**Comment by kvark** [comment]
Since WebGPU isn't stable yet, you can't expect any released version of `wgpu`, including 0.10, to work forever. The context name changed semi-recently from "gpupresent" to "webgpu", which is a breaking change, so 0.10 can't run on the Web any more, and that's expected.

**Comment by Kiomarou** [comment]
You are correct. We had no such expectations. Breaking changes are bound to happen since WebGPU isn't stable yet. However we simply observed this breaking change and would like to report it as such that it would be good to be fixed accordingly.

I now noticed this breaking change was fixed in master but hasn't been pushed to crates.io yet. In the case this was forgotten we'll request an update for the crate on crates.io to fix this breaking change.

**Comment by kvark** [comment]
It doesn't make sense to back-port to the released version, I think. For people targeting the browsers, they should pick a concrete version of `wgpu` and a concrete version of a browser. Allowing any of these two to diverge is guaranteed to break.

**Comment by Kiomarou** [comment]
I am not sure what you mean about backporting, as the current version in the repo has already fixed this issue, however the crate on crates.io does not reflect this even though both versions are 0.10.2:
![image](https://user-images.githubusercontent.com/25067779/135766079-0ddb81d6-af2d-400d-ba72-d8683985d7b7.png)

**Comment by kvark** [comment]
We publish from a branch, "v0.10" in this case. The version in `master` doesn't matter at all, since nobody is expected to override crates release by git master. "Backporting" means taking a patch and copying it into v0.10 branch, often releasing a patched crate with it.
