### ISSUE TITLE
Should present() be on a Queue?

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2028]
Follow up to #2021

Pro: in the backends, the queue is either explicitly, or implicitly used.
Con: it's also used in `acquire()` and it has to match. So passing it only to `present()` seems weird?
Also, the current way is somewhat similar to buffers. Mapping a buffer has to be ordered with respect to any queue submissions of this buffer, but the `map()` is on a buffer, not a queue.

**Comment by genusistimelord** [comment]
I guess another question would be if this would affect performance And or Affect the way someone could layout their rendering in a negative fashion? What would it look like compared to what you currently have?
