### ISSUE TITLE
Avoid CPU readback in WebGL backend

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2031]
**Is your feature request related to a problem? Please describe.**
Copying to/from an index buffer currently involves a CPU readback, which is unexpected.
See https://github.com/gfx-rs/wgpu/pull/1686#discussion_r724501932

**Describe the solution you'd like**
Forbid GPU copies between index and non-index buffers under WebGL. Allow only index-index, or staging-index, or index-staging copies.

**Describe alternatives you've considered**
keep the readback

**Additional context**
we want wgpu-hal to be *really* close to HW, not polyfilling all the holes

**Comment by mrk-its** [comment]
Let's close it, it is solved by #2112
