### ISSUE TITLE
Water Example Not Working on WebGL

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#2032]
**Description**

**Repro steps**
Run `./run-wasm-example.sh water` in the WGPU repo.

**Expected vs observed behavior**

The water is invisible, when it should be visible.

**Extra materials**

Observed:

![image](https://user-images.githubusercontent.com/25393315/136456630-e2141f7e-c2bd-422c-b3de-fa255bd6f8c3.png)

Expected:

![image](https://user-images.githubusercontent.com/25393315/136456713-2cc9ce04-0767-4684-9330-59b80c914b7b.png)

**Platform**

WebGL2

---

The issue with the water rendering has something to do with the water shader. Context on exactly what causes the shading issue is here: https://github.com/gfx-rs/wgpu/pull/1686#issuecomment-884596050.

I don't currently understand the fix necessary.

**Comment by cwfitzgerald** [comment]
This is expected behavior due to rods

**Comment by zicklag** [comment]
Should we update the example shader to use a different entrypoint for WebGL, so that we can get it displaying, just without the extra blurring around the water border ( like this https://github.com/gfx-rs/wgpu/pull/1686#issuecomment-884596050 )?
