### ISSUE TITLE
Fix WebGL Lint Warnings in WebGL Examples

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu#2040]
**Description**
When running the WebGL examples with [WebGL lint](https://github.com/greggman/webgl-lint) enabled, we get some errors in the console that we should fix.

**Repro steps**

To enable WebGL lint I created a modified version of the `run-wasm-example.sh` script and I also used a modified version of the WebGL lint JavaScript script that would disable the warnings about `undefined` arguments, which is not harmful and is a side-effect of the way that wasm-bindgen specifies the arguments.

Here is a gist with both the modified `run-wasm-example.sh` script that I used and the modified WebGL lint script.

https://gist.github.com/zicklag/7c586299a5d1843b9a75a6b812a926ad

*Yes this is a little annoying and hack-ish. Maybe we should build WebGL lint into our `run-wasm-example.sh` script as an optional flag or something.*

**Expected vs observed behavior**
Expected no errors or warnings in the console from WebGL lint.

**Extra materials**

**Platform**

**Comment by cwfitzgerald** [comment]
I'm not entirely sure this is something we really want to do.
