### ISSUE TITLE
Device lost with dispatch_indirect() - (missing docs and sanity checks)

### ISSUE THREAD

**Issue by dwbrite** [gfx-rs/wgpu#2044]
## Update

`dispatch_indirect()` should be called not with a buffer of _data_, but with a "command" buffer, something roughly equivalent to:

```
typedef struct VkDispatchIndirectCommand {
    uint32_t    x;
    uint32_t    y;
    uint32_t    z;
} VkDispatchIndirectCommand;
```

**Solution** 
✅ document the exact structure required
🔲 add sanity checks on the `indirect_buffer` param. 

---

Original Issue Below

--- 

**Description**

> A clear and concise description of what the bug is.

I don't know where to even _start_ describing this. Basically I have two compute shaders, one runs with `dispatch_indirect(some_storage_buffer)` and does nothing. The other runs with `dispatch(X, 1, 1)` and adds a small amount of objects to `some_storage_buffer`.

When only _one_ shader is run (either/or), the program runs fine. When both shaders are run, the device is lost and the program crashes. If both shaders are run _but a new buffer is used for dispatch_indirect_, it appears not to crash.

On Linux + Mesa, these crashes can freeze the OS or ["corrupt" the desktop environment](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/ENDgXACoFomEJZdUlscVNSqm).

**Repro steps**
Example: https://github.com/dwbrite/wgpu-particle-demo/tree/distill-breakage
Trace: https://github.com/dwbrite/wgpu-particle-demo/blob/distill-breakage/trace/trace.zip

**Expected vs observed behavior**
expected 👍, observed 🔥

**Extra materials**
See link above

**Platform**
Tested on PopOS with a Ryzen 3500u, and on Windows and OpenSUSE Tumbleweed on a Ryzen 7 2700x + RX 470.
Vulkan, GL, and DX12.

\+ confirmed freezing on some macbook from like 2013 :^)

**Comment by dwbrite** [comment]
The problems seems to manifest similarly across Vulkan, DX12, and GL. 

Vulkan and GL have a tendency to corrupt the DE session, DX12 manages to figure out something is wrong and reports: 

`ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]`

Again, only when _both_ shaders are run. If just one xor the other runs, then it's fine.

This occurs even when the shaders are submitted with different CommandEncoders.

**Comment by dwbrite** [comment]
So this gets weirder still! The program runs fine when calling `dispatch(...)` instead of `dispatch_indirect(some_storage_buffer)`! Which means it's probably not anything wrong in the shaders.

When I get time I'm going to start looking into wgpu-hal and wgpu-core to see if `dispatch_indirect()` is doing anything funny with the buffer.

**Comment by kvark** [comment]
I was just playing with your example. So the buffer contains some floating point data, and you are passing it as an indirect arguments buffer, which expects 3 integers. So it comes down to the missing piece in wgpu that would run a compute job to analyze and clamp the indirect buffer contents.

**Comment by dwbrite** [comment]
> So it comes down to the missing piece in wgpu that would run a compute job to analyze and clamp the indirect buffer contents.

I'm not sure it's a good idea to clamp the buffer contents, since that would modify the user's data. That could be a problem in the case where a user is sending an array of arguments in the buffer. We should figure out exactly why what I've done above is so problematic. My immediate guess is that floats being read as u32 were higher than the max workgroup count.

**Comment by teoxoy** [comment]
This will be fixed once we get to https://github.com/gfx-rs/wgpu/issues/2431
