### ISSUE TITLE
DX12 panic for code that works fine on Vulkan

### ISSUE THREAD

**Issue by superdump** [gfx-rs/wgpu#2060]
**Description**

> Oct 12 15:46:20.691 ERROR wgpu_hal::dx12::instance: ID3D12Device::CreateShaderResourceView: The Dimensions of the View are invalid due to at least one of the following conditions. MostDetailedMip (value = 0) must be between 0 and MipLevels-1 of the Texture Resource, 0, inclusively. With the current MostDetailedMip, MipLevels (value = -1) must be between 1 and 1, inclusively, or -1 to default to all mips from MostDetailedMip, in order that the View fit on the Texture. First2DArrayFace (value = 0) must be between 0 and ArraySize-6 of the Texture Resource, 54, inclusively. [ STATE_CREATION ERROR #31: CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS

**Repro steps**

Grab bevy on the `pipelined-rendering` branch at commit https://github.com/bevyengine/bevy/commit/43e8a156fb4739abee3060c53140f4a94cab9ae5 which upgrades to wgpu 0.11 / naga 0.7 for the new reworked renderer. Run `WGPU_BACKEND=dx12 cargo run --example 3d_scene_pipelined`.

**Expected vs observed behavior**

Expected: No panic, like with Vulkan.
Observed: A panic.

**Platform**

Windows 10, DirectX 12, wgpu 0.11, naga 0.7.

**Comment by kvark** [comment]
published in wgpu-hal-0.11.2
