### ISSUE TITLE
Synchronizing transfers into the same resource

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2065]
Tuning into Vulkanized event, I asked:
> what about write-write hazards in transfer commands? i.e. when there are 2 copies into the same buffer, unsynchronized

Answer from John Zulauf:
> They are only hazards if they write the same regions of the buffer.  If they do write the same regions, then that is a hazard and requires a barrier to have predictable results.

So it looks like we need to extend the logic that detects write-write conflicts. It currently only triggers for storage writes, and we need to extend it to transfers.

**Comment by cwfitzgerald** [comment]
This is handled
