### ISSUE TITLE
Uniform block sizes seem to be rounded up to the nearest 16 on WebGL

### ISSUE THREAD

**Issue by Liamolucko** [gfx-rs/wgpu#2072]
**Description**
WebGL seems to be rounding the size of uniforms up to the nearest 16, causing errors to be thrown when the slightly-smaller buffer is passed to a draw call. Adding some padding to the buffer solves the problem.

**Repro steps**
None of wgpu's examples use uniforms with alignments less than 16, so I created a toy example which draws a vertical line: https://github.com/Liamolucko/wgpu-uniform-repro. Build with `cargo build && wasm-bindgen target/wasm32-unknown-unknown/debug/wgpu-uniform-repro.wasm --target web --out-dir pkg`, and then start a http server for the folder.

**Expected vs observed behavior**
Expected:
![image](https://user-images.githubusercontent.com/43807659/137432167-cffae936-8109-4961-a22c-0f2f83eac0f2.png)
Observed:
![image](https://user-images.githubusercontent.com/43807659/137432209-4ad3ce6c-e207-4396-ab4f-27a98d444c4e.png)
```
WebGL warning: drawArraysInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. wgpu-uniform-repro.js:604:25
```

**Platform**
`wgpu` 0.11.0, Firefox 93 (also fails in Chromium), Manjaro Linux, nVidia GeForce GTX 780.

**Comment by Liamolucko** [comment]
Apparently this used to be a layout requirement for uniform buffers, but was removed in gpuweb/gpuweb#1560.

**Comment by kvark** [comment]
This isn't a clear as we'd hope. See https://github.com/gpuweb/gpuweb/issues/1558 and https://github.com/austinEng/webgpu-samples/issues/149, which notably has zero responses.
Finally, clarification from @Kangz confirms that we end up requiring 16-byte aligned uniform buffers in the end - https://github.com/gpuweb/gpuweb/issues/425#issuecomment-993715281

**Comment by grovesNL** [comment]
I think https://github.com/gpuweb/gpuweb/issues/425#issuecomment-993715281 is deriving the alignment from the types of the fields though, so we wouldn't necessarily end up with 16-byte alignment for something like `SizeOf(struct Block {float x;};)`, right?

Should we go ahead with having WebGL validation to enforce alignment to `UNIFORM_BLOCK_DATA_SIZE` (queried from the program)?

**Comment by cwfitzgerald** [comment]
Uniform buffers require that all structs be rounded up to 16, so that would still be align 16. The only potential issue is if someone had a uniform buffer of a bare u32. This can be a downlevel feature forcing all assignments to 16.
