### ISSUE TITLE
WGPU RTX3060ti Mobile Driver Incompatibility

### ISSUE THREAD

**Issue by Tofaa2** [gfx-rs/wgpu#2090]
**Description**

Graphics component when using Bevy and its Default Plugins dont function. Works on my pc but laptop with rtx 3060tii mobile and i5-11300H frames and graphics become unresponcive and the application ran with wgpu crashes. Sorry if this isnt the place to sort this out i assumed it was

**Repro steps**
Ideally, a runnable example we can check out.

**Expected vs observed behavior**
Clearly describe what you get, and how it goes across your expectations.

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

Here is a bevy issue thread made by me a bit ago:

https://github.com/bevyengine/bevy/issues/2928

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
Windows 10 latest build

**Comment by teoxoy** [comment]
I'm closing the issue, @Tofaa2 please reopen it if you can provide us more info.
