### ISSUE TITLE
GLES Wayland surface resize not working 

### ISSUE THREAD

**Issue by PolyMeilex** [gfx-rs/wgpu#2094]
**Description**
When resizing the window on Wayland + GLES the surface never resizes. Judging by the log the surface configures are actually called with proper values, but the surface never updates.

**Repro steps**
- Run any example from the repo

**Expected vs observed behavior**
- The surface should reconfigure/resize when surface configure method is called

**Extra materials**

https://user-images.githubusercontent.com/20758186/137992632-46593121-0209-4ad8-b4b3-9b59b37e0d73.mp4

[log.log](https://github.com/gfx-rs/wgpu/files/7376743/log.log)

**Platform**
Linux Wayland + nouveau driver

**Comment by kaimast** [comment]
For the cube example the camera/viewport seems to get resized by the actual render texture does not.

There's also another issue here related to the scale factor: the viewport is initialized at half the size of the window. This bug existed a while ago and I thought it was fixed...

![image](https://user-images.githubusercontent.com/4525445/145693416-3ba3cdc9-6322-4b29-a092-8f29ed3a5f6f.png)
