### ISSUE TITLE
Crash under MacOS 10.12

### ISSUE THREAD

**Issue by francesco-cattoglio** [gfx-rs/wgpu#2095]
**Description**
A student of mine is experiencing the following bug: at application start the code crashes. If the program is run from the command line, the following line is returned:
```
2021-10-20 12:28:29.792 franzplot[10701:1634657] -[MTLIGAccelDevice readWriteTextureSupport]: unrecognized selector sent to instance 0x7fb36a836a00
fatal runtime error: Rust cannot catch foreign exceptions
Abort trap: 6
```

**Repro steps**
Unfortunately I do not have access to the machine used by my student, so I am unable to personally reproduce the bug. If somebody can get a hold of a similar machine I can provide the binary that crashes.

**Extra materials**
Here are all the details printed out by MacOS error dialog
[detailed_error_report.txt](https://github.com/gfx-rs/wgpu/files/7380502/detailed_error_report.txt)

**Platform**
Model: MacBookAir6,2, BootROM 117.0.0.0.0, 2 processors, Intel Core i5, 1,3 GHz, 4 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.21.171.134.1a2)
Bluetooth: Version 5.0.5f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0128F, 121,33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by kvark** [comment]
Ok, so this is fixed in latest. Are you going to update to latest, or do you need a patch for 0.7/0.8, which are ancient at this point?
