### ISSUE TITLE
Improve Rendy usage semantics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#210]
From https://github.com/gfx-rs/wgpu/issues/207#issuecomment-498647866 :
> I suggest implementing rendy::memory::MemoryUsage for BufferUsage to consider all set flags appropriately.

**Comment by kvark** [comment]
Documenting the API is indeed a separate task. This one is about internal details on how we communicate that API usage to Rendy.

**Comment by paulkernfeld** [comment]
Since v0.5 of wgpu moved off Rendy, should this issue now be closed?

**Comment by kvark** [comment]
Indeed!
