### ISSUE TITLE
Cannot copy depth24plus textures

### ISSUE THREAD

**Issue by magcius** [gfx-rs/wgpu#2122]
**Description**
Currently, there's a check for COPY_SRC / COPY_DST when trying to create a depth24plus texture: https://github.com/gfx-rs/wgpu/blob/41c595cfcf345136db314de8225144db8de74403/wgpu-core/src/device/mod.rs#L637-L648

This is out of date compared to the latest spec.

**Platform**
I'm testing on Firefox Nightly, version 95.0a1 (2021-10-27) (64-bit), on Windows 10.

**Comment by jinleili** [comment]
Verified on master branch of wgpu, this issue has been fixed.
