### ISSUE TITLE
Vulkan Mailbox presentmode does not limit framerate like FIFO, unlike DX12 Mailbox

### ISSUE THREAD

**Issue by PROMETHIA-27** [gfx-rs/wgpu#2128]
**Description**
When using mailbox presentmode on a vulkan adapter, framerate is not capped to refresh rate. Switching to FIFO caps the framerate, as does changing the adapter to DX12. 

**Repro steps**
Here is a gist with a program that demonstrates the issue with a spinning quad:
https://gist.github.com/PROMETHIA-27/f9a4b1cd46a6251659efcbbb05ff416d

Changing the instance backend to VULKAN and presentmode to Mailbox causes the quad to spin much faster. Leaving either as DX12 or FIFO prevents this behavior. 

**Expected vs observed behavior**
On both vulkan and DX12, mailbox and fifo presentmodes should behave visually identically.
Instead, on vulkan they behave differently as mailbox does not limit framerate.

**Platform**
Windows 10 Home version 20H2 Build 19042.1288
CPU: AMD Ryzen 9 5900HX with Radeon Graphics
(Because of High Performance flag I run the program on discrete GPU, not integrated)
GPU: NVIDIA RTX 3070

**Comment by cwfitzgerald** [comment]
This is expected, and is actually an artifact of that our current DX12 implementation doesn't support mailbox at all. Mailbox means that there is no tearing, but you can still render as fast as possible, the screen will just use the "most recent" frame when it comes time to present. Mailbox being unsupported means that it auto-falls through to FIFO on DX12, showing the frame limiting you're expecting.

**Comment by PROMETHIA-27** [comment]
Does that mean the DX12 implementation will support mailbox in the future, or is that a limitation of DX12?

**Comment by kvark** [comment]
An adapter does not *have to* support Mailbox. Current code - https://github.com/gfx-rs/wgpu/blob/c3d906856f11821ab75f7318089704c20922359d/wgpu-hal/src/dx12/adapter.rs#L376

Maybe in the future we'll find a way, but users should be ready to handle adapters without Mailbox.
Unfortunately, this isn't exposed directly to wgpu-rs, but it's fully present at wgpu-hal level. So we may need to provide some API for users to discover if Mailbox is available.

**Comment by cwfitzgerald** [comment]
A logical place for this to go is part of the DownlevelFeatures as one of the ones _not_ part of the webgpu compliance set, as we do with Anisotropic Filtering.

**Comment by kvark** [comment]
I don't think "downlevel" is the right place for this. "downlevel" is for things that are guaranteed by WebGPU but not the secondary APIs. In this case, WebGPU doesn't guarantee Mailbox, so it's not a downlevel capability. It's just a native-only capability, so we can add it on the side.

**Comment by cwfitzgerald** [comment]
This was sorted when presentation modes were reworked a while ago. Dx12 supports mailbox, fifo, and immediate.
