### ISSUE TITLE
Metal backend not working because of missing surface capabilities

### ISSUE THREAD

**Issue by sandydoo** [gfx-rs/wgpu#2135]
Hi, everyone!

**Description**
I'm seeing the following error coming from the surface validation function when running the examples on Metal:
```
thread 'main' panicked at 'Error in Surface::configure: requested usage is not supported', wgpu/src/backend/direct.rs:204:9
```

It looks like #1688 added `COPY_DST` as a default `TextureUse`, but the Metal adapter only exposes `COLOR_TARGET`.

https://github.com/Wumpf/wgpu/blob/a7613e7998b5a1701ff9aeeac7abf46986cd8776/wgpu-core/src/conv.rs#L64-L70
```rust
pub fn map_texture_usage(
    usage: wgt::TextureUsages,
    aspect: hal::FormatAspects,
) -> hal::TextureUses {
    // Enforce COPY_DST, otherwise we wouldn't be able to initialize the texture.
    let mut u = hal::TextureUses::COPY_DST;
```

https://github.com/Wumpf/wgpu/blob/a7613e7998b5a1701ff9aeeac7abf46986cd8776/wgpu-hal/src/metal/adapter.rs#L322
```rust
usage: crate::TextureUses::COLOR_TARGET, //TODO: expose more
```

**Repro steps**
The `hello-triangle` example is enough to reproduce this.

**Expected vs observed behavior**
Naturally, nothing can be rendered to screen because of the validation error.
Is adding `COPY_DST` to the metal adapter the right approach?

```rust
usage: crate::TextureUses::COPY_DST | crate::TextureUses::COLOR_TARGET,
```

Are other adapters affected by this?

**Extra materials**
<details>

<summary>Comparison of capabilities at runtime between `master` and `0.10.2`</summary>

```rust
// wgpu@0.10.2

// capabilities
SurfaceCapabilities { formats: [Bgra8Unorm, Bgra8UnormSrgb, Rgba16Float], swap_chain_sizes: 2..=3, current_extent: Some(Extent3d { width: 1600, height: 1200, depth_or_array_layers: 1 }), extents: Extent3d { width: 4, height: 4, depth_or_array_layers: 1 }..=Extent3d { width: 4096, height: 4096, depth_or_array_layers: 1 }, usage: COLOR_TARGET, present_modes: [Fifo, Immediate], composite_alpha_modes: [Opaque, PreMultiplied, PostMultiplied] }

// config
SurfaceConfiguration { usage: RENDER_ATTACHMENT, format: Bgra8UnormSrgb, width: 1600, height: 1200, present_mode: Mailbox }

// hal_config
SurfaceConfiguration { swap_chain_size: 3, present_mode: Mailbox, composite_alpha_mode: Opaque, format: Bgra8UnormSrgb, extent: Extent3d { width: 1600, height: 1200, depth_or_array_layers: 1 }, usage: COLOR_TARGET }


// wgpu@master

// capabilities
SurfaceCapabilities { formats: [Bgra8Unorm, Bgra8UnormSrgb, Rgba16Float], swap_chain_sizes: 2..=3, current_extent: Some(Extent3d { width: 1600, height: 1200, depth_or_array_layers: 1 }), extents: Extent3d { width: 4, height: 4, depth_or_array_layers: 1 }..=Extent3d { width: 4096, height: 4096, depth_or_array_layers: 1 }, usage: COLOR_TARGET, present_modes: [Fifo, Immediate], composite_alpha_modes: [Opaque, PreMultiplied, PostMultiplied] }

// config
SurfaceConfiguration { usage: RENDER_ATTACHMENT, format: Bgra8UnormSrgb, width: 1600, height: 1200, present_mode: Mailbox }

// hal_config
SurfaceConfiguration { swap_chain_size: 3, present_mode: Mailbox, composite_alpha_mode: Opaque, format: Bgra8UnormSrgb, extent: Extent3d { width: 1600, height: 1200, depth_or_array_layers: 1 }, usage: COPY_DST | COLOR_TARGET }
```

</details>

**Platform**
- wgpu@master
- MacOS 11.6
- Macbook Pro 13-inch late 2013, Integrated Intel Iris

**Comment by kvark** [comment]
@Wumpf this is an interesting one.
On one hand, it feels to me that adding COPY_DST inside `map_texture_usage` is a mistake. It should be added outside, by whatever is interested in supporting the copies.
However, this leaves the question of how we'd zero-initialize surface textures then. I believe for them clearing with a renderpass makes more sense. How feasible would it be to have the surface textures doing different logic for zero initialization?

**Comment by Wumpf** [comment]
Arguably we should always do surface clears over copy for zero init when we can anyways. Logistics for this are just a bit tricky, but now that we have everything in place it should be in reach
