### ISSUE TITLE
combined vertex buffer vertex len check seems incorrect

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#214]
If I draw:
```rust
        rpass.set_vertex_buffers(&[(&self.buf, 0)]);
        rpass.draw(0..(self.buf.len()) as u32, 0..1);
        rpass.set_vertex_buffers(&[(&self.strips_buf, 0)]);
        rpass.draw(0..(self.strips_buf.len()) as u32, 0..1);
```
every vertex is rendered correctly.

If i do:
```rust
        rpass.set_vertex_buffers(&[(&self.buf, 0), (&self.strips_buf, 0)]);
        rpass.draw(0..((self.buf.len() + self.strips_buf.len())) as u32, 0..1);
```
which afaics should be identical, I receive an assertion error:
```
thread 'main' panicked at 'Vertex out of range!', /home/m4b/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/803c607/wgpu-native/src/command/render.rs:338:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Is only the first (or last) vertex buffer size used in the count check?

**Comment by kvark** [comment]
> rpass.set_vertex_buffers(&[(&self.buf, 0), (&self.strips_buf, 0)]);

This is not identical. This command would bind "self.buf" as the first vertex buffer and "self.strips_buf" as the second. Since you are asking for `self.buf.len() + self.strips_buf.len()` afterwards, there is clearly not enough data, so the validation is correct in rejecting this.

Note: we need to add a parameter that specifies the start slot, see #215

**Comment by m4b** [comment]
I see; I don’t really understand why we’re given an array of buffers to draw if the lens of both are never relevant ? I guess I don’t understand the usecase then for two buffers. How can I ever draw both ?

Anyway seems I should just either keep what I have (although this flickers) or copy all the vertices into a new buffer and just use that with the combined len ?

**Comment by kvark** [comment]
The binding mode of vertex buffers/attributes have not changed for the past 20 years. Vertex inputs are loaded from N vertex buffers: some of the buffers may contain multiple interleaved (or not) attributes, some only single ones. These aren't "buffers to draw", these are just sources of input for your vertex shader.

Lens of all the input buffers **are** relevant, which is what triggers a validation error in your case.

What are you trying to do, exactly?

**Comment by m4b** [comment]
As I said, I want to draw both vertex buffers.

**Comment by kvark** [comment]
Sorry, I have to repeat this: nobody "draws" vertex buffers. They are just storages for vertex attributes, which are inputs to your vertex shader.

How do you create the render pipeline? What is the data you put into the buffers? What do you expect on screen?

**Comment by m4b** [comment]
You’re being pedantic now, but ok. I want to call the draw method that is provided by wgpu on `self.buf.len() + self.strips_buf.len()` vertices. I have two buffers that contain these vertices. The pipeline is constructed with triangle list. What appears on screen is a bunch of triangles.

If I call them as I provided in the first example, the triangles appear on screen (but they flicker, which is another issue but out of scope). If I use the second approach I get the assertion error.

If the first is how I draw two buffers with vertex attributes compatible with my pipeline, I will just do that, I guess, and open another issue about flickering.

**Comment by kvark** [comment]
Ok, so you have a bunch of vertices in one buffer, and another bunch in a different buffer. Vertex attributes have to be fetched sequentially, so you can't have have the vertices from both of the buffers used in the same draw call. Proper (and obvious) way is to do it like your first example.

It appears to me that the issue can be closed then. I will be happy to look at the flickering bug you are seeing, just need a way to reproduce it.

**Comment by seivan** [comment]
@m4b Just wanna point out a use case if instanced drawing.
Bind your vertices, and bind a buffer containing the vertex attributes. 

For a quad you'd have 4 (`TriangleStrip`, `Cw`, without index) in one buffer, and N in other buffer containing model data, and what not. 

You'd be better off shoving everything into one buffer and draw and keep a second buffer with the attribute that change often if you're worried about constantly writing a buffer.
