### ISSUE TITLE
hello-triangle resize behavior

### ISSUE THREAD

**Issue by prideout** [gfx-rs/wgpu#2144]
Resizing the window in `wgpu/examples/hello-triangle` works fine on my Windows NVIDIA machine but not on my M1 MacBook. It doesn't seem to refresh even though the `WindowEvent::Resized` arm is definitely getting hit in the event loop.  Screenshot attached after widening the window. (no error messages).

<img width="1485" alt="Screen Shot 2021-11-01 at 3 35 23 PM" src="https://user-images.githubusercontent.com/1288904/139750973-30931b4e-53bc-4b38-9a15-92f4964c21a7.png">

**Comment by kvark** [comment]
What about other examples like `cube`?

**Comment by prideout** [comment]
`cube` works great, there is no resize issue there.

**Comment by xiaopengli89** [comment]
This problem can be solved by calling `window.request redraw();` during the resize event.

**Comment by xiaopengli89** [comment]
The `cube` example uses `framework.rs`, which will redraw every 1/60 second.
