### ISSUE TITLE
hello-triangle panics on fullscreen mode (Vulkan)

### ISSUE THREAD

**Issue by timokoesters** [gfx-rs/wgpu#2155]
If I add this line to wgpu/examples/hello-triangle/main.rs:
```
     let window = winit::window::Window::new(&event_loop).unwrap();
+    window.set_fullscreen(Some(winit::window::Fullscreen::Borderless(None)));
     #[cfg(not(target_arch = "wasm32"))]
```
I get this error:
```
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', wgpu/src/backend/direct.rs:204:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This also happens in the exclusive fullscreen mode.

cc @kvark

**Comment by kvark** [comment]
Please provide detailed information about your platform.
I just tried this on Linux/Vulkan/Intel, and it works well as expected.

**Comment by timokoesters** [comment]
I can reproduce this bug on the wgpu master branch, wgpu v0.11 and v0.10
I'm on linux, here's my adapterinfo: `AdapterInfo { name: "NVIDIA GeForce GTX 1050 Ti", vendor: 4318, device: 7298, device_type: DiscreteGpu, backend: Vulkan }`

Do you need anything else?

**Comment by timokoesters** [comment]
On wgpu v0.9 I get a crash too, but it looks different:

```
thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', /home/timo/Development/rust/wgpu/wgpu-core/src/device/mod.rs:4556:29
```

**Comment by VarLad** [comment]
Same error for me
It looks like its an NVIDIA + Wayland issue? @timokoesters

**Comment by cwfitzgerald** [comment]
Closing as ot of scope.
