### ISSUE TITLE
WGSL texture_2d_array with 1 layer is not translated to an array texture for WebGL2 GLSL

### ISSUE THREAD

**Issue by superdump** [gfx-rs/wgpu#2161]
**Description**
Using a depth buffer texture_2d_array with 1 layer in WGSL works fine with Vulkan, Metal, etc. But with WebGL2 it is translated as a non-array texture and fails silently.

**Repro steps**
There is an example in https://github.com/gfx-rs/wgpu/issues/2138 that exhibits this issue. Please shout at me if you want me to test something!

**Expected vs observed behavior**
Expected: Array texture shadow map with 1 layer works as it does for native.
Observed: Silent failure.

**Platform**
Windows 10, wpgu master, WebGL2.

**Comment by kvark** [comment]
GLES backend guesses the type of the texture currently: it checks for n==1, and it checks for n % 6, both are crappy. There needs to be a proper solution instead of this guesswork, but I don't know what this is yet.

**Comment by teoxoy** [comment]
Related: https://github.com/gfx-rs/wgpu/issues/1614

**Comment by cwfitzgerald** [comment]
Closing in favor of #1614
