### ISSUE TITLE
Can't run example in browser on windows

### ISSUE THREAD

**Issue by trsh** [gfx-rs/wgpu#2169]
**Description**
Can't run example in browser on windows

**Repro steps**
run-wasm-example.sh cube

**Expected vs observed behavior**
I guess a link to localhost

**Extra materials**
![Untitled11111111](https://user-images.githubusercontent.com/3727523/140807259-6c0f305c-7223-41f8-8714-ac24d17d8e2f.png)

**Platform**
Windows 64x, GTX 750 Ti

**Comment by kvark** [comment]
Looks like you are using a different version of wasm-bindgen from the one wgpu was compiled with. Your log says "0.2.76", check this against your lockfile.

**Comment by trsh** [comment]
So how I fix it for web? In root dir lock file it's 0.2.78

**Comment by trsh** [comment]
Ok it seems to be the issue with WIKI https://github.com/gfx-rs/wgpu/wiki/Running-on-the-Web-with-WebGPU-and-WebGL . Because it says strictly install specific version and then points to 0.2.76 version.

**Comment by trsh** [comment]
I run a Python server and run into this:

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

**Comment by kvark** [comment]
Ok, the wiki page is unfortunately mentioning an older version. I see that the Cargo lock has `0.2.78` right now.
