### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#217]
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver, version 418
Backend: Vulkan

Repro: https://github.com/rukai/wgpu-rs/blob/memory_leak_repro/examples/repro/main.rs

Removing this line, makes the leak drastically better: https://github.com/rukai/wgpu-rs/blob/8c390eaf493a9803cc3ccef9e600ecc299474863/examples/repro/main.rs#L74

**Comment by kvark** [comment]
What backend are you using?

**Comment by rukai** [comment]
I have now edited it into the original post.

**Comment by rukai** [comment]
I ran valgrind massif like this: `valgrind --tool=massif --massif-out-file=massif.txt wgpu-rs/target/release/examples/repro`
I have attached the output file. [massif.txt](https://github.com/gfx-rs/wgpu/files/3269332/massif.txt)

It looks like its caused by `create_descriptor_pool`.

**Comment by kvark** [comment]
Thank you for investigation! We are indeed missing the freeing calls for descriptors. In order to make it happen, we'll need to add tracking of bind groups the same way we are tracking textures and buffers.

**Comment by rukai** [comment]
Mind if I take this on?
I'll start by adding a DescriptorSet variant to NativeResource and then go from there.

**Comment by kvark** [comment]
That would be great! Thank you!
