### ISSUE TITLE
TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES fails on DX12+AMD.

### ISSUE THREAD

**Issue by Elabajaba** [gfx-rs/wgpu#2185]
**Description**
Attempting to run a WGPU application that uses `wgpu::Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES` crashes on startup when run with DX12 on an AMD GPU.

**Repro steps**
https://github.com/Elabajaba/wgpu-adapter-formats
Alternatively, run bevy's pipelined-rendering branch with the WGPU_BACKEND env variable set to dx12 on an AMD GPU.

**Expected vs observed behavior**
Expected: It doesn't error and crash.
Observed: It crashes almost instantly when it reaches to `adapter.request_device`

**Extra materials**
`ERROR wgpu::backend::direct] Error in Adapter::request_device: unsupported features were requested: TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`

Querying for supported features using `adapter.features()` in DX12 returns:
```DEPTH_CLAMPING | TEXTURE_COMPRESSION_BC | TIMESTAMP_QUERY | MAPPABLE_PRIMARY_BUFFERS | MULTI_DRAW_INDIRECT | MULTI_DRAW_INDIRECT_COUNT | ADDRESS_MODE_CLAMP_TO_BORDER | POLYGON_MODE_LINE | POLYGON_MODE_POINT | CONSERVATIVE_RASTERIZATION | VERTEX_WRITABLE_STORAGE | CLEAR_COMMANDS```

**Platform**
Tested on both wgpu master, and wgpu 0.11.
Windows 11, AMD 6800XT with latest 21.11.2 driver.

**Comment by Elabajaba** [comment]
Note, after looking into this a bit more I found a number of features that don't appear to be supported on AMD+DX12, contrary to what the docs in wgpu-types claim.

Supported on vulkan, but not dx12 (ignoring vulkan only features):
```TEXTURE_BINDING_ARRAY
BUFFER_BINDING_ARRAY
SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING
UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING
PARTIALLY_BOUND_BINDING_ARRAY
UNSIZED_BINDING_ARRAY
PUSH_CONSTANTS
TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES
PIPELINE_STATISTICS_QUERY (unsure about this one. docs say DX12 works, but that it also only works on vulkan)
```

Supported on dx12, but not vulkan:
`DEPTH_CLIP_CONTROL` (not sure if this one even applies to vulkan?)

**Comment by kvark** [comment]
Looks like DX12 backend implements `texture_format_capabilities`, just forgets to expose the feature.

**Comment by stshine** [comment]
Same here on Windows 10 and NVIDIA Geforce GTX1650.

**Comment by kvark** [comment]
It's a good way to get a taste of contributing to wgpu!

**Comment by stshine** [comment]
I would like to have a try :)
Any hints on how to fix this?
