### ISSUE TITLE
C API for tagged union type unnecessarily verbose

### ISSUE THREAD

**Issue by porky11** [gfx-rs/wgpu#219]
A singe enum, which represents a tagged union, is exported to the C API.
You can find it [here](https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/binding_model.rs#L85) and it looks like this:

```rust
#[repr(C)]
#[derive(Debug)]
pub enum BindingResource {
    Buffer(BufferBinding),
    Sampler(SamplerId),
    TextureView(TextureViewId),
}
```

In the C API, the [expansion of this type here](https://github.com/gfx-rs/wgpu/blob/master/ffi/wgpu.h#L381) is overly complicated and looks like this:

```rust
typedef enum {
  WGPUBindingResource_Buffer,
  WGPUBindingResource_Sampler,
  WGPUBindingResource_TextureView,
} WGPUBindingResource_Tag;

typedef struct {
  WGPUBufferBinding _0;
} WGPUBindingResource_WGPUBuffer_Body;

typedef struct {
  WGPUSamplerId _0;
} WGPUBindingResource_WGPUSampler_Body;

typedef struct {
  WGPUTextureViewId _0;
} WGPUBindingResource_WGPUTextureView_Body;

typedef struct {
  WGPUBindingResource_Tag tag;
  union {
    WGPUBindingResource_WGPUBuffer_Body buffer;
    WGPUBindingResource_WGPUSampler_Body sampler;
    WGPUBindingResource_WGPUTextureView_Body texture_view;
  };
} WGPUBindingResource;
```

For every single field enum variant, a new struct is generated. This makes using the C API or writing wrappers for other languages unnecessarily complicated.

A small improvement, I'd suggest, looks like this:
```rust
typedef enum {
  WGPUBindingResource_Buffer,
  WGPUBindingResource_Sampler,
  WGPUBindingResource_TextureView,
} WGPUBindingResource_Tag;

typedef struct {
  WGPUBindingResource_Tag tag;
  union {
    WGPUBufferBinding buffer;
    WGPUSamplerId sampler;
    WGPUTextureViewId texture_view;
  };
} WGPUBindingResource;
```
But since the C API is generated by cbindgen, it would be preferable to be able to generate this code by cbindgen as well, so updating "wgpu.h" will be as simple as before.

The most straightforward way to achieve this is adding a simple rule, that single value enum variants will not be converted to new types, which only contain a single element, but instead just use that single element.

According to [this documentation](https://libraries.io/cargo/cbindgen) it looks like such a feature doesn't exist for cbindgen, so it may be best to wait until such a feature exists.

**Comment by kvark** [comment]
The C API is what https://github.com/webgpu-native/webgpu-headers define, as of the near future :)
