### ISSUE TITLE
Very slow to free identifiers on debug builds

### ISSUE THREAD

**Issue by jamesbeilby** [gfx-rs/wgpu#2193]
**Description**

Firstly, thanks for building an awesome library!

We had a Bevy game demo that successfully created a large number of textures (>100K). When trying to exit the application, it appeared to freeze for _several minutes_. This is due to a very slow assertion check in wgpu when freeing identifiers on debug builds.

I made a fix locally, which fixes this issue but with a small general performance penalty.

**Repro steps**

Add several thousand items to a Registry at once, and then drop them.
For example, add following lines to `Example::init` function in `examples/bunnymark/main.rs`:
```
let mut cache = Vec::<TextureView>::new();
for i in 1..100000 {
    cache.push( texture.create_view(&wgpu::TextureViewDescriptor::default()) );
}
```
On a debug build, 100K items cause the application to freeze for ~30 seconds when the cache is dropped (e.g. on application exit). This scales really badly, with O(N^2) complexity, so for 1M textures, it takes about an hour.

**Expected vs observed behavior**

Expected debug build to have poor performance, but still to have a real time quality. It should not be so prohibitively slow that the application is unusable (so it's not possible to debug other aspects).

**Extra materials**

The cause is this check in `hub.rs`:
```
        // avoid doing this check in release
        if cfg!(debug_assertions) {
            assert!(!self.free.contains(&index));
        }
```
This is painful because it has O(N^2) complexity - each drop compares to all items in the free list, then adds itself to the free list. So freeing 100,000 id's costs about 5,000,000,000 comparisons. Freeing 1 million id's costs half a trillion comparisons.

My local fix replaces the free Vec with a HashSet, so the assertion is O(1). This fixes the issue, but at a small increased cost for general use. In my view this is appropriate for a debug build, but I don't know much about wgpu and the use cases. Maybe it's better to remove this check altogether, or leave as-is?

**Platform**

wgpu 0.9.0, also present on master

**Comment by kvark** [comment]
Thank you for filing! I think we should just remove the assert. The hubs are hopefully getting deprecated anyway.
Also note, you are on wgpu-0.9, which is quite behind the latest 0.11. So if you want this on crates, we'd have to release 0.9, 0.10, and 0.11... yikes

**Comment by jamesbeilby** [comment]
Sure, raised PR. I don't think it's a showstopper for Bevy project and hopefully they will bump wgpu to latest at some point!
