### ISSUE TITLE
STATUS_ACCESS_VIOLATION on instance creation on Vulkan

### ISSUE THREAD

**Issue by Dreamykass** [gfx-rs/wgpu#2204]
**Description**
STATUS_ACCESS_VIOLATION on instance creation on Vulkan (DX12 runs fine, as expected)
I updated the drivers recently, and before that it did not crash like this.

**Repro steps**
get the code from <https://sotrh.github.io/learn-wgpu/beginner/tutorial6-uniforms>
`cd` to `tutorial6-uniforms`
change line 238 in `main.rs` to `let instance = wgpu:Instance::new(wgpu::Backends::VULKAN);` just to be sure
`cargo run --bin tutorial6-uniforms`

**Expected vs observed behavior**
Terminal output:
```
> cargo run --bin tutorial6-uniforms
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target\debug\tutorial6-uniforms.exe`
error: process didn't exit successfully: `target\debug\tutorial6-uniforms.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
>
```

**Extra materials**
Call stack as debugged via CLion:
![image](https://user-images.githubusercontent.com/65950243/142945569-48022cee-5bc4-47bb-b5e4-5fe624aab4c0.png)
Additional maybe useful info from the debugger:
![image](https://user-images.githubusercontent.com/65950243/142947041-3992f096-9cd7-4f6a-aef2-ce3ea09657f8.png)
The error thing is at this exact like I think:
![image](https://user-images.githubusercontent.com/65950243/142947197-86a4a30b-69ed-4064-8838-fa0e30bf799d.png)

**Platform**
wgpu: 0.11
nvidia drivers version: 496.76 (newest at the time of reporting)
vulkan sdk: 1.2.198.0 (also newest, freshly updated)
system: Windows 10, 10.0.19043
CPU: 17-9700
GPU: RTX 2080 Ti
GPU (integrated): Intel UHD Graphics 630
(I have one monitor connected to the RTX GPU, and one connected to the motherboard/CPU)
(I updated the drivers recently, and before that it did not crash like this.)

**Comment by Dreamykass** [comment]
Will try to downgrade/install older drivers.

**Comment by kvark** [comment]
Interesting crash! So it's trying to read a field at offset 0x20 of some struct that it has a nullptr for.
Seems pretty basic. Could you try `wgpu`'s own examples? Then perhaps `ash` examples?

**Comment by toastmod** [comment]
I can vouch this thread, getting the same thing for the same reason.

**Comment by Dreamykass** [comment]
`wgpu-info`:
```
>git clone https://github.com/gfx-rs/wgpu
...
>cd .\wgpu\
>cargo run
...
Compiling wgpu-info v0.11.0 (...\wgpu\wgpu-info)
    Finished dev [unoptimized + debuginfo] target(s) in 39.45s
     Running `target\debug\wgpu-info.exe`
error: process didn't exit successfully: `target\debug\wgpu-info.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
![image](https://user-images.githubusercontent.com/65950243/142992555-ec9ee223-08f8-44ab-bdd3-17b61baa9879.png)

`ash` triangle example:
![image](https://user-images.githubusercontent.com/65950243/142997994-38d4f589-6aed-418c-aca3-39f61a5e866b.png)


So, same thing on both.

**Comment by kvark** [comment]
Ok, what about native tools, like `vulkan-info` and `vkcube`?

**Comment by ImUrX** [comment]
It seems its Overwolf in my side
![image](https://i.imgur.com/tAk1Ysl.png)

**Comment by kvark** [comment]
Ok, so TL;DR: overwolf installs a Vulkan layer, enabled by default in the system, which crashes.

**Comment by Dreamykass** [comment]
Yes, that was it. I've not used this app in *years*, and I'd probably never find this out myself.

Amazing, thank you, @ ImUrX.
