### ISSUE TITLE
Descriptor pools are destroyed while in use.

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#221]
I just started hitting this when using brawllib to render in realtime instead of generating a gif: 
```[2019-06-11T08:35:41Z ERROR gfx_backend_vulkan] 
VALIDATION [VUID-vkDestroyDescriptorPool-descriptorPool-00303 (0)] : Cannot call vkDestroyDescriptorPool on DescriptorPool 0x166e94 that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to descriptorPool (via any allocated descriptor sets) must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyDescriptorPool-descriptorPool-00303)
```

This is clearly caused by https://github.com/gfx-rs/wgpu/pull/220
I'll look into it.

**Comment by kvark** [comment]
It's not the first, and unlikely the last issue about resource tracking. We need some sort of internal debugging infrastructure to identify and fix these issues quickly. I.e. you can hard-code a resource ID somewhere, and every refcount change would print the spot to the console. This is what WebRender chasing infrastructure does.

**Comment by rukai** [comment]
`Buffer` `RefCount`s are given to the `RenderPass` in `wgpu_render_pass_set_vertex_buffers` to ensure they stay alive. I tried to do the same for `DescriptorSet`s in `wgpu_render_pass_set_bind_group` https://github.com/rukai/wgpu/commit/f0eb6519b3780793f230744229f5ec3a0cfea91b

But it did not resolve the issue.

**Comment by kvark** [comment]
The change is correct. Are you using any compute? The same needs to happen for `ComputePass`.
