### ISSUE TITLE
DX12 backend crashes silently when making the surface COPY_DST

### ISSUE THREAD

**Issue by Dimev** [gfx-rs/wgpu#2234]
**Description**
When using the DX12 backend, and marking the surface texture as COPY_DST only, wgpu will cause crash without a stack trace in debug, and with
```
thread 'Render thread' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
      note: label = `Render Texture`
    parent device is lost
```
in release mode (in my case, where I have the renderer on a seperate thread)

**Repro steps**
Run this code:
```rust
use wgpu; // = 0.11
use winit; // = 0.25
use pollster::block_on; // = 0.2

fn main() {

	let event_loop = winit::event_loop::EventLoop::new();

	let window = winit::window::Window::new(&event_loop).unwrap();
    
	let instance = wgpu::Instance::new(wgpu::Backends::DX12);

	let surface = unsafe {instance.create_surface(&window) };

	let adapter = block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
		compatible_surface: Some(&surface),
		power_preference: wgpu::PowerPreference::HighPerformance,
		..Default::default()
	}))
	.expect("Couldn't create adapter");

	let (device, queue) = block_on(adapter.request_device(
		&wgpu::DeviceDescriptor {
			label: None,
			features: wgpu::Features::empty(),
			limits: wgpu::Limits::default(),
		},
		None,
	))
	.expect("Could not create device and queue");

	let config = wgpu::SurfaceConfiguration {
		usage: wgpu::TextureUsages::COPY_DST, 
		format: surface.get_preferred_format(&adapter).unwrap(),
		width: window.inner_size().width,
		height: window.inner_size().height,
		present_mode: wgpu::PresentMode::Fifo,
	};

	surface.configure(&device, &config);

	let frame = surface
            .get_current_texture()
            .expect("Failed to get texture");

	let mut encoder = device
		.create_command_encoder(&wgpu::CommandEncoderDescriptor {
			label: Some("Render Encoder"),
		});

	let texture = device.create_texture(&wgpu::TextureDescriptor {
		size: wgpu::Extent3d {
			width: window.inner_size().width,
			height: window.inner_size().height,
			depth_or_array_layers: 1,
		},
		mip_level_count: 1,
		sample_count: 1,
		dimension: wgpu::TextureDimension::D2,
		format: wgpu::TextureFormat::Rgba32Float,
		usage: wgpu::TextureUsages::all(),
		label: Some("Render Texture"),
	});

	let source = wgpu::ImageCopyTexture {
		texture: &texture,
		mip_level: 0,
		origin: wgpu::Origin3d { x: 0, y: 0, z: 0 },
		aspect: wgpu::TextureAspect::All,
	};

	let destination = wgpu::ImageCopyTexture {
		texture: &frame.texture,
		mip_level: 0,
		origin: wgpu::Origin3d { x: 0, y: 0, z: 0 },
		aspect: wgpu::TextureAspect::All,
	};

	// copy the texture over
	encoder.copy_texture_to_texture(
		source,
		destination,
		wgpu::Extent3d {
			width: window.inner_size().width,
			height: window.inner_size().height,
			depth_or_array_layers: 1,
		},
	);

	let commands = encoder.finish();
    queue.submit(std::iter::once(commands));
}
```

**Expected vs observed behavior**
Expected: With Vulkan, it doesn't crash and properly copies the texture the the surface
Observer: With DX12, it crashes without a stack trace (debug) or an incorrect error (in release)

**Platform**
windows 10 Build 19043 
wgpu 0.11.0, 
cargo 1.56.0
GPU: NVidia GTX 1660
Driver: Geforce game ready driver, version 496.76

Note: wgpu only sees the DX12 and Vulkan backends on my computer

**Comment by UpsettingBoy** [comment]
Weirdly enough, I only get your error when executing this example in dev profile (release profile executes fine).
The error I obtain using a logger is:
`[ERROR wgpu_hal::dx12::instance] ID3D12CommandList::CopyTextureRegion: The source and destination resource formats are incompatible. The source format is R32G32B32A32_TYPELESS and the destination format is B8G8R8A8_TYPELESS. Some non-obvious formats are considered equivalent: BC[1|4] ~= R16G16B16A16|R32G32, BC[2|3|5|6|7] ~= R32G32B32A32, and R9G9B9E5_SHAREDEXP ~= R32. [ RESOURCE_MANIPULATION ERROR #874: COPYTEXTUREREGION_FORMATMISMATCH]`

**Comment by UpsettingBoy** [comment]
Changing `texture` format to `surface.get_preferred_format(&adapter).unwrap()` and its usage to only `wgpu::TextureUsages::COPY_SRC` solved the problem for me.

Keep in mind that, per `copy_texture_to_texture` documentation, source and destination formats must be the same.

**Comment by Dimev** [comment]
Ah that makes sense. How would I do logging?

**Comment by UpsettingBoy** [comment]
First you have to make sure to have installed the validation layers in your system. Then use some logger crate like env_logger.

**Comment by Dimev** [comment]
I read through the docs again. The reason I'm copying a texture to the output surface is because I want all my textures I render to to be Rgba32Float, and be their own texture for ease of use. Looking at the docs, the surface texture only really supports being used as a render attachment, and Bgra8 textures. 

Is there an easy way to then copy a texture to the window output, besides drawing a full-screen triangle and rendering via that way, or am I thinking about this the wrong way?

**Comment by Dimev** [comment]
Yup with the logger I now also get 
```
[2021-12-04T13:10:20Z ERROR wgpu_hal::dx12::instance] ID3D12CommandList::CopyTextureRegion: The source and destination resource formats are incompatible. The source format is R32G32B32A32_TYPELESS and the destination format 
is B8G8R8A8_TYPELESS. Some non-obvious formats are considered equivalent: BC[1|4] ~= R16G16B16A16|R32G32, BC[2|3|5|6|7] ~= R32G32B32A32, and R9G9B9E5_SHAREDEXP ~= R32. [ RESOURCE_MANIPULATION ERROR #874: COPYTEXTUREREGION_FORMATMISMATCH]
```

**Comment by CatCode79** [comment]
However it should be noted that in the documentation the use of the [SurfaceConfiguration](https://wgpu.rs/doc/wgpu/struct.SurfaceConfiguration.html) can only be used as RENDER_ATTACHMENT.

Taking a quick look at the WebGpu specs I can't figure out if it's an official limitation or just a lack of implementation.

Dawn has a similar limitation, with [specific error message](https://dawn.googlesource.com/dawn/+/refs/heads/main/src/dawn_native/SwapChain.cpp#83) (which in wgpu seems to be missing).

If by chance it is not a limitation dictated by the WebGpu specifications it still seems that there may be hope to correct the thing.

**Comment by Dimev** [comment]
Ah thanks. I'll have to copy to it by rendering to it then

**Comment by UpsettingBoy** [comment]
> However it should be noted that in the documentation the use of the SurfaceConfiguration can only be used as RENDER_ATTACHMENT.
> Taking a quick look at the WebGpu specs I can't figure out if it's an official limitation or just a lack of implementation.

@kvark should `usage` field of `SurfaceConfiguration` be removed then or it is inherited from the spec?

**Comment by kvark** [comment]
We need to support more than just RENDER_ATTACHMENT usages. At the very least, we need to support COPY_SRC and COPY_DST. As for shader binding, I think these should be optional. The exact mechanism of exposing these ones is to be figured out. For now, let's focus on fixing COPY_XX usages.

**Comment by kvark** [comment]
This issue isn't about COPY_DST, really. With #2248 we have copy texture validation, and it properly errors.
Copying the same format works fine on the swapchain. So I'm closing this.
