### ISSUE TITLE
Conservative-raster Intel HSW GT2 thread panick  Adapter supp

### ISSUE THREAD

**Issue by plum** [gfx-rs/wgpu#2239]
**Description**

**Repro steps**
Ideally, a runnable example we can check out.

**Expected vs observed behavior**
Clearly describe what you get, and how it goes across your expectations.

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

**Comment by kvark** [comment]
Please feel out the issue template, e.g. provide the panic message and call stack, your HW configuration, etc

**Comment by plum** [comment]
I've closed the issue because meanwhile I have solved it. 
It was due to the defualt i915 driver included with linux kernal (arch distro) being insufficient, it seems. The 'vulkan-intel' package, i.e. Intel's vulkan mesa driver had to be installed on top.

Thanks,
John
