### ISSUE TITLE
Run through Vulkan sync validation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2243]
It's a new thing that needs to be explicitly enabled - https://www.khronos.org/blog/a-guide-to-vulkan-synchronization-validation. Let's see if anything shows up on our examples or user code.

**Comment by kvark** [comment]
Found one:
> [2021-12-02T15:58:27Z ERROR wgpu_hal::vulkan::instance] VALIDATION [SYNC-HAZARD-WRITE_AFTER_WRITE (0xfdf9f5e1)]
        Validation Error: [ SYNC-HAZARD-WRITE_AFTER_WRITE ] Object 0: handle = 0x55ad6d7f9b20, name = Uniform Buffer, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xfdf9f5e1 | vkCmdCopyBuffer: Hazard WRITE_AFTER_WRITE for dstBuffer VkBuffer 0x55ad6d7f9b20[Uniform Buffer], region 0. Access info (usage: SYNC_COPY_TRANSFER_WRITE, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: 0, command: vkCmdCopyBuffer, seq_no: 13, reset_no: 1).

Looks like we *do* need to sync writes after all. It's strange because D3D doesn't need that.

**Comment by kvark** [comment]
Here is another one (from `water`):
> [2021-12-02T16:01:47Z ERROR wgpu_hal::vulkan::instance] VALIDATION [SYNC-HAZARD-WRITE_AFTER_READ (0x4b3455b4)]
        Validation Error: [ SYNC-HAZARD-WRITE_AFTER_READ ] Object 0: handle = 0x561e46c4d3c0, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x4b3455b4 | vkCmdEndRenderPass: Hazard WRITE_AFTER_READ in subpass 0 for attachment 1 depth aspect during store with storeOp VK_ATTACHMENT_STORE_OP_STORE. Access info (usage: SYNC_LATE_FRAGMENT_TESTS_DEPTH_STENCIL_ATTACHMENT_WRITE, prior_usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, read_barriers: VK_PIPELINE_STAGE_2_NONE_KHR, command: vkCmdDraw, seq_no: 2, reset_no: 1)

This is https://github.com/KhronosGroup/Vulkan-Docs/issues/1700 and https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2349

**Comment by cwfitzgerald** [comment]
I think we've covered this one
