### ISSUE TITLE
Weird artifacts being drawn on specific hardware

### ISSUE THREAD

**Issue by BrunoWallner** [gfx-rs/wgpu#2254]
**Description**
[project-repo](https://github.com/BrunoWallner/crav)
I draw basic square shapes with the help of [learn-wgpu](https://github.com/sotrh/learn-wgpu).
I basically just copy pasted everything, except the mesh generation (`src/backends/wgpu/mesh.rs`) and changed the datatype of how the indices are stored from `u16` to `u32`.

On my laptop (specs below) everything works fine running off of both GPU's, but both on my and my brothers PC weird artifacts are being drawn and the program crashes.

**Repro steps**
```sh
mkdir issue 
cd issue

# project repo
git clone https://github.com/BrunoWallner/crav

# dependency of crav
git clone https://github.com/BrunoWallner/audioviz 

cd crav

# '-b wgpu' to use wgpu backend instead of terminal
# '--debug-white-noise' to skip audio capturing and use white-noise
cargo r --release -- -b wgpu --debug-white-noise
```

**Expected vs observed behavior**
Normally it should look like this (running in terminal backend):
![wgpu_issue_working](https://user-images.githubusercontent.com/78647562/144713609-7525b89f-1f48-4a34-908c-7b213e12a045.png)

But on my and my brothers PC it looks like this:
![wgpu_issue](https://user-images.githubusercontent.com/78647562/144713642-9424cfeb-b814-47ec-9ff0-ac2d234910ce.png)

**Platform**
Laptop:
* OS: `Arch Linux`
* Kernel: `5.15.4-zen1-1-zen`
* DE: `GNOME 41.1`
* CPU: `Intel i7-6820HQ`
* GPU: `NVIDIA Quadro M2000M`, `Intel HD Graphics 530`
* XDG_SESSION_TYPE: `wayland`

My PC:
* OS: `Arch Linux`
* Kernel `5.15.5-arch1-1`
* DE: `GNOME 41.1`
* CPU: `AMD Ryzen 5 1400`
* GPU : `NVIDIA GeForce GTX 1070`
* GPU driver version: `495.44`
* XDG_SESSION_TYPE: `x11`

Brothers PC:
* OS: `Windows 11`
* CPU: `AMD Ryzen 5 5600X`
* GPU: `NVIDIA GeForce RTX 3070`

**Notes**
I already updated from wgpu 0.10.0 to 0.11.0 bit it does not fix the issue.

I dualboot Linux and Windows 11, but it does not work on either of them, so I think it should definitely be some kind of hardware issue introduced by my weird code.

**Comment by kvark** [comment]
These kind of rendering differences are not acceptable for `wgpu`. If it renders differently, while you are using fully safe code - that's our bug! Thank you for filing it:)

**Comment by kvark** [comment]
I can run this on Linux with the expected result.
However, on Windows the code doesn't even build properly. Working around the errors gets me running but then hitting `StreamConfigNotSupported`. So I'm unable to reproduce the Windows/Vulkan/AMD setup because of this.

**Comment by BrunoWallner** [comment]
I fixed it not being able to be built on Windows and with the `--debug-white-noise` argument the `StreamConfigNotSupported` panic should not occur.

**Comment by cwfitzgerald** [comment]
Check to see if your renderpass rendering to the surface output has `store: true`. I had very similar artifacting when store was accidentally set to false. We will one day clear this, but we don't right now.

**Comment by BrunoWallner** [comment]
Thank you. Setting `store` on the renderpass ops to `true` fixed the issue.

previous not working code:
```rs
let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
    label: Some("Render Pass"),
    color_attachments: &[
        wgpu::RenderPassColorAttachment {
            view: &view,
            resolve_target: None,
            ops: wgpu::Operations {
                load: wgpu::LoadOp::Clear(
                    if self.config.wgpu.transparent {    
                        wgpu::Color::TRANSPARENT
                    } else {
                        wgpu::Color::BLACK
                    }
                ),
                store: false, /* issue */
            }
        }
    ],
    depth_stencil_attachment: None,
});
```

working code:
```rs
let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
    label: Some("Render Pass"),
    color_attachments: &[
        wgpu::RenderPassColorAttachment {
            view: &view,
            resolve_target: None,
            ops: wgpu::Operations {
                load: wgpu::LoadOp::Clear(
                    if self.config.wgpu.transparent {    
                        wgpu::Color::TRANSPARENT
                    } else {
                        wgpu::Color::BLACK
                    }
                ),
                store: true,
            }
        }
    ],
    depth_stencil_attachment: None,
});
```

**Comment by kvark** [comment]
To clarify, it's a bug in `wgpu`, or rather a thing we still need to implement. `store: false` shouldn't lead to diverging behaviors on platforms. Filed #2261 to follow-up.
