### ISSUE TITLE
Angle support on Apple platforms

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2259]
This is not very useful given the good state our Metal backend is in. But it would be interesting nonetheless, to help with bugs, to allow people develop GLES backend on macs, and even compare performance to some extent.

#2257 brings in some of that, but we can't pass correct window handle to Angle. It expects `CALayer`, but we only have `NSView` from `RawWindowHandle` - https://github.com/rust-windowing/raw-window-handle/issues/14

We can do the same thing we do on Metal backend - asking for `CALayer` and even creating it if needed.

**Comment by jinleili** [comment]
Preparing to compile angle to iOS, found that [ANGLE](https://github.com/google/angle) does not have plans to support GLES on iOS.
<img width="787" alt="截屏2022-02-11 17 42 34" src="https://user-images.githubusercontent.com/1001342/153570919-7f64fddf-d456-459e-b6a0-957eb1386bcd.png">

**Comment by cwfitzgerald** [comment]
There's very little reason to follow through on this, so I'm going to close.

**Comment by teoxoy** [comment]
This was actually added by https://github.com/gfx-rs/wgpu/pull/2461. Not for iOS though.
