### ISSUE TITLE
Failed to get `deno_console` as a dependency of package `cts_runner`

### ISSUE THREAD

**Issue by CCCCC7** [gfx-rs/wgpu#2260]
**Description**
I perform cts test and the test fails.

**Repro steps**
I perform these set of commands to run CTS:
    **These commands pass no issues** [
        git clone https://github.com/gpuweb/cts.git,
        cd cts,
        git checkout $(cat ../cts_runner/revision.txt),
    ]
    **Then I try to run the the set of tests via and receive an error** [
        cargo run --manifest-path ../cts_runner/Cargo.toml --frozen -- ./tools/run_deno --verbose "<test string>",
    ] 
**ERROR**: <error: failed to get `deno_console` as a dependency of package `cts_runner v0.1.0 (D:\wgpu-master\cts_runner)`

Caused by:
  failed to load source for dependency `deno_console`

Caused by:
  Unable to update https://github.com/denoland/deno?rev=ca75752e5a9499a0a997809f02b18c2ba1ecd58d

Caused by:
  failed to fetch into: C:\Users\<myname>\.cargo\git\db\deno-22855de1c03c9128

Caused by:
  attempting to update a git repository, but --frozen was specified>

**Expected vs observed behavior**
I simply get a failed to load dependency when there should be no issue loading the dependency.

**Extra materials**
https://i.imgur.com/11xyh3C.png

**Platform**
Windows 11, latest version of rust stable.

**Comment by kvark** [comment]
Why are you specifying `--frozen`?
Note that we have a CI job that builds and runs the tests, albeit we aren't auto-triggering it on all PRs. It's manually triggered.
https://github.com/gfx-rs/wgpu/blob/master/.github/workflows/cts.yml

**Comment by CCCCC7** [comment]
because thats what it says on the front page of wgpu to do... Can you clarify since I am really new to rust what the flag --frozen actually does?

**Comment by kvark** [comment]
Oh, indeed! I fixed the README now.
"--frozen" requires all of the dependencies to be present in your cargo cache.
