### ISSUE TITLE
ubuntu 20.04 server: Buffer::map_async never resolves when using Maintain::Poll

### ISSUE THREAD

**Issue by ecton** [gfx-rs/wgpu#2266]
**Description**

My kludgey-engine Kludgine supports rendering a frame offscreen, and based on the comment in the capture example, I was attempting to make my async code behave properly by not blocking and insteading using Poll in a loop. This worked for many wgpu versions, but stopped working under Github Actions CI when I updated to wgpu 0.11.1.

My fix was to switch to using the blocking version of polling: https://github.com/khonsulabs/kludgine/commit/fc71dda5c9240dc711bddc4f1cce745fb29315a9#diff-ec27a183b0ec358cceb9156a88bb5b947ecfaa81dd8a9585f4ef817dfe2c366aR142-R154

The old code's tracing output shows it getting to submitting the mapping request, but never resolves:

```sh
2021-12-07T22:49:24.582833Z DEBUG wgpu_core::device: Buffer (2, 1, Vulkan) map state -> Waiting    
2021-12-07T22:49:24.582898Z DEBUG wgpu_core::device::life: Buffer Valid((3, 1, Vulkan)) is detached    
2021-12-07T22:49:24.582927Z DEBUG wgpu_core::device::life: Buffer Valid((4, 1, Vulkan)) is detached    
2021-12-07T22:49:24.582953Z TRACE wgpu_core::device::life: Mapping of Valid((2, 1, Vulkan)) at submission 1 gets assigned to active Some(0)    
```

Through debugging, I can confirm that the device poll loop is indeed running continuously while waiting for the map_async future to resolve.

**Repro steps**

By replacing device.poll in create_png in the capture example with this:

```rust
let done = Arc::new(AtomicBool::default());
let thread_done = done.clone();
std::thread::spawn(move || {
    while !thread_done.load(Ordering::SeqCst) {
        device.poll(wgpu::Maintain::Poll);
    }
});

// ...

if let Ok(()) = buffer_future.await {
    done.store(true, Ordering::SeqCst);
```

This replicates my setup without introducing any oddities in the potential for an async runtime to be causing weirdness. When I installed ubuntu 20.04 server fresh, added `build-essential` and the [ppa and dependencies from this repo's github action](https://github.com/gfx-rs/wgpu/blob/master/.github/workflows/ci.yml#L143-L146), the example freezes when run with `cargo run --example capture`.

Of note, while I observed this change apparently between 0.11.0 and 0.11.1, I cannot get the above change to work in my headless setup in the example on what I believe was the released commit of 0.11.0. In either event, I believe these changes are simpler than what I originally had in my engine, and they show the primary issue: `Maintain::Poll` isn't enough to resolve `map_async` in the headless environment, but `Maintain::Wait` does.

**Comment by kvark** [comment]
Unable to reproduce on latest.
Here is the code - https://github.com/kvark/wgpu/commit/2284d859b4d8ad91447139408d92bd584f8aafac
Runs just fine on Linux/Intel.

**Comment by ecton** [comment]
I can confirm that it runs fine in that branch on my machine as well.

**Comment by ecton** [comment]
@kvark You need to remove [the Poll::Wait line](https://github.com/kvark/wgpu/commit/2284d859b4d8ad91447139408d92bd584f8aafac#diff-2e528c946f81edc4e122d1b007e57783f4d09f9035b84001b1e565ffe2eb9428R134). After removing that line, I still reproduce the issue.

I am on AMD, however.

**Comment by kvark** [comment]
Removed the wait in https://github.com/kvark/wgpu/commit/3e052855cfa9a0fde6943044c46d1ced57a56c9c, still unable to repro on Intel/Linux.

**Comment by ecton** [comment]
Did you try submitting that branch to Github Actions to run that example? That's how I originally encountered this issue -- it only happens when I run inside of a virtual machine in a headless/gpu-less environment. My same machine outside of that virtual machine doesn't exhibit the behavior.

Here's the log of me running from your branch:

```sh
ecton@ubuntu:~/wgpu$ git status
HEAD detached at kvark/wait-test
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	red.png

nothing added to commit but untracked files present (use "git add" to track)
ecton@ubuntu:~/wgpu$ time cargo run --example capture
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/capture`
[2021-12-09T03:55:30Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3003: xcb_connect failed
[2021-12-09T03:55:30Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3003: xcb_connect failed
[2021-12-09T03:55:30Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3003: xcb_connect failed
[2021-12-09T03:55:30Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3001: eglInitialize
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
^C

real	0m7.055s
user	0m7.013s
sys	0m0.040s
ecton@ubuntu:~/wgpu$ cat /proc/cpuinfo | grep "model name"
model name	: AMD EPYC-Rome Processor
model name	: AMD EPYC-Rome Processor
```

I killed it after waiting for longer than it should take -- the example normally is too quick to be killed. My actual physical processor is an AMD Ryzen 7 3800X, and I've given the virtual machine two virtual CPUs.

**Comment by kvark** [comment]
damn, debugging it on CI VM doesn't sound like fun

**Comment by ecton** [comment]
I'm not sure if you can reproduce it with a local VM running Ubuntu or not -- but I don't disagree, it wasn't fun even to debug what I figured out -- I can't imagine how it's going to be tracking it down further!

I haven't been able to figure out how to force using the software renderer instead of my graphics card without using the VM abstraction. Does anyone have any ideas of ways to restrict access to the GPU in Linux with some sort of sandboxing instead -- that might be easier to debug?

I also don't know if it's OS-specific -- My host OS is Arch (Manjaro), but the guest OS matches what I use on CI: ubuntu. I can try setting up another guest OS, but it may be a few days before I have time to really dig in.

This particular issue is not blocking me in any way, so it's not high priority -- but I'd love to help track it down.

**Comment by ecton** [comment]
> but it may be a few days before I have time to really dig in.

My brain wouldn't let it go. I'm unable to reproduce it in an arch VM on the same hardware. There are, I'm sure, countless differences between those OSes -- not sure where to start narrowing down the search.

**Comment by kvark** [comment]
> I haven't been able to figure out how to force using the software renderer instead of my graphics card without using the VM abstraction.

https://github.com/gfx-rs/wgpu/blob/1446b5274ffdf7c470685b45e1de5532bb912332/wgpu-types/src/lib.rs#L136

**Comment by cwfitzgerald** [comment]
Closing as stale.
