### ISSUE TITLE
Call to Surface::get_current_texture() seems to delay by one frame

### ISSUE THREAD

**Issue by chad-russell** [gfx-rs/wgpu#2269]
I'm trying to use wgpu and winit to have a graphical element in my app follow the mouse cursor. If I naively do the most straightforward thing of just updating a mouse coordinate variable in the `MouseInput` event from winit, and then update the buffers and issue a draw call inside the `RedrawRequested(_)` event, I run into a small issue:

The line ```let frame = surface.get_current_texture().expect("Failed to acquire next swap chain texture");``` consistently takes nearly exactly 16ms, meaning that I'm drawing graphics for where the mouse was one frame ago so it seems laggy.

Using a 2019 MacBook Pro, OS is Monterey 12.0.1

I think this must be something with how wgpu interacts with macOS specifically, because when compiling the same application for the web via wasm I do *not* see this issue. I've also tried to rule out the idea that it's just some bone-headed programming error on my part by compiling the examples in the iced gui repository. They actually have the same behavior - laggy on macOS, but super snappy on the web.

Any help is greatly appreciated, I can also make a minimal example if that would be helpful.

**Comment by cart** [comment]
I'm seeing this behavior on my Macbook as well, both on linux and on macos. When running our [3d_scene_pipelined example](https://github.com/bevyengine/bevy/main/examples/3d/3d_scene_pipelined.rs) with vsync disabled and all lights removed on my linux / vulkan desktop machine (nvidia 1070 with proprietary drivers) `get_current_texture()` takes ~0.005-0.014 milliseconds. On my macbook on macos (with an Nvidia 750m) I'm getting ~1-15 milliseconds  (with it generally alternating between ~1 ms and ~10 ms every other frame). On that same macbook running linux + vulkan (and nvidia proprietary drivers) I get ~10-14 ms every frame. Given that we're only drawing 5 simple unlit / unshadowed / untextured meshes, that seems very high. Seems like a contributor to this issue: https://github.com/bevyengine/bevy/issues/3052 given that `get_current_texture` dwarfs all other contributors to frame time in `3d_scene_pipelined`.

**Comment by cart** [comment]
Here is the branch with the modified `3d_scene_pipelined` example and a simple `get_current_texture` duration measurement printed to the terminal: https://github.com/cart/bevy/tree/weird-wait

**Comment by kvark** [comment]
`get_current_frame` is meant to block on CPU until a frame of the swapchain can be retired. For FIFO this is the oldest frame, for Mailbox this is any frame.

> The line let frame = surface.get_current_texture().expect("Failed to acquire next swap chain texture"); consistently takes nearly exactly 16ms, meaning that I'm drawing graphics for where the mouse was one frame ago so it seems laggy.

This would be expected with FIFO mode (aka V-sync) if you don't have a lot of CPU work, since your CPU is just waiting for GPU and has nothing else to do.

If you want to get up-to-date input, perhaps you could experiment with the event loop processing in the following way:
  - at some point, get the current frame and block
  - then process all of the events in the queue, basically until you get the `MainEventsCleared`
  - then start working on a frame given the fresh input

**Comment by cart** [comment]
Yeah it does make sense that it would block when vsync is enabled. But without vsync shouldn't there always be a frame available? All of the numbers I reported were with vsync completely disabled.

**Comment by chad-russell** [comment]
Ah, so this seems to help a lot actually! It seems MacOS laptops have vsync permanently on so I'm not sure how to test that on my current setup.

I moved the creation of the frame from inside the `MainEventsCleared` handler (i.e. just before the `present()` call) to the top of the run loop in winit. I also keep it inside of an `Option`, so that way I can check every iteration of the run loop if I have a valid frame or not. When it's time to present, I simply `.take()` the option and then it gets repopulated in the next iteration through the run loop. This along with adding in a manual timer to make sure at least 15ms have passed before attempting to render a new frame have completely fixed the issue for me.

I am still a bit confused as to why this doesn't seem to be needed on the web target, I guess probably something to do with how winit processes the event loop. Perhaps it sends the `MainEventsCleared` exactly in sync with the browser's `requestAnimationFrame` api so there is always a new frame ready.

**Comment by cart** [comment]
Out of curiosity, does adding a manual "wait" actually reduce frame time, or does it just move frame time from `get_current_texture()` to the "wait" you added?

**Comment by chad-russell** [comment]
It appears to just move it around - I get 16.67ms average wait time either way. But if I remove the "wait" it appears quite stuttery, and if I go quickly I'm able to completely get my mouse outside of the box I'm drawing.

Here's a minimal example with some variables to tweak at the top: https://github.com/chad-russell/wgpu-frame-jank-demo/tree/master

**Comment by cwfitzgerald** [comment]
This is an issue of frame pacing, something that can be more thoroughly solved by #2869
