### ISSUE TITLE
Vulkan validation error after update

### ISSUE THREAD

**Issue by UpsettingBoy** [gfx-rs/wgpu#2270]
**Description**
After updating to latest master from v0.11.1, I now get a Vulkan validation error. I have not detected any problem caused by this error, but I still think is interesting to check why it happens (and if it only happens to me 😓).

**Repro steps**
On UpsettingBoy/gpgpu-rs@0f2303aef72d9db3cc1a80f01ee1fd0a4b227421
- Run `cargo r --example simple-compute`
- Get Vulkan validation error message

**Expected vs observed behavior**
I didn't get any validation error message before the update, tho it still works the same.

**Extra materials**
Validation message I get:
<details>

`VUID-VkDebugUtilsMessengerCreateInfoEXT-messageSeverity-requiredbitmask(ERROR / SPEC): msgNum: -1046727155 - Validation Error: [ VUID-VkDebugUtilsMessengerCreateInfoEXT-messageSeverity-requiredbitmask ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xc19c360d | vkCreateDebugUtilsMessengerEXT: value of pCreateInfo->messageSeverity must not be 0. The Vulkan spec states: messageSeverity must not be 0 (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-VkDebugUtilsMessengerCreateInfoEXT-messageSeverity-requiredbitmask)
    Objects: 1
        [0] 0, type: 3, name: NULL`

</details>

**Platform**
Win 10 + NVIDIA MX150 + Intel UHD 620 using wgpu gfx-rs/wgpu@a8caa367ee584309a06678b4e0aac75556073e42

**Comment by kvark** [comment]
Thank you for reporting!
This seems harmless, but needs fixing for sure.

**Comment by kvark** [comment]
Fixed by 90685b56257c8ab3147df08a05325151531a8d45
