### ISSUE TITLE
Most of the samples have Vulkan swapchain validation errors

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu#2286]
**Description**
Most of the samples have validation errors.

**Repro steps**
All of the samples that open a window and render show this swapchain error:

```
$ WGPU_POWER_PREF=high cargo run --example boids
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target\debug\examples\boids.exe`
Using NVIDIA GeForce RTX 2060 (Vulkan)
[2021-12-13T14:33:24Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x1a999117898, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1904,990), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (800,600), minImageExtent = (800,600), maxImageExtent = (800,600). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.2.198.1/windows/1.2-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2021-12-13T14:33:24Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x1a999117898, name: ?)
```

**Expected vs observed behavior**
No validation errors

**Platform**
Windows 10

**Comment by kvark** [comment]
We need a way for wgpu implementation to report back the surface size limits. And then, ideally, winit-based examples would respect those limits.

**Comment by aloucks** [comment]
That makes sense for the first one. I think this is actually a bug in winit. I see an erroneous resize event happening even in the winit  examples. However, shouldn't wgpu refuse to execute the resize if it's outside the range of valid values (I do see a validation warning if I enable logging).

The second issue looks unrelated though. Should I open a different issue for that?

**Comment by kvark** [comment]
> The second issue looks unrelated though. Should I open a different issue for that?

yes, please

> However, shouldn't wgpu refuse to execute the resize if it's outside the range of valid values (I do see a validation warning if I enable logging).

yes, it should. I suppose this validation check is missing.

**Comment by aloucks** [comment]
> yes, it should. I suppose this validation check is missing.

wgpu itself logs a warning (separate from the vulkan validation) but otherwise ignores it.

**Comment by cwfitzgerald** [comment]
This is now not a problem with up to date vulkan sdks
