### ISSUE TITLE
AMD iGPUs are detected as DiscreteGpus for the DX12 backend.

### ISSUE THREAD

**Issue by Elabajaba** [gfx-rs/wgpu#2304]
**Description**
On systems running AMD iGPUs, the iGPU's DX12 backend is labelled as a DiscreteGpu, while the Vulkan backend is labelled as an IntegratedGpu. This can cause issues when requesting a high power adapter as it will choose the DX12 backend over the Vulkan backend on systems that only have an AMD iGPU.

**Repro steps**
Run any wgpu application that requests a high power adapter on a laptop with an AMD iGPU and no discrete GPU on Windows.

**Expected vs observed behavior**
Expected: You get a Vulkan backend.
Observed: You get a DX12 backend.

**Extra materials**
https://gist.github.com/Elabajaba/0a4f6cd1202791f1a4ccfc544d130481
kvark's aha: https://matrix.to/#/!XFRnMvAfptAHthwBCx:matrix.org/$i9mLMKUQ4BP1YCSOM8kcOTlt55YxOIHCHAUOy6g_QRE

> so it's not reporting to be cache-coherent... interesting

**Platform**
Windows 10, tested on wgpu 0.11 and wgpu 0.12. Laptop with a Vega8 AMD iGPU and no discrete GPU.

**Comment by kvark** [comment]
Could you try #2305 ?

**Comment by Elabajaba** [comment]
Looks to have fixed it.

https://gist.github.com/Elabajaba/d62f81ce17fe61149d11aa7d874f7a94

**Comment by superdump** [comment]
Interesting. I had noticed with certain AMD drivers on a laptop with AMD Vega iGPU and mobile RTX 3080 discrete GPU that wgpu would use the Vega with DX12, but if I updated the drivers to the latest from AMD, then it would use the RTX with Vulkan. I guess this logic and that the newer driver exposed the cache coherent UMA, whatever that is, is probably what was making the difference?

**Comment by kvark** [comment]
surprising but possible
