### ISSUE TITLE
Vulkan Cannot call vkDestroyFramebuffer on VkFramebuffer

### ISSUE THREAD

**Issue by IsseW** [gfx-rs/wgpu#2310]
**Description**
When running the cube example, vulkan throws error every frame. 

This only happens when it is run with vulkan on the GeForce card. Integrated graphics with DirectX 12 works fine. 

Issue originally posted in bevy https://github.com/bevyengine/bevy/issues/3405.

**Extra materials**
Error every frame:
```
[2021-12-20T23:25:15Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-vkDestroyBuffer-buffer-00922 (0xe4549c11)]
        Validation Error: [ VUID-vkDestroyBuffer-buffer-00922 ] Object 0: handle = 0x2597b50000000030, name = _Staging, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0xe4549c11 | Cannot free VkBuffer 0x2597b50000000030[_Staging] that is in use by a command buffer. The Vulkan spec states: All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution (https://vulkan.lunarg.com/doc/view/1.2.154.1/windows/1.2-extensions/vkspec.html#VUID-vkDestroyBuffer-buffer-00922)
[2021-12-20T23:25:15Z ERROR wgpu_hal::vulkan::instance]         objects: (type: BUFFER, hndl: 0x2597b50000000030, name: _Staging)
```
**Platform**
On windows 10, with commit 54f20be. Graphics card: GeForce 940MX

**Comment by kvark** [comment]
Your subject says "vkDestroyFramebuffer" but the posted validation error says "vkDestroyBuffer". Is this intentional?

What happens if you run wgpu examples?

What is the version of your Vulkan SDK / validation layers?

**Comment by IsseW** [comment]
I just copied the same title I used for the bevy issue, should probably change it. The errors I posted in this issue are when running the wgpu cube example. 

I can check my vulkan version later tonight.

**Comment by IsseW** [comment]
My vulkan SDK is version 1.2.154.1, I don't know how to check the version of my Vulkan validation layers.

**Comment by cwfitzgerald** [comment]
That error is expected and was removed from the newest validation layers
