### ISSUE TITLE
Creating TextureDimension::D1 depth/stencil formats makes metal panic (and does not fail)

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#2323]
**Description**
Creating a 1 dimensional depth(/stencil) format does not cause a failure but makes metal panic:
```
-[MTLTextureDescriptorInternal validateWithDevice:]:1248: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor: depth/stencil pixel formats require texture type of MTLTextureType2D[Array] or MTLTextureTypeCube[Array].
```

Similar to #2045, #2057

**Repro steps**
As described. Seen when running `clear_texture` test on Metal with a depth format after depth formats got enabled as in #2307

**Expected vs observed behavior**
Should give a specialized error.
This is also lacking in the WebGPU spec I believe.

**Extra materials**
n/a

**Platform**
MacOS

**Comment by Wumpf** [comment]
Found it in the spec after all, it is called out on `createTexture` https://gpuweb.github.io/gpuweb/#dom-gpudevice-createtexture

**Comment by kvark** [comment]
Yes, let's forbid depth-stencil 1D textures please.
