### ISSUE TITLE
Pure GL context

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2344]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to integrate wgpu into a system that already created the window and GL context, and we want to draw something using wgpu's GLES context in addition to other stuff. In this case, EGL isn't involved.

**Describe the solution you'd like**
Some sort of constructor for GLES adapter, used in conjunction with `create_adapter_from_raw`.
This also means working without any Instance, and without any EGL involved.
Would be great to make it not a compile time feature.

**Describe alternatives you've considered**
Separate cargo feature for "raw" mode.

**Additional context**
required for https://github.com/kvark/vange-rs/issues/172

**Comment by caiiiycuk** [comment]
This also can be used with emscripten target.
