### ISSUE TITLE
Support Wayland Frame Callbacks

### ISSUE THREAD

**Issue by kaimast** [gfx-rs/wgpu#2375]
**Is your feature request related to a problem? Please describe.**
There seems to be no way to reliably stop rendering when the window is occluded or not visible for some other reason. This can potentially waste a lot of energy for applications that continuously render, like games.

**Describe the solution you'd like**
Wayland has a mechanisms called [frame callbacks](https://wayland-book.com/surfaces-in-depth/frame-callbacks.html). This is, for example, how [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1542808) prevents rendering when the window is occluded. 

From the Firefox bug description: 
_Wayland does not expose a concept of vsync or refresh rates. Instead, an application can be notified when the compositor decides that the application should render its next frame through "frame callbacks"._

_These frame callbacks exists per surface, and while they very explicitly do not indicate vsync, they are guaranteed to fire at a time that would give the application the most time to render before the next vblank. These events will under normal operation usually fire at display refresh rate, however, they are throttled as the Wayland compositor sees fit. The events may occur at a reduced rate or not at all, such as is the case for hidden windows._

Ideally, I would like to see wgpu to expose this via an additional `PresentMode` or another flag you can set when configuring the `Surface`.

**Describe alternatives you've considered**
There has been some work on occlusion notifications in winit (for example [for Windows](https://github.com/rust-windowing/winit/issues/2022)). But for Wayland there is no way to do this yet.
There might eventually be a [suspend](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/38) notification on Wayland but no idea if this will materialize any time soon and if compositors will implement it.

There is no mechanism like this for X11 as far as I know.

**Additional context**
I am not sure if this is the right place to report this issue. There might be some significant amount of work needed in the `client-toolkit` or `winit` crates before this could potentially be implemented.
I mainly just wanted to put this here, because I have been trying to figure out yesterday why my app does not do this by default and could not find any documentation in frame callbacks with regard to `wgpu` or `winit`.

**Comment by kvark** [comment]
Thank you for writing this down!
Windows occlusion and visibility is totally out of scope for wgpu itself. This should be up to `winit` to handle and expose, if it doesn't do this already.

**Comment by Diggsey** [comment]
Yeah, AFAIK there would be no changes required to wgpu to take advantage of this - you would just wait for the callback before calling `present`. It definitely doesn't make sense as a new `PresentMode`.

**Comment by kaimast** [comment]
> Yeah, AFAIK there would be no changes required to wgpu to take advantage of this - you would just wait for the callback before calling `present`. It definitely doesn't make sense as a new `PresentMode`.

That makes sense. I wasn't sure if this would be best be done internally when calling `present`.

We can close this for now and I might open an issue with `winit`.
