### ISSUE TITLE
Upgrade to winit 0.20.0

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#238]
Winit has released a prerelease of the upcoming 0.20.0 release.
We should start porting to it, so we can see how wgpu handles event loops 2.0
I don't mind whether we leave the PR unmerged until the full 0.20 release or merge with the pre-release.

Has anyone started on this? Otherwise I would like to take it on.

**Comment by m4b** [comment]
I too am also very keen to see how this works out on various platforms :)

**Comment by rukai** [comment]
This happened with 0.3!
