### ISSUE TITLE
Reading pixels into CPU memory

### ISSUE THREAD

**Issue by cloudhead** [gfx-rs/wgpu#239]
I'm looking for a way to read texture data back into CPU-memory. Something like `glReadPixels` from OpenGL. Is there a good way to do this currently? Basically a way to get a `&[u8]` from a `wgpu::Texture`.

Thanks

**Comment by kvark** [comment]
See [hello-compute](https://github.com/gfx-rs/wgpu-rs/blob/master/examples/hello-compute/main.rs) from the Rust wrapper (to be ported over here as well - #203).

Basically, getting the texture data back involves the following steps:
  1. creating a buffer with MAP_READ flag (not necessarily mapped right away)
  2. doing the GPU work of filling the texture texels
  3. executing `copy_texture_to_buffer` to copy texels from this texture into the buffer (it has to be non-mapped at this point)
  4. requesting to map that buffer to CPU with `map_read_async`
  5. callback is provided that gets you the slice of data

The example I linked get the data from a buffer (as opposed to a texture), so it uses `copy_buffer_to_buffer`. It also uses the same buffer for both uploading and downloading the data, which could be confusing (is it?).

**Comment by cloudhead** [comment]
Thanks :+1:, I thought this might be the only way, but wondered if there was a simpler API, symmetrical to the `fill_from_slice` on `Buffer`.
