### ISSUE TITLE
write_buffer on another thread can block get_current_texture for an extra frame

### ISSUE THREAD

**Issue by danielkeller** [gfx-rs/wgpu#2394]
I'm using wgpu on macos/metal, and when I call write_buffer on a different thread from get_current_texture, about 20% of the calls to write_buffer will block both calls for an extra ~16 ms. Here's a screenshot of puffin viewer showing the problem:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1353587/149627464-f4cc780c-41d8-42ad-947f-67a24aa2aeb5.png">
It looks like write_buffer might be taking a lock at just the wrong moment and causing get_current_texture to miss the screen refresh, and locking up both threads until the next screen refresh.

**Comment by kvark** [comment]
Similarly to #2395, this is blocked on #2272

**Comment by cwfitzgerald** [comment]
Obsoleted by #2710
