### ISSUE TITLE
RenderPass Drop seem to lock on each other in multithread

### ISSUE THREAD

**Issue by kunos** [gfx-rs/wgpu#2395]
**Description**
Trying to fill up 4 shadow passes in parallel, the time taken by the 4 passes is the same regardless if they are ran in parallel or on a single thread.
After a discussion on Discord this seems to be the source of some kind of internal lock:
https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/command/render.rs#L1042

In general the Drop implementation of RenderPass is pretty slow which is the main reason why I had to try to run things in parallel.
As a reference, I am pushing around 3000 draw calls some and seeing times of 1-2ms for the RenderPass to complete the Drop resulting in a scenario that for a typical engine with 4 shadomap passes + 1 main render passes of being totally CPU bound at around 100fps with GPU usage around 30%.... DirectX11 version of the engine running exactly the same content runs at 270fps maxing out GPU usage.

**Platform**
WGPU 0.12

**Comment by kvark** [comment]
Right. The `Drop` is where all the real recording happens, so it's expected to be slow.
It's definitely not the plan to make it lock the other threads away from recording.
Should have been addressed by #2272, but it got stuck in flight...

**Comment by cwfitzgerald** [comment]
Obsoleted by #2710
