### ISSUE TITLE
Front face semantics is broken on Intel/Linux/Vulkan

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2396]
Downstream - https://github.com/kvark/vange-rs/issues/155

**Description**
```rust
fn color_fs(in: Varyings, [[builtin(front_facing)]] is_front: bool) -> [[location(0)]] vec4<f32> {
    ...
    let normal = normalize(in.normal) * select(-1.0, 1.0, is_front);
    ...
}
```
It turns out that the `select` returns 0.0. If I replace it with `if`, then `is_front` turns out to be neither true or false.

**Repro steps**
[Run https://github.com/kvark/vange-rs](https://github.com/kvark/vange-rs/tree/1f412ad2328da783b94b24d7958db7449e608975)

**Expected vs observed behavior**
`front_facing` needs to work

**Extra materials**
Need to submit this bug upstream to Mesa/Intel.

**Platform**
```
Adapter 0:
        Backend:   Vulkan
        Name:      "Intel(R) Xe Graphics (TGL GT2)"
        VendorID:  32902
        DeviceID:  39497
        Type:      IntegratedGpu
        Compliant: true
```

**Comment by kvark** [comment]
Pushed the minimal example in hello-triangle in https://github.com/kvark/wgpu/tree/bug-intel-front-facing

**Comment by kvark** [comment]
Filed upstream as https://gitlab.freedesktop.org/mesa/mesa/-/issues/5876

**Comment by teoxoy** [comment]
Looks like this has been fixed upstream.
