### ISSUE TITLE
It would be nice if `wgpu::RenderPass::execute_bundles` receive `IntoIterator` instead of `Iterator`

### ISSUE THREAD

**Issue by maku693** [gfx-rs/wgpu#2406]
**Is your feature request related to a problem? Please describe.**

Currently, `wgpu::RenderPass::execute_bundles()` receives `Iterator<Item = &'a RenderBundle>` as an argument `render_bundles`.

https://github.com/gfx-rs/wgpu/blob/cdd480a89c9e3b681d9d174e65082d2bdbc903ef/wgpu/src/lib.rs#L2631-L2634

However it seems `render_bundles` does not have to be an `Iterator` because the method internally calls `render_bundles.into_iter()`.

If we can pass `IntoIterator` instead of `Iter`, it would be better aligned with other interfaces like `wgpu::Queue::submit`, and be more rust-y like we can pass `Some(render_bundle)` rather than `std::iter::once(render_bundle)`.

**Describe the solution you'd like**

Make `wgpu::RenderPass::execute_bundles` receives `IntoIterator` instead of `Iterator`. 

I have an intention to submit a PR.

**Describe alternatives you've considered**

Maintain the status-quo. (In case if I miss some reason the type of `render_bundles` needs to be `Iterator`.)

**Comment by kvark** [comment]
Thank you for filing! As long as it's aligned with `submit()` we are good.

**Comment by maku693** [comment]
Thank you! I'll work on it then.
