### ISSUE TITLE
Creating identical BindGroupLayouts in parallel can result in different layout ids

### ISSUE THREAD

**Issue by Tarv3** [gfx-rs/wgpu#2407]
**Description**
Calling `device.create_bind_group_layout(&desc)` in parallel with identical `desc` occasionally results in the created `BindGroupLayout` objects having different layout_ids.

I suspect it is due to the following lines of code where the following might happen. 

- Two threads get read access to the bind_group_layouts
- Both threads determine that no duplicated layout exists
- Both threads create and insert the new layout with different ids

https://github.com/gfx-rs/wgpu/blob/cdd480a89c9e3b681d9d174e65082d2bdbc903ef/wgpu-core/src/device/mod.rs#L3803-L3822

**Repro steps**
The attached [bind-group-layout-test.zip](https://github.com/gfx-rs/wgpu/files/7898165/bind-group-layout-test.zip) file contains a simple program that spawns many threads that call `device.create_bind_group_layout(&desc)` with a common `BindGroupLayoutDescriptor`. The resulting layout ids are printed to the console.

When running this program in debug mode, most of the time some of the printed layout ids would be different. However, when running in release mode, most of the time the ids would all be the same.

**Expected vs observed behavior**
When creating `BindGroupLayout` objects with the same `BindGroupLayoutDescriptor` in parallel, some of the bind group layouts would have different layout ids. I would expect all bind group layouts created with the same descriptor to have the same layout id as the id is used for validation.

**Platform**
- OS: Windows 10
- wgpu version: 0.12

**Comment by kvark** [comment]
Thank you for filing! This is indeed a bug here. Also, unfortunate one. It means we have to keep a lock for the duration of BGL creation, so this deduplication has an immediate effect on the performance.
One way to solve this, I suppose, would be to just hash the contents of BGL descriptor, and use this hash in whatever places we are comparing for equality.

**Comment by Tarv3** [comment]
You could drop the lock during the BGL creation but check for deduplication again when you obtain a write lock before you insert it. However, if deduplication is just as expensive as creating the layout then this might not help.

**Comment by kvark** [comment]
The cost of creation is not a concern here. BGLs are not created every frame. It's the locking, rather, that I'm concerned about, which could prevent the *use* of BGLs by other work. I suppose if we copy the descriptors out in a separate hashset or something like this, and we no longer deduplicate based on the storage itself, we'll be fine.

**Comment by a1phyr** [comment]
I don't know whether this is applicable here, but you could use something like [`parking::RwLockUpgradableReadGuard`](https://docs.rs/lock_api/0.4.5/lock_api/struct.RwLock.html#method.upgradable_read) here. Doing so would prevent several thread from doing the check at the same time, while allowing reading it for other work.

**Comment by kvark** [comment]
Right, that's possible, although I wouldn't work BGLs to be handled entirely differently (i.e using different types of storage) from the rest. The less diversity in code the better.

**Comment by cwfitzgerald** [comment]
This is long fixed.
