### ISSUE TITLE
GL backend produce wrong values in compute shader when `groupMemoryBarrier()` is used.

### ISSUE THREAD

**Issue by francesco-cattoglio** [gfx-rs/wgpu#2408]
**Description**
When using `groupMemoryBarrier()` in a compute shader on Linux, GL backend, Intel iGPU, the values produced by the shader can be wrong.

**Repro steps**
This is the repro case, using glow directly: https://github.com/francesco-cattoglio/gl-intel-workgroup-bug

**Expected vs observed behavior**
When using a shared workgroup buffer, it seems like the `groupMemoryBarrier()` only synchronizes the memory for the first 16 threads (on 11-th gen CPU, seems to me that 32 threads work correctly instead). Therefore, if one uses a `local_size_x` greater than 16, some memory locations will likely contain wrong data after the `groupMemoryBarrier()` call.

**Platform**
I can confirm this bug exists on Intel iGPUs, from 7-th to 11-th gen, under Ubuntu Linux 20.04, with both default system mesa and mesa 21.3 from kisak's PPA.
This does not happen on my AMD 4000 series APU, nor does it happen if Vulkan backend is selected for wgpu on Intel.

**Comment by kvark** [comment]
Upstream issue - https://gitlab.freedesktop.org/mesa/mesa/-/issues/5894

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/naga/issues/1677 fixed this issue, closing.
