### ISSUE TITLE
Validate MSAA compatibility with render pass

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#241]
We need to ensure that the active render pass has the same sample count as the render pipeline being used, otherwise the following validation error is triggered:
> VALIDATION [VUID-vkCmdDrawIndexed-renderPass-00454 (0)] : vkCmdDrawIndexed(): RenderPasses incompatible between active render pass w/ renderPass 0x30 and pipeline state object w/ renderPass 0x8 Attachment 0 is not compatible with 0: They have different samples.. The Vulkan spec states: The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdDrawIndexed-renderPass-00454)
object info: (type: RENDER_PASS, hndl: 48)

**Comment by rukai** [comment]
I'll look into it

**Comment by rukai** [comment]
How do I reproduce this?
When I set the sample_counts to mismatching values, I hit this panic as expected: https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/command/render.rs#L423

**Comment by kvark** [comment]
Indeed, you are right. Not sure how we hit the validation error then. Let's reopen once we see this case again.
