### ISSUE TITLE
Latest firefox nightly request device with requiredLimits not work as expected

### ISSUE THREAD

**Issue by onsummer** [gfx-rs/wgpu#2414]
**Description**
When I request an device with requiredLimits, it does not work as my expected.

The code is running at Firefox nightly 98.0a1 (2022-01-22)

![image](https://user-images.githubusercontent.com/26168955/150647721-0de08e20-fb45-4c6c-bc3f-48e381ae084f.png)

The adapter.limits.maxTextureDimension2D is 16384, but I pass requiredLimits.maxTextureDimension2D is over this number, it resolve.

I found that there is an function in https://github.com/gfx-rs/wgpu/blob/0183e7d1e85ac95f2461426a910b2f86f5373119/wgpu-core/src/instance.rs, line 30:

``` rust
fn check_limits(requested: &wgt::Limits, allowed: &wgt::Limits) -> Vec<FailedLimit> {
// ...
}
```

The function check the requested with allowed, if not satisfied, then push an new FailedLimit to the faild Vec3 container.

It stands to reason that a FailLimits will be generated, but seems that Firefox nightly does not report an error in the console.

**Repro steps**
As the code below:

```html
<body onload="main()">
  <div style="width: 800px; height: 600px;">
    <canvas width="800" height="600"></canvas>
  </div>
</body>
```

```js
const main = async () => {
  const adapter = await navigator.gpu.requestAdapter()
  const device = await adapter.requestDevice({
    requiredLimits: {
      maxTextureDimension2D: 100000000086
    }
  })

  debugger
}
```

**Expected vs observed behavior**
Report an error that `requiredLimits.maxTextureDimension2D` is over adapter's limits.maxTextureDimension2D on console.

**Platform**
Windows 10 2004

**Comment by kvark** [comment]
Thank you for filing! I'll get to this next week, hopefully.

**Comment by kvark** [comment]
Upstream https://bugzilla.mozilla.org/show_bug.cgi?id=1751718

**Comment by kvark** [comment]
There is nothing to do on wgpu side, closing.
