### ISSUE TITLE
MAPPABLE_PRIMARY_BUFFERS on M1 Pro

### ISSUE THREAD

**Issue by BGR360** [gfx-rs/wgpu#2426]
Came over here from https://github.com/bevyengine/bevy/issues/3686#issuecomment-1020820103.

Mostly just starting a conversation, as I have little to no knowledge on the subject matter.

It was suggested in that discussion I linked that perhaps wgpu shouldn't warn MAPPABLE_PRIMARY_BUFFERS on platforms like Apple M1 that have powerful integrated GPUs. Thoughts?

**Comment by cwfitzgerald** [comment]
This is just from us erroneously detecting it as a dedicated, not an integrated, gpu. Once this is fixed, the warning will go away.

**Comment by BGR360** [comment]
I'd be willing to take a stab at fixing that. Could you point me in the right direction?

**Comment by cwfitzgerald** [comment]
https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/metal/mod.rs#L117-L121

Here is the offending check. I'm not sure there's a clean way in the metal api to determine uma-ness, but I haven't checked. If not we can likely use the adapter family to determine which is which.

**Comment by kvark** [comment]
See also - https://github.com/KhronosGroup/MoltenVK/issues/1201
We could do a similar fix.

**Comment by superdump** [comment]
I was just looking into this and I noticed that it's currently based on 'power' where high is mapped to discrete and low is mapped to integrated. But then I saw this in mtl::Device: https://github.com/gfx-rs/metal-rs/blob/master/src/device.rs#L1580 This seems like a good deciding factor perhaps?

**Comment by cwfitzgerald** [comment]
Yup, that's what MVK does

**Comment by superdump** [comment]
So, to clarify, we would need to fix this for the Metal backend, and the GL backend at least for WebGL2. The Vulkan backend using MoltenVK with the fix should be correct already. Right?

**Comment by superdump** [comment]
https://github.com/gfx-rs/wgpu/pull/2429 how's this?
