### ISSUE TITLE
validation errors on descriptor pool release

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#243]
Sometime recently, can track down if you like, pretty sure it was MSAA and/or rendy upgrades, I started seeing this validation error:
```
VALIDATION [VUID-vkDestroyDescriptorPool-descriptorPool-00303 (0)] : Cannot call vkDestroyDescriptorPool on DescriptorPool 0x708 that is currently in use by a command buffer. The Vulkan spec states: All submitted commands that refer to descriptorPool (via any allocated descriptor sets) must have completed execution (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkDestroyDescriptorPool-descriptorPool-00303)
object info: (type: DESCRIPTOR_POOL, hndl: 1800)
```
It is basically printed every frame.

I've tracked down it's coming from:
1. the buffer copy of CPU data to a storage buffer used in a dispatch step of a compute pipeline
2. it involves:
   1. an input storage buffer filled every frame with some input data from the CPU
    2. an output storage buffer, allocated once with a fixed size the compute shader writes to
    3. a uniform buffer with a single piece of information (the size of the input storage buffer).
    4. a re-bind of the new input buffer, new uniform buffer, and non reallocated output storage buffer
    5. on off-chance the input > output size, i reallocate the output buffer to match (hence why it's mutable in function declaration below)

I don't think I'm doing anything explicitly wrong here, so the validation error is surprising, but please let me know if something here is a red flag.

The offending function is basically this:

```rust 
    pub fn copy(
        &mut self,
        input: &[Gfx], // CPU input data
        output: &mut wgpu::Buffer,
        device: &wgpu::Device,
        encoder: &mut wgpu::CommandEncoder,
    ) -> usize {
       // input storage buffer, we fill with the CPU input data, in `input`
        let input_data = device.create_buffer_mapped(real_npositions, wgpu::BufferUsage::STORAGE);

        for (ref gfx, ref mut vertex) in input.iter().zip(input_data.data.iter_mut()) {
            **vertex = Vertex::from(**gfx);
        }
        let shard_info_size = std::mem::size_of::<u32>();
        // uniform buffer
        let shard_info =
            device.create_buffer_mapped(shard_info_size, wgpu::BufferUsage::UNIFORM);
        shard_info.data[0] = input.len();
      // bind
        device.create_bind_group(&wgpu::BindGroupDescriptor {
            layout: &self.layout,
            bindings: &[
                wgpu::Binding {
                    binding: 0,
                    resource: wgpu::BindingResource::Buffer {
                        buffer: input_data,
                        range: 0..input_data.size() as u64, // technically i put the wgpu::Buffer into a struct which computes the size, and has this method, but deref's to wgpu::Buffer, in case this caught your eye
                    },
                },
                wgpu::Binding {
                    binding: 1,
                    resource: wgpu::BindingResource::Buffer {
                        buffer: output,
                        range: 0..output.size() as u64,
                    },
                },
                wgpu::Binding {
                    binding: 2,
                    resource: wgpu::BindingResource::Buffer {
                        buffer: shard_info,
                        range: 0..shard_info.size() as u64,
                    },
                },
            ],
        });
       // dispatch
        {
            let mut cpass = encoder.begin_compute_pass();
            cpass.set_pipeline(&self.pipeline);
            cpass.set_bind_group(0, &bind_group, &[]);
            cpass.dispatch(NUM_WORK_GROUPS as u32, 1, 1);
        }
       // function ends, so I assume this compute is run until it finishes, and then `input_data` is dropped?
```
Even if last comment is false (e.g., the compute runs asynchronously, and the function call ends, calling the drop of the `input_data`) and even if this causes lifetime issues, I added a `std::thread::sleep(Duration::from_millis(200))` just before the function ends; i'm doing this on some test data, and I _still see_ the message occasionally; I don't think its possible that I'm doing work on the gpu for 200 ms, for the test inputs I'm working with (maybe 200 vertices are being copied into the input_data storage buffer, and otherwise I run at 60fps, but still see the validation error)

Anyway, let me know if you see anything strange; if I comment out this call, the validation errors disappear, so _something_ in there is unusual; i feel like it has to do with the input storage buffer, but I dunno.

**Comment by m4b** [comment]
So I believe I've checked out the fix in #244 and I still receive the same validation errors, so I don't think this fixes the issue reported here unfortunately

**Comment by kvark** [comment]
Could you do a little debugging on your end? The expected sequence of events is the following:
  1. you create a bind group
  2. on `set_bind_group`, it becomes a part of the `ComputePass::trackers` (this is what #244 is fixing)
  3. on `end_pass` the trackers are moved (back) to `CommandBuffer`
  4. on `submit` we are going through the used bind groups and update their `submission_index`
  5. the bind group gets dropped on your end, which calls `wgpu_bind_group_destroy`, which ends up pushing the bind group into `PendingResources::referenced`
  6. the next `PendingResources::triage_referenced()` call sees that the bind group is no longer referenced and removes it from HUB. It then looks for the active submissions with the given index (we updated in step 4) and adds our resource to the appropriate `ActiveSubmission::resources` list
  7. in `PendingResources::cleanup` a few frames later we see that this submission is done, and we actually call gfx-rs to destroy the descriptor set associated with this bind group. This is where our validation errors fires up

The only way we could see this validation is if this sequence is broken at some point, so that we don't properly associate the bind group with an active submission and destroy it ahead of time.

**Comment by m4b** [comment]
I will do extra debugging but can we reopen. I’m pretty certain this is not fixed.

**Comment by m4b** [comment]
I'm not longer seeing this error as of:

```
wgpu 0.2.2 (git+https://github.com/gfx-rs/wgpu-rs?rev=5dd361fc639e71af328504f9e27a08daf83d7633)"
wgpu-native 0.2.6 (git+https://github.com/gfx-rs/wgpu?rev=32399cff8a0b55389f2d2493ea5c900c986c2547)"
```

So going to close this!
