### ISSUE TITLE
Zero out workgroup memory

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2430]
For WebGPU it's important that the workgroup memory doesn't contain garbage. Otherwise one page could see the side products of another page. We need to find a way to zero-initialize it, and we need to figure out when exactly we have to do this.

**Comment by teoxoy** [comment]
How would this work?

So far I could only find how to do this on Vulkan/SPIR-V (naga would need to set `OpConstantNull` on Workgroup variables) but not all devices support the [`VK_KHR_zero_initialize_workgroup_memory`](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_zero_initialize_workgroup_memory.html) extension.

I tried to find something similar for Metal and DX11/12 without success (they don't allow initializers for  Workgroup variables).
