### ISSUE TITLE
Texture formats conversion

### ISSUE THREAD

**Issue by xenoliss** [gfx-rs/wgpu#2436]
Hello, I'm writing a compute shader in WGSL that is using some `texture_storage_2d`. The list of supported texel formats for this is given here : https://www.w3.org/TR/WGSL/#storage-texel-formats.

In my shader, I end up with the following: 
```
[[group(2), binding(0)]] var texture_storage_src: texture_storage_2d<rgba8unorm, read>;
[[group(2), binding(1)]] var texture_storage_dst: texture_storage_2d<rgba8unorm, write>;
```
Please also note that the WGSL specs are explicitly saying that for texture storage types, the access mode **must** be `write` (https://www.w3.org/TR/WGSL/#texture-storage). Nevertheless I set them to `read` and `write` (to match with `StorageTextureAccess::ReadOnly` and `StorageTextureAccess::WriteOnly` I set when defining my binding group layout) and no error is raised. As a new user that's kind of confusing (the difference between specs and wgpu), could you clarify this ?

Back on the CPU side, the following code
```rs
let prefered_format = surface.get_preferred_format(&adapter).unwrap();
println!("PREFERED FORMAT {:?}", prefered_format);
```
is giving me : `PREFERED FORMAT Bgra8UnormSrgb`. The only other supported format I have is `Bgra8Unorm`.

The problem comes when I'm now trying to copy the content of my `texture_storage_2d` (that has been filled in my compute shader) to a texture that will be presented on screen. The following code shows this process:
```rs
let output = self.surface.get_current_texture()?;

let mut encoder = self
    .device
    .create_command_encoder(&CommandEncoderDescriptor {
        label: Some("Command encoder"),
    });

{
    let mut cpass = encoder.begin_compute_pass(&ComputePassDescriptor {
        label: Some("Compute Pass"),
    });
    cpass.set_pipeline(&self.compute_pipeline);
    cpass.set_bind_group(0, &self.uniforms_bind_group, &[]);
    cpass.set_bind_group(1, &self.agents_bind_groups[frame_num % 2], &[]);
    cpass.set_bind_group(2, &self.textures_storage_bind_groups[frame_num % 2], &[]);
    cpass.dispatch(self.work_group_count, 1, 1);
}

encoder.copy_texture_to_texture(
    ImageCopyTexture {
        texture: &self.textures[frame_num % 2],
        mip_level: 0,
        origin: Origin3d { x: 0, y: 0, z: 0 },
        aspect: TextureAspect::All,
    },
    ImageCopyTexture {
        texture: &output.texture,
        mip_level: 0,
        origin: Origin3d { x: 0, y: 0, z: 0 },
        aspect: TextureAspect::All,
    },
    Extent3d {
        width: WIDTH,
        height: HEIGHT,
        depth_or_array_layers: 1,
    },
);

self.queue.submit(std::iter::once(encoder.finish()));
output.present();
```

I end up with the following error:
```
Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    source format (Rgba8Unorm) and destination format (Bgra8Unorm) are different
```

What is the intended way to fill a texture from a compute shader and then display it on screen ? Thanks for your help !

PS: Also I'm a bit surprised that the only supported formats are "Bgra8UnormSrgb" and "Bgra8Unorm", any idea ?

**Comment by jinleili** [comment]
`texture_storage_2d` access must be `write`: https://www.w3.org/TR/WGSL/#texture-storage
Binding it as `texture_2d` to read or sample

Use a `RenderPass` draw you `texture_2d` on screen, the texture format will be converted automatically

**Comment by xenoliss** [comment]
Hey thansk for the help, will give it a try !

> texture_storage_2d access must be write

I agree on that but then why `StorageTextureAccess` does not enforce it and allows other access mode  ?

**Comment by cwfitzgerald** [comment]
It is a native extension to allow textures to be used as read/write or read, which is why those enumerations are there.
