### ISSUE TITLE
WSLg: thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by Ploppz** [gfx-rs/wgpu#2441]
On WSL with WSLg in Windows 11.
Commit: https://github.com/Ploppz/bup/commit/94f0e8f3c99f9f12c8a19a5e08b0d55e3aa26e3c

`cargo run` with nightly rustc panics:

```
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/ploppz/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.9.0/src/window.rs:350:15
```

If you want to reproduce the issue, note that you have to install: `libclang-dev libsodium-dev libssl-dev libgtk-3-dev pkg-config liblzma-dev build-essential`

**Comment by kvark** [comment]
You are using wgpu-0.9 for this? I don't think we'd be supporting it now, it's been a while!

**Comment by Ploppz** [comment]
Yeah I'll try to upgrade, thanks
