### ISSUE TITLE
Memory usage grows over time

### ISSUE THREAD

**Issue by ZacharyKamerling** [gfx-rs/wgpu#2448]
**Description**
Memory usage grows over time.

**Repro steps**
Most examples (boids, cube, hello-triangle, mipmap, etc)  exhibit this behavior.

**Platform**
Windows 11 Home Insider Preview
wgpu = "0.12.0"
--release

**Comment by cwfitzgerald** [comment]
Does running in release mode `cargo run --example mipmap --release` for example, fix the problem?

**Comment by ZacharyKamerling** [comment]
It does not. I ran all of them in release mode.

**Comment by cdecompilador** [comment]
I've experienced a similar issue, resizing starts to grow the program memory consumption, on the VULKAN and DX12 backends at least.

Also the memory consumption of just creating adapter, device, queue, pipeline takes up to 40 MB of ram, which is too big compared to doing the process from scratch on each backend

**Comment by jimblandy** [comment]
@cdecompilador That sounds like two problems separate from the one the original reporter identiified. Could you file a separate issue for those?

**Comment by cwfitzgerald** [comment]
Without a reproduction case, there's not much we can do about these, please re-file with a repro case if you have one on the latest wgpu.
