### ISSUE TITLE
M1 in macOS incorrectly reports supported compressed texture formats

### ISSUE THREAD

**Issue by superdump** [gfx-rs/wgpu#2452]
**Description**
Apple M1 GPUs support ASTC, BC, EAC/ETC2, and even PVRTC compressed texture formats but on BC is reported as being supported.

**Repro steps**
Inspect the `Features` returned from `Adapter::features()` for an M1 GPU in macOS.

**Expected vs observed behavior**
- Expected
  - `TEXTURE_COMPRESSION_BC`, `TEXTURE_COMPRESSION_ASTC_LDR`, and `TEXTURE_COMPRESSION_ETC2` are all reported as being supported.
- Observed
  - Only `TEXTURE_COMPRESSION_BC` is reported as being supported.

**Platform**
Tested with wgpu 0.8 and master on an M1 Max running macOS Monterey 12.2

**Comment by superdump** [comment]
I dug into this a bit and with some hacking to report all of ASTC, BC, EAC/ETC2 as being supported, I have been able to make use of all on M1. I did this because at first it was unclear from Apple documentation exactly what M1 should support.

It looks like the checks in `metal-rs` probably need to be updated, but also the way the features are constructed in `wgpu` look like they could be improved as they seem to always report BC: https://github.com/gfx-rs/wgpu/blob/766c6cda1917c1265fa8a5f610ef7516d4314d1b/wgpu-hal/src/metal/adapter.rs#L1013

**Comment by superdump** [comment]
I didn't understand the relation between `MTLGPUFamily` and `MTLFeatureSet` and was trying to understand where the Apple7 family fit into the feature sets, but the table at the beginning of: https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf clarifies that there is not yet any corresponding feature set for Apple7 (which includes A14 and M1 GPUs.)

However, I see elsewhere in the code that `device.supports_family(MTLGPUFamily::Apple7)` is used so I think I can just make use of that.

**Comment by superdump** [comment]
I've made a PR that fixes both the issues detailed above: https://github.com/gfx-rs/wgpu/pull/2453

In metal-rs, it seems that it is not currently possible to correctly detect compressed texture format support using the following methods:
```rust
    pub fn supports_pvrtc_pixel_formats(&self) -> bool {
        self.os() != OS::macOS
    }

    pub fn supports_eac_etc_pixel_formats(&self) -> bool {
        self.os() != OS::macOS
    }

    pub fn supports_astc_pixel_formats(&self) -> bool {
        match self.os() {
            OS::iOS => self.gpu_family() >= 2,
            OS::tvOS => true,
            OS::macOS => false,
        }
    }

...

    pub fn pvrtc_pixel_formats_capabilities(&self) -> PixelFormatCapabilities {
        if self.supports_pvrtc_pixel_formats() {
            PixelFormatCapabilities::Filter
        } else {
            PixelFormatCapabilities::empty()
        }
    }

    pub fn eac_etc_pixel_formats_capabilities(&self) -> PixelFormatCapabilities {
        if self.supports_eac_etc_pixel_formats() {
            PixelFormatCapabilities::Filter
        } else {
            PixelFormatCapabilities::empty()
        }
    }

    pub fn astc_pixel_formats_capabilities(&self) -> PixelFormatCapabilities {
        if self.supports_astc_pixel_formats() {
            PixelFormatCapabilities::Filter
        } else {
            PixelFormatCapabilities::empty()
        }
    }
```
as they _only_ depend on the OS and not on the MTLGPUFamily and so they have insufficient information. Arguably reporting a lack of support when the GPU supports the format is less harmful than reporting support where there is none. It still unnecessarily limits use to BC on macOS for M1 GPUs.

**Comment by jinleili** [comment]
Verified on the master branch of wgpu, this issue has been fixed.
