### ISSUE TITLE
Running wgpu in a secondary thread segfaults when main thread ends.

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#246]
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver

```
fn main() {
    std::thread::spawn(move || {
        triangle_example();
    });

    std::thread::sleep(std::time::Duration::from_millis(500));
}
```
Running the triangle example in a separate thread and then ending the main thread causes the wgpu thread to segfault.

repro: https://github.com/rukai/wgpu-rs/blob/segfault_repro/examples/repro/main.rs

**Comment by Aaron1011** [comment]
Minimized reproduction: https://github.com/Aaron1011/wgpu-segfault

The issue occurs in `gfx_backend_gl`, which uses `libloading` to dynamically load the OpenGL shared library: https://github.com/gfx-rs/gfx/blob/07043744b4b05893363066ca0e50c5e38348f20c/src/backend/gl/src/window/egl.rs#L20-L23

When the `libloading::Instance` gets dropped when the thread function returns, it unloads the shared library. However, it appears that a TLS destructor remains registered for the shared library, despite the code being unloaded. When libc attempts to run the registered TLS destrutors on thread exit (after the Rust code has run), we get a segfault.

See https://github.com/nagisa/rust_libloading/issues/41 for more details

**Comment by kvark** [comment]
@Aaron1011 any idea on what we should be doing?

**Comment by Aaron1011** [comment]
@kvark: There's talk about changing `libloading` to only call `dlopen` when explicitly requested (instead of automatically on `Drop`): https://github.com/nagisa/rust_libloading/issues/41#issuecomment-782934696

**Comment by Aaron1011** [comment]
For now, the best solution is probably to do something similar to this workaround: https://github.com/nagisa/rust_libloading/issues/41#issuecomment-448303856

Specifically, `gfx_backend_gl` should open the graphics driver shared library with `RTLD_NODELETE`.

**Comment by Aaron1011** [comment]
From my testing, it looks like unloading `libX11.so` doesn't cause any problems - it's unloading `libEGL.so` that causes problems. For example, NVIDIA's `libglvnd` [registers a pthread key destructor](https://github.com/NVIDIA/libglvnd/blob/acc654454867c7cdd681cc1f60f858bcd6e5e729/src/EGL/libeglcurrent.c#L79-L84)
