### ISSUE TITLE
hello-compute example crashes - Internal error: mapping of ResourceBinding { group: 0, binding: 0 } is missing

### ISSUE THREAD

**Issue by ingun37** [gfx-rs/wgpu#2460]
**Description**
*hello-compute* example crashes with the message
```
[2022-02-06T07:22:09Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
    Internal error: mapping of ResourceBinding { group: 0, binding: 0 } is missing

', wgpu/src/backend/direct.rs:2273:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Repro steps**
```shell
git clone https://github.com/gfx-rs/wgpu.git
cd wgpu
cargo run --example cube
```

**Expected vs observed behavior**
* Expected to terminate successfully
* but instead observed crash.

**Extra materials**

**Platform**
* MacOS Monterey 12.1
* wgpu 0.12.0
* revision 3e0305d27d790034fc54ef871f733399fb7cd374
  Author: Samuel Hurel <samuel.hurel@gmail.com>
  Date:   Sat Feb 5 15:53:04 2022 +0100
  Allow non struct buffers in wgsl (#2451)

**Comment by jinleili** [comment]
Has been fixed by https://github.com/gfx-rs/wgpu/pull/2459
