### ISSUE TITLE
Unable to fallback to Immediate from Mailbox.

### ISSUE THREAD

**Issue by EbbDrop** [gfx-rs/wgpu#2463]
Somme adapters support Immediate mode but not Mailbox so it would be nice if you could specify to fall back to Immediate instead of FiFo in those cases.

I see two solution to this problem:

- Some way to query safely what present modes a adapter supports so that you could implement the fallback manually.
- An extra `Option<PresentMode>` field on SurfaceConfiguration to specifie the fallback you want to use. If the fallback is also not supported fall back to FiFo

**Comment by cwfitzgerald** [comment]
This is covered by the new presentation mode api - it's completely on the user to choose what they want.
