### ISSUE TITLE
Bevy app crashing due to wgpu on certain platforms

### ISSUE THREAD

**Issue by a-b-c-1-2-3** [gfx-rs/wgpu#2465]
**Description**
On creating a project in Bevy and enabling the "wayland" feature, startup fails on certain GPUs(?) and the window closes immediately after opening. This issue is present on my home PC, on a GTX 1080 running Gnome on Wayland, but *not* on my Laptop, which is running KDE Wayland with an Intel iGPU. The error given is caused by wgpu, stderr: `thread 'main' panicked at 'Error in Surface::configure: requested format Bgra8UnormSrgb is not in list of supported formats: [Bgra8Unorm]'`

**Repro steps**
Create a basic Bevy app:
```
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run()
}
```
Execute it under the conditions described (GTX 1080, Gnome Wayland, native Wayland window), notice crash.
Other scenarios attempted:
- Run on bevy taken from git, not stable ver. (0.6)
Same error.

**Expected vs observed behavior**
Expected: Blank window opens
Observed: Bevy crashes with aforementioned error

**Extra materials**
Logs: https://github.com/gfx-rs/wgpu/files/7994274/log.txt

**Platform**
Arch Linux (all pkgs + rust-nightly up to date), Ryzen 7 1800x, GTX 1080, Gnome-Wayland, using stable ver. of Bevy, wgpu ver. 0.12.0, running on native Wayland (not Xwayland).

Update: Seems like disabling Wayland on the stable version makes it work.

**Comment by xiaopengli89** [comment]
Bevy always use `srgb` color space, which not all physical devices support.

https://github.com/bevyengine/bevy/blob/main/crates/bevy_render/src/view/window.rs#L137
https://github.com/bevyengine/bevy/blob/865698548f23fa13a03202442bf114f5c01b8f46/crates/bevy_render/src/texture/mod.rs#L63

**Comment by a-b-c-1-2-3** [comment]
Hm. Is there any way to make it work short of forking the Bevy sources and modifying the `impl`?
