### ISSUE TITLE
Can't compile shader because of "@stage"

### ISSUE THREAD

**Issue by jansen44** [gfx-rs/wgpu#2466]
### About
- Device: __MacBook Pro 13-inch, 2017 - MacOS Monterey 12.1__;
- wgpu Version: __0.12.0__;
- Rust Version: __1.58.1__;
- Cargo Version: __1.58.0__;

### Problem
For some reason there's a problem when trying to compile a WGSL shader, and the error message shows that the problem is with ```@stage``` notation, where '@' is not a valid character. I really don't know what's wrong, if it's a bug or I'm just missing something, but I just can't figure. The shader in question is the same shader from wgpu 'hello-triangle' example, the weird thing is: I can run the example flawlessly but can't compile the same shader using the same code within my own project.

### Shader source
```wgsl
@stage(vertex)
fn vs_main(@builtin(vertex_index) in_vertex_index: u32) -> @builtin(position) vec4<f32> {
    let x = f32(i32(in_vertex_index) - 1);
    let y = f32(i32(in_vertex_index & 1u) * 2 - 1);
    return vec4<f32>(x, y, 0.0, 1.0);
}

@stage(fragment)
fn fs_main() -> @location(0) vec4<f32> {
    return vec4<f32>(1.0, 0.0, 0.0, 1.0);
}
```

### Relevant Rust code
```rust
// ...
    let shader = device.create_shader_module(&wgpu::ShaderModuleDescriptor {
        label: None,
        source: wgpu::ShaderSource::Wgsl(Cow::Borrowed(include_str!("shader.wgsl"))),
    });
// ...
```

### Error Message
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
    
Shader '' parsing error: expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file, found '@'
  ┌─ wgsl:1:1
  │
1 │ @stage(vertex)
  │ ^ expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file


    expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file, found '@'

', /Users/jansenjunior/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cwfitzgerald** [comment]
Thanks for filling! The problem here is that. 0.12 uses an older version of wgsl, so if you want to look at compatible shaders, look at the 0.12 branch of wgpu. If you want to use the shaders from the master branch, you should also use the master version of wgpu.
