### ISSUE TITLE
Relax color attachment validation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#2469]
See https://github.com/gpuweb/gpuweb/pull/2562, which covers 2 of the issues linked from there:

1. We need to make the color attachments `Option`-al in render pipelines, render passes, and render bundles
2. We need to allow shaders to have more outputs than the pipeline has. (maybe we already allow that?)

**Comment by teoxoy** [comment]
This has been done in https://github.com/gfx-rs/wgpu/pull/2778 and https://github.com/gfx-rs/wgpu/pull/2822.
