### ISSUE TITLE
vk backend on macOS cannot support surface `configuration`'s `Rgba16Float` format

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/wgpu#2489]
**Repro steps**
Install [Vulkan SDK for Mac](https://vulkan.lunarg.com/sdk/home#mac), then set surface `configuration`'s format to `Rgba16Float`, run `WGPU_BACKEND=vk cargo run --example skybox`:

```sh
Using Apple M1 Max (Vulkan)
thread 'main' panicked at 'Error in Surface::configure: requested format Rgba16Float is not in list of supported formats: [Bgra8Unorm, Bgra8UnormSrgb]', wgpu/src/backend/direct.rs:231:9
```

**Platform**
macOS + Vulkan SDK

**Comment by kvark** [comment]
This is a bit tricky, because WebGPU baseline says nothing about Rgba16F needed to be supported for presentation.

**Comment by jinleili** [comment]
But [WebGPU Spec](https://gpuweb.github.io/gpuweb/#canvas-configuration) says:
> The supported context formats are a [set](https://infra.spec.whatwg.org/#ordered-set) of [GPUTextureFormat](https://gpuweb.github.io/gpuweb/#enumdef-gputextureformat)s that must be supported when specified as a [GPUCanvasConfiguration](https://gpuweb.github.io/gpuweb/#dictdef-gpucanvasconfiguration).[format](https://gpuweb.github.io/gpuweb/#dom-gpucanvasconfiguration-format) regardless of the given [GPUCanvasConfiguration](https://gpuweb.github.io/gpuweb/#dictdef-gpucanvasconfiguration).[device](https://gpuweb.github.io/gpuweb/#dom-gpucanvasconfiguration-device), initially set to: «["bgra8unorm"](https://gpuweb.github.io/gpuweb/#dom-gputextureformat-bgra8unorm), ["rgba8unorm"](https://gpuweb.github.io/gpuweb/#dom-gputextureformat-rgba8unorm), ["rgba16float"](https://gpuweb.github.io/gpuweb/#dom-gputextureformat-rgba16float)».

**Comment by kvark** [comment]
oh, I missed this. Interesting. Kinda surprised rgba16float would be universally supported.

**Comment by jinleili** [comment]
Support for `Rgba16Float` now depends on the physical device:
https://github.com/gfx-rs/wgpu/blob/01628a1fad05708ebc3d5e701736915b39ad37ae/wgpu-hal/src/vulkan/adapter.rs#L1524-L1540
