### ISSUE TITLE
Validation error with atomic arrays on metal

### ISSUE THREAD

**Issue by Ria8651** [gfx-rs/wgpu#2490]
**Description**
When running the `hello-compute` example with an atomic array (`array<atomic<u32>>`) I get a validation error. I'm not sure if this is how you're supposed to make an atomic array but the error didn't look right, so I tried it on windows with Vulkan. On windows, the atomics worked perfectly so I figured I should post a bug report. I can run some tests if you don't have access to a mac.

**Repro steps**
On macOS, m1 chip, metal backend

In shader.wgsl change
```rust
struct PrimeIndices {
    data: [[stride(4)]] array<u32>;
};
```
to
```rust
struct PrimeIndices {
    data: [[stride(4)]] array<atomic<u32>>;
};
```
and add `atomicAdd(&v_indices.data[global_id.x], 1u);` to the main function.

**Expected vs observed behaviour**
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
    Internal error: Metal: program_source:58:49: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
    uint _e6 = metal::atomic_fetch_add_explicit(&metal::uint(_e3) < 1 + (_buffer_sizes.size0 - 0 - 4) / 4 ? v_indices.data[_e3] : DefaultConstructible(), 1u, metal::memory_order_relaxed);
```

**Platform**
wgpu version 0.12

**Comment by kvark** [comment]
Looks like https://github.com/gfx-rs/naga/issues/1643, which got fixed in Naga master.
Would you be able to run your shader through Naga latest, or port your program to wgpu master?

**Comment by Ria8651** [comment]
Thanks, it works in master. Until the next release, I'll just process everything in a second dispatch.

**Comment by ciaochaos** [comment]
atomicExchange() and atomicCompareExchangeWeak() panic on Metal

`program_source:184:49: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
    uint _e33 = metal::atomic_exchange_explicit(&uint(_e30) < 1 + (_buffer_sizes.size4 - 0 - 4) / 4 ? springForceSrc[_e30] : DefaultConstructible(), 0u, metal::memory_order_relaxed);`
