### ISSUE TITLE
WGSL shader has inverted y when used directly or compiled to SPIR-V with naga

### ISSUE THREAD

**Issue by dbartussek** [gfx-rs/wgpu#2492]
**Description**
When using the exact same shader compiled with naga vs directly as WGSL, the y axis is inverted.

**Repro steps**
Simple shader, run with TriangleStrip topology and 4 vertices:
```
struct VertexOutput {
    [[builtin(position)]] position: vec4<f32>;
    [[location(0)]] tex_coords: vec2<f32>;
};

[[stage(vertex)]]
fn vertex([[builtin(vertex_index)]] vertex_index: u32) -> VertexOutput {
    var out: VertexOutput;
    let x = i32(vertex_index) / 2;
    let y = i32(vertex_index) % 2;
    let tc = vec2<f32>(
        f32(x),
        f32(y)
    );
    out.position = vec4<f32>(
        tc.x * 2.0 - 1.0,
        tc.y * 2.0 - 1.0,
        0.0, 1.0
    );
    out.tex_coords = tc;
    return out;
}

[[stage(fragment)]]
fn fragment(in: VertexOutput) -> [[location(0)]] vec4<f32> {
    return vec4<f32>(in.tex_coords.x, in.tex_coords.y, 0.0, 1.0);
}
```

**Expected vs observed behavior**
The shader should produce the same result when used directly or compiled to SPIR-V.

**Extra materials**
Result of using ShaderSource::Wgsl:
![wgsl](https://user-images.githubusercontent.com/39270698/154780657-942f95ea-d0da-414a-bd82-49c9bcad685c.png)

Result of using ShaderSource::SpirV:
![wgsl_spirv](https://user-images.githubusercontent.com/39270698/154780676-5b300617-686b-4d4a-a2fc-158939bef2b6.png)

**Platform**
Windows 10
Rust nightly
wgpu 0.12.0
naga 0.8.5

**Comment by cwfitzgerald** [comment]
On the cli it's --keep-coordinate-space
