### ISSUE TITLE
WGPUCommandBufferId vs. WGPUCommandEncoderId

### ISSUE THREAD

**Issue by DagAgren** [gfx-rs/wgpu#250]
Should this not be WGPUCommandEncoderId?

https://github.com/gfx-rs/wgpu/blob/32399cff8a0b55389f2d2493ea5c900c986c2547/ffi/wgpu.h#L647

**Comment by kvark** [comment]
You are correct, this should be the encoder ID. In our implementation today those are the same things, hence it works, but we should fix this code nevertheless.

**Comment by Napokue** [comment]
Does this apply for all of the following methods:
https://github.com/gfx-rs/wgpu/blob/32399cff8a0b55389f2d2493ea5c900c986c2547/ffi/wgpu.h#L647

https://github.com/gfx-rs/wgpu/blob/32399cff8a0b55389f2d2493ea5c900c986c2547/ffi/wgpu.h#L654

https://github.com/gfx-rs/wgpu/blob/32399cff8a0b55389f2d2493ea5c900c986c2547/ffi/wgpu.h#L659

https://github.com/gfx-rs/wgpu/blob/32399cff8a0b55389f2d2493ea5c900c986c2547/ffi/wgpu.h#L664

Or just for the `wgpu_command_buffer_copy_buffer_to_buffer`?

**Comment by kvark** [comment]
Yes, it applies to all of these
