### ISSUE TITLE
Vertex buffer is not rendered on DX12 WARP fallback.

### ISSUE THREAD

**Issue by FrankenApps** [gfx-rs/wgpu#2503]
**Description**
 I have a simple application that renders a cube. It runs fine on Metal, Vulkan and WebGL2. But when the fallback adapter is used on windows only the background is rendered and not the vertices inside the vertex buffer.

**Repro steps**
I have a pretty basic application I used for testing some stuff over [here](https://github.com/FrankenApps/wgpu_cube) that can be used to reproduce this. Just run it with `cargo run --release --features force_fallback` on Windows (I am using Windows 10).

I have also reproduced this using [learn-wgpu](https://github.com/sotrh/learn-wgpu/tree/master/code/intermediate/tutorial12-camera) (for example with tutorial 12), but not with the official wgpu examples. Therefore there is a very real possibility that this is not really an issue with wgpu, but after asking on matrix I was advised to report this.

**Expected vs observed behavior**
I would like to see a textured cube but am only seeing the window with the clear color.

**Extra materials**
Screenshots to help explain your problem: 
![screenshot](https://user-images.githubusercontent.com/17967303/155328638-c24dbf92-5337-41dd-9771-0ac4d865b4ce.png)

Renderdoc trace: 
[capture.rdc.zip](https://github.com/gfx-rs/wgpu/files/8124625/capture.rdc.zip)

**Platform**
Windows 10, wgpu `0.12` and `master.`

**Comment by cwfitzgerald** [comment]
Everything looks fine in renderdoc and PIX, but if I run it normally, I see nothing.

I don't have time right this second to report this to the microsoft directx discord, but here's the PIX file too, which should help.

[wgpu2503.zip](https://github.com/gfx-rs/wgpu/files/8128916/wgpu2503.zip)

**Comment by FrankenApps** [comment]
Yes, I forgot to mention that everything seems alright in renderdoc. In the meantime I was able to narrow this down a bit.

I ran different sections of the `learn-wgpu` tutorial and I found out that all worked up until [Tutorial 10 - Working with lights](https://sotrh.github.io/learn-wgpu/intermediate/tutorial10-lighting/#ray-path-tracing) where nothing is shown in the window anymore.

Therefore I suspect the problem is related to something in the shader that is added in this section.

**Comment by kvark** [comment]
Thank you for digging to the root of this! Please keep this open for tracking.
Next step for us would be reducing the test case and submitting a bug report to Microsoft.

**Comment by cwfitzgerald** [comment]
This is likely fixed with an updated WARP

**Comment by FrankenApps** [comment]
Can confirm that this now works on Window 11.
