### ISSUE TITLE
wgpu crashes on my hardware

### ISSUE THREAD

**Issue by dryluggage** [gfx-rs/wgpu#2514]
**Description**
Trying to run bevy with Backend=gl opens a window and then closes the window and panics results in an crash

**Repro steps**

type code:
use bevy::{prelude::*};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
		.run();
		}
in terminal run:
WGPU_BACKEND=gl cargo run

**Expected vs observed behavior**
it should run the code

crashes with this output in the terminal:
2022-02-27T13:31:36.620291Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2022-02-27T13:31:37.677330Z ERROR wgpu_hal::gles::egl: EGL 'eglCreateContext' code 0x3005: eglCreateContext    
thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!', /home/coffer/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.6.1/src/renderer/mod.rs:74:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Extra materials**

**Platform**
Arch Linux 5.16.11-arch1-1
Intel(R) Q45/Q43

**Comment by cwfitzgerald** [comment]
Unfortunately it crashes because your hardware doesn't support the version of opengl we need to run. It only supports gles2 and we need gles3.

**Comment by dryluggage** [comment]
will it ever support gles2?

**Comment by cwfitzgerald** [comment]
No, the way gles2 manages memory is basically completely incompatible with how wgpu does it. In a weird twist of fate, once we have a dx11 backend, you could run wgpu applications as your gpu does support FL10, which we will support.
