### ISSUE TITLE
Multiple passes not working in wasm on Chrome

### ISSUE THREAD

**Issue by gents83** [gfx-rs/wgpu#2517]
Hi guys,

I've ported my custom engine to use wgpu.

The engine works like this:
- First pass render 3D scene content (scene, object, mesh, textures, etc)
- Second pass is a UI pass that draw first pass content inside an image element of egui (in order to have a resizable viewport and support docking in future)

It works successfully on PC, but when using it in wasm on Chrome Canary it seems that multiple render passes are not working.
Code is available at: https://github.com/gents83/INOX/

Any known issue related to multiple render passes?

Note:
Using only 1 render pass and drawing directly to the screen works fine instead (on both platforms) - but that's not answering the question :)

**Comment by cwfitzgerald** [comment]
I don't know of any off the top of my head.

We seem to map renderpasses alright (https://github.com/gfx-rs/wgpu/blob/master/wgpu/src/backend/web.rs#L1963-L2042), at least by a quick check over, so I think you should head over and talk to the dawn people (their matrix: https://matrix.to/#/#webgpu-dawn:matrix.org)
