### ISSUE TITLE
Handle zero-range buffer bindings

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#253]
Relevant Vulkan message:
> VALIDATION [VUID-VkDescriptorBufferInfo-range-00341 (0)] : vkUpdateDescriptorSets() failed write update validation for Descriptor Set 0x101 with error: Write update to VkDescriptorSet 0x101 allocated with VkDescriptorSetLayout 0x6 binding #1 failed with error message: Attempted write update to buffer descriptor failed due to: VkDescriptorBufferInfo range is not VK_WHOLE_SIZE and is zero, which is not allowed.. The Vulkan spec states: If range is not equal to VK_WHOLE_SIZE, range must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorBufferInfo-range-00341)
object info: (type: DESCRIPTOR_SET, hndl: 257)

**Comment by GabrielMajeri** [comment]
Would it work to replace the `size: wgt::BufferSize` type on `BufferBinding`
https://github.com/gfx-rs/wgpu/blob/584468e34b4c25aab5a2bfa71796959baf504899/wgpu-core/src/binding_model.rs#L67-L70
with `wgt::NonZeroBufferAddress`?

This would break the API, but statically enforce non-zero-ness.

**Comment by kvark** [comment]
That's an interesting suggestion! The problem, however, is that 0 is not the only invalid value to provide there, so using type-level protection against 0 but not other invalid values seems inconsistent.
To clarify, the WebGPU group recently agreed to required that buffer bindings have to include the structure size defined in the buffer, plus a stride of an unbound array if the structure ends with one. That means that there is a shader-dictated "minimum buffer bindings size", and anything below that value is invalid to specify here. Users can optionally specify it in `GPUBindGroupLayoutEntry` for early validation.

All in all, I think the issue should now be closed in light of the "minimum buffer bindings size" changes. Instead, we need proper run-time validation for it (in a separate issue).
