### ISSUE TITLE
windows11 wsl2  Failed to set cursor

### ISSUE THREAD

**Issue by jaredzhou** [gfx-rs/wgpu#2532]
**Description**
run hello-triangle example error when mouse move out of the window, errors report appears:
[2022-03-10T02:20:50Z ERROR smithay_client_toolkit::window::fallback_frame] Failed to set cursor
**Repro steps**
in windows 11 wsl2 ubuntu run
cargo run --example hello-triangle
**Extra materials**
![image](https://user-images.githubusercontent.com/7837324/157576255-fa9c779c-6e95-4667-a3ec-58f9d915bd58.png)
![image](https://user-images.githubusercontent.com/7837324/157575868-078d85fc-4d8b-463b-acb2-ffc7cf3595af.png)

**Platform**
windows 11 wsl2 ubuntu

**Comment by cwfitzgerald** [comment]
This is an issue with winit or part of the wayland stack, nothing we can do about it from our end.
