### ISSUE TITLE
Request: Standalone examples

### ISSUE THREAD

**Issue by David-OConnor** [gfx-rs/wgpu#2536]
Currently, the [examples folder](https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples) is tightly integrated with the framework for running examples. This is presumably to faciliate running examples from the CLI, but makes learning WGPU syntax from examples tough. 

Eg, there's no (that I've found) `Cargo.toml` that lists the dependencies and their required frequencies, the examples require the `framework` file,  traits in the `framework` file are located somewhere else etc.

It would be nice to have examples you can copy + paste, and `Cargo.run`, as a basis for starting a WGPU-based program.

**Comment by kvark** [comment]
The README in the example folder states at the beginning:
> For the simplest examples without using any helping code (see framework.rs here), check out:
>    hello for printing adapter information
    hello-triangle for graphics and presentation
    hello-compute for pure computing

Is it difficult to just copy them out?

**Comment by David-OConnor** [comment]
Those don't use 3d graphics.

**Comment by kvark** [comment]
Mmm, you got me confused a bit. If you want to get a template for starting a new project - just take hello-triangle. If you need more features, look at the more complex examples to see how they are used. The example framework only helps with initialization anyway, it doesn't help with actual per-frame logic.

**Comment by David-OConnor** [comment]
Hello triangle is 2D; I'm describing a standalone 3D example.

**Comment by kvark** [comment]
I don't think there is a need for this. A full project can be seen as initialization + logic. The first part is clearly represented in hello-triangle, the second part is aplenty in the other examples. Fwiw, nothing about hello-triangle is "2D". It's all the same API, just not loading meshes or applying perspective transformations.

**Comment by Gordon-F** [comment]
> It would be nice to have an example that includes applying perspective transforms, camera movement, multiple objects to render etc at least, since you'll see those in any 3d project.

How about [learn-wgpu](https://sotrh.github.io/learn-wgpu/) project? It contains standalone example for camera movement, multiple objects rendering and etc.

**Comment by David-OConnor** [comment]
I've been learning using that tutorial. It's great, but its [Github](https://github.com/sotrh/learn-wgpu/tree/master/code/intermediate) still doesn't provide a MVP 3D example.

**Comment by cwfitzgerald** [comment]
I think something like this is fully in the purview of the learn-wgpu project more than our project as our examples have always been rather feature dense, and are there for testing wgpu as well as samples of the api. Every non-framework example increases our maintenance burden significantly and prevents us from integration testing it, so I'd be very hesitant to add another.
