### ISSUE TITLE
3D texture renders as random garbage when updated after creation (Metal)

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#2556]
**Description**
My application (which I am in the process of porting from another graphics API to `wgpu`) draws meshes which use a 3D texture atlas (for voxels) which is written to every frame. I found that performing any such texture updates (except immediately after creation) results in all textured areas having random flickers of garbage (varying per frame) and seemingly none of the written texels other than the initial ones appear correctly.

Since non-textured content displays correctly and I am not performing any animation remotely like the effect seen, I think that this is likely a wgpu/driver/GPU bug.

**Repro steps**
For now, I just have [this trace (56 MB exceeded GitHub's size limit)](https://drive.google.com/file/d/1tDdzddhQEbiU2wtHyRljz8Lb0c2f7Cup/view?usp=sharing). I'll be continuing to investigate, but @cwfitzgerald said that a trace would be sufficient.

**Expected vs observed behavior**
* Expected: a mostly static scene, with my various textures showing.
* Actual: all textures are randomly flickering garbage.

**Extra materials**

This is what I see when running the program that produced the above trace. The bottom half of the screen *should* be displaying a consistent repeating texture, but instead it shows the cyan that I initially filled my atlas texture with, plus various garbage. (In this case the garbage is colorful but it is often black and white.)

<img width="912" alt="image" src="https://user-images.githubusercontent.com/779501/159843603-44b386c5-ed86-45d6-a7e7-0c6e4107e10d.png">

On the other hand, when I replay the trace I captured in the wgpu player, the garbage looks different and the original cyan is mostly replaced with black. (Note: some of the content here is using vertex coloring, which is stably working as intended.)

<img width="912" alt="image" src="https://user-images.githubusercontent.com/779501/159842998-ed96f3b4-c54a-4241-8fa0-476c33cc3519.png">

I tried enabling Metal validation [running under Xcode](https://github.com/gfx-rs/wgpu/wiki/Debugging-with-Xcode) and [via `METAL_DEVICE_WRAPPER_TYPE=1`](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#metal), and didn't see any errors logged as a result of that.

**Platform**

* `wgpu` 0.12.0
* macOS 12.3 (21E230)
* Hardware:
    * Model Identifier: MacBookPro16,1
    * Processor Name: 8-Core Intel Core i9
    * GPU: AMD Radeon Pro 5500M

I'm planning to try on a different machine but have not gotten that set up yet.

**Comment by kpreid** [comment]
Not wgpu's fault; sorry for the noise, folks. This turns out to have been inside my own shader code — I forgot to copy some texturing-related vertex attributes to the fragment shader, so the fragment shader was effectively using uninitialized data as texture coordinates.

**Comment by kvark** [comment]
Interesting still. wgpu itself doesn't have a notion of "uninitialized data". Everything is cleared to zero at start.

**Comment by kpreid** [comment]
> wgpu itself doesn't have a notion of "uninitialized data". Everything is cleared to zero at start.

The WGSL looked roughly like this:

```rust
struct BlockVertex { ... }

struct VertexOutput {
    [[builtin(position)]] clip_position: vec4<f32>;
    [[location(0)]] color_or_texture: vec4<f32>;
    [[location(1)]] clamp_min: vec3<f32>;
    [[location(2)]] clamp_max: vec3<f32>;
};

[[stage(vertex)]]
fn vs_main(
    input: BlockVertex,
) -> VertexOutput {
    var out: VertexOutput;                                           // ← the problem!
    out.color_or_texture = input.color_or_texture;
    // TODO: projection matrix
    out.clip_position = vec4<f32>(input.position * vec3<f32>(0.05, 0.05, 0.01), 1.0);
    return out;
}

[[stage(fragment)]]
fn fs_main_opaque(in: VertexOutput) -> [[location(0)]] vec4<f32> {
        var texcoord: vec3<f32> =
            clamp(in.color_or_texture.xyz, in.clamp_min, in.clamp_max);
        return textureSampleLevel(block_texture, block_sampler, texcoord, 0.0);
}
```

So, none of the uninitialized data was the responsibility of `wgpu`'s CPU-side code; it was a variable inside the shader that only got partially initialized. Correcting/rejecting this program would require inserting zero-initialization in the shader code. I imagine that WebGPU might in fact want to specify that, though.
