### ISSUE TITLE
nvidia discrete card not selected with HighPerformance power preference

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#257]
Tested on: linux laptop, archlinux, with one integrated intel gpu, and one discreet nvidia gpu, and nvidia proprietary drivers (version 430.14)

## Issue

The nvidia gpu does not seem "selectable" when a `HighPerformance` power preference is used.

E.g., when I create an adapter via:

```rust
         let adapter = instance.get_adapter(&wgpu::AdapterDescriptor {
            power_preference: wgpu::PowerPreference::HighPerformance,
         });
```

I still receive the intel gpu, confirmed via debug log as well as via `nvidia-smi`:
```
[2019-07-24T03:16:40Z INFO  wgpu_native::instance] Adapter AdapterInfo { name: "Intel(R) HD Graphics 620 (Kaby Lake GT2)", vendor: 32902, device: 22806, device_type: IntegratedGpu }

m4b@efrit ::  [ ~ ] nvidia-smi
Tue Jul 23 20:17:20 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.14       Driver Version: 430.14       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 920MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8    N/A /  N/A |      0MiB /  2004MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

I'm definitely able to run stuff (opengl programs at least) on the nvidia discrete gpu, e.g., via `primusrun glxgears`:

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      8117      G   glxgears                                       2MiB |
|    0      8118      G   /usr/lib/Xorg                                  6MiB |
+-----------------------------------------------------------------------------+
```

I'm not even remotely an expert here, so selecting the nvidia gpu in a primusrun functionality may be out of scope for wgpu, I'm not sure. However, since:

1. `vulkaninfo` can detect and query the card
2. `nvidia-smi` can detect and query the card

I don't see any reason why wgpu can't detect and query the card, which it currently doesn't.

@kvark you mentioned some debugging, any suggestions on how to dig deeper as to why my nvidia card isn't selected?

### Resources

Primusrun: https://wiki.archlinux.org/index.php/Bumblebee#Primusrun
PRIME technology (haven't gotten this working): https://wiki.archlinux.org/index.php/PRIME
archlinux nvidia card information: https://wiki.archlinux.org/index.php/NVIDIA

**Comment by kvark** [comment]
@m4b thanks for filing this excellent bug report!

> @kvark you mentioned some debugging, any suggestions on how to dig deeper as to why my nvidia card isn't selected?

Break [here](https://github.com/gfx-rs/wgpu/blob/66eb63fe20a8b1949c39be58c239402d0510060d/wgpu-native/src/instance.rs#L221) and see? Shouldn't be too hard.

**Comment by m4b** [comment]
Ok, thanks for the excellent line to easily grab this info!

looks like it doesn't even see the discrete, it only loops once:

```
221	    let (mut integrated_first, mut discrete_first, mut discrete_last, mut alternative) =
(gdb) n
229	    for (i, adapter) in adapters.iter().enumerate() {
(gdb) 
231	            hal::adapter::DeviceType::IntegratedGpu => {
(gdb) p adapter
$1 = (*mut gfx_hal::adapter::Adapter<gfx_backend_vulkan::Backend>) 0x55555745d510
(gdb) n
232	                integrated_first = integrated_first.or(Some(i));
(gdb) 
230	        match adapter.info.device_type {
(gdb) 
229	    for (i, adapter) in adapters.iter().enumerate() {
(gdb) 
244	        PowerPreference::LowPower => integrated_first.or(discrete_last),
(gdb) n
246	            discrete_first.or(integrated_first)
(gdb) 
250	    let selected = preferred_gpu
(gdb) p integrated_first
$2 = core::option::Option<usize>::Some(0)
(gdb) p discrete_first
$3 = core::option::Option<usize>::None
```

**Comment by kvark** [comment]
Could you print the `adapters` out?

**Comment by m4b** [comment]
As expected, single element in the vec:
```
ADAPTERS: [Adapter { info: AdapterInfo { name: "Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) ", vendor: 32902, device: 0, device_type: IntegratedGpu }, physical_device: PhysicalDevice(0x558847bee810@ThreadId(1)), queue_families: [QueueFamily] }]
```

**Comment by kvark** [comment]
@m4b is this still an issue?

**Comment by jon-chuang** [comment]
I am experiencing this issue on Ryzen 4800H and NVIDIA gtx 1650
```
AdapterInfo { name: "AMD RADV RENOIR (LLVM 10.0.0)", vendor: 4098, device: 5686, device_type: IntegratedGpu, backend: Vulkan }
```

**Comment by kvark** [comment]
@jon-chuang do you have Vulkan drivers for the NV card in your machine? Is it visible in `vulkaninfo`?

**Comment by kaimast** [comment]
I think I also have this issue with the nvidia 460 drivers. I am pretty sure they support vulkan but for some reason `vulkaninfo` does not work.

```
❯ vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
error: XDG_RUNTIME_DIR not set in the environment.
ERROR at /build/vulkan-tools-jYkto9/vulkan-tools-1.2.141.0+dfsg1/vulkaninfo/vulkaninfo.h:240:vkGetPhysicalDeviceSurfaceFormats2KHR failed with ERROR_INITIALIZATION_FAILED
```

**Comment by kvark** [comment]
@kaimast something is seriously messed up with your configuration, it seems. The loader is trying to use the 32-bit drivers?

**Comment by kaimast** [comment]
> @kaimast something is seriously messed up with your configuration, it seems. The loader is trying to use the 32-bit drivers?

Sorry for replying so late to this.

I think it triggers some Wayland bug for me. Vulkaninfo and vkcube work fine under X11 and so does my wgpu application.
This used to work fine though, maybe it always fell back to Intel and I did not notice.

**Comment by cwfitzgerald** [comment]
I'm going to close this as out of scope for now, if you feel like there is some additional logic we need, please feel free to ask to re-open.

**Comment by kaimast** [comment]
Retried this with the newest (465) Nvidia linux driver and still got this problem. However I noticed the following:

If you select LowPower GPU in wgpu and set the DRI_PRIME environment variable to 1, wgpu will offload rendering to the NVIDIA GPU.
