### ISSUE TITLE
Updating ash to 0.37 breaks Firefox

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#2580]
#2557 updated wgpu-hal to Ash 0.37, which requires Rust 1.59. Unfortunately, Firefox is still using Rust 1.57 for builds.

I'll investigate when Mozilla plans to bring Firefox forward to 1.59. But we urgently need the fixes in #2567 and #2565, so it would be very helpful if we could back out #2557 for the time being.

**Comment by jimblandy** [comment]
It seems like Firefox might be willing to move their MSRV forward to 1.59.

**Comment by kvark** [comment]
Interesting. Last time I checked Firefox kept going just 2 weeks behind the latest stable. But 1.57 is the whole 12 weeks behind.

**Comment by jimblandy** [comment]
All sorted out - Firefox now requires 1.59.
