### ISSUE TITLE
Way to recover the `Extent3D` of a `Texture` after creation

### ISSUE THREAD

**Issue by kneasle** [gfx-rs/wgpu#2581]
Currently, there seems to be no way to access the size/`Extent3D` of a `Texture` after initialisation.  This information is clearly stored somewhere, because wgpu is able to perform validity checks on things like texture copying.  Ideally, we'd just be able to access the size with e.g. `let extent: wgpu::Extent3D = texture.extent()` if `texture: wgpu::Texture`.

### Context

One of my current projects (a GPU-powered image editor) spends a lot of time handling textures of different sizes and therefore needs to know access texture sizes after creation.  My current solution is to create a struct `SizedTexture` like (actual code [here](https://github.com/kneasle/4th-year-proj/blob/master/src/utils.rs#L67-L103)):

```rust
/// A [`wgpu::Texture`] which keeps a record of its dimensions (I'm not really sure why wgpu
/// doesn't give us access to this.  Maybe there's a way that I don't know about - @kneasle).
#[derive(Debug)]
pub struct SizedTexture {
    tex: wgpu::Texture,
    size: wgpu::Extent3d,
}

impl std::ops::Deref for SizedTexture {
    type Target = wgpu::Texture;

    fn deref(&self) -> &wgpu::Texture {
        &self.tex
    }
}
```

This turns out to be so useful that the code never uses `Texture`s directly (only through a `SizedTexture`).  This is a non-ideal solution, because the indirection/`Deref` magic makes the code more complex and difficult to understand.  It would be much better if we could recover the size with something like `fn Texture::extent(&self) -> Extent3D`.

I can't be the only person to want to do stuff like this, so if there's a way to do this already then please let me know (if there _is_ a way to do this, we should definitely make it easier to find).  Otherwise, I'd be very happy to implement this :)

**Comment by cwfitzgerald** [comment]
Thanks for filing. This is mainly a question about WebGPU's willingness to expose such information. The group have been intentionally conservative to prevent backwards compat issues if some couldn't be provided. I feel like theres a webgpu issue somewhere, but I couldn't immediately find it.

**Comment by kneasle** [comment]
I figured that future compatibility might be the issue.  But equally you can store the `Extent3D` directly in the `Texture` struct on creation, and I can't see how you could ever end up in a situation where that information is invalid - why on earth would a backend try to change the texture size?

I guess this would also make `wgpu` diverge from WebGPU's spec, which I can understand isn't especially desirable.  But `wgpu` is a generally very streamlined experience, and this stands out as a source of development friction.

**Comment by cwfitzgerald** [comment]
Upstream issues are here: https://github.com/gpuweb/gpuweb/issues/1497, https://github.com/gpuweb/gpuweb/issues/1498

It's not if the information is invalid, it's if the data is stored at all. On WebGPU, the information would need to be stored in the browser thread as part of the JS object. Right now the information is likely stored by the implementation for validation purposes, but it is stored in the GPU thread.

For things like this, we really want to keep aligned with the spec because we want to facilitate people writing portable code and this would be one of the first traps people would hit.

**Comment by kneasle** [comment]
OK this makes sense - I would be genuinely surprised if I were the first person to want to do something like this.  I'm happy to defer to the WebGPU folks on API design - they're the ones doing the legwork and the API is very nice so far.

I'll stick with the slightly hacky `SizedTexture` for now - I'd like to see it included at some point, but I appreciate having a consistent API (it makes sense either expose all the information or keep it all hidden).  I'll close this issue, since people can still find this and be directed to the upstream issues.

**Comment by cwfitzgerald** [comment]
You most definitely aren't the first person to hit this, and I think WebGPU does want to expose these things, but needs to figure out what subset to actually expose.
