### ISSUE TITLE
Instance creation will panic if wrong backend is selected

### ISSUE THREAD

**Issue by bmcpt** [gfx-rs/wgpu#2587]
**Description**
An attempt to initialize wgpu with wrong backend will cause a crash. In contrast vulkan sdk returns an error code if something goes wrong. It would be better if wgpu did the same.

**Repro steps**
Run this on an android device:

        let instance = wgpu::Instance::new(wgpu::Backends::DX12);

I have a question related to this issue:

        let instance = wgpu::Instance::new(wgpu::Backends::VULKAN | wgpu::Backends::GL);

On android, I expect this line of code to initialize wgpu with vulkan if it is available, or with opengl if not. Is that what it will do?

**Comment by kvark** [comment]
What kind of crash? What's the error message, the call stack, etc?

**Comment by bmcpt** [comment]
Sorry, it's the request_adapter call that fails (with a result).
