### ISSUE TITLE
Custom error handler for wgpu errors

### ISSUE THREAD

**Issue by bmcpt** [gfx-rs/wgpu#2588]
**Description**
Uniform arrays in a shader have to be statically sized. The suggested method of using dynamically sized arrays is to declare the array size to be very large and pass the actual size in another uniform:

https://computergraphics.stackexchange.com/questions/5323/dynamic-array-in-glsl

But when I tried doing that, the program crashed with this error:

```
2022-04-10T13:10:45.365Z ERROR [wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `Render Encoder`
    In a draw command, indexed:false indirect:false
      note: render pipeline = `main pipeline`
    Buffer is bound with size 64 where the shader expects 524280 in group[0] compact index 0
```

The first line suggests that it's possible to configure wgsl to not abort on error. How do I do that? Is there any other better way of using dynamic uniform arrays in wgsl?

**Comment by kvark** [comment]
This is a validation error. If you handle it yourself, you can avoid the panic, but it will still not work or do anything useful (since it's an error).

Do you need uniform buffers specifically? Unsized storage buffers seem to fit this case much better.

**Comment by bmcpt** [comment]
> This is a validation error. If you handle it yourself, you can avoid the panic,

How do I do that?

> Do you need uniform buffers specifically? Unsized storage buffers seem to fit this case much better.

I started with storage buffers, but they are a downlevel feature and don't work with opengl on my fairly recent android device.

**Comment by bmcpt** [comment]
I need to access some array data from vertex buffers.

**Comment by kvark** [comment]
https://wgpu.rs/doc/wgpu/struct.Device.html#method.on_uncaptured_error allows you to set a handler. But as I said, it's not going to be useful for your case.

Your fairly recent Android device doesn't support Vulkan? That's unfortunate.
Another way for you could be placing data in textures.

**Comment by bmcpt** [comment]
> Another way for you could be placing data in textures

Thanks.
