### ISSUE TITLE
Some llvmpipe versions don't like 'shadow' example

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#2594]
Because `.github/workflows/ci.yaml` pulls the latest `llvmpipe` from `ppa:oibaf/graphics-drivers`, the specific version of llvmpipe we get varies from day to day, and when we happen to get a buggy version, we get CI failures that have nothing to do with the PR in question.

We should instead pull a specific known-good (or known-adequate) version of LLVM pipe to run our CI tests against.

**Comment by cwfitzgerald** [comment]
As of #3873 we are back on lavapipe/llvmpipe, but are using a "mesa release" ppa as opposed to "mesa trunk" now, so we should be further insolated to these.
