### ISSUE TITLE
 App sometimes takes 5 to 10 second to start

### ISSUE THREAD

**Issue by oknozor** [gfx-rs/wgpu#2596]
I am copy pasting https://github.com/iced-rs/iced/issues/1300 here, at first I thought it was a iced specific issue but I am getting the same behavior from wgpu's example. 

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When I launch any iced app either in release or debug mode it can take up to 10 seconds to show up. 
This is random and sometimes does not happen at all. I have not been able to reproduce on other laptops.

At first I thought it was related to the app I am writing but I am getting the same result with the Pokedex example. 

I tried to change the wgpu backend like so : `WGPU_BACKEND=vulkan onagre`, `WGPU_BACKEND=gl onagre`  without success. 

**Hardware :**
- MSI bravo 15
- 03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c1)
- 07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev *c7)

**Drivers :** 
- mesa 21.3.7-2
- vulkan-radeon 21.3.7-2

I'd be curious to know if people with the same hardware experience the same issue. Also does this belongs in wgpu's repo ? 
 

### What is the expected behavior?

Iced apps should start faster.

### Version

0.3.0

### Operative System

Linux

### Do you have any log output?

The application hangs at the last line of these logs : https://gist.github.com/oknozor/024a8baa43466b1bf5d9b9d19fa8d0f7

And continue with the following: https://gist.github.com/oknozor/8a55d64df7a77f347454d7dc379cfde0

**Comment by kvark** [comment]
Running through a sampling profiler should give an idea about where the time is spent.

**Comment by oknozor** [comment]
Can you give specific instruction on how to do that ?

**Comment by kvark** [comment]
https://perf.wiki.kernel.org/index.php/Main_Page should be a good start. I don't think it's worth doing a walkthrough right here. Maybe jump on our Matrix rooms to follow up if you get any issues?

**Comment by oknozor** [comment]
Here is a flamegraph : 

![flamegraph](https://user-images.githubusercontent.com/24563836/165708763-cfa9f9b9-efac-4fe2-9702-f890be0ae698.svg)

And the perf folded stack : https://gist.github.com/oknozor/47a742a81dd1836f995994193061739f

**Comment by oknozor** [comment]
Any updates ? Is there anything more I can do to help ?

**Comment by cwfitzgerald** [comment]
Closing as stale with not a lot we can actually do here.
