### ISSUE TITLE
Panic on 0-sized uniform

### ISSUE THREAD

**Issue by kneasle** [gfx-rs/wgpu#2597]
### Description

`wgpu` panics when creating a 0-sized uniform.  It feels like this should be a validation error rather than a panic with no message.

### Reproduction Example

```rust
fn main() {
    let instance = wgpu::Instance::new(wgpu::Backends::all());
    let adapter =
        pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptionsBase::default()))
            .unwrap();
    let (device, _queue) =
        pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor::default(), None))
            .unwrap();

    device.create_shader_module(&wgpu::ShaderModuleDescriptor {
        label: None,
        source: wgpu::ShaderSource::Wgsl(
            "
struct Uniforms {};

[[group(0), binding(0)]]
var<uniform> uniforms: Uniforms;
            "
            .into(),
        ),
    });
}
```

When run, this panics with:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/kneasle/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.12.2/src/validation.rs:896:61
```

That specific line of code has moved, but the two `unwraps` are now [here](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/validation.rs#L875) and [here](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/validation.rs#L888).

Here's a zip with the example: [wgpu-0-sized-uniform.zip](https://github.com/gfx-rs/wgpu/files/8491064/wgpu-0-sized-uniform.zip)

---

Thanks very much for an otherwise stable library, by the way!  It's easily the nicest way of handling GPUs I've found.

**Comment by kneasle** [comment]
I'm happy to make a PR for this if someone could point me to how the validation error handling works

**Comment by cwfitzgerald** [comment]
Thanks for filing!

As of https://github.com/gfx-rs/naga/pull/1826 (1 hour ago!), this is now a naga validation error so this code will never be hit.

**Comment by kneasle** [comment]
Ayy nice - you guys are so on it!
