### ISSUE TITLE
How to build for iOS?

### ISSUE THREAD

**Issue by DagAgren** [gfx-rs/wgpu#260]
I see references to people getting wgpu to build for iOS, but I am failing to figure out how.

I am trying to build a static library for wgpu, then building a project in Xcode that uses C and Swift, and linking it against the static library. I have this working for macOS.

What I have tried so far:

1. "cargo lipo" - fails because of a bug in cargo-lipo: https://github.com/TimNN/cargo-lipo/issues/32
2. Applied this PR to cargo-lipo to fix the bug: https://github.com/TimNN/cargo-lipo/pull/30 - Now  libwgpu_native.a does build (with a warning about cdylib not being supported but this does not seem to matter, since I don't want a dylib).
3. Building for simulator on Xcode 10 does not work due to Metal not being supported, this is expected.
4. Building for simulator on Xcode 11 does not work and gives hundreds of warnings like "ld: warning: building for iOS Simulator, but linking in object file (/.../libwgpu_native.a(wgpu_native.23kem15cwy8kmrf8.rcgu.o)) built for", and then fails to link the wgpu symbols.
5. Building for device on Xcode 10 or 11 gives this error: "ignoring file libwgpu_native.a, file was built for archive which is not the architecture being linked (arm64)", and then every wgpu symbol is not found.
6. I tried taking the .a files apart and re-building them with ar, but that changes nothing.
7. I also tried taking just the arm64 .a file before lipo combines it into a fat library along with x86_64, but that also fixes nothing.

Any hints what I should be trying?

**Comment by grenlight** [comment]
Latest ```gfx-backend-metal``` 0.2.3 can not build on ```--target x86_64-apple-ios```, because iPhoneSimulator use the macOS's metal, not ```iPhoneSimulator.platform/usr/bin/metal```, related error:

```
error: failed to run custom build command for `gfx-backend-metal v0.2.3`

Caused by:
  process didn't exit successfully: `xxx/target/debug/build/gfx-backend-metal-17fc808e758b981d/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=/Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.2.3/shaders
cargo:rerun-if-changed=/Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.2.3/shaders/blit.metal

--- stderr
error: cannot execute tool '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin/metal'
thread 'main' panicked at 'shader compilation failed', /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.2.3/build.rs:69:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:408
   6: build_script_build::main
             at ./build.rs:69
   7: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
```

use ```cargo build --target aarch64-apple-ios --features metal``` can  build ```staticlib``` for iOS device, and on Xcode project's ```Build Settings``` tab add ```-lc++``` to ```other linker flags```

**Comment by grenlight** [comment]
gfx was fixed this issue on master branch [xcode11 supports metal on ios simulators](https://github.com/gfx-rs/gfx/pull/2873)

**Comment by seivan** [comment]
I've gotten wgpu to work on `iOS` on device using my own SDL2 bindings. It also work with existing `Rust-SDL`. 

That being said, I am not building a binary to run on the device directly - instead I embed it within a Xcode project as a static lib. 

I haven't touched Xcode 11 (and the new simulators) yet though.

**Comment by DagAgren** [comment]
@seivan I take it you are doing all your logic in Rust and then building the whole thing as a static lib?

I am trying to build just the native wgpu library and do my logic in C instead, which I am struggling to make work.

**Comment by Napokue** [comment]
Hi @DagAgren !

We recently launched our first draft of a [Getting Started](https://github.com/gfx-rs/wgpu/wiki/Getting-Started). It's nowhere near complete, but there you can find how to generate the headers and the static library. 

You can also take a look at the [examples](https://github.com/gfx-rs/wgpu/tree/master/examples) folder. 

I hope this will be sufficient for you now, otherwise you can always ask us either here in a comment or on our [Gitter](https://gitter.im/gfx-rs/webgpu)!

**Comment by DagAgren** [comment]
I have generated a static library, as I posted above, it works fine on macOS. The problem here is cross-compiling for iOS.

**Comment by DagAgren** [comment]
Latest discovery: Trying to build with this command line fails:


```    IPHONEOS_DEPLOYMENT_TARGET=10.3 cargo build --target aarch64-apple-ios --release --features "local gfx-backend-metal"

It seems to fail because some part of the build is trying to build using a macOS toolchain instead of iOS:

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.0.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.1.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.10.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.11.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.12.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.2.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.3.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.4.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.5.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.6.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.7.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.8.rcgu.o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.build_script_build.d4nublvl-cgu.9.rcgu.o" "-o" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832" "/Users/dag/Code/wgpu/target/release/build/failure_derive-5b285aa0740a5832/build_script_build-5b285aa0740a5832.19rk5xwoz6f2j0wl.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/dag/Code/wgpu/target/release/deps" "-L" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-f82c0a9772c4e2d7.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-20a65d310acebd43.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-212cc06e5020f729.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-a87c7ef368fefef0.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-48969ef6c8844944.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-1c73d9e90218204e.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-f50a1231cc9f1267.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-cf45bae2f464a64c.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-86d96dfff3061cfd.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-9eca447bd9f984a8.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-5bcecb35195cda38.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-bbf1821b401c61a5.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-b5e7b61ba6096de6.rlib" "/Users/dag/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-378dddda86e1fac1.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
          ld: warning: URGENT: -ios_version_min is invalid for architecture x86/x86_64, inferring -iosmac_version_min. This will be an error in the future.
          ld: iosmac platform version must be at least 12.0
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error```

**Comment by DagAgren** [comment]
Removing the `IPHONEOS_DEPLOYMENT_TARGET=10.3` from the command makes the build succeed, but the resulting .a file will not contain some wgpu symbols.

For instance, `nm -gC target/aarch64-apple-ios/release/libwgpu_native.a | grep _wgpu_device_create` will show nothing.

**Comment by DagAgren** [comment]
`IPHONEOS_DEPLOYMENT_TARGET=10.3 cargo build --target aarch64-apple-ios --release --features "local gfx-backend-metal" 2>&1 | grep "Could not compile"` outputs this:

```
error: Could not compile libc.
error: Could not compile syn.
error: Could not compile proc-macro2.
error: Could not compile byteorder.
```

So apparently those four dependencies aren't crosscompiling correctly?

**Comment by grenlight** [comment]
I created a repo can run on macOS and iOS correctly: [ real time SDF calculate and rendering](https://github.com/grenlight/sdf-text-view)

**Comment by kvark** [comment]
@DagAgren is this resolved? Could you in this case write down the conclusion and close it? Thanks!

**Comment by DagAgren** [comment]
It partly is, but not entirely. I managed to build using this command line: 

    cargo build --target aarch64-apple-ios --manifest-path wgpu-native/Cargo.toml --features "local,gfx-backend-metal"

However, specifying the iOS version with IPHONEOS_DEPLOYMENT_TARGET=10.3 still does not work, since some dependencies seem to build native code for some reason, and that option is passed in to those builds too, which breaks them.

Didn't attempt getting a universal build yet.

**Comment by kvark** [comment]
@DagAgren what's the state of things now? Is this still a problem, and if so, do we have a plan on how to address this?
