### ISSUE TITLE
Start documentation Wgpu

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/wgpu#262]
This issue is for the start of the documentation I'm planning to create for wgpu. Kvark already made a Wiki page on this repository. Unfortunately there isn't a fork available for a Wiki, so I'll create this Wiki first on my fork. Which can be found [here](https://github.com/Napokue/wgpu/wiki).

Issue will be completed after the following topics are described:
- Windows setup instructions
- Generating header files
- Generating static library
- Running an example

I don't have a macOS enviroment, nor a Linux environment, so I wouldn't be able to document them.

With these basics described, and hopefully macOS and Linux setup instructions too, newcomers can start easier.

For those who are reading this, let me know down in the comment section what other topics would've been golden if they would've been documentated when you were starting out.

**Comment by kvark** [comment]
@Napokue thank you for the amazing work!
Please just move the wiki to this repo. I added you to the Explainers team, so you should be able to modify the wiki. Ping us whenever anything is a concern that needs reviewing.

**Comment by Napokue** [comment]
Alright, definitely doing that! And I also will need help from you guys!

**Comment by GabrielMajeri** [comment]
Would a better idea be to use GitHub Pages for hosting the documentation? That way, the docs could be written as Markdown files and stored in a `docs` folder in the repo. It wouldn't limit contributions to the docs only for people who have wiki access.

**Comment by kvark** [comment]
We'll be happy to grant access to wiki for anyone who is willing to contribute. Historically, the debate over github versus wiki shows up quite often. My preferences is to go with a wiki because it introduces less friction to write some thing down. Doing the regular PR workflow is just sometimes too cumbersome.

See also - https://github.com/rust-gamedev/wg/pull/63#issuecomment-542836575

**Comment by Napokue** [comment]
I have only worked with the wiki so far, so I cannot speak about the GitHub Pages. 

I will make some time next week to finish the "Setting up GLFW 3" for Windows. The first draft of the wiki (Windows only) will then be finished. This issue could be considered closed after that?

**Comment by Napokue** [comment]
Removed the "Setting up GLFW 3" section, so we can call this current wiki the first version. Also updated the make commands from "make example-xxx" to "make run-example-xxx". 

Issue will be closed.
