### ISSUE TITLE
[Investigation] DX11 examples not working correctly

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/wgpu#263]
When inputting `[1, 2, 3, 4]` into the compute example. It has to output `[0, 1, 7, 2]`. This works for Vulkan and DX12 (I couldn't test Metal). DX11 however, outputs `[1, 2, 3, 4]` also mentioned in issue https://github.com/gfx-rs/wgpu-rs/issues/47. 

I have tested the compute examples in Wgpu-rs, Wgpu, and Gfx. Both Wgpu-rs and Wgpu are outputting `[1, 2, 3, 4]` when using DX11, but Gfx is correctly outputting `[0, 1, 7, 2]` for DX11, DX12, and Vulkan.

I will investigate and fix this.

**Comment by kvark** [comment]
I took a look at the cube example on dx11, and it's not working either. I think the memory management needs to be refined there, but I haven't got all the details. TL;DR: this might not be an isolated bug in DX11 but rather a chunk of logic missing.

**Comment by cwfitzgerald** [comment]
As of the latest gfx-backend-dx11 release, all the wgpu examples should work correctly on dx11 🎉
