### ISSUE TITLE
`wgpu` should let app wait until `SurfaceTexture` presentation is complete

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#2650]
**Is your feature request related to a problem? Please describe.**
There's no way to tell when a particular `SurfaceTexture` is done being presented. This makes it hard for programs to match the frame rate of the swapchain.

**Describe the solution you'd like**
wgpu should offer a blocking function or future so that the user can wait until it's worth rendering another frame.

**Describe alternatives you've considered**
The examples hard-code 60Hz, which is unsatisfying. You could present as fast as possible, but in Mailbox mode this will use the full CPU.

**Additional context**
Possibly relevant:
- #1451
- #421
- #932

**Comment by cwfitzgerald** [comment]
Is this covered by #2700?

**Comment by jimblandy** [comment]
No, that doesn't have any interaction with presentation that I'm aware of. Surface texture::present doesn't return a Submission index.

Also, what (I think) we want to know is, when has a texture been presented, or perhaps, when is it done being presented? Neither of those correspond to queue activity.

**Comment by cwfitzgerald** [comment]
Superseded by 2869

**Comment by EriKWDev** [comment]
clickable: #2869
