### ISSUE TITLE
Cant use indirect buffer

### ISSUE THREAD

**Issue by pwouik** [gfx-rs/wgpu#2680]
**Description**
It seems that I cant put both indirect and storage usage
`usage: wgpu::BufferUsages::INDIRECT | wgpu::BufferUsages::STORAGE,`
I get
buffer usage is STORAGE which does not contain required usage INDIRECT

I need that to write an indirect buffer in a shader

**Repro steps**
create a buffer with wgpu::BufferUsages::INDIRECT | wgpu::BufferUsages::STORAGE
use a storage binding type in a BindGroupLayout:`wgpu::BufferBindingType::Storage `
use multidrawindirect with the buffer

**Platform**
wgpu 0.12, Archlinux vulkan backend

**Comment by pwouik** [comment]
I tried a buffer copy as a workaround but even with only indirect usage it say it's a storage buffer (but doesn't work in a bind group)

**Comment by kvark** [comment]
Do you have some code to run that reproduces the issue?

**Comment by pwouik** [comment]
https://github.com/pwouik/rust_voxel_engine/blob/bfc2556514a8a49594c5261cb5caf19f7324630a/src/chunk_renderer.rs#L155-L170
where I define the buffers

https://github.com/pwouik/rust_voxel_engine/blob/bfc2556514a8a49594c5261cb5caf19f7324630a/src/chunk_renderer.rs#L504
MDI call

the rest of the code probably doesn't work, I was completely rewriting the renderer

**Comment by cwfitzgerald** [comment]
Your problem is here: https://github.com/pwouik/rust_voxel_engine/blob/bfc2556514a8a49594c5261cb5caf19f7324630a/src/chunk_renderer.rs#L152 this is the count buffer but it only has a storage usage, not an indirect usage.

**Comment by pwouik** [comment]
thank you
