### ISSUE TITLE
wgpu doesn't render with alpha channels

### ISSUE THREAD

**Issue by joohei** [gfx-rs/wgpu#2682]
I am trying to render a semi-transparent png-image with wgpu. I have an issue where some of the pixels that shouldn't be showing are showing. For example in the left of my image there is a gray (128, 128, 128) block, which has alpha value of 0, which means that it should be invisible, correct? I have set texture format to Rgba8UnormSrgb:

![image](https://user-images.githubusercontent.com/99501993/169669593-45de5a9f-2c23-4501-9d95-009cb1b1a51f.png)

Here is the png image and the jpg equivalent, which is what wgpu is rendering. 
![image](https://user-images.githubusercontent.com/99501993/169669616-f3386235-73d3-45b8-9415-003c480f686f.png)
![image](https://user-images.githubusercontent.com/99501993/169669627-cdabd091-6886-43cd-b6f5-2c110d7b44d1.png)

**Comment by kpreid** [comment]
The interpretation of an image's alpha channel depends on the render pipeline's `BlendState`. The results you're showing suggest that you haven't configured it to use the alpha for blending, so it's copying the RGB channels without interpreting alpha. (Note that besides the gray area, the edges of the rainbow also are not properly antialiased.)

 Try changing the blend state from whatever it currently is to `wgpu::BlendState::ALPHA_BLENDING`.

**Comment by joohei** [comment]
> The interpretation of an image's alpha channel depends on the render pipeline's `BlendState`. The results you're showing suggest that you haven't configured it to use the alpha for blending, so it's copying the RGB channels without interpreting alpha. (Note that besides the gray area, the edges of the rainbow also are not properly antialiased.)
> 
> Try changing the blend state from whatever it currently is to `wgpu::BlendState::ALPHA_BLENDING`.

Yes that totally fixed it. Thank you for your quick reply!
