### ISSUE TITLE
Running example 9 will not validate...

### ISSUE THREAD

**Issue by gschian0** [gfx-rs/wgpu#2696]
Running Example WGPU09... I get this error

`  Compiling wgpu_project v0.1.0 (C:\Users\GennaroSchiano\Documents\GitHub\wgpu-step-by-step\wgpu09)
    Finished dev [unoptimized + debuginfo] target(s) in 2.45s
     Running `target\debug\wgpu_project.exe`
[2022-05-27T02:22:22Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    error matching FRAGMENT shader requirements against the pipeline
    shader global ResourceBinding { group: 0, binding: 1 } is not available in the layout pipeline layout
    binding is missing from the pipeline layout`

windows 10
NVIDIA GEFORCE RTX3070 Laptop

any help would be apprectiated!  I just purchased the webgpu and rust book... looking forward to learning more!

Bless,
Gennaro

**Comment by cwfitzgerald** [comment]
I don't know that tutorial at all, but if you share your source, we can better help you

**Comment by CatCode79** [comment]
By any chance are you referring to this repository?
https://github.com/jack1232/wgpu-step-by-step

This is the official wgpu graphics api repo.

**Comment by cwfitzgerald** [comment]
Closing as stale - if there's anything else we can help you with, please refile an issue or open a discussion.
