### ISSUE TITLE
Rejection of WGSL compute shaders with no buffer usage

### ISSUE THREAD

**Issue by hanawatson** [gfx-rs/wgpu#2701]
**Description**
Not sure if this is expected behavior (and if so, it doesn't appear to be documented) but wgpu rejects WGSL compute shaders that do not make use of any input/output/storage buffers.

**Repro steps**
WGSL example to run through wgpu:
```
@stage(compute) @workgroup_size(1)
fn main() {
    var var0 = 0;
}
```

**Expected vs observed behavior**
Expected behavior: acceptance and execution of the compute shader
Observed behavior: thrown error message:
```
        The application panicked (crashed).
        Message:  Error reflecting bind group 0: invalid group index 0
        Location: wgpu/src/backend/direct.rs:1796
```

**Extra materials**
None, but happy to provide any more if needed.

**Platform**
cargo 1.60.0, wgpu v0.12.0, Mesa Intel(R) UHD Graphics 620 (KBL GT2) (renderer version 21.3.8), Vulkan backend, Kali Linux

**Comment by jinleili** [comment]
Verified by vk and metal backend on master, this issue is gone

**Comment by cwfitzgerald** [comment]
Nice
