### ISSUE TITLE
Clarify relationship with gfx-rs and web technologies

### ISSUE THREAD

**Issue by duane** [gfx-rs/wgpu#2709]
**Is your feature request related to a problem? Please describe.**

No. This should only affect the readme.

**Describe the solution you'd like**

It's not clear what relationship gfx-rs have aside from gfx-rs being deprecated in favor of the latter. I was very confused about this and would have expected some rationale *until* I discovered that the wgpu work is intended to address other platforms than browsers. Why was this transition necessary, and why is it named "wgpu" if the "w" does not stand for "web"?

**Describe alternatives you've considered**

gfx-rs appears to be in maintenance mode, and there are no other clear alternatives to this approach to GPU access.

**Additional context**

Been out of the loop for a few years. I was surprised to find gfx-rs deprecated in favor of some web-oriented thing. A little more context for the relationship between the two, or the meaning of the name, would be appreciated.

**Comment by cwfitzgerald** [comment]
Thanks for filling! 

https://github.com/gfx-rs/gfx/discussions/3768 is the issue about the depreciation of gfx-hal in exchange for wgpu, which is mentioned in the depreciation betting in the Readme. 

`wgpu` doesn't stand for anything formally, but yes it's just shortening webgpu. Not the best name, but too late to change it now. I've tried to compensate for this by emphasizing in the Readme how we're a cross platform api first, an implementation of webgpu serving. 

Is there something in particular that you would like to see added to the Readme?

**Comment by cwfitzgerald** [comment]
Closing as stale - if there is anything else that we can add, please feel free to re-open this or file a new issue/discussion.
