### ISSUE TITLE
WASM, buffer_future panics after commit 32af4f5 in example hello-compute

### ISSUE THREAD

**Issue by TimothyBergstrom** [gfx-rs/wgpu#2715]
**Description**

I have some issues when running webgpu for wasm32-unknown-unknown after the commit 32af4f56079fd2203c46c9c452cfe33fd60a5721. In commit 8063edc6482cfc828895ec0feaa446767fecc510, it works fine

I tested the "wgpu/examples/hello-compute/main.rs"

```
// Note that we're not calling `.await` here.
let buffer_slice = staging_buffer.slice(..);
// Sets the buffer up for mapping, sending over the result of the mapping back to us when it is finished.
let (sender, receiver) = futures_intrusive::channel::shared::oneshot_channel();
buffer_slice.map_async(wgpu::MapMode::Read, move |v| sender.send(v).unwrap());

// Poll the device in a blocking manner so that our future resolves.
// In an actual application, `device.poll(...)` should
// be called in an event loop or on another thread.
device.poll(wgpu::Maintain::Wait);

// Awaits until `buffer_future` can be read from
if let Some(Ok(())) = receiver.receive().await {  // <-- Fails here, row 160. Returns a None
   ...
} else {
    panic!("failed to run compute on gpu!")
}
```

**Repro steps**

Go to `wgpu` directory

(in windows, in unix remove "set")
`set RUSTFLAGS=--cfg=web_sys_unstable_apis`

Run the commands
`cargo build --no-default-features --target wasm32-unknown-unknown --example hello-compute`
`wasm-bindgen --out-dir target/generated --web ../target/wasm32-unknown-unknown/debug/examples/hello-compute.wasm`

change `getObject(arg0).dispatch` in `target/generated/hello-compute.js`

```
imports.wbg.__wbg_dispatch_b68689d8b6913579 = function(arg0, arg1, arg2, arg3) {
    getObject(arg0).dispatch(arg1 >>> 0, arg2 >>> 0, arg3 >>> 0);
};

```
to 

```
imports.wbg.__wbg_dispatch_b68689d8b6913579 = function(arg0, arg1, arg2, arg3) {
    getObject(arg0).dispatchWorkgroups(arg1 >>> 0, arg2 >>> 0, arg3 >>> 0);
};

```
Not sure if it is an issue with the "wrong" dispatch comes from wasm-bindgen or wgpu? Otherwise, it yields the error `Uncaught (in promise) TypeError: getObject(...).dispatch is not a function`.

Create the file `target/generated/index.html `and add the following:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <script type="module">
      import init from "./hello-compute.js"; // Change this file to the name of the example you are using
      init();
    </script>
  </body>
</html>
```

Run the command (requires installation)
`simple-http-server target/generated`

open `localhost:8000`

open the console (f12) and check output

**Expected vs observed behavior**

Example should pass / compute in both commits

**Extra materials**

Fail commit 32af4f56079fd2203c46c9c452cfe33fd60a5721
![fail_32af4f56079fd2203c46c9c452cfe33fd60a5721](https://user-images.githubusercontent.com/30318121/171596070-868b3ada-fd79-474f-a5c4-c1effaf07a7d.PNG)

Ok commit 8063edc6482cfc828895ec0feaa446767fecc510
![ok_8063edc6482cfc828895ec0feaa446767fecc510](https://user-images.githubusercontent.com/30318121/171596089-5e2a9eda-1a1b-4d96-8421-4c8a404c058c.png)

**Platform**

Windows version 10.0.19044 build 19044
cargo 1.60.0 (d1fd9fe2c 2022-03-01)
rustc 1.60.0 (7737e0b5c 2022-04-04)
wasm-bindgen 0.2.80
Firefox nightly 103.0a1 (2022-05-31) (64-bit) with webgpu enabled

**Comment by cwfitzgerald** [comment]
Hmm, there's something up with the plumbing, the sender is being dropped without being called.

**Comment by cwfitzgerald** [comment]
> Also, any findings about the issue which requires the line getObject(arg0).dispatch(arg1 >>> 0, arg2 >>> 0, arg3 >>> 0); to be changed to getObject(arg0).dispatchWorkgroups(arg1 >>> 0, arg2 >>> 0, arg3 >>> 0); in target/generated/hello-compute.js? Should I create a new issue for that one?

web_sys is just out of date, see https://github.com/gfx-rs/wgpu/pull/2795

Bleh that's annoying. https://docs.rs/wasm-bindgen/latest/wasm_bindgen/closure/struct.Closure.html#method.once_into_js though seems to support turning FnOnce functions into closures without leaking what they contain. However because we share resources with a function that doesn't get called, we should add a call to https://doc.rust-lang.org/std/rc/struct.Rc.html#method.decrement_strong_count to cause the Rc to fully die.

**Comment by cwfitzgerald** [comment]
@TimothyBergstrom could you try out https://github.com/gfx-rs/wgpu/pull/2807? I don't have a WebGPU browser handy.

**Comment by TimothyBergstrom** [comment]
Yes, it seems to work fine with the fix

![image](https://user-images.githubusercontent.com/30318121/175767455-0798bb84-8dd8-43f4-b3cc-88079c7f1454.png)
