### ISSUE TITLE
SurfaceTexture::present blocks for > 50ms on android

### ISSUE THREAD

**Issue by bmcpt** [gfx-rs/wgpu#2721]
**Description**
A call to `SurfaceTexture::present` function blocks for 50-60ms on android. Desktop build of that app works fine, even on old computers.

**Expected vs observed behavior**
`SurfaceTexture::present` shouldn't take more than a millisecond like it does on desktop.

**Platform**
Android 11 and 12, vulkan backend

**Comment by bmcpt** [comment]
Sometimes `get_current_texture` lags too (for a similar amount) . And when it does lag, the following `present` call doesn't lag.

**Comment by cwfitzgerald** [comment]
This sounds like you're GPU bound, your application is taking 50-60ms on a mobile GPU and running much faster on desktop and it's manifesting in a strange way due to the driver blocking in present.

**Comment by cwfitzgerald** [comment]
I'm going to close this for now, but if there are still specific issues with presentation on android, please continue the discussion.

**Comment by Nathan-M-code** [comment]
Same problem with wgpu 27, Samsung A54 5G.
`SurfaceTexture::present` blocks very long every 2 frames, around 30 ms.
@cwfitzgerald Can you specify what you mean by "This sounds like you're GPU bound" ? The commands I submit are quite simple I'm suprised the phone cannot handle them.
