### ISSUE TITLE
The function "dispatch_workgroups_indirect" does not work

### ISSUE THREAD

**Issue by panxinmiao** [gfx-rs/wgpu#2728]
**Description**

I tried to update the wgpu-native to the latest wgpu-core, but the test case of `dispatch_workgroups_indirect`  in the downstream wgpu-py can't pass.

Then I tried to modify this example: "https://github.com/gfx-rs/wgpu/blob/master/wgpu/examples/hello-compute/main.rs" , create an indirect buffer and replace `dispatch_workgroups` with `dispatch_workgroups_indirect` for testing, the result is not correct also.

**Repro steps**

modify this example: "https://github.com/gfx-rs/wgpu/blob/master/wgpu/examples/hello-compute/main.rs", use `dispatch_workgroups_indirect` instead.

**Expected vs observed behavior**

The output value is always equal to the input.  No computes seem to have been made.

**Platform**

wgpu master branch.  Windows10, vulkan backend

**Comment by cwfitzgerald** [comment]
I can't seem to get this to reproduce on metal, what code did you use, I used 

```
    let indirect_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
        label: None,
        contents: bytemuck::cast_slice(&[numbers.len() as u32, 1, 1]),
        usage: wgpu::BufferUsages::INDIRECT,
    });

    // A command encoder executes one or many pipelines.
    // It is to WebGPU what a command buffer is to Vulkan.
    let mut encoder =
        device.create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    {
        let mut cpass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor { label: None });
        cpass.set_pipeline(&compute_pipeline);
        cpass.set_bind_group(0, &bind_group, &[]);
        cpass.insert_debug_marker("compute collatz iterations");
        cpass.dispatch_workgroups_indirect(&indirect_buffer, 0); // Number of cells to run, the (x,y,z) size of item being processed
    }
````

**Comment by panxinmiao** [comment]
My code is similar to yours,
The results are as follows:
![image](https://user-images.githubusercontent.com/8044566/175336223-5c2ff3d5-54c9-4309-b638-5ca9b383e2d6.png)

**Comment by cwfitzgerald** [comment]
I've got this reproducing on dx12 with a validation error about bad barriers - I know the problem here.
