### ISSUE TITLE
Track used pipeline stages

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#273]
The barriers we currently issue have a very generic stage coverage (i.e. "all_images() -> all_images()"). We could track the stages used in each synchronization unit and OR those stages together when issuing a barrier.

**Comment by cwfitzgerald** [comment]
Is this still an issue?

**Comment by kvark** [comment]
Yes, we don't have that implemented. It's an optimization. Ideally, we'd play with it once we have any performance metrics to track.

**Comment by cwfitzgerald** [comment]
Done in new hal.
