### ISSUE TITLE
Read/Write and Read-Only Storage Texture Error Message Doesn't Say Why

### ISSUE THREAD

**Issue by OneKnightOnly** [gfx-rs/wgpu#2735]
**Description**
R32Uint StorageTexture requires TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES to be enabled.

**Repro steps**

        let texture = ctx.device.create_texture(&wgpu::TextureDescriptor {
            size: wgpu::Extent3d {
                width: 2,
                height: 2,
                depth_or_array_layers: 2,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D3,
            format: wgpu::TextureFormat::R32Uint,
            usage: wgpu::TextureUsages::TEXTURE_BINDING
                | wgpu::TextureUsages::STORAGE_BINDING
                | wgpu::TextureUsages::COPY_DST,
            label: None,
        });

        let bind_group_layout =
            ctx.device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    entries: &[wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::StorageTexture {
                            access: wgpu::StorageTextureAccess::ReadWrite,
                            format: wgpu::TextureFormat::R32Uint,
                            view_dimension: wgpu::TextureViewDimension::D3,
                        },
                        count: None,
                    }],
                    label: None,
                });

**Expected vs observed behavior**
R32Uint is part of webgpu spec and shouldn't require special features enabled.

**Error Messge**
    In Device::create_bind_group_layout
    binding 0 entry is invalid
    Features TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES are required but not enabled on the device.

**Comment by cwfitzgerald** [comment]
Ahh, that's the problem, you're making a read_write storage texture, something that isn't supported in baseline webgpu. The way we current guard this is by the custom features flag. As is obvious, the error message really could be improved for this case. Going to rename and leave open.

**Comment by OneKnightOnly** [comment]
Oh thats what it is, I just changed the access to writeonly and it works perfectly thanks.

**Comment by feresr** [comment]
Is there no way to `read` a texture from a compute shader? (without the feature flag) 
how is this usually done in webGPU?

**Comment by cwfitzgerald** [comment]
If you want to read from a texture, bind it as a normal texture (not a storage texture) and use textureLoad on it
