### ISSUE TITLE
Implement Timestamp Queries on Metal

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#2739]
**Is your feature request related to a problem? Please describe.**
Follow up to #2738, metal sspecial consideration for timestamps because of TBDR architectures.

**Describe the solution you'd like**
Align with upstream spec and implement on metal.

Hard part will be the stupid linear regression we need for timestamp period analysis.

**Describe alternatives you've considered**

None

**Additional context**
https://github.com/gpuweb/gpuweb/pull/2190

**Comment by Wumpf** [comment]
I understand the limitations of timestamps in TBDR architectures (i.e. the question for timestamp in a pass rather ill-posed). But could you please paraphrase the `Hard part will be the stupid linear regression we need for timestamp period analysis.` bit? Is this about the timestamp unit being under-specified as mentioned here https://github.com/gpuweb/gpuweb/issues/1325#issuecomment-760403320? How does this work currently on Intel/Nvidia Gpus where `WRITE_TIMESTAMP_INSIDE_PASSES` is allowed on Metal?

The originally indirectly linked webgpu issue is quite long 😅

**Comment by cwfitzgerald** [comment]
Yeah the problem is how to get the timestamp unit. Through metal there is a single way of figuring out the unit. You need to call https://developer.apple.com/documentation/metal/mtldevice/3194378-sampletimestamps to get the cpu and gpu timestamps, but you need to call it twice and then determine the "slope" between the two calls to figure out the gpu timestamp unit. On Apple chips the timestamps are always the same, but on intel/nvidia/amd the timestamps will both be different and have a different unit.
