### ISSUE TITLE
Windows 11's WARP Passes the Water Example Image Comparison Test

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#2760]
**Description**

Follow up to #2746 which found that Windows 11's version of WARP passes the image comparison tests while Windows 10's don't. We currently have no way of representing this state in our testing framework.

We need some way of exposing something like the driver version, which we can hopefully use to guard the tests.

**Repro steps**

Run `cargo nextest run water` and see the test fail because the image comparison succeeded.

**Comment by PrototypeNM1** [comment]
DirextX doesn't seem to provide a way of getting the driver version directly, so you have to [dig through the registry](https://stackoverflow.com/questions/56935213/how-to-get-adapter-driver-version-in-directx12) instead. GPUDetect implements the prior explanation plus verifying the LUID [here](https://github.com/GameTechDev/gpudetect/blob/b0aa04cd87bfea933066e80e88e8821ffa5082ba/GPUDetect.cpp#L420).

I pulled these values from three PCs: one that came with Windows 11, one that was upgraded to Windows 11, and one on Windows 10.

| OS | Product | Version | Subversion | Build | Age |
| -- | ------- | ------- | ---------- | ----- | --- |
| Windows 11 | 0xa | 0x0000 | **0x55f0** | 0x0001 | newest |
| Windows 11 (upgraded) | 0xa | 0x0000 | 0x4a61 | 0x0364 | oldest |
| Windows 11 (upgraded) | 0xa | 0x0000 | **0x55f0** | 0x0001 | newest |
| Windows 10 | 0xa | 0x0000 | 0x4a61 | 0x0054 | oldest |
| Windows 10 | 0xa | 0x0000 | 0x4a61 | 0x0364 | newest |

The Subversion field being >=0x55f0 seems to be a reliable indicator of the Microsoft Basic Render Driver being the fixed Windows 11 driver, 0x4a61 being the original Windows 10 driver.

**Comment by cwfitzgerald** [comment]
All good information - I think as this is a testing problem, we should just encourage people who hit this problem to get the new WARP [nuget package](https://www.nuget.org/packages/Microsoft.Direct3D.WARP), so they can just fix the problem.

I will look to get information on how to actually use it.
