### ISSUE TITLE
v0.13 release date

### ISSUE THREAD

**Issue by paulkre** [gfx-rs/wgpu#2797]
Is there any information regarding the release date of the next version? I just wasted some time trying to get the shaders in the `examples` folder to work until I realised that the WGSL version of v0.12 is completely outdated. The last release was 6 months ago so I think an update might be appropriate.

**Comment by cwfitzgerald** [comment]
Once all the issues in https://github.com/gfx-rs/wgpu/milestone/14 are tackled, we're going to cut a release. My hope is it's going to be in about two weeks.
