### ISSUE TITLE
Implement Push Constants for DX12

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#2829]
We currently cannot combine user defined push constants with the existing root constants that naga sends forward. This is partly a wgpu and partly a naga task.

**Comment by memoryruins** [comment]
naga's tracking issue for implementing push constants for its HLSL backend https://github.com/gfx-rs/naga/issues/1782

**Comment by LoganDark** [comment]
Looks like that issue has been resolved now

**Comment by cwfitzgerald** [comment]
Still waiting on #2866

**Comment by LoganDark** [comment]
Might want to add a closing keyword to the issue, then
