### ISSUE TITLE
wgpu's Cargo.toml repository field in v0.13 links to v0.12's branch

### ISSUE THREAD

**Issue by memoryruins** [gfx-rs/wgpu#2830]
Because of this, the repository buttons on v0.13's crates.io and docs.rs link to v0.12's branch. 

https://github.com/gfx-rs/wgpu/blob/e125321bff7eb602d1849f18f22606afeebef3fb/wgpu/Cargo.toml#L8

Would it be preferred to update the branch part of the url or remove it? The other `wgpu-*` crates currently do not include a branch.

https://github.com/gfx-rs/wgpu/blob/e125321bff7eb602d1849f18f22606afeebef3fb/wgpu-hal/Cargo.toml#L8

**Comment by cwfitzgerald** [comment]
Bleh, ofc I manage to miss something lol.

We linked it so that when people got linked to the repository they see 0.12's examples not the potentially out of date master branch. I'll queue this up for a patch.

**Comment by cwfitzgerald** [comment]
Closed by cb0646f
