### ISSUE TITLE
v0.13 - BrowserWebGpu - AutoNoVSync does not properly fallback

### ISSUE THREAD

**Issue by simbleau** [gfx-rs/wgpu#2840]
**Description**
AutoNoVSync appears to not fall-back correctly.

**Repro steps**
https://github.com/simbleau/nbody-wasm-sim/tree/4cd3b2fadb0bed6b71ef3253f3989d78fd5d2020
`wasm-pack build --target web`
`python -m http.server`
[`http://localhost:8000/`](http://localhost:8000/)

**Expected vs observed behavior**
Error stack forwarded to the console via WASM:
`panicked at 'Error in Surface::configure: requested present mode AutoNoVsync is not in the list of supported present modes: [Fifo]'`

This seems like a bug because the [AutoNoVSync documentation](https://docs.rs/wgpu/latest/wgpu/enum.PresentMode.html#variant.AutoNoVsync) says it will fallback to Fifo, but clear it is not, and detects Fifo as a supported present mode.

**Extra materials**
![2022-07-02_20-17](https://user-images.githubusercontent.com/48108917/177019795-3ade6708-c553-4bbf-8dde-8dfa62d73824.png)

**Platform**
wgpu 0.13
linux, ubuntu 20.04 LTS

**Comment by Seabass247** [comment]
I also get this bug.

Platform
wgpu 0.13
Windows 11

**Comment by cwfitzgerald** [comment]
D'oh, easy fix - I'll fix it and launch a backport

**Comment by simbleau** [comment]
I can do the PR as well if you want. :)

**Comment by cwfitzgerald** [comment]
Sorry didn't reply fast enough, I wanted to refactor bit of code a bit too - but let's merge your change first, then I'll merge mine in so you still get credit :)

**Comment by simbleau** [comment]
Awesome! Still working on the PR/Changelog ceremony. Thanks!

**Comment by simbleau** [comment]
PR is ready.

**Comment by simbleau** [comment]
Hey, necromancing because this appears to still be an outstanding issue. I thought we fixed it, but I guess not?
![2022-07-03_15-50](https://user-images.githubusercontent.com/48108917/177055213-df1a7e4a-50bf-4e77-9fe7-17e82f727cca.png)

**Comment by cwfitzgerald** [comment]
Is wgpu-core at 0.13.1?

**Comment by simbleau** [comment]
Yes

**Comment by cwfitzgerald** [comment]
That's wgpu, cargo won't update transitive dependencies unless you force it to, try cargo update -p wgpu-core -p wgpu-hal

**Comment by simbleau** [comment]
It works! Sorry for the necromancing. :P

**Comment by cwfitzgerald** [comment]
All good!

**Comment by simbleau** [comment]
Yes

Thank you,
Spencer C. Imbleau (he/him/his) (https://www.glsen.org/pronouns)
Software Engineer II
NASA, Kennedy Space Center
***@***.*** ***@***.***) | +1 (704) 747-5126 (tel:+1-704-747-5126)
