### ISSUE TITLE
v0.13 - BrowserWebGPU - GPUCommandEncoder.beginRenderPass: Missing required 'loadValue' member of GPURenderPassColorAttachment

### ISSUE THREAD

**Issue by simbleau** [gfx-rs/wgpu#2841]
**Description**
Render pass appears to be broken and gives a totally useless error, I can't really figure out what this means:
`Uncaught (in promise) TypeError: GPUCommandEncoder.beginRenderPass: Missing required 'loadValue' member of GPURenderPassColorAttachment.`

That points to the javascript wrapper it seems made by `wasm-pack`, so I don't think the error is truly there...
![2022-07-02_21-24](https://user-images.githubusercontent.com/48108917/177020895-3db48ccf-6c3b-4405-8674-4d08b2987bc3.png)

**Repro steps**
[https://github.com/simbleau/nbody-wasm-sim/tree/4fadff5a14e186887bc00c2711fd5c66566c2335](https://github.com/simbleau/nbody-wasm-sim/tree/4fadff5a14e186887bc00c2711fd5c66566c2335)
`wasm-pack build --target web`
`python -m http.server`
[`http://localhost:8000/`](http://localhost:8000/))

**Expected vs observed behavior**
I am trying to begin the render pass to clear a color in v0.13, which worked in v0.12
```rs
{
            let _render_pass =
                encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                    label: Some("Render Pass"),
                    color_attachments: &[Some(
                        wgpu::RenderPassColorAttachment {
                            view: &view,
                            resolve_target: None,
                            ops: wgpu::Operations {
                                load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                                store: true,
                            },
                        },
                    )],
                    depth_stencil_attachment: None,
                });
        }
```

**Extra materials**
![2022-07-02_21-14](https://user-images.githubusercontent.com/48108917/177020674-81a41e07-604b-44ce-bf5c-340902546260.png)

**Platform**
wgpu 0.13
Ubuntu 20.04 LTS

**Comment by simbleau** [comment]
P.S. I'd love to fix this myself in a PR if someone has guidance. Just a litte lost. I'm interested in contributing more to wgpu.

**Comment by cwfitzgerald** [comment]
What browser is this?

**Comment by simbleau** [comment]
Firefox Nightly

**Comment by cwfitzgerald** [comment]
I think ff is behind on the spec so we're actually ahead of firefox here -- chrome nightly should work.
