### ISSUE TITLE
Use WGSL instead of GLSL in library documentation 

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#2849]
There are a number of items in `wgpu` whose documentation contain examples using GLSL syntax or other references to GLSL elements. Since WGSL is now the standard shading language for WebGPU, it would be beneficial to readers if these examples were presented first in WGSL. (Keeping the GLSL would still be helpful for new users arriving from WebGL.)

Relevant occurrences of the text "GLSL" in documentation as of commit c36eb9f44bd9462fe176fb859839592131428feb (just after 0.13.1):

* `Features::SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING`
* `Features::UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING`
* `BufferBindingType`
* `BindingType`
* `StorageTextureAccess`
* `TextureSampleType`
* `TextureViewDimension`

Incomplete list (since it's hard to search for) of locations where the documentation refers to GLSL entities without even mentioning GLSL:

* `PipelineLayoutDescriptor` refers to "set = 0" which is GLSL syntax.
* `BindingType::Texture::multisampled` refers to GLSL texture sampling functions.
* `Features::TEXTURE_BINDING_ARRAY` and `BUFFER_BINDING_ARRAY` have GLSL examples.

Also possibly of interest: the following items mention something like “See the OpenGL specification” but are not about shading language per se and are mostly just declining to explain a topic:

* `BlendFactor`
* `BlendState`
* `BindingType::StorageTexture`
* `SamplerBindingType`

**Comment by Sebbl0508** [comment]
Shouldn't this be closed now?

**Comment by norepimorphism** [comment]
Maybe, though #2888 technically didn't address everything @kpreid mentioned; it was primarily additive and didn't remove or modify bits where GLSL or OpenGL are mentioned out of context, for example. Remaining items of interest are:

- `BindingType::Texture::multisampled`
- `BindingType::StorageTexture`
- `BlendFactor`
- `BlendState`
- `PipelineLayoutDescriptor`
- `SamplerBindingType`

And maybe more.

**Comment by techforni** [comment]
I can help on this
