### ISSUE TITLE
Window dragging causes freeze

### ISSUE THREAD

**Issue by Sebbl0508** [gfx-rs/wgpu#2852]
Hello,

first off: i don't know if this is a `winit` or `wgpu` problem.
What i DO know is that this happens with examples from `iced` also.
This does NOT happen when just opening a window with `winit` and drawing nothing to it

So, on my machine, when dragging a window, it freezes for maybe a second or so.
What i noticed is that this also freezes some other GPU accelerated applications like OBS while the window is dragged.
[Here's a Video](https://mega.nz/file/qxQ1HLDL#VemHvkyLVdgdva_h-JMYboAQAf922RzdvS4_URsSN2s) showing this effect.

My PC configuration:
```
OS: Pop! OS 22.04 LTS
CPU: AMD Ryzen 5 3600
GPU: NVIDIA RTX 3070
Kernel: 5.17.15-76051715-generic
GPU-Driver: Proprietary 515.48.07
```
The WGPU Backend in-use is `Vulkan`
The `PresentMode` is `AutoVsync`
Available `PresentMode`s are `[Fifo, Immediate]`
This doesn't happen on `Immediate` present mode

This problem doesn't occur with other games or games written with Raylib for example.
While dragging the cursor also stays smooth, this isn't visible on the video because apparently this problem also influenced the recording

**Comment by Sebbl0508** [comment]
Weirdly enough, apparently dragging *any* other window while a wgpu app on `Fifo` is running result in the same effect

**Comment by jinleili** [comment]
This lag is not related to `winit`，to keep things simple, in the current wgpu `examples`, the event loop is created in the main thread（ui-thread）, where the command queue also does the encoding for each frame，which does cause lag in the main thread while performing other UI tasks.

**Comment by Sebbl0508** [comment]
This lag doesn't seem to happen on my laptop with integrated AMD GPU or on windows
