### ISSUE TITLE
Adapter::request_device terminates with SIGSEGV (Address boundary error) in debug mode

### ISSUE THREAD

**Issue by olofwalker** [gfx-rs/wgpu#2864]
**Description**
When running a WGPU 0.13 application in debug mode, the application crashes when doing the following call:

```
        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    label: None,
                    features: wgpu::Features::empty(),
                    limits: wgpu::Limits::default(),
                },
                None, // Trace path
            )
            .await
            .unwrap();
```

This works when running in release mode.

**Repro steps**
I've tested and got the same behavior when running `sotrh` excellent tutorials also, I think this started with 0.12.

1. Clone
https://github.com/sotrh/learn-wgpu
2. cd code/beginner/tutorial6-uniforms
3. cargo run --bin tutorial6-uniforms 

This will result in a SIGSEGV (Address boundary error)

Add a `--release` and it works.

**Expected vs observed behavior**
I expect it to work the same in both debug and release mode

**Platform**

- Rust 1.62
- wgpu 0.13
- Thinkpad T14
- Ubuntu 22.04 LTS
- "GPU"
```
  *-display                 
       description: VGA compatible controller
       product: Renoir
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:07:00.0
       logical name: /dev/fb0
       version: d1
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list fb
       configuration: depth=32 driver=amdgpu latency=0 mode=1920x1080 resolution=1920,1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:c0-bf iomemory:c0-bf irq:62 memory:c60000000-c6fffffff memory:c70000000-c701fffff ioport:1000(size=256) memory:fd300000-fd37ffff
```
- (/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so) version 0.0.1

**Comment by victorvde** [comment]
Since this only happens in debug mode, one thing you can check is updating or removing your Vulkan validation layers (cf. https://github.com/gfx-rs/wgpu/issues/2789#issuecomment-1159831351 ).
Otherwise a backtrace from gdb would be helpful to be able to diagnose the issue.

**Comment by olofwalker** [comment]
@victorvde I should have added a stacktrace, sorry about that. 

This seems to be connected to the loading of renderdoc in wgpu described here https://github.com/gfx-rs/wgpu/issues/2793. This ticket has the same issue as what I'm seeing https://github.com/gfx-rs/wgpu/issues/2789.

**Comment by cwfitzgerald** [comment]
Closing in favor of #2793 nice spot
