### ISSUE TITLE
Commit 0eb6845 with update of web-sys 0.3.58 causes crash on WASM

### ISSUE THREAD

**Issue by TimothyBergstrom** [gfx-rs/wgpu#2880]
**Description**

I have some issues when running webgpu for wasm32-unknown-unknown after the commit https://github.com/gfx-rs/wgpu/commit/0eb6845b6ad114963de73167332b8048b8997184. In commit https://github.com/gfx-rs/wgpu/commit/b0c798639a9b041a14dfaf3f1deb1b1b932f55c5, it works fine with some minor manual changes (before the update to web-sys 0.3.58)

Is this an issue with web-sys or could something be done in wgpu?

**Repro steps**

* Make a new directory and create the following files:

`Cargo.toml`
```
[package]
name = "wgpu_test"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu/", rev = "b0c7986"}
log = "0.4"
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
bytemuck = { version = "1.4", features = ["derive"] }
futures-intrusive = "0.4"
wasm-bindgen-futures = "0.4.30"
```

`.cargo\Config.toml`
```
[target.wasm32-unknown-unknown]
rustflags = ["--cfg=web_sys_unstable_apis"]
```

* Create a "src" directory and copy the files from "wgpu/examples/hello-compute" in b0c7986 to "src"

* Run the following commands:
`cargo build --no-default-features --target wasm32-unknown-unknown`
`wasm-bindgen --out-dir target/generated --web target/wasm32-unknown-unknown/debug/wgpu_test.wasm`
`simple-http-server target/generated`

Change `getObject(arg0).dispatch` in `target/generated/wgpu_test.js`

```
imports.wbg.__wbg_dispatch_b68689d8b6913579 = function(arg0, arg1, arg2, arg3) {
    getObject(arg0).dispatch(arg1 >>> 0, arg2 >>> 0, arg3 >>> 0);
};

```
to

```
imports.wbg.__wbg_dispatch_b68689d8b6913579 = function(arg0, arg1, arg2, arg3) {
    getObject(arg0).dispatchWorkgroups(arg1 >>> 0, arg2 >>> 0, arg3 >>> 0);
};

```

* Open `localhost:8000` in a webgpu enabled browser. It should display the following:

When running b0c798639a9b041a14dfaf3f1deb1b1b932f55c5
![image](https://user-images.githubusercontent.com/30318121/178779240-dfa14227-d031-46e8-b7a0-5e1f0797554f.png)

* Change the file `Cargo.toml` to this.

```
[package]
name = "wgpu_test"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu/", rev = "0eb6845"}  # rev b0c7986 -> rev 0eb6845
log = "0.4"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"   # 0.1.2 -> 0.2.0 
bytemuck = { version = "1.4", features = ["derive"] }
futures-intrusive = "0.4"
wasm-bindgen-futures = "0.4.30"
```

* Redo the build commands (no need to replace dispatch this time)

* Open `localhost:8000` in a webgpu enabled browser. It should display the following:

When running https://github.com/gfx-rs/wgpu/commit/0eb6845b6ad114963de73167332b8048b8997184
![image](https://user-images.githubusercontent.com/30318121/178778402-9ea6c84b-5bc8-4372-ac64-a7d77c4b4262.png)

**Expected vs observed behavior**

The new update with web-sys 0.3.58 should work with webgpu.

**Extras**

I can get it to work by adding the following from row 112 in main.rs:

```
let bind_group_entry = wgpu::BindGroupLayoutEntry {
    binding: 0,
    visibility: wgpu::ShaderStages::COMPUTE,
    ty: wgpu::BindingType::Buffer {
        ty: wgpu::BufferBindingType::Storage {
            read_only: false
        },
        has_dynamic_offset: false,
        min_binding_size: None
    },
    count: None
};
let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
    label: None,
    entries: &[bind_group_entry]
});
let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
    label: None,
    bind_group_layouts: &[&bind_group_layout],
    push_constant_ranges: &[]
});
let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
    label: None,
    layout: Some(&pipeline_layout),
    module: &cs_module,
    entry_point: "main",
});
```

And then changing

```
imports.wbg.__wbg_end_f1481b58f775f227 = function(arg0) {
    getObject(arg0).end();
};
```

to

```
imports.wbg.__wbg_end_f1481b58f775f227 = function(arg0) {
    getObject(arg0).endPass();
};
```

**EDIT:**

Instead of adding the bind-group layouts in main.rs, it also works by changing the following:

`wgpu_test.js`
```
imports.wbg.__wbg_createComputePipeline_ee9ec9853a37625d = function(arg0, arg1) {
    const ret = getObject(arg0).createComputePipeline(getObject(arg1));
    return addHeapObject(ret);
};
```

to
```
  imports.wbg.__wbg_createComputePipeline_ee9ec9853a37625d = function(arg0, arg1) {
      const shader = getObject(arg1);
      delete shader.layout;
      const ret = getObject(arg0).createComputePipeline(shader);
      return addHeapObject(ret);
  };
```

with the additional change of "end()" to "endPass()"

**Platform**

OS: Windows
Edition: Windows 10 Home
Version: 21H1
OS build: 19043.1766
Experience: Windows Feature Experience Pack 120.2212.4180.0

cargo 1.62.0 (a748cf5a3 2022-06-08)
rustc 1.62.0 (a8314ef7d 2022-06-27)
wasm-bindgen 0.2.80 (also tested with 0.2.81)
Firefox nightly 104.0a1 (2022-07-13) (64-bit) with webgpu enabled

**Comment by teoxoy** [comment]
This looks like it was due to Firefox's WebIDL bindings for WebGPU being out of date.

This might happen from time to time since wgpu's web target and Firefox's bindings don't get updated in sync.
It should however not happen once the WebGPU v1 is officially published, Firefox's WebGPU implementation becomes spec compliant and also web-sys is updated to expose the WebGPU v1 API surface.
