### ISSUE TITLE
wgpu calls `createBuffer` on an `undefined` from a worker thread on Wasm

### ISSUE THREAD

**Issue by norepimorphism** [gfx-rs/wgpu#2884]
**Description**
*wgpu* attempts to execute the `createBuffer` method on an `undefined` when running in a worker thread on the target `wasm32-unknown-unknown`. The instance, adapter, surface, and device were created on the main thread.

**Repro steps**
A runnable example is [here](https://norepimorphism.github.io), the source code for which is [here](https://github.com/norepimorphism/noctane); see [`wasm.rs`](https://github.com/norepimorphism/noctane/blob/a9f7e684785377acb230d39ef6b251f8c24c9589/core/examples/wasm.rs) and [`core/src/lib.rs`](https://github.com/norepimorphism/noctane/blob/a9f7e684785377acb230d39ef6b251f8c24c9589/core/src/lib.rs). More generic instructions are described below.

1. Create a new Rust crate targeting `wasm32-unknown-unknown`.
2. Export a `main` function using `#[wasm_bindgen]`.
3. In `main`, create a *wgpu* instance, adapter, device, and surface.
4. Create a new thread (e.g., using `wasm_thread`) in which a vertex buffer is created and initialized with the device returned by *wgpu*.
5. Observe the error.

**Expected vs observed behavior**
I expect the vertex buffer creation to be successful, after which render passes would occur, the command queue would be submitted, and the surface frame would ultimately be presented.

Instead, I observe that attempting to create the vertex buffer from a worker thread crashes the Wasm process.

**Extra materials**
On Microsoft Edge (Chromium-based), I receive the following error:
![Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createBuffer')](https://user-images.githubusercontent.com/97794085/179077531-efe837fa-0501-4c37-95d3-9bd668cda997.png)

On Firefox, I receive the following error:
![TypeError: can't access property "createBuffer", getObject(...) is undefined](https://user-images.githubusercontent.com/97794085/179077791-db646eae-d09e-49fb-889d-d228b343e2bc.png)

**Platform**
Windows 11. *wgpu* 0.13 (latest minor release). *naga* 0.9.

**Comment by codeart1st** [comment]
I also run into this issue.

**Comment by teoxoy** [comment]
Related: https://github.com/gfx-rs/wgpu/issues/2652 (talks about the GLES backend but the same ideas should apply here too)
