### ISSUE TITLE
Regression in 0.13: Textures with width/height that are not modulo block width/height are no longer supported

### ISSUE THREAD

**Issue by superdump** [gfx-rs/wgpu#2885]
In 0.12 I had a compressed array texture with layers that were 250x250 and could load that just fine, providing the block data such that there are blocks that cover the image. So for example, the number of blocks per row for a 250x250 image with 4x4 blocks would be (250 + 4 - 1) / 4 = 63. And as a sanity check 63 * 4 = 252.

In 0.13 I get:
```
Caused by:
    In Device::create_texture
    Width 250 is not a multiple of Bc1RgbaUnormSrgb's block width (4)
```

**Comment by cwfitzgerald** [comment]
This is actually the intended behavior, making compressed textures that aren't multiples of the texel width isn't portable, I believe dx12 requires it.

See also https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-gputexturedescriptor

**Comment by superdump** [comment]
Cool, good to know! Thanks!
