### ISSUE TITLE
How to render android camera preview(samplerExternalOES) on wgpu？

### ISSUE THREAD

**Issue by chenkecheng** [gfx-rs/wgpu#2891]
Android Camera share preview buffers by SurfaceTexure, how to render these buffers on wgpu?

**Comment by i509VCB** [comment]
Linking to the general memory import/export issue since this would involve that: https://github.com/gfx-rs/wgpu/issues/2320

**Comment by cwfitzgerald** [comment]
Going to close in favor of that issue
