### ISSUE TITLE
wgpu-hal and wgpu-core should enable web-sys features when necessary

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/wgpu#2894]
**Description**
We expose some `web_sys` types in wgpu-hal and wgpu-core that should require the relevant feature on web-sys (e.g. `OffscreenCanvas` in https://github.com/gfx-rs/wgpu/blob/25b16d5cc8ca84b82574bb1d02d2c51d3ea264c8/wgpu-hal/src/gles/web.rs#L55)

**Repro steps**
Try to build wgpu-native with the wasm32-unknown-unknown target

**Expected vs observed behavior**
Compilation can fail if a crate attempts to use wgpu-hal or wgpu-core without enabling the web-sys features manually, but this shouldn't be required - we should handle it in wgpu-hal and wgpu-core

**Extra materials**
https://github.com/gfx-rs/wgpu-native/issues/207 is related

**Platform**
Latest wgpu

**Comment by teoxoy** [comment]
Was fixed by #2922.
