### ISSUE TITLE
Using Rgba16Unorm texture as RENDER_ATTACHMENT

### ISSUE THREAD

**Issue by paulkre** [gfx-rs/wgpu#2899]
When I try using a `Rgba16Unorm` texture as a `RENDER_ATTACHMENT` of a render pass I get the following error:

```
Texture usages RENDER_ATTACHMENT are not allowed on a texture of type Rgba16Unorm
```

Is it somehow possible to support this usage?

Is there maybe a list of `TextureFormat`s that work as a `RENDER_ATTACHMENT`? Or is the only supported format `Rrgba8Unorm`?

**Comment by cwfitzgerald** [comment]
What version of wgpu-core and wgpu-hal are you using?

**Comment by paulkre** [comment]
The error still occurs in `v0.13.2`.

**Comment by Seamooo** [comment]
can confirm the allowed_usages attached to Rgba16Unorm explicitly doesn't allow for `RENDER_ATTACHMENT` [see here](https://github.com/gfx-rs/wgpu/blob/6448c6062f268288f451962f6ff92be79e8b1e06/wgpu-types/src/lib.rs#L2222)

**Comment by cwfitzgerald** [comment]
There is a feature: `ADAPTER_SPECIFIC_TEXTURE_FORMAT_FEATURES` which expands usages to whatever the device supports, which can be checked with https://docs.rs/wgpu/latest/wgpu/struct.Adapter.html#method.get_texture_format_features
