### ISSUE TITLE
Can't set MSAA samples beyond 4

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/wgpu#2910]
**Description**

The Vulkan capabilities viewer says that my hardware/driver supports MSAA samples up to 8 for all targets:

![image](https://user-images.githubusercontent.com/4706210/180598869-998f22cb-8faa-4216-ba99-914e77102499.png)

Setting MSAA samples to 1 or 4 works correctly, however increasing the samples to 8 causes the following error:

```
     Running `C:\...\msaa-line.exe`
Using NVIDIA GeForce GTX 1080 (Vulkan)
[2022-07-23T09:22:55Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Vulkan)>`
    In a pass parameter
      note: command buffer = `<CommandBuffer-(0, 1, Vulkan)>`
    attachment's sample count 8 is invalid

', wgpu\src\backend\direct.rs:2391:5
```

**Repro steps**
Modify the `msaa-line` sample to set the number of samples to 8, and run it.

**Expected vs observed behavior**
Clearly describe what you get, and how it goes across your expectations.

I appreciate that the current web spec only supports sample counts of 1 or 4, but I don't think this limitation should be enforced as a strict validation (especially for desktop builds, where the driver likely supports at least 8, and one can always query against the underlying API directly).

**Extra materials**
This appears to be failing a [hardcoded validation](https://github.com/gfx-rs/wgpu/blob/9f82504d8a3b6e234599b19cc35c299bcec8b138/wgpu-core/src/command/render.rs#L725-L727).

All other hardcoded validations I can find only check that the number of samples are less than 32.
 
**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

Windows 10, Vulkan, v0.13.1 of wgpu

**Comment by cwfitzgerald** [comment]
Thanks for the issue! We definitely want to add this, and the way I think that this should manifest is by extending the TextureFormatFeatutes and splitting multisampling into three flags, 2, 4, and 8 sample flags for each texture.
