### ISSUE TITLE
can't pass BufferDescriptor cross async runtime, because Label is &'a str

### ISSUE THREAD

**Issue by moyy** [gfx-rs/wgpu#2915]
when I create Buffer cross async runitme,  I can't pass BufferDescriptor because it's require a lifetime with reference label;

if possible, the label relplace with Cow<'str> instead of ‘str, as I can pass the owned of BufferDescriptor.

show code as follow: 

``` rs

pub struct BufferDesc {
    pub size: BufferAddress,
    
    pub usage: BufferUsages,
    
    pub mapped_at_creation: bool,
}

// now i can pass the owned of BufferDesc cross async runtime(impl with multithread)
pub async fn create_buffer(
    device: wgpu::Device,
    desc: BufferDesc,
) -> wgpu::Buffer {
    let async_value = AsyncValue::new();
    let async_value_clone = async_value.clone();

    R_RES_RT.spawn(R_RES_RT.alloc(), async move {
        let d = wgpu::BufferDescriptor {
            label: None,
            size: desc.size,
            usage: desc.usage,
            mapped_at_creation: desc.mapped_at_creation,
        };
        let r = device.create_buffer(&d);
        async_value_clone.set(r);
    });

    async_value.await
}
```

**Comment by moyy** [comment]
Can you tell me that which example is running with multithread, one thread is encoding comand, and the other thread is create  render resource like texture or buffer etc. 

3Q

![image](https://user-images.githubusercontent.com/25075465/180990650-8d7c0d89-cd1f-4c58-912f-ada91f3732fd.png)

**Comment by kpreid** [comment]
You should be able to use the `wgpu::Device` from any thread (sharing it with `Arc` if needed) to create the buffer, so there is no need to send the creation request anywhere. Does that work for your situation?
