### ISSUE TITLE
Access violation reading location

### ISSUE THREAD

**Issue by genusistimelord** [gfx-rs/wgpu#2917]
**Description**
when starting up software that uses wgpu we are getting a Stop reason: Exception 0xc0000005 encountered at address 0x7ffa5d357011: Access violation reading location 0xffffffffffffffff caused by

```
#[doc = "<https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetPhysicalDeviceSurfaceSupportKHR.html>"]
    pub unsafe fn get_physical_device_surface_support_khr(
        &self,
        physical_device: PhysicalDevice,
        queue_family_index: u32,
        surface: SurfaceKHR,
        p_supported: *mut Bool32,
    ) -> Result {
        (self.get_physical_device_surface_support_khr)(
            physical_device,
            queue_family_index,
            surface,
            p_supported,
        )
    }
```

**Repro steps**
ideally this works on a lot of machines but a intel igpu and Nividia iGPU laptop is having this issue. I am running a Iced application that calls wgpu so if this a iced configuration issue let me know and ill try to fix it.

**Expected vs observed behavior**
to load up the correct GPU or driver or switch to a more acceptable rendering engine if vulkan is not fully supported like DX.

**Platform**
windows 10 21h2
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
32.0 GB ram
Intel iGPU UHD Graphics 630 16GB share mem
Nvidia Geforce RTX 2070 with Max-Q Design 8GB dedicated ram
wgpu 0.13

**Comment by cwfitzgerald** [comment]
Do you have the vulkan sdk installed? If so is it up to date? A lot of segfaults we get are due to out of date validation layers

**Comment by genusistimelord** [comment]
he has the latest versions of nvidia drivers for windows 10  installed but let me check if there is anything for vulkan that needs installed.

**Comment by genusistimelord** [comment]
OK so yeah there was a beta driver which fixed the issue and could be installed on windows 10. The new issue I see is that a lot of these laptops with dual GPU's have tons of Issues. Either they want to use the iGPU or they lack support for vulkan or other drivers. The only exception seems to be AMD CPU's with a AMD dGPU  since its much easier for them to integrate them together.

I just wish there was a good easy way to fix this without a kernel exception. Like some way to test if vulkan failed then switch to DX on windows or opengl on linux type of system.

**Comment by cwfitzgerald** [comment]
There's little we can do about the driver segfaulting unfortunately.
