### ISSUE TITLE
Windows 10  Intel(R) Iris(R) Plus Graphics (Vulkan) examples have errors and bevy doesn't work.

### ISSUE THREAD

**Issue by DragonJT** [gfx-rs/wgpu#2919]
I have Windows 10  Intel(R) Iris(R) Plus Graphics (Vulkan)
When running the cube example I get 2 errors and the program runs at 20fps. I came across this error when trying to get bevy to work. But it crashes due to a lot of vulkan errors. They said it was probably a wgpu issue. This is the errors I got when running the wgpu cube example...

  Compiling wgpu-hal v0.13.0 (C:\source\bevy\wgpu\wgpu-hal)
   Compiling wgpu v0.13.0 (C:\source\bevy\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 15s
     Running `target\debug\examples\cube.exe`
Using Intel(R) Iris(R) Plus Graphics (Vulkan)
[2022-07-27T19:03:25Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x2d56fb69728, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1418,680), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (800,600), minImageExtent = (800,600), maxImageExtent = (800,600). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2022-07-27T19:03:25Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x2d56fb69728, name: ?)
Avg frame time 17.794945ms
Avg frame time 16.708403ms

**Comment by genusistimelord** [comment]
can you make sure you have the latest driver updates? As this could be an out of date vulkan driver.
https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html

**Comment by DragonJT** [comment]
I downloaded intel driver & support assistant and updated my driver to 31.0.101.2111 driver date 19/07/2022. I still get the same errors as before when running the cube example.

     Running `target\debug\examples\cube.exe`
Using Intel(R) Iris(R) Plus Graphics (Vulkan)
[2022-07-28T18:54:03Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x23800e04a28, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1418,680), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (800,600), minImageExtent = (800,600), maxImageExtent = (800,600). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2022-07-28T18:54:03Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x23800e04a28, name: ?)
Avg frame time 16.455471ms
Avg frame time 16.654875ms

**Comment by cwfitzgerald** [comment]
That warning is annoying but harmless. What gives you the impression it's running at 20 fps? The frame time shows ~60fps.

**Comment by DragonJT** [comment]
My mistake I thought frametime was fps. I also managed to get bevy working now that I updated drivers. Although it still has error messages.
