### ISSUE TITLE
The number type for max_storage_buffer_binding_size on wgpu::Limits

### ISSUE THREAD

**Issue by gabrielmfern** [gfx-rs/wgpu#2929]
**Is your feature request related to a problem? Please describe.**
I am using wgpu for making a deep learning Rust crate on the GPU computational side,
and working with large deep learning models it is needed to use very large buffers, perhaps 16gb, 32gb, things like that.

But to have very large buffers like that I need to set the 'max_storage_buffer_binding_size' to be a very large amount of bytes
that can't really be written with just u32 (the type for the field right now).

**Describe the solution you'd like**
The solution would be simply to change this to u64 and deal with the repercussions of it on some new version.

**Describe alternatives you've considered**
Perhaps changing this max from using just directly bytes to using megabytes or something like that.

**Additional context**
The max size that you can get using u32 for the max_storage_buffer_binding_size is `4294967295`
which is just 3gb in comparison to 16gb, 32gb or maybe even 128gb.

**Comment by cwfitzgerald** [comment]
This is actually bubbling up from the underlying apis which express the limit in u32s. This is in part to shaders which do address calculations using 32bit values. See https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceLimits.html. There are also known issues with implementations hitting rounding errors once you exceed 2^31-1 or so. I would advise that if you want to deal with more data than that, you should expect the data to need to be resident in multiple different buffer bindings. This also improves your chances of being able to allocate that large amount of data - allocating a contiguous 16gb buffer is likely close to impossible, even on a card with lots of vram.
