### ISSUE TITLE
Keep a fixed array in a WGPU shader

### ISSUE THREAD

**Issue by jafioti** [gfx-rs/wgpu#2945]
I feel like this is an extremely common occurrence in shader code. I'm writing a marching cubes shader, and I want to make the edge table available efficiently. I would like to just include it directly in the shader, like this:
```
let edge_table = array<u32, 256>(
    0x000u, 0x109u, 0x203u, 0x30au, 0x406u, 0x50fu, 0x605u, 0x70cu,
    0x80cu, 0x905u, 0xa0fu, 0xb06u, 0xc0au, 0xd03u, 0xe09u, 0xf00u,
    0x190u, 0x099u, 0x393u, 0x29au, 0x596u, 0x49fu, 0x795u, 0x69cu,
    ...
    0x70cu, 0x605u, 0x50fu, 0x406u, 0x30au, 0x203u, 0x109u, 0x000u
);
```
But it won't let me access that with a runtime index. Why? Seems like the main use case of an array would be to access it at runtime.

So I switched to using an array provided by a buffer. But since WGPU requires all array items from uniform buffers to be at least 16 bytes, I need to waste a ton of space using wrapped types like this:
```
struct wrapped_u32 {
    @size(16) data: u32,
}

struct EdgeTable {
    data: array<wrapped_u32, 256>,
};
```
This obviously increases the memory usage by 4x, which seems crazy to me that this would be required. 

So my question is, what is the sanest way around these roadblocks? I don't think I'm doing anything crazy or unusual here, yet it's been a pretty hard experience.

**Comment by cwfitzgerald** [comment]
If you switch the `edge_table` declaration to be with a `var` instead of a `let`, this should allow dynamic indexing. In the case for buffers, you can store a `array<vec4<u32>>` then do `table.data[index / 4][index % 4]` to get the u32 you want. Not the most ideal thing, but storage buffers get around the problem.

**Comment by jafioti** [comment]
@cwfitzgerald Thanks for the response, when I switch to a `var`, I get `Global variable [9] 'edge_table' is invalid Type isn't compatible with address space Handle`

**Comment by jafioti** [comment]
Nevermind, I needed to use `var<private>`
