### ISSUE TITLE
Dropped frames

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#296]
The https://github.com/rukai/brawllib_rs renderer is dropping frames on:
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver, version 418
Backend: Vulkan

However the issue does not occur on my laptop with an AMD card.

I tried to create a minimal reproduction by modifying the triangle example to make such frame drops noticeable, but the issue did not appear.

I'll try to further investigate.

**Comment by cwfitzgerald** [comment]
Going to close this as stale, if there's any more information or reproduces on wgpu master, feel free to re-open.
