### ISSUE TITLE
Possibly missing `msg_send![..., retain]` in `wgpu-hal/src/metal/surface.rs`

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#2974]
#2826 removed [a `retain` message send][retain] from `Surface::from_view` that incremented the reference count on `view`, without adding back anything complementary (that I can see). There's nothing in that PR to suggest that the old `retain` call was incorrect, and indeed, the returned `Surface` holds a new pointer to the `view`, so this seems like a bug.

[retain]: https://github.com/gfx-rs/wgpu/blob/a108efe6b66a3dd0ccfb6bd5d73eaf1992c7fd04/wgpu-hal/src/metal/surface.rs#L131

**Comment by jimblandy** [comment]
cc @jinleili

**Comment by jinleili** [comment]
Yes, you are right.
Since Surface's `view` field is only called in `destroy_surface`, wouldn't it be better to just remove the view field?

**Comment by jinleili** [comment]
Oops, still need `view` field on the iOS target.

**Comment by jimblandy** [comment]
@jinleili I think this is closed. If there's anything missing, please re-open and fill me in.
