### ISSUE TITLE
Option to diable validation layers at runtime

### ISSUE THREAD

**Issue by LaylBongers** [gfx-rs/wgpu#300]
Most of the time, because of the big performance hit Vulkan validation layers cause, I want to run my game without validation layers enabled even in debug mode.
Sometimes however, to debug a rendering issue, I'll want to enable them, preferably through a command line flag on my game.
It would be nice if, for example, `Instance::new()` had the option to disable or enable validation layers for the platform it's running on, besides just leaving it to the default value.

**Comment by kvark** [comment]
There are many ways to communicate that, and having this configurable would be an improvement.
Changing `Instance::new` is not preferred though, since it's nice to have all `Instance` types agree on how they are initialized.

**Comment by kvark** [comment]
wwwwaaaaiiitttt, this is not gfx-rs repository, sorry. There is only one Instance type.
Before this can go anywhere, gfx-rs needs to have this configurable.

**Comment by cwfitzgerald** [comment]
Solved by #4230
