### ISSUE TITLE
As the title, in the webgpu, I create two compute pipelines to compute different attributes, I wonder the compute pipelines is parallel or serial.

### ISSUE THREAD

**Issue by juzi5230** [gfx-rs/wgpu#3000]
As the title, in the webgpu, I create two compute pipelines to compute different attributes, I wonder the compute pipelines is parallel or serial.

If they are serial, whether I can change them to be parallel.

thank you！

The following is the code: 

    const commandEncoder = device.createCommandEncoder()
    const computePass = commandEncoder.beginComputePass()
    computePass.setPipeline(pipelineObj.computePipeline)
    computePass.setBindGroup(0, pipelineObj.computeGroup)
    computePass.dispatchWorkgroups(Math.ceil(NUM / 128))
    computePass.end()

    const computePass1 = commandEncoder.beginComputePass()
    computePass1.setPipeline(pipelineObj.computeLightPipeline)
    computePass1.setBindGroup(0, pipelineObj.lightGroup)
    computePass1.dispatchWorkgroups(Math.ceil(NUM / 128))
    computePass1.end()

_Originally posted by @juzi5230 in https://github.com/gfx-rs/wgpu/discussions/2999_

**Comment by teoxoy** [comment]
Answered here: https://github.com/gfx-rs/wgpu/discussions/2999#discussioncomment-4315885
