### ISSUE TITLE
Colors on ANGLE are darker than expected

### ISSUE THREAD

**Issue by bigfarts** [gfx-rs/wgpu#3016]
**Description**
Colors on ANGLE are darker than expected, likely because of some sRGB color issue.

**Repro steps**
https://gist.github.com/bigfarts/3f051479c2c786d91f0b4e618d346dbc

This is just a basic drawing demo, which emits fragment color `vec4<f32>(0.5, 0.2, 0.3, 1.0)`.

**Expected vs observed behavior**
Vulkan:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/90592158/189181920-b261eab6-08d3-422d-8f83-ccefed0fb062.png">

Metal:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/90592158/189189865-ffbcae56-9fbd-416a-9101-9e294658c2d4.png">

ANGLE:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/90592158/189181754-4dc24365-f74b-438d-b4ef-7268a2d56b01.png">

**Extra materials**
The swapchain format selected on all of Vulkan, Metal, and ANGLE are Bgra8UnormSrgb, but it looks like ANGLE treats the input color as sRGB but Vulkan and Metal treat it as linear.

**Platform**
OS: Windows 11
wgpu version: v0.13.2
ANGLE version: https://github.com/google/gfbuild-angle/releases/tag/github%2Fgoogle%2Fgfbuild-angle%2Ff810e998993290f049bbdad4fae975e4867100ad

**Comment by cwfitzgerald** [comment]
I think this should not be an issue anymore.
