### ISSUE TITLE
Web and native backends disagree on some types being `Send` and `Sync`

### ISSUE THREAD

**Issue by i509VCB** [gfx-rs/wgpu#3026]
In #3025 when implementing static assertions to ensure types properly implement (or don't) `Send` and `Sync`, I noticed a few types do not agree depending whether you are compiling for web or native.

The following types differ on native and web:

| Type                 | Native            | Web               |
|---------------------|-------------------|--------------------|
| RenderPass     | Send + Sync | !Send + !Sync |
| ComputePass  | Send + Sync | !Send + !Sync |
| BufferView       | Send + Sync | !Send + !Sync |
| BufferViewMut | Send + Sync | !Send + !Sync |

**Comment by teoxoy** [comment]
Related: https://github.com/gfx-rs/wgpu/issues/2652 & https://github.com/gfx-rs/wgpu/issues/2884

**Comment by teoxoy** [comment]
Fixed by https://github.com/gfx-rs/wgpu/pull/3691
