### ISSUE TITLE
WebGL: `mat2x2<f32>` seems to be sized differently than `vec4<f32>`

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/wgpu#3028]
**Description**
`mat2x2<f32>` seems to be padded more than `vec4<f32>` on WebGL but possibly not on OpenGL

**Repro steps**
Run https://github.com/lobis/fractal-explorer/commit/ad9da1f5e2776ff6540cef62e55bcacbfdd91051 and its parent commit to see the differences, e.g. with wasm-pack or building with `cargo build --target wasm32-unknown-unknown` and `wasm-bindgen-cli`

**Expected vs observed behavior**
`mat2x2<f32>` in that example fails with browser warnings/errors when run with WebGL (not caught by the GL backend)

**Extra materials**
More details in https://github.com/gfx-rs/wgpu/discussions/3027#discussioncomment-3656241 and that thread

**Platform**
WebGL, wgpu 0.13

**Comment by cwfitzgerald** [comment]
Closing in favor of naga issue https://github.com/gfx-rs/wgpu/issues/4371
