### ISSUE TITLE
Question: Can we create a linear-space views of SRGB textures or SRGB views of linear-space textures?

### ISSUE THREAD

**Issue by yanchith** [gfx-rs/wgpu#3030]
I have a pipeline that is SRGB aware, but after a certain point I'd like to treat it as `Rgba8Unorm`, because I composite UI on top, and there's colors there that users set in code, so their eye does the correction already.

Tried to achieve this with a texture that is `Rgba8Unorm`, but creating an `Rgba8UnormSrgb` write view and a `Rgba8Unorm` read view. Unfortunately, the validator doesn't like it much:

```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Texture::create_view
    Unable to view texture Rgba8Unorm as Rgba8UnormSrgb
```

Is there a reason this shouldn't be working?

**Comment by cwfitzgerald** [comment]
This is supported in the spec, but we currently don't support this as no one has implemented it yet.

**Comment by yanchith** [comment]
Oh, that's great to hear! I think I'll need it eventually for the engine I am working on, and I'd be happy to implement it in wgpu when that happens (can't commit to specific dates yet, sorry).

I think we can label this as a feature request, meanwhile.

**Comment by expenses** [comment]
:+1: This is needed for using a srgb TextureView for the surface on the web.
