### ISSUE TITLE
Nintendo Switch support through Vulkan extensions

### ISSUE THREAD

**Issue by HeavyRain266** [gfx-rs/wgpu#3032]
**Is your feature request related to a problem? Please describe.**

This partially fixes problem with running ex. [Bevy Engine](https://github.com/bevyengine/bevy) on Nintendo Switch by providing full feature coverage for renderer.

**Describe the solution you'd like**

Current solution is implementation of `ash::extensions::nn::ViSurface` which implements Switch's surface for handling swapchain frames.

**Describe alternatives you've considered**

Only alternative is closed source implemention of the NVN API (GL-like)

**Additional context**

Further testing of the Switch compatibility requires closed source `winit` integration which will take some time to implement.

**Comment by expenses** [comment]
Should just be a case of adding a `create_surface_from_` function to wgpu-hal/vulkan like: https://github.com/gfx-rs/wgpu/blob/061e04bff1eea948a64f392087de8f6699c090b0/wgpu-hal/src/vulkan/instance.rs#L416-L433.

**Comment by expenses** [comment]
(and querying for support)

**Comment by HeavyRain266** [comment]
I will try that once I finish winit backend and see if you need some special code from NDA to initialize vulkan on switch.

**Comment by i509VCB** [comment]
In theory raw-window-handle could have a handle type for the switch?

The type is specified in the Vulkan specification and at least from a outsider's view that's all that Vulkan appears to need?

**Comment by HeavyRain266** [comment]
Talked with Nintendo about following extensions and usage is under NDA. Besides that, you also need some parts of their own Vulkan SDK which then has to do something with Nvidia too.

At the end, it's not possible to make it publicely available without violating NDA.

**Comment by i509VCB** [comment]
The extensions are in the registry though? However if there is undocumented usage requirements, then wgpu can't really do much about those.

**Comment by HeavyRain266** [comment]
It is public in registry because it's too much hassle to maintain their own registry and everything else required.
