### ISSUE TITLE
error: could not compile wgpu-hal due to 569 previous errors

### ISSUE THREAD

**Issue by manen** [gfx-rs/wgpu#3049]
i'm using arch linux with wayland on sway. examples run just fine, but when i attempt to run my own code (or actually just compile the standard rust hello world with wgpu 0.13.1 as dependency) it does this.

full `cargo check` output (it's a lot): https://gist.github.com/manen/3f6f049b585447a0921692077d6fef98

**Comment by manen** [comment]
using `editon = "2021"`

**Comment by cwfitzgerald** [comment]
If you're using a workspace, you need to manually add `resolver = "2"` to the workspace Cargo.toml - see https://github.com/gfx-rs/wgpu/issues/2356
