### ISSUE TITLE
Support for cubemaps

### ISSUE THREAD

**Issue by LaylConway** [gfx-rs/wgpu#306]
Currently, while you can create a view with `TextureViewDimension::Cube`, the texture won't work in a cube sampler.

https://github.com/gpuweb/gpuweb/issues/68 mentions always marking textures with `VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT`, but textures that are marked with it actually can't be used for regular sampling, so this isn't an option. There probably needs to be a spec change to really correctly feed this value through.

For now I've made a local copy of wgpu-native with the following code change:
```rust
    // Hacks in a special cases for arrays and cubemaps
    let view_capabilities = match desc.array_layer_count {
        1 => hal::image::ViewCapabilities::empty(),
        6 => hal::image::ViewCapabilities::KIND_CUBE,
        _ => hal::image::ViewCapabilities::KIND_2D_ARRAY,
    };
```

This (I hope) isn't acceptable as a solution, but I currently have no other way to mark a texture as being a cubemap without breaking the spec.

**Comment by LaylConway** [comment]
With the hack, the cubemaps do work without any additional changes needed, at least on the vulkan backend.

![vmmo-bin-client-pc_2019-08-22_21-27-38](https://user-images.githubusercontent.com/3094382/63544638-efd9c900-c525-11e9-98c6-1e8523023745.png)

**Comment by kvark** [comment]
@LaylConway 

> but textures that are marked with it actually can't be used for regular sampling, so this isn't an option

Please elaborate on that. IIRC, that flag allows you create cube texture views and non-cube texture views. The latter are perfectly fine for regular sampling.

**Comment by LaylConway** [comment]
I think I instead hit an issue with not following the spec, my bad. I had briefly tried setting KIND_CUBE on all textures, but the spec says that it can only be set for textures with >= 6 layers. This caused sampling on normal textures to just return black. Validation layers were off, that's why I didn't spot it until now.
