### ISSUE TITLE
[gles] firefox: WebGL warning: getSyncParameter

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#3064]
**Description**
Firefox reports `WebGL warning: getSyncParameter: ClientWaitSync must return TIMEOUT_EXPIRED until control has returned to the user agent's main loop. (only warns once)` 

Seems to happen in the most trivial examples. Chrome in contrast is happy

**Repro steps**
Can be observed in Bevy's samples
https://bevyengine.org/examples/2d/sprite/

**Platform**
webgl, firefox

**Comment by Wumpf** [comment]
Came up here before https://github.com/gfx-rs/wgpu/issues/2573#issuecomment-1161731826 - remained unclear if this is a firefox bug as I understand

**Comment by softmoth** [comment]
This is still an issue with Bevy 0.10.

**Comment by kdashg** [comment]
I will be making the warning quieter here: https://bugzilla.mozilla.org/show_bug.cgi?id=1822867

**Comment by cwfitzgerald** [comment]
Fixed upstream
