### ISSUE TITLE
`wgpu::backend::web::Context::queue_validate_write_buffer` is unimplemented

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#3085]
The body of the implementation of `wgpu::Context::queue_validate_write_buffer` for `web::Context` is a "TODO" comment. Presumably the underlying web APIs will do the validation anyway, but it would make `wgpu` present errors more consistently if we did implement this.

(This is no surprise to anyone, but I generally feel that "TODO" comments should be avoided in favor of issues, since our tools for tracking the latter are much better.)

https://github.com/gfx-rs/wgpu/blob/6451d31b7a0a1ce6dbcaf8cc7e6536ac06587f6d/wgpu/src/backend/web.rs#L2286-L2294

cc: @teoxoy

**Comment by teoxoy** [comment]
I think this was blocked by web_sys not exposing buffer size and usage.
