### ISSUE TITLE
derive(Hash) for DepthStencilState and DepthBiasState

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/wgpu#3087]
**Is your feature request related to a problem? Please describe.**

With the number of pipelines in use in a reasonably complicated program, it's useful to be able to cache wgpu::RenderPipeline objects. Most of the data involved in creating a RenderPipelineDescriptor is already hashable, but notably neither wgpu::DepthStencilState nor wgpu::DepthBiasState have a derive(Hash).

**Describe the solution you'd like**

Add #[derive(Hash)] to the remaining data-only structs involved in resource creation.

**Describe alternatives you've considered**

Users can manually implement hashing for these types in their own code, but they can't actually implement the Hash trait directly (3rd-party-impl rules), nor do they have the ability to auto-derive the implementation.

**Comment by killianc3** [comment]
It is not possible to `derive(Hash)` for `DepthBiasState` because it contains f32 types, same for `DepthStencilState`, or maybe I missed something ?

**Comment by swiftcoder** [comment]
Ah, shoot, yes, you are right. DepthBiasState would need a custom Hash impl (which could either naively treat those two floats as byte sequences, or have distinct handling for +/- zero and infinity), after which DepthStencilState could have a derived impl.

**Comment by killianc3** [comment]
Yes I see, after some research the implementation of a custom `hash` for `f32` is feasible, but, we have to depend on libraries like `ordered_float` or `num_traits` to transform into byte sequences. Maybe you have another idea or have done this implementation before, if so, I'd be interested to see it !

**Comment by grovesNL** [comment]
Custom hashing the descriptors with [`f32::to_bits`](https://doc.rust-lang.org/std/primitive.f32.html#method.to_bits) would probably be ok for all reasonable depth/stencil values.
