### ISSUE TITLE
Optimise creation functions

### ISSUE THREAD

**Issue by DagAgren** [gfx-rs/wgpu#309]
After some practical tests of running a simple game engine on top of libwgpu_native, I've noticed that the functions most likely to cause issues with performance seem to be create_bind_group and the create_buffer* functions. These can reasonably need to be called quite often (for instance if you have buffers that need to change in size), but are also quite slow at the moment.

Some profiling seems to indicate that the majority of the time in these function is spent inside wgpu code, and only a fairly small fraction in the underlying graphics library (in my case, Metal), so they seem a good candidate for some optimisation work.

**Comment by cwfitzgerald** [comment]
Closing as stale - from my profiling our resource creation is fairly efficient and if there's new-hal information saying it isn't please re-file!
