### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by evanshabsove** [gfx-rs/wgpu#3124]
**Description**
Hi there, I am trying to compile a bevy app I've built for wasm. When I run the file in the browser I get the following error in the console

```
panicked at 'index out of bounds: the len is 6 but the index is 6', /Users/macbook/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.13.2/src/gles/queue.rs:358:25
```

I'm just trying to figure out what could be going wrong, I've made a discussion thread in the Bevy github group as well 

https://github.com/bevyengine/bevy/discussions/6302

Which has some  additional information

**Repro steps**
You could try running my game (it's pretty basic and poor lol) 

https://github.com/evanshabsove/chat_platformer

running `bash run-wasm.sh` should generate the file

**Expected vs observed behavior**
Game runs in browser as expected

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**
MacOS Monterey V 12.6, Graphics AMD Radeon Pro 5300M

**Comment by tauseefk** [comment]
@evanshabsove were you able to put together a workaround?
I just ran into the same problem trying to deploy my Bevy + WASM prototype with Trunk.
In the past I've used WASM pack and a separate web repo with a Git workflow to deploy on pages, however I'd prefer to save some time and let Trunk handle it so I can focus on actually building the game.

**Comment by teoxoy** [comment]
On GLES, we force cube compatible textures to be cube textures since we need to infer the view type at creation time.

https://github.com/gfx-rs/wgpu/blob/9dc834a0ac694d576a584a89f72733a0bb2f4485/wgpu-hal/src/gles/mod.rs#L328-L334

A possible solution for this is tracked by https://github.com/gfx-rs/wgpu/issues/1614.

**Comment by teoxoy** [comment]
I think for now this can be worked around in `bevy_ecs_tilemap`, opened https://github.com/StarArawn/bevy_ecs_tilemap/issues/395.

Let's track progress on this front in https://github.com/gfx-rs/wgpu/issues/1614.
