### ISSUE TITLE
`QueueWriteBufferView` is strange.

### ISSUE THREAD

**Issue by botahamec** [gfx-rs/wgpu#3134]
According to the documentation for [`Queue::write_buffer_with`](https://docs.rs/wgpu/0.14.0/wgpu/struct.Queue.html#method.write_buffer_with):

> The returned value can be dereferenced to a `&mut [u8]`; dereferencing it to a `&[u8]` panics!

According to the documentation for [`Deref`](https://doc.rust-lang.org/nightly/core/ops/trait.Deref.html):

>  **this trait should never fail**. Failure during dereferencing can be extremely confusing when `Deref` is invoked implicitly.

**Comment by teoxoy** [comment]
Sadly there is no nice way to express this in rust since it's always valid to reborrow a `&mut T` as a `& T`.

**Comment by botahamec** [comment]
@teoxoy There's no reason why it needs to implement `DerefMut`. Preferably there would be a safer interface that replicates only the features of an array which make sense to use.

**Comment by botahamec** [comment]
@kpreid Is the idea that there might be a method that modifies a `&mut [u8]` but doesn't read from it that someone might want to use for writing to the buffer? The better interface there would probably just to use a method that returns a `&mut [u8]`. But I must say that this seems like a weird thing to need.

**Comment by botahamec** [comment]
What was the precedent?

I get that it's slow, but is it really worth it to crash on an implicit dereference? Especially when the docs for `Deref` say that it "must not fail", in bold. It's still possible to read from it anyway. If you really want to prevent reading, we could get something similar by just implementing `AsMut<[u8]>` but not `AsRef<[u8]>`.

**Comment by botahamec** [comment]
I could probably implement that, at least for the `QueueWriteBufferView`.

`BufferViewMut` might need some more brainstorming, as it is sometimes readable, but it shouldn't be too bad. The docs for `AsRef` have a pretty clear recommendation for what to do if it can fail, which is to not implement it, and instead just make your own `as_ref` which returns an `Option` or a `Result`. 

`BufferView` already just implements `Deref` and `AsRef`, so as far as I can tell, it should already be fine.
