### ISSUE TITLE
Feature request: disable uniformity analysis on shader creation

### ISSUE THREAD

**Issue by raphlinus** [gfx-rs/wgpu#3135]
Uniformity analysis of WGSL is too strict and fails to accept some valid shaders, including the coarse rasterization stage of [piet-gpu](https://github.com/linebender/piet-gpu). This is captured in an [upstream WGSL bug](https://github.com/gpuweb/gpuweb/issues/3479) and mitigations are being discussed. One such mitigation is to opt-out of the analysis.

I'd like a flag to disable uniformity analysis at shader creation time. That flag already exists in the naga API as `ValidationFlags`, but that's currently hardcoded to `all()` in wgpu-core's `Device::create_shader_module()` method, so basically what I'm asking is for that to be plumbed through.

The feature can be a temporary stopgap, and should probably be marked as such, until the issue is resolved upstream.

**Comment by ErichDonGubler** [comment]
Related/perhaps a dupe: https://github.com/gfx-rs/wgpu/issues/5320

**Comment by ErichDonGubler** [comment]
@raphlinus: Would implementing the WGSL diagnostic filter management per https://github.com/gfx-rs/wgpu/issues/5320 satisfy this particular request? That's not the same as your request to expose this on the API side, but if you're willing to add `diagnostic` directives in shader source, this might be a standards-supported way to do this.
