### ISSUE TITLE
Cannot compile for iOS

### ISSUE THREAD

**Issue by grenlight** [gfx-rs/wgpu#315]
When config my [app](https://github.com/grenlight/sdf-text-view)'s cargo dependencies to latest wgpu-rs [commit](https://github.com/gfx-rs/wgpu-rs/commit/c6522fa60b00af31a9703481bd3057c831c9249e),compiling to iOS failed:
<img width="1113" alt="Ping-Mu-Kuai-Zhao-2019-08-30-Xia-Wu2 19 46" src="https://user-images.githubusercontent.com/1001342/64018038-d1934f00-cb5d-11e9-9574-a959f828f248.png">
but compiling to macOS was successful.

**Comment by seivan** [comment]
@grenlight Maybe you need a `--features metal`? 
It shouldn't afaik drag in `gfx-backend-vulkan` for `iO`S & `macOS`.

**Comment by grenlight** [comment]
the latest commit removed backend features, so cannot use ``` --features metal```
