### ISSUE TITLE
WGPU hangs indefinitely, freezing whole computer when trying to create an instance of VULKAN

### ISSUE THREAD

**Issue by rhedgeco** [gfx-rs/wgpu#3158]
**Description**
Program hangs when trying to create an instance with the VULKAN backend, and sometimes if I dont `ctrl+C` fast enough the entire computer locks up and restart is necessary.

**Repro steps**
```rust
fn main() {
    // this line hangs
    let instance = wgpu::Instance::new(wgpu::Backends::VULKAN);

    // this line is never reached
    println!("I never get printed :(");
}
```

**Expected vs observed behavior**
No hanging plz thanks lol

**Extra materials**
No extra materials at this time. Cant keep computer up long enough to get info while hanging. Hangs debugger freezes up when trying to step through.

**Platform**
Laptop Brand: Framework Laptop
Processor: 11th Gen Intel® Core™ i7-1165G7 × 8
Graphics: Mesa Intel® Xe Graphics (TGL GT2)
Linux Version: 6.0.6-arch1-1
OS: Arch Linux
GNOME Version: 43.0
Windowing: Wayland (also tested and hangs on Xorg)

**Comment by rhedgeco** [comment]
Well, after updating system, it no longer hangs, it just takes like 30 seconds to create the instance. Better than hanging, but certainly the slowest ive ever seen it.

**Comment by cwfitzgerald** [comment]
I'm going to close this as a system issue
