### ISSUE TITLE
Specifying multiple `--target` at once turns on unwanted features

### ISSUE THREAD

**Issue by gilescope** [gfx-rs/wgpu#3182]
When I'm making something that targets desktop and wasm it would be great to compile them in one go:

`cargo check --target wasm32-unknown-unknown --target x86_64-apple-darwin`

Unfortunately while they individually work, I think the metal feature gets turned on for the wasm target and you get lots of errors if you do them together because it then can't find `mtl::`. I'm not sure if this is a fundamental limitation with cargo or whether we can tweak the Cargo.toml? Would be super cool if this worked out of the box.

**Describe alternatives you've considered**
Could just write a shell script to compile both of them but where's the fun in that?

**Additional context**
Being able to compile for multiple targets at once is fairly new for cargo.

**Comment by cwfitzgerald** [comment]
I didn't even know you could do that. I suspect, if it's compiling each crate once, but with merged features, we can't do anything about this, as we need target specific features for the backend.

**Comment by gilescope** [comment]
Cargo says it’s compiling twice the number crates so maybe it’s possible…

**Comment by teoxoy** [comment]
@gilescope I think with https://github.com/gfx-rs/wgpu/pull/3466 merged, this should now work fine. Could you give it another shot?

**Comment by daxpedda** [comment]
Indeed, I just tried it, works.

**Comment by teoxoy** [comment]
Thanks!
