### ISSUE TITLE
Manual refcounting on Metal

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#3191]
**Is your feature request related to a problem? Please describe.**
In DX12 we have a lightweight abstraction over a Com pointer that copies the value without touching the refcount. This is done ... because we can, in wgpu-hal at least. Everything is unsafe, and wgpu-hal doesn't manage lifetimes, so there is very little point to do refcounting internally for every copy (of the object data).

**Describe the solution you'd like**
Everything should basically store raw pointers to Metal objects, internally. We'd manually call `acquire`/`release` to control the object lifetime.

**Describe alternatives you've considered**
Possibly using the XxxRef objects, generated in metal-rs? Assuming they can be copied and not just borrowed.

**Additional context**
The backend already uses lightweight pointers as `BufferPtr`, `TexturePtr`, and `SamplerPtr`. I think we should just do it more aggressively in wgpu-hal's Metal backend.

Also, this isn't really a performance concern. The actual need here is to have `Api::Buffer` copyable at the API level. Same for textures and samplers. Whether or not Metal is the only blocker for this is an open question. WebGL may require non-copy semantics as well.

**Comment by cwfitzgerald** [comment]
See note on #3195
