### ISSUE TITLE
Make wgpu-hal resources impl Copy

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#3195]
**Is your feature request related to a problem? Please describe.**
#3191 describes it well enough.
By-move semantics doesn't really help anything in wgpu-hal. Implementations are mostly caring about copyable handles, and lifetimes are up to the user.

**Describe the solution you'd like**
Make `Api::Buffer`, `Api::Texture`, `Api::TextureView`, and `Api::Sampler` implement `Copy`.

**Describe alternatives you've considered**
We can't make *everything* copy, e.g. bind groups clearly need to carry arrays of data.
But the selected types are probably safe to do.

**Additional context**

**Comment by kvark** [comment]
I noticed that `DropGuard` is a blocker for this, e.g. #1609

**Comment by kvark** [comment]
Next blocker - Vulkan, somewhat unexpectedly.
Buffers and textures carry gpu-allock blocks...

**Comment by cwfitzgerald** [comment]
I'm not sure what problem this is actually solving? We abstract resources by IDs anyway, which are copyable

**Comment by kvark** [comment]
This wouldn't affect the users of wgpu, wgpu-native, or wgpu-core.
It would make wgpu-hal closer to the low level apis it abstracts over. And it could simplify some of the interaction between wgpu-core and wgpu-hal (less lifetimes to pass borrowed stuff).

Overall, it looks like wgpu-hal is *almost* able to do this. The benefit isn't that high, so we may as well not try pursuing it further.

**Comment by jimblandy** [comment]
The robust thing would be to go in the opposite direction and require all resources to implement `Drop`, but since destruction requires a `Device` that's not possible.

I wonder if it would be feasible to check wgpu-hal's MIR for attempts to Drop hal resources. Any such occurrences are bugs, right?

**Comment by kvark** [comment]
I don't think it's worth thinking about robustness too hard in the context of `wgpu-hal`. It's a totally unsafe API, there is near-zero need to make it safer. Note that all other resource objects in low-level APIs are `Copy`: Vulkan is `size_t`, Metal and D3D - pointers, GL - `u32` handles.

**Comment by cwfitzgerald** [comment]
After a serious vulnerability showed up in d3d due to copyable handles, I don't think this will ever really fly anymore. Having proper memory management for resources is extremely important, and copyability goes against that.
