### ISSUE TITLE
AMDVLK 2022.Q4.2 versus wgpu 0.12.0: [...Z ERROR wgpu::backend::direct] Error in Adapter::request_device: not enough memory left

### ISSUE THREAD

**Issue by jokeyrhyme** [gfx-rs/wgpu#3201]
Howdie, I've run into a bit of a strange one, and I'm not sure if it's a bug or if it's a bug somewhere else in the stack (probably the latter)

I thought I'd record this here just so that others can find it, hopefully

I just updated my Archlinux system and noticed right away that [`onagre`](https://github.com/oknozor/onagre) stopped working

However, it does work if I explicitly tell it to use RADV instead of AMDVLK, so I believe this has been broken by the new AMDVLK version (amdvlk 2022.Q4.2-1)

```
❯ AMD_VULKAN_ICD=RADV onagre
(works)
```

```
❯ AMD_VULKAN_ICD=AMDVLK onagre
[2022-11-10T21:49:55Z ERROR wgpu::backend::direct] Error in Adapter::request_device: not enough memory left
[2022-11-10T21:49:55Z ERROR wgpu::backend::direct] Error in Adapter::request_device: not enough memory left
Error: GraphicsAdapterNotFound
```

Other details of my system in case they are relevant:
- AMD Ryzen 7950X with integrated AMD GPU
- AMD Radeon RX 6800XT (discrete AMD GPU, and the one I plug my monitors into)

```
❯ uname -a
Linux myhnegon 6.0.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Nov 2022 18:01:58 +0000 x86_64 GNU/Linux
```

**Comment by jokeyrhyme** [comment]
`wezterm` just started using wgpu 0.14.0: https://github.com/wez/wezterm/blob/8479be746552db7d927a0dc8f31b4c5f751a2dfe/wezterm-gui/Cargo.toml#L102

has similar unexpected behaviour

**Comment by teoxoy** [comment]
This sounds like a driver bug. Let's see what the resolution of https://github.com/GPUOpen-Drivers/AMDVLK/issues/305 will be.

**Comment by jokeyrhyme** [comment]
Yes, this was a driver bug, fixed now
