### ISSUE TITLE
Doc comment typo

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#3202]
`texture_2d` -> `texture_2d`

https://github.com/gfx-rs/wgpu/blob/3c82a4cd5c7aaf61aa4b4e9a6d6ea8e881cfb411/wgpu-types/src/lib.rs#L4566

**Comment by cwfitzgerald** [comment]
This was since fixed (https://github.com/gfx-rs/wgpu/pull/3608).
