### ISSUE TITLE
wgpu fails to compile using cargo

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [gfx-rs/wgpu#3209]
cargo 1.65.0
tried to compile https://github.com/galoomba1/miratope-rs

**Comment by H-A-M-G-E-R** [comment]
i understood

**Comment by H-A-M-G-E-R** [comment]
it says
error[E0597]: `desc_set` does not live long enough
    --> CENSORED\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.2\src\device\mod.rs:1792:26
     |
1792 |                     set: desc_set.raw_mut(),
     |                          ^^^^^^^^^^^^^^^^^^ borrowed value does not live long enough
...
1813 |     }
     |     -
     |     |
     |     `desc_set` dropped here while still borrowed
     |     borrow might be used here, when `write_map` is dropped and runs the `Drop` code for type `BTreeMap`
     |
     = note: values in a scope are dropped in the opposite order they are defined

**Comment by cwfitzgerald** [comment]
This is https://github.com/gfx-rs/wgpu/pull/2968 - a release to fix this will be out shortly.
