### ISSUE TITLE
Take `IntoIterator` instead of slices in various descriptors

### ISSUE THREAD

**Issue by PROMETHIA-27** [gfx-rs/wgpu#3220]
**Is your feature request related to a problem? Please describe.**
While writing a render graph/abstraction library on top of wgpu, I've noticed that a lot of unnecessary allocations are made necessary by functions/descriptors taking slices instead of iterators. The basic idea is that I have some type, `MyBindGroup` (or whatever I'm wrapping) which contains the corresponding wgpu type. Instead of being able to pass in a iterator of `MyBindGroup` mapped to their inner types, I have to allocate a vec, dump the inner types in the vec, and then borrow that for a single line and immediately drop it. 

**Describe the solution you'd like**
Change `BindGroupLayoutDescriptor`, `PipelineLayoutDescriptor`, and possible other API's that aren't immediately obvious to me to take `I: IntoIterator<T>` instead of `&[T]`. I'd be willing to make a PR for this if this seems acceptable. I did check internally to see if this is actually feasible and it seems like these slices are simply `.iter()`'d, and only `.iter()`'d, so I don't see any issue with it. For example, if I make a `Vec<BindGroupLayout>`, in order to pass them to a `PipelineLayoutDescriptor` another `Vec` must be allocated instead of using `.iter()`.

**Describe alternatives you've considered**
- I can be forced to make many small temporary allocations, which is unnecessarily wasteful.
- I did notice the `ArrayVec` crate, which might be useful in reducing the performance impact of these temporary allocations, but I still find that a undesirable solution, especially for e.g. individual `BindGroupLayoutEntry`'s of which there can be far more than a reasonable amount to stack allocate.
- If there are any other solutions, I would like to know them.

**Additional context**
There would be a complexity cost to this as it will introduce a sizeable amount of additional generics. I think it's worth it for the flexibility, performance, and ergonomics. 
This also may go against some philosophy/direction of the wgpu-rs project that I'm unaware of, as I've noticed the API bears a very close resemblance to the wgpu spec, and afaik the spec contains no mention of iterators.

**Comment by cwfitzgerald** [comment]
We used to do this all over the place in gfx (predecessor to wgpu) and gfx-hal (the predecessor to wgpu-hal) and we intentionally didn't do it when writing the newer abstractions.

I asked @kvark on the matrix about the history of this choice and his response was:

> I don't recall this properly written down, but I did complain about the type complexity in https://vimeo.com/621152607 (around 15:30 mark).
> My view on this is that we tended to overcomplicate type signatures for dubious benefit, and this issue 3220 is proposing exactly this. The extra allocation on the creation of a BGL or PL is nothing at all to worry about. These are some of the least dynamic objects in the API.

I am in agreement that the complexity needed to make them fully generic would well outweigh any small wins we get, especially when those small wins can be achieved by other, less intrusive ways, like memory pools.
