### ISSUE TITLE
STATUS_ACCESS_VIOLATION despite my graphics drivers being directx12 compatable

### ISSUE THREAD

**Issue by RosaKadar** [gfx-rs/wgpu#3222]
I have been having this issue for some time and really did not know where to ask, when I run an example(or anything else) I get exit code: 0xc0000005, STATUS_ACCESS_VIOLATION, despite as you can see my computer being directx12 compatible 
![image](https://user-images.githubusercontent.com/93528120/202920342-403e45fd-f077-496f-a4db-564a53f6fff2.png)

**Comment by francesco-cattoglio** [comment]
I am sorry to tell you, but your integrated VGA is likely not compatible with DirectX 12.
Your CPU is an i5-2520M, which according to Intel website has an Intel® HD Graphics 3000 VGA. This is quite old and is probably missing some required features. This likely means that you cannot run DirectX 12 software even though the reported installed version is DirectX 12

**Comment by RosaKadar** [comment]
Alright, I see.

**Comment by RosaKadar** [comment]
I ran it through GDB and it somehow pointed me to a file from OBS studio i had in app data as the cause for the issues, which after i deleted it pointed me towards overwolf(the mod launcher for games) and after i deleted both it started working but telling me it's using microsoft basic render driver and that "initialization of object failed"

**Comment by cwfitzgerald** [comment]
wgpu worked though, just giving an error message on initialization?

Getting segfaults from those things are pretty common and nothing we can really do about it.

**Comment by RosaKadar** [comment]
i see, yes it does work now, just with an error on initialization and with the wrong graphics driver

**Comment by cwfitzgerald** [comment]
Great
