### ISSUE TITLE
Not possible to write a function that takes a pointer argument

### ISSUE THREAD

**Issue by gmilleramilar** [gfx-rs/wgpu#3230]
**Description**
It's not possible to write a function that takes a pointer argument?  There seems to be no value for the "address space" generic
parameter for ptr that compiles.

**Repro steps**
This contrived function does not compile, regardless of which address space you use for the pointer.

`fn contrived(a:ptr<storage, array<f32>>) ->u32 {
    return arrayLength(*a);
}`

Each of "function", "private", "workgroup", "uniform", "storage" and "handle" result in different errors from the compiler.

**Extra materials**
Here are the error messages for each of the possible values.

C:\Users\gmiller_amilarcap\dev\wgpu\wgpu\examples\hello-compute>cargo run --example hello-compute
   Compiling wgpu v0.14.0 (C:\Users\gmiller_amilarcap\dev\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.43s
     Running `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe`
No numbers were provided, defaulting to [1, 2, 3, 4]
[2022-11-23T14:49:34Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
  ┌─ :5:16
  │
5 │ fn contrived(a:ptr<function, array<f32>>) ->u32 {
  │                ^^^^^^^^^^^^^^^^^^^^^^^ naga::Type [5]

    Type [5] '' is invalid
    Unsized types like [4] must be in the `Storage` address space, not `Function`

', wgpu\src\backend\direct.rs:2510:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe` (exit code: 101)

C:\Users\gmiller_amilarcap\dev\wgpu\wgpu\examples\hello-compute>cargo run --example hello-compute
   Compiling wgpu v0.14.0 (C:\Users\gmiller_amilarcap\dev\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.42s
     Running `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe`
No numbers were provided, defaulting to [1, 2, 3, 4]
[2022-11-23T14:49:55Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
  ┌─ :5:16
  │
5 │ fn contrived(a:ptr<private, array<f32>>) ->u32 {
  │                ^^^^^^^^^^^^^^^^^^^^^^ naga::Type [5]

    Type [5] '' is invalid
    Unsized types like [4] must be in the `Storage` address space, not `Private`

', wgpu\src\backend\direct.rs:2510:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe` (exit code: 101)

C:\Users\gmiller_amilarcap\dev\wgpu\wgpu\examples\hello-compute>cargo run --example hello-compute
   Compiling wgpu v0.14.0 (C:\Users\gmiller_amilarcap\dev\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.40s
     Running `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe`
No numbers were provided, defaulting to [1, 2, 3, 4]
[2022-11-23T14:50:15Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
  ┌─ :5:16
  │
5 │ fn contrived(a:ptr<workgroup, array<f32>>) ->u32 {
  │                ^^^^^^^^^^^^^^^^^^^^^^^^ naga::Type [5]

    Type [5] '' is invalid
    Unsized types like [4] must be in the `Storage` address space, not `WorkGroup`

', wgpu\src\backend\direct.rs:2510:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe` (exit code: 101)

C:\Users\gmiller_amilarcap\dev\wgpu\wgpu\examples\hello-compute>cargo run --example hello-compute
   Compiling wgpu v0.14.0 (C:\Users\gmiller_amilarcap\dev\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.42s
     Running `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe`
No numbers were provided, defaulting to [1, 2, 3, 4]
[2022-11-23T14:50:36Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
  ┌─ :5:16
  │
5 │ fn contrived(a:ptr<uniform, array<f32>>) ->u32 {
  │                ^^^^^^^^^^^^^^^^^^^^^^ naga::Type [5]

    Type [5] '' is invalid
    Unsized types like [4] must be in the `Storage` address space, not `Uniform`

', wgpu\src\backend\direct.rs:2510:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe` (exit code: 101)

C:\Users\gmiller_amilarcap\dev\wgpu\wgpu\examples\hello-compute>cargo run --example hello-compute
   Compiling wgpu v0.14.0 (C:\Users\gmiller_amilarcap\dev\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.44s
     Running `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe`
No numbers were provided, defaulting to [1, 2, 3, 4]
[2022-11-23T14:51:00Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module

Shader validation error:
  ┌─ :5:1
  │
5 │ ╭ fn contrived(a:ptr<storage, array<f32>>) ->u32 {
  │                  ^^^^^^^^^^^^^^^^^^^^^^ naga::Type [5]
6 │ │     return arrayLength(*a);
  │ ╰───────────────────────────^ naga::Function [1]

    Function [1] 'contrived' is invalid
    Argument 'a' at index 0 is a pointer of space Storage { access: LOAD }, which can't be passed into functions.

', wgpu\src\backend\direct.rs:2510:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe` (exit code: 101)

C:\Users\gmiller_amilarcap\dev\wgpu\wgpu\examples\hello-compute>cargo run --example hello-compute
   Compiling wgpu v0.14.0 (C:\Users\gmiller_amilarcap\dev\wgpu\wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.44s
     Running `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe`
No numbers were provided, defaulting to [1, 2, 3, 4]
[2022-11-23T14:51:21Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module

Shader '' parsing error: unknown address space: 'handle'
  ┌─ wgsl:5:20
  │
5 │ fn contrived(a:ptr<handle, array<f32>>) ->u32 {
  │                    ^^^^^^ unknown address space

    unknown address space: 'handle'

', wgpu\src\backend\direct.rs:2510:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\gmiller_amilarcap\dev\wgpu\target\debug\examples\hello-compute.exe` (exit code: 101)

**Platform**
Windows 11

**Comment by cwfitzgerald** [comment]
`array<T>` is only valid inside the storage space - simultaneously it's invalid to have a pointer into storage memory. You should be able to have a pointer to `ptr<function, array<T, 5>>` or so.
