### ISSUE TITLE
Seg Fault in many examples

### ISSUE THREAD

**Issue by opfromthestart** [gfx-rs/wgpu#3263]
**Description**
Many examples will crash after the first frame, where they should run further.
As well, some examples render incorrectly, or run with lots of errors, which I believe is a bug.
It appears to be related to #2338 and #2438.

boids - Runs and appears correct, but gives lots of errors. A sample of them are given below, as many errors are produced each frame.
bunnymark - Runs but icon does not appear. Similar errors to boids.
conservative-raster - Runs and appears correct, other than a white outline of a triangle. Similar errors to boids.
cube - Runs and appears correct, like screenshot-lines. Similar errors to boids.
hello-triangle - Runs and appears correct. Similar errors to boids given below.
hello-windows - Runs and appears correct. Similar errors to boids.
mipmap - Crashes with seg fault. Output and backtrace below.
msaa-line - Crashes with seg fault. Output and backtrace below.
shadow - Crashes with seg fault.
skybox - Crashes with seg fault.
teture-arrays - Runs and appears correct. Similar errors to boids.
water - Crashes with seg fault.
Ones not listed seemed to not work for other reasons.

**Repro steps**
Run the examples under the platform given below. I can't reinstall myself so cannot be sure it is a machine bug, but I have seen similar issues on Mint.

**Expected vs observed behavior**
I expect the examples to run and look like the screenshots. Instead, some crash and some do not render the proper image.

**Extra materials**
[boid_log.txt](https://github.com/gfx-rs/wgpu/files/10156385/boid_log.txt)
[hello_triangle_log.txt](https://github.com/gfx-rs/wgpu/files/10156414/hello_triangle_log.txt)
[mipmap_log.txt](https://github.com/gfx-rs/wgpu/files/10156449/mipmap_log.txt)
[msaa-line_log.txt](https://github.com/gfx-rs/wgpu/files/10156495/msaa-line_log.txt)

**Platform**
Linux Mint 20.3

Intel Corporation UHD Graphics
GeForce GTX 1650 SUPER
nvidia-driver-510
I am using the latest version of wgpu, 1.14.0.
I am using rustc 1.65.0.

**Comment by cwfitzgerald** [comment]
The vulkan validation layers you have appear to be very old (from the vk 1.1 days), which is causing the crashes. Can you update your vulkan sdk via https://vulkan.lunarg.com/sdk/home#linux and try again?
