### ISSUE TITLE
`Features::SHADER_PRIMITIVE_INDEX` should be supported on all native platforms

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#3269]
Naga's glsl, hlsl, msl and spv backends support `Builtin::PrimitiveIndex` but `wgpu` only advertises support for `Features::SHADER_PRIMITIVE_INDEX` on the Vulkan backend.

**Comment by cwfitzgerald** [comment]
Is there anything we need to do for this, or do we just flip the switch?

**Comment by teoxoy** [comment]
I think it is a matter of just flipping the switch, yeah.
