### ISSUE TITLE
Fix remaining tests for WebAssembly

### ISSUE THREAD

**Issue by haraldreingruber** [gfx-rs/wgpu#3282]
After adding support for running the current tests via WebAssembly in the browser (#3238), there were 2 tests that were not easily fixable for the WebAssembly target.

1. `clear_texture.rs` pass, but there are `texSubImage2D: invalid format` warnings in the browser dev-console. Which probably means that there are some false-positives.
2. `buffer_copy.rs` is executing code that is expected to panic. As catching an unwinding panic is not working for WASM, a [workaround needs to be used](https://github.com/gfx-rs/wgpu/pull/3238#issuecomment-1340290733). For this test, the workaround doesn't work because apparently the panic is not getting redirected to the error scope of the device.

In order to make tests to be executed by the WASM browser test, the `#[wasm_bindgen_test]` attribute needs to be added (next to the usual `#[test]`)

**Comment by cwfitzgerald** [comment]
I think it would end up as wasm specific code which accesses the webgl2 context directly. All other apis have callback systems (including native gl https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/gles/egl.rs#L232) which we already hook.

**Comment by cwfitzgerald** [comment]
Closing as old, see #3678 for more info about current state
