### ISSUE TITLE
`GpuAutoLayoutMode::Auto` throws an error on Firefox Nightly

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/wgpu#3284]
**Description**
When using `layout: None` parameter to create `ComputePipeline`, runs perfectly in chrome Canary, but the following error occurs when running on Firefox Nightly:
```log
Uncaught (in promise) TypeError: GPUDevice.createComputePipeline: 'layout' member of GPUPipelineDescriptorBase is not an object.
```

**Repro steps**
```rust
device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                layout: None,
                module: &shader,
                entry_point: "cs_main",
                label: None,
            });
```

**Extra materials**

[My code](https://github.com/jinleili/learn-wgpu-zh/blob/98bb9155875e258ecffacfe46e3a4101a2e0a5b2/code/intermediate/compute-pipeline/src/blur_node.rs#L21-L26)

[Online demo](https://jinleili.github.io/learn-wgpu-zh/intermediate/compute-pipeline/#运行示例代码)，need to click the `点击运行 Compute_pipeline` button manually.

**Platform**
Firefox Nightly, Chrome Canary

**Comment by cwfitzgerald** [comment]
This is a problem with Firefox being behind where we are in the spec.
