### ISSUE TITLE
WebGPU Device Limits

### ISSUE THREAD

**Issue by unfolding18** [gfx-rs/wgpu#3299]
**Is your feature request related to a problem? Please describe.**
When compiling to WebGPU, you cannot specify device limits beyond the default limits provided by the implementation - for example, if you wish to request that the `max_storage_buffer_binding_size` limit be increased. Currently, any user-defined limits are simply ignored, as seen here: https://github.com/gfx-rs/wgpu/blob/master/wgpu/src/backend/web.rs#L1237

**Additional context**
After some discussion with several users on Matrix, it seems that the issue stems from the fact that `web-sys` doesn't have any bindings for setting the limits in https://docs.rs/web-sys/latest/web_sys/struct.GpuDeviceDescriptor.html

The struct contains a member that is `record<DOMString, GPUSize64> requiredLimits`, which apparently is where the problem starts (`record<>` is not supported by web-sys?). Maybe others can chime in with additional context here.

**Comment by FL33TW00D** [comment]
This was fixed with a polyfill for record in: https://github.com/gfx-rs/wgpu/pull/4107
