### ISSUE TITLE
Provide alternate implementations for browsers that do not provide WebGPU

### ISSUE THREAD

**Issue by 823984418** [gfx-rs/wgpu#3311]
Provide deno_webgpu precompiled results enable me to load this library when I confirm that the browser does not have a WebGPU.
And one small request: CPU fallback adapter.

**Comment by cwfitzgerald** [comment]
I'm not sure what you're asking for here

**Comment by teoxoy** [comment]
We already have support for GLES 3 (WebGL 2) for browser targets - these adapters/devices are however not WebGPU spec compliant.
