### ISSUE TITLE
INDIRECT_EXECUTION downlevel flag not set on 2080SUPER, driver 527.56, vulkan backend

### ISSUE THREAD

**Issue by apessino** [gfx-rs/wgpu#3318]
After updating today, my desktop apps no longer run because the `INDIRECT_EXECUTION` downlevel flag is not set. Latest NVidia studio driver on a 2080 SUPER using the vulkan backend, windows 10. A call to `downlevel_capabilities.is_webgpu_compliant()` returns `false`, as expected.

All other downlevel flags are set (`get_downlevel_capabilities()` returns 0x7FFFB) but the indirect bit is 0 for some reason. This adapter obviously supports indirect drawing/calls, and the flag is set if I use the DX12 backend.

Any suggestions as to what could be causing this on vulkan? Thanks...

**Comment by cwfitzgerald** [comment]
Likely caused by https://github.com/gfx-rs/wgpu/pull/3316

**Comment by apessino** [comment]
Indeed that was the issue - thank you!
