### ISSUE TITLE
Validation Error with bevy

### ISSUE THREAD

**Issue by T0mstone** [gfx-rs/wgpu#3322]
I encountered this error while trying out bevy and after looking into similar errors<sup>1</sup>,
I came to the conclusion that it is probably a bug in wgpu.

<sup>1</sup>) What led me here was [bevy#5419](https://github.com/bevyengine/bevy/issues/5416) in particular,
which links to [#2925](https://github.com/gfx-rs/wgpu/issues/2925) here, which has apparently been resolved now;
My error message looks very similar to that one (though not the exact same, mind you).

**Description**
A basic dummy bevy project gives several `VALIDATION` error messages when run.

**Repro steps**
add `bevy = "0.9.1"` as a dependency to a new cargo project,
then write the following in `main.rs`:
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run()
}
```
and finally run it.

**Expected vs observed behavior**
I expected it to open a window and sit there doing nothing.
Instead, there are lots of error messages (a lot of which are repeated, probably because bevy tries the same thing each frame).
The specific errors I get are `VUID-vkResetCommandPool-commandPool-00040`, `VUID-vkDestroyBuffer-buffer-00922` and `VUID-vkDestroyImage-image-01000`.

**Extra materials**
The whole output log (with repeated error messages): [output.zip](https://github.com/gfx-rs/wgpu/files/10273146/output.zip)

**Platform**
OS: Ubuntu 20.04.5 LTS
Graphics Card: AMD Radeon RX 5700 XT
Rust: bevy 0.9.1, which uses wgpu 0.14.2

**Comment by cwfitzgerald** [comment]
Your validation layers seem a bit old, try updating them from https://vulkan.lunarg.com/sdk/home#linux

**Comment by T0mstone** [comment]
That fixed it, thank you very much!
