### ISSUE TITLE
Renderdoc dont like Vulkan

### ISSUE THREAD

**Issue by Snowiiii** [gfx-rs/wgpu#3331]
**Description**
Its Really weird,I know my GPU supports Vulkan (1.3) and ye i want that the App Runs in Vulkan but when i Ran the in Renderdoc its Says that i currently in a GLES Context so i changes the Backend from all -> Vulkan but if i run the App normal its will Start like normal but if if Start the App in Renderdoc the App crashes instandly 
(Btw if the Apps uses GLES its works in Renderdoc)

**Repro steps**
Run the App in Renderdoc with Vulkan as Backend

**Expected vs observed behavior**
Expected: The App dont Crash UwU
observed: The App Crashes :c

**Platform**
Linux Arch: 6.1.1-zen1-1-zen
WGPU: 0.14.2 (lastest)

(Sorry for my English)

**Comment by cwfitzgerald** [comment]
Thanks for filling!

If you are using a system with wayland as the default window server, renderdoc does not support wayland and will not be able to find a (renderdoc connected) device to render to a wayland window. You can, however, tell winit to go into X11 mode by setting the `WINIT_UNIX_BACKEND=x11` environment variable
