### ISSUE TITLE
passing mismatched texture format causes validation errors

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#334]
When porting to 0.3.0, I did not notice the texture format for depth textures changed `wgpu::TextureFormat::Depth32Float`, from previously `wgpu::TextureFormat::R32Float`.

Everything compiles, etc., but when run, the gpu complains:

```
VALIDATION [VUID-vkCmdBeginRenderPass-initialLayout-00896 (0)] : Layout/usage mismatch for attachment 1 in VkRenderPass 0x75[] - the initial layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL but the image attached to VkFramebuffer 0xae[] via VkImageView 0x87[] was not created with VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT The Vulkan spec states: If any of the initialLayout or finalLayout member of the VkAttachmentDescription structures or the layout member of the VkAttachmentReference structures specified when creating the render pass specified in the renderPass member of pRenderPassBegin is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL, or VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL then the corresponding attachment image view of the framebuffer specified in the framebuffer member of pRenderPassBegin must have been created with a usage value including VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdBeginRenderPass-initialLayout-00896)
object info: (type: IMAGE, hndl: 133)
```

Changing to above depth fixes the problem. Can we make this a compile time error somehow?

**Comment by m4b** [comment]
> Depth format was never `R32Float`, it was `D32Float`.

Hah, whoops! Wasn't caught by validation before, so that's interesting. Ideally this isn't a runtime issue; seems like would be fairly straightforward to ensure this at compile time?

**Comment by kvark** [comment]
What do you have in mind for catching this at compile time?

**Comment by m4b** [comment]
If only one format is acceptable then seems pretty straightforward to make it compile time checked. Eg typestate pattern would probably work.

But that might be too invasive in the current api design is my guess ?

**Comment by kvark** [comment]
I don't quite see how this would work. When texture is created, you never tell explicitly if it's a "depth" texture or a "color" texture. You are providing the usage mask and the format among other things. A texture can then be re-interpret under a different format when creating a view. Say, you created `R32Float` texture and then you created a view of type `Depth32Float`. I don't see how the rich typing would support that. FYI, any type-level experiments would need to be done in wgpu-rs (and not here).

**Comment by yanchith** [comment]
Oh, the view re-interpretation is really interesting. What are the rules of what view is valid to create for a texture? Does it need to have same-sized pixels? Is the re-interpretation just a bit-wise transmute, or is there something else happening (e.g. int to normalized float)?

As for the type-level fix for this, I once did something similar for WebGL in TypeScript (https://github.com/yanchith/webglutenfree/blob/master/src/texture.ts). it involved creating separate enums for color and depth-stencil formats and Textures being generic over format (not sure this is expressible in rust without const generics). It was a lot of typing overall and the compiler errors for the case the programmer got it wrong were horrible. I am personally fine with development-time run-time validation here.

**Comment by kvark** [comment]
Restrictions for re-interpretation are slightly different in the APIs (see https://github.com/gpuweb/gpuweb/issues/79), but the main rule is that it's just a bit-wise transmute.

**Comment by kvark** [comment]
I believe we are validating the formats now, please re-open otherwise!
