### ISSUE TITLE
GLES 3.0 Binding Model Broken with Shared Vertex/Fragment Uniform Buffers

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#3349]
**Description**

Due to GLES 3.0 not having binding indexes, we need to rely completely on reflection to bind all the buffers in the right place. Naga (correctly) generates unique names and structures and such for the vertex and fragment shaders. Because there are no binding indexes, GLES matches up bindings by name of the struct, and because they are different, creates different bindings for each stage.

Our choices are to:
- Change our binding model to bind buffers separately for vertex and fragment on GLES 3.0.
- Try to share the binding across states. This unfortunately also means that the structs in vertex and fragment must be _identical_, and this is not a requirement of WebGPU at all.

In order to not add this giant requirement, we should change our binding model.

**Repro steps**

Bind a buffer to both vertex and fragment shaders in GLES 3.0.

**Expected vs observed behavior**

Only one of the buffers will be correctly bound, the other won't be. This will cause all sorts of nonsense.

**Comment by ryankaplan** [comment]
Hi again @cwfitzgerald! Can you help me figure out if I'm running into this issue? The repro steps are `Bind a buffer to both vertex and fragment shaders in GLES 3.0` but I'm not sure what this means from the perspective of the wgpu API. Is it sufficient to draw using a uniform buffer that is bound to uniforms with both `wgpu::ShaderStages::VERTEX` and `wgpu::ShaderStages::FRAGMENT` visibility?

**Comment by cwfitzgerald** [comment]
Yeah - binding a single buffer with VERTEX_FRAGMENT doesn't work. It will only end up binding to one stage.

**Comment by ryankaplan** [comment]
So I'm extra sure, you're saying that this is no good...

```
wgpu::BindGroupLayoutEntry {
  // Problem: we will bind to only one of these...
  visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
  ...
}
```

But I could, for example, split the above layout entry into two layout entries that bind to the same buffer that I bound to before. Does that sound right?

**Comment by cwfitzgerald** [comment]
Correct!

**Comment by cwfitzgerald** [comment]
This bug doesn't exist.

I do not have the original reproduction for this issue and the test I wrote for it passes every time.

Notably we use glUniformBlockBinding to bind the blocks on the CPU side, which allows us to call bind once to multiple blocks, and everything is happy.

The reproduction still found a bug in #4607, so I'm going to keep it in the PR.

**Comment by ryankaplan** [comment]
That matches what I'm seeing too. Splitting my layouts into separate FRAGMENT | VERTEX usages didn't seem to change anything for me.
