### ISSUE TITLE
iOS: GPU Timeout and Discarded

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#336]
On wgpu `0.3.0` + winit `0.20.0-alpha3` i'm seeing what appear to be new gpu errors.

The application loads successfully, a single frame is rendered, and then I see:

```
2019-09-09 22:46:02.894432-0700 test[13776:6361225] Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)
2019-09-09 22:46:02.894697-0700 test[13776:6361225] Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (IOAF code 5)
```

It will sit in this state until I touch the screen, then winit panics with a dpi assertion:

```
thread '<unnamed>' panicked at 'assertion failed: validate_hidpi_factor(dpi_factor)', /Users/ataraxis/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.20.0-alpha3/src/dpi.rs:113:9
```

I think this is a red herring; I've printed the dpi I get from winit (`3.0`), and it seems ok. I suspect the window has already died and dpi returns some random value, which triggers the assert? Or maybe not, I'm not totally sure.

**Comment by kvark** [comment]
Possibly addressed by  #337

**Comment by seivan** [comment]
#337 Fixed it for me, but I am using SDL2. 
That being said, before the fix I used to get the same errors sans the panic.

**Comment by kvark** [comment]
Alright, I'm going to close this then. Thanks for testing!
Please re-open if needed.

**Comment by m4b** [comment]
K thanks for testing, I will try to checkout master this weekend and see if it fixes it for me, and report back here

**Comment by m4b** [comment]
I have confirmed that the messages to the console in this issue are gone in master, but the panic remains :/

So this seems to be a winit issue...
