### ISSUE TITLE
DX12: internal panic

### ISSUE THREAD

**Issue by xiaopengli89** [gfx-rs/wgpu#3360]
**Description**
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    Internal error in VERTEX | FRAGMENT | VERTEX_FRAGMENT shader: 0x887A0005

```

The error occurs on some specific intel platforms with release mode, the root cause is `D3DCompile` without `D3DCOMPILE_SKIP_OPTIMIZATION` may do the code generation incorrectly, it's probably a driver bug.

It might help users if we could provide the capability to specify instance flags.

similar issue #2472 

**Platform**
Windows 10, [a06ef71](https://github.com/gfx-rs/wgpu/commit/a06ef71fd773914f7bd68773054a1a2222d70f98)

**Comment by teoxoy** [comment]
Isn't this a duplicate of https://github.com/gfx-rs/wgpu/issues/2472?

**Comment by xiaopengli89** [comment]
This should be fixed with dxc compiler.
