### ISSUE TITLE
Advisory errors on CI

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#3368]
**Description**

There have been security issue(s) on our dependencie(s)

We get the following error on CI, it should be simple to fix (just update a few dependencies hopefully).

```

  1.64-x86_64-unknown-linux-musl installed - rustc 1.64.0 (a55dd71d5 2022-09-19)

error[vulnerability]: reject_remote_clients Configuration corruption
    ┌─ /github/workspace/Cargo.lock:252:1
    │
252 │ tokio 1.21.1 registry+https://github.com/rust-lang/crates.io-index
    │ ------------------------------------------------------------------ security vulnerability detected
    │
    = ID: RUSTSEC-2023-0001
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0001
    = On Windows, configuring a named pipe server with [pipe_mode] will force [ServerOptions]::[reject_remote_clients] as `false`.
      
      This drops any intended explicit configuration for the [reject_remote_clients] that may have been set as `true` previously.
      
      The default setting of [reject_remote_clients] is normally `true` meaning the default is also overriden as `false`.
      
      ## Workarounds
      
      Ensure that [pipe_mode] is set first after initializing a [ServerOptions]. For example:
      
      ```rust
      let mut opts = ServerOptions::new();
      opts.pipe_mode(PipeMode::Message);
      opts.reject_remote_clients(true);
      ```
      
      [ServerOptions]: https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/struct.ServerOptions.html
      [pipe_mode]: https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/struct.ServerOptions.html#method.pipe_mode
      [reject_remote_clients]: https://docs.rs/tokio/latest/tokio/net/windows/named_pipe/struct.ServerOptions.html#method.reject_remote_clients
    = Announcement: https://github.com/tokio-rs/tokio/security/advisories/GHSA-7rrj-xr53-82p7
    = Solution: Upgrade to >=1.18.4, <1.19.0 OR >=1.20.3, <1.21.0 OR >=1.23.1
    = tokio v1.21.1
      ├── cts_runner v0.1.0
      ├── deno_web v0.111.0
      │   └── cts_runner v0.1.0 (*)
      └── deno_webgpu v0.81.0
          └── cts_runner v0.1.0 (*)

warning[unmaintained]: xml-rs is Unmaintained
    ┌─ /github/workspace/Cargo.lock:337:1
    │
337 │ xml-rs 0.8.4 registry+https://github.com/rust-lang/crates.io-index
    │ ------------------------------------------------------------------ unmaintained advisory detected
    │
    = ID: RUSTSEC-2022-0048
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2022-0048
    = xml-rs is a XML parser has open issues around parsing including integer
      overflows / panics that may or may not be an issue with untrusted data.
      
      Together with these open issues with Unmaintained status xml-rs
      may or may not be suited to parse untrusted data.
      
      ## Alternatives
      
      - [quick-xml](https://crates.io/crates/quick-xml)
    = Announcement: https://github.com/netvl/xml-rs/issues
    = Solution: No safe upgrade is available!
    = xml-rs v0.8.4
      ├── gl_generator v0.14.0
      │   ├── (build) glutin_egl_sys v0.1.6
      │   │   └── glutin v0.29.1
      │   │       └── (dev) wgpu-hal v0.14.0
      │   │           ├── wgpu v0.14.0
      │   │           │   └── wgpu-info v0.14.0
      │   │           └── wgpu-core v0.14.0
      │   │               ├── deno_webgpu v0.81.0
      │   │               │   └── cts_runner v0.1.0
      │   │               ├── dummy v0.14.0
      │   │               ├── player v0.14.0
      │   │               └── wgpu v0.14.0 (*)
      │   ├── (build) glutin_gles2_sys v0.1.5
      │   │   └── glutin v0.29.1 (*)
      │   ├── (build) glutin_glx_sys v0.1.8
      │   │   └── glutin v0.29.1 (*)
      │   └── (build) glutin_wgl_sys v0.1.5
      │       └── glutin v0.29.1 (*)
      └── wayland-scanner v0.29.5
          ├── (build) wayland-client v0.29.5
          │   ├── glutin v0.29.1 (*)
          │   ├── smithay-client-toolkit v0.16.0
          │   │   ├── sctk-adwaita v0.4.3
          │   │   │   └── winit v0.27.5
          │   │   │       ├── glutin v0.29.1 (*)
          │   │   │       ├── player v0.14.0 (*)
          │   │   │       ├── (dev) wgpu v0.14.0 (*)
          │   │   │       └── (dev) wgpu-hal v0.14.0 (*)
          │   │   └── winit v0.27.5 (*)
          │   ├── wayland-cursor v0.29.5
          │   │   └── smithay-client-toolkit v0.16.0 (*)
          │   ├── wayland-egl v0.29.5
          │   │   └── glutin v0.29.1 (*)
          │   ├── wayland-protocols v0.29.5
          │   │   ├── smithay-client-toolkit v0.16.0 (*)
          │   │   └── winit v0.27.5 (*)
          │   └── winit v0.27.5 (*)
          └── (build) wayland-protocols v0.29.5 (*)

warning[unsound]: Potential unaligned read
   ┌─ /github/workspace/Cargo.lock:15:1
   │
15 │ atty 0.2.14 registry+https://github.com/rust-lang/crates.io-index
   │ ----------------------------------------------------------------- unsound advisory detected
   │
   = ID: RUSTSEC-2021-0145
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0145
   = On windows, `atty` dereferences a potentially unaligned pointer.
     
     In practice however, the pointer won't be unaligned unless a custom global allocator is used.
     
     In particular, the `System` allocator on windows uses `HeapAlloc`, which guarantees a large enough alignment.
     
     # atty is Unmaintained
     
     A Pull Request with a fix has been provided over a year ago but the maintainer seems to be unreachable.
     
     Last release of `atty` was almost 3 years ago.
     
     ## Possible Alternative(s)
     
     The below list has not been vetted in any way and may or may not contain alternatives;
     
      - [is-terminal](https://crates.io/crates/is-terminal)
      - std::io::IsTerminal *nightly-only experimental*
   = Announcement: https://github.com/softprops/atty/issues/50
   = Solution: No safe upgrade is available!
   = atty v0.2.14
     └── env_logger v0.9.3
         ├── player v0.14.0
         ├── (dev) wgpu v0.14.0
         │   └── wgpu-info v0.14.0
         ├── (dev) wgpu-hal v0.14.0
         │   ├── wgpu v0.14.0 (*)
         │   └── wgpu-core v0.14.0
         │       ├── deno_webgpu v0.81.0
         │       │   └── cts_runner v0.1.0
         │       ├── dummy v0.14.0
         │       ├── player v0.14.0 (*)
         │       └── wgpu v0.14.0 (*)
         └── wgpu-info v0.14.0 (*)

advisories FAILED
```

**Comment by nical** [comment]
The `atty` issue should go away if we update `env_logger`.

**Comment by teoxoy** [comment]
We'll need to wait for a new version of deno deps to get released to avoid the tokio vulnerability (see https://github.com/denoland/deno/pull/17271#issuecomment-1380490396).

**Comment by cwfitzgerald** [comment]
For the ones that are unavoidable and not part of our normal dependencies, we can add them to the ignore list.

**Comment by cwfitzgerald** [comment]
This has been cleared up.
