### ISSUE TITLE
Confusion about use bitflags in Features

### ISSUE THREAD

**Issue by 823984418** [gfx-rs/wgpu#3385]
I've noticed that the WGPU is using bitflags extensively on projects as a container for several enumeration features.
Does this mean that there is a limit to the number of enumerated items that can occur in the future?
For example, in Features, does the use of U64 mean that no more than 16 (now 10) webgpu Features and 48 (now 26) native Features will be supported in the future?
Whether to design for support for more Features?
Further, should we consider designing the enumeration collection support of the wgpu itself?

**Comment by nical** [comment]
> Does this mean that there is a limit to the number of enumerated items that can occur in the future?

No, the type will simply evolve as needed.
