### ISSUE TITLE
Start a knowledge base in the wiki on environment dependencies

### ISSUE THREAD

**Issue by juliusl** [gfx-rs/wgpu#3395]
**Is your feature request related to a problem? Please describe.**
When wgpu fails to find an adapter due to missing dependencies, it's kind of difficult to figure out how to fix the issue. A lot of the information from existing issues seem to be out of date, and external knowledge bases are very chaotic. 

**Describe the solution you'd like**
A page for each common environment and the deps that need to be installed, and a bit of an overview on how to troubleshoot issues. 
For example, currently to use Vulkan on WSL2 w/ Ubuntu 22.xx, you need to install `vulkan-tools`, `list of gpu drivers`, `list of development libraries`, etc. 

Or, to troubleshoot whether or not Vulkan is installed or working correctly, you might need to install `vulkaninfo` via `vulkan-tools` (Ubuntu 22.04) pkg or `vulkan-utils` (Ubuntu 18.04) pkg.

**Additional context**
About a year or two ago, wgpu seemed to just work out of the box w/ the rest of the ecosystem (winit), but recently it seems like there are a lot of undocumented development library requirements popping up between the two. This is a good problem to have because it means the needle keeps getting pushed forward but can be frustrating when maintaining a dependency on wgpu. Since wgpu is picking backends in the background, it feels like adding this type of information in the wiki would be helpful when downstream maintainers troubleshoot issues.

**Comment by juliusl** [comment]
Example format, 

# WSL2 + Ubuntu 22.04 + Wayland + Vulkan + NVidia 

## Tested platform versions

```
Windows 11 Version 22H2
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47

WSL Distros: 
- Ubuntu 22.04.1 LTS
```

## Tested hardware info

```
Nvidia Quadro P400 - Driver 31.0.15.2802
```

## Required Packages
    - `libwayland-dev`
    - `vulkan-tools`
    - `nvidia-driver-525`

Also, mesa drivers need to be updated to the latest, 

```
sudo add-apt-repository ppa:oibaf/graphics-drivers -y
sudo apt-get update
sudo apt-get upgrade -y
```

To undo the above,

```
sudo apt install ppa-purge -y
sudo ppa-purge ppa:oibaf/graphics-drivers -y
```

**Comment by maxcrous** [comment]
Seconding this! It took me a while to figure out I needed `libfontconfig-dev` besides `fontconfig`.

**Comment by cwfitzgerald** [comment]
Our wiki is open for public editing, so I would recommend just going ahead and starting it!
