### ISSUE TITLE
`make_spirv_raw` should handle big-endian SPIR-V binaries

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/wgpu#3408]
**Description**
We used to allow both little- and big-endian SPIR-V binaries in gfx/wgpu, but now it looks like the host endianness is assumed. See https://github.com/gfx-rs/gfx/blob/3da35c4339513de6a69e7794d42a63203f5820e5/src/auxil/auxil/src/lib.rs#L84 or https://github.com/ash-rs/ash/blob/8b4575086e7a6eff4d81eb5c2cf88714e56c4128/ash/src/util.rs#L127 for reference.

**Repro steps**
n/a

**Expected vs observed behavior**
Big-endian words would be passed to the Vulkan driver but this should be handled at the application level.

**Extra materials**
n/a

**Platform**
n/a

**Comment by 1e1001** [comment]
I've got an implementation of this on my home computer, I'll submit a PR in a few hours if nobody else has by then

**Comment by 1e1001** [comment]
> Big-endian words would be passed to the Vulkan driver but this should be handled at the application level.

Oh? Does this mean we only have to check that the magic matches rather than swapping all the words?

**Comment by grovesNL** [comment]
@1e1001 oh I just meant it should be handled at somewhere above the driver-level. i.e., handling it directly in wgpu would be really useful, although it's also possible for us to require that the magic number matches if we want to require applications to provide little-endian.
