### ISSUE TITLE
Unable to run wgpu Cube example in Chrome Canary

### ISSUE THREAD

**Issue by gents83** [gfx-rs/wgpu#3413]
It compiles fine but when running it, it just fails to run :(

![image](https://user-images.githubusercontent.com/62186646/213880310-57dc0846-8cbf-4eb7-a945-1a2b7111bec8.png)

And actually I've also surface_configure error in my examples as well (https://gents83.github.io/INOX/web/)

![image](https://user-images.githubusercontent.com/62186646/213880394-447e1cd9-917a-49d5-93ce-637eeeab96b8.png)

Do you know if is it expected to run correctly on Wasm\Web or if is there any known issue?
Just to know if it's worth to investigate or someone already have ideas :)

Thanks a lot!

**Comment by jinleili** [comment]
[This PR ](https://github.com/gfx-rs/wgpu/pull/2986) depends on setlike GPUSupportedFeatures interface , but is not yet implemented in web-sys. Currently, only the webgl backend can run (`cargo run-wasm --example cube --features webgl`).

**Comment by codeart1st** [comment]
I have the same problem (second screenshot).

![image](https://user-images.githubusercontent.com/581407/215277049-83ee2b33-8f17-464c-a83e-822bd2f0a24d.png)


https://github.com/gfx-rs/wgpu/blame/fe2b230b0e735ccdefa0ef002dc7ade554dd2c98/wgpu/src/backend/web.rs

**Comment by cwfitzgerald** [comment]
Closing in favor of #3430

**Comment by michael8090** [comment]
https://wgpu.rs/examples-gpu/?example=mipmap

The official examples are broken on chrome 113, so maybe we should reopen the issue.

**Comment by cwfitzgerald** [comment]
They don't work because that is an old deployment, see https://github.com/gfx-rs/wgpu/issues/3684
