### ISSUE TITLE
Feature POLYGON_MODE_POINT for Metal backend

### ISSUE THREAD

**Issue by paulkre** [gfx-rs/wgpu#3421]
Does anyone know when the Metal backend will support the [`POLYGON_MODE_POINT`](https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.POLYGON_MODE_POINT) feature?

Theoretically, it should be possible already:
https://developer.apple.com/documentation/metal/mtlprimitivetype

**Comment by jinleili** [comment]
`POLYGON_MODE_POINT` is not `MTLPrimitiveTypePoint` in your document above, it is [MTLTriangleFillMode](https://developer.apple.com/documentation/metal/mtltrianglefillmode?language=objc), which is indeed not supported in Metal.

**Comment by paulkre** [comment]
Thanks for the information. In that case, is it maybe already possible on Metal to render vertices as points instead of triangles?

**Comment by jinleili** [comment]
Yes, but since PointSize is not defined in the WebGPU spec, `Point` is just a pixel size.
