### ISSUE TITLE
Creating a bind group with a Depth32Float texture fails with bind group layout expecting a filterable texture in 0.15.0

### ISSUE THREAD

**Issue by yanchith** [gfx-rs/wgpu#3427]
**Description**
Creating a bind group with a depth texture (`Depth32Float`) with layout entry `BindingType::Texture` with `wgpu::TextureSampleType::Float { filterable: true }` fails with:

```
Caused by:
    In Device::create_bind_group
    texture binding 1 expects sample type = Float { filterable: true }, but given a view with format = Depth32Float
```
 
This didn't fail in 0.14.2.

**Repro steps**

Unfortunately I can't provide an example to be checked out, but the steps are:

- Create a bind group layout

```rust
        let sampled_texture_bind_group_layout =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: None,
                entries: &[
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                        count: None,
                    },
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::VERTEX | wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                            view_dimension: wgpu::TextureViewDimension::D2,
                            multisampled: false,
                        },
                        count: None,
                    },
                ],
            });
```
- Create a depth texture and its view:

```rust
    let depth = device.create_texture(&wgpu::TextureDescriptor {
        label: None,
        size: wgpu::Extent3d {
            width: size.x,
            height: size.y,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Depth32Float,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    });
    let depth_view = depth.create_view(&wgpu::TextureViewDescriptor::default());

```

- Create a bind group with the layout and the depth texture:

```rust
        let intermediate_depth_texture_bind_group =
            device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: None,
                layout: &sampled_texture_bind_group_layout,
                entries: &[
                    wgpu::BindGroupEntry {
                        binding: 0,
                        resource: wgpu::BindingResource::Sampler(&nearest_sampler),
                    },
                    wgpu::BindGroupEntry {
                        binding: 1,
                        resource: wgpu::BindingResource::TextureView(
                            &depth_view,
                        ),
                    },
                ],
            });
```

**Expected vs observed behavior**
This didn't fail on 0.14.2, and I could sample from a depth texture to view it visually. Not sure, if this is supposed to be an error, but it sure was convenient to have just one bind group layout for all filterable textures, wheres now I'd have to have multiple bind group layouts and multiple pipelines.

**Extra materials**
I tracked this down to `wgpu-core/src/device/mod.rs`, function `fn texture_use_parameters()`. The match statement there says the binding type has to be `filterable: false`, if we want to match it with a depth texture.

**Platform**
Windows, Nvidia, wgpu: 0.15.0, custom engine.

**Comment by yanchith** [comment]
If it is indeed ok for validation to relax and once again allow pairing depth textures with filterable float sample types, I'd be happy to PR the fix.

**Comment by cwfitzgerald** [comment]
This is actually intentional - you cannot linear sample depth textures - see the last line of the verbiage here https://gpuweb.github.io/gpuweb/#depth-formats.

You should be able to do this if you enable the TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES flag and your gpu supports it but that forfits portability.

**Comment by yanchith** [comment]
Oh no. Thanks, I'll see what I can do.
