### ISSUE TITLE
Default not working with another clause

### ISSUE THREAD

**Issue by Norlock** [gfx-rs/wgpu#3441]
**Description**
According to the specs you should be able to include default with another clause. This does not seem to work.
https://github.com/Norlock/sparticles/blob/bug-switch/src/shaders/trail_render.wgsl
 

**Repro steps**
```rust
git clone https://github.com/Norlock/sparticles.git
git checkout bug-switch
cargo run --release --example default
```

**Expected vs observed behavior**
Expected: working switch.
Observed behaviour: 
```rust

Caused by:
    In Device::create_shader_module
      note: label = `particle`
    
Shader 'particle' parsing error: expected unsigned/signed integer literal, found 'default'
    ┌─ wgsl:170:18
    │
170 │         case 5u, default {
    │                  ^^^^^^^ expected unsigned/signed integer literal


    expected unsigned/signed integer literal, found 'default'
```

**Platform**
I'm running on Linux, with Vulkan backend, wgpu version 14.

**Comment by teoxoy** [comment]
wgpu v15 and naga v11 have been released recently which contain https://github.com/gfx-rs/naga/pull/2126.

Could you update and give it another shot?

**Comment by Norlock** [comment]
I have updated to version 15: 

But it won't even start https://github.com/Norlock/sparticles/tree/version-15. Maybe I forgot something, otherwise I will make another ticket for 15.

**Comment by Norlock** [comment]
Yes updating fixed the issue, thanks.
