### ISSUE TITLE
Unusually dark screen when using Vulkan backend

### ISSUE THREAD

**Issue by Pyxrs** [gfx-rs/wgpu#3449]
**Description**
When using Vulkan on any wpgu project, the output is much darker than when using DX12 or Browser WebGPU.
I should also note that this wasn't an issue on my Radeon card a year ago, but I'm not sure if it's the new graphics card or a WGPU update that caused this issue.

**Repro steps**

Reproduced using
- Windows 10 or Windows 11
- Nvidia Geforce RTX 3060
- [This project specifically](https://github.com/sotrh/learn-wgpu/tree/master/code/beginner/tutorial8-depth/), but also the WGPU examples ([https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples](https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples))
- Use wgpu 0.12, 0.14, or 0.15 (untested on 0.13)

**Expected behavior (using DX12)**
![Expected](https://media.discordapp.net/attachments/836737209247072328/1070933331438489600/image.png)
**And on the [Learn Wgpu website](https://sotrh.github.io/learn-wgpu/beginner/tutorial8-depth/#challenge)**
![Expected](https://media.discordapp.net/attachments/836737209247072328/1070933988421677087/image.png)

**Observed behavior (using Vulkan)**
![Observed](https://media.discordapp.net/attachments/836737209247072328/1070933071571992626/image.png)

**Extra materials**
I found a similar issue that could be potentially the same problem, but it was reported as fixed #1646

**Comment by teoxoy** [comment]
There is no release with the fix yet. Can you give master a try?

**Comment by Pyxrs** [comment]
Works on master 👍

**Comment by teoxoy** [comment]
There will be a minor version release containing the fix next week.

**Comment by wez** [comment]
@teoxoy can you reference the commit that fixes this issue from this PR?
I didn't see an obvious commit in the history, and I'm not sure if 0.15.1 has the fix you mentioned or whether my users are running into a different gamma issue.

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/pull/3444 part of the [0.15.1 release](https://github.com/gfx-rs/wgpu/blob/v0.15/CHANGELOG.md#wgpu-0151-2023-02-09) should have fixed the issue.
