### ISSUE TITLE
Shader module unchecked doesn't disable bounds checking codegen

### ISSUE THREAD

**Issue by unfolding18** [gfx-rs/wgpu#3483]
**Description**
Naga adds additional bounds checking code to WGSL shaders prior to compilation. It is configurable via Naga, but does not appear to work in `wgpu-rs` itself. In particular, `create_shader_module_unchecked()` does not disable bounds checking. Note that I have only checked this on the Metal backend, as that is the hardware I am using/targeting.

**Repro steps**
Create a WGSL shader that indexes into any array, buffer, matrix, or vec. Set `wgpu` to use the Metal backend. Run the executable through Xcode's shader debugger. You should see that, regardless of whether you use `create_shader_module` or `create_shader_module_unchecked`, the resulting Metal shader code contains various conditionals and bounds checking routines.

**Expected vs observed behavior**
Ideally, `create_shader_module_unchecked` would disable bounds checking (or this would be configurable somehow via the API).

**Platform**
MacOS Ventura 13.2, `wgpu` version 0.14.0, Metal backend.

**Comment by cwfitzgerald** [comment]
This appears to be a two sided problem. First is that we just are never changing the bounds check policies we pass to naga. See https://github.com/gfx-rs/wgpu/blob/e4445205c2df23a629760a1fccb8e46c574d2587/wgpu-hal/src/metal/device.rs#L692-L699 for where they are hard coded. Second we are setting them _in the pipline layout_, when the unchecked-ness comes on a per-module basis.
