### ISSUE TITLE
zero_init_workgroup_mem fails in some configurations

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#3492]
**Description**

On some platforms `cargo nextest run fails` in `zero_init_workgroup_mem`.

For example on a Mac M1 max:

```
thread 'shader::zero_init_workgroup_mem::zero_init_workgroup_mem' panicked at 'Zero-initialization of workgroup memory failed (81% of disptaches failed).', wgpu/tests/shader/zero_init_workgroup_mem.rs:175:5
```

**Repro steps**

run `cargo nextest run`.

**Platform**

 - Mac M1 max (Moac OS 12.5.1 "Metal GPUFamily Apple 7") on current wgpu (rev 719ba83726343c0afd3f7327e0150a9b76e8d1b3)
 - Windows + DXC according to https://github.com/gfx-rs/wgpu/pull/3447#issue-1568690578

**Comment by teoxoy** [comment]
@Elabajaba we think we fixed this issue in https://github.com/gfx-rs/naga/pull/2259 (https://github.com/gfx-rs/wgpu/pull/3512).
Can you confirm that on your Windows + DXC setup it now succeeds?

**Comment by nical** [comment]
The mac M1 issue is fixed.

**Comment by Elabajaba** [comment]
> Can you confirm that on your Windows + DXC setup it now succeeds?

DX12 now passes all the tests with both FXC and DXC. (apart from the 1 skipped test)

**Comment by cwfitzgerald** [comment]
Sounds like this has been fixed!
