### ISSUE TITLE
Remove `DownlevelFlags::VERTEX_STORAGE`

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#3495]
Remove `DownlevelFlags::VERTEX_STORAGE` since the WebGPU Spec doesn't require it (see https://github.com/gpuweb/gpuweb/issues/1069#issuecomment-1435164652).

We could either bundle it together with `Features::VERTEX_WRITABLE_STORAGE` or move it in the `Features` enum.

**Comment by kainino0x** [comment]
Apologies, I misread our spec. Read-only storage is OK in the vertex stage, writable storage is disallowed.

**Comment by teoxoy** [comment]
Np, @cwfitzgerald and I were just talking about it and it seems our downlevel feature flag is set incorrectly which misled me as well.
