### ISSUE TITLE
Drop DirectX 11

### ISSUE THREAD

**Issue by Snowiiii** [gfx-rs/wgpu#3500]
DirectX was released back in 2009, DirectX 12 came out 2015 its been over 8 Years now i think we should drop DirectX 11 and focus on Other Things than Maintaining a Very old API

**Comment by nical** [comment]
I wish. Unfortunately we can't take D3D12 for granted either. I don't have the data handy but as a reference point in broad strokes there's at least 50% of Firefox users on windows that don't have a D2D12-compatible configuration (I am being very conservative with this number, it is quite a bit more than that).
So D3D11 can help wgpu reach a lot of places. The picture is also grim on the OpenGL side FWIW.

Wgpu's D3D11 backend is not yet in a state to be a maintenance burden anyway. There is some skeleton code in the repository but it is not complete and not hooked up yet.

Unless you were maintaining the backend, it isn't very much up for debate. People will either volunteer to do the work or grudgingly do it to make wgpu work in more places. Until it happens D3D11 isn't slowing anyone down, so I'll close this.
