### ISSUE TITLE
Hello example does nothing

### ISSUE THREAD

**Issue by fenhl** [gfx-rs/wgpu#3503]
**Description**
[The `hello` example](https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples/hello) does not print any output.

**Repro steps**
`cargo run --example=hello`

**Expected vs observed behavior**
According to the example's readme, there should be command-line output including `Available adapters:`. Instead, there is only the output from Cargo (on a retry: `Finished dev [unoptimized + debuginfo] target(s) in 0.39s` and <code>Running \`target\debug\examples\hello.exe\`</code>), the binary itself prints nothing.

**Platform**
Windows 11 Pro version 22H2 (build 22621.1265), `wgpu` commit e18520078a3eab5a5fc6beee974033e8a98822f3.

**Comment by cwfitzgerald** [comment]
I suspect the issue is that RUST_LOG defaults to `error`. We should set the filter with https://docs.rs/env_logger/latest/env_logger/fn.init_from_env.html such that it defaults to info

**Comment by fenhl** [comment]
with `$env:RUST_LOG = 'info'` it does indeed print a list of available adapters. It also prints a bunch of other info and warnings though, so maybe the logger should be configured to only print info from `hello` itself by default.
