### ISSUE TITLE
Allow hooking into image barriers / texture transitions on a backend-specific basis

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#3516]
**Is your feature request related to a problem? Please describe.**
I'm trying to hook into FidelityFX Super Resolution 2, a Vulkan/DirectX12 library. This library handles all the dispatches, but requires that the input textures have a certain `VkAccessFlagBits`, and be in a certain  `VkImageLayout` (or the DX12 equivalents, for DX12).

**Describe the solution you'd like**
Add a command encoder `transition_textures()` method that hooks into wgpu's resource tracker, and adds a transition to the next pipeline image barrier (if necessary) to a specific user provided `VkImageLayout` for Vulkan, or similar thing for DX12 and others.

**Describe alternatives you've considered**
I've tried doing such a thing [here](https://github.com/gfx-rs/wgpu/compare/master...JMS55:wgpu:master). I ran into the problem that `wgpu_hal::TextureUses` is too high level - I can't specify or coerce it to get a specific `VkImageLayout`. I'm also unsure if it would work correctly or if I made other mistakes.

**Comment by cwfitzgerald** [comment]
This is obsoleted by #4067
