### ISSUE TITLE
Allow hooking into command buffers on a backend-specific basis

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#3517]
**Is your feature request related to a problem? Please describe.**
I'm trying to hook into FidelityFX Super Resolution 2, a Vulkan/DirectX12 library. This library handles all the dispatches, but requires that we pass it a `VkCommandBuffer`.

**Describe the solution you'd like**
Add a method to get a backend-specific `VkCommandBuffer` (for Vulkan, or the equivalent for DirectX12) from a `&mut wgpu::CommandEncoder`. I believe this is not exactly straightforward, as it seems like wgpu's CommandEncoder wraps many command buffers or something. 

The user should also be able to set a debug label that will show up in debuggers like RenderDoc for subsequent commands issued on the command buffer.

**Comment by cwfitzgerald** [comment]
This is also obsoleted by #4067
