### ISSUE TITLE
Add hal_features parameter to Adapter::request_device().

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#3535]
**Is your feature request related to a problem? Please describe.**
I would like to enable specific Vulkan extensions, that don't (and probably shouldn't) have corresponding wgpu features.

**Describe the solution you'd like**
Add a `hal_features: &[&CStr]` parameter to `Adapter::request_device()`. 

**Describe alternatives you've considered**
Currently you can make the device yourself using Adapter<Hal>::device_from_raw() and Adapter::create_device_from_hal(), but this is a lot of unnecessary boilerplate and duplicate code that needs to be kept up-to-date with wgpu's internals.

**Comment by teoxoy** [comment]
Which Vulkan extensions are you interested in enabling?

**Comment by JMS55** [comment]
I need whatever the list of extensions DLSS returns. Currently, on my system, that seems to be:
```
VK_NVX_binary_import
VK_NVX_image_view_handle
VK_EXT_buffer_device_address
VK_KHR_push_descriptor
```

**Comment by cwfitzgerald** [comment]
#4067 is what will also get you this.
