### ISSUE TITLE
Suballocation works incorrectly

### ISSUE THREAD

**Issue by xiaopengli89** [gfx-rs/wgpu#3552]
**Description**
Related to #3544 

**Repro steps**
Uploading transparent pixel data

**Expected vs observed behavior**
Transparent pixels should be rendered correctly

**Extra materials**
![图片](https://user-images.githubusercontent.com/11287532/222351113-0dbf75d3-c247-4207-82e3-613eaf96506a.png)

**Platform**
os: Win10
gpu: Intel iris xe
wgpu: 0.15 with dx12 backend

**Comment by Elabajaba** [comment]
I can't reproduce this on windows+AMD. Do you have a small example to demonstrate this? (also Intel's Xe GPU drivers are a mess, have you updated them recently?)

**Comment by xiaopengli89** [comment]
This problem does not necessarily happen, it needs to repeatedly create textures and upload data, the intel driver version has been updated to the latest. I guess it is a driver bug, so I added a feature to manually turn off suballocation optimization.

**Comment by xiaopengli89** [comment]
[Initializing DX12 Textures After Allocation and Aliasing](https://asawicki.info/news_1724_initializing_dx12_textures_after_allocation_and_aliasing), I think we should initialize the memory before writing data to it.

**Comment by xiaopengli89** [comment]
> It informs the driver that the current content of the resource might be garbage; we know about it, and we don't care, we don't need it, not going to read it, just going to fill the entire resource with a new content.

**Comment by teoxoy** [comment]
@xiaopengli89 does this happen only when uploading data to RGBA textures?

Would it be possible for you to put together an example we could try to reproduce?

**Comment by xiaopengli89** [comment]
Since I can't solve this problem, can wgpu add a feature to disable suballoction?

**Comment by teoxoy** [comment]
Do you have any updates from intel?

I don't think requiring users to manually work around it is something we want to rely on. If this is driver issue we should instead try to implement a workaround in wgpu.

cc @cwfitzgerald

**Comment by xiaopengli89** [comment]
> Do you have any updates from intel?

No, even after installing the latest xe driver, the problem still exists.

**Comment by cwfitzgerald** [comment]
Yes, we should deal with this internally by using the old route on Xe
