### ISSUE TITLE
CPU usage on Windows 10, i5 8400

### ISSUE THREAD

**Issue by 4r33x** [gfx-rs/wgpu#3569]
Hey! Can someone help me figure out why wgpu consuming so much CPU? 
My GPU: AdapterInfo { name: "NVIDIA GeForce RTX 2070 SUPER", vendor: 4318, device: 7812, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "531.18", backend: Vulkan }
CPU: Intel Core i5 8400
Win10
All examples(cube etc...)  in wpgu repository, and also my setup, consumes about 25% CPU, even if program idles.
Tried to switch backends,  performance modes, PresentModes - no luck at all

![image](https://user-images.githubusercontent.com/20604101/223821382-bac82774-9faa-4018-9f92-151016f6544c.png)

Flamegraphs:
![flame2](https://user-images.githubusercontent.com/20604101/223820771-334f8d3a-51f8-4ae7-8069-7fe3f830f9b7.png)
![flame1](https://user-images.githubusercontent.com/20604101/223820786-db82c45b-92ba-450b-8d98-2344e8c840ed.png)
![flame1closeup](https://user-images.githubusercontent.com/20604101/223820794-f174c42b-de41-4d28-b043-83341f843a5d.png)

**Comment by teoxoy** [comment]
It's hard to tell what is going on based on the info given so far. Did you manage to debug it further?

**Comment by jimblandy** [comment]
We don't seem to have enough information to act on here, so I'm closing this. Feel free to re-open.
