### ISSUE TITLE
Gpu performance when with multisamplecount

### ISSUE THREAD

**Issue by wjian23** [gfx-rs/wgpu#3574]
when with multisamplecount 4, even creating a renderpass bind with full_view of 4k resolution in 60fps will cost 60%+ gpu.
without multisamplecount, would also cost 16% either.
what can I do if I just want to repaint a little scissor_rect within a low gpu cost，when with multisamplecount 4?

device:
    MacBook Pro 2018
    cpu: Intel Core i7
    gpu: Radeon Pro 555X 4 GB
         Intel UHD Graphics 630 1536 MB
    mem: 16G

**Comment by Wumpf** [comment]
Slow performance on multisampling is generally expected as it takes a lot more memory and computation, there is not all that much you can do. Anything that gets the work you need to do per pixel and the size of your target down will help. If you only want to draw a small portion of the screen, you can try setting the viewport to just that portion. A more extreme measure would be to have a multisampling target just for that portion of the screen you're interested in, resolve the target and render that into the final (non-multisampled) output in a separate step.

**Comment by teoxoy** [comment]
Closing as it seems this has been answered.
