### ISSUE TITLE
Device removal exception

### ISSUE THREAD

**Issue by Canvas02** [gfx-rs/wgpu#3604]
I don't know if this is a bug or is something wrong on my side but, when trying to run the wgpu examples I get this:
```
Using Intel(R) HD Graphics 4600 (Dx12)
[2023-03-19T15:27:10Z ERROR wgpu_hal::auxil::dxgi::exception] ID3D12Device::RemoveDevice: Device removal has been triggered for the following reason (DXGI_ERROR_DEVICE_HUNG: The Device took an unreasonable amount of time to execute its commands, or the hardware crashed/hung. As a result, the TDR (Timeout Detection and Recovery) mechanism has been triggered. The current Device Context was executing commands when the hang occurred. The application may want to respawn and fallback to less aggressive use of the display hardware). [ EXECUTION ERROR #232: DEVICE_REMOVAL_PROCESS_AT_FAULT]
```

Additionally while trying to run the [iced](https://github.com/iced-rs/iced) examples (while using the wgpu backend) I get this:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
      note: label = `(wgpu internal) StagingBelt staging buffer`
    parent device is lost

```

I am running windows 10 (OS Build 19045.2728) with a duel gpu setup, an Integrated (Intel) gpu and a dedicated (Nvidia) gpu

Is there any way I can fix this?

**Comment by xiaopengli89** [comment]
[DirectX 12 Applications No Longer Working on 4th Generation Intel® Processor Graphics](https://www.intel.com/content/www/us/en/support/articles/000057520/graphics.html)

**Comment by Canvas02** [comment]
Is there any way I can force wpgu to use the dedicated gpu

**Comment by xiaopengli89** [comment]
You can set PowerPreference to HighPerformance when calling request_adapter.

**Comment by Canvas02** [comment]
What if I am using a library like iced, is there something like an environment variable where I can force it to use the high performance adapter?

**Comment by xiaopengli89** [comment]
I don't think so.

**Comment by Canvas02** [comment]
What about these: https://github.com/gfx-rs/wgpu#environment-variables

**Comment by xiaopengli89** [comment]
These env vars only works in tests or examples.

**Comment by teoxoy** [comment]
> If I want to contribute an "env var overloading" feature would it get accepted or no?

Since wgpu is a lib, we shouldn't switch default behavior based on env variables. Those can be implemented by applications built on top instead.
