### ISSUE TITLE
copy_buffer_to_buffer with size 0 causes floating point exception on Metal

### ISSUE THREAD

**Issue by michaelfairley** [gfx-rs/wgpu#362]
[Minimal wgpu-rs example](https://gist.github.com/michaelfairley/b523353bd9ac5b06f363e6d9899e2565#file-main-rs), using curent `wgpu-rs` master (which is pinned to a ~2 week old wgpu-native, but there don't seem to have been any relevant commits since then).

Hits a divide-by-zero in the Intel Metal driver: https://gist.github.com/michaelfairley/b523353bd9ac5b06f363e6d9899e2565#file-crash_report

The docs for the underlying Metal function don't say anything about 0 being undefined/forbidden: https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400767-copy

Vulkan spec says ["The size must be greater than 0"](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkBufferCopy), so it seems like wgpu is on the hook for making this safe.

**Comment by kvark** [comment]
Thank you for filing! We should just ignore the command if the copy is of size 0
