### ISSUE TITLE
Reconsider lavapipe

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#3622]
The wgpu sources have various comments here and there remarking on how lavapipe doesn't implement Vulkan well enough to fully support WebGPU, but I wonder if that's true any more. Apparently Linux Mesa lavapipe 22.1.2 [passes](https://www.khronos.org/conformance/adopters/conformant-products#submission_696) the Vulkan 1.3 CTS.

We should go through wgpu and see what works now and which caveats still apply. It would sure be nice to have lavapipe for software-based testing.

**Comment by teoxoy** [comment]
The `zero_init_workgroup_mem` test failing in CI (running via swiftshader currently) is becoming more and more prevalent. I wonder how lavapipe compares.

**Comment by cwfitzgerald** [comment]
The `zero_init_workgroup_mem` test failing in CI is our fault not swiftshader's, it's the same thing affecting WARP: https://github.com/gfx-rs/wgpu/issues/3193

This wasn't obvious before as the vulkan validation layers were off. Afaict, there have been no spurious failures from swiftshader (that weren't our fault), but there have been quite a few from lavapipe. We should definitely try it again, but I have a lot more confidence in swiftshader than lavapipe.
