### ISSUE TITLE
How to enable dx12 feature

### ISSUE THREAD

**Issue by xiaopengli89** [gfx-rs/wgpu#3643]
**Description**
`create_surface_from_visual` / `create_surface_from_surface_handle` unavailable anymore after #3590

**Comment by teoxoy** [comment]
Sorry, I didn't catch this in my review. I think we need to revert https://github.com/gfx-rs/wgpu/pull/3590.

`wgpu` on windows enables `wgpu-core`'s `dx11` and `dx12` features. So, it was correct that those functions had guards only for `windows`.

@toastmod how did you disable `dx12` for `wgpu` when `wgpu` doesn't have a feature flag for it?

**Comment by cwfitzgerald** [comment]
They were forking. We should revert it.
