### ISSUE TITLE
Support for Windows 7

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#365]
In theory, our backend's `Instance` creation would fail if a backend isn't available. This allows us to only enumerate the adapters of the backends exposed on a system.

However, it turns out that D3D12 backend doesn't fail gracefully: running a `wgpu-rs` example on Windows 7 just fails instantly with a modal dialog saying that "d3d12.dll" can't be loaded. This means we have d3d12 [implicitly linked](https://docs.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll?view=vs-2019#implicit-linking) on Windows, which is not what we want.

Technically, it's a problem down the stack: gfx-backend-dx12, winit, etc. But it's also a blocker for using `wgpu-native` in Gecko, so we should resolve it quickly.

**Comment by kvark** [comment]
Building with `WINAPI_NO_BUNDLED_LIBRARIES` environment doesn't appear to fix this.
Any ideas, @retep998, @msiglreith, anybody?

**Comment by retep998** [comment]
You'll need to modify whatever is calling the function from `d3d12.dll` to call it using `LoadLibrary`/`GetProcAddress` (using `libloading` for example) instead of calling it directly from `winapi`.

`WINAPI_NO_BUNDLED_LIBRARIES` is to solve a completely different problem.

**Comment by kvark** [comment]
@retep998 isn't it `winapi` code calling the functions from `d3d12.dll`?
I was looking for documentation on environment variables like `WINAPI_NO_BUNDLED_LIBRARIES` but didn't find any.

**Comment by kvark** [comment]
@retep998 wait, re-reading your message now. Are you basically saying we *can't* use `winapi` at all?! Because no matter how many `LoadLibrary` calls we do at run time, if we have any code that uses D3D12 via `winapi`, we'll end up with this DLL linking problem at startup.

**Comment by kvark** [comment]
I did some digging and found the answers.
We were using the following methods forcing the implicit DLL linking:
  - D3D12SerializeRootSignature

**Comment by msiglreith** [comment]
Having some additional entrypoint for these is fine for me.
The HLSL compiler entrypoint probably need to be loaded as well dynamically

**Comment by kvark** [comment]
gfx fix is coming in https://github.com/gfx-rs/gfx/pull/3069
We'll not be able to pick it up however(!) until Rendy helpers are published. cc @omni-viral

**Comment by kvark** [comment]
This happened
