### ISSUE TITLE
WebGL: INVALID_ENUM: framebufferTexture2D: invalid attachment

### ISSUE THREAD

**Issue by lucasmerlin** [gfx-rs/wgpu#3659]
**Description**
I have two render passes, one occasionally renders something to different textures, and the other renders those textures on screen.

Running my app in chrome leads to the following error being logged almost every frame: `WebGL: INVALID_OPERATION: drawElementsInstanced: no buffer is bound to enabled attribute`
In safari the following is logged: 
![image](https://user-images.githubusercontent.com/8009393/230718278-a64e8e4b-1fce-4bc3-bacf-c14f0479dafb.png)

A couple of frames do succeed though, and render the expected output. I suspect in those frames, the render pass rendering to the texture was run.

**Repro steps**
I was able to create a reproduction for the `WebGL: INVALID_ENUM: framebufferTexture2D: invalid attachment` error from safari, which I hope is the root cause of the problem: https://github.com/lucasmerlin/invalid-attachment-reproduction

Running the code natively should show a red square on green background, running it in the browser shows nothing and in safari it logs the invalid attachment error.

Surface.rs contains code that renders the square to a texture and surface_view.rs contains code that displays the texture on screen.

**Expected vs observed behavior**
There should be no errors and the frame should render successfully.

**Extra materials**
A video of the issue in my app (once the first tile loads, the frames start to fail)
https://user-images.githubusercontent.com/8009393/230718617-54357603-c722-4e21-b15c-be040c066bda.mov

For reference, I also asked about this on matrix: https://matrix.to/#/!XFRnMvAfptAHthwBCx:matrix.org/$dSku7Ho_VLMf81jjr7w5mriD6wzeHY4FGvJISRSK7T8?via=matrix.org

**Platform**
I'm using MacOS, the error showed up in chrome, firefox and safari, although with different, or no error messages. Natively it runs fine.

**Comment by Azorlogh** [comment]
Could you try again with wgpu 0.16?
I suspect there might be two different bugs here, and one of them might have been fixed by https://github.com/gfx-rs/wgpu/pull/3706

**Comment by lucasmerlin** [comment]
Gave it a try, seems to be fixed now! Thank you!
