### ISSUE TITLE
wgpu-hal doesn't compile for Vulkan without Metal on Mac

### ISSUE THREAD

**Issue by meyerzinn** [gfx-rs/wgpu#3699]
**Description**
```
cargo build --features vulkan
```

```
error[E0433]: failed to resolve: could not find `metal` in the crate root
   --> wgpu-hal/src/vulkan/instance.rs:454:20
    |
454 |             crate::metal::Surface::get_metal_layer(view as *mut objc::runtime::Object, None)
    |                    ^^^^^ could not find `metal` in the crate root
```

[wgpu-hal/src/vulkan/instance.rs#L454](https://github.com/gfx-rs/wgpu/blob/fc4d591e9ea4ea7c769dff9408a196012f2c9516/wgpu-hal/src/vulkan/instance.rs#L454) is the sad line.

**Expected vs observed behavior**
> That almost certainly needs to be pulled into a wgpu-hal/auxil submodule, with all the dependencies set up right
>
> -@cwfitzgerald 

**Platform**

M1 MacBook Air (2020) running Ventura (13.3.1) with the latest Vulkan SDK (1.3.243).

**Comment by jinleili** [comment]
It seems that this issue cannot be reproduced on the latest `trunk` branch.

**Comment by Wumpf** [comment]
confirmed!
as of https://github.com/gfx-rs/wgpu/pull/3964 we're even running with molten-vk on ci now!
not entirely sure which pr fixed the feature compilation issue but seems to be a bit further back
