### ISSUE TITLE
[meta] Build times

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#370]
This is a tracking issues for build time issues. We want the debug builds to be really fast!
Upstream:
  - https://github.com/amethyst/rendy/issues/203

**Comment by kvark** [comment]
Here is the output of `cargo +nightly rustc -- -Z time-passes` on "wgpu-native":
[wgpu-rust-passes.txt](https://github.com/gfx-rs/wgpu/files/3799017/wgpu-rust-passes.txt)

Notable mentions:
  - total time is ~ 3 minutes (the system was busy doing other things though)
  - time: 7.359; rss: 214MB	wf checking
  - time: 9.392; rss: 287MB	MIR borrow checking
  - time: 7.192; rss: 444MB	codegen to LLVM IR
  - time: 7.479; rss: 459MB	LLVM passes
  - time: 8.426; rss: 489MB	codegen
  - time: 7.072; rss: 488MB	running linker
  - time: 10.840; rss: 432MB	linking

**Comment by kvark** [comment]
[Flamegraph](https://github.com/brendangregg/FlameGraph) generated by [Measureme](https://github.com/rust-lang/measureme):
![rustc](https://user-images.githubusercontent.com/107301/68046127-7abb0a80-fcb1-11e9-9ba1-d0d5696147b4.png)

**Comment by cwfitzgerald** [comment]
Closing as stale/worked on, we've made improvements in our build times, and we're doing alright for the complexity of our library.
