### ISSUE TITLE
Feature Request: BUFFER_BINDING_ARRAY support for metal

### ISSUE THREAD

**Issue by theswerd** [gfx-rs/wgpu#3720]
I want to get a sum of the difference between two fixed sized arrays. I built a script to do it, and then I realized BUFFER_BINDING_ARRAY isn't supported on metal

I'd like to use compute shaders to compute the difference between two fixed length arrays. I have written a shader, but I realized it won't work on MacOS, because BUFFER_BINDING_ARRAY isn't supported on Metal.

This seems like it shouldn't be a large lift, given that [STORAGE_RESOURCE_BINDING_ARRAY](https://wgpu.rs/doc/wgpu/struct.Features.html#associatedconstant.STORAGE_RESOURCE_BINDING_ARRAY) and [TEXTURE_BINDING_ARRAY](https://wgpu.rs/doc/wgpu/struct.Features.html#associatedconstant.TEXTURE_BINDING_ARRAY) are both already implemented on Metal.

Secondly, as it isn't currently implemented, what do you recommend I do to pass in two fixed sized arrays into a shader?

**Comment by teoxoy** [comment]
I don't think you need `binding_array`s for what you are trying to do. You can pass arrays via uniform or storage buffers.
