### ISSUE TITLE
rust-toolchain file is breaking the world for me

### ISSUE THREAD

**Issue by mcclure** [gfx-rs/wgpu#3721]
**Description**
I checked out the wgpu repo so I can run the examples, but any cargo command I execute prints a strange error message.

**Repro steps**
I git checkout this repo on my Windows computer. I run any git command:  
`cargo.exe run --example hello-triangle`  
or even  
`cargo.exe --version`

No matter what I do, it prints:
```
error: invalid channel name '# If you see this, run "rustup self update" to get rustup 1.23 or newer.' in '\\?\C:\Users\Andi\work\r\other\wgpu\rust-toolchain'
info: caused by: invalid toolchain name: '# If you see this, run "rustup self update" to get rustup 1.23 or newer.'
```

I don't know what this means. I tried running `rustup self update` and `rustup update` and am now running rust 1.69.0 but there is no difference. I see this in both "trunk" and v0.16 branches. I get it both at project root and in the "wgpu" sub-folder.

I asked on the "in webgpu we rust" Matrix channel about this. I was recommended `cargo.exe +stable`, like `cargo.exe +stable run --example hello-triangle`. This fixes everything. But I would not have figured it out on my own. The person in the Matrix channel said the problem was "For some reason there is an old rust-toolchain file in the wgpu repo". Looking I see this file has been there for about a month and it is there to help CI somehow.

**Expected behavior**

I should not have to type "+stable" to run normal cargo operations in the wgpu repo. That is not the usual way of interacting with a git repo, and it is not discoverable. It also contradicts the [advice in the README](https://github.com/gfx-rs/wgpu#rust). Moreover, the error message you get is not helpful (gives actively incorrect advice).

This is all unfriendly to entry level users. If I had not known the Matrix channel I would have been stuck.

**Platform**

I am running on Windows 10. I have (now) rust 1.69.0. I invoke cargo.exe from inside of WSL but I see the same error if I invoke in normal CMD.COM.

This is so weird it seems like there must be something about my setup causing it (for example Windows)?

**Comment by Wumpf** [comment]
fyi: I added the rust-toolchain file somewhat naively after I got annoyed by ci having errors I didn't have locally since they used different versions (in particular clippy lints change a lot between versions).

Didn't run into the described awful issues myself, maybe it's something about which channel is set to the default in one's rustup?
There gotta be a way to specify the used rust version without these errors, but I haven't found it yet :(. Here's the documentation on how the file is supposed to work https://rust-lang.github.io/rustup/overrides.html

**Comment by mcclure** [comment]
Figured out the problem (see emphasis)
```
Andi@Alita:/mnt/c/Users/Andi/work/backup/listening-playlist$ rustup.exe self update
info: checking for self-updates
info: downloading self-update
info: rustup updated successfully to 1.25.2
Andi@Alita:/mnt/c/Users/Andi/work/backup/listening-playlist$ rustup.exe --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
```

1.25.2… 1.11.0

Looks like

1. The problem was, indeed, an old Rustup
2. The error message printed by the wgpu file is correct, and there is nothing you should have done differently
3. Looks like I have an interesting bug to file on rustup now

Let me double check some stuff and then I'll close this.

**Comment by mcclure** [comment]
Successfully upgraded rustup to 1.25.2, as your error message recommends.

Ran `cargo.exe --version`. It churned for a while installing (apparently) Rust 1.64.0, and then printed `cargo 1.64.0 (387270bc7 2022-09-16)`. Ran `cargo.exe run --example bunnymark`. It worked (or rather, [it failed in the way I expected it to](https://github.com/gfx-rs/wgpu/issues/3722).

This is a little surprising to me as my "regular" install of rust is 1.69.0. The enforcement of a MSRV is documented in the README but it is not totally obvious to me, reading the README as a person with moderate Rust experience, that enforcing the Minimum Supported Rust Version in this way also imposes a Maximum Supported Rust Version. It might make sense for you to document the `+stable` trick if people wish to make one-off builds with a newer Rust (unless this is something you actually wish to prevent people from doing).

If the directory-local "downgrade" from 1.69.0 to 1.64.0 is expected from your perspective, you may close this bug. Thanks for the help.

**Comment by Wumpf** [comment]
> If the directory-local "downgrade" from 1.69.0 to 1.64.0 is expected from your perspective

Yeah, that's exactly what it's for. Otherwise someone developing on wgpu might accidentally violate the minimum supported rust version by doing something that works only in a newer Rust version. It does not affect anyone _using_ wgpu (well except running samples from the repo that is).

(would close it, but I'm not a maintainer :))

**Comment by mcclure** [comment]
Thanks
