### ISSUE TITLE
bunnymark example does not work (on win10?)

### ISSUE THREAD

**Issue by mcclure** [gfx-rs/wgpu#3722]
**Description**
The "bunnymark" example does not work in the repo. All it shows is a blue screen.

**Repro steps**

`cargo.exe +stable run --example bunnymark`

**Expected vs observed behavior**

I don't know what this example does, but the directory contains a file "screenshot.png". It shows a blue screen with a weird distorted texture. I don't even see the distorted texture.

**Extra materials**

![image](https://user-images.githubusercontent.com/277318/233867651-7e4c7153-c399-4e7f-bf12-8515bfcd266c.png)

**Platform**
I am on Windows 10 Build 19045.  When I run the example it prints " NVIDIA GeForce RTX 3070 Ti (Vulkan)" for my gpu information. I have driver version 516.94. I have not tried to upgrade but I could. I have Rust 1.69.0. I tried this in both the trunk and v0.16 tags in git and got the same results.

**Comment by cwfitzgerald** [comment]
Hit space, and you should see them appear - #3723 should make this clearer
