### ISSUE TITLE
Allow disabling the `StageError::InputNotConsumed` error

### ISSUE THREAD

**Issue by Aaron1011** [gfx-rs/wgpu#3748]
**Is your feature request related to a problem? Please describe.**
The [Ruffle](https://github.com/ruffle-rs/ruffle/issues) project dynamically builds Naga shaders and wgpu render passes/pipelines based on user-provided code. It turns out that some user-provided input shaders have vertex shader outputs that are unused by the fragment shader. When we compile these shaders to Naga and pass the `naga::Module` to wgpu, a ` `StageError::InputNotConsumed` is produced.

**Describe the solution you'd like**
It would be very useful to be able to disable the wgpu check that produces `StageError::InputNotConsumed`. Since Ruffle is compiling user-provided shaders, the original input shaders are never going to be fixed (as they would be if the error occured when compiling Ruffle's own internal shaders).

**Describe alternatives you've considered**
Ruffle could duplicate the wgpu `InputNotConsumed` logic, and modify its shader compilation to produce a `naga::Module` that has no unused outputs in the vertex shaders. However, this adds unnecessary complexity and runtime overhead, as AFAIK all of the target wgpu backends should be able to handle a vertex shader with unused outputs.

**Additional context**
Ruffle is compiling *to* naga by building up a `naga::Module`, and then using a `wgpu::ShaderSource::Naga` with the built module.

**Comment by teoxoy** [comment]
The error was introduced by https://github.com/gfx-rs/wgpu/pull/2704 but this doesn't seem to be a requirement of the WebGPU spec.

The spec only requires that fragment inputs were output by the previous vertex stage.

> For each user-defined input of descriptor.fragment there must be a user-defined output of descriptor.vertex that location, type, and interpolation of the input.
> 
> > NOTE: Vertex-only pipelines can have user-defined outputs in the vertex stage; their values will be discarded.

_from https://gpuweb.github.io/gpuweb/#abstract-opdef-validating-inter-stage-interfaces_

So, we most likely need a workaround for https://github.com/gfx-rs/naga/issues/1945.

**Comment by cwfitzgerald** [comment]
Yeah, that requirement was backed out. Afaik, we just need to pipe the full list of vertex outputs into the fragment input in Naga so Naga can generate the correct struct.

**Comment by Imberflur** [comment]
> Yeah, that requirement was backed out. Afaik, we just need to pipe the full list of vertex outputs into the fragment input in Naga so Naga can generate the correct struct.

I've been looking into this a bit. The place where we have both vertex and fragment shaders, `create_render_pipeline`, pretty much has immutable access to the naga shader modules. So it seems like either the module needs to be cloned or this info could be passed through and utilized in the `hlsl::Writer`?

**Comment by teoxoy** [comment]
We'd ideally do this in the HLSL backend.

**Comment by Imberflur** [comment]
It looks like dawn implemented this by removing the outputs on the vertex shader side <https://bugs.chromium.org/p/dawn/issues/detail?id=1493#c20>.
