### ISSUE TITLE
Support `POLYGON_MODE_LINE` and `POLYGON_MODE_POINT` for GL

### ISSUE THREAD

**Issue by LucaCiucci** [gfx-rs/wgpu#3762]
**Is your feature request related to a problem? Please describe.**
I'm trying to use wgpu in a tauri application (compiling for `wasm32`), I need to draw some lines and points so I tried to request [`Features::POLYGON_MODE_LINE`](https://github.com/gfx-rs/wgpu/blob/f173575427b028dde71bdb76dce10d27060b03ba/wgpu-types/src/lib.rs#L651) and [`Features::POLYGON_MODE_POINT`](https://github.com/gfx-rs/wgpu/blob/f173575427b028dde71bdb76dce10d27060b03ba/wgpu-types/src/lib.rs#L651) using a GL backend, but the [`Adapter::request_device`](https://github.com/gfx-rs/wgpu/blob/f173575427b028dde71bdb76dce10d27060b03ba/wgpu/src/lib.rs#L1715) function returns an error if these features are requested. 

**Describe the solution you'd like**
Support these two polygon modes for the GL backend.

**Describe alternatives you've considered**
Use `PrimitiveTopology::LineList` or `PrimitiveTopology::PointList`, but `POLYGON_MODE_*` could simplify the usage in some cases, for example when switching the representation of a mesh to wireframe or points.

**Additional context**
None.

**Comment by cwfitzgerald** [comment]
`glPolygonMode` seems to be completely unsupported on GLES outside of `GL_NV_polygon_mode` which has basically zero support, so this is unfortunately not really feasible to support
