### ISSUE TITLE
Specify size is in bytes for buffer documentation

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#3768]
These two fields should specify that they're the size _in bytes_.

https://docs.rs/wgpu/latest/wgpu/enum.BindingType.html#variant.Buffer.field.min_binding_size

https://docs.rs/wgpu-types/0.16.0/wgpu_types/struct.BufferDescriptor.html#structfield.size

**Comment by jimblandy** [comment]
@JMS55 Are you working on this? If not, I could take care of this.

**Comment by JMS55** [comment]
I am not. I would love for someone else to tackle this, thank you.
