### ISSUE TITLE
Could the examples be under more permissive licenses?

### ISSUE THREAD

**Issue by mcclure** [gfx-rs/wgpu#3769]
This repo is dual-license MIT and Apache, which is very permissive for such a complex piece of software. However, there is no separate license for the *examples*, and for pure example code any license at all can be a problem.

At some level this is a nitpick but it can come up. For example, I am publishing some WebGPU examples of my own, and to make these examples as useful as possible I would like to publish them as CC0/public domain. But I may use the wgpu examples or parts of them as a basis for my examples, and— although I am grateful for the wgpu examples and so would absolutely credit the history of the examples in my repo!—, the MIT encumbrance means *my* samples must also be MIT encumbered. If I want to be as useful as possible, I find myself considering slightly silly options like writing examples from scratch entirely, or going over, say, hello-triangle trying to rewrite it to be legally distinct— which for something as simple as hello-triangle, which consists mostly of configuration, and is so simple it might not actually be eligible for copyright protection at all, sounds a little bit tortured. For this case it would be most practical if I could just think about the code and not think about licenses, so that *my* users are able to just think about the code and not the licenses.

Usually this is not really a concern for sample code for a *library*, because people can not use the sample code without also using the library. But in the case of wgpu, a user could target web, in which case wgpu would not be included as a library and would be just a set of bindings to the browser (I am *assuming* the wgpu library in wasm-bindgen mode does not result in license encumbrances). For very simple wasm embedded in a web page, having to follow the ordinarily minimal restrictions of MIT could actually be a bit awkward.

I know this is demanding, but would it be possible to add an additional LICENSE to the examples directory, or possibly just to the directories of the simplest examples (such as the `hello-`s), to license them under an "unrestricted" family such as CC0 or BSD-0 (IE, "disclaimer of warranty only")?

**Comment by jimblandy** [comment]
This seems completely fine to me. But I think we need the permission of the code's authors to re-license it.

**Comment by cwfitzgerald** [comment]
We can absolutely try to relicense the examples, it would just be rather annoying to the community as we'll have to ping a _lot_ of people (see #1473) to formally get their permission to relicense.

Otoh, on a human level (and IANAL and this is not legal advice blahblah) the examples are meant to be stolen from and no one is going to be remotely annoyed at them being used to create other tutorials. The whole point of examples is that you can copy from them. Plus they don't do anything particularly unique all parts of the examples could be found somewhere else as there's only so many ways to do basic rendering. I would personally just go ahead and use them.

**Comment by jimblandy** [comment]
I think we're not planning to take any action here. Feel free to re-open if this is not the case.
