### ISSUE TITLE
Add a feature gate to enable XR/Multiview rendering

### ISSUE THREAD

**Issue by MalekiRe** [gfx-rs/wgpu#3778]
As mentioned here https://github.com/gpuweb/gpuweb/issues/4109 the webgpu spec specifically does not allow for multiview rendering because of it's validation of 2D texture and 1 array layer of the render target texture. In order to be able to use WGPU to make XR applications I forked WGPU here with an example of how to resolve this issue. https://github.com/MalekiRe/wgpu and used it here in an openxr-wgpu example https://github.com/MalekiRe/wgpu-openxr-example

If we could have some form of disable for the validation as part of wgpu, because it seems like multiview *is* something eventually intended, that would be awesome.

**Comment by cwfitzgerald** [comment]
We already have a feature to make it conditional on, so we just need to make that validation looser when https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.MULTIVIEW is enabled

**Comment by MalekiRe** [comment]
Ooo can I make a PR that disables this validation when MULTIVIEW is enabled?
