### ISSUE TITLE
Support f16 float type

### ISSUE THREAD

**Issue by nathanielsimard** [gfx-rs/wgpu#3791]
I would like to be able to write compute shaders with wgpu using half precision, but it seems like it's impossible as of now.

```bash
var<storage, read_write> input: array<f16>;
                                      ^^^ unknown type

    unknown type: 'f16'
```

**Comment by teoxoy** [comment]
This is only supported via `spirv-passthrough`, track https://github.com/gfx-rs/wgpu/issues/4384 for support in WGSL.
