### ISSUE TITLE
`wgpu_core::storage::Storage::get` should panic if `id`'s index is bad

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#3802]
At the moment, `wgpu_core::storage::Storage::get` treats an `id` whose index is out of bounds for `Storage::map` the same as an `id` referring to an invalid resource. But an out-of-bounds id index is more like a vacant entry than an `Error` entry, so I think it should panic. This would simplify the code a bit because we could just use Rust indexing on `self.map`.

**Comment by teoxoy** [comment]
This has been done in https://github.com/gfx-rs/wgpu/commit/896418c74098b0f135583b7fc6310dc3aad16b8c (https://github.com/gfx-rs/wgpu/pull/5897).
