### ISSUE TITLE
Are `MAP_` modes with corresponding `COPY_` meant not to allow other usage modes?

### ISSUE THREAD

**Issue by apessino** [gfx-rs/wgpu#3805]
I am trying to add compute timestamps - I need to declare the buffer to resolve the stamps into as follows:

```rust
  timestamp_buffer: wgpu.device.create_buffer(&wgpu::BufferDescriptor {
                  label: None,
                  size: std::mem::size_of::<TimestampData>() as wgpu::BufferAddress,
                  usage: wgpu::BufferUsages::QUERY_RESOLVE
                      | wgpu::BufferUsages::MAP_READ
                      | wgpu::BufferUsages::COPY_DST,
                  mapped_at_creation: false,
              }),
```

This seems correct to me. Unfortunately, the call fails because of these checks starting at 399 in `wgpu\wgpu-core\src\device\resource.rs`:

```rust
      if !self
          .features
          .contains(wgt::Features::MAPPABLE_PRIMARY_BUFFERS)
      {
          use wgt::BufferUsages as Bu;
          let write_mismatch = desc.usage.contains(Bu::MAP_WRITE)
              && !(Bu::MAP_WRITE | Bu::COPY_SRC).contains(desc.usage);
          let read_mismatch = desc.usage.contains(Bu::MAP_READ)
              && !(Bu::MAP_READ | Bu::COPY_DST).contains(desc.usage);
          if write_mismatch || read_mismatch {
              return Err(resource::CreateBufferError::UsageMismatch(desc.usage));
          }
      }
```

Here `read_mismatch` is `true` even though both `MAP_READ` and `COPY_DST` are set, because `QUERY_RESOLVE` is **also** set. I don't think this is what is meant to be happening - I cannot use the buffer to resolve the queries unless it is set to `QUERY_RESOLVE` and I am not sure why the test above should prevent this. Is there something I am missing or is the validation just not implemented as intended?

Thanks!

**Comment by Wumpf** [comment]
It's more a case of bad error message & confusing code flow rather than a straight up error: The spec states at https://www.w3.org/TR/webgpu/#buffer-creation
```
If descriptor.[usage](https://www.w3.org/TR/webgpu/#dom-gpubufferdescriptor-usage) contains [MAP_READ](https://www.w3.org/TR/webgpu/#dom-gpubufferusage-map_read):

    descriptor.[usage](https://www.w3.org/TR/webgpu/#dom-gpubufferdescriptor-usage) must contain no other flags except [COPY_DST](https://www.w3.org/TR/webgpu/#dom-gpubufferusage-copy_dst).

If descriptor.[usage](https://www.w3.org/TR/webgpu/#dom-gpubufferdescriptor-usage) contains [MAP_WRITE](https://www.w3.org/TR/webgpu/#dom-gpubufferusage-map_write):

    descriptor.[usage](https://www.w3.org/TR/webgpu/#dom-gpubufferdescriptor-usage) must contain no other flags except [COPY_SRC](https://www.w3.org/TR/webgpu/#dom-gpubufferusage-copy_src).
```

And yes (quite recently!) this includes `QUERY_RESOLVE`, meaning that a query resolve buffer typically needs a secondary buffer with `COPY_DST` + `MAP_READ`

https://github.com/gfx-rs/wgpu/pull/3636 will add some more examples on timer queries.

Oh and I happen to maintain a crate for a higher level interface to make profiling via timer queries easy if you're interested https://github.com/Wumpf/wgpu-profiler :) (it essentially maintains a ringbuffer of queries for you)

**Comment by apessino** [comment]
I suspected something like that was going on, I appreciate you confirming it for me so quickly!

I guess one extra buffer it is. I must say, the whole `query` interface is not what some would call "ergonomic," even by GPU standards. The hoops one has to jump through just to get a few timings seem rather excessive (feels like lingering Vulkan-ism ;) ), but hey, it is what it is.

Thanks again!
