### ISSUE TITLE
'No suitable GPU adapters found on the system!' WebGL error when run on Chromium

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu#3811]
Hi! I've been noticing this issue with my own code recently and I just checked the examples here and found the same problem. When I run the cube example with `cargo run-wasm --example cube --features webgl` I get this error:

`panicked at 'No suitable GPU adapters found on the system!', wgpu/examples/cube/../framework.rs:190:14`

![20230529_10h15m01s_grim](https://github.com/gfx-rs/wgpu/assets/13566135/c14d229e-62c4-4f8b-926b-4a9b867c536c)

This happens on origin/trunk with commit 4478c52debcab1b88b80756b197dc10ece90dec9 on Chromium `Version 114.0.5735.45 (Official Build) Arch Linux (64-bit)` and notably **doesn't happen on Firefox `113.0.2 (64-bit)`**. I tried doing a bisect to see if anything was broke things and found that 37fbae78 and aa46e82f are also broken. I didn't go back further.

Is it possible that now that WebGPU has been properly released, there needs to be a setting added to the web canvas to specify that we want it for WebGL and not WebGPU?

OS: Arch Linux x86_64 with the 6.3.4-arch1-1 kernel.

**Comment by expenses** [comment]
I've tested a few more versions.
`116.0.5798.0 (Official Build) canary (64-bit)` on Windows 11: Working ✅ 
`Version 116.0.5799.0 (Developer Build) (64-bit)` on Linux: Not working ❌

**Comment by expenses** [comment]
I went all the way back to v0.13.0 (e125321bff7eb602d1849f18f22606afeebef3fb) in July 2022 and got a different but related error: `panicked at 'Cannot convert into WebGL2 context', wgpu-hal/src/gles/web.rs:40:14`

**Comment by expenses** [comment]
So I went and downgraded chromium from 114 to 111, which worked, then slowly upgraded it back up to try and bisect when it broke. But the latest version works again, even the 116 snapshot version. Not sure what happened here, bit of a mystery.

**Comment by Wumpf** [comment]
Fairly sure I also saw this spuriously occurring on Chrome 113
