### ISSUE TITLE
v0.16.1 release info is incomplete

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#3814]
* GitHub is showing v0.16.0 as "latest"
* trunk CHANGELOG.md shows the changes as unreleased

**Comment by emilk** [comment]
0.16.1 also did not include a release of `wgpu-hal`, which is still on 0.16.0, which means this fix got missed:
* https://github.com/gfx-rs/wgpu/pull/3780

**Comment by cwfitzgerald** [comment]
Ugh, what a mess - sorry about this. Fixing now.

**Comment by cwfitzgerald** [comment]
Fixed the releases on crates and github.

**Comment by emilk** [comment]
Awesome - thank you @cwfitzgerald ❤️
