### ISSUE TITLE
wgpu not rendering with gl_VertexIndex

### ISSUE THREAD

**Issue by Trap101** [gfx-rs/wgpu#3835]
see issue #3831 

I rose that last issue thinking that it's a naga problem, but wgpu just don't seem to be rendering at all with `gl_VertexIndex` passed in to a simple draw call. Is there anything I am missing?

**Comment by teoxoy** [comment]
Which backend is it not working on? Could you also share the full shader?

**Comment by Trap101** [comment]
The backend is Vulcan, according to `wgpu::adaptor::get_info()`. The full code is here

vertex shader
```
#version 450
void main(){
    vec2 pos[3] = vec2[3]( vec2(-0.7, 0.7),
                           vec2(0.7, 0.7),
                           vec2(0.0, -0.7) );
    gl_Position = vec4( pos[uint(gl_VertexIndex)], 0.0, 1.0 );
}
```

fragment shader
```
#version 450
layout(location=0) out vec4 FragColor;
void main(){
   FragColor = vec4(1.0,0.0,0.0,1.0);
}
```

**Comment by teoxoy** [comment]
I think that should work. Can you put together a minimum reproducible test case and share it here?

**Comment by Trap101** [comment]
https://github.com/Trap101/test_wgpu/tree/wgsl/src
here is the minim reproducible example

**Comment by Wumpf** [comment]
This is not a problem with `gl_VertexIndex`. That part works fine.

But your triangle winding order is the wrong way round. Either you need to fix up your shader or you either change which faces are front facing by doing `front_face: wgpu::FrontFace::Ccw` or disable culling via `cull_mode: None` (or tell it to full front faces, but that would be semantically odd)

**Comment by Wumpf** [comment]
Fixing up shader would require to swap two if the vertices, like so for example:
```
    vec2 pos[3] = vec2[3]( vec2(0.7, 0.7),
                           vec2(-0.7, 0.7),
                           vec2(0.0, -0.7) );
```
