### ISSUE TITLE
Validation errors about the dynamic offset count

### ISSUE THREAD

**Issue by kocsis1david** [gfx-rs/wgpu#386]
For the first draw call, I have these bind groups (bind group index, dynamic offset count):
(0, 1)
(1, 1)
(2, 1)

For the second draw call, I use two bind groups (but I rebind them all):
(0, 1) // compatible with the bind group 0 of the previous draw call, only the dynamic offset is different
(1, 1) // incompatible

I get the validation error when I bind the incompatible bind group, the error says that I provided 2 dynamic offsets when only 1 is required.
It seems that `binder.entries` still has 3 entries during the second draw call, but the `expected_layout_id` is None for the last entry. But this line (https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/command/bind.rs#L194) seems to also collect the dynamic offsets from the inactive last bind group.

**Comment by kvark** [comment]
Thanks to the log provided, I found the problem here: https://github.com/gfx-rs/wgpu/blob/469c086a1ae8843f87296f0b29dd7a6031aca3f9/wgpu-core/src/command/bind.rs#L187

The bind group iterator uses `TakeSome`, but the offsets don't. So if first one stops, we are still providing all the offsets erroneously.

**Comment by kocsis1david** [comment]
I thought TakeSome was correct to stop, because the pipeline layout didn't need the last bind groups.

But I could also imagine TakeSome to also stop if there is an empty slot between the bindings. E.g. if you bind something at the index 0 and 2, but you don't bind anything to index 1. In this case, `actual_value` would yield `Some`, `None`, `Some` and so the iterator would stop at the first `None` and the 2nd bind group wouldn't be bound if I understand the code correctly.

**Comment by kvark** [comment]
`TakeSome` *is* correct to stop. The problem is that it doesn't stop the dynamic offsets iterator.
