### ISSUE TITLE
Resizing Lag

### ISSUE THREAD

**Issue by CJBuchel** [gfx-rs/wgpu#3868]
I'm using Linux Pop Os 22 and something I've noticed which is quite odd is the resize lag in my application.
I'm unsure if it's the operating system, a bug or something that I'm neglecting and can't see.

My code is a bit spread with attempts of abstraction for my later use case, so bare with the snippets.
I have a loop which is just wrapped around a winit event loop like so `(my main application/super loop)`

```rs
e_loop.lock().run_loop(
      |mut e| {
        // prepare window
        {
          if let Some(mut window) = self.window.try_lock() {
            window.on_prepare(&mut e);
          }
        }

        // Get events and run dispatch
        self.on_event(&mut e);

        // // Update layers
        for layer in self.layer_stack.iter_mut() {
          layer.lock().on_update();
        }

        match e.event {
          winit::event::Event::RedrawRequested(_) => {
            // Render gui
            self.with_gui_layer(|gui| gui.begin());
            for layer in self.layer_stack.iter_mut() {
              layer.lock().on_gui_render();
            }
            self.with_gui_layer(|gui| gui.end());
          }
          _ => {}
        }

        {
          if let Some(mut window) = self.window.try_lock() {
            window.on_update(&mut e);
          }
        }

        // Get FPS
        fps_counter += 1;
        if fps_timer.elapsed() >= std::time::Duration::from_secs(1) {
          info!("FPS: {}", fps_counter);
          fps_counter = 0;
          fps_timer = std::time::Instant::now();
        }
      },
      running,
    );
```

And I have two functions which help with rendering a new frame, `window.on_prepare()` and `window.on_update()` which are both called in the loop, on_prepare at the start and on_update at the end.
```rs
pub(crate) fn on_prepare(&mut self, event: &mut EventContainer) {
    
    // Handle window resize event
    event.dispatch(|e| match e {
      winit::event::WindowEvent::Resized(size) => self.on_resize_event(&size),
      _ => false,
    });
    
    // handle window scale event
    event.dispatch(|e| match e {
      winit::event::WindowEvent::ScaleFactorChanged { scale_factor, new_inner_size } => {
        self.on_rescale_event(scale_factor, new_inner_size)
      },
      _ => false,
    });

    // check if there is a redraw event
    match event.event {
      winit::event::Event::RedrawRequested(_) => {
        self.graphics_context.new_frame();
      },
      _ => {}
    }
  }

  pub(crate) fn on_update(&mut self, event: &mut EventContainer) {
    match event.event {
      winit::event::Event::MainEventsCleared => {
        self.inner_window.request_redraw();
      },
      winit::event::Event::RedrawRequested(_) => {
        self.graphics_context.swap_buffers();
      },
      _ => {}
    }
  }
  
  fn on_rescale_event(&mut self, scale: &f64, size: &PhysicalSize<u32>) -> bool {
    self.set_scale(*scale);
    self.on_resize_event(size);
    true
  }

  fn on_resize_event(&mut self, size: &PhysicalSize<u32>) -> bool {
    self.set_width(size.width);
    self.set_height(size.height);
    
    if self.props.width == 0 || self.props.height == 0 {
      self.inner_window.set_minimized(true);
    } else {
      self.inner_window.set_minimized(false);
    }
    
    if self.props.width > 0 && self.props.height > 0 {
      self.graphics_context.surface_config.width = self.props.width;
      self.graphics_context.surface_config.height = self.props.height;
      self.graphics_context.reconfigure();
      self.inner_window.request_redraw();
    }
    true
  }
```

The on prepare function is just suppose to grab a new `SurfaceTexture` if a redraw event has been requested.
The on prepare also checks to see if a resize event has triggered, if it has then reconfigure and request a redraw.
And the on update function is suppose to request a redraw and if a redraw is already requested then present the `SurfaceTexture`.
```rs
pub(crate) fn new_frame(&mut self) {
    match &self.frame {
      Some(Err(f)) => {
        warn!("(new_frame) Surface warning {}", f);
        self.reconfigure();
      }
      None => {
        self.frame = Some(self.surface.get_current_texture());
      },
      _ => {}
    }
  }

  pub fn get_current_frame(&self) -> &Option<Result<SurfaceTexture, SurfaceError>> {
    &self.frame
  }

  pub(crate) fn reconfigure(&mut self) {
    let _ = self.frame.take(); // drop the current frame
    self.surface.configure(&self.device, &self.surface_config);
    self.frame = Some(self.surface.get_current_texture());
  }

  pub(crate) fn swap_buffers(&mut self) {
    match self.frame.take() {
      Some(Ok(frame)) => {
        frame.present();
      },
      None => {
        error!("(swap_buffer) No frame to swap");
      },
      _ => {}
    }
  }
```

And as far as I can tell this is the proper way to do it, by only calling `get_current_texture()` once, and making sure it's at the start. Then calling `present()` afterwards. And they only trigger if a redraw event is happening, much the same the actual rendering code also doesn't get called unless it's currently a redraw event.

Something very odd though is the extreme amount of lag when resizing, and the funny thing is... during debug mode the lag is acceptable, it's actually when I run release mode where the resizing feels as if it's 5fps.
There is also a random vulkan validation error when I exit my code but I'm assuming that's unrelated and not really important for the moment.

I have found a way around this, which is to omit checking if it's currently a redraw event or not and just grabbing a new `SurfaceTexture` every new loop. And also presenting the `SurfaceTexture` after every `MainEventsCleated` event.

For instance if I just change my `on_update` and `on_prepare` the I get much more reasonable frames when resizing
```rs
pub(crate) fn on_prepare(&mut self, event: &mut EventContainer) {
    
    // Handle window resize event
    event.dispatch(|e| match e {
      winit::event::WindowEvent::Resized(size) => self.on_resize_event(&size),
      _ => false,
    });
    
    // handle window scale event
    event.dispatch(|e| match e {
      winit::event::WindowEvent::ScaleFactorChanged { scale_factor, new_inner_size } => {
        self.on_rescale_event(scale_factor, new_inner_size)
      },
      _ => false,
    });

    // check if there is a redraw event
    self.graphics_context.new_frame();
  }

  pub(crate) fn on_update(&mut self, event: &mut EventContainer) {
    match event.event {
      winit::event::Event::MainEventsCleared => {
        self.inner_window.request_redraw();
        self.graphics_context.swap_buffers();
      },
      _ => {}
    }
  }
```

This method however isn't exactly desirable because it's inefficient. And it also presents a `SurfaceTexture` regardless of if work has been submitted for it. Causing a bunch of `wgpu_core::present` errors, which don't seem like they actually cause any real errors. But I assume it's there for a reason, and I also don't have a way to check if it's presentable or not.

I'm just really baffled, I'm unsure why the resizing is quite so laggy for me, and what's more weird is why it's much worse on release. Regardless of what method I'm using it seems that release mode has an issue with resizing events, it's quite bad.
I'm also really confused why the "proper" way of getting and presenting a new frame actually makes the resizing events feel so choppy as well. My preference is to use the proper method, but while it seems inefficient I actually would prefer to just call a frame each cycle instead.

So I guess my question is, is it bad to improve the speed of the resizing by using my hack method? And also why does the normal resizing feel so choppy, and even worse so when compiled in release mode?

**Comment by CJBuchel** [comment]
For reference about what I mean, you can see below.

This is a recording of the hacky method for getting and presenting a frame compiled in release mode
https://github.com/gfx-rs/wgpu/assets/35585061/68769436-f373-4ab1-8170-b2aad46095a8


This is a recording of the "proper" method for getting and presenting a frame in release mode
https://github.com/gfx-rs/wgpu/assets/35585061/a6c207cd-3efd-46e7-b99c-2ea2195a702c

And this is the same, using what I consider the "proper" method but instead compiled in debug mode. I just find it interesting that it's quicker. The hacky method during debug mode is also significantly quicker when resizing.
https://github.com/gfx-rs/wgpu/assets/35585061/11a2ab06-98c7-4d51-9de0-f0d93c594168

- edit
I tested it on windows 11 and doing it the "proper" way is butter smooth. Both in debug mode and in release, then again it is also using DirectX12 instead of Vulkan but still. Huge difference. What's more interesting though is my "hack" doesn't actually work at all on windows, it runs but it basically crashes when you resize it or try to close the window. So I guess I know which method I'm using, I guess I'm just curious if there is a solution to it being so choppy on linux?

**Comment by Q4LEX** [comment]
I am currently coding a small vulkan renderer and I experience the same things, even when absolutely minimizing the work that is done when the window is resized. On windows? It runs butterly smooth. I am also running POP..

After some internet "research" I figured it's just a quirk of how POP_os handles things and we have to live with it ¯\_(ツ)_/¯.

Maybe I'm wrong though

**Comment by jimblandy** [comment]
It seems like there's no action wgpu needs to take here, so I'm closing this. Feel free to re-open.
