### ISSUE TITLE
executable exits with `STATUS_ENTRYPOINT_NOT_FOUND` if `GetWindowSubclass` is used

### ISSUE THREAD

**Issue by LucaCiucci** [gfx-rs/wgpu#3884]
Note: I'm not sure this issue concerns WGPU or some other crate from the dependencies.

**Description**
When using `GetWindowSubclass` (either from `winapi` or `windows` crate), the program exits with code `0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND`. Removing `use wgpu` the error goes away.

**Repro steps**
Here are two examples:
```rust
/*
[dependencies]
wgpu = "0.16.1"
winapi = "0.3.9"
*/

use wgpu; // <- removing this, the error goes away
use winapi::um::commctrl::GetWindowSubclass;
fn main() {
    let _ = unsafe { GetWindowSubclass(0 as _, None, 0, 0 as _); };
}
```

```rust
/*
[dependencies]
wgpu = "0.16.1"
windows-sys = { version = "0.48.0", features = ["Win32_UI_Shell", "Win32_Foundation"] }
*/

use wgpu; // <- removing this, the error goes away
use windows_sys::Win32::UI::Shell::GetWindowSubclass;
fn main() {
    let _ = unsafe { GetWindowSubclass(0 as _, None, 0, 0 as _); };
}
```
Executing `cargo run` the output is:
```
error: process didn't exit successfully: `target\debug\aaa.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)
```
Double-clicking on the executable produces the following error (message box):
```
The procedure entry point GetWindowSubclass could not be located in the dynamic link library C:\...\<my-executable>.exe
```

**Expected vs observed behavior**
No error

**Extra materials**
Debugging with Visual Studio:
```
'aaa.exe' (Win32): Loaded 'C:\Users\lucac\Desktop\aaa\target\debug\aaa.exe'. Symbols loaded.
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.22621.608_none_fb280a3c7926c2cc\comctl32.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'aaa.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. 
Exception thrown at 0x00007FFC4835EE2D (ntdll.dll) in aaa.exe: 0xC0000139: Entry Point Not Found.
The thread 0x1ad0 has exited with code 3221225785 (0xc0000139).
The thread 0x7130 has exited with code 3221225785 (0xc0000139).
The program '[27624] aaa.exe' has exited with code 3221225785 (0xc0000139) 'Entry Point Not Found'.
```

**Platform**
Windows, tried the following toolchains:
```
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc
stable-i686-pc-windows-msvc
```

**Comment by cwfitzgerald** [comment]
What on earth?

I have no idea how to even start debugging this. https://github.com/gabdube/native-windows-gui/issues/241 is something that came up when I googled, which might have some information about it. Seems like it's either a thing where you need to ship manifests or some incompatibility is winapi and windows-rs.

**Comment by ErichDonGubler** [comment]
Ah, this tickles an old experience of mine. Just took some time to refresh myself on [this](https://github.com/microsoft/windows-rs/issues/1294#issuecomment-968126521), which I think is relevant. TL;DR: you will need to use a manifest to opt into `comctl32.dll` 6.* or older, assuming you wish to continue with `winapi`. There was an issue with the 5.* version series where `GetWindowSubclass` was exposed in one way, but not another (ordinal and symbol name, I want to say?). EDIT: IIRC, you can sidestep this altogether with `windows-sys`?

Because of the above, I feel confident that this is not a WGPU-specific issue.

**Comment by LucaCiucci** [comment]
gabdube/native-windows-gui#241 and microsoft/windows-rs#1294 are definetly related to this problem. I will try the [manifest solution](https://github.com/microsoft/windows-rs/issues/1294#issuecomment-968126521) tomorrow and post an update.

Yes, at this point I agree this is probably not a WGPU issue.
