### ISSUE TITLE
add default parameter version of function

### ISSUE THREAD

**Issue by ghost** [gfx-rs/wgpu#3888]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

for example:

https://www.w3.org/TR/webgpu/#gpu-interface
```javascript
interface GPU {
  Promise<GPUAdapter?> requestAdapter(optional GPURequestAdapterOptions options = {} );
}
```
turn
```rust
wgpu::Instance::request_adapter(&self,options:&RequestAdapterOptions<'_>) -> ...
```
into
```rust
wgpu::Instance::request_adapter_a(&self,options:Option<&RequestAdapterOptions<'_>>) -> ...
```
```rust
wgpu::Instance::request_adapter_b(&self) -> ...
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
you says "The api is based on the [WebGPU standard](https://gpuweb.github.io/gpuweb/)"
but the implementation is partial

**Comment by cwfitzgerald** [comment]
Hello, thanks for filling!

As we're mapping the Javascript api to rust, we make adjustments to it to make it more ideomatic rust. One of those adjustments is through the use of the default trait as opposed to options:

You can call `instance.request_adapter(&RequestAdapterOptions::default())` if you want to default all the fields. If you want to default only some of them, you can use [rust's struct update syntax](https://doc.rust-lang.org/reference/expressions/struct-expr.html#functional-update-syntax)
