### ISSUE TITLE
Add support for WGSL `override` declarations

### ISSUE THREAD

**Issue by e2-71828** [gfx-rs/wgpu#3895]
**Is your feature request related to a problem? Please describe.**
I have some constant values that need to have the same value in both Rust and WGSL code.  Ideally, these constants should be determinable at runtime, so that the program has the opportunity to read them from a configuration file at startup.

**Describe the solution you'd like**
The WGSL specification describes [`override` declarations](https://www.w3.org/TR/WGSL/#override-decls) which are designed for this purpose.  In WebGPU, these are set by specifying `GPUPipelineConstant`s in the [`GPUProgrammableStage` description](https://www.w3.org/TR/webgpu/#gpuprogrammablestage).  The corresponding [`wgsl` type](https://wgpu.rs/doc/wgpu_hal/struct.ProgrammableStage.html), however, does not include any facility to specify these constants.

**Describe alternatives you've considered**
There are a few workarounds possible to get similar results:
1. The values can be passed from Rust to WGSL in a uniform buffer, but this requires using an additional binding in each render pass and the shader compiler can't use any optimizations that take advantage of the fact that this constant won't actually change between draw calls.
2. A build script or proc macro can read the constant value out of the shader source and import it into Rust.  This adds a lot of complexity, and means that these constants must be known at compile time, and can't be determined during the graphics system initialization.
3. The shader source can be transformed by some kind of templating engine before being handed to the shader compiler.  This also adds significant complexity, and means that you're using a nonstandard dialect of WGSL which makes it harder to integrate other tools, like a build-time shader validation check.

**Comment by Wumpf** [comment]
Thanks for the detailed report, but this is actually already an existing issue here https://github.com/gfx-rs/wgpu/issues/1762 and there's quite a bit of work to do on Naga as well to enable this https://github.com/gfx-rs/wgpu/issues/4484
You're spot in in that wgpu isn't WebGPU conformant there yet.
