### ISSUE TITLE
request_adapter returns None for VMware SVGA II Adapter

### ISSUE THREAD

**Issue by qdwang** [gfx-rs/wgpu#3909]
**Description**
It's failed to get the adapter in a vmware ubuntu 20.04 environment. 

**Repro steps**
```rust
use winit::{
    event_loop::{EventLoop},
    window::WindowBuilder,
};

fn main() {
    pollster::block_on(init());
}

async fn init() {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop).unwrap();

    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::all(),
        dx12_shader_compiler: Default::default(),
    });
    
    let surface = unsafe { instance.create_surface(&window) }.unwrap();

    let adapter = instance.request_adapter(
        &wgpu::RequestAdapterOptions {
            power_preference: wgpu::PowerPreference::default(),
            compatible_surface: Some(&surface),
            force_fallback_adapter: false,
        },
    ).await.unwrap(); // panic here because of the None result

    println!("{:?}", adapter);
}
```
Just run this code under Ubuntu 20.04 in vmware player.
It will panic at the `request_adapter` step.

**Expected vs observed behavior**
It should return the adapter.

**Extra materials**
The `glow` crate works fine in the same environment.

**Platform**
Ubuntu 20.04 in vmware player 16
```
$ lspci | grep VGA
00:0f.0 VGA compatible controller: VMware SVGA II Adapter
```

**Comment by cwfitzgerald** [comment]
Can you run `glxinfo`? Additionally can you set up `env_logger::init()` in your code, then run with `RUST_LOG=info`. We require gles 3.0 or greater and I suspect the SVGA driver doesn't support gles 3.

**Comment by qdwang** [comment]
I checked `glxinfo`, it shows a gles 2 version. 
`OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.0.8`

Thanks for the reply.
