### ISSUE TITLE
On Vulkan, debug labels shouldn't require validation layer

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#3913]
In #3809, I unintentionally made the population of `wgpu_hal::vulkan::InstanceShared::debug_utils` conditional on *both*:
- the availability of the `VK_EXT_debug_utils` extension *and*
- the availability of the `VK_LAYER_KHRONOS_validation`.

It it perfectly possible to report debug labels even when validation is not enabled: the extension and the layer are independent of each other.

**Comment by kulkalkul** [comment]
If anyone else encounters this, InstaceFlags::VALIDATION is enabled when debugging but it still requires Vulkan Configurator installed (bundled in Vulkan SDK I think).
