### ISSUE TITLE
Backends::GL doesn't work on macOS

### ISSUE THREAD

**Issue by olegus199** [gfx-rs/wgpu#3919]
**Description**

Hello! I've figured out that Backends::GL doesn't work on macOS. At first I noticed it in my game project. I'm creating a game with Bevy engine, which uses wgpu. I'm making it on M1 MacBook and testing it on iMac late 2012. Both Macs are supporting Metal, so no problem was there. But then I've tested the game on the iMac mid 2011 which doesn't support Metal and supports OpenGL only, and the game crashed with panic "Unable to find a GPU". 

Then I took step forward and checked my egui program which I write with backend wgpu. I tried to manually turn on GL there on my M1 MacBook and it crashed. After that, I've created a blank program, where I initialised window with winit, I initialised adapter, device, queue etc (following the instructions with which I learn wgpu). I've created a simple square on the screen and manually turned on Backends::GL, and the program crashed. 

I have programs on my M1 which works fine with OpenGL, and in the wgpu it doesn't seem to work. So, what I may be doing wrong? I will appreciate your reply, thanks!

**Platform**

wgpu 0.16.2

**Comment by Wumpf** [comment]
Short story is that wgpu's GL backend is actually GLES for the most part (maybe we should rename that 🤔 ). So if you _really_ want to run with the GL backend on Mac, you'd need to use Angle.
See https://github.com/gfx-rs/wgpu#supported-platforms and https://github.com/gfx-rs/wgpu#angle
Might be that nobody tried this in a while on Mac, so not sure if it will actually work out.
