### ISSUE TITLE
use wgpu in Unity native rendering plugin

### ISSUE THREAD

**Issue by ZhaoXiangXML** [gfx-rs/wgpu#3930]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a [Unity native rendering plugin](https://github.com/Unity-Technologies/NativeRenderingPlugin) with rust that does computing on GPU. I think it would be nice to integrate wgpu with Unity so I can dispatch compute shaders with wpgu in unity.

**Describe the solution you'd like**
Since Unity has already initialized the graphic device when it starts, I think it's possible to skip some initialization code of wgpu and use what's provided by Unity instead.

e.g. for Vulkan, this struct is prepared by Unity:
```cpp
struct UnityVulkanInstance
{
    VkPipelineCache pipelineCache; // Unity's pipeline cache is serialized to disk
    VkInstance instance;
    VkPhysicalDevice physicalDevice;
    VkDevice device;
    VkQueue graphicsQueue;
    PFN_vkGetInstanceProcAddr getInstanceProcAddr; // vkGetInstanceProcAddr of the Vulkan loader, same as the one passed to UnityVulkanInitCallback
    unsigned int queueFamilyIndex;

    void* reserved[8];
};
```

I'm new to GPU programming, I'm not sure about the difficulty in this.

Reference: https://github.com/aosoft/unity-native-plugin-rs

**Describe alternatives you've considered**

**Additional context**

**Comment by Wumpf** [comment]
> I think it would be nice to integrate wgpu with Unity so I can dispatch compute shaders with wpgu in unity.

You could also just dispatch compute shaders in Unity directly? https://docs.unity3d.com/Manual/class-ComputeShader.html

I think integrating an existing graphics device + queue into wgpu is a bit too much to ask for the API. We're already struggling in taking more basic existing resources like textures and buffers (for which there are many usecases and a path towards that).

Closing this since I believe this is out of scope and don't see the usecase for this.

**Comment by ZhaoXiangXML** [comment]
My use case is to do some computing by both CPU and GPU in rust code, like PhysX which is a physics engine that can do some computing on GPU.

My computing engine is supports to work both as standalone executable and Unity plugin.

I understand it's not in the plan of wgpu, however any instruction on how could I implement it myself would be helpful.

Thanks
