### ISSUE TITLE
Possible to delete a buffer that is mapped asynchronously

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#395]
The library doesn't correctly detect if a buffer is mapped for the matter of cleaning it up. We are only checking for the pending map operation on the GPU: https://github.com/gfx-rs/wgpu/blob/4fdb54d33a38632ee111465e4c8282dc95994aa8/wgpu-core/src/device.rs#L302

Instead, we need to turn this into an enum:
```rust
enum MapState {
  Waiting, // waiting for GPU to be done before mapping
  Active, // mapped
  Idle, // not mapped
}
```

**Comment by kunalmohan** [comment]
Hi! I want to get more familiar with the structure of the API and I think this would be a good start for the same. I would like to try and solve this one.

**Comment by aloucks** [comment]
I think mapped/unmaped is much more descriptive than active/idle. I find it easier to think about it as the state of the buffer instead of the state of the buffer mapping.

```rust
enum BufferState {
  // GPU has in-flight commands that are still referencing this buffer
  Referenced { map_pending: bool },
  Mapped, 
  Unmapped,  
}
```

And then we can short circuit the mapping of buffers that are not in flight:

(pseudo code)

```rust
async fn map_write(&self) -> Result<BufferWriteMapping, Error> {
  match get_buffer_state(self.id) {
    // Update the state to mapped and resolve immediately
    BufferState::Unmapped => set_buffer_state(self.id, BufferState::Mapped),
    BufferState::Mapped => Err("buffer is already mapped"),
    BufferState::Referenced { map_pending: true } => Err("buffer mapping already requested"),
    // request_write_map would set `map_pending` to true and return a future
    // that resolves once the mapping is complete
    BufferState::Referenced { map_pending: false } => request_write_map(self.id),
  }
}

**Comment by kunalmohan** [comment]
Just a thought...instead of storing a bool in map_pending, I can simply store `Option<BufferPendingMapping>` and remove https://github.com/gfx-rs/wgpu/blob/306554600ab7479ec3e54d0c076c71f02474237a/wgpu-core/src/resource.rs#L89

**Comment by kunalmohan** [comment]
I am a bit confused. The `map_write` you mentioned above will be implemented in wgpu-rs, right? So the check here https://github.com/gfx-rs/wgpu/blob/306554600ab7479ec3e54d0c076c71f02474237a/wgpu-core/src/device/mod.rs#L2082-L2085 will need to be moved with it. Do we need that? Or am I think something wrong here?

**Comment by kunalmohan** [comment]
Also I am not sure when to set the `BufferMapState` to `Referenced`.

**Comment by kvark** [comment]
Here is where [we scan](https://github.com/gfx-rs/wgpu/blob/306554600ab7479ec3e54d0c076c71f02474237a/wgpu-core/src/device/mod.rs#L1445) through resources used in a submission.

**Comment by kunalmohan** [comment]
This seems to be more confusing than I thought :sweat_smile:. I have,therefore, opened a draft PR for initial review #547 .
