### ISSUE TITLE
Inconsistent wgpu wiki for middleware implementation

### ISSUE THREAD

**Issue by PPakalns** [gfx-rs/wgpu#3953]
**Description**
Inconsistent wgpu wiki for middleware implementation

https://github.com/gfx-rs/wgpu/wiki/Encapsulating-Graphics-Work

Has Internal and External graphics data approach.

For Internal approach at the start of document middleware function signatures are defined:
```rs
impl MiddlewareRenderer {
    fn new(&Device, &TextureFormat, ..) -> Self;

    // Prepare for rendering, create all resources used during render, storing render data internally
    fn prepare(&mut self, ..);

    // Render using internal data and user provided renderpass
    fn render<'rpass>(&'rpass mut self, &mut RenderPass<'rpass>);
}
```

Further in text render function has different signature:
```rs
fn render<'rpass>(&'rpass self, &mut RenderPass<'rpass>);
```

without mut access to self.

I assume, as self need to life as long as rpass, it should be an immutable reference to better integrate with frameworks that support wgpu middlewares.

For example egui_wgpu  https://docs.rs/egui-wgpu/latest/egui_wgpu/renderer/struct.CallbackFn.html assumes that in render/paint stage of rendering all middleware data is immutable.

What is the best practices approach?

I suggest to use the following function signature:
`fn render<'rpass>(&'rpass self, &mut RenderPass<'rpass>);`

**Comment by cwfitzgerald** [comment]
Ah! That must have been a typo! The render function is designed to be `&'rpass self` as that allows multiple calls to the render function

**Comment by cwfitzgerald** [comment]
Updated the wiki!
