### ISSUE TITLE
Buffer does not exist panic, after buffer is destroyed while a mapping operation is queued

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/wgpu#3971]
**Description**
An internal panic is triggered in `wgpu-core` after a buffer is unmapped and dropped while a mapping operation is still queued.

**Repro steps**
I've reduced the problem to the following reproduction case
```rust
fn main() {
    // SETUP CODE
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());
    let adapter = pollster::block_on(wgpu::util::initialize_adapter_from_env_or_default(
        &instance, None,
    ))
    .unwrap();

    let (device, queue) =
        pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor::default(), None))
            .unwrap();

    // CREATE BUFFERS
    let dest = device.create_buffer(&wgpu::BufferDescriptor {
        label: None,
        size: 16,
        usage: wgpu::BufferUsages::MAP_READ | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });

    let index = queue.submit(Some(
        device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor::default())
            .finish(),
    ));

    // SUBMISSIONS
    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor::default());
    encoder.clear_buffer(&dest, 0, None);
    queue.submit(Some(encoder.finish()));

    dest.slice(..).map_async(wgpu::MapMode::Read, |_| {});

    device.poll(wgpu::Maintain::WaitForSubmissionIndex(index));

    dest.unmap();
    std::mem::drop(dest);

    device.poll(wgpu::Maintain::Wait);
}
```

This reproduction case is very artificial but in practice it can happen when a submission takes longer to finish than the first poll call and the `unmap` and `drop` are allowed to run before the second poll call.

**Expected vs observed behavior**

With the previous code I reliably get the following panic:

```
thread 'main' panicked at 'Buffer[0] does not exist'
```

I expected the code to work fine or at least have a proper error message of what I did wrong.

**Extra materials**

The problem seems to only work with the combination of `unmap` and `drop`, I think the problem is that the `unmap` causes the buffer `map_state` to go, from `Waiting` to `Idle` causing the `RefCount` on `BufferPendingMapping` to be dropped, which with the following `drop` causes the life count to reach 0, which marks the buffer as being ready for destruction on `triage_suspected` and passing the life count check on `remove_abandoned`.

This normally wouldn't be a problem, but since the second submission (which at this point still hasn't been completed), uses the buffer in one of it's commands, this causes the buffer to not be immediately mapped but instead pushed into the submission's `ready_to_map`.

Finally when the submission is finally finished (in the last poll), `handle_mapping` will be called which will look into the submission's `ready_to_map`, which will try to access the buffer but the buffer was already removed causing the panic.

There seems to be checks for buffers that were already destroyed, but the problem here is that the buffer was completely removed.

**Platform**
Linux x64, wgpu a7798f2f8ade7829ffc08c47ff12c338a456b0aa, NVIDIA GeForce RTX 3060 running the 535.86.05 drivers.

**Comment by Elabajaba** [comment]
This doesn't panic for me on arcanization https://github.com/gfx-rs/wgpu/pull/3626

**Comment by jimblandy** [comment]
Since arcanization has landed, I'm closing this bug. Please feel free to re-open if it seems like it's still a problem.
