### ISSUE TITLE
Colours on WebGPU backend are darker than WebGL2 or Vulkan

### ISSUE THREAD

**Issue by arthomnix** [gfx-rs/wgpu#3976]
**Description**
Colours appear darker when using the WebGPU backend than when running the same app on the web with WebGL or natively with Vulkan.
Possibly related to #3016?

**Repro steps**
View the WebGL version at https://arthomnix.dev/fractal (note: you will need to use a browser that does not support WebGPU, otherwise it will redirect automatically to the WebGPU version)

Alternatively, you can run the project natively, sources are available at https://github.com/arthomnix/fractal_viewer

Then open https://arthomnix.dev/fractal/webgpu in a browser that supports WebGPU - the colours will be darker than the WebGL or native versions.

**Expected vs observed behavior**
I expect the colours to be the same regardless of backend, whereas in reality the colours are darker on WebGPU than other backends.

**Extra materials**
![20230725_15h12m27s_grim](https://github.com/gfx-rs/wgpu/assets/35371030/c9cbb8a6-ce60-4f2f-82c2-b11adb104b9c)
Side by side comparison of WebGL version (Firefox 116.0b8 Developer Edition) and WebGPU version (Firefox 117.0a1 Nightly)

![20230725_15h16m53s_grim](https://github.com/gfx-rs/wgpu/assets/35371030/d9eab94b-553b-4a55-b0a4-005ebfd2f3e9)
Native version using Vulkan backend - same colours as WebGL

**Platform**
wgpu 0.16.3 (can't upgrade to 0.17 as the project uses egui-wgpu which depends on 0.16)
Native version tested on Arch Linux with Wayland desktop and Intel Haswell integrated GPU, and on a Steam Deck running SteamOS 3
WebGL version tested on Firefox Developer Edition 116.0b8 and Chromium 115 on the previously mentioned Arch machine
WebGPU version tested on Firefox Nightly 117.0a1 on the previously mentioned Arch machine

**Comment by jinleili** [comment]
On [WebGPU spec](https://www.w3.org/TR/webgpu/#canvas-configuration), you need to use `view_formats` to set the sRGB color target.
<img width="608" alt="截屏2023-07-28 13 27 54" src="https://github.com/gfx-rs/wgpu/assets/1001342/fc96b9df-c623-47bf-88cc-2fd65485c3ad">
<img width="573" alt="截屏2023-07-28 13 28 27" src="https://github.com/gfx-rs/wgpu/assets/1001342/6f82b398-3afb-4396-84b2-c2cfe1fdce14">
