### ISSUE TITLE
Question: Crash with webgpu-backend in browser, "canvas context is not a GPUCanvasContext"

### ISSUE THREAD

**Issue by ghost** [gfx-rs/wgpu#3980]
## Description

When I run the examples/hello_triangle example in Chrome browser, an exception is printed in the browser's console:

``` txt
panicked at 'canvas context is not a GPUCanvasContext: Object { obj: JsValue(GPUCanvasContext) }', wgpu\src\backend\web.rs:852:14
```

## Repro steps

Build:

``` bat
cd examples/hello_triangle

cargo build --target wasm32-unknown-unknown 

wasm-bindgen --out-dir generated --web ../../target/wasm32-unknown-unknown/debug/hello-triangle.wasm
```

Create index.html in the examples/hello_triangle/generated/ directory, with the following content:

``` html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hello Triangle</title>
    </head>
    <body>
        <script type="module">
            import init from "./hello-triangle.js";
            init();
        </script>
    </body>
</html>
```

Navigate to the examples/hello_triangle/generated/ directory and start a web server;

## Expected vs observed behavior

I expected to see a triangle effect in Chrome.

## Platform

+ Windows 11
+ chrome 115.0.5790.102
+ rustc 1.65.0 (897e37553 2022-11-02)
+ wasm-bindgen 0.2.87
+ wgpu 0.17.0
    - SHA-1: 8a8e00a5a523311c7576eebf953bcc5ffa56f557
    - refactor(wasm): remove unnecessary JsCast import

**Comment by jinleili** [comment]
`RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --target wasm32-unknown-unknown`
`RUSTFLAGS=--cfg=web_sys_unstable_apis` cannot be omitted. There is a more convenient way to run wgpu examples, just execute:
`cargo xtask run-wasm --bin hello-triangle `

**Comment by ghost** [comment]
> `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --target wasm32-unknown-unknown` `RUSTFLAGS=--cfg=web_sys_unstable_apis` cannot be omitted. There is a more convenient way to run wgpu examples, just execute: `cargo xtask run-wasm --bin hello-triangle `

thanks very much, use 'cargo xtask run-wasm --bin hello-triangle' I can see a triangle now.

**Comment by ghost** [comment]
> `RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --target wasm32-unknown-unknown` `RUSTFLAGS=--cfg=web_sys_unstable_apis` cannot be omitted. There is a more convenient way to run wgpu examples, just execute: `cargo xtask run-wasm --bin hello-triangle `

Hello, according to your prompt, I have successfully run it with xtask run-wasm; but I tried another way you said, adding the RUSTFLAGS environment variable, but there is still a problem when running. Do you have any clues? Tell me, the difference between xtask and cargo build; 

very grateful;

Specific steps: WIndows 11

``` cmd
set RUSTFLAGS=--cfg=web_sys_unstable_apis

cargo build --bin hello-triangle --target wasm32-unknown-unknown 

wasm-bindgen --out-dir static/ --web target/wasm32-unknown-unknown/debug/hello-triangle.wasm
```

Add index.html in static/, the content is as shown in the content;

**Comment by jinleili** [comment]
This is the build script I created for the wgpu Chinese tutorial. I hope it can be helpful:
https://github.com/jinleili/learn-wgpu-zh/blob/master/build-wasm.sh

If you are using wgpu 0.17 or the trunk branch,  make sure to install version 0.2.87 of wasm-bindgen-cli:
`cargo install -f wasm-bindgen-cli --version 0.2.87`
