### ISSUE TITLE
VertexFormat documentation uses GLSL instead of WGSL types

### ISSUE THREAD

**Issue by ScanMountGoat** [gfx-rs/wgpu#3990]
The current documentation uses GLSL types like `float` and `ivec4` instead of WGSL types like `f32` or `vec4<i32>`. This is related to #2849. This should be an easy fix, but I'm not sure how to handle double precision types. It doesn't look like double precision is mentioned anywhere in the [WGSL spec](https://www.w3.org/TR/WGSL/) other than literals.

https://www.w3.org/TR/webgpu/#enumdef-gpuvertexformat

**Comment by Wumpf** [comment]
regarding double, let's just pretend it's called `f64`. It's very likely that in the future there's going to be official wgsl extensions with that, see https://github.com/gfx-rs/wgpu/issues/4410
