### ISSUE TITLE
`VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR` Present When Portability Extension Is Not

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4004]
Test the suppress-obs-vuid using the latest wgpu (wgpu-hal with Suppress validation error caused by OBS layer (#4002)):

`wgpu = { git = "https://github.com/gfx-rs/wgpu.git" }`

on Windows 11, Nvidia RTX 3060 with Vulkan backend. Still got a validation error:

`VUID-VkInstanceCreateInfo-flags-zerobitmask(ERROR / SPEC): msgNum: 1636402386 - Validation Error: [ VUID-VkInstanceCreateInfo-flags-zerobitmask ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x618984d2 | vkCreateInstance: parameter pCreateInfo->flags must be 0. The Vulkan spec states: flags must be 0 (https://vulkan.lunarg.com/doc/view/1.3.204.1/windows/1.3-extensions/vkspec.html#VUID-VkInstanceCreateInfo-flags-zerobitmask)`

However, this error only occurs once, but not on every frame, which is different from the previous error that is logged every frame.

The app runs fine, but this error is still very annoying.

_Originally posted by @jack1232 in https://github.com/gfx-rs/wgpu/issues/4002#issuecomment-1664582002_

**Comment by jimblandy** [comment]
For the sake of searches, I'll just mention `VUID-VkInstanceCreateInfo-flags-06559` here.

**Comment by jack1232** [comment]
It works. Thank you!
