### ISSUE TITLE
`Queue::on_submitted_work_done` Does Not Obey WebGPU Ordering Contract

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4024]
**Description**

The wgpu spec specifies the following about promise ordering:

> For some [GPUQueue](https://gpuweb.github.io/gpuweb/#gpuqueue) q and [GPUBuffer](https://gpuweb.github.io/gpuweb/#gpubuffer) b on the same [GPUDevice](https://gpuweb.github.io/gpuweb/#gpudevice), 
> if p1 = b.[mapAsync()](https://gpuweb.github.io/gpuweb/#dom-gpubuffer-mapasync) is called before p2 = q.[onSubmittedWorkDone()](https://gpuweb.github.io/gpuweb/#dom-gpuqueue-onsubmittedworkdone), 
> then p1 must settle before p2.

**Repro steps**

Submit a piece of work. Block until it is done. Call `map_async` on a buffer touched by that submit, then call `on_submitted_work_done`. The callback for `on_submitted_work_done` will immediately fire, despite the `map_async` callbacks not happening.

**Other**

Should be pretty easy to fix this, we just need to remove the optimistic immediate call of the callback. Will try to fix this tomorrow.

**Comment by teoxoy** [comment]
Has been recently clarified in https://github.com/gpuweb/gpuweb/pull/4117

**Comment by cwfitzgerald** [comment]
It was always my understanding of what should happen, but that's when it was formalized.
