### ISSUE TITLE
Support for object labels

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#404]
gfx-hal got support for labels in https://github.com/gfx-rs/gfx/pull/3000 and follow-ups. It doesn't cover all objects, but it's incredibly useful already.

The [upstream API](https://gpuweb.github.io/gpuweb/) has commands for starting/ending a debug region (see `insertDebugMarker`) and setting the labels on most objects. We need to implement it.

**Comment by schulzch** [comment]
Having [debug labels and messages](https://www.khronos.org/opengl/wiki/Debug_Output) for Nsight, RenderDoc, and the like would be pretty awesome. This issue is probably related to #289, but at a lower level of tracing, recording and replay, e.g., using apitrace.

**Comment by kvark** [comment]
This is mostly done now in the API, just waiting for gfx-hal-0.6, so that we can enable the impl paths and close this.

**Comment by kvark** [comment]
I totally forgot about this one. We should still do it and release a patch version.

**Comment by grovesNL** [comment]
Clients like wgpu-rs are able to use debug labels now, so I think this is complete
