### ISSUE TITLE
"capture" example panics in Chrome, calls `unwrap()` on `ChannelSendError`

### ISSUE THREAD

**Issue by dcki** [gfx-rs/wgpu#4041]
**Description**

When I try to run the "capture" example in Chrome it panics at `buffer_slice.map_async(wgpu::MapMode::Read, move |v| sender.send(v).unwrap())`. `unwrap()` is called on `ChannelSendError(Ok(()))`.

Is the "capture" example intended to run in a web browser, or only natively? If it is not intended to run in a web browser, maybe the readme should say so.

**Repro steps**

```
rustup target add wasm32-unknown-unknown
cargo install wasm-bindgen-cli
git clone https://github.com/gfx-rs/wgpu
cd wgpu
git checkout v0.17.0
cargo build --bin capture --target wasm32-unknown-unknown
wasm-bindgen --out-dir generated --web target/wasm32-unknown-unknown/debug/capture.wasm
echo '<!doctype html>' > generated/index.html && echo '<html><body><script type="module">import init from "./capture.js"; init();</script></body></html>' >> generated/index.html
cd generated
python3 -m http.server
# View localhost:8000 and javascript console in Chrome
```

**Expected vs observed behavior**

Expected:

If I understand correctly this example is supposed to create a file named red.png somewhere. (When running the example natively, `wgpu/red.png` is created.)

Observed:

In the JavaScript console there is an error:

```
panicked at 'called `Result::unwrap()` on an `Err` value: ChannelSendError(Ok(()))', examples/capture/src/main.rs:141:73
```

**Extra materials**

None.

**Platform**

`git checkout v0.17.0` is used to checkout that commit before running `cargo build` etc.

Chrome Version 115.0.5790.170 (Official Build) (x86_64)

```
$ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.65.0 (897e37553 2022-11-02)`
$ cargo --version
cargo 1.65.0 (4bc8f24d3 2022-10-20)
$ wasm-bindgen --version
wasm-bindgen 0.2.87
```

**Comment by teoxoy** [comment]
Fixed by https://github.com/gfx-rs/wgpu/pull/4043.
