### ISSUE TITLE
Using simpler set bindgroup function call on web improves performance

### ISSUE THREAD

**Issue by mikialex** [gfx-rs/wgpu#4047]
First, thanks for creating this great library.

We observed a strange performance issue when using wgpu's webgpu backend directly on the web.

The performance test is roughly drawing 10000 cubes using 10000 drawcall. Each one using a unique bindgroup. From the browser's devtools profiler, we see the setBindgroup is the biggest cost(23% on Chrome, and even more on Firefox). We haven't seen this on the native side.

After some investigation, we found that at least on Firefox, the browser will do expensive checks on third
parameter. This code is from firefox:

<img width="629" alt="code" src="https://github.com/gfx-rs/wgpu/assets/13088597/0311a0b1-5420-4efd-948f-e9365cd0b285">

If we directly use the https://docs.rs/web-sys/latest/web_sys/struct.GpuRenderPassEncoder.html#method.set_bind_group instead of using https://docs.rs/web-sys/latest/web_sys/struct.GpuRenderPassEncoder.html#method.set_bind_group_with_u32_array_and_f64_and_dynamic_offsets_data_length , the setbindgroup cost on chrome reduced to 15% and the issue totally fixed on firefox.

I suggest using simpler calls on the web if the dynamic offset feature is not actively used. The setBindgroup is the hottest path in rendering. Even if the browser fixed this performance issue in the future, pass fewer parameters across the wasm js boundary is good for performance.

We tested on chrome 115, firefox nightly 2023-08-10, using wgpu 0.17

**Comment by cwfitzgerald** [comment]
We'd gladly accept a PR for this, nice bit of research.
