### ISSUE TITLE
Create Texture from Canvas data on Webgpu backend

### ISSUE THREAD

**Issue by AlienSmith** [gfx-rs/wgpu#4050]
On web we are using canvas to load image data, then we need to get it back on CPU to create Texture Object. This process could be expensive considering all the mapping and possibly staging. It would be really nice if we could use the copyExternalImageToTexture() function provided by webgpu to directly copy canvas data.  
Otherwise, Can we just enable Texture:as_hal for wasm32? Then maybe we can use import_external_texture() provided by web_sys to solve this problem.

**Comment by cwfitzgerald** [comment]
copy_external_texture_to_texture is already implemented on both the webgpu and webgl backends! It's just not visible in the docs as by default the docs arent showing wasm.

**Comment by AlienSmith** [comment]
Thanks :D

**Comment by stephenmartindale** [comment]
To spare other readers of this issue some minor amount of head-scratching: the salient method is not `copy_external_texture_to_texture` but rather `wgpu::Queue::copy_external_image_to_texture(..)`:

```rs
#[cfg(all(target_arch = "wasm32", not(target_os = "emscripten")))]
pub fn copy_external_image_to_texture(&self, source: &wgt::ImageCopyExternalImage,
                                             dest: ImageCopyTextureTagged,
                                             size: Extent3d) { .. }
```
