### ISSUE TITLE
the DX12 backend only partially renders on windows 10

### ISSUE THREAD

**Issue by bananaturtlesandwich** [gfx-rs/wgpu#4088]
**Description**
on launch with the DX12 backend, only a part of the window is rendered

![](https://github.com/gfx-rs/wgpu/assets/71292624/8c5471e2-40c5-4e7f-a112-7e284a62964a)

**Repro steps**
- clone and run [this branch](https://github.com/bananaturtlesandwich/stove/tree/dx12)
- the only difference between it and main is [this commit](https://github.com/bananaturtlesandwich/stove/commit/f98061cadddd01fe3b230bb50b11f9d0ea226b30) which removes the vulkan backend

**Platform**
I am using windows 10 using wgpu from the egui-wgpu re-export which I believe uses version ^0.16 of wgpu

**Comment by bananaturtlesandwich** [comment]
if the manifest isn't compiled by winres in build.rs then the whole window is rendered but the scale factor and input is screwed
![](https://github.com/gfx-rs/wgpu/assets/71292624/d9d0f38b-7e55-4795-a98c-c60f124d64d6)

**Comment by teoxoy** [comment]
I don't think you need the manifest file as winit takes care of setting those dpi parameters. As for the scale not being right, you don't seem to listen to `WindowEvent::ScaleFactorChanged` (while the [egui_winit crate does](https://github.com/emilk/egui/blob/ea15987ad4f8da2e3deb61f2b75480e314b34b12/crates/egui-winit/src/lib.rs#L199)).

**Comment by bananaturtlesandwich** [comment]
> I don't think you need the manifest file as winit takes care of setting those dpi parameters. As for the scale not being right, you don't seem to listen to `WindowEvent::ScaleFactorChanged` (while the [egui_winit crate does](https://github.com/emilk/egui/blob/ea15987ad4f8da2e3deb61f2b75480e314b34b12/crates/egui-winit/src/lib.rs#L199)).

I call egui_winit::on_event which does handle this event [here](https://github.com/bananaturtlesandwich/stove/blob/dx12/src/main.rs#L87)

**Comment by bananaturtlesandwich** [comment]
This app runs perfectly with the vulkan backend, I was just curious about dx12

**Comment by gabereiser** [comment]
`WindowEvent::ScaleFactorChanged` fires after the `WindowEvent::Resize` resize on DX12 and you set the old scaling on line 159 instead of the value from ScaleFactorChanged.

**Comment by bananaturtlesandwich** [comment]
pushed to branch adding a refresh on resize but it's still the same

**Comment by gabereiser** [comment]
add a stdout log in your resize handler for `factor` and see what it says...

**Comment by bananaturtlesandwich** [comment]
![image](https://github.com/gfx-rs/wgpu/assets/71292624/0ab6cadd-3815-4d14-88b9-069c32f28c84)
scalefactorchanged is never called

**Comment by bananaturtlesandwich** [comment]
> if the manifest isn't compiled by winres in build.rs then the whole window is rendered but the scale factor and input is screwed

removing the manifest gives 1.75 scale factor and calls scale factor change but the window still looks the same
![image](https://github.com/gfx-rs/wgpu/assets/71292624/cb5730c2-6b0b-41ac-899b-7063c7ff39ba)

**Comment by cwfitzgerald** [comment]
I very strongly suspect this isn't our problem and it's a problem with some logic elsewhere - considering we have no idea about scale factor. If it is found to be a problem with us, please ask for this to be re-opened. 

Does egui's examples with egui_wgpu work correctly?
