### ISSUE TITLE
Examples which exclude lavapipe wrongly exclude other drivers with mesa vendor id

### ISSUE THREAD

**Issue by i509VCB** [gfx-rs/wgpu#4097]
**Description**
Examples and tests which exclude lavapipe use the vendor id to identify the device. Community drivers in Mesa use the same vendor id. To be more precise, any case where lavapipe is excluded should also consider the adapter name.

**Repro steps**
Well... I'm not going to encourage you to run Vulkan drivers (agxv) which are still in development.

**Expected vs observed behavior**
Tests and examples which skip/explicitly fail when using lavapipe should not cause other drivers with the mesa vendor id to fail

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/blob/625afc3b4299c92c79e0b3881e22a0bb780678ed/examples/hello-compute/src/main.rs#L59

This is the only place I found where we only check for mesa's vendor id. Are there other instances?
