### ISSUE TITLE
Cargo failing to load git submodule

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/wgpu#41]
It looks like cargo doesn't support recursively loading git submodules in dependencies.

It works fine when one checks out the entire crate locally and depends on that directly, but if I point my crate's dependency at this git repository, I get the following:
```
$ cargo build
    Updating git repository `https://github.com/gfx-rs/wgpu`
error: failed to load source for a dependency on `wgpu`

Caused by:
  Unable to update https://github.com/gfx-rs/wgpu

Caused by:
  failed to update submodule `examples/vendor/glfw`

Caused by:
  no URL configured for submodule 'examples/vendor/glfw'; class=Submodule (17)
```

**Comment by grovesNL** [comment]
Thanks for reporting the issue. The git submodule was temporary and it wasn't supposed to have been added to `master`. It should be resolved with #42 which removes it again.
