### ISSUE TITLE
Vsync + minimal frame buffering

### ISSUE THREAD

**Issue by Remmirad** [gfx-rs/wgpu#4100]
**Is your feature request related to a problem? Please describe.**

To enable Vsync one can use the `PresentMode`s `Fifo` or `FifoRelaxed` which both buffer roughly 3 frames. This causes some input lag that Id like to avoid while still having vsync active and a framerate limitation to the displays refreshrate (blocking `get_current_texture`). `Mailbox` protects against tearing and reduces frame buffering but seems to miss the framerate limitation? 

**Describe the solution you'd like**

A `PresentMode` that buffers only one frame like `Mailbox` but limits framerate to the display refreshrate like e.g. `Fifo` does. Also this could be included in `AutoVsync` as the first option?

**Describe alternatives you've considered**

Maybe the queue length of e.g. `Fifo` could be customizable?
This can also be done with a manual framerate limiter and `Mailbox` so if a new/changed mode is not worth the effort this still can be achieved manually but it would be nice to have it built in.

**Additional context**

**Comment by cwfitzgerald** [comment]
I think this use case will be fully covered by the apis under #2869 - though the ability to limit frame buffer varies.
