### ISSUE TITLE
Forced GPU selection prevents wgpu running on hybrid nvidia laptops

### ISSUE THREAD

**Issue by flukejones** [gfx-rs/wgpu#4101]
The block at https://github.com/gfx-rs/wgpu/blob/625afc3b4299c92c79e0b3881e22a0bb780678ed/wgpu-hal/src/vulkan/instance.rs#L771 is an issue. On hybrid nvidia laptops it is preventing running wgpu based applications completely.

So what is happening for every Nvidia hybrid user is:
1. Intel GPU is blocked so it's impossible to select it
2. Nvidia will never work either due to https://github.com/NVIDIA/egl-wayland/issues/72
3. wgpu based apps just will not work (such as https://github.com/lapce/floem/issues/100 and all wgpu examples)

Given the above, this commit should be reverted, and be done before the next release of wgpu.

Related: https://github.com/gfx-rs/wgpu/issues/1215 (nvidia provides ways to force nvidia gpu selection)
Related: https://github.com/gfx-rs/wgpu/pull/1898 (the commit)

**Comment by teoxoy** [comment]
I think we should apply the workaround conditionally on the mesa version.

**Comment by flukejones** [comment]
@teoxoy mesa version of?

This block also prevents the use of Nvidia GL btw.

**Comment by teoxoy** [comment]
The "block" was added to work around a bug in mesa. We should find the version of mesa in which it was fixed and conditionally apply the workaround on it.

> This block also prevents the use of Nvidia GL btw.

That is most likely a different issue. This workaround is only present in our Vulkan backend.

**Comment by flukejones** [comment]
Mesa for what though, intel? I'm using `mesa-vulkan-drivers-23.2.0~rc2-3.fc40.x86_64`. And the previous version also works fine.

To be as clear as I can, current wgpu will never work on hybrid with that block due to https://github.com/NVIDIA/egl-wayland/issues/72

**Comment by teoxoy** [comment]
> Mesa for what though, intel? I'm using `mesa-vulkan-drivers-23.2.0~rc2-3.fc40.x86_64`. And the previous version also works fine.

The [fix](https://gitlab.freedesktop.org/mesa/mesa/-/commit/6b61fbca8bcade59576fd9c5291533d1390907b3) upstream got released as part of mesa 21.2. 

> To be as clear as I can, current wgpu will never work on hybrid with that block due to [NVIDIA/egl-wayland#72](https://github.com/NVIDIA/egl-wayland/issues/72)

Right now it works on x11, but not on Wayland.

Would you be interested in contributing the fix?

**Comment by flukejones** [comment]
> Would you be interested in contributing the fix?

Sure I don't mind.
