### ISSUE TITLE
vkCmdFillBuffer on NVidia overwrites full buffer

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4122]
When we issue a vkCmdFillBuffer for the tail end of a buffer, nvidia will overwrite the entire buffer.

I suspect the best way to work around this is that in the wgpu-hal vulkan backend, make all buffers 4 bytes longer than they need to be. This means that all the fill buffers will issue will only be for part of the buffer. Because of robust buffer access and that wgpu-core doesn't know about this length, all the other code will work okay. We do use vk::WHOLE_SIZE in a few places and those places will have to be removed in exchange for specifying an explicit size.

https://forums.developer.nvidia.com/t/vkcmdfillbuffer-bugged-on-ada/262483

**Comment by cwfitzgerald** [comment]
After much fluff, the bug is actually completely unrelated to the size of the buffer.

As far as I can tell the following is the bug precondition:

```rust
let succeeds = 'b: {
    if copy_length >= 4096 {
        if start_offset % 16 != 0 {
            if copy_length == 4096 {
                break 'b true;
            }
            if copy_length % 16 == 0 {
                break 'b false;
            }
        }
    }
    true
};
```

if succeeds returns false, the clear window will be "slid" down until the offset if a multiple of 16

**Comment by nical** [comment]
For future reference in case we try to narrow down the driver versions for the workaround, this was reproduced (at least on):
- RTX4080, driver 31.0.15.2802
- 1080TI, driver 537.13

**Comment by cwfitzgerald** [comment]
Do note that as we don't know when it started and likely never will, we will only be able to have an upper bound on where the workaround is applied.
