### ISSUE TITLE
Possible VK memory leak on Linux-X11-x86_64

### ISSUE THREAD

**Issue by jakubgiesler** [gfx-rs/wgpu#4125]
There is a possible memory leak in the VK backend under Linux-X11-x86_64 in wgpu_hal::vulkan::adapter::<impl wgpu_hal::Adapter<wgpu_hal::vulkan::Api> for wgpu_hal::vulkan::Adapter>::surface_capabilities (adapter.rs:1547) 
 
It could be just a junk data made by Valgrind.
Also it could just be optimization thing where it's cheaper to "leak" memory to reuse it later to avoid unnecessary allocations.

**Comment by teoxoy** [comment]
Line 1547 currently points at:
https://github.com/gfx-rs/wgpu/blob/caad255737fc68c53ac1108b69acc2de27b3851d/wgpu-hal/src/vulkan/adapter.rs#L1547

What is the version/commit you are using?

**Comment by cwfitzgerald** [comment]
I just ran multiple of our tests under valgrind and didn't see anything - could you add a reproduction case/more stacks?

**Comment by cwfitzgerald** [comment]
Closing until further data is provided - if you do, i"ll happily reopen :)
