### ISSUE TITLE
`POLYGON_MODE_LINE` should be a downlevel feature, not a feature

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#4131]
It's required as part of the WebGPU spec by now, see https://www.w3.org/TR/webgpu/#enumdef-gpuprimitivetopology

But it's currently still advertised as regular feature https://docs.rs/wgpu/latest/wgpu/struct.Features.html#associatedconstant.POLYGON_MODE_LINE

**Comment by teoxoy** [comment]
Polygon mode is not part of the spec, it's always fill (the first link leads to `GPUPrimitiveTopology`).

**Comment by Wumpf** [comment]
ohh I see, missunderstood then 😳 . Thanks for clearing it up
