### ISSUE TITLE
Publish binaries via github releases?

### ISSUE THREAD

**Issue by Korijn** [gfx-rs/wgpu#414]
Have you considered publishing the binaries you are building on Travis [as Github releases](https://docs.travis-ci.com/user/deployment/releases/) for tagged commits?

Are they perhaps available somewhere else?

I'd love to open a PR for your `.travis.yml`, but I'll need to know more about your release cycle in order to correctly implement the publishing logic.

/cc @almarklein

**Comment by kvark** [comment]
@Korijn thank you for reaching out!

We have this release pipeline set up for [gfx-portability](https://github.com/gfx-rs/portability). Unlike the portability stuff though, the WebGPU API is changing, so the library is by no means a drop in solution to anything. However, I can see how some users may be using the binaries together with the headers, and having releases makes sense.

So to sum it up, I believe having binary packaged releases (as you suggest) would be good.

FWIW, the publishing logic shouldn't care about the release cycle. It should just detect if there is a release and do the thing.

**Comment by Korijn** [comment]
Great, I'll get on it.

> FWIW, the publishing logic shouldn't care about the release cycle. It should just detect if there is a release and do the thing.

Well, that's kind of what I tried to say with "release cycle". How should CI detect if there is a release? Do you push a tagged commit, or a branch with a `release/` prefix, or is every commit on master a release?

**Comment by grovesNL** [comment]
In gfx-portability, we just attach a tag whenever we want to make a new release, then Travis CI attaches binaries to the associated GitHub release. I think we could probably use the same strategy for wgpu.

**Comment by Korijn** [comment]
Okay. Thanks for elaborating on that point. I'll set it up!
