### ISSUE TITLE
Add an `xtask test`

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#4144]
**Is your feature request related to a problem? Please describe.**
It's hard to remember how to run thorough local tests (or even builds) when working on changes that are platform-dependent. CI can do it but CI is slower and requires more steps.

**Describe the solution you'd like**
Add a `test` subcommand to the `xtask` that will run all, or a requested subset of, native and wasm tests, with features such as `webgl` both enabled and disabled.

**Comment by cwfitzgerald** [comment]
#3873 includes an xtask for running tests.
