### ISSUE TITLE
XlibHandle is usize, not u64

### ISSUE THREAD

**Issue by MarkSwanson** [gfx-rs/wgpu#415]
On an arm v7l raspberry pi 4 device:

~/src/rust/wgpu $ cargo build
   Compiling wgpu-native v0.4.0 (/home/pi/src/rust/wgpu/wgpu-native)
error[E0308]: mismatched types
  --> wgpu-native/src/device.rs:85:9
   |
85 |         window,
   |         ^^^^^^ expected u32, found u64
   |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
   |
85 |         window: window.try_into().unwrap(),

The bug seems to be that XlibHandle is defined to use a c_ulong, which works like the Rust usize type.
The existing wgpu code:
pub extern "C" fn wgpu_create_surface_from_xlib(
    display: *mut *const std::ffi::c_void,
    window: u64,
) -> id::SurfaceId {...}

should be changed to:

pub extern "C" fn wgpu_create_surface_from_xlib(
    display: *mut *const std::ffi::c_void,
    window: usize,
) -> id::SurfaceId

I know the raspberry pi doesn't support Vulkan yet.
The Rock pi is an arm device that has Vulkan support today.
The Jetson nano (Arm) also has Vulkan support today too.

**Comment by kvark** [comment]
Thank you for report! Would you want to make a PR?

**Comment by MarkSwanson** [comment]
I attempted to do this, and the evidence pointed me towards modifying raw-window-handle instead:
https://github.com/rust-windowing/raw-window-handle/issues/46

**Comment by Osspial** [comment]
Looking at [`x11_dl`](https://docs.rs/x11-dl/2.18.4/i686-unknown-linux-gnu/x11_dl/xlib/type.Window.html) and the [xlib headers](https://code.woboq.org/qt5/include/X11/X.h.html#Window), it seems that X11's Window is defined as `c_ulong`, not `usize`. Redefining `XlibHandle` to `c_ulong` should fix the compile errors.

**Comment by MarkSwanson** [comment]
Yeah, that worked.

**Comment by Lokathor** [comment]
I think I just hit this exact same bug on my rpi4 when I was checking to see if wgpu works on it yet or not.

```
   Compiling wgpu-native v0.4.0 (https://github.com/gfx-rs/wgpu?rev=b51053dc2dc3bbe9b2ba050fde42eeb6405fe092#b51053dc)
error[E0308]: mismatched types
  --> /home/pi/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/b51053d/wgpu-native/src/device.rs:85:9
   |
85 |         window,
   |         ^^^^^^ expected `u32`, found `u64`
   |
help: you can convert an `u64` to `u32` and panic if the converted value wouldn't fit
   |
85 |         window: window.try_into().unwrap(),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by kvark** [comment]
@MarkSwanson could you make it a PR, please?

**Comment by MarkSwanson** [comment]
Will submit a PR later today. Testing on a Jetson Nano atm...

**Comment by MarkSwanson** [comment]
Done: https://github.com/gfx-rs/wgpu/pull/430

**Comment by GabrielMajeri** [comment]
PR #430 was merged, is this issue still on?
