### ISSUE TITLE
cargo xtask - no such subcommand: `xtask` 

### ISSUE THREAD

**Issue by neilsarkar** [gfx-rs/wgpu#4158]
**Description**
On trunk, `cargo xtask` is not found, but it is referenced in multiple places including https://github.com/gfx-rs/wgpu/wiki/Running-on-the-Web-with-WebGPU-and-WebGL

**Repro steps**

```bash
git clone https://github.com/gfx-rs/wgpu.git
cd wgpu
cargo xtask run-wasm --bin cube
```

**Expected vs observed behavior**

Expected to build and see the cube example running in browser. Instead got this:

```bash
$ cargo xtask run-wasm --bin cube
error: no such subcommand: `xtask`

	Did you mean `apk`?

	View all installed commands with `cargo --list`
```

**Extra materials**

It appears that the `.cargo/config.toml` that supports xtask was removed here: https://github.com/gfx-rs/wgpu/pull/4107

For beginners, the missing `.cargo/config.toml` can be hard to debug, especially since the project doesn't use the workspace setup suggested by  https://github.com/matklad/cargo-xtask

Was this intentional? If so I can raise a separate issue about updating the documentation to reflect the removal of the xtask alias.

**Platform**

```
rustc 1.65.0 (897e37553 2022-11-02)
Mac OS Ventura 13.5.2
```

**Comment by cwfitzgerald** [comment]
That absolutely doesn't seem intentional. cc @OptimisticPeach 

We'd absolutely accept a PR to re-add it.

**Comment by neilsarkar** [comment]
thanks! submitted a pr reversing that deletion ^

**Comment by OptimisticPeach** [comment]
Oops, yup, I 100% didn't intend on deleting that -- I was using `.cargo/config.toml` to temporarily let CLion know that I'm compiling with WASM as the target, so removing that was part of my cleanup however apparently I forgot to notice that there were extra things in that file, other than the config I was adding 😅.
