### ISSUE TITLE
Examples crash when resizing on x11+vulkan (known commit)

### ISSUE THREAD

**Issue by Azorlogh** [gfx-rs/wgpu#4180]
**Description**
Running the `cube` example, my window manager (on x11) hangs when resizing the window.
I have pinpointed the bug to the following commit: https://github.com/gfx-rs/wgpu/commit/1d0a22b1a8f38d9c9fe3418c543ee2bfaa046cb2

**Repro steps**
- Linux w/ X11
- Run the `cube` example
- Resize the window

**Expected vs observed behavior**
Expected: should resize and run smoothly
Observed: My WM hangs for ~5 seconds. Then it becomes responsive again, but the window has not been redrawn. Attempting to resize again at this point will *not* make the WM hang a second time, but the window never gets redrawn again.

**Extra materials**
Trace:
[wgpu_resize_bug_trace.zip](https://github.com/gfx-rs/wgpu/files/12744032/wgpu_resize_bug_trace.zip)

**Platform**
Archlinux, X11, no compositor
WGPU version: Any commit since https://github.com/gfx-rs/wgpu/commit/1d0a22b1a8f38d9c9fe3418c543ee2bfaa046cb2
Adapter: NVIDIA GeForce RTX 2060 (Vulkan)

**Comment by coderedart** [comment]
I am using 0.17.1 and i have the same problem. If i switch to plasma wayland session and launch my app and resize it, everything works fine.

But if i log in to plasma x11 session, then the app hangs the entire system for a few seconds if i resize it. After that, it just stops rendering and stays hanged (according to my logfile), and i had to use ctrl + C to stop the app smh.

**Comment by cwfitzgerald** [comment]
There's a fix up, I'll try to land it tonight, sorry for the problem. To work around the issue, run `cargo update -p wgpu-hal --precise 0.17.0` until I can patch it.

**Comment by cwfitzgerald** [comment]
Published in v0.17.2
