### ISSUE TITLE
`wgpu-info` output is too verbose by default

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#4208]
The output from `wgpu-info` could be helpful in all sorts of diagnostic situations, but the default output is more than 1000 lines long on my system. The more verbose sections should be printed only on request only - especially "Texture Format Allowed Usages" and `Texture Format Flags".

**Comment by teoxoy** [comment]
We can most likely remove those sections altogether if the format extensions land in the spec.

**Comment by cwfitzgerald** [comment]
I'm not sure what you mean by this? Logging? Is https://github.com/gfx-rs/wgpu/issues/3206 related?

**Comment by teoxoy** [comment]
I thought it's about `wgpu-info`. @jimblandy can you confirm?

**Comment by John-Nagle** [comment]
There's too much stuff at "info" level from WGPU and Rend3. Debugging/trace info is fine, but if things are going well, please try to avoid anything at "info" level or higher per-frame. Otherwise, the log fills up with far too much per-frame info. Thanks.

**Comment by jimblandy** [comment]
Sorry, I had been saying `wgpu-core` when I meant `wgpu-info`. Comments and title are edited.

**Comment by ognis1205** [comment]
Hi there, I'm a newcomer here, but if it's okay, could you please assign this issue to me?

**Comment by cwfitzgerald** [comment]
We don't really do assignments, but if you want to tackle this, please just go ahead and make a PR!

**Comment by ognis1205** [comment]
@jimblandy 

I am going to add `--verbose` option (default is false, i.e., opt-in) and the following entries:

 - `Features`
 - `Limits`
 - `Downlevel Properties`
 - `Texture Format Allowed Usages`
 - `Texture Format Flags`

will be shorten (with ellipsis).

**Comment by cwfitzgerald** [comment]
I think we can have 3 different modes. The default just lists the adapter info. First verbose also does `features`, `limits`, and `downlevel-properties`. Second verbose does the texture format information.

**Comment by ognis1205** [comment]
@cwfitzgerald 
Thank you for elaborating!
