### ISSUE TITLE
Window not being cleared when running out of container

### ISSUE THREAD

**Issue by me-self** [gfx-rs/wgpu#4209]
**Description**
When running the examples in a container all goes as expected. When executing the same binary outside of the container the window is never cleared unless something forces it to be redrawn (such as passing another window above it)

**Repro steps**
`git clone https://github.com/gfx-rs/wgpu && cargo run --bin boids`

**Expected vs observed behavior**
I expect to get the same results whether I run it in a container, or out of container. When run outside of the container, the window is never cleared.

**Extra materials**
Screenshots cause the window to be redrawn, so this cannot properly be shown.

**Platform**
- OpenSUSE MicroOS
- wgpu 0.17.0
- rustup and the contents of the git repo are used. The container uses distrobox and runs OpenSUSE Tumbleweed.
- wayland with Nvidia RTX 3060 Mobile GPU

**Comment by cwfitzgerald** [comment]
I'm not really sure what could be causing this. Could you double check `wgpu-hal` is on 0.17.2. If that doesn't fix it, I honestly have no idea what could be going on or if it's our fault :(

**Comment by me-self** [comment]
It's on 0.17 in the cargo.toml, but if I remember right, the minor version should update, no?
I was thinking it might be an Nvidia & Wayland specific issue, but can't test because attempting to run with Xorg gives the following error: `thread 'main' panicked at 'No suitable GPU adapters found on the system!', /home/sandmuel/Documents/wgpu/examples/common/src/framework.rs:187:10`

**Comment by cwfitzgerald** [comment]
You can run `cargo update -p wgpu-hal` to make sure you're on latest.

**Comment by me-self** [comment]
Unfortunately still getting the same results.

**Comment by cwfitzgerald** [comment]
Really not sure then. I would look at `ash`'s examples as well.

**Comment by cwfitzgerald** [comment]
Closing as not currently actionable, please re-file if more information arises!
