### ISSUE TITLE
Device lost when using multi_draw_indexed_indirect and storage buffer binding array

### ISSUE THREAD

**Issue by mikialex** [gfx-rs/wgpu#4216]
I'm using multiple wgpu's native-only features for example multi-indirect draw to do some rendering experiments and get device lost errors. The situation is a little complicated but I think it's easy to understand.

I'm using three storage buffer binding arrays, each binding array to address the real vertex data like position, normal, and uv in the binding array by the index and offset, dynamically in the shader. The binding array is partially bound. 

The multi-indirect draw's drawcall buffer is prepared from the host side, using the base_instance field as the drawcall ID. In the shader, I use the drawcall ID to get the vertex metadata from a storage buffer that matches the drawcall buffer. The metadata contains position, normal, and uv's buffer index and offset. Then, I use the buffer index and offset to get real vertex data from the storage buffer binding array I mentioned above.

My test data and what I expect is a 5 * 5 cube array (25 cubes) on the ground, but I constantly get device lost error.

I'm using wgpu 0.17, windows10, vulkan backend, rtx3070 with latest nvidia driver. I also tested on the other rtx4090 machine but still have this issue.

The error is not always reproducible, If I reduce my cube array example's cube count to 2-4 cubes, It will display correctly. If I'm using nsight to launch my executable then 5x5 cube will likely display correctly. However, even if it not crash, it only display part of the cubes

<img width="876" alt="lost-cubes" src="https://github.com/gfx-rs/wgpu/assets/13088597/5381598e-b280-478a-b6a4-9e82b17aa7dc">

This is the 5x5 cube case wgpu trace I record.
[wgpu-trace.zip](https://github.com/gfx-rs/wgpu/files/12840002/wgpu-trace.zip)

**Comment by cwfitzgerald** [comment]
Are you indexing out-of-bounds for the binding arrays? We do not have anything preventing you from doing this, and you'll get proper undefined behavior. We want to implement bounds checks on this, we just haven't gotten around to it yet.

**Comment by mikialex** [comment]
By roughly checking my code logic again and again I still "believe" my code does not have out-of-bound access. I wish to see if we could get something check ability built in wgpu in debug build in the future.

Also, I switched my implementation from a storage buffer binding array to a big allocated storage buffer, and everything works fine now.

**Comment by cwfitzgerald** [comment]
Yeah we want to add this at some point. I'm going to close this issue as it's not really something actionable, but if you hit further issues, please do file.
