### ISSUE TITLE
Integrate Clippy

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#422]
Being a part of Gecko puts the code base under big pressure to be safe. We need to integrate clippy in our workflow in order to get there:
  - clear the current errors, possibly warnings as well
  - have it on CI preventing any issues

P.S. we'll likely need to do the same for gfx-rs repo.

**Comment by kvark** [comment]
> error: this public function dereferences a raw pointer but is not marked `unsafe`
   --> wgpu-core/src/device.rs:849:18
    |
849 |                 *mapped_ptr_out = ptr;

> error: this public function dereferences a raw pointer but is not marked `unsafe`
   --> wgpu-core/src/device.rs:854:22
    |
854 |                     *mapped_ptr_out = ptr::null_mut();

**Comment by yanchith** [comment]
I think I'll be able to do this in between jobs. Do we also want to deny clippy warnings in CI?

**Comment by kvark** [comment]
@yanchith Ideally, instead of blocking the merge it should post a comment to the PR saying that revision XXX produces the following warnings.
