### ISSUE TITLE
Startup time on mac

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#4225]
**Description**

Recording some discussions that happened on matrix, about the impact of wgpu's dependencie son deno's startup (an extra 3ms):

Some of deno's internal doc on the issue:

https://mozilla.modular.im/_matrix/media/v3/download/matrix.org/ZkSLZElgZEKFmpYxbEHCmaIJ

https://mozilla.modular.im/_matrix/media/v3/download/matrix.org/lNziwrvMBKKZUMfVvpOdltML

https://mozilla.modular.im/_matrix/media/v3/download/matrix.org/fyInrkSpOgQWccsLETrSgkwy

Deno managed to mitigate the issue by patching wgpu deps that statically link frameworks.

**Platform**

Mac

**Comment by teoxoy** [comment]
Hasn't this been fixed by https://github.com/gfx-rs/wgpu/pull/3853?
