### ISSUE TITLE
Support DP4A language extension

### ISSUE THREAD

**Issue by FL33TW00D** [gfx-rs/wgpu#4241]
Tracking implementation of DP4A which looks like it will land soon.
Related issues
- https://github.com/gpuweb/gpuweb/issues/2677
- https://github.com/gfx-rs/wgpu/issues/4544
Happy to implement this myself when it's implemented on Dawn/Tint.

**Comment by jimblandy** [comment]
Closed as dup of #4544 (Naga and wgpu issues got merged)
