### ISSUE TITLE
Compute example doesn't link on Windows Nightly

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#425]
Annoying [error on CI](https://travis-ci.org/gfx-rs/wgpu/jobs/629529031?utm_medium=notification&utm_source=github_status):
>(Link target) -> 
  wgpu_native.lib(wrapper.o) : fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0xA [C:\Users\travis\build\gfx-rs\wgpu\examples\compute\build\compute.vcxproj]

Currently blocking bors to merge anything :( We should find out what happens there and/or disable the build of *this particular example* on Windows Nightly.

**Comment by Korijn** [comment]
Compared to the last successful build on master, we can see the following difference:

```
$ rustc --version
rustc 1.41.0-nightly (99b89533d 2019-12-16)
$ rustup --version
rustup 1.20.2 (13979c968 2019-10-16)
$ cargo --version
cargo 1.41.0-nightly (626f0f40e 2019-12-03)

$ rustc --version
rustc 1.42.0-nightly (9ae6cedb8 2019-12-23)
$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
$ cargo --version
cargo 1.41.0-nightly (19a0de242 2019-12-12)
```

**Comment by LaylConway** [comment]
A quick skim of the log seems to indicate that wgpu_native.lib is being built actually using the GNU toolchain. It's installed with `nightly-x86_64-pc-windows-gnu`. This may currently on nightly be incompatible with MSVC.

**Comment by Korijn** [comment]
That's odd, I thought MSVC is the default toolchain on Windows. Must be Travis trying to make their Windows image as Linux-y as possible? Do you happen to know the rustup command sequence to install and activate the msvc toolchain?

**Comment by LaylConway** [comment]
I tend to use:
```
rustup default nightly-msvc
```
This should also work with `install`.

**Comment by Korijn** [comment]
That fixed it. See #426

**Comment by kvark** [comment]
Please cc me from that pr
