### ISSUE TITLE
No output, when "hello" example ran. Exit after few seconds

### ISSUE THREAD

**Issue by szpolny** [gfx-rs/wgpu#4257]
**Description**
No output, when "hello" example ran. Exit after few seconds

**Repro steps**
```bash
git clone https://github.com/gfx-rs/wgpu.git
cd wgpu/
cargo run --bin hello
```

**Expected vs observed behavior**
As far as i know i should get list of video adapters, but i get nothing and app is exiting after few seconds.

**Extra materials**
![image](https://github.com/gfx-rs/wgpu/assets/43553431/b5d6bace-c552-4871-9e85-3866a0d72e4f)

**Platform**
OS: Fedora Linux 38 (Workstation Edition) x86_64 
Kernel: 6.5.6-200.fc38.x86_64 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 

cargo 1.70.0 (ec8a8a0ca 2023-04-25)
wgpu: trunk branch, c07d889f commit

**Comment by cwfitzgerald** [comment]
This is because it's being sent to the logging infrastructure, which is hidden by default. if you do `RUST_LOG=info` you should see it. We should improve this.

**Comment by szpolny** [comment]
Thanks, but now there is wrong name of my graphic card and there is no info about my graphic driver.

```bash
[2023-10-17T21:17:33Z INFO  hello] Selected adapter: AdapterInfo { name: "NV136", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
```

**Comment by cwfitzgerald** [comment]
This looks like a name nouveau would give to your device. Do you have the proprietary drivers installed? Do [`ash`](https://github.com/ash-rs/ash)'s examples work?

**Comment by szpolny** [comment]
Vulkan was not installed, thank you.
