### ISSUE TITLE
buffer memory leak

### ISSUE THREAD

**Issue by wuyanzhiyan** [gfx-rs/wgpu#4274]
**Description**
The created buffer is not released, and the GPU memory usage does not decrease

**Repro steps**
```
let instance=::wgpu::Instance::new(
        ::wgpu::InstanceDescriptor{
            backends: ::wgpu::Backends::all(),
            ..Default::default()
        }
    );
    let adapter=instance.enumerate_adapters(::wgpu::Backends::all())
        .next().unwrap();
    let (device, queue) = pollster::block_on(adapter.request_device(
        &::wgpu::DeviceDescriptor {
            features: ::wgpu::Features::empty(),
            limits: if cfg!(target_arch = "wasm32") {
                ::wgpu::Limits::downlevel_webgl2_defaults()
            } else {
                ::wgpu::Limits::default()
            },
            label: None,
        },
        None,
    )).unwrap();
    for i in 0..20000{
        //buffer not release
        let buffer=device.create_buffer(
            &::wgpu::BufferDescriptor{
                label: Some("device_only_buffer"),
                size: 204800,
                usage: ::wgpu::BufferUsages::STORAGE|::wgpu::BufferUsages::COPY_DST|::wgpu::BufferUsages::COPY_SRC,
                mapped_at_creation: false,
            }
        );
        buffer.destroy();
    }
    loop {
        
    }
```
**Expected vs observed behavior**
While the loop is waiting, the GPU memory should drop。

**Platform**
windows11,  wgpu0.17.1

**Comment by cwfitzgerald** [comment]
If you insert a `device.poll(Poll)` in the loop does the problem go away?

**Comment by wuyanzhiyan** [comment]
> If you insert a `device.poll(Poll)` in the loop does the problem go away?

Thanks for the answer, using `device.poll(Poll)` does work. But do you need `device.poll(Poll)` on each `Buffer` drop to avoid GPU memory issues?Doesn't drop `Buffer` automatically free GPU memory?

**Comment by cwfitzgerald** [comment]
The fundamental problem is that we can't delete memory until the gpu is finished using it. When you drop a buffer, it gets put on a list of resources waiting for the gpu to be finished. Inside poll (or submit) we check the status of previous submissions, and delete all resources both the user and the gpu are finished with.
