### ISSUE TITLE
Support non-gfx backends

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#43]
At the end of the day, when WebGPU is standardized, and there is a solid test suite provided, we will consider adding direct mapping backends to GL and potentially Metal.

**Comment by kvark** [comment]
I believe the first step here is to split wgpu-native into the following parts:
  1. API structures and types that reflect WebGPU IDL
  2. actual entry points and type implementations (i.e. `struct Buffer<B: hal::Backend> { .. }`), possibly together with some registry bits.

**Comment by Michael-Lfx** [comment]
I am curious about the meaning of introducing gfx-hal to wgpu when it will map to GL or Metal backend directly.

**Comment by kvark** [comment]
The biggest gain from using gfx-hal is because it's a single backend that gets us everything. It's high quality and has great network effects within Rust ecosystem. Developing a GL or Metal backend from scratch is somewhat feasible (but still a ton of work) but doing it for Vulkan and D3D12 is less so.

**Comment by cwfitzgerald** [comment]
Is this still on the radar at all? I feel like, based on our discussions, it isn't.

**Comment by kvark** [comment]
I don't think we have the bandwidth even to just explore this, closing
