### ISSUE TITLE
Native translation to FXC binaries

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4300]
The FXC is not publicly specified, but there is some information about its structure:
http://timjones.io/blog/archive/2015/09/02/parsing-direct3d-shader-bytecode

It would be very nice to be able to generate it natively from SPIR-V. This would greatly improve the performance of (uncached) pipeline creation when working with API abstraction libraries that take SPIR-V input (https://github.com/gfx-rs/gfx/issues/1374). This in turn could give us an edge comparing to NXT and MoltenVK.

The downsides are:
  - difficult to debug
  - working without clear specification

**Comment by teoxoy** [comment]
I think this is out of scope at this point in time, unless someone makes a really good case for it.
