### ISSUE TITLE
SPIR-V back-end uses extra pass to write output

### ISSUE THREAD

**Issue by Timo-DK** [gfx-rs/wgpu#4303]
At the moment, the current SPIR-V back-end uses an exta pass, which results in increased and (probably) unnecessary memory.

After everything is parsed, it then rearranges all the data in the correct order for the Physical- and Logical Layout.

A better and proposed way of @kvark is just single passing it. This means stripping the phase of rearranging, and holding data in temporarily vectors, to just directly write it to the output string.

There will be some lightweight "scans" through the IR to look for example the Capabilities the SPIR-V output requires, but this shouldn't be a whole lot of iterations.

**Comment by cwfitzgerald** [comment]
I do not think they're is bandwidth to persue this, and without a clear perf/memory problem, I'm going to close this.
