### ISSUE TITLE
Consider using Gherkin for tests

### ISSUE THREAD

**Issue by pjoe** [gfx-rs/wgpu#4304]
Just wondering if it could make sense to use Gherkin for some tests.

https://cucumber.io/docs/gherkin/reference/

Maybe using tables and outlines could be useful:

https://github.com/b-yond-infinite-network/jest-cucumber-fusion/blob/master/docs/GherkinTables.md

https://github.com/b-yond-infinite-network/jest-cucumber-fusion/blob/master/docs/ScenarioOutlines.md

**Comment by cwfitzgerald** [comment]
I think our test infra is already complicated enough, I don't think this would benefit us.
