### ISSUE TITLE
[spv-in] Embark SPIRV shaders fail to parse with multiple errors

### ISSUE THREAD

**Issue by repi** [gfx-rs/wgpu#4308]
Did a quick test to take 20 of our GLSL -> SPIRV (compiled by shaderc) test shaders we have at Embark and just read them into a naga module with the SPIRV front-end with the latest `master` version of naga. 

Was a collection of vertex, fragment and (a few) compute shaders. 

Unfortunately all of them failed to parse the valid SPIRV, they failed on these set of errors:

- InvalidId(14)
- InvalidId(17)
- UnsupportedCapability
- UnsupportedCapability(MultiView)
- UnsupportedInstruction
- UnsupportedInstruction(Function, BitwiseAnd)
- UnsupportedStorageClass(9)

This was more of a first experiment to see if `naga` could handle our current fairly simple shaders, we are not reliant on this at this point but thought it would be good to report.

If there are any later additional improvements or fixes in `naga` with the SPIRV input parser, ping me here and I can re-run the tests. May be able to later also open source these shaders as we'll use them in the open [Rust GPU](https://shader.rs) project as well (convert them from GLSL to Rust, still output SPIRV).

**Comment by cwfitzgerald** [comment]
This is an out of date tracking issue, so I'm going to close it. Newer issues should cover any remaining issues.
