### ISSUE TITLE
How to raise precision in WGSL

### ISSUE THREAD

**Issue by baptistemanson** [gfx-rs/wgpu#4312]
Hi all,

I couldn't figure out how to raise the precision in WGSL.
It resulted in my shader in some division by zero, which gets very funky (doesnt crash):

```
[[stage(fragment)]]
fn main() {
    out_target = vec4<f32>( 1.0 / 0., 0.0 , 1.0);
}
```

**Comment by teoxoy** [comment]
Closing as outdated.
