### ISSUE TITLE
Uniform control flow inside a for loop

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu#4316]
Hey, so I just tried to see what happened if I switched my project over to the wgpu-rs master, and I'm getting this error:
```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `../shaders/compiled/scene_shader.frag.spv`
    Required uniformity of control flow for ImplicitLevel in [253] is not fulfilled because of Expression([239])
```
The compiled shader is pretty long, so I won't post the disassembly here, just run `spirv-dis` on https://github.com/expenses/dune_scene/blob/c21606dc9d20772864c71c66e12d047ab45f80cc/shaders/compiled/scene_shader.frag.spv if you want to.

I believe that this error is being caused by 
```
%1110 = OpImageSampleDrefImplicitLod %float %1096 %1108 %1049
```
which in the glsl code is happening here:
https://github.com/expenses/dune_scene/blob/c21606dc9d20772864c71c66e12d047ab45f80cc/shaders/includes/shadows.glsl#L40-L45
```rust
for (uint i = 0; i < ITERATONS; i++) {
    shadow_sum += texture(
        sampler2DArrayShadow(SHADOW_TEXTURE_ARRAY, SHADOW_SAMPLER),
        vec4(light_local + step * coords[i], cascade_index_f, comparison)
    );
}
```
Unfortunately, there just isn't a `textureLod` function for `sampler2DArrayShadow` in glsl:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/textureLod.xhtml
so that's not a solution.

**Comment by teoxoy** [comment]
Let's track this in https://github.com/gfx-rs/wgpu/issues/4369.
