### ISSUE TITLE
Handle atan2 where x == 0

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4319]
See https://github.com/gfx-rs/wgpu/issues/1277
Looks like MSL doesn't handle this, but we should.

**Comment by jimblandy** [comment]
We need to re-check what the WGSL spec requires now - it may have been changed to give us the leeway to do whatever the platform does, in which case no work is required here.

**Comment by ErichDonGubler** [comment]
@jimblandy: Yep, pretty sure that that's the case; screenshot of current spec. (visual emphasis mine):

<img width="807" alt="Screenshot 2024-02-01 at 10 41 47 AM" src="https://github.com/gfx-rs/wgpu/assets/658538/cad3c8d4-6036-4c98-8bc8-c533321c8fd4">
