### ISSUE TITLE
Ideas for uniformity analysis v5

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4320]
Following the discussion in gfx-rs/wgpu#4316, here are some ideas on how to make our analysis more complete. See gfx-rs/naga#564 for where we are currently.

When we scan the expressions, we used to determine if it's uniform pessimistically. We'd consider all locals, as well as private-class globals, to be non-uniform. This is blocking gfx-rs/wgpu#4316.
Instead, we could have the following context per expression:
  - one bit per function local. If the bit is set, the local has to be uniform in order for the expression to be uniform.
  - one bit per function argument (for non entry points)
  - one bit per private global, similarly

After we collect and accumulate this, we would also determine which of the locals and globals are *actually* uniform.

**Comment by teoxoy** [comment]
Let's track this in https://github.com/gfx-rs/wgpu/issues/4369.
