### ISSUE TITLE
Negative Positions Not Rendered Correctly

### ISSUE THREAD

**Issue by cab** [gfx-rs/wgpu#4332]
(I lack some of the knowledge to really understand what's going on here, so apologies in advance for any ambiguity).

This is using naga 0.4.0.

Example of the issue is here: https://github.com/cab/wgpu-example-01

When the position becomes negative [here](https://github.com/cab/wgpu-example-01/blob/main/src/shader.vert#L210), nothing is rendered, even if part of the rectangle is still on-screen.

Additional information:
* This works correctly if the `cross` feature in wgpu is used.
* Hard-coding the translation (e.g. `vec4(-10.0, 0.0, 0.0, 0.0)`) also works.
* This at least happens on ubuntu + vulkan. It does not seem to happen with ubuntu + chrome canary/webgpu.

**Comment by cwfitzgerald** [comment]
I'm going to close this, assuming that the problem has been fixed in the mean time. If it hasn't, please file a new issue!
