### ISSUE TITLE
imageStore in shaders doesn't seem to be properly synchronized

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu#434]
I am working on a application which writes to a storage image from one compute shader invocation via `imageStore(...)`  then tries to read it back the value in a second invocation. This works fine on one machine with an integrated Intel GPU, but fails (by reading back what seems to be garbage values) on a different machine with a discrete AMD GPU.

I believe that this may be caused by a missing pipeline barrier between the two shader invocations, but I couldn't find anything in the API that would let me hint that the barrier was required.

**Comment by kvark** [comment]
Today, WebGPU synchronization in a compute pass treats each `dispatch` as a separate synchronization scope. This means you should be getting the storage writes in the next dispatch automatically, you aren't expected to insert any barriers yourself.

What version are you using? What backend?

The problem you are describing sounds like #272, which was fixed a while ago in #281. I wonder if there is something about your case that the code doesn't handle, or maybe we just regressed. Sharing a repro case would help too!

**Comment by fintelia** [comment]
I'm on Ubuntu using the Vulkan backend with wgpu-rs version [8f083e5](https://github.com/gfx-rs/wgpu-rs/commit/8f083e54c57f7411c60b53fc8366be254bace093).

My code is on the _wgpu_ branch of https://github.com/fintelia/terra/tree/wgpu. It should be runnable (`cargo run --release` from the repository root) but on the first run needs to download ~5GB of content to ~/.cache/terra and then spend ~5 minutes processing it. The bug manifests as a blurry circle on the ground where the high resolution normal maps produced by the compute shader turn out to contain only constant values.

If I have a chance I'll make a more minimal reproduction case.

**Comment by fintelia** [comment]
Update: This turned out to be a bug in my code, not in wgpu. I was passing creating the relevant BindGroupLayoutBindings with SampledTexture instead of StorageTexture. A little annoying that this didn't trigger any error, but that's probably just because I don't have the necessary validation layers configured.

**Comment by kvark** [comment]
@fintelia could you provide more details? you were using a `SampledTexture` binding and didn't get the results of the previous `Storage` use of the same texture?

**Comment by fintelia** [comment]
I fixed things in [this patch](https://github.com/fintelia/terra/commit/d38defbc3179406d45554d19e40c0b6314950a3d).

The bug was that my [Rust code](https://github.com/fintelia/terra/blob/46539fe9b2adf7e087ee209e9e10c32aee24b986/src/generate/gpu.rs#L58) claimed the binding=2 was a SampledTexture while my GLSL code declared it as an [image2D uniform](https://github.com/fintelia/terra/blob/46539fe9b2adf7e087ee209e9e10c32aee24b986/src/shaders/gen-heights.comp#L12) which means it was expecting a storage texture bound to that slot. The issue wasn't immediately apparent because the GPU/driver actually let me do imageLoad and imageStore operations with things improperly configured.

**Comment by kvark** [comment]
I see, thanks! This would be #269 then.
