### ISSUE TITLE
[spv-in] Spirv Shader with Uniform Sampling/TextureGrad Fails Uniformity Analysis

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4359]
A shader which passed validation in 0.6.3 fails to validate in naga master due to:

```
Function [1] 'main' is invalid:
        Required uniformity of control flow for IMPLICIT_LEVEL in [419] is not fulfilled because of Expression([390])
```

This shader uses either textureGrad or sampling inside of uniform control flow. and shouldn't fail.

[opaque.frag.cpu.zip](https://github.com/gfx-rs/naga/files/7157594/opaque.frag.cpu.zip)

---

This was found because I found a hlsl compile error in naga 0.6.3 that I wondered might be fixed by the new spirv control flow stuff. If you compile this shader to hlsl with 0.6.3, it'll try to use a inside-scope variable outside of that scope, causing a compile error.

**Comment by teoxoy** [comment]
Let's track this in https://github.com/gfx-rs/wgpu/issues/4369.
