### ISSUE TITLE
GLSL/HLSL out pass through the modulus operator on integers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4398]
"a % b" expression gets passed through form WGSL to GLSL, e.g.
```rust
@vertex
fn main() -> @builtin(position) vec4<f32> {
	let x: i32 = -4 % 5;
	return vec4<f32>(0.0);
}
```
Produces:
```cpp
#version 310 es

precision highp float;
precision highp int;


void main() {
    int x = (-4 % 5);
    gl_Position = vec4(0.0);
    gl_Position.yz = vec2(-gl_Position.y, gl_Position.z * 2.0 - gl_Position.w);
    return;
}
```

Problem is - the semantics of "%" is different. In GLSL it's "x - y * floor(x/y)", while in WGSL it's meant to be "x - y * trunc(x/y)".

Edit: same for HLSL, with a little difference that this is UB:
> The % operator is defined only in cases where either both sides are positive or both sides are negative.

**Comment by teoxoy** [comment]
This has been resolved by: c584331f3931a529f83082c927c993dddb2da4a8 (https://github.com/gfx-rs/naga/pull/1867) & 943235cd5e91df9a1d41c60f525d26734bc0d261 (https://github.com/gfx-rs/naga/pull/1452).
