### ISSUE TITLE
Make validation truly optional

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4409]
Currently, even with empty validation flags, the validator complains about things that aren't required to produce the module info. For example, it requires the `@group` and `@binding` to be present, unconditionally, on resources. This doesn't affect construction of `ModuleInfo` and should be gated behind a flag. Moreover, documentation of `--validation` option in naga-cli says:
>   --validate        bitmask of the ValidationFlags to be used, use 0 to disable validation

**Comment by teoxoy** [comment]
Has been addressed by https://github.com/gfx-rs/naga/pull/2156.
