### ISSUE TITLE
Spurious validation error due to discard statement

### ISSUE THREAD

**Issue by sconybeare** [gfx-rs/wgpu#4416]
Consider the following shader excerpt:
```
fn shade_disc(tex_coords: vec2<f32>, color: vec4<f32>) -> vec4<f32> {
   let r = tex_coords * 2.0 - 1.0;
    if length(r) > 1.0 {
        discard;
        return color;
    } else {
        return color;
    }
}
```
It fails validation, apparently because Naga is treating the `discard` statement as diverging:
```
$ naga shader.wgsl
error:
  ┌─ shader.wgsl:1:1
  │
1 │ ╭ fn shade_disc(tex_coords: vec2<f32>, color: vec4<f32>) -> vec4<f32> {
2 │ │     let r = tex_coords * 2.0 - 1.0;
3 │ │     if length(r) > 1.0 {
4 │ │         discard;
5 │ │         return vec4(0.0);
  │ │                ^^^^^^^^^ instructions after return
6 │ │     } else {
7 │ │         return color;
  │ ╰─────────────────────^ naga::Function [1]

Function [1] 'shade_disc' is invalid:
        There are instructions after `return`/`break`/`continue`
```
This is inconsistent with the current [webgpu spec](https://gpuweb.github.io/gpuweb/wgsl/#behaviors-rules), which describes the `discard` statement as having `{Next}` behavior.

This is especially awkward when using the D3D12 backend with wgpu, since in that case, removing the `return vec4(0.0);` line causes a D3D compile error of the form `error X3507: 'fs_main': Not all control paths return a value`. AFAICT this is because `discard` statements have the same semantics in HLSL as in the webgpu spec.

**Comment by teoxoy** [comment]
Let's track this in https://github.com/gfx-rs/wgpu/issues/4369.
