### ISSUE TITLE
Make `SPV_KHR_storage_buffer_storage_class` optional

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#4427]
The `SPV_KHR_storage_buffer_storage_class` extension requires the `VK_KHR_storage_buffer_storage_class` extension which might not be supported. We can instead conditionally translate storage buffers to `Uniform` address space and decorate them with `BufferBlock`.

wgpu issue: https://github.com/gfx-rs/wgpu/issues/3348

**Comment by jimblandy** [comment]
Since the Naga issues and WGPU issues were merged, this is now really just a duplicate of #3348. Let's track further work there.
