### ISSUE TITLE
Fine-grained locking

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#444]
For most objects locking the whole storage is OK because it's mostly locked for reading. There is a few objects that are different in a way that they are always mutable: command buffers and passes. It would be much more efficient if we could allow them to lock multiple different elements at the same time, i.e. the locking should be more granular than the whole storage.

I imagine we'd get there by introducing a different storage type used for those mutable objects. I'm sure Rust ecosystem already has necessary primitives for us to use.

**Comment by cwfitzgerald** [comment]
Superseded by #2710
