### ISSUE TITLE
Naga wgsl->spv fails on tint-translated piet-gpu kernel4

### ISSUE THREAD

**Issue by raphlinus** [gfx-rs/wgpu#4440]
I used tint to translate [kernel4.spv](https://github.com/linebender/piet-gpu/blob/master/piet-gpu/shader/kernel4.spv) into wgsl, translated file attached. (note: I had to remove the "restrict" qualifiers for tint to succeed)

```
error:
     ┌─ kernel4.wgsl:643:2
     │
 643 │     }
     │ ╭───^
 644 │ │
 645 │ │   fn main_1() {
 646 │ │     var tile_ix : u32;
     · │
1186 │ │               } else {
     │ │ ╭────────────────────^
1187 │ │ │               break;
     │ │ ╰───────────────────^ invalid break
     · │ │
1342 │ │     return;
1343 │ │   }
     │ ╰───^ naga::Function [27]

Function [27] 'main_1' is invalid:
        The `break` is used outside of a `loop` or `switch` context
Generating SPIR-V output requires validation to succeed, and it failed in a previous step
```

[kernel4.wgsl.gz](https://github.com/gfx-rs/naga/files/7422152/kernel4.wgsl.gz)

Looking at the [source](https://github.com/linebender/piet-gpu/blob/master/piet-gpu/shader/kernel4.comp#L151), this corresponds to a do-while loop in the original GLSL, which might help explain why naga is having trouble recognize the break pattern.

**Comment by jimblandy** [comment]
These days the shader source linked above is no longer valid. It contains the code:

```
          continuing {
            let x_1122 : u32 = tile_seg_ref.offset;
            if ((x_1122 != 0u)) {
            } else {
              break;
            }
          }
```

The spec now requires that `break` to be a `break if` statement.
