### ISSUE TITLE
Returning a matrix from vertex shaders tries to center the matrix in a perspective coordinate space

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/wgpu#4442]
Found this while testing gfx-rs/naga#1524. It causes a validation error with MSL, and the GLSL output looks suspicious: https://github.com/gfx-rs/naga/pull/1524/commits/e9d55e35328d23c20e49aff06d9a574c23eeddb7#diff-df3c6ef5dd3eb006b2c8511d5cfbd8ff63c9b4924bd3ff43f41ee298ceccaa7d

**Comment by teoxoy** [comment]
This has been fixed by https://github.com/gfx-rs/naga/commit/57e1793143e9ed7937be90f4ef0ea58c7303d61f.
