### ISSUE TITLE
[glsl-out] fix usage of gsamplerCubeArrayShadow

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#4455]
from https://github.com/bevyengine/bevy/issues/841#issuecomment-999017895
> Internal error in FRAGMENT shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias

**Comment by allsey87** [comment]
A quick note for those who are trying to get Bevy working under Linux with an Intel-based graphics card, you probably need to install the `vulkan-intel` package for your distribution.

**Comment by magcius** [comment]
I realize immediately below the code that errors out is code that checks for TEXTURE_SHADOW_LOD. Assuming the user has support for TEXTURE_SHADOW_LOD, this shouldn't be impossible to fix.

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/pull/5171 should have resolved this, closing.
