### ISSUE TITLE
Error messages are garbled and truncated in firefox console log

### ISSUE THREAD

**Issue by glalonde** [gfx-rs/wgpu#4459]
![image](https://user-images.githubusercontent.com/4079525/150623570-394a722c-b7f8-440c-9826-c7e9c386e565.png)

Not sure if this is a naga issue or something with my `console_log` setup, but it looks like it is naga. The truncation is the frustrating part.

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/pull/3591 fixed the ANSI color escape codes being embedded in the messages.

Let's track further improvements in https://github.com/gfx-rs/wgpu/issues/4494.
