### ISSUE TITLE
Naga should not permit readable storage textures by default

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#4466]
As a deliberate extension for use by native apps, Naga accepts readable storage images, even though these are forbidden in the WGSL spec. However, Naga offers no means to disable this extension for WGSL compliance. This feature should be optional, and our tests should run with it disabled by default.

For example, the following declaration is accepted by Naga but rejected by Tint:

```
var image_storage_src: texture_storage_2d<rgba8uint, read>;
```

As explained in [Matrix chat](https://app.element.io/#/room/!fjjkgHFcwtkREywzfk:matrix.org/$bEjLspm1c2069P7W8BxiPRjjNSnRfZMNESm8j8w_0EQ), Naga deliberately permits readable storage textures for use by native `wgpu` apps. However, when used in WebGPU, this should be disabled for consistency with other implementations.

I think Naga's tests should run with this disabled, so that we can assume that tests are spec-compliant WGSL unless explicitly marked otherwise.

Perhaps the best way to implement this would be to add a flag to `naga::valid::Capabilities`. I think this should be off by default.

**Comment by teoxoy** [comment]
read-only storage textures have now landed in the core spec, we can close this.
