### ISSUE TITLE
Framebuffers keep accumulating, degrading performance

### ISSUE THREAD

**Issue by LaylConway** [gfx-rs/wgpu#447]
Not sure how the lifecycle of framebuffers works right now or where it's coming from.

&borrowfan on Discord showed me a flame graph, showing that `.collect()` in `triage_framebuffers` takes increasingly long to complete. I added a `println` before it and that showed that framebuffers keep accumulating and aren't cleaned up until the `Surface` is destroyed.

**Comment by LaylConway** [comment]
Quickly doing some more debugging, it seems `remove_list` is always empty until a surface gets destroyed.

**Comment by LaylConway** [comment]
Looking further into this, it seems `command_encoder_begin_render_pass` keeps creating new framebuffers, because it seems, for me, that the resolve target is different every frame:
```
FB AttachmentData { colors: [(0, 1, Vulkan)], resolves: [], depth_stencil: None }
Reuse
FB AttachmentData { colors: [(2, 1, Vulkan)], resolves: [(4, 74, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(5, 1, Vulkan)], resolves: [(7, 74, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(0, 1, Vulkan)], resolves: [], depth_stencil: None }
Reuse
FB AttachmentData { colors: [(2, 1, Vulkan)], resolves: [(7, 75, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(5, 1, Vulkan)], resolves: [(4, 75, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(0, 1, Vulkan)], resolves: [], depth_stencil: None }
Reuse
FB AttachmentData { colors: [(5, 1, Vulkan)], resolves: [(7, 76, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(2, 1, Vulkan)], resolves: [(4, 76, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(0, 1, Vulkan)], resolves: [], depth_stencil: None }
Reuse
FB AttachmentData { colors: [(5, 1, Vulkan)], resolves: [(4, 77, Vulkan)], depth_stencil: None }
Create
FB AttachmentData { colors: [(2, 1, Vulkan)], resolves: [(7, 77, Vulkan)], depth_stencil: None }
Create
```

**Comment by LaylConway** [comment]
I'm resolving to the swapchain's image view, and I think there's a new view created every frame, that's probably what's causing this. I'm not 100% sure about this though.

**Comment by LaylConway** [comment]
This was fixed by the merge so I'll close it

**Comment by kvark** [comment]
Isn't merged yet
