### ISSUE TITLE
Function-local `const` declarations not implemented

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#4493]
https://gpuweb.github.io/gpuweb/wgsl/#const-decls

**Comment by nical** [comment]
This blocks a few of the official webgpu samples, see https://bugzilla.mozilla.org/show_bug.cgi?id=1806659#c4

**Comment by ErichDonGubler** [comment]
Firefox bug: [bug 1878320](https://bugzilla.mozilla.org/show_bug.cgi?id=1878320)

**Comment by sagudev** [comment]
@jimblandy is this being actively worked on or can I try it?

**Comment by jimblandy** [comment]
@sagudev It's on our list of things we need, but we don't have it scheduled. It would be wonderful if you'd like to give this a shot. If I recall correctly, you haven't done much Naga work before, but @teoxoy and I would be happy to help you out as necessary.

**Comment by sagudev** [comment]
I implemented it in #6156, it just needs more tests.
