### ISSUE TITLE
Metal shader translation does not align `vec3`s to match std140

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#4522]
***See later updates as this original description is an incorrect diagnosis.***

My application worked OK under the Metal backend but mis-shaded under the WebGL backend. I made the problem disappear by modifying my camera uniform struct to avoid lone `f32`s in favor of `vec4<f32>`s.

My understanding is that this is because WebGL uniforms expect [“std140” layout](https://www.khronos.org/opengl/wiki/Interface_Block_(GLSL)#Memory_layout) which pads every field up to a multiple of 16 bytes (the size of a `vec4<f32>`). (My own knowledge of GL is limited here, as I never used structs in uniforms rather than individual scalar/vector/matrix uniforms before starting to use `wgpu`, so I could be missing some nuance.)

It seems to me that, to support portability between backends, `wgpu` should either:

* do whatever code transformation is necessary to effectively _not_ have std140 padding on the WebGL backend (probably not a good idea), or
* consider it a `MissingDownlevelFlags` error when a shader has a struct used as a uniform which has padding under std140 that would not be present on other backends. (In particular, `DownlevelFlags::BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED` probably applies to the same situations; maybe it should be renamed and expanded to cover this?)

**Comment by teoxoy** [comment]
@ErichDonGubler and I went over this thinking it would be a quick fix but the solution I proposed wouldn't have fully fixed the underlying issue.

I filed https://github.com/gfx-rs/wgpu/issues/4703 to track the full solution.

**Comment by kpreid** [comment]
Testing my application `all-is-cubes` with the workarounds for this issue (explicitly packing vec3s into vec4s) removed confirms that it's fixed as of revision 1cf0fe84. Thanks!
