### ISSUE TITLE
Use root NSView on macos when not provided by raw-window-handle

### ISSUE THREAD

**Issue by lmcgrath** [gfx-rs/wgpu#453]
I’m working to integrate `rust-sdl2` with `raw-window-handle`, and `SDL2` only exposes the `NSWindow` handle and not the `NSView` handle. I see `wgpu` requires both handles, but the root `NSView` can be fetched from the given `NSWindow` handle though with a little bit of objective-c. I was wondering if I could contribute some code to grab the `NSView` handle if it isn’t provided?

Here’s the related [rust-sdl2 issue](https://github.com/Rust-SDL2/rust-sdl2/issues/910).

**Comment by kvark** [comment]
Interesting. If this is about adding a bit of logic in `wgpu` macOS path to derive `NSView`, that sounds good to me. Please make a PR for us to have a better idea, it doesn't appear to be complex piece of work.
