### ISSUE TITLE
Compute shader throwing validation errors not present in Vulkan

### ISSUE THREAD

**Issue by spencerkohan** [gfx-rs/wgpu#4534]
I'm attempting to create a module from the following shader:

```glsl
#version 450
layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform texture2D input_image;
layout(set = 0, binding = 1) uniform sampler input_sampler;
layout(set = 1, binding = 0, rgba8) uniform writeonly image2D output_image;

void main() {

    ivec2 textureSize = imageSize(output_image);
    if (gl_GlobalInvocationID.x >= textureSize.x || gl_GlobalInvocationID.y >= textureSize.y) {
        return;
    }

    ivec2 index = ivec2(gl_GlobalInvocationID.xy);
    vec2 uv = index / textureSize;

    vec4 value = texture(
        sampler2D(input_image, input_sampler),
        uv
    );

    imageStore(output_image, index, value);
}
```

This shader works perfectly on Vulkan, but throws a few validation errors when used with naga.

The firs is related to early return:

>     Function [1] 'main' is invalid
>         Required uniformity of control flow for IMPLICIT_LEVEL in [31] is not fulfilled because of Return

And if I comment out that section, I get a second error:

>     Entry point main at Compute is invalid
>     Uses operations forbidden at this stage

By process of elimination, it seems to come down to the texture sampling:

```
vec4 value = texture(
    sampler2D(input_image, input_sampler),
    uv
);
```

Are these known issues, and is there any documentation about how naga's GLSL deviates from the standard?

**Comment by teoxoy** [comment]
Let's track this in https://github.com/gfx-rs/wgpu/issues/4369.
