### ISSUE TITLE
[spv-in] Sampling results for depth textures need to be changed to scalar floats

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu#4551]
This is a followup to https://github.com/gfx-rs/naga/pull/2341. Consider the following SPIR-V shader snippet:

```
<snip>
%type_2d_image = OpTypeImage %float 2D 1 0 0 1 Unknown
<snip>
         %68 = OpSampledImage %type_sampled_image %66 %67
         %69 = OpImageSampleExplicitLod %v4float %68 %65 Lod %float_0
         %70 = OpCompositeExtract %float %69 0
<snip>
```

`OpTypeImage` has a `1` after `2D` to indicate that it is a depth texture. When it is sampled the sample typed is a 4-component vector as [required by the spec](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpImageSampleExplicitLod).

This shader doesn't pass naga validation though because [the wgsl spec requires that depth textures sample to scalar floats](https://www.w3.org/TR/WGSL/#texturesamplelevel):

```
[2023-05-25T23:00:43Z ERROR naga::proc::typifier] Access index type Scalar { kind: Float, width: 4 }
Function [1] 'dof_downsample_with_coc' is invalid: 
        Expression [45] is invalid
        Type resolution failed
        Invalid access into expression [44], indexed: true
Generating wgsl output requires validation to succeed, and it failed in a previous step
```

If I manually mess with the the SPIR-V assembly to change the result type of the sample to a scalar float then naga processes it fine (note that this fails SPIR-V validation):

```
<snip>
%type_2d_image = OpTypeImage %float 2D 1 0 0 1 Unknown
<snip>
         %68 = OpSampledImage %type_sampled_image %66 %67
         %70 = OpImageSampleExplicitLod %float %68 %65 Lod %float_0
<snip>
```

What we need to do in the above case is, upon sampling a depth texture, we need to change the sample type to be a scalar float then insert a composite instruction that creates a 4-component vector with each field set to the scalar sample result (to not break later instructions).

**Comment by schell** [comment]
I just got bit by this one while attempting to use `OpImageFetch` to read a depth texture. @expenses is this still on your radar? I might try to tackle it as it's preventing me from [finishing occlusion culling](https://renderling.xyz/devlog/index.html#tue_oct_8_2024). I imagine @LPGhatguy would be interested in getting this one done, as well.

**Comment by schell** [comment]
In the case of `OpImageSampleDref[Explicit | Implicit]Lod` the result type is a scalar, we have to account for that.

**Comment by schell** [comment]
Actually it's any of the `OpImage` variants that use depth references.
