### ISSUE TITLE
Validate that a pipeline is bound in a pass before any draws/dispatches

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#456]
Within a pass, we track a number of conditions to make sure an upcoming draw call is valid. For example, if a pipeline requires the blend color to be set, we detect this. In this issue, we need to make sure that at least some pipeline is bound.

**Comment by kunalmohan** [comment]
I'd like to try and solve this one!

**Comment by kunalmohan** [comment]
While working on this I found that we check compatibility of a bind group in render pass but not in compute pass. Do we need to add that (probably as a separate issue)?

**Comment by kvark** [comment]
Yes, we also need to check bind group compatibility for compute, but this isn't exactly what this issue is :)

**Comment by kunalmohan** [comment]
Yeah, I understand. I'll open an issue for the same.
