### ISSUE TITLE
Some examples hang after #4202

### ISSUE THREAD

**Issue by a1phyr** [gfx-rs/wgpu#4584]
**Description**
Running `skybox`, `shadow` or `boids` example hangs.
I didn't test all other examples, but at least `hello-triangle` and `hello-compute` work.

**Repro steps**
Run examples

**Extra materials**
This starts happenning in #4202

**Platform**
OS: Debian stable

`wgpu-info`:

```
Adapter 0:
	   Backend: Vulkan
	      Name: "Intel(R) UHD Graphics 630 (CML GT2)"
	  VendorID: 32902
	  DeviceID: 39880
	      Type: IntegratedGpu
	    Driver: "Intel open-source Mesa driver"
	DriverInfo: "Mesa 22.3.6"
	 Compliant: true

Adapter 1:
	   Backend: Vulkan
	      Name: "llvmpipe (LLVM 15.0.6, 256 bits)"
	  VendorID: 65541
	  DeviceID: 0
	      Type: Cpu
	    Driver: "llvmpipe"
	DriverInfo: "Mesa 22.3.6 (LLVM 15.0.6)"
	 Compliant: true

Adapter 2:
	   Backend: Gl
	      Name: "Mesa Intel(R) UHD Graphics 630 (CML GT2)"
	  VendorID: 32902
	  DeviceID: 0
	      Type: IntegratedGpu
	    Driver: ""
	DriverInfo: ""
	 Compliant: false
```

Hangs happen with all of them

**Comment by TornaxO7** [comment]
Oh boi.... I'll dig into this later. Thank you for finding this.

**Comment by TornaxO7** [comment]
Ok, I think I found the issue. I let the `window` drop in the `new()`function of the gpu-test-struct. Adding it back again did it for me. I'll quickly create a PR.
