### ISSUE TITLE
`QueueWriteBufferView` has confusing documentation

### ISSUE THREAD

**Issue by dthusian** [gfx-rs/wgpu#4587]
The description for `wgpu::QueueWriteBufferView` reads:

> A read-only view into a staging buffer.
> 
> Reading into this buffer won’t yield the contents of the buffer from the GPU and is likely to be slow. Because of this, although [AsMut](https://doc.rust-lang.org/nightly/core/convert/trait.AsMut.html) is implemented for this type, [AsRef](https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html) is not.

This is contradictory. A read-only view shouldn't implement `AsMut`. Should the documentation say "write-only"?

**Comment by cwfitzgerald** [comment]
Heh, yeah that doesn't make any sense!

Would you be able to find a PR to improve it?

**Comment by dthusian** [comment]
Yes, I can open a pr.
