### ISSUE TITLE
hello-triangle tries to configure with zero size on web

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#4593]
**Description**
When `hello-triangle` starts up under wasm, it configures the surface with `window.inner_size()`, but that size is zero. Furthermore, the WebGPU backend does not catch this validation error.

**Repro steps**

`cargo xtask run-wasm --bin hello-triangle`
`cargo xtask run-wasm --bin hello-triangle --features webgl`

**Expected vs observed behavior**

* The example should not configure with zero size. (Is this a winit bug that the canvas size is incorrectly reported?)
* This should be a validation error on all backends, or succeed on all backends. Instead, on WebGPU this does not produce a wgpu validation error, but produces a validation error from the underlying WebGPU, and rendering then succeeds later.

    ```
    The texture size ([Extent3D width:0, height:0, depthOrArrayLayers:1]) or mipLevelCount (1) is empty.
    at ValidateTextureDescriptor (../../third_party/dawn/src/dawn/native/Texture.cpp:478)
    ```

    On WebGL it panics with a validation error inside wgpu.

**Platform**

* Chrome 118.0.5993.88
* macOS `x86_64-apple-darwin`
* wgpu trunk b6fa2c536c75c9da7aecbc5491d346fbc29a336e

**Comment by cwfitzgerald** [comment]
The WebGPU issue is https://github.com/gfx-rs/wgpu/issues/3675

**Comment by eblack-leaf** [comment]
Having trouble with this as well, I believe it is the new semantics of Window::request_inner_size() from winit. It does not immediately set the window size and returns None with a note that it will be set when Resized event is emitted. Problem is the only time I have figured out to obtain the wgpu::Surface is while still in async fn before event loop starts. Unsure how to target web in the current state of winit + wgpu.
![Error Running Triangle Example](https://github.com/gfx-rs/wgpu/assets/113637960/0a1a192f-43d1-41ca-a7df-4737ee5c4fd6)
