### ISSUE TITLE
Backport `raw-window-handle` v0.6 support to `wgpu` v0.18

### ISSUE THREAD

**Issue by daxpedda** [gfx-rs/wgpu#4595]
I was wondering if it would be possible to add support for `raw-window-handle` v0.6, see #4202, to `wgpu` v0.18.

As far as I can see, it's unfortunately not possible anymore to remove the dependency on `raw-window-handle` v0.5, because it wasn't marked optional, doing that now would be a breaking change.

My proposal would be to add a new crate feature to enable support for `raw-window-handle` v0.6.

I've already put together something working here: https://github.com/daxpedda/wgpu/compare/v0.18...daxpedda:wgpu:raw-window-handle-v0.6. I'm happy to make a PR, but would require a new `v0.18` branch to target it against.

**Comment by cwfitzgerald** [comment]
With winit supporting RWH 0.5, is this really worth the bother?

**Comment by pzipper** [comment]
> With winit supporting RWH 0.5, is this really worth the bother?

Winit 0.29 seems to use RWH 0.6 by default, and RHW 0.5 must be enabled with a feature flag

**Comment by daxpedda** [comment]
After some thinking on this I agree that this doesn't make sense.
- We can't change the type of `Surface` to implement safe surface creation.
- We can't make RWH v0.5 optional so the dependency will be there anyways.

The only advantage I see is for compatibility with other types/libraries that only support RWH v0.6, which personally I have no horse in, as e.g. Winit has compatibility for both.

Therefor I'm closing this.
