### ISSUE TITLE
Intel iGPUs with outdated graphics drivers struggle to render with `VK_EXT_robustness2` enabled

### ISSUE THREAD

**Issue by TheoDulka** [gfx-rs/wgpu#4599]
**Description**
For 0.15 and later, the shadow example doesn't render the cubes nor shadows, only the plane. The problem is expanded on in bevy https://github.com/bevyengine/bevy/issues/8037, where it only shows the clear color and sometimes UI. The shadow example was just what I used to find where the problem was in the update from 0.14.0 to 0.15.0.

**Repro steps**
1. Find an intel laptop with an integrated GPU
2. Make sure the graphics driver is relatively old (one I'm using is from June 2021)
3. Run the shadow example in a version of wgpu 0.15 and later

**Extra materials**
The problem comes from 39f6b03e197830ee9243443bfc47fa673d44a9ad / https://github.com/gfx-rs/wgpu/pull/3327

Removing this snippet of code fixes the bevy issue and the shadow example:
https://github.com/gfx-rs/wgpu/blob/43b74f9892abab4069e653671f75b3ff5850aa62/wgpu-hal/src/vulkan/adapter.rs#L671-L675 I have no idea why, so I wanted to ask if anyone has any ideas on why `VK_EXT_robustness2` causes almost everything to not be rendered in vulkan, yet be fine with a more recent driver or a different GPU. A couple thoughts I got was perhaps:
- "could be that Intel screwed up the implementation of that extension"
- "maybe an alignment issue? 'It is important to query the robustUniformBufferAccessSizeAlignment and robustStorageBufferAccessSizeAlignment from VkPhysicalDeviceRobustness2PropertiesEXT as the alignment of where buffers are bound-checked is different between implementations'"

_I'm sure this extension is useful to have, so I don't want to add a PR removing it for all GPUs, and am currently unaware of how best to add an exception for outdated intel iGPU drivers._

**Platform**
Windows 10
Intel UHD Graphics, version: 27.20.100.9664
wgpu 0.15 and later
Vulkan

**Comment by cwfitzgerald** [comment]
Hmm. Could you send a lot of `vulkaninfo` (part of the vulkan sdk) or grab the vulkan capability viewer from https://vulkan.gpuinfo.org and upload/link us a report on your code

**Comment by TheoDulka** [comment]
[vulkaninfo.txt](https://github.com/gfx-rs/wgpu/files/13194217/vulkaninfo.txt)

**Comment by cwfitzgerald** [comment]
Alright, it's almost certainly not robustStorageBufferAccessSizeAlignment as they're both `4`.

We can disable robustness based on it being Intel and a certain age of driver. Does updating your driver fix the problem? 

Without a specific driver version that works (unless you'd be wiling to binary search the driver to refine it), I think "drivers before now get this workaround.

**Comment by TheoDulka** [comment]
I had updated my driver before, but I wanted to figure out this issue, so I downgraded back.

[Driver Version 31.0.101.2115](https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html) was the earliest one I could find and try (due to Intel's End Of Life on 6th gen proc) and it works.

I'll make a PR with that workaround.

**Comment by cwfitzgerald** [comment]
Thanks for the work!

**Comment by tasogare3710** [comment]
I ran `cargo run --example breakout` using Intel N95 and dirver version **31.0.101.4648** and bevy's main repository, no problem.

```shell
2023-10-28T12:12:24.389221Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-10-28T12:12:24.600363Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) UHD Graphics", vendor: 32902, device: 18130, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "Intel driver", backend: Vulkan }
2023-10-28T12:12:25.420770Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "22621", cpu: "Intel(R) N95", core_count: "4", memory: "15.8 GiB" }
2023-10-28T12:12:25.435251Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
2023-10-28T12:13:26.733515Z  INFO bevy_window::system: No windows are open, exiting
2023-10-28T12:13:26.736252Z  INFO bevy_winit::system: Closing window 0v0
```

![bevy_breakout](https://github.com/gfx-rs/wgpu/assets/6017705/530c9143-956e-4e79-a7b3-6c304abb111d)

**Comment by tasogare3710** [comment]
Is this issue caused by a specific version of the driver(and cpu?)?

**Comment by cwfitzgerald** [comment]
Yeah somewhere between 27.20.100.9664 and 31.0.101.2115 it was fixed

**Comment by TheoDulka** [comment]
I'm pretty sure that the issue doesn't just affect a specific driver version, but that's something that could be looked into as I'm not 100% sure. I would assume that it was fixed in one driver version though, because many intel processor gens with older drivers experience this issue, seen in the bevy issue.

Your driver version 31.0.101.4648 is a later version compared to the known working version of 31.0.101.2115, so it makes sense that it works.

If you'd be willing, you could try using this earlier version [30.0.101.1729](https://www.intel.com/content/www/us/en/download/741626/741627/intel-arc-pro-graphics-windows.html) (assuming it's one you can use) to see if the earliest working version could be narrowed down

**Comment by tasogare3710** [comment]
I have tried all the versions available for download.

| driver version   | result |
| ---------------- | ---- |
| 31.0.101.4648 | good |
| 31.0.101.4316 | good |
| 31.0.101.4092 | good |
| 31.0.101.3517 | Exit code 8 "No driver was found that can be installed on the current device" |
| 30.0.101.1729 | Exit code 8 "No driver was found that can be installed on the current device" |

* Alder Lake-**N** supports 31.0.101.4092 or later.
 - - -
31.0.101.2115 is the last version of the 6th-10th gen driver,  30.0.101.1729 is the driver for the current product that supports the arc and 11th gen and later, so it seems safe to assume that the last driver for the old product still has the bug...Really.
