### ISSUE TITLE
NodeJS bindings

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#46]
These would be required in order to run the WebGPU CTS (cc @kainino0x). I wonder if we can auto-generate it from Rust, like we generate C bindings.

**Comment by kainino0x** [comment]
My thought is that we can share a Node bindings layer, atop a common C interface. It could reduce the amount of work and maintenance here. However, if you can generate bindings that match, it would also be good.

**Comment by grovesNL** [comment]
@kainino0x do you plan to generate bindings from dawn.json or write them manually?

**Comment by GabrielMajeri** [comment]
Are there any updates on the Node bindings?

Also, would they be added to this repository, or a separate one like `wgpu-native`?
