### ISSUE TITLE
panic! when Instance is destroyed

### ISSUE THREAD

**Issue by RasmusBruhn** [gfx-rs/wgpu#4604]
**Description**
When an Instance is created with flags set to wgpu::InstanceFlags::DEBUG or wgpu::InstanceFlags::DISCARD_HAL_LABELS and later goes out of scope and rust is running in Debug mode it panics with the message:

thread 'main' panicked at 'attempt to subtract with overflow', C:\Users\rasmu\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.18.0\src\auxil\dxgi\exception.rs:34:5

It does not panic with the flag wgpu::InstanceFlags::VALIDATION

If a Surface is created using the Instance it does not panic until the surface is destroyed.

**Repro steps**
Ideally, a runnable example we can check out.

**Expected vs observed behavior**
```
fn main() {
    let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::all(),
        flags: wgpu::InstanceFlags::DEBUG,
        dx12_shader_compiler: Default::default(),
        gles_minor_version: wgpu::Gles3MinorVersion::Automatic,
    });
}
```

**Platform**
OS: Windows 11
System Type: x64-based PC
Processor: AMD Ryzen 5 4500U with Radeon Graphics, 2375 Mhz, 6 Core(s), 6 Logical Processor(s)
GPU: AMD Radeon(TM) Graphics
wgpu version 0.18.0

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/blob/e78e9dd4000635883584f7ce1e297fe2618d8f16/wgpu-hal/src/auxil/dxgi/exception.rs#L34

This is the offending code, it looks like we don't get to register the handler if we didn't get `InstanceFlags::VALIDATION` but we are trying to unregister it regardless on drop.

**Comment by hakolao** [comment]
Also encountered this (with 0.19)
