### ISSUE TITLE
Clamping when rendering onto R16Uint format textures

### ISSUE THREAD

**Issue by mathiasplans** [gfx-rs/wgpu#4670]
Hey. I was trying to render (headless) with R16Uint texture as the color attachment with the following fragment shader:
```wgsl
@fragment
fn fs_main(in: vertex_output) -> @location(0) u32 {
    return u32(in.color.r * 65535.0);
}
```
When I convert it into 16-bit PNG I get:
![output](https://github.com/gfx-rs/wgpu-native/assets/22378202/733b79df-f9cf-40bb-87f4-2ff38bd4348d)

If I use this shader:
```wgsl
@fragment
fn fs_main(in: vertex_output) -> @location(0) u32 {
    return u32(in.color.r * 255.0);
}
```
I get the following PNG:
![output](https://github.com/gfx-rs/wgpu-native/assets/22378202/6d367971-fbe9-4d47-b4ed-09a91f65db06)

This PNG looks like what I expected from the first shader. However, it will not have full range of values (0 to 65535) so I can't use it. It looks like the output of the fragment shader is clamped to 255. Is this intentional?

The workaround I currently have is to use RG8Uint texture format and use this shader:
```wgsl
@fragment
fn fs_main(in: vertex_output) -> @location(0) vec2<u32> {
    var col1 = u32(in.color.r * 65535.0) >> 8u;
    var col2 = u32(in.color.r * 65535.0) & 255u;
    return vec2<u32>(col1, col2);
}
```

**Comment by rajveermalviya** [comment]
cc @gfx-rs/wgpu (should probably be transferred to the wgpu repo)

**Comment by teoxoy** [comment]
Which backend are you using? Also, what hardware/drivers do you have?

**Comment by mathiasplans** [comment]
I am using Vulkan backend (dozen, so actually DirectX?) on WSLg. My PC has NVIDIA RTX A3000. Nvidia driver version is 529.08.

Now that I look at it with fresher eyes, I can't seem to find a reason why there would be black stripes there. If it were just clamping, there would be a solid white square.

**Comment by teoxoy** [comment]
Could you try to reproduce the issue in Windows (outside of WSL)? It might be an issue with Mesa's Dozen.

**Comment by teoxoy** [comment]
Dozen is not yet Vulkan conformant:

https://gitlab.freedesktop.org/mesa/mesa/-/blob/bafc27583cf7c2d136fa05764e5e2145fedbc9cc/src/microsoft/vulkan/dzn_device.c#L979-984

You should report this issue to the mesa repo.
