### ISSUE TITLE
POLYGON_MODE_LINE on WebGPU

### ISSUE THREAD

**Issue by benjamin-sieffert** [gfx-rs/wgpu#4675]
Until 0.17 it was possible to draw in POLYGON_MODE_LINE on WebGPU even though the feature was neither advertised by the adapter, nor supported on web according to the documentation.
Since 0.18 wpgu "correctly" rejects attempts to draw in POLYGON_MODE_LINE.

However, on the old version the feature was actually working as  intended, i.e. it was drawing only the outline of polygons.
I had tested on Chrome+Windows as well as Firefox-Nightly+Linux and both worked flawlessly.

I would be happy if this feature was supported again.

**Comment by teoxoy** [comment]
I don't know how it's possible it worked before, the param was ignored. The only thing we do now is panic if it's not "fill".
