### ISSUE TITLE
OpenGL ES 2.0 Support for Android?

### ISSUE THREAD

**Issue by p0ryae** [gfx-rs/wgpu#4697]
Why is there a lack of OpenGL ES 2.0 support on wgpu? Is there a particular reason behind? 

None of the Adreno 200 series GPUs currently have support.

**Comment by cwfitzgerald** [comment]
GLES2 has no concept of uniform buffers only vertex buffers. While it's theoretically possible that wgpu could ruin on GLES2 it would be a ton of work and no "normal" wgpu program would be able to run on it. With that level of restriction, a user that needs that much compatability should be using gles directly.

**Comment by teoxoy** [comment]
I feel like this is out of scope unless there is someone invested enough to add and maintain the code/downlevel functionality.
