### ISSUE TITLE
Write shader IO structs separately

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#4703]
Due to us having to possibly [write out padding explicitly](https://github.com/gfx-rs/wgpu/blob/3ec547cdcaaa14488327d8f1b5f7736278c4178d/naga/src/back/msl/writer.rs#L3312) to structs and because said padding shouldn't be part of the IO locations, we need to write separate structs for shader IO which then get converted back to their original form.

We do something similar in the HLSL backend.

https://github.com/gfx-rs/wgpu/blob/3ec547cdcaaa14488327d8f1b5f7736278c4178d/naga/src/back/hlsl/writer.rs#L446

**Comment by cwfitzgerald** [comment]
Just wanted to add that it would be nice to add a test in the shader layout tests for structs with `@locations` in them to make sure this works properly in practice.

**Comment by teoxoy** [comment]
It turns out the MSL backend is already doing this. I got the wrong idea from the fix in https://github.com/gfx-rs/naga/pull/1298 which fixed the specific issue but not the overall problem.
