### ISSUE TITLE
Remove naga's `span` and `validate` features

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#4705]
It's unclear why the spans are gated behind the `span` feature. They are essential for diagnostics, take almost no space, and all users of naga that I could find enable it or have it enabled because they depend on `wgpu-core` transitively.

The `validate` feature might have more value than `span` as it gates quite a bit more code than `span` but still gets enabled by `wgpu-core` unconditionally.

The main driving factor behind removing them is maintenance burden (having to always consider the case where those are not enabled).

Related (original PRs):

- https://github.com/gfx-rs/naga/pull/1092
- https://github.com/gfx-rs/naga/pull/1437

**Comment by cwfitzgerald** [comment]
To add more context, I have personally been bitten by the lack of both these features silently causing issues without real connection to why the problem is happening.
