### ISSUE TITLE
Mask Off Haswell Devices on Vulkan

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4715]
Similarly to #4709, we should remove all vulkan instances of haswell gpus. These only show up on mesa https://gitlab.freedesktop.org/mesa/mesa/-/blob/242c7a651308f43d5f6f2590717fd72f44eba3ca/src/intel/vulkan/anv_device.c#L769-775. They aren't compliant and will never be compliant. I can't find the post now, but jekstrand said that trying to support vulkan on haswell was a mistake as it gave people the impression it was possible.

Maybe we have an instance flag that disables masking if people really care.

cc @teoxoy

**Comment by teoxoy** [comment]
I have a broader patch that should take care of this, I was looking through our issues to see which ones the PR would take care of.

Will put it up soon.

**Comment by melody-rs** [comment]
I'm curious why Haswell isn't compliant?

**Comment by cwfitzgerald** [comment]
Basically the gen7 hardware doesn't have the features needed to meet vulkan 1.0. On the proprietary drivers, vulkan support only shows up in skylake (gen8)

**Comment by melody-rs** [comment]
Oh, that's annoying. I've been doing most of my development on a haswell laptop :(

**Comment by cwfitzgerald** [comment]
Wgpu will still work for you, it will just be via GLES 3.2 instead of Vulkan.
