### ISSUE TITLE
Mesh Shaders

### ISSUE THREAD

**Issue by lylythechosenone** [gfx-rs/wgpu#4721]
Mesh shaders are an exciting new technology that can provide dramatic performance and ease-of-use improvements for graphics developers in areas such as procedural generation and geometry clipping.  I think support for them would be monumentally helpful in 3d renderers, who might currently need to use a native API for this, or instead opt to use a less performant and less ergonomic option.

**Comment by cwfitzgerald** [comment]
Thanks for filing! Duplicate of #3018
