### ISSUE TITLE
Make vec4f accept int parameter

### ISSUE THREAD

**Issue by beaufortfrancois** [gfx-rs/wgpu#4727]
In the codelab for [webgpu](https://codelabs.developers.google.com/your-first-webgpu-app#3), the vertex module code is invalid and it will throw error when you try to use it. The reason behind this error is that the `vec4f` expects a float literal instead of a int literal and can't convert between them.

```wgsl
// wrong
@vertex
fn vertexMain(@location(0) pos: vec2f) ->
  @builtin(position) vec4f {
  return vec4f(pos.x, pos.y, 0, 1);
}

// correct
@vertex
fn vertexMain(@location(0) pos: vec2f) ->
  @builtin(position) vec4f {
  return vec4f(pos.x, pos.y, 0.0, 1.0);
}
```

My understanding according to https://gpuweb.github.io/gpuweb/wgsl/#f32-builtin is that it should work:
![image](https://github.com/gfx-rs/wgpu/assets/634478/f74f0ed0-2f8e-4d73-9929-1abe90824879)

Note that it works fine with Tint, in Chrome browser.
See original issue raised at https://github.com/googlecodelabs/feedback/issues/1305

**Comment by teoxoy** [comment]
Thanks for the report! This will be addressed by https://github.com/gfx-rs/wgpu/issues/4400.

**Comment by beaufortfrancois** [comment]
Thanks @teoxoy! Any rough ETA?

**Comment by teoxoy** [comment]
@jimblandy is actively working on it, since a lot of CTS shaders are running into this as well.
