### ISSUE TITLE
Texture sampling issues when using a texture binding_array on Windows+AMD gpu with wgpu 0.18

### ISSUE THREAD

**Issue by Elabajaba** [gfx-rs/wgpu#4762]
**Description**
Textures look borked when sampling from a `binding_array<texture_2d<f32>>` on Windows+AMD gpu+wgpu 0.18+vulkan.

**Repro steps**
Run bevy's [`texture_binding_array`](https://github.com/bevyengine/bevy/blob/main/examples/shader/texture_binding_array.rs) ([shader code](https://github.com/bevyengine/bevy/blob/main/assets/shaders/texture_binding_array.wgsl)) example on Windows with an AMD gpu.

**Expected vs observed behavior**

![broken sampling](https://github.com/gfx-rs/wgpu/assets/177631/6d8aa558-2ebd-46fd-a5ad-d252f51a315a)

**Extra materials**

The wgsl: https://gist.github.com/Elabajaba/783e298cff814526a4e9e17031a7346f

A similar bug happened on Linux+AMD (RADV) with wgpu 0.17, but is fixed with wgpu 0.18.
This bug only appeared for me on windows+amd with wgpu 0.18 + vulkan.

**Platform**
Windows 11, AMD 6800xt with the 23.11.1 driver.

**Comment by nical** [comment]
Which backend(s) are you seeing this issue with?

**Comment by teoxoy** [comment]
It seems my interpretation of where the decoration should go was not 100% accurate https://github.com/gfx-rs/naga/pull/2421#issuecomment-1665678646.

> VUID-RuntimeSpirv-NonUniform-06274
If an instruction loads from or stores to a resource (including atomics and image instructions) and the resource descriptor being accessed is not dynamically uniform, then the operand corresponding to that resource (e.g. the pointer or sampled image operand) must be decorated with NonUniform

_from https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/RuntimeSpirv.html_

On a second read of the VUID, I think we should decorate both the access chain and the result of the load; `glslang` seems to be doing this as well ([ref](https://github.com/KhronosGroup/glslang/blob/bfd96d3044e1e2b0522a71166203ed4ddcf8d6e5/SPIRV/SpvBuilder.cpp#L3712)).

Which would explain why this previously worked in 0.17 (where we were only decorating the access chain) but not in 0.18 (where we are only decorating the load). It seems drivers care about one or the other.

**Comment by teoxoy** [comment]
> Which backend(s) are you seeing this issue with?

Vulkan/SPIR-V - it was reported over on matrix
