### ISSUE TITLE
Update `web-sys` to `0.3.65`?

### ISSUE THREAD

**Issue by torokati44** [gfx-rs/wgpu#4776]
For updating wgpu to `0.18` in Ruffle (https://github.com/ruffle-rs/ruffle/pull/13732), we'd have to downgrade our `web-sys` dependency from `0.3.65` to `0.3.64` because of the `GpuComputePassTimestampWrite` -> `GpuComputePassTimestampWrites` feature rename.

Would it be possible to update wgpu to `web-sys` `0.3.65` instead, preferably in a new `0.18` patch release?

It's not a particularly important, we don't _require_ the newer `web-sys` version; but I assume sooner or later both projects will update anyway, so it would be nice to avoid this back-and-forth on our end.

Also, I noticed that your `js-sys` dependency is already at `0.3.65`.

**Comment by cwfitzgerald** [comment]
We've already updated on trunk - we'd accept a PR to the v0.18 branch (similar to https://github.com/gfx-rs/wgpu/pull/4631)

**Comment by torokati44** [comment]
> We've already updated on trunk

Huh, on `trunk` I'm only seeing `js-sys` as being at `0.3.65`, but not `web-sys`:

https://github.com/gfx-rs/wgpu/blob/12ee31d6f90c016f47575d5088d1eb21f68ec827/Cargo.toml#L160-L165

**Comment by cwfitzgerald** [comment]
Ah, I think it's just that wgpu is now compatible with both versions.

**Comment by torokati44** [comment]
I don't understand how that's possible when `web-sys` renamed a feature... :thinking:

**Comment by cwfitzgerald** [comment]
That feature isn't wired up right now, so we likely just removed the feature.

**Comment by torokati44** [comment]
It's at least still enabled:

https://github.com/gfx-rs/wgpu/blob/12ee31d6f90c016f47575d5088d1eb21f68ec827/wgpu/Cargo.toml#L170-L170

Is the proper fix for `trunk` to remove this line then?

**Comment by cwfitzgerald** [comment]
Then I guess i have no idea what's going on lol

**Comment by torokati44** [comment]
Both bump PRs merged (on `trunk` and `v0.18`). Thank you!
I'd wait with closing this issue until a new `v0.18.x` release.

**Comment by benjamin-sieffert** [comment]
Hey there, would you mind releasing this fix on the 18 series?
19 has some breaking changes, so the update is not trivial.
Meanwhile, 18 and 19 conflict on web-sys due to this issue here, making it very hard to set up a project that selects wgpu version based on feature flags.
Thank you!
