### ISSUE TITLE
Expose the `raw_display_handle` traits 

### ISSUE THREAD

**Issue by VirgileHenry** [gfx-rs/wgpu#4802]
**Is your feature request related to a problem? Please describe.**

I'm trying to create a renderer with WGPU that itself is a library ,and I want the renderer to be able to be created from any surface. To do this, WGPU would need to expose the used traits `raw_window_handle::HasRawWindowHandle` `raw_window_handle::HasRawDisplayHandle`, so I could write something like: 

```rust
fn create_my_renderer<T>(handle: &T) 
    where T: wgpu::raw_window_handle::HasRawWindowHandle + wgpu::raw_window_handle::HasRawDisplayHandle,
{
    // create instance
    let surface = unsafe { instance.create_surface(handle) }
}
```

And then my rendering lib can be used with any surface, I don't have to include something like winit in the library (this can be the choice to the user of the rendering lib) 

**Describe the solution you'd like**

It is as simple as exposing the crate (wgpu/lib.rs) :
```rust
pub use raw_window_handle;
``` 
Or, if we only want to expose the two traits and not the whole crate:
```rust
// faking it's the lib with the name, maybe another name is more appropriate
pub mod raw_window_handle {
    pub use raw_window_handle::HasRawWindowHandle,
    pub use raw_window_handle::HasRawDisplayHandle,
};
```

**Describe alternatives you've considered**

I've tried including myself the `raw_window_handle` lib, but the compiler can't reunite them as the same lib and can't figure out the traits forms the same bound.

Currently, I've cloned the repo and I modified it to include this feature. But IMHO, this could be a nice add-on for future versions.

**Comment by VirgileHenry** [comment]
Should I do a PR for this ? Or did someone already fixed it ? 
I have no idea what the procedure is, but I've forked the repo and made the change, so I can create a PR if this is accepted to be a change of the current v0.18 branch.

**Comment by kpreid** [comment]
> I've tried including myself the raw_window_handle lib, but the compiler can't reunite them as the same lib and can't figure out the traits forms the same bound.

This is a sign that you have used the wrong _version_ of the library in your dependencies. `wgpu` currently depends on `raw-window-handle ^0.5`, so you must do the same — *not* `^0.6` which is incompatible. It still may be desirable to re-export the dependency, but it isn't strictly necessary.

**Comment by cwfitzgerald** [comment]
Yeah it's not necessary - I think it would be nice though to have re-exports of all of our public dependencies.

**Comment by npetrangelo** [comment]
Does wgpu have any plans to use the most recent version of [raw_window_handle](https://docs.rs/raw-window-handle/latest/raw_window_handle/index.html)? Other windowing crates like winit are and I'm finding the incompatibility annoying

**Comment by cwfitzgerald** [comment]
Yes, 0.19 is coming out in two weeks with support for it. In the mean time, winit has a "rwh_05" feature that keeps compatability with wgpu.

**Comment by cwfitzgerald** [comment]
Closing in favor of https://github.com/gfx-rs/wgpu/issues/5054
