### ISSUE TITLE
Bug when not setting the adapter in the callback

### ISSUE THREAD

**Issue by porky11** [gfx-rs/wgpu#481]
I tried to create a device using an uninitialized adapter and the program fails with an unreachable code error.
```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', wgpu-native/src/device.rs:176:5
```
I don't think, this behavior is intended. Normally you would expect unreachable code to never be reached.
Or is it ok, because I submitted an invalid value?

**Comment by kvark** [comment]
You are right, user is never expected to reach "unreachable" code, this is an error catching/reporting bug on our side.

**Comment by cwfitzgerald** [comment]
CLosing as stale due to old hal
