### ISSUE TITLE
Shader Compilation Cache: Can serialize & deserialize ComputePipeline/ShaderModule

### ISSUE THREAD

**Issue by nathanielsimard** [gfx-rs/wgpu#4812]
It would be highly beneficial to implement a mechanism for caching shader compilation on disk. This could involve making ShaderModule or ComputePipeline serializable/deserializable, thereby preventing the need to recompile each shader when launching an application.

While I don't have a specific solution to propose, I would be content as long as we could avoid recompiling all kernels on a device with a cache. It's worth noting that the cache could be tailored to the specifics of each Graphics API.

In our usage of wgpu as a backend in Burn (https://burn.dev), it would be particularly advantageous to avoid recompiling all compute shaders when launching a model for inference or training, as this would significantly reduce cold start times. Furthermore, I envision that game engines built on top of wgpu could also derive substantial benefits from incorporating such a feature.

**Comment by daxpedda** [comment]
Cc https://github.com/gfx-rs/wgpu/issues/3103.

**Comment by Wumpf** [comment]
Makes sense, but I think the issue daxpedda pointed out is indeed a duplicate 

* #3103

Btw. @nathanielsimard _if_ you're on Vulkan you can already pass in a precompiled SpirV blob to save you the compliation step. But there is no platform indpeendent mechanism yet sadly!
https://docs.rs/wgpu/latest/wgpu/enum.ShaderSource.html#variant.SpirV
