### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by warvstar** [gfx-rs/wgpu#482]
Any android support? How much work would be involved to get such a thing?

**Comment by kvark** [comment]
I don't know any of the blockers between us and Android support. It should either work already (on devices supporting Vulkan), or reachable within a few minor fixes. Running on OpenGL is a different story, which we need to get better at.

**Comment by kvark** [comment]
Looks like it's fixed by https://github.com/gfx-rs/wgpu-native/pull/5
