### ISSUE TITLE
Test wgpu_test::shader::struct_layout::uniform_input failing (Vulkan/AMD Radeon RX 6900 XT)

### ISSUE THREAD

**Issue by valaphee** [gfx-rs/wgpu#4829]
**Description**
All tests are passing except the `wgpu_test::shader::struct_layout::uniform_input` test, which fails with
```
[2023-12-04T20:27:43Z ERROR wgpu_test::expectations] Expected to fail due to [ValidationError(Some("a matrix with stride 8 not satisfying alignment to 16"))], but did not fail
thread '<unnamed>' panicked at 'explicit panic', tests\src\run.rs:110:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Extra materials**
[wgpu-info.json](https://github.com/gfx-rs/wgpu/files/13551147/wgpu-info.json)

**Platform**
Windows 11 with an AMD Radeon RX 6900 XT (driver version 23.10.2)

**Comment by cwfitzgerald** [comment]
Thanks for filing.

You're running without the vulkan validation layers! Our tests currently rely on the vulkan validation layers being present.
