### ISSUE TITLE
Does wgpu support bindless textures?

### ISSUE THREAD

**Issue by stephanemagnenat** [gfx-rs/wgpu#483]
Vulkan exposes bindless textures through the `shaderSampledImageArrayDynamicIndexing` extension, and [most implementations support it](http://vulkan.gpuinfo.org/listreports.php?feature=shaderSampledImageArrayDynamicIndexing). I saw that [`gfx_hal` lists it as an optional feature](https://github.com/gfx-rs/gfx/blob/237831204ab8946cd9c15a5cb76d15fe8406393d/src/hal/src/lib.rs#L147). My question is, is there a way to actually use it from `wgpu`? That extension would improve the performance of 2D games for example.

**Comment by kvark** [comment]
I think you are looking for https://github.com/gpuweb/gpuweb/issues/380
Note: if the group doesn't end up designing any extension, we can try to figure something out here in wgpu, but that would be available only for native targets, not the web.

**Comment by stephanemagnenat** [comment]
Thank you for the pointer, I missed it in my earlier search. In my case, I was thinking about high-performance native 2D engine using Rust.

**Comment by cwfitzgerald** [comment]
I'm currently working on full blown descriptor indexing an an extention. If you think `shaderSampledImageArrayDynamicIndexing` without full non uniform indexing is useful to you, I'll add that as a separately checkable extension.

**Comment by stephanemagnenat** [comment]
That's great! I would guess (without checking) that there would be more hardware support for `shaderSampledImageArrayDynamicIndexing` than for full blown description indexing, but I might be wrong.

**Comment by cwfitzgerald** [comment]
`shaderSampledImageArrayDynamicIndexing` iirc is supported by basically 100% of implementations of vulkan on all platforms, or something stupidly close to that. `shaderSampledImageArrayNonUniformIndexing` is mainly desktop hardware. I'll expose that as a separate extension, so you can use choose which one you want to support. Doesn't take much extra work at all.
