### ISSUE TITLE
Missing error messages

### ISSUE THREAD

**Issue by porky11** [gfx-rs/wgpu#485]
When errors occur, I normally just get a rust default error message like this:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`', wgpu-core/src/device/mod.rs:977:9
```

This does not provide any useful information on what's wrong. It would be nice to get some hint at least.

**Comment by kvark** [comment]
Thanks for the report! I renamed the title a bit to make it more constructive and close to the problem.
Relevant code in this case is https://github.com/gfx-rs/wgpu/blob/d4a46cb60e71d6b108e9052cc581e52e44a16a44/wgpu-core/src/device/mod.rs#L977
Adding an error message is trivial, might be a good first issue.

**Comment by hgallagher1993** [comment]
I can pick this up :-) is there an exact error message ye have in mind?

**Comment by kvark** [comment]
@hgallagher1993 great! Something like
> "The bind group {:?} has {} bindings, while the corresponding layout {:?} expects {}"

where the "{:?}" would be printing the IDs

**Comment by hgallagher1993** [comment]
Cool, I should get it done sometime over the weekend

**Comment by Hyperion101010** [comment]
Hi there @kvark as it seems this issue is still open. I would like to work on this one. Will open a PR once done.

**Comment by hgallagher1993** [comment]
Ya you can take it, I've been trying to get the examples to run before doing this like installing glfw 3.3 etc but haven't got it going yet and haven't had the time the week or so to really look into it

**Comment by Hyperion101010** [comment]
Ok cloning and patching it.

**Comment by Hyperion101010** [comment]
I opened a PR please take a look.

**Comment by paulkernfeld** [comment]
Looks like the [specific assertion inside of `fn device_create_bind_group`](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/mod.rs#L1045) is now more explanatory. I could see two possible courses of action:

1. Close the issue, now that the specific assertion is more informative
2. Treat this as a general effort to improve assertion error messages within `wgpu-core`. I would be happy to take a stab at this. There are several dozen assertions that could probably be explained more.

I'm not sure which way would be better so I think a maintainer will be able to make this decision.

**Comment by kvark** [comment]
You are totally right. We can have this issue for general error messages. It's typically driven by confusion people face, since in the long run we'll not have any assertions like that, and instead implement the error model in the way it's done upstream. So the efforts to make them nicer are only good in short-term.

**Comment by radgeRayden** [comment]
The error message at the line https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/queue.rs#L87 is incorrect; from the logic surrounding it it should report that an usage of `COPY_SRC` is necessary, instead of the inexistant `DST_SRC`

**Comment by radgeRayden** [comment]
The error message at the line https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/queue.rs#L87 is incorrect, reporting that a buffer usage of `DST_SRC` (that doesn't exist) is necessary when it probably meant to say `COPY_DST`.

**Comment by kvark** [comment]
@radgeRayden thank you for spotting! I'm addressing this one in #666

**Comment by kvark** [comment]
This is being replaced by #638
