### ISSUE TITLE
Queue.write_texture waits too long when called from a separate thread

### ISSUE THREAD

**Issue by lisyarus** [gfx-rs/wgpu#4859]
I'm using wgpu through wgpu-native in C++. In my application, I tried to make a separate thread that loads textures from disk, builds mipmaps, and loads them to the GPU using `queue.write_texture`. I noticed that with this approach the textures appear to load much longer than if I loaded them all in the main rendering thread.

Upon futher investigation it turned out that the `write_texture` call makes random stalls and can take anything from 0 to 16 milliseconds, regardless of the texture / mipmap level size. It looks like this function waits for the next `queue.submit` or something like that before it can actually submit the texture write.

Returning the `write_texture` call to the main thread (i.e. the separate thread only loads from disk and computes mipmaps) makes things run fast again.

To be honest, I'm not sure if this is a bug or expected behavior. Is there some synchronization happening under the hood? Is submitting to a queue from a different thread not how it is supposed be done?

Thank you in advance!

**Comment by cwfitzgerald** [comment]
Hello!

This is basically https://github.com/gfx-rs/wgpu/issues/2710 - basically up until very recently (after 0.18 released), there was a significant amount of locking in wgpu. `get_current_texture` and `write_*` commonly caused massive amounts of contention. So most of this should go away once 0.19 lands.

**Comment by lisyarus** [comment]
@cwfitzgerald Thanks a lot!

**Comment by lisyarus** [comment]
@cwfitzgerald Sorry to bump this, but I couldn't find the info anywhere. Is there any planned or approximate release date for 0.19?

**Comment by cwfitzgerald** [comment]
We release every 12 weeks, and 0.19 is slated for January 17th - we hide the dates in the [milestones](https://github.com/gfx-rs/wgpu/milestones) :)

Note that wgpu-native can update earlier or later, as they're not directly tied to our versioning. @rajveermalviya what's the current deal with wgpu-native's versioning/releasing schedule?

**Comment by rajveermalviya** [comment]
Release schedule of `wgpu-native` follows `wgpu` - when wgpu 0.19 gets released, wgpu-native will follow with a release of 0.19.0.1. Though `wgpu-native`'s trunk does sometimes gets updated to `wgpu`'s trunk, rather than targeting the latest release of `wgpu`.

But unfortunately it's mostly done on-demand, currently it targets a [version of `wgpu`](https://github.com/gfx-rs/wgpu/commits/2e7fd75712bfaacdaaa5538204cfe8b9360f82ca ) that is post 0.18 but pre arcanisation. I will soon get it updated to latest wgpu trunk.

**Comment by lisyarus** [comment]
@cwfitzgerald @rajveermalviya Thank you! To be honest, I'm more interested in filtering floating-point textures, which iirc was merged around a week ago? Anyway, a fresh release of wgpu-native with wgpu trunk would be cool, but I'm guessing you have enough work already, and I can absolutely wait until January :)

**Comment by rajveermalviya** [comment]
@lisyarus wgpu-native `trunk` now targets wgpu@[6dc9cca](https://github.com/gfx-rs/wgpu/commits/6dc9ccab8592645fda3204be1cfb5929fd7f924d/) :)

You can download `trunk` binary archives from here: https://github.com/gfx-rs/wgpu-native/actions/runs/7192422937

**Comment by lisyarus** [comment]
@rajveermalviya Thank you so much again!

**Update**: I've checked the latest build you linked, indeed the synchronization issues seem to be fixed, and filtering floating-point textures is supported. Amazing! :)
