### ISSUE TITLE
Minimizing input lag

### ISSUE THREAD

**Issue by HalfVoxel** [gfx-rs/wgpu#486]
Hi

I've been trying to figure out how to minimize input lag while using wgpu and winit (which seems to be the standard).
This has turned out to be tricky due to how the borrowing of swapchain images works.

My current render loop looks something like

```
event_loop.run(move |events, _, control_flow| {
     // Process events
     let frame = swap_chain.get_next_texture();
     // Render
}
```

The problem is that with vsync get_next_texture may block. Usually it blocks for 16ms (60 Hz). This results in that even if there would be input events during those 16 ms they will not be detected by the program until the next frame.

Trying to acquire the frame at the end of the event loop

```
let mut next_frame = ...;
event_loop.run(move |events, _, control_flow| {
     // Process events
     // Render
     next_frame = swap_chain.get_next_texture();
}
```

does not seem to work very well. Maybe my limited rust skills is preventing me from seeing an obvious solution, but I can not get that to work without the compiler complaining. Furthermore since frames are only presented upon drop this will cause the presentation to be unnecessarily delayed (if it would work, that is).

Using the mailbox present mode seems like it would help. However wgpu does not seem to support that (is there any reason for this?).

So the different solutions that I could see for this are
* Add a method to the swap chain that blocks until an image is ready, but don't actually acquire it.
* Support the mailbox present mode
* Don't use vsync. This does indeed work, however it will possibly introduce tearing, which I'd like to avoid.

Does anyone have any other suggestions for how to minimize the input lag?

**Comment by HalfVoxel** [comment]
Oops. I posted this on the wgpu repo, not wgpu-rs as I intended. I'm closing this and opening https://github.com/gfx-rs/wgpu-rs/issues/172 instead.

**Comment by kvark** [comment]
fwiw, you can move issues between repos. No need to close & reopen.
