### ISSUE TITLE
[wgsl-in] Implement `quantizeToF16`

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/wgpu#4875]
Implement the `quantizeToF16` built-in function from the WGSL spec.

**Comment by jimblandy** [comment]
The spec you want to follow is [here](https://gpuweb.github.io/gpuweb/wgsl/#quantizeToF16-builtin).

The basic outline of this work is:

- At some point, add a snapshot test input file to `naga/tests/in/math-functions.wgsl`, and edit `naga/tests/snapshots.rs` to know about it.
- Add the function to `naga::MathFunction` in the Naga IR in `naga/src/lib.rs`. You'll get lots of compiler errors. Use `todo!()` to get things running again.
- Add the function to the WGSL front end, `naga/src/front/wgsl`. You'll figure it out.
- Extend the typifier in `proc/typifier.rs`.
- Extend the validator in `valid/expression.rs`.
- Add support to the WGSL backend in `back/wgsl`.
- Add support to the SPIR-V backend, using `OpQuantizeToF16`.
- Figure out what the corresponding functions are on Metal and HLSL, and add support to `back/msl` and `back/hlsl`.

You can use features like `wgsl-in` or `spv-out` to enable specific parts of Naga. By default, Naga doesn't enable any front- or backends, so you can pare down how much of the code base you want to deal with by just enabling the piece you're working on now.

**Comment by teoxoy** [comment]
You might find some more info in the issue that proposed adding this to the spec: https://github.com/gpuweb/gpuweb/issues/704
