### ISSUE TITLE
Latest `naga` release on `crates.io` has a higher version than what's in `trunk`

### ISSUE THREAD

**Issue by torokati44** [gfx-rs/wgpu#4889]
This makes it impossible to patch the `naga` dependency of `naga_oil` to what's in `wgpu` `trunk`, because `cargo` thinks that would be a downgrade.

May I suggest bumping the version to `0.15.0+dev` or something similar?

**Comment by torokati44** [comment]
Thanks a lot for the super quick fix! 🚀

**Comment by torokati44** [comment]
(Unfortunately, the exact reason for my request is still not fixed, as `naga_oil` requires the `span` feature of `naga`, which got removed in `0.14.2`, so I still have to fork it. Anyway, this is one less roadblock!)

**Comment by cwfitzgerald** [comment]
(Note for those worried about semver, it got removed on trunk, 0.14.2 still has it).
