### ISSUE TITLE
Freeing resources after device loss should use `Device::trackers` to find resources, not `Device::life_tracker`

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#4907]
At present, device loss uses `LifetimeTracker::release_gpu_resources` to find buffers to free. However, `Device::life_tracker` does not hold a complete record of all resources created with the device. For buffers, for example, it only mentions buffers that are waiting to be mapped or ready to be mapped. `Device::trackers`, however, holds a `Tracker` whose `buffers` field holds all buffers owned by the `Device`, which is exactly what device loss needs.

**Comment by jimblandy** [comment]
This would be a follow-up to #4851. CC @bradwerth

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/pull/5075 resolved this.
