### ISSUE TITLE
CPU profiling infrastructure

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#491]
Candidates:
  - https://github.com/glennw/thread_profiler (note: our threading is not fixed when in standalone mode, I don't think we can use this)
  - https://github.com/AlexEne/rust_hawktracer
  - https://github.com/padenot/chrome-tracing (used by WebAudio implementation in Gecko)

Some obvious things we'd like to track down:
  - time to acquire a new swapchain image (including the fence block time)
  - time to submit
  - time to record a pass
  - time to create resources

**Comment by JoNil** [comment]
I have been thinking about building rust bindings to tracy, maybe that could be an option: https://bitbucket.org/wolfpld/tracy/src/master/

**Comment by kvark** [comment]
That does look pretty fancy and functional! My personal preference though would be to have something Rusty :) The chrome-tracing thing, in particular, appears to be battle-tested.

**Comment by kvark** [comment]
Interesting windows-only solution - https://github.com/embarkStudios/superluminal-perf-rs

**Comment by gw3583** [comment]
> I have been thinking about building rust bindings to tracy, maybe that could be an option: https://bitbucket.org/wolfpld/tracy/src/master/

FWIW, I built an early pass as rust bindings for tracy - https://github.com/gw3583/tracy-rs - it only exposes a basic set of CPU profiling APIs for now. It's published on crates.io.

**Comment by kvark** [comment]
We didn't have enough choices, so here is some more by @gw3583:
- https://github.com/yse/easy_profiler#easy_profiler
- https://github.com/jonasmr/microprofile
- https://github.com/Celtoys/Remotery

**Comment by GabrielMajeri** [comment]
How about the [`tracing`](https://github.com/tokio-rs/tracing) crate? It seems to be a pretty mature pure Rust solution.

**Comment by kvark** [comment]
This is a very interesting one, which somehow I didn't see before. I'd be open to trying it out in `wgpu`! The only unclear thing to me is how we are going to analyze its output.

**Comment by mstange** [comment]
I think `tracing` leaves the output part as "any way you want" - I think `tracing` is more of an abstraction layer you put in between the capturing and the analysis. So, for example, you could instrument your code with `tracing` spans, and then have a subscriber that takes those and uses `tracy-rs` to convert them into output that can be analyzed.

**Comment by kvark** [comment]
@mstange yes, I understand that abstract nature of it. I'm more asking about the practical side: what do people use with it (i.e. which subscribers)?

**Comment by cwfitzgerald** [comment]
To add even more options to the fire: https://github.com/hrydgard/minitrace is out there. Doesn't fit the rusty component, but it exists. It also outputs to chrome traces.

chrome-tracing imo looks really simple, is pure rust, and will probably get done exactly what we need to. The only possible missing feature would be events, but that's probably not a show stopper.

**Comment by kvark** [comment]
chrome-tracing gives me an uneasy feeling because of its name :)
Let's start with `tracing` as the Rust idiomatic solution, and consider others if we hit any blockers (i.e. dependency tree is too large, doesn't support our use case, or something else).

**Comment by GabrielMajeri** [comment]
I've been looking through the code, `wgpu-core` already has a `trace` feature, and it seems to be used for tracing some events to a `trace.ron` file. How is that affected by this issue?

**Comment by cwfitzgerald** [comment]
@GabrielMajeri That's for api tracing, which serializes all calls to wgpu into RON files so the player can replay them later.

**Comment by cwfitzgerald** [comment]
I think this is pretty solved by our tracing integration.
