### ISSUE TITLE
Resources should need only one submission to be released

### ISSUE THREAD

**Issue by gents83** [gfx-rs/wgpu#4917]
In mem_leaks.rs we can see that it has been modified to add 2 consecutive poll.
This should not be necessary.
Resources should be released in a specific order to avoid keeping as marked to be used resourced that should not be used anymore.

![image](https://github.com/gfx-rs/wgpu/assets/62186646/16a2fce2-9ed1-4df9-8ba8-c99a974e1303)

**Expected behavior:**
In a single submission all resources even with dependencies should be released

Tagging @nical & @jimblandy for info

**Comment by nical** [comment]
My take is that we should not attempt to release resource in a specific order and just let the `Arc`s do their thing (if there is a particular order to preserve, then model it with strong references). This means that we stop conditionally retaining resources in the `triage_*` functions based on their reference count (I believe that's what prevents some resources from being released in a single polling step of the device.

**Comment by gents83** [comment]
True, but we've to solve this problem.
Since some resources keep some Arc to other resources and we want to be sure that in 1 submit we need to be sure to release before the one holding refs to others.
Otherwise they will not be released in the same frame.
So basically what the triage was doing is:
If A has an Arc reference of B, then we've first to remove the reference and then release A, so B will result as a lonely reference and can be released.
Maybe we could find a smarter alternative?

**Comment by nical** [comment]
I am in the middle of a fair amount of churn in the resource deallocation logic, and there was the winter break but I'm hoping to get to all of this soon.

The alternative I'm hoping for is the simple/dumb one: When A is dropped, it drops the reference of B. If A was the only thing holding B alive, then B naturally gets deallocated immediately after A.
