### ISSUE TITLE
`DrawIndexedIndrect` struct incorrectly names the first field `vertex_count`

### ISSUE THREAD

**Issue by olofwalker** [gfx-rs/wgpu#4923]
**Description**
The `DrawIndexedIndirectly` field `vertex_count` should be named `index_count`.

**Repro steps**
Replace any `draw_index` call with a `draw_indexed_indirectly` call and initialize the indirect structure like this:

```
let vertex_count = mesh.vertex.len();
let index_offset = 0;
let vertex_offset = 0;

DrawIndexedIndirect {
                vertex_count: vertex_count,
                instance_count: 1,
                base_index: index_offset,
                vertex_offset,
                base_instance: 0,
}
```

**Expected vs observed behavior**
I created the buffer with the number of vertexes in `vertex_count` and saw that only part of the mesh was rendered.

When replacing the vertex count in `vertex_count`, with the index count, the mesh renders correctly.

**Extra materials**
MDM documentation describes the expected format of the indirect indexed buffer with correct names:
https://developer.mozilla.org/en-US/docs/Web/API/GPURenderPassEncoder/drawIndexedIndirect

**Platform**
MacOS Sonoma 14, Rust, WGPU 0.18

**Comment by cwfitzgerald** [comment]
Thanks for filling!

This has actually already been fixed, and will be part of 0.19! https://github.com/gfx-rs/wgpu/blob/c97b351b835966a3765818ebe61b97fe6bbcb206/wgpu-types/src/lib.rs#L6731C1-L6731C1
