### ISSUE TITLE
[webgpu target] Possible to automatically (blocking) yield after SurfaceTexture::present?

### ISSUE THREAD

**Issue by benjamin-sieffert** [gfx-rs/wgpu#4925]
I have noticed that, presenting to the target canvas on WebGPU via `SurfaceTexture::present`, it seems to only come into effect (reach the screen) after "yielding" from my application code.
This yielding can be for example
- `gloo_timers::future::TimeoutFuture::new(100).await` in my `async fn main`
- returning from the handler of winit’s EventLoop

I presume the reason for this behavior is pretty obvious and "intended" to someone familiar with the wgpu code – probably some delayed tasks that need an execution slot to run, and are waiting for the single available thread.

My application was not written primarily for the wasm32 target. I have succeeded in nicely yielding after the main `present` calls, but there are still minor `present` where I can not yield like I would need to. Either because I am not in an async context, or because I am not able to "save the stack" easily in a way that would allow me to early return from the event loop.

Now what I was wondering is, could there be an optional feature in wgpu (or does it exist already?) that makes it so I do not have to yield, but the presentation goes through regardless? This could be either via configuration, or by having an explicit blocking (not async!!) call `wait_for_present()` etc.

FWIW, using emscripten+SDL (this is WebGL in the background) over winit+wgpu, `present` works same as on desktop, i.e. it is not necessary to yield. I know that emscripten+SDL use a lot of hacks to achieve this desktop experience – it may not be feasible. But it goes to show that it’s fundamentally possible, at least with WebGL.

Best regards, and thank you for the awesome library

**Comment by cwfitzgerald** [comment]
Thanks for filling!

This is unfortunately basically out of our hands. On the webgpu and webgl backend, present is a no-op, as there actually isn't a present hook for us to call into, present is defined as implicit.

In webgpu it's (basically) defined as a special task that fires after the first task that accesses that surface textures texture.

On webgl it isn't as clear, but similar.

Emscripten uses a ton of hacks to make this work, and it's very questionable how well they work well at all. As wgpu is always trying to be as thin (as possible) layer over webgpu, we don't really have much we can do to fix this.
