### ISSUE TITLE
[naga] Subtractions don't work without whitespace.

### ISSUE THREAD

**Issue by alister-chowdhury** [gfx-rs/wgpu#4941]
**Description**

It seems naga is unable to handle subtracting a number without there being a whitespae between it, which sounds like the lexer order is a bit iffy.

**Repro steps**
```wgsl
@fragment 
fn main(@location(0) A: vec4f) -> @location(0) vec4f {
    let a = A-2.;
    return a;
}
```

`naga example.frag.wgsl`

By comparison, this is deemed ok:
```wgsl
@fragment 
fn main(@location(0) A: vec4f) -> @location(0) vec4f {
    let a = A - 2.;
    return a;
}
```

Tint seems to have no issue parsing this.

**Platform**
On x64 Win10, using the latest naga.
naga version: `0.14.0`

**Comment by teoxoy** [comment]
I think this was fixed by https://github.com/gfx-rs/wgpu/pull/4870. Could you try that commit or latest trunk?

**Comment by alister-chowdhury** [comment]
```
cargo run example.frag.wgsll
```

Seemed to work!
Many thanks, closing ticket!

(I assume I tested this correctly, cloned the repo at trunk and did cargo run from wgpu/naga-cli

**Comment by cwfitzgerald** [comment]
Sounds correct to me!
