### ISSUE TITLE
Single backend optimizations

### ISSUE THREAD

**Issue by valaphee** [gfx-rs/wgpu#4952]
**Is your feature request related to a problem? Please describe.**
Now with work-in-progress ability to compile without specific backends it should also be possible to compile with only one (the platform preferred) backend, but at the moment backend match statements wouldn't get eliminated, optimized out.

**Describe the solution you'd like**
When only one backend is enabled, all the matching could get omitted and only the one enabled backend gets returned, which would also allow for better inlining and branch prediction. (especially Id::backend)

**Comment by Wumpf** [comment]
Related to
* #3514

**Comment by cwfitzgerald** [comment]
I'm not sure this is currently worth the bother and code overhead. We will be changing around how the dispatch code works at some point in the future either as hub removal or de-genericising wgpu-core, so I'm going to close this for now.
