### ISSUE TITLE
Wgsl struct constructor failed

### ISSUE THREAD

**Issue by Alphapage** [gfx-rs/wgpu#4953]
Hello,

This code doesn't work:

https://google.github.io/tour-of-wgsl/types/structures/

It fails with error:

Shader validation error: 
  ┌─ Fragment shader:7:19
  │
7 │ const a_bicycle = Vehicle(2, 10.5);
  │                   ^^^^^^^^^^^^^^^^ naga::Expression [3]

   Constant expression [3] is invalid
   Composing 0's component type is not expected

**Platform**
MacOs,  `wgpu`:0.18.0

**Comment by teoxoy** [comment]
I think this should work now (https://github.com/gfx-rs/wgpu/pull/4743). Could you try that commit or latest trunk?

**Comment by Alphapage** [comment]
Yeah !
That's working.
Hope to have a release version soon...
Many thanks.
