### ISSUE TITLE
Metal Shading Language compiler treats infinite loops as UB

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#4972]
The Metal Shading Language compiler sometimes determines that a loop diverges. Since divergence is undefined behavior in C++, the compiler will assume the loop must be unreachable, which can lead it to make other conclusions that could result in erased bounds checks.

The workaround is to place a magic incantation in loops to cause the compiler to believe that every loop has a side effect.

Here's Dawn's solution: https://dawn-review.googlesource.com/c/dawn/+/166860 

A better explanation for it: https://dawn-review.googlesource.com/c/dawn/+/167763/3/src/tint/lang/msl/writer/ast_printer/ast_printer.cc 

```
    // This statement prevents the MSL compiler from erasing a loop during
    // optimizations.  In the AIR dialiect of LLVM IR, WGSL loops should compile
    // to a loop that contains an 'asm' call with a 'sideeffect' annotation.
    //
    // For example, compile a WGSL file with a trivial while(1) loop to 'a.metal',
    // then compile that to AIR (LLVM IR dialect):
    //
    //    xcrun metal a.metal -S -o -
    //
    // The loop in the AIR should look something like this:
    //
    //    1: ...
    //      br label %2
    //
    //    2:                                      ; preds = %1, %2
    //      tail call void asm sideeffect "", ""() #1, !srcloc !27
    //      br label %2, !llvm.loop !28
    //
    // It is important that the 'sideeffect' annotation exist. That tells the
    // optimizer that the instruction has side effects invisible to the
    // optimizer, and therefore the loop should not be eliminated.
    Line() << R"(__asm__("");)";
```

**Comment by jrmuizel** [comment]
Google tried https://github.com/google/dawn/commit/9be037cf1bcbd4a37d083d079f4e457e2b7f5182 and replaced that with https://github.com/google/dawn/commit/ffd485c685040edb1e678165dcbf0e841cfa0298
