### ISSUE TITLE
STATUS_ACCESS_VIOLATION on windows msvc

### ISSUE THREAD

**Issue by DhruvDh** [gfx-rs/wgpu#498]
```
error: process didn't exit successfully: `target\release\dip_viewer.exe -f easy.txt` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

happens at [this code](https://github.com/DhruvDh/dip_image_viewer) when running on particular machines build with `--release`. (msvc stable and nightly)
Building without release gives -

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', C:\Users\ddhamani\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.4.2\src\hub.rs:120:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\dip_viewer.exe -f easy.txt` (exit code: 101)
```

but it works fine on my laptop. This happens due to missing something wgpu dynamically links against?

I am not sure what's causing this, but I think the issue originates in wgpu. I don't have any experience interpreting backtraces, but I could try if it would help.

**Comment by kvark** [comment]
Could you get a full call stack from the debug panic?
Could you provide the repro case for us? Do you see it happening in the wgpu-rs examples?

**Comment by DhruvDh** [comment]
Hi, I cannot reproduce the error on my machine, but can on a computer at my university. I'll set a reminder to do so when I am at the university next.

**Comment by hedgehog1029** [comment]
I'm encountering the same assertion failure on Linux; [here's the backtrace](https://paste.dimdev.org/ipiriyusoj.rb). This is a simple `iced` program; I'll see if I can recreate it with the actual example.

**Comment by hedgehog1029** [comment]
Okay, yup, on my machine this can be reproduced by running the `counter` example from [`iced`](https://github.com/hecrj/iced/tree/) (`cargo run --package counter`). The window does actually render, but as soon as I move my mouse over the window it panics.

**Comment by kvark** [comment]
@hedgehog1029 this is a different issue. Please file a bug. Also, did you try running `wgpu-rs` examples?

**Comment by grovesNL** [comment]
@DhruvDh are you still having this issue?

**Comment by DhruvDh** [comment]
I tried building the same application and running it in Windows Sandbox. I could not reproduce the issue.

Sorry for not being able to respond with more details when I initially reported the issue - the issue occurred on a library computer which I no longer had access to.

**Comment by grovesNL** [comment]
Ok great, thank you!
