### ISSUE TITLE
Desktop GL seems to support READ_ONLY_DEPTH_STENCIL

### ISSUE THREAD

**Issue by valaphee** [gfx-rs/wgpu#4985]
Out of curiosity I tried the water example with the GL backend which normally would panic because of
```
thread 'main' panicked at wgpu\src\backend\direct.rs:3139:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `Main Command Encoder`
    In a pass parameter
      note: command buffer = `Main Command Encoder`
    Attempted to use a texture (mips 0..1 layers 0..1) with conflicting usages. Current usage TextureUses(RESOURCE) and new usage TextureUses(DEPTH_STENCIL_WRITE). TextureUses(DEPTH_STENCIL_WRITE) is an exclusive usage and cannot be used with any other usages within the usage scope (renderpass or compute dispatch).
```
which is because https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-core/src/command/render.rs#L986 `DEPTH_STENCIL_WRITE` usage is set instead of `DEPTH_STENCIL_READ` and `RESOURCE`.

I don't know if this intended, when the downlevel flag is not existent.

But setting `READ_ONLY_DEPTH_STENCIL` downlevel flag for Desktop GL seem to work fine (couldn't find out if this is because of an extension, etc.), on WebGL it would still work, but the water wouldn't render because of
```
WebGL warning: drawArraysInstanced: Texture level 0 would be read by TEXTURE_2D unit 1, but written by framebuffer attachment DEPTH_ATTACHMENT, which would be illegal feedback.
```

**Comment by cwfitzgerald** [comment]
I would need to double check, but I believe this is UB in the GL spec - we'd need to double check to see if this is or isn't UB in the DGL spec compared to GLES.

**Comment by teoxoy** [comment]
It works on some drivers but not on others mostly the ones for mobile GPUs and WebGL (people have run into this previously as we weren't checking for this). Last time I checked the specs, all versions of the GL and GL ES specs said it's UB.

**Comment by cwfitzgerald** [comment]
Alright, going to close this then.

**Comment by teoxoy** [comment]
If people have the time to investigate which drivers support this maybe we can enable it only for those.
