### ISSUE TITLE
Naga/Naga-CLI Doc Collision Causes CI Flakes

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#4997]
naga and naga-cli both have the same artifact name: `naga`. This causes issues with `cargo doc` as they try to document both to the same folder `naga`. Every so often it causes the documentation to crash if naga and naga-cli are documented at the same time.

Warning from cargo:
```
warning: output filename collision.
The bin target `naga` in package `naga-cli v0.14.0 (/Users/cwfitzgerald/programming/wgpu/naga-cli)` has the same output filename as the lib target `naga` in package `naga v0.14.2 (/Users/cwfitzgerald/programming/wgpu/naga)`.
Colliding filename is: /Users/cwfitzgerald/programming/wgpu/target/doc/naga/index.html
The targets should have unique names.
This is a known bug where multiple crates with the same name use
the same path; see <https://github.com/rust-lang/cargo/issues/6313>
```

Crash (from https://github.com/gfx-rs/wgpu/actions/runs/7406766998/job/20151733343?pr=4974):
```
 Documenting naga-cli v0.14.0 (/Users/runner/work/wgpu/wgpu/naga-cli)
error: "/Users/runner/work/wgpu/wgpu/target/aarch64-apple-ios/doc/naga/arena/struct.Arena.html": No such file or directory (os error 2)

error: "/Users/runner/work/wgpu/wgpu/target/aarch64-apple-ios/doc/naga/arena/struct.Range.html": No such file or directory (os error 2)

error: "/Users/runner/work/wgpu/wgpu/target/aarch64-apple-ios/doc/naga/arena/struct.Handle.html": No such file or directory (os error 2)

error: "/Users/runner/work/wgpu/wgpu/target/aarch64-apple-ios/doc/naga/all.html": No such file or directory (os error 2)

error: couldn't generate documentation: I/O error

error: could not document `naga`
```

There's basically two options:
- Change naga-cli's binary name away from `naga`. This would be mildly annoying as we wouldn't have the cool `naga`.
- Disable documenting naga-cli in CI. This has the downside that `cargo doc` locally still has the issue and you cannot view `naga`'s docs until you document only naga (as naga-cli completely overwrites it).

**Comment by teoxoy** [comment]
I'd vote for changing the name of `naga-cli`'s binary to `naga-cli`. It's an unfortunate situation though, it would have been nice if binaries and libraries had their own "namespaces".

**Comment by grovesNL** [comment]
It would be a total hack, but we could edit the binary crate name on CI for building the docs until this is supported upstream.

**Comment by cwfitzgerald** [comment]
@grovesNL fun idea, though that still won't fix cargo doc locally

**Comment by grovesNL** [comment]
What if we moved naga-cli into its own separate workspace?

**Comment by cwfitzgerald** [comment]
We could, but that has other problems and would mean we need to double up most of the commands (and build time) to make it work.

**Comment by cwfitzgerald** [comment]
OH! You can turn documentation off for a target. Going to turn that off for the naga-cli. It's not really needed for any binaries at all....
