### ISSUE TITLE
Metal `half` name reserved

### ISSUE THREAD

**Issue by BenjaminSchaaf** [gfx-rs/wgpu#5072]
**Description**
Writing a wgpu shader using a variable with the name `half` doesn't work under metal, as `half` is a reserved name.

**Repro steps**
Use the `hello_triangle` example, with the following shader on macOS (using metal):

```wgsl
@vertex
fn vs_main(@builtin(vertex_index) in_vertex_index: u32) -> @builtin(position) vec4<f32> {
    let x = f32(i32(in_vertex_index) - 1);
    let y = f32(i32(in_vertex_index & 1u) * 2 - 1);
    return vec4<f32>(x, y, 0.0, 1.0);
}

@fragment
fn fs_main() -> @location(0) vec4<f32> {
    let half = 0.5;
    return vec4<f32>(half, 0.0, 0.0, 1.0);
}
```

Apologies if this doesn't reproduce, I'm reporting this from memory of testing on someone else's mac

**Expected vs observed behavior**
The shader should work, `half` works with other backends. Instead it fails to compile the shader once it gets to the metal backend compiler.

**Platform**
macOS, wgpu 0.18.0, naga 0.14.2

**Comment by teoxoy** [comment]
I think this has been fixed with https://github.com/gfx-rs/wgpu/pull/4707. Could you try latest trunk?

**Comment by BenjaminSchaaf** [comment]
Apologies, I should have found that duplicate. I can't test right now, but I'm sure it's fixed.
