### ISSUE TITLE
`webgpu` feature fails to compile

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#5095]
**Repro steps**
Create a new crate with wgpu 0.19 as a dependency:
```toml
[dependencies]
wgpu = "0.19"
```

Build it with `cargo build --target wasm32-unknown-unknown`

It fails to build due to missing features on web_sys:
e.g.
```
error[E0412]: cannot find type `GpuBuffer` in crate `web_sys`
    --> /home/rukai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/webgpu.rs:3480:29
     |
3480 |     fn new(buffer: web_sys::GpuBuffer, desc: &crate::BufferDescriptor<'_>) -> Self {
     |                             ^^^^^^^^^ not found in `web_sys`
```

I could probably enable those features in web_sys myself but wgpu should really do that for me.

If I instead do:
```toml
[dependencies]
wgpu = { version = "0.19", default-features = false }
```

It will build successfully.

**Platform**
* Linux
* rust 1.75

**Comment by Elabajaba** [comment]
I'm also running into this with upgrading bevy to wgpu 0.19.

**Comment by cwfitzgerald** [comment]
This is because you need `--cfg web_sys_unstable_apis` in your rust flags to compile webgpu at all. This is unfortunate, but a fact of life. We should likely document this more forwardly.

**Comment by rukai** [comment]
Given that we now need this cfg to use the crate at all in it's default state, I think it needs to be documented both:
* In the main repo readme
* In the cargo.toml directly above where the websys features are enabled

**Comment by Wumpf** [comment]
I agree this should be documented in all those places. But to clarify, is this new behavior for you? We already defaulted to using webgpu on wasm whenever webgl feature is disabled. The thing that's new in 0.19 is that you can now explicitly opt-out of WebGPU (by disabling default features and not specifying `webgpu`) instead of doing so "accidentally" by picking webgl.

**Comment by rukai** [comment]
Ah, fair point, my example was bad as I was actually enabling the webgl feature before and after 0.19
So in conclusion previously the webgl feature was disabling webgpu but that no longer occurs, resulting in the confusion of existing WebGL users when 0.19 doesnt compile for them.
