### ISSUE TITLE
Incorrect mesa version warn: mesa version < 21.2 on Mesa 23.3 driver

### ISSUE THREAD

**Issue by MeowKatee** [gfx-rs/wgpu#5107]
**Description**
```bash
RUST_LOG=trace __VK_LAYER_NV_optimus=non_NVIDIA_only WGPU_ADAPTER_NAME=530 ruffle
```

Trying to launch [`ruffle`](ruffle-rs/ruffle: A Flash Player emulator written in Rust) on integrated GPU (Intel HD Graphics 530),

with Mesa 23.3 driver:
```text
...
        driverID        = DRIVER_ID_INTEL_OPEN_SOURCE_MESA
        driverName      = Intel open-source Mesa driver
        driverInfo      = Mesa 23.3.3-arch1.1
...
```

I got this warn:

```text
2024-01-20T16:18:46.658121Z  WARN wgpu_hal::vulkan::instance: Disabling presentation on 'Intel(R) HD Graphics 530 (SKL GT2)' (id 0x561212a239f0) due to NV Optimus and Intel Mesa < v21.2    
```
**Repro steps**

Launch ruffle (with [a patch](https://github.com/ruffle-rs/ruffle/issues/14834#issuecomment-1902141404) to make ruffle deal with WGPU_ADAPTER_NAME) on a Intel HD 530 + NVIDIA GTX 750Ti/960M laptop

**Expected vs observed behavior**

ruffle should work with integrated gpu

**Extra materials**

![image](https://github.com/gfx-rs/wgpu/assets/78525839/c2b56267-ceca-4283-9075-598372831042)

**Platform**

```toml
wgpu = { git = "https://github.com/gfx-rs/wgpu", branch = "v0.18" }
```

OS: Arch Linux x86_64
Host: Inspiron 7559 1.3.1
Kernel: 6.6.11-x64v2-xanmod1-1
CPU: Intel i5-6300HQ (4) @ 3.200GHz
GPU: NVIDIA GeForce GTX 960M
GPU: Intel HD Graphics 530

-------

```text
local/mesa 1:23.3.3-1
    An open-source implementation of the OpenGL specification
local/mesa-utils 9.0.0-3
    Essential Mesa utilities
local/vulkan-intel 1:23.3.3-1
    Intel's Vulkan mesa driver
```

**Comment by cwfitzgerald** [comment]
Thanks for filling! This should be fixed on 0.19
