### ISSUE TITLE
Missing VertexFormat unorm10_10_10_2 present in other implementations

### ISSUE THREAD

**Issue by waywardmonkeys** [gfx-rs/wgpu#5110]
In https://github.com/gpuweb/gpuweb/pull/4288, a new vertex format was added, but it doesn't seem to be in wgpu.

Is this an oversight, something planned, or intentionally omitted?

If given some pointers (or just an indication that it is desired), I might be able to try adding it myself.

**Comment by teoxoy** [comment]
We didn't get around to add it yet but it shouldn't be too hard. PRs welcome!

**Comment by kamalesh0406** [comment]
@waywardmonkeys are you working on a PR? If not, I can give it a try.

**Comment by waywardmonkeys** [comment]
I wasn’t yet, so feel free!
