### ISSUE TITLE
Wasm32 build missing web_sys::Gpu*

### ISSUE THREAD

**Issue by rongcuid** [gfx-rs/wgpu#5111]
**Description**
When trying to compile a basically empty wgpu project for web, build fails

**Repro steps**
Basically follow the first few steps of https://sotrh.github.io/learn-wgpu/beginner/tutorial1-window/#web-assembly, but with version updated:

Cargo.toml:

```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"

env_logger = "0.11.0"
log = "0.4.20"
wgpu = "0.19"
winit = "0.29.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
wgpu = { version = "0.19", features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }

```

lib.rs:

```
use winit::{
    event::*,
    event_loop::{ControlFlow, EventLoop},
    keyboard::{Key, NamedKey},
    window::WindowBuilder,
};

#[cfg(target_arch = "wasm32")]
use wasm_bindgen::prelude::*;

#[cfg_attr(target_arch = "wasm32", wasm_bindgen(start))]
pub fn run() {
}
```

Try compiling with `wasm-pack build`.

**Expected vs observed behavior**
Expected: compiles without error.

Actual: large amount of errors about types not found in `web_sys`:

```
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling wgpu v0.19.0
error[E0432]: unresolved import `web_sys::GpuTextureFormat`
   --> /Users/rongcuid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/webgpu.rs:142:9
    |
142 |     use web_sys::GpuTextureFormat as tf;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `GpuTextureFormat` in the root

error[E0432]: unresolved import `web_sys::GpuTextureSampleType`
   --> /Users/rongcuid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/webgpu.rs:267:9
    |
267 |     use web_sys::GpuTextureSampleType as ts;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `GpuTextureSampleType` in the root

error[E0432]: unresolved import `web_sys::GpuCullMode`
   --> /Users/rongcuid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/webgpu.rs:279:9
    |
279 |     use web_sys::GpuCullMode as cm;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `GpuCullMode` in the root
```

... and 200 more errors.

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**
Mac OS 14.2.1
Rust 1.75.0
wasm-pack 0.12.1

**Comment by rongcuid** [comment]
It seems like these are unstable features. Should they be guarded behind some feature flags?

**Comment by kpreid** [comment]
What's changed is that it used to be that enabling `webgl` _disabled_ the WebGPU backend, and thus the use of those unstable features. That's no longer the case because `webgl` and `webgpu` are allowed to coexist — now you need `default-features = false` to disable the `webgpu` feature.

**Comment by cwfitzgerald** [comment]
There's a much more actionable error coming out shortly in a patch.
