### ISSUE TITLE
IDs can be recycled before a resource is removed from the registry

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#5143]
Ids are made available for recycling from `ResourceInfo::drop`, or in other words, when a `wgpu-core` `Texture`, `CommandBuffer`, etc. is dropped.

It works fine in most cases because the registry holds arcs to the resources themselves. There is one case where it breaks: when we submit command buffers, they are replaced by placeholders in the registry that don't maintain the `ResourceInfo` alive. The `ResourceInfo` is then dropped before we get to remove the resource from the registry, allowing another CommandBuffer to be placed at the same index before we clear the slot of the previous one.

See also my ramblings in #5141

**Comment by teoxoy** [comment]
This was fixed by https://github.com/gfx-rs/wgpu/pull/5244.
