### ISSUE TITLE
`GPUProgrammableStage.entryPoint` should be optional

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#5145]
In https://github.com/gpuweb/gpuweb/pull/4387, the WebGPU API spec was changed such that, if there's only one appropriate entry point in the shader module, pipeline creation will just use that one automatically: you can omit its name from the `GPUProgrammableStage`  when you create the pipeline.

This is a cute readability hack for small (and maybe not-so-small) examples, so folks are excited about using it in the WebGPU examples repo: https://github.com/webgpu/webgpu-samples/pull/334

In our code, this would mean that `wgpu_core::pipeline::ProgrammableStageDescriptor::entry_point` would become an `Option`, consumers would use reflection to find the right entry point, and then callers in `wgpu`/Firefox/etc. would be changed to accommodate.

Since `wgpu_core` takes care of producing a `naga::Module`, it has enough information to choose an entry point before passing the module to `wgpu_hal`, so `wgpu_hal` can continue to require a specific name.

**Comment by jimblandy** [comment]
I'm taking the liberty of marking this P1 for Firefox, because of https://github.com/webgpu/webgpu-samples/pull/334.

**Comment by ErichDonGubler** [comment]
I'll take this!

**Comment by ErichDonGubler** [comment]
I'll take this!

**Comment by ErichDonGubler** [comment]
Firefox bug: [bug 1877488](https://bugzilla.mozilla.org/show_bug.cgi?id=1877488)
