### ISSUE TITLE
Cannot create transparent window

### ISSUE THREAD

**Issue by Bromles** [gfx-rs/wgpu#5150]
**Description**
With WGPU version 0.19, when trying to create a transparent window with a semi-transparent green triangle, the following happens, depending on the OS:

- On Windows with both DX12 and Vulkan adapters, the window is created, but the background is black instead of transparent, and the triangle is also filled with a solid green color. The window itself responds correctly to dragging.

- On WSL, the window is created with GL adapter and appearance is correct. But the application crashes when trying to click on a window with a wayland event loop error (`other error during loop operation` and `Io error: Broken pipe (os error 32)`)

- On MacOS with Metal adapter, behavior is fully consistent with Windows

When trying the same on version 0.17, the only difference is that in the case of WSL, the window no longer crashes when clicked, that is, the behavior becomes completely correct. But on Windows and MacOS the behavior is similar to 0.19

I'm not sure if it's a bug or my incorrect code, but, considering correct behavior with version 0.17 and WSL, I think it might be the former case.

**Repro steps**
You can check out my code [here](https://github.com/Bromles/wgpu-transparency-repro), it's fairly simple and close to a minimal reproduction

The `master` branch contains version 0.19 and the branch `0.17`, respectively, 0.17

**Extra materials**
![image](https://github.com/gfx-rs/wgpu/assets/34621477/68363da0-1291-4701-8b5c-f07754b0b602)
![image](https://github.com/gfx-rs/wgpu/assets/34621477/1622c69d-74ae-4de6-a270-988dfe5fe598)

**Platform**
- Windows 11 Enterprise 22H2 (22621.3085), 3090 Ti with Studio Driver 551.23
- WSL with Ubuntu 22.04, same hardware as Windows
- MacOS Sonoma 14.2.1, M1

**Comment by cwfitzgerald** [comment]
Thanks for filling!

Your problem is likely to do with the surface alpha mode https://github.com/Bromles/wgpu-transparency-repro/blob/master/src/app.rs#L70 - the default varies by platform, but almost always the default either assumes alpha = 255, or will ignore alpha.

If you want transparency, you need the surface alpha mode to one of the modes that is transparent. Note that not all backends support transparency by default. For example DX12 needs you to create a window using a DirectComposition surface to do any kind of blending.

**Comment by Bromles** [comment]
@cwfitzgerald Thank you very much for your answer! 

I achieved the correct behavior on MacOS by selecting the PostMultiplied alpha mode (Opaque and PostMultiplied were available). However, on Windows, only Opaque mode is available. Although I'm running with a Vulkan adapter, I think that might be the same issue as mentioned with DX12's surface type. 

Could you please tell me how to specify the surface type so that it maintains transparency? You provided a type name for DX12, but, as far as I know, the surface is created just from the window (as a SurfaceTarget), so I'm not sure how to implement it

**Comment by fgimian** [comment]
I can also reproduce this issue on Windows 11 Pro and haven't had any luck solving it. Some guidance would be greatly appreciated. 😄 

Cheers
Fotis

**Comment by danielnehrig** [comment]
@fgimian where you able to solve this on win11 i also cant get it to work on win11

**Comment by fgimian** [comment]
> @fgimian where you able to solve this on win11 i also cant get it to work on win11

I’m afraid not mate, this problem sadly prevented me from continuing my little project.

Cheers
Fotis

**Comment by danielnehrig** [comment]
> > @fgimian where you able to solve this on win11 i also cant get it to work on win11
> 
> I’m afraid not mate, this problem sadly prevented me from continuing my little project.
> 
> Cheers Fotis

sorry one thing do you have an AMD GPU ? also please head over to https://github.com/gfx-rs/wgpu/issues/5368 and leave a comment there

**Comment by fgimian** [comment]
> sorry one thing do you have an AMD GPU ? also please head over to https://github.com/gfx-rs/wgpu/issues/5368 and leave a comment there 

I use an NVIDIA video card.

**Comment by danielnehrig** [comment]
> > sorry one thing do you have an AMD GPU ? also please head over to #5368 and leave a comment there
> 
> I use an NVIDIA video card.

alright thanks i can get a transparent window on nvidia cards with vulkan backend if you return to your project just hit me up and i'll lend you some aid

**Comment by khassar00** [comment]
> > > sorry one thing do you have an AMD GPU ? also please head over to #5368 and leave a comment there
> > 
> > 
> > I use an NVIDIA video card.
> 
> alright thanks i can get a transparent window on nvidia cards with vulkan backend if you return to your project just hit me up and i'll lend you some aid

Can you create an example?Thank you very much for your help.
