### ISSUE TITLE
Recycle IDs of the freed objects properly

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#517]
Just encountered an interesting architectural problem in Gecko. When a texture view is destroyed, Gecko content process deletes the ID and sends a message to the server to delete the object. The unexpected bit here is that the ID on the server side is still alive up until the point of GPU no longer using the object. So if the content side tries to assign the same ID to a new object and register it on the server, the conflict happens, and we die.

In order to resolve it, we should not immediately free the ID on the content side. We need a mechanism for `wgpu` to give the IDs back when it's ready to do so. Then we'll have Gecko sending a message to the content side returning the ID.

**Comment by kvark** [comment]
Fix is coming in https://phabricator.services.mozilla.com/D67211 aka "ID recycler abomination".

**Comment by Kangz** [comment]
What's we've done in `dawn_wire` is associate a generation to each IDs, not sure if it is applicable in your case though.

**Comment by kvark** [comment]
@Kangz we've had an "epoch" from the start. However, our requirements for "index" lifetime are stronger, since we store stuff in arrays. So we can't have 2 things alive in the hub that share the same index with different epochs.
