### ISSUE TITLE
GL edge case, overhead of Fence::get_latest() quadratic over number of submits

### ISSUE THREAD

**Issue by adrian17** [gfx-rs/wgpu#5179]
Hey, we just encountered a weird edge case: during a single frame, we do a bunch (100+) of submits for draws to a texture target. We observed that with each submit, the list of pending fences here:

https://github.com/gfx-rs/wgpu/blob/d7bbababa7ffd2708e994df472aae27697de3bfa/wgpu-hal/src/gles/mod.rs#L603-L605

kept increasing and never got cleared (until the end of the frame). With each submit, this entire list gets iterated (note: `get_latest` is called twice during one submit) and checked with `getSyncParameter()`:

https://github.com/gfx-rs/wgpu/blob/d7bbababa7ffd2708e994df472aae27697de3bfa/wgpu-hal/src/gles/mod.rs#L626-L629

Which means, that the number of calls to `gl.getSyncParameter` is quadratic over number of submits.
This wasn't an issue on most platforms as this is supposed to be fast anyway - except for Firefox, where for some reason the IPC overhead of this call is nontrivial, and was enough to slow down the entire frame by an order of magnitude.

FF Profile:  https://share.firefox.dev/3HIrLby 
FF issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1875046

I don't know if this is actually actionable on wgpu side; my understanding is that usage that would have led to this situation, shouldn't be done in the first place. But still, thought that this is worth pointing out.

**Comment by cwfitzgerald** [comment]
The fences always happen in order - we should be able to iterate until we find an unsignalled fence, then bail. In your case, we should always bail after the first check. Unfortunately once the submits finish, there is are lot of checks to do.
