### ISSUE TITLE
Don't panic when hitting wgpu-core only paths on webgpu backend

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#5187]
Currently, all methods that require a native feature will always lead to panic on the WebGPU backend. This is unlike other errors (including lacking features on wgpu-core!) which are funneled through the error callbacks, meaning it's impossible to ignore these errors on WebGPU

**Describe the solution you'd like**
Ideally, we'd use the same mechanism and invoke the error callbacks. They are right now directly set on the backend so this might would need some additional book-keeping.

**Describe alternatives you've considered**
Technically we could return a result for all of these cases, but that would make error handling awfully inconsistent.

**Comment by cwfitzgerald** [comment]
Duplicate of https://github.com/gfx-rs/wgpu/issues/3675

**Comment by Wumpf** [comment]
Ah thx, searched but didn't find it
