### ISSUE TITLE
instance.create_surface() panics

### ISSUE THREAD

**Issue by thequver** [gfx-rs/wgpu#5225]
**Description**
Hello, i'm using wgpu 0.19.1 and my application panics on an old laptop when creating a surface with this error:
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\ACER\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-core-0.19.0\src\instance.rs:521:39```
This happens when i use `wgpu::Backends::PRIMARY` in the instance descriptor. If i use `wgpu::Backends::SECONDARY` everything works. I didn't have this error in wgpu 0.18, I think this is beause directx11 backend was removed. I seems my laptop was using it before because it doesn't support vulkan.

**Repro steps**
Unlikely you can reproduce this because the laptop is too old.

**Expected vs observed behavior**
`instance.create_surface()` panics but maybe you can return an error instead of just panic?

**Platform**
Win11, wgpu 0.19.1, ATI Mobility Radeon HD 5470 graphics card

**Comment by Wumpf** [comment]
The panic was fixed in
* https://github.com/gfx-rs/wgpu/pull/5166

with that surface creation should return an error in your case
