### ISSUE TITLE
Fix shader instrumentation for `wgpu_test::shader::struct_layout::uniform_input`

### ISSUE THREAD

**Issue by ErichDonGubler** [gfx-rs/wgpu#5245]
#5046 introduced a regression to shader compilation for `wgpu_test::shader::struct_layout::uniform_input` that we deemed acceptable, short-term (see https://github.com/gfx-rs/wgpu/pull/5046/commits/dded748fd5c5bdd46c2c68c6aaaa2cebdcfe4219#diff-c51c9614e4ff5936967ac762ce3e2d469375383a3c4995ad65a899ecf231b64dR232-R236).

But now, let's fix it!

**Comment by cwfitzgerald** [comment]
This is just #4371 - we aren't generating valid spirv, so shader validation is giving up before even trying.

**Comment by ErichDonGubler** [comment]
Ah, okay. I'll close in favor of that issue, then!
