### ISSUE TITLE
Make `wgpu_hal::vulkan::CommandEncoder::discard_encoding` idempotent so we can discard on `Drop`

### ISSUE THREAD

**Issue by ErichDonGubler** [gfx-rs/wgpu#5255]
In <https://github.com/gfx-rs/wgpu/pull/5251>, we changed all but the Vulkan backend's `CommandEncoder` implementations to call `CommandEncoder::discard_encoding`. The reason we/I forewent changing the Vulkan backend is because it doesn't appear idempotent. We'd like this to change, though, to keep things safer via [the `Drop` trait](https://doc.rust-lang.org/stable/std/ops/trait.Drop.html)! To make a concrete list, we should:

1. [`wgpu_hal::vulkan::CommandEncoder::discard_encoding`](https://docs.rs/wgpu-hal/0.19.1/wgpu_hal/trait.CommandEncoder.html#tymethod.discard_encoding) idempotent, like with other backends.
1. Call [`wgpu_hal::CommandEncoder::discard_encoding`](https://docs.rs/wgpu-hal/0.19.1/wgpu_hal/trait.CommandEncoder.html#tymethod.discard_encoding) in [`wgpu_hal::vulkan::CommandEncoder`](https://docs.rs/wgpu-hal/0.19.1/wgpu_hal/trait.CommandEncoder.html#)'s [`Drop`](https://doc.rust-lang.org/stable/std/ops/trait.Drop.html) implementation (likely in `wgpu-hal/src/vulkan/command.rs`, close to the other `impl super::CommandEncoder` block).
1. Adjust documentation of the trait definition of [`wgpu_hal::CommandEncoder::discard_encoding`](https://docs.rs/wgpu-hal/0.19.1/wgpu_hal/trait.CommandEncoder.html#tymethod.discard_encoding) to _require_ idempotency, since this seems like an important property for _any_ backend.
1. Adjust the documentation of [`wgpu_hal::CommandEncoder`](https://docs.rs/wgpu-hal/0.19.1/wgpu_hal/trait.CommandEncoder.html#) to recommend that implementers also implement [`Drop`](https://doc.rust-lang.org/stable/std/ops/trait.Drop.html).

**Comment by jimblandy** [comment]
See my comments on #5557. I think strengthening the obligations for `wgpu_hal` trait implementors is in general not the right approach. Except in cases where, say, any reasonable implementation of a method would necessarily provide a guarantee, or where providing portable behavior across backends requires some guarantee, `wgpu_hal` traits should generally foist off as many responsibilities onto their user as possible. See the [wgpu-hal crate-level docs](https://wgpu.rs/doc/wgpu_hal/index.html) for more background.

Idempotency is a great example of something that can be established once by some backend-independent type in `wgpu-core`, and then all the `wgpu_hal` backends can just lean on that.

**Comment by jimblandy** [comment]
I've tried to clarify the justification for preferring weak requirements in `wgpu-hal` traits in #5566. In that context I think it makes more sense for the Vulkan `discard_encoding` implementation to assert if `self.active` is `null`.
