### ISSUE TITLE
Panic: Some(called `Option::unwrap()` on a `None` value),

### ISSUE THREAD

**Issue by 0323pin** [gfx-rs/wgpu#5272]
Hi,

I maintain a package for `simp` for NetBSD. `simp` is a downstream image viewer using `wgpu`.

With version 3.5.0 of `simp`, using `wgpu`-0.18.0 and `wgpu-core`-0.18.1, everything was fine.

But, with `simp`-3.5.1 using `wgpu`-0.19.1, I'm getting the following panic at runtime.
```
PanicInfo { payload: Any { .. }, message: Some(called `Option::unwrap()` on a `None` value), location: Location { file: "/usr/pkgsrc/wip/simp/work/vendor/wgpu-core-0.19.0/src/instance.rs", line: 521, col: 39 }, can_unwind: true, force_no_backtrace: false }
Exception: simp exited with 1
```

See also, https://github.com/Kl4rry/simp/issues/28
I believe this is a regression, could you please have a look?

Thanks

**Platform**
NetBSD development branch, x86_64, Rust-1.75.0

**Comment by Wumpf** [comment]
Judging from the code location this got likely fixed  in https://github.com/gfx-rs/wgpu/pull/5166
@0323pin  Can you check again trunk?

**Comment by 0323pin** [comment]
I suspected that but, it's not in any release. I'll apply a patch to `wgpu` in the `simp` build and check the outcome.

It will take me sometime, though.

**Comment by 0323pin** [comment]
@Wumpf I've patched the build and with it I'm no longer getting a `wgpu` error. It still panics but, now on `simp`s `src/main.rs`.

```
Deprecation: the legacy temporary assignment syntax is deprecated; use "tmp" instead
  [tty 8]:1:1-16: RUST_BACKTRACE=1 simp
xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF-8" (mapped to "en_US.UTF-8")
PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: CreateSurfaceError { inner: Hal(NoSupportedBackend) }), location: Location { file: "src/main.rs", line: 100, col: 63 }, can_unwind: true, force_no_backtrace: false }
Exception: simp exited with 1
```

Can we keep this open until it's sorted?

**Comment by 0323pin** [comment]
I no longer believe this is the reason. Closing now, will re-open if needed.
