### ISSUE TITLE
Make TypeInner::scalar_width return the width in bytes

### ISSUE THREAD

**Issue by atlv24** [gfx-rs/wgpu#5278]
TypeInner::scalar_width currently returns the scalar width in bits. This is counter-intuitive, when the width is stored in bytes and assumed to be bytes everywhere else. If the current functionality is to be maintained, it should be renamed to `scalar_width_bits` and documented.

https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/proc/mod.rs#L267

**Comment by teoxoy** [comment]
I think this makes sense, a PR would be welcome!
