### ISSUE TITLE
[wgpu-core] request_adapter fails when requesting with a specific backend

### ISSUE THREAD

**Issue by rajveermalviya** [gfx-rs/wgpu#5289]
**Description**
[Instance::request_adapter](https://docs.rs/wgpu-core/latest/wgpu_core/global/struct.Global.html#method.request_adapter) fails when instance is created with `Backends::all()`, and then a surface is initialized, and then request_adapter is called with a specific backend in an environment with 2 or more backends.

**Repro steps**
1. Ensure you have two or more different backends.
2. [Update `instance_request_adapter`](https://github.com/gfx-rs/wgpu/blob/440574f92777c1e42a3355aa394c317645a6531b/wgpu/src/backend/wgpu_core.rs#L562) to pass a single backend like `wgt::Backends::DX12/VULKAN/METAL` instead of `wgt::Backends::all()`.
3. Run the hello_triangle example
4. Notice request_adapter fails, if it doesn't fail then cycle through other available backends on Step 2.

**Expected vs observed behavior**
request_adapter should succeed

**Platform**
macOS 14, Metal + MoltenVK

**Comment by rajveermalviya** [comment]
Closing as seems to be dupe of https://github.com/gfx-rs/wgpu/issues/5324, which will be fixed by https://github.com/gfx-rs/wgpu/pull/5535

**Comment by Wumpf** [comment]
@rajveermalviya thanks for following up, did you confirm using the branch from #5535 that it fixes the issue for you? :)
(seems very likely indeed, but might be nice to have the extra datapoint :))

**Comment by rajveermalviya** [comment]
@Wumpf  Yes, I confirmed that #5535 fixes the issue on at least MoltenVK + Metal setup (I haven't tested it on other platforms).
Thanks for working on it! :)

**Comment by Wumpf** [comment]
excellent, thank you!
