### ISSUE TITLE
Validation limits are too high

### ISSUE THREAD

**Issue by munrocket** [gfx-rs/wgpu#5296]
I have integrated gpu card on one PC and all examples gives this error
```
webgpu.js:331 panicked at 'Unable to find a suitable GPU adapter!: RequestDeviceError { inner: WebGpu(JsValue(OperationError: Required limit (255) is greater than the supported limit (0).
 - While validating maxVertexBufferArrayStride
 - While validating required limits
```
This limit probably required only for one example.

**Comment by cwfitzgerald** [comment]
Okay this is very weird, as maxVertexBufferArrayStride is required to be at least 2048 - so requesting 255 should be totally fine.

**Comment by teoxoy** [comment]
Looks like a dawn issue.

**Comment by munrocket** [comment]
> Looks like a dawn issue.

Maybe because I used linux. But other websites was ok. I can check Firefox Nightly.

**Comment by munrocket** [comment]
With C++ (dawn) I can set validation limit to any amount and this error go away.
I suppose with rust+wgpu the same situation?

**Comment by teoxoy** [comment]
I don't think this is an issue on our side, the error in the top most comment looks like a Chromium error that is not spec-compliant.
