### ISSUE TITLE
Clarify Readme Supported Platform Table

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#531]
It's a little unclear to me what all the symbols mean and how they relate to each other. Obviously the green checkmark means supported, but what does the lighter checkmark mean? Also it took to looking at the markdown source to figure out what the symbol for opengl meant.

It would just be nice to have a little key to explain it :)

**Comment by kvark** [comment]
Yeah, I think it would be good to add a small legend

**Comment by cwfitzgerald** [comment]
What does the light checkmark mean? I can make a PR to add this if you tell me 😄

**Comment by kvark** [comment]
The ":white_check_mark:" supposed to mean a "weak" support, while ":heavy_check_mark:" means good support.
