### ISSUE TITLE
docs.rs macOS and wasm32 builds failing

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#5317]
With wgpu 0.18, the macOS and wasm32 targets no longer build on docs.rs as they did in previous versions. https://github.com/rust-lang/docs.rs/issues/2424#issuecomment-1965472342 retrieved the details:

> Trying `cargo rustdoc --target wasm32-unknown-unknown` locally gives an explicit `compile_error!`:
> 
> ```
> error: webgpu feature used without web_sys_unstable_apis config:
>        Here are some ways to resolve this:
>        * If you wish to use webgpu backend, create a .cargo/config.toml in the root of the repo containing:
>            [build]
>            rustflags = [ "--cfg=web_sys_unstable_apis" ]
>            rustdocflags = [ "--cfg=web_sys_unstable_apis" ]
>        * If you wish to disable webgpu backend and instead use webgl backend, change your wgpu Cargo.toml entry to:
>            wgpu = { version = "", default-features = false, features = ["webgl"] }
>   --> src/backend/mod.rs:7:1
>    |
> 7  | / compile_error!(
> 8  | |     "webgpu feature used without web_sys_unstable_apis config:
> 9  | | Here are some ways to resolve this:
> 10 | | * If you wish to use webgpu backend, create a .cargo/config.toml in the root of the repo containing:
> ...  |
> 16 | | "
> 17 | | );
>    | |_^
> ```
> 
> while `x86_64-apple-darwin` appears to fail to cross-compile a dependency
> 
> ```
> warning: objc_exception@0.1.2: gcc: error: unrecognized command-line option ‘-arch’
> warning: objc_exception@0.1.2: gcc: error: unrecognized command-line option ‘-mmacosx-version-min=10.7’
> 
> error: failed to run custom build command for `objc_exception v0.1.2`
> ```

So, at least, the docs.rs metadata in `wgpu/Cargo.toml` should be updated to include building with `--cfg=web_sys_unstable_apis`. I don't know what would be doable for the macOS build.

**Comment by cwfitzgerald** [comment]
Way ahead of you :) This fixes the wasm issue https://github.com/gfx-rs/wgpu/pull/5310 and  https://github.com/gfx-rs/metal-rs/pull/303 should make metal compile again
