### ISSUE TITLE
wgpu-compute-toy Metal naga build error

### ISSUE THREAD

**Issue by knutsoned** [gfx-rs/wgpu#5347]
**Description**
Building wgpu-compute-toy produces an error while running the example buddhabrot

**Repro steps**
Using https://github.com/compute-toys/wgpu-compute-toy run:
cargo run examples/davidar/buddhabrot.wgsl

**Expected vs observed behavior**
Attached log shows build errors.

**Extra materials**
Attaching per WARN  wgpu::backend::direct] Please report it to https://github.com/gfx-rs/naga messages

**Platform**
macOS 13.6.3
rustc 1.76.0

[crash.txt](https://github.com/gfx-rs/wgpu/files/14501652/crash.txt)

**Comment by ErichDonGubler** [comment]
We're failing to generate a valid Metal shader, for some reason; from `crash.txt` in the OP:

```
thread 'main' panicked at src/pp.rs:29:9:
0:0: Validation Error

Caused by:
    In Device::create_compute_pipeline
    Internal error: Metal: program_source:57:5: error: too many arguments provided to function-like macro invocation
    bool success,
    ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.723/include/metal/metal_assert:19:9: note: macro 'assert' defined here
#define assert(condition) ((void) 0)
        ^
program_source:55:6: error: program scope variable must reside in constant address space
void assert(
     ^
program_source:61:5: error: expected expression
    if (!(success)) {
    ^
program_source:67:2: error: expected ';' after top level declarator
}
 ^
 ;
program_source:224:29: warning: unused variable '_e205'
                        int _e205 = uint(_e202) < 1 + (_buffer_sizes.size18 - 0 - 4) / 4 ? metal::atomic_fetch_add_explicit(&atomic_storage[_e202], 1, metal::memory_order_relaxed) : DefaultConstructible();
                            ^
program_source:226:29: warning: unused variable '_e213'
                        int _e213 = uint(_e210) < 1 + (_buffer_sizes.size18 - 0 - 4) / 4 ? metal::atomic_fetch_add_explicit(&atomic_storage[_e210], 1, metal::memory_order_relaxed) : DefaultConstructible();
                            ^
program_source:231:33: warning: unused variable '_e224'
                            int _e224 = uint(_e221) < 1 + (_buffer_sizes.size18 - 0 - 4) / 4 ? metal::atomic_fetch_add_explicit(&atomic_storage[_e221], 1, metal::memory_order_relaxed) : DefaultConstructible();
                                ^
program_source:233:33: warning: unused variable '_e232'
                            int _e232 = uint(_e229) < 1 + (_buffer_sizes.size18 - 0 - 4) / 4 ? metal::atomic_fetch_add_explicit(&atomic_storage[_e229], 1, metal::memory_order_relaxed) : DefaultConstructible();
                                ^
program_source:238:37: warning: unused variable '_e243'
                                int _e243 = uint(_e240) < 1 + (_buffer_sizes.size18 - 0 - 4) / 4 ? metal::atomic_fetch_add_explicit(&atomic_storage[_e240], 1, metal::memory_order_relaxed) : DefaultConstructible();
                                    ^
program_source:240:37: warning: unused variable '_e251'
                                int _e251 = uint(_e248) < 1 + (_buffer_sizes.size18 - 0 - 4) / 4 ? metal::atomic_fetch_add_explicit(&atomic_storage[_e248], 1, metal::memory_order_relaxed) : DefaultConstructible();
                                    ^


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I won't spend further cycles on further triaging this, but I wonder if this is related to an existing filed issue? CC @gfx-rs/naga 

---

It also seems wrong that we're reporting a validation error with a cause of an internal error. It seems that this is…_just_ an internal error.

**Comment by jmatsushita** [comment]
It looks like this error is there result of a conflict with the compute-toy prelude's `assert` function defined here: https://github.com/compute-toys/wgpu-compute-toy/blob/master/src/lib.rs#L415-L419 

Renaming that function to `assert_toy` fixes the error. I've submitted a PR https://github.com/compute-toys/wgpu-compute-toy/pull/17/files

**Comment by teoxoy** [comment]
It seems metal has an undocumented assert macro.

We should add it to our metal reserved words.
https://github.com/gfx-rs/wgpu/blob/8e15707631f1db5612824dea122ea8b6a4e9b271/naga/src/back/msl/keywords.rs

**Comment by jmatsushita** [comment]
Thanks for addressing this! 

> It seems metal has an undocumented assert macro.

That was also my finding, specifically here on my machine `/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/32023/Libraries/lib/clang/32023.116/include/metal/metal_assert`

Is there something to consider reporting upstream somewhere?

**Comment by teoxoy** [comment]
See https://developer.apple.com/bug-reporting/
