### ISSUE TITLE
Issue while downloading PyOpenGL-accelerate

### ISSUE THREAD

**Issue by Syed-Jalal** [gfx-rs/wgpu#5352]
C:\Users\MYPC122\AppData\Local\Temp\pip-build-env-c0g1nwyx\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\MYPC122\AppData\Local\Temp\pip-install-ryupch5n\pyopengl-accelerate_f153e7cf9eb84e82a4cda87493c6a03d\OpenGL_accelerate\wrapper.pxd
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling src\wrapper.pyx because it changed.
      [1/1] Cythonizing src\wrapper.pyx
      building 'OpenGL_accelerate.wrapper' extension
      creating build\temp.win32-cpython-312
      creating build\temp.win32-cpython-312\Release
      creating build\temp.win32-cpython-312\Release\src
      "D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\MYPC122\AppData\Local\Temp\pip-install-ryupch5n\pyopengl-accelerate_f153e7cf9eb84e82a4cda87493c6a03d\src -IC:\Users\MYPC122\AppData\Local\Temp\pip-install-ryupch5n\pyopengl-accelerate_f153e7cf9eb84e82a4cda87493c6a03d -IC:\Users\MYPC122\AppData\Local\Programs\Python\Python312\include -IC:\Users\MYPC122\AppData\Local\Programs\Python\Python312\Include "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc\wrapper.c /Fobuild\temp.win32-cpython-312\Release\src\wrapper.obj
      wrapper.c
      "D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x86\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\MYPC122\AppData\Local\Programs\Python\Python312\libs /LIBPATH:C:\Users\MYPC122\AppData\Local\Programs\Python\Python312 /LIBPATH:C:\Users\MYPC122\AppData\Local\Programs\Python\Python312\PCbuild\win32 "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x86" "/LIBPATH:D:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x86" /EXPORT:PyInit_wrapper build\temp.win32-cpython-312\Release\src\wrapper.obj /OUT:build\lib.win32-cpython-312\OpenGL_accelerate\wrapper.cp312-win_amd64.pyd /IMPLIB:build\temp.win32-cpython-312\Release\src\wrapper.cp312-win_amd64.lib
         Creating library build\temp.win32-cpython-312\Release\src\wrapper.cp312-win_amd64.lib and object build\temp.win32-cpython-312\Release\src\wrapper.cp312-win_amd64.exp
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PySequence_List
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyBaseObject_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyGC_Enable
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_SetAttr
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_InternFromString
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyCFunction_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyOS_snprintf
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyThreadState_Get
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_Exception
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyException_GetTraceback
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_SetObject
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyCode_NewEmpty
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_GivenExceptionMatches
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsUnsignedLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_WarnEx
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_RuntimeWarning
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyFrame_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_DeprecationWarning
      wrapper.obj : error LNK2001: unresolved external symbol __imp__Py_LeaveRecursiveCall
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyLong_AsByteArray
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyImport_ImportModuleLevelObject
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_NormalizeException
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_Occurred
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromSsize_t
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GenericGetAttr
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTraceBack_Here
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyThreadState_UncheckedGet
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_RuntimeError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyMethod_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_SetAttrString
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_UnTrack
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_Hash
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Concat
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyInterpreterState_GetID
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromUnsignedLongLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetAttr
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyModule_GetName
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsUnsignedLongLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp___Py_NoneStruct
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsLongLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTuple_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PySequence_Contains
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_SetItemString
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_Size
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromLongLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyFloat_FromDouble
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyGC_Disable
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_AttributeError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTuple_GetSlice
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_SetString
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetIter
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyNumber_Add
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_WarnFormat
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_FromUnsignedLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_Next
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_Format
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_RichCompare
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTuple_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp___Py_FalseStruct
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyImport_GetModule
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyNumber_InPlaceAdd
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyFloat_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyLong_FromByteArray
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyModule_NewObject
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyMethod_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Join
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_OverflowError
      wrapper.obj : error LNK2001: unresolved external symbol __imp___Py_Dealloc
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTuple_GetItem
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyImport_GetModuleDict
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyModule_GetDict
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PySequence_GetSlice
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_Free
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_ExceptionMatches
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyCapsule_GetPointer
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_Del
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyLong_AsLong
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDescr_IsData
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_ClearWeakRefs
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_Not
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_AsUTF8
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromFormat
      wrapper.obj : error LNK2001: unresolved external symbol __imp__Py_Version
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyVectorcall_Function
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyList_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_IsFinalized
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyImport_AddModule
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyType_Ready
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetAttrString
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_Clear
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyList_Append
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_RichCompareBool
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Decode
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyWrapperDescr_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyException_SetTraceback
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyCapsule_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyObject_GenericGetAttrWithDict
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_VectorcallDict
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_SetItem
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_CallFinalizerFromDealloc
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyDict_GetItem_KnownHash
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyMem_Free
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_StopIteration
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyList_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyErr_NoMemory
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_GetItemString
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GetItem
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_CallObject
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyModuleDef_Init
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_GC_Track
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyBytes_FromStringAndSize
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_NotImplementedError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_DelItem
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnstable_Code_NewWithPosOnlyArgs
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Compare
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_IsSubclass
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_TypeError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyMem_Realloc
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_IsTrue
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyDict_Copy
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_NameError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTuple_Pack
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyMem_Malloc
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyList_AsTuple
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_IndexError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__Py_EnterRecursiveCall
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_ImportError
      wrapper.obj : error LNK2001: unresolved external symbol __imp___Py_TrueStruct
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_SystemError
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_SetItem
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyObject_GC_New
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyException_SetCause
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyType_Modified
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyTraceBack_Type
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromString
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyType_Lookup
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_Format
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyObject_Call
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PySequence_Tuple
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyUnicode_FromStringAndSize
      wrapper.obj : error LNK2001: unresolved external symbol __imp__PyExc_ModuleNotFoundError
      wrapper.obj : error LNK2001: unresolved external symbol __imp___PyObject_GetDictPtr
      build\lib.win32-cpython-312\OpenGL_accelerate\wrapper.cp312-win_amd64.pyd : fatal error LNK1120: 146 unresolved externals
      error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyOpenGL-accelerate
Failed to build PyOpenGL-accelerate
ERROR: Could not build wheels for PyOpenGL-accelerate, which is required to install pyproject.toml-based projects

**Comment by Syed-Jalal** [comment]
what do i do

**Comment by Wumpf** [comment]
There's no indication this has anything at all to do with wgpu.
