### ISSUE TITLE
Firefox deprecating WEBGL_debug_renderer_info

### ISSUE THREAD

**Issue by lexi-the-cute** [gfx-rs/wgpu#5365]
Just giving you a heads up that Firefox is deprecating WEBGL_debug_renderer_info

> WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.

https://github.com/gfx-rs/wgpu/blob/14dbf8c60e9e20fdd8d27c28e907d3e1208690dc/wgpu-hal/src/gles/adapter.rs#L198

**Comment by cwfitzgerald** [comment]
I'm not sure how much there is we can do about this - they advertise support for it, then yell at us for using it. We are actually a case where we are behaving correctly. When they remove support, we will just start using RENDERER directly.
