### ISSUE TITLE
Unable to recover from nVidia driver bug that prevents swapchain creation.

### ISSUE THREAD

**Issue by vorporeal** [gfx-rs/wgpu#5382]
**Description**

nVidia drivers currently have a bug where a system using Prime Render Offload w/ Wayland may erroneously claim to be able to present to a surface in some situations where it actually cannot.  See: https://github.com/NVIDIA/egl-wayland/issues/94

Due to the fact that `Surface::configure` treats any errors as fatal, it isn't possible to recover from this (e.g.: try a different adapter).

I've confirmed locally, with a forked version of wgpu, that changing `surface_configure()` (in `wgpu_core`) to call `self.handle_error()` instead of `self.handle_error_fatal` does produce a validation error that can be recovered from successfully.

I'm happy to send over a PR, but wanted to confirm that this is:
1. A reasonable thing to do, and
2. There aren't any unforeseen implications for making this a recoverable error.

**Repro steps**

* Use a system with integrated GPU + dedicated nVidia GPU
* Load `nvidia_drm` kernel module with `modeset=0`
  * Can be confirmed by verifying that `sudo cat /sys/module/nvidia_drm/parameters/modeset` outputs "N".
* Run a wgpu example using the nVidia adapter (I ran `hello_triangle`, changing the power preference to `HighPerformance` from the default)

**Expected vs observed behavior**

Expected: `device.push_error_scope(ErrorFilter::Validation)` and `device.pop_error_scope()` can be use around a call to `Surface::configure()` to detect swapchain creation failures.

Observed: Swapchain creation errors are unconditionally fatal.

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

**Platform**

wgpu 0.18 (but the code for 0.19 also treats the error as fatal)
Gnome, running on Wayland
Arch Linux w/ Mesa 24.0.2
NVIDIA RTX 2000 Ada Generation Laptop GPU; nVidia proprietary drivers, version 550.54.14.

**Comment by vorporeal** [comment]
Might be a dupe of https://github.com/gfx-rs/wgpu/issues/3586.

**Comment by vorporeal** [comment]
I'd like to clarify here that I don't think `external:driver-bug` is an appropriate label - while the cause of the swapchain creation failure is a driver bug, the fact that it is unconditionally fatal to a wgpu-using application is a `wgpu` API flaw.

Another place where this is a problem is `Surface::get_current_texture` - this can fail due to the device being lost, and all errors produced by `Global::surface_get_current_texture` are treated as fatal (as opposed to, say, marking the device as lost and/or returning an appropriate error from `Surface::get_current_texture`).

In fact, "Error in Surface::get_current_texture_view: Validation Error Caused by: Parent device is lost" is the second-most common crash in our application, and `wgpu` provides no way for us to avoid it.

**Comment by ErichDonGubler** [comment]
@vorporeal: You're referring to calls (like this one in `ContextWgpuCore::surface_get_current_texture` below) to `ContextWgpuCore::handle_error_fatal`, right?

https://github.com/gfx-rs/wgpu/blob/ed843f802974eae9d708d3b3895264e9efb01dc6/wgpu/src/backend/wgpu_core.rs#L794

**Comment by Wumpf** [comment]
agreed, the issue is about flawed error handling which wgpu has in this and other places.
The fact that there's a driver bug tripping it is almost secondary - generally wgpu way too readily goes into unwrap/panic/assert and this is particularly true for surface handling which is naturally one of the things that go sideways frequently.

**Comment by Wumpf** [comment]
reading over it another time I think this is most definitely a dup of #3586 :)
At this point I'm inclined to go with `handle_error` instead of `fatal_error` and deal with the fallout step by step as we discover it.
