### ISSUE TITLE
Make `naga::back` items public to support out of tree backends

### ISSUE THREAD

**Issue by LegNeato** [gfx-rs/wgpu#5398]
**Is your feature request related to a problem? Please describe.**

As suggested in a [matrix thread](https://matrix.to/#/!fjjkgHFcwtkREywzfk:matrix.org/$Z2RBmjWdw4oDhlaKM65nhvD5ybqC-c7OkzR_c_WizoQ?via=matrix.org&via=mozilla.org&via=gitter.im), I am trying to convert the rust backend in https://github.com/gfx-rs/wgpu/pull/5175 to an out of tree maintained backend. To do so, I need some types in `naga::back` to be public.

For example, my PR uses https://github.com/gfx-rs/wgpu/blob/a63bec8cd67b4abe3b9717e1926a94d1035b830a/naga/src/back/mod.rs#L77 which works when it is in-tree but fails out of tree.

It seems pretty much everything in `naga::back` should be public if out of tree backends are encouraged as the module is meant for backends to use.

I'm fine dealing with breakage if these are `pub` and marked as unstable and/or hidden in the docs.

**Describe the solution you'd like**
The items in `naga::back` be `pub`.

**Describe alternatives you've considered**
1. I could not use those abstractions. My out of tree backend will be structured differently / drift from the in-tree ones. Eventually I would like to merge it in naga proper and using existing abstractions will help.
2. I could copy and paste what I need in. This will be what I do if naga doesn't want them to be `pub`.

**Additional context**
I was told in matrix to open an issue when something prevents the backend from being out of tree. I am happy to put up a PR flipping what I need to `pub`, but I wanted to open this issue first to see if there is a different preferred solution.

**Comment by AdrianEddy** [comment]
+1 I'm also interested in this feature
