### ISSUE TITLE
Storage epoch assertion failure

### ISSUE THREAD

**Issue by SludgePhD** [gfx-rs/wgpu#5401]
**Description**

```
thread 'main' panicked at /home/sludge/code/wgpu/wgpu-core/src/storage.rs:203:17:
assertion `left == right` failed
  left: 3827
 right: 3828
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /home/sludge/code/wgpu/wgpu-core/src/storage.rs:110:39:
TextureView[Id(4,3828,vk)] does not exist
```

**Repro steps**
None yet, this is the first time I've seen this assertion failure.

**Expected vs observed behavior**
This presumably should not be happening?

**Platform**
wgpu trunk on Arch Linux with Vulkan.

**Comment by Elabajaba** [comment]
This looks like the same error that I'm hitting in https://github.com/gfx-rs/wgpu/issues/5372

**Comment by teoxoy** [comment]
Closing in favor of https://github.com/gfx-rs/wgpu/issues/5372.
