### ISSUE TITLE
Implement new builtin packing/unpacking functions from WGSL spec

### ISSUE THREAD

**Issue by VlaDexa** [gfx-rs/wgpu#5423]
**Is your feature request related to a problem? Please describe.**
I tried using [unpack4xU8](https://www.w3.org/TR/WGSL/#unpack4xU8-builtin) and [pack4xU8](https://www.w3.org/TR/WGSL/#pack4xU8-builtin), but naga refused to parse them

**Describe the solution you'd like**
I would like them to be implemented

**Describe alternatives you've considered**
There is a problem, though. I tried implementing them myself and have found that [SPIR-V GLOp](https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html) doesn't have the same functions. I don't know how closely this repo is affiliated with the group that writes WGSL spec, so I don't know if they can be pressured to remove these functions from the spec so would WGSL more closely resemble SPIR-V.

**Additional context**
I have written parsing support that you can see in a PR that I will open referencing this issue.

**Comment by Wumpf** [comment]
> There is a problem, though. I tried implementing them myself and have found that [SPIR-V GLOp](https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html) doesn't have the same functions.

This would be one of the many cases where we have to polyfill ("emulate") a function. Many wgsl functions have a direct equivalent in the target language, so this isn't very uncommon.

edit: I see you're already doing this in your draft pr for a bunch of other languages, so yeah same story :)
