### ISSUE TITLE
supports_queue_family assertion fails, possibly because of two different gpus

### ISSUE THREAD

**Issue by Nejat** [gfx-rs/wgpu#543]
I first ran across this while running the provided examples in the [coffee](https://github.com/hecrj/coffee) project using the `vulkan` feature ...

`thread 'main' panicked at 'assertion failed: suf.supports_queue_family(&adapter.raw.queue_families[0])', /home/nejat/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/device.rs:2059:9`

> the examples work while using the `opengl` feature

Seeing that the assertion failure was in the [wgpu-native](https://crates.io/crates/wgpu-native) crate, I went back to test a program I wrote using the [Pixels](https://github.com/parasyte/pixels) project, which also depends on the same crate, and the project that was working before now has the same exact assertion failure as above.

There is one change in the system I'm using that might help point to what is causing this issue, but I have not been able to debug it.

Originally I had a single `RTX 2080 ti` when my Pixels based application worked. I recently added a second GPU, a `Radeon Pro WX 5100`. 

Is it possible the existence of two GPUs might be the cause of the assertion failure? 

This is all on `Pop!_OS 19.10`

**Comment by kvark** [comment]
Thank you for filing! That's a tough issue here, and we need a good plan for that together with @Kangz. When you are requesting an adapter, we don't know what surface you'd want to use it with, so it may end up incompatible with the surface.
We could provide a way to find out if a surface can be used with this adapter, but we also need a way to let you pick the right one. So we may need something like a list of surfaces passed in (or at least a single surface), to which an adapter has to be able to present to, at the time an adapter is requested...
Filed https://github.com/webgpu-native/webgpu-headers/pull/39 to discuss an upstream solution.

**Comment by Nejat** [comment]
Excuse me if I'm over simplifying it, I do not mean to trivialize the complexity of the issue, especially knowning that Vulkan provides a much lower level interface, however could the answer be found in how OpenGL or DX12 handle the issue? 

Not only does the OpenGL version initialize on this machine with two different GPUs, I can drag the window from one GPU display to the other. 

Just a thought.

**Comment by kvark** [comment]
@Nejat I can tell you how :)
-  OpenGL doesn't allow you to create a device without a surface to begin with
- DX12 and Vulkan have an explicit check for a surface being compatible with an adapter, and they expose all adapters at once

Since WebGPU API is shaped as "request an adapter", we'll be checking for compatibility with a surface at that moment, and we need to know which surface you want to use it with.

**Comment by Nejat** [comment]
Thank you for the clarification

**Comment by kvark** [comment]
Fixed by https://github.com/gfx-rs/wgpu/pull/545
