### ISSUE TITLE
Naga generates invalid SPIR-V in a shader with a unused acceleration structure

### ISSUE THREAD

**Issue by Vecvec** [gfx-rs/wgpu#5446]
**Description**
When converting a shader with one acceleration structure that is never used using Naga to SPIR-V and using it (using gfx-rs/wgpu#3631) the vulkan validation layers give 
````
Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282 | vkCreateShaderModule(): pCreateInfo->pCode (spirv-val produced an error):
    1st operand of Capability: operand RayQueryKHR(4472) requires one of these extensions: SPV_KHR_ray_query
      OpCapability RayQueryKHR
    . The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://vulkan.lunarg.com/doc/view/1.3.275.0/windows/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08737)
````
while this is a fork of gfx-rs/wgpu#3631, no naga changes are in either. 

**Repro steps**
```` wgsl
@group(0) @binding(0)
var acc_struct: acceleration_structure;

@workgroup_size(1)
@compute
fn comp_main() {}
````
gives this error, while changing comp_main to 
```` wgsl 
fn comp_main() {
    var rq: ray_query;
    rayQueryInitialize(&rq, acc_struct, RayDesc(0u, 0xFFu, 0.001, 100000.0, vec3f(0.0, 0.0, 0.0), vec3f(0.0, 0.0, 1.0)));
    rayQueryProceed(&rq);
    let intersection = rayQueryGetCommittedIntersection(&rq);
}
````
fixes the issue

**Expected vs observed behavior**
Expected: No validation error
Observed: Validation error

**Extra materials**
test log (just this test, I don't think the other tests would help): 
[failed test.txt](https://github.com/gfx-rs/wgpu/files/14781962/failed.test.txt)

**Platform**
This is a fork of gfx-rs/wgpu#3631.

**Comment by teoxoy** [comment]
There is probably some validation missing. The fix should be part of https://github.com/gfx-rs/wgpu/pull/3631.

**Comment by Vecvec** [comment]
I think this might be the cause https://github.com/gfx-rs/wgpu/blob/0f4839c46627437006f6cb6f2f4f804eb5b5cd2d/naga/src/back/spv/writer.rs#L1861-L1862
this only puts the extension in if there is a ray desc or a ray intersection used, should there be a bool that is set somewhere (maybe in the shader module?) to tell the writer that this feature is enabled if any ray-tracing type is used?

**Comment by teoxoy** [comment]
Ah, I misunderstood what the issue was.

The backend should loop over all types and set the `has_ray_query` var if it sees `TypeInner::AccelerationStructure` or `TypeInner::RayQuery` in addition to the special types.
