### ISSUE TITLE
Deadlock destroying resources of a destroyed device

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#5471]
If you call `wgpu_core::global::Global::device_destroy` and then `Global::device_poll` on a device that has a buffer and an empty submission queue, wgpu will deadlock. This is a regression from #5426.

- `Global::device_poll` calls `poll_single_device`, which acquires a read guard on the device's snatchlock, and passes it to `Device::maintain`.

- `Device::maintain` notices that `self` is no longer valid and that the submission queue is empty, and calls `Device::release_gpu_resources`.

- `Device::release_gpu_resources` calls `Buffer::destroy` and `Texture::destroy`.

- `Buffer::destroy` and `Texture::destroy` both try to acquire a write guard on the device's snatchlock, causing a deadlock.

**Comment by jimblandy** [comment]
The following test case deadlocks:

```
#[gpu_test]
static DEVICE_DESTROY_THEN_BUFFER_CLEANUP: GpuTestConfiguration = GpuTestConfiguration::new()
    .parameters(TestParameters::default())
    .run_async(|ctx| async move {
        // When a device is destroyed, its resources should be released,
        // without causing a deadlock.
        let buffer = ctx.device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 256,
            usage: wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        });

        // Create a 512 x 512 2D texture.
        let texture_extent = wgpu::Extent3d {
            width: 512,
            height: 512,
            depth_or_array_layers: 1,
        };
        let texture = ctx.device.create_texture(&wgpu::TextureDescriptor {
            label: None,
            size: texture_extent,
            mip_level_count: 2,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rg8Uint,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            view_formats: &[],
        });

        // Destroy the device.
        ctx.device.destroy();

        // Poll the device, which should try to clean up its resources.
        assert!(ctx
                .async_poll(wgpu::Maintain::wait())
                .await
                .is_queue_empty());

        drop((buffer, texture));
    });
```

(This would go in `tests/tests/device.rs`.)

**Comment by ErichDonGubler** [comment]
@jimblandy: ~~I think I have an even simpler test case for your pleasure!~~ EDIT: Actually, we want to exercise both textures and buffers. 😅

<details><summary>The following complete Rust program will never terminate: </summary>


```rust
use wgpu::{BufferDescriptor, BufferUsages, Instance};

fn main() {
    let instance = Instance::new(Default::default());

    let adapter = pollster::block_on(instance.request_adapter(&Default::default())).unwrap();

    let (device, _queue) =
        pollster::block_on(adapter.request_device(&Default::default(), None)).unwrap();

    // Create a resource that needs to be cleaned up…
    let _buffer = device.create_buffer(&BufferDescriptor {
        label: None,
        size: 32,
        usage: BufferUsages::MAP_READ,
        mapped_at_creation: false,
    });
    // …but don't do anything with it.

    device.destroy();

    // We now have an empty submission queue, and the device will clean up `_buffer` on the next `poll` operation.

    instance.poll_all(true);
}
```

The locking region of device polling was overlaid onto the locking region with <https://github.com/gfx-rs/wgpu/pull/5426> (CC @TheSludgePhD, @nical, @Wumpf).

</details>

**Comment by ErichDonGubler** [comment]
This issue was observed on the Firefox side as [bug 1888705](https://bugzilla.mozilla.org/show_bug.cgi?id=1888705) (while trying to re-vendor with [bug 1887909](https://bugzilla.mozilla.org/show_bug.cgi?id=1887909)).
