### ISSUE TITLE
Sampler binding 2 expects filtering = false, but given a sampler with filtering = true

### ISSUE THREAD

**Issue by Alphapage** [gfx-rs/wgpu#5472]
Hello,

My sample `BindingType` is set to `SamplerBindingType::NonFiltering`, but I get an error.
The sampler is created like this:
```
device.create_sampler(&wgpu::SamplerDescriptor {
                        label: None,
                        address_mode_u: wgpu::AddressMode::ClampToEdge,
                        address_mode_v: wgpu::AddressMode::ClampToEdge,
                        address_mode_w: wgpu::AddressMode::ClampToEdge,
                        mag_filter: wgpu::FilterMode::Linear,
                        min_filter: wgpu::FilterMode::Linear,
                        mipmap_filter: wgpu::FilterMode::Nearest,
                        ..Default::default()
                    })
```
If a sampler is set to NonFiltering, maybe I don't have to create a sample with those filtering descriptions.

Any idea?

Thank you in advance for your help.

**Comment by teoxoy** [comment]
min and mag filter need to be set to nearest.

**Comment by Alphapage** [comment]
Ok so when NonFiltering, then SamplerDescriptor must be set to default.
Why not provide an optional Sampler which could be set to None when unfiltered ?
Thank you anyway for your help.

**Comment by teoxoy** [comment]
There are still other properties that are available even on non filtering samplers.
