### ISSUE TITLE
WGSL: Support the `enable` directive

### ISSUE THREAD

**Issue by armansito** [gfx-rs/wgpu#5476]
The WGSL specification has introduced the `enable` directive for to implementation-specific extensions (see https://www.w3.org/TR/WGSL/#enable-extensions-sec). Currently naga rejects these as an invalid token, for example:

```
enable f16;
^^^^^^ expected global item ('struct', 'const', 'var', 'alias', ';', 'fn') or the end of the file
```

Even if naga doesn't support a requested extension, it should recognize the `enable` directive. In my specific use case, naga is used to parse and preprocess WGSL which may end up getting passed on to a different implementation (i.e. Dawn/Chromium). It would be nice to be able to declare Chromium-specific enable directives for the wgsl-in -> wgsl-out case.

**Comment by ErichDonGubler** [comment]
Part of #4384.

**Comment by FL33TW00D** [comment]
#5701

**Comment by EriKWDev** [comment]
just wanna bumb that this is not only f16 support-related but also `clip_distances` which would be very handy for planar the reflections in our engine, but since we cannot set the clip-distances in wgsl atm we have to resort to fragment-shader discard

**Comment by ErichDonGubler** [comment]
@EriKWDev: Just filed #6236 for that extension specifically. 🙂

**Comment by ErichDonGubler** [comment]
Resolved by <https://github.com/gfx-rs/wgpu/pull/6424>. 👏🏻
