### ISSUE TITLE
Device limits reports a max texture size that is bigger than defaults even if not requested

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu#5490]
**Description**
After creating the device without asking for any particular limits, I get a maxTextureDimension2D value that is way larger than the default. On my machine with an RTX3080 I get a limit of 32768. Other limits might be exceeding defaults, but I haven't tested many of them.

**Repro steps**
It is observable by slightly modifying the hello_triangle example to print the limits:
```diff
diff --git a/examples/src/hello_triangle/mod.rs b/examples/src/hello_triangle/mod.rs
index faa1db8f8..350c03f8d 100644
--- a/examples/src/hello_triangle/mod.rs
+++ b/examples/src/hello_triangle/mod.rs
@@ -38,6 +38,9 @@ async fn run(event_loop: EventLoop<()>, window: Window) {
         .await
         .expect("Failed to create device");
 
+    let limits = device.limits();
+    print!("{0}", limits.max_texture_dimension_2d);
+
     // Load the shaders from disk
     let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
         label: None,
```

**Expected vs observed behavior**
I expected the device to report a max texture size of 8196 as per [the spec](https://gpuweb.github.io/gpuweb/#limits).

**Platform**
Running on Arch Linux default kernel, NVIDIA RTX3080 driver version 550.67. I have observed the problem in the wgpu sample and on my own application running on top of wgpu-native.

**Comment by teoxoy** [comment]
I think this is due to this line:

https://github.com/gfx-rs/wgpu/blob/fb305b85f692f3fbbd9509b648dfbc97072f7465/examples/src/hello_triangle/mod.rs#L34

**Comment by radgeRayden** [comment]
> I think this is due to this line:
> 
> https://github.com/gfx-rs/wgpu/blob/fb305b85f692f3fbbd9509b648dfbc97072f7465/examples/src/hello_triangle/mod.rs#L34

I can observe the same effect by modifying the wgpu-native example to do a similar print. I don't know rust very well and was just doing a small modification to confirm it was a problem upstream, but it looks pretty clear to me that the C example requests no limits. What modifications should I do to the rust example to rule out a problem in wgpu itself?

**Comment by radgeRayden** [comment]
Thanks to a pointer by @wumpf I was able to rule out the issue upstream, and it seems indeed to be a bug in wgpu-native.
