### ISSUE TITLE
Pass resources as Arcs when adding them to the registry

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#5493]
A step towards #5124 

Currently when creating a resource, the registry takes the resource by value, and produce an Arc.

It does this so that it can set the ID of the resource, however it doesn't mesh well with our plan of making the resources DST to reduce the amount of generics in wgpu-core.

See the linked issue. In the future `Arc<core::Texture<A>>` might become an alias that would look like `Arc<core::TextureSource<dyn hal::Texture>>`.

We could instead pass the resource as an Arc to the registry directly. The steps would become:
 - reserve a slot in the registry, get an ID
 - create the resource with the ID
 - put the resource in an Arc and place it in the registry with the ID

**Comment by lylythechosenone** [comment]
To add to this, I don't think that's exactly how the transformation will go. Texture<A> will simply move to Texture<A = DynApi>. Everything else you said is correct, however.

**Comment by NyxAlexandra** [comment]
Will this change make it possible to (for example) make `wgpu::Texture: Clone`?

**Comment by lylythechosenone** [comment]
@NyxAlexandra this is about wgpu_core, not wgpu. wgpu's public API (and within the scope of this issue, wgpu_core's as well) will remain exactly the same.

**Comment by lylythechosenone** [comment]
Some more context on this:

Currently, inserting something into the registry means acquiring a `FutureId`, and then using `assign` to insert the value into the registry. `assign` takes `T` by value. `assign_existing` *does* take an `Arc<T>`, but it appears to be geared towards re-inserting a value that is already in another slot. We could add another function, or just slightly change `assign_existing`.

**Comment by lylythechosenone** [comment]
When implementing this I received this error (on wasm only):
```
error: usage of an `Arc` that is not `Send` and `Sync`
   --> wgpu-core/src/instance.rs:528:59
    |
528 |         let (id, _) = self.surfaces.prepare(id_in).assign(Arc::new(surface));
    |                                                           ^^^^^^^^^^^^^^^^^
    |
    = note: `Arc<Surface>` is not `Send` and `Sync` as:
    = note: - the trait `Send` is not implemented for `Surface`
    = note: - the trait `Sync` is not implemented for `Surface`
    = help: consider using an `Rc` instead. `Arc` does not provide benefits for non `Send` and `Sync` types
    = note: if you intend to use `Arc` with `Send` and `Sync` traits
    = note: wrap the inner type with a `Mutex` or implement `Send` and `Sync` for `Surface`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
    = note: `-D clippy::arc-with-non-send-sync` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::arc_with_non_send_sync)]`
```
Clippy is correct in this case. Wasm does not require `Send + Sync`. Do we want to `#[allow]` this, or do we want to use e.g. `Rc` instead, on wasm only?

**Comment by lylythechosenone** [comment]
I'm just going to `#[allow]` it for now, and create another issue about this specifically.
