### ISSUE TITLE
Try Option<CompareFunction> for the sampler

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#551]
Our `wgt::CompareFunction` has an "Undefined = 0" variant. This is non-idiomatic in Rust.
I wonder if instead we can just omit the `Undefined` variant completely, and instead rely on the fact that `Option<Enum>::None` equals to the raw value of 0 if that value isn't covered by the enum.

@Gankra for a simple `#[repr(C)] enum Enum { one = 1, two = 2 }` does the Rust guarantee anything about the binary representation of `Option<Enum>::None`?

**Comment by grovesNL** [comment]
Maybe we should expose a separate `Option<CompareFunction>` in wgpu-rs, where `CompareFunction` is `wgt::CompareFunction` without the `Undefined` variant

**Comment by aloucks** [comment]
Shouldn't the native `C` descriptor be an entirely different struct from the `Rust` wrapper? I think these issues would go away If we just moved to two entirely different sets of structs. I think the enums and bitflags can probably be shared but having everything else separate will be cleaner.

**Comment by kvark** [comment]
@aloucks but this *is* an enum :)

In general, we can have all things different. The benefit of sharing types is just having less code to maintain.

**Comment by kvark** [comment]
It turns out None takes the next raw value, not 0.
