### ISSUE TITLE
Abstract type coercion missing for function arguments

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#5523]
From [conversation](https://github.com/gfx-rs/wgpu/issues/5515#issuecomment-2048794750) in #5515:

> I think this works per the spec - the type of a literal is AbstractInt which should be coerced into whatever makes the most sense in context. I'm not sure how thorough our implementation is in 0.19 or trunk.

It works in a few spots (simple integer expressions, for example) but call a function that takes a u32 and pass a 0 and you get this beauty:

Shader validation error:
    ┌─ surface.wgsl:367:12
    │
367 │     return with_cond(vertex_ix, 0);
    │            ^^^^^^^^^^^^^^^^^^^^^^^
    │            │                    │
    │            │                    naga::Expression [2]
    │            invalid function call

    Entry point vs_main_cond at Vertex is invalid
    Call to [11] is invalid
    Argument 1 value [2] doesn't match the type [1]

It wants a 0u. Don't get me started on that error message... my goodness.

**Comment by sagudev** [comment]
today I noticed similar problem:

```wgsl
fn f() {
    let n = vec3f(1,0,1);
    let l = vec3f(1,1,0);
    let lambert = max(dot(n, l), 0);// needs 0. to work
}
```

**Comment by jimblandy** [comment]
> today I noticed similar problem:
> 
> fn f() {
>     let n = vec3f(1,0,1);
>     let l = vec3f(1,1,0);
>     let lambert = max(dot(n, l), 0);// needs 0. to work
> }

#6833 does fix this.
