### ISSUE TITLE
Atomics and Scalars are collapsed to the same LocalType

### ISSUE THREAD

**Issue by atlv24** [gfx-rs/wgpu#5569]
Atomics and Scalars are collapsed to the same LocalType
https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/back/spv/mod.rs#L360
Type capability requests are based on TypeInner
https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/back/spv/writer.rs#L835
But deduplicated by LocalType
https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/back/spv/writer.rs#L977

This means if an `atomic<u64>` is seen after `u64`, then the necessary `Int64Atomics` capability doesn't get requested.

`LocalType` should represent Atomic and non-Atomic types with distinct values, but I'm not sure how. Do we want a `atomic: bool` or an `Atomic {}` variant?

**Comment by atlv24** [comment]
Neither solution works, because type declarations must be unique. I'm going to lift the capability request call out of the lookup so it happens on every type instead

**Comment by teoxoy** [comment]
> I'm going to lift the capability request call out of the lookup so it happens on every type instead

Sounds good, not sure why it was nested.
