### ISSUE TITLE
Allocated `Chunk` was freed, but memory is still shared and never will be destroyed

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu#557]
I'm seeing these pop up after updating imgui-wgpu-rs to use WGPU 0.5.

You can reproduce by running the `hello_world` example. 

https://github.com/aloucks/imgui-wgpu-rs/tree/wgpu-next

```
ERROR 2020-04-06T23:41:23Z: gfx_memory::allocator::general: Allocated `Chunk` was freed, but memory is still shared and never will be destroyed
ERROR 2020-04-06T23:41:23Z: gfx_memory::allocator::general: Allocated `Chunk` was freed, but memory is still shared and never will be destroyed
ERROR 2020-04-06T23:41:23Z: gfx_memory::allocator::general: Allocated `Chunk` was freed, but memory is still shared and never will be destroyed
```

**Comment by kvark** [comment]
A trace log by @lachlansneff from hello-compute reporting this problem: 
[hello-compute-trace.txt](https://github.com/gfx-rs/wgpu/files/4444422/hello-compute-trace.txt)
