### ISSUE TITLE
Crash compiling and using HLSL shaders

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/wgpu#5571]
Source shader: https://paste.rs/CAVpW.txt
Output HLSL and crash: https://paste.rs/nW7t8.txt

Source shader: https://paste.rs/13TBc.txt
Output HLSL and crash: https://paste.rs/A2Vhb.txt

**Comment by cwfitzgerald** [comment]
Yeah we need to wrap scalar push constants in structs in the hlsl backend.

**Comment by cwfitzgerald** [comment]
Closing in favor of #5683
