### ISSUE TITLE
createBindGroup accepts textures from different device

### ISSUE THREAD

**Issue by sagudev** [gfx-rs/wgpu#5582]
**Description**
CreateBindGroup does not create ValidationError when textures (happens also when using StorageTexture) are from different devices. When using Samplers from different devices ValidationError is triggered.

**Repro steps**
Repro is here: https://github.com/sagudev/CBG

**Extra materials**
This causes `Set must be allocated from this allocator` crash in gpu-allocator while testing https://gpuweb.github.io/cts/standalone/?q=webgpu:api,validation,createBindGroup:binding_resources,device_mismatch:entry={%22texture%22:{%22multisampled%22:false}} in both servo and firefox.

**Platform**
Ubuntu 23.10
Wgpu 0.19.4 and trunk (4f3d9a2af52d2ab10042787a1115fe8c0779d4d9)

**Comment by sagudev** [comment]
One thing to note is that I did not find this in spec, so tests can be out of specs, but then we should still successfully do cleanup (destroy texture without crashing).

**Comment by teoxoy** [comment]
> One thing to note is that I did not find this in spec

See "valid to use with" (it covers device mismatch).

**Comment by sagudev** [comment]
> valid to use with

I see it now, thanks.

**Comment by sagudev** [comment]
https://github.com/gfx-rs/wgpu/blob/c2e520c52c426ae2ca22f324a71c702a06e183f2/wgpu-core/src/device/resource.rs#L2203 this is check on sampler and is missing in other cases of match.

**Comment by teoxoy** [comment]
Would you be able to put up a PR for this?

**Comment by sagudev** [comment]
> Would you be able to put up a PR for this?

Yes, I can. Although probably not this week.
