### ISSUE TITLE
Naga (Metal conversion) crash if we use "vertex" variable name in VertexOutput

### ISSUE THREAD

**Issue by tpisto** [gfx-rs/wgpu#5588]
The shader code that causes Naga error is working with Chrome, so I assume it's valid shader code.

**Description**

This shader code works:

```
struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(1) @interpolate(flat) instance: u32,
    @location(2) @interpolate(linear) my_vertex: vec2f
}
```
**Please note the "my_vertex" name**

This causes naga errors:

```
struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(1) @interpolate(flat) instance: u32,
    @location(2) @interpolate(linear) vertex: vec2f
}
```

**Please note the "vertex" name**

**Platform**
OS X, M1

**Comment by teoxoy** [comment]
I'm not seeing any errors on trunk. Could you provide more details? naga/wgpu version would be a good start.
