### ISSUE TITLE
"Draw Indexed Primitives Validation" assertion when drawing empty buffer

### ISSUE THREAD

**Issue by tgross35** [gfx-rs/wgpu#5632]
**Description**

Drawing an empty buffer is usually okay, but when running the debugger in XCode it will throw an assertion in metal.

**Repro steps**

My example is a bit messy but I think this is the core portion of it:

```rust
    fn prepare(mut self, /* ... */) {
        // ...

        queue.write_buffer(
            &self.fill_vbo,
            0,
            bytemuck::cast_slice(dbg!(&self.fill_geometry.vertices)),
        );
        queue.write_buffer(
            &self.fill_ibo,
            0,
            bytemuck::cast_slice(dbg!(&self.fill_geometry.indices)),
        );

        // ...
    }

    fn paint(&self, /* ... */) {
        render_pass.set_pipeline(&self.pipeline);
        render_pass.set_bind_group(0, &self.bind_group, &[]);
        
        render_pass.set_vertex_buffer(6, self.fill_vbo.slice(..));
        render_pass.set_index_buffer(self.fill_ibo.slice(..), wgpu::IndexFormat::Uint16);
        render_pass.draw_indexed(0..self.fill_geometry.indices.len() as u32, 0, 0..1);

        // ...
    }
```

During some of my code paths, `self.fill_geometry.vertices` and `self.fill_geometry.indices` are empty so the vertex and index buffers both get cleared. Within `draw_indexed`, the following error gets thrown:

```
-[MTLDebugRenderCommandEncoder validateDrawIndexedPrimitives:indexCount:indexType:indexBuffer:indexBufferOffset:instanceCount:function:]:6168: failed assertion `Draw Indexed Primitives Validation
indexCount(0) must be non-zero.
'
```

This comes from within the call to `metal::encoder::RenderCommandEncoderRef::draw_indexed_primitives`.

For whatever reason, this problem is only observable when running with the xcode debugger (not just LLDB), which is probably related to the metal debugger I was trying to use. Just running via `Debug`->`Debug Executable` is sufficient to reproduce.

**Expected vs observed behavior**

It would be nice to assert on this within `wgpu` so it is consistent across platforms. Alternatively, just return without going to the backend if an empty range is received.

**Extra materials**

egui had this problem at some point, I guess an issue report didn't make it upstream https://github.com/emilk/egui/issues/1772

**Platform**

aarch64 MacOS, wgpu 0.19.4 via eframe 0.27.2

**Comment by cwfitzgerald** [comment]
Should have been fixed in 0.20 by #5137
