### ISSUE TITLE
sRGB seemingly applied to non-sRGB render targets with 0.20 GL backend

### ISSUE THREAD

**Issue by vorporeal** [gfx-rs/wgpu#5639]
**Description**

Upgraded to the 0.20 release and noticed that, when using the GL backend with a non-sRGB texture format (specifically, `Rgba8Unorm`), colors render as though an sRGB texture format was selected.

Specifically, the rendering is different from Vulkan with the same texture format, but the _same_ as Vulkan when using `Bgra8UnormSrgb` (can't do a direct comparison due to adapter support).

**Repro steps**

Will try to repro with a `wgpu` example; wanted to report this as soon as I found it so y'all were aware.

**Expected vs observed behavior**

I expect the same color representation between the Vulkan and GL backends when using non-sRGB texture formats.

**Screenshots**

Vulkan w/ `Bgra8Unorm` (expected):

![image](https://github.com/gfx-rs/wgpu/assets/211194/2a5bd2bf-0390-49df-95c8-89887f13953f)

OpenGL w/ `Rgba8Unorm` (unexpected):

![image](https://github.com/gfx-rs/wgpu/assets/211194/14befa97-e87a-4174-8165-a4928987714c)

Vulkan w/ `Bgra8UnormSrgb`:

![image](https://github.com/gfx-rs/wgpu/assets/211194/7ac2f4ba-01d5-4465-80d4-6a7eb027dc08)

**Platform**

Linux $HOSTNAME 6.8.7-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 19 Apr 2024 09:51:31 +0000 x86_64 GNU/Linux

Adapters:

> IntegratedGpu: Intel(R) Graphics (RPL-P)
> Backend: Vulkan
> Driver: Intel open-source Mesa driver (Mesa 24.0.6-arch1.2)

> IntegratedGpu: Mesa Intel(R) Graphics (RPL-P)
> Backend: Gl
> Driver: OpenGL (4.6 (Compatibility Profile) Mesa 24.0.6-arch1.2)

rustc 1.76.0
`wgpu` 0.20.0
`winit` 0.30.0

**Comment by vorporeal** [comment]
I'm suspicious of the changes in https://github.com/gfx-rs/wgpu/pull/5482, where issues with sRGB were discussed during the review process.

**Comment by Wumpf** [comment]
@valaphee any chance you could have a look at this? :)

**Comment by valaphee** [comment]
Sure. (maybe I just should have copied the sRGB handling from wgl ^^')

For reproduction, you can simply set https://github.com/gfx-rs/wgpu/blob/trunk/examples/src/framework.rs#L13 `SRGB` to `false`, and it should use the non-sRGB view format.

**Comment by Wumpf** [comment]
* fixed in #5642
