### ISSUE TITLE
Segfault when dGPU is disabled on a multi-gpu device with HighPerformance preference set

### ISSUE THREAD

**Issue by darthdeus** [gfx-rs/wgpu#5650]
**Description**
Using `power_preference: wgpu::PowerPreference::HighPerformance` on a device with dual GPU where the laptop is set to use the integrated GPU still chooses the dGPU and leads to a crash.

**Repro steps**
Unfortunately, I can't provide a good repro here, other than `power_preference: wgpu::PowerPreference::HighPerformance`, I haven't observed this on my own machine, I've had two users report this and have them both confirm the crash goes away after either setting the laptop to dGPU, or `PowerPreference::None`

**Expected vs observed behavior**
wgpu should choose the available adapter

**Extra materials**
I understand this is highly sub-optimal, but, going to just provide what information I have:

- Logs provided by a user https://pastebin.com/BBGQ8Xcn, shows NVIDIA GPU being selected, also should note that the app has a panic handler that was verified to work in other error reports, but there's no panic in the log, and I confirmed that with two people, so I assume it's just some kind of segfault.
- Error report by the user https://steamcommunity.com/app/2331980/discussions/0/4348864737701979166/, where they confirm that after switching their laptop to use the NVIDIA GPU the crash stopped happening.
- Probably not important but patch in Comfy that we deployed that another user tested and confirmed that it fixed it for them once we changed the default to `PowerPreference::None` https://github.com/darthdeus/comfy/commit/cfebbb4914e405ac66afb284d9fe846fc50f56f8

**Platform**
- `wgpu: 0.19.3`
- Windows

I get that this is a suboptimal bug report, but considering it happened for two people, I'd imagine this probably isn't an edge case of a single computer, and should be reproducible on other dual GPU machines. I don't have one myself, so I can't really provide more info.

**Comment by Wumpf** [comment]
Very hard to diagnose without a callstack but there's plenty of dual gpu issues logged already (most of them Linux though), so might even be duplicate.
Worth noting that in 0.20 there's some bug fixes around surface creation in particular in the presence of several possible adapters that could be relevant. Might be worth upgrading once 0.20.1 is out (there were some new issues identified recently that warrant a timely 0.20.1 issue)

As much as I appreciate the detailed report given little few information there is, I'm going to close this since there's nothing actionable here. We know that at least some igpu+dgpu setups work so it's not like this gonna instantly repro on every such device. Also while the workaround implies a wgpu issues, the logs provided are technically not about that at all and look much more like regular operation.

Please re-open once there's something someone can latch onto and figure out a fix.

**Comment by darthdeus** [comment]
> We know that at least some igpu+dgpu setups work so it's not like this gonna instantly repro on every such device

I mean I understand I'm not giving exact hardware specifications, but more than one person managed to reproduce this consistently, both the crash before the change, and things working after `PowerPreference::None`. I'd imagine if anyone working on wgpu has a laptop with two GPUs they can probably repro this by just setting `PowerPreference::HighPerformance` and setting nvidia control panel to use the iGPU without much issues.

I have no stake in this issue, the problem is solved on my side, I'm only reporting so that others don't end up having their games crash on user devices without knowing why.

**Comment by Wumpf** [comment]
This should absolutely be re-opened if there's a reliable repro that someone can test against. But as it stands I'm not sure we could even reliably check if the issue has been fixed or not? I suppose it's a bit borderline - maybe you could contact the userbase and ask them to check an updated version of your game, but I reckoned that's impractical and you'd rather rely on the workaround you put in.

> I'd imagine if anyone working on wgpu has a laptop with two GPUs they can probably repro this by just setting PowerPreference::HighPerformance and setting nvidia control panel to use the iGPU without much issues.

wgpu's examples don't to that for instance.
Not that it matters much, I mean I'm not questioning whether an issue _exists_ :/. Just if there's anything actionable we need to add to the issue tracker beyond what's there. Admittedly I also didn't do an exhaustive search if we have anything here that matches it (I wouldn't be surprised though).
