### ISSUE TITLE
Timestamp query example returns absurdly large values

### ISSUE THREAD

**Issue by valaphee** [gfx-rs/wgpu#5660]
**Description**
The timestamp query example returns values which are way outside an acceptable value range. Both Vulkan and GL return similar large values, therefore I don't know if it could also be an issue with the example itself.

**Repro steps**
Running `cargo run --bin wgpu-examples -- timestamp_queries`

**Expected vs observed behavior**
More sane values.

**Extra materials**
```
cargo run --bin wgpu-examples -- timestamp_queries
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/wgpu-examples timestamp_queries`
Adapter supports timestamp queries.
Adapter supports timestamp queries within passes.
Raw timestamp buffer contents: [156289729554, 156289731758, 156289731042, 156289733254, 156289737042, 156289735586, 0, 0]
Elapsed time before render until after compute: 184467439174198208.00 μs
Elapsed time render pass: 184467440737095520.00 μs
Elapsed time first triangle: 14.96 μs
Elapsed time compute pass: 184467440737095488.00 μs
Elapsed time after first dispatch: 184467439174198176.00 μs
```

**Platform**
Adapter Vulkan AdapterInfo { name: "AMD Radeon RX 6900 XT (RADV NAVI21)", vendor: 4098, device: 29631, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.0.5-arch1.1", backend: Vulkan }

Arch Linux 6.8.5-arch1-1

**Comment by teoxoy** [comment]
This is probably related to https://github.com/gfx-rs/wgpu/issues/2521.
