### ISSUE TITLE
Reexports of wgpu-core and wgpu-hal make documentation search full of noise

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#5669]
**Repro steps**
1. Go to <https://docs.rs/wgpu/latest/wgpu/?search=render_pass>
2. Try to find the items relevant to actually using render passes.

**Expected vs observed behavior**
Formerly, this would be a reasonably short and useful list, containing

* `wgpu::CommandEncoder::begin_render_pass`
* `wgpu::RenderPass`

Now, it contains 40 results, 38 of which are from `wgpu_core` and `wgpu_hal`, therefore irrelevant to typical `wgpu` users, and the `wgpu` entries are not even sorted to the top.

I notice the re-exports have `#[doc(inline)]` on them. Perhaps removing that would fix this.

**Comment by cwfitzgerald** [comment]
Agree this is a problem - will see if removing the inline helps.

**Comment by valaphee** [comment]
Might have to do with https://github.com/rust-lang/rust/issues/124635 ?

**Comment by cwfitzgerald** [comment]
Yup, fixes it.
