### ISSUE TITLE
adapter.features() doesn't expose all features in wasm

### ISSUE THREAD

**Issue by munrocket** [gfx-rs/wgpu#5685]
**Description**
adapter.features() doesn't expose all features in WebAssembly

**Repro steps**
1) Create device with features
```rust
log::info!("adapter.limits = {:#?}", adapter.features()); // <-- not showing everything

let (device, queue) = adapter
  .request_device(
    &wgpu::DeviceDescriptor {
      label: Some("GPU Device"),
      features: adapter.features(), // <-- not allowing everything
      limits: wgpu::Limits::default(),
    },
    None,
  )
```
2) Create shader or API with feature
```wgsl
enable chromium_experimental_subgroups; 

@compute @workgroup_size(256)
fn main(@builtin(subgroup_invocation_id) sg_id : u32) {
   //...
}
```
3) Can't access to features that supported in adapter. Also can't access extensions by name. Can we register it somehow?

**Expected vs observed behavior**
It is not showing `chromium-experimental-subgroups` which can be fun to play with, also `float32-filterable`, `rg11b10ufloat-renderable`, `bgra8unorm-storage`, `chromium-experimental-timestamp-query-inside-passes`.

**Platform**
WebAssembly

**Comment by teoxoy** [comment]
I think only features from the spec will be present as we can't guarantee compatibility with `chromium-experimental` features.

`float32-filterable`, `rg11b10ufloat-renderable` and `bgra8unorm-storage` should work though.

https://github.com/gfx-rs/wgpu/blob/ca917449552f7e53aa2f918a59136a8baa3b12c3/wgpu/src/backend/webgpu.rs#L762-L773
