### ISSUE TITLE
Windows SDK requirement / Link Error 1181 for wgpu-native

### ISSUE THREAD

**Issue by Phaiax** [gfx-rs/wgpu#569]
Hello

Building wgpu-native v0.5 in windows gives 
```
error: linking with `link.exe` failed: exit code: 1181`
...
LINK : fatal error LNK1181: cannot open input file 'd3d12.lib'
```

(I do not have GLFW 3 installed and use the rust stable-msvc toolchain)

The solution was to install the Windows SDK (newest version 10.0.17763.0) via the Visual Studio installer (Change installation > single components > SDKs, .. > Windows 10 SDK).

Maybe that would be a good addition for the [Getting Started wiki page](https://github.com/gfx-rs/wgpu/wiki/Getting-Started#getting-started). And it seems nightly is not required anymore?

Best regards, Phaiax

**Comment by grovesNL** [comment]
Hi @Phaiax! GLFW3 should be required to run any of the examples which use it (like `triangle`).

I agree that it would be useful to add a note to Getting Started about using an updated Windows SDK when building wgpu-native on Windows.

Nightly is only required to run `cbindgen` so we could clarify this in the wiki.

**Comment by grovesNL** [comment]
I just updated https://github.com/gfx-rs/wgpu/wiki/Getting-Started, could you take a look and let me know if I've missed anything? Thank you :)

**Comment by cwfitzgerald** [comment]
Closing as this issue seems to have been solved.

**Comment by tommy-mor** [comment]
to other people who may be having this issue: I could not find d3d12.lib because it was linking against other versions of the apis in ``C:\Program Files (x86)\Windows Kits``, from windows 8. I deleted the old apis, reinstalled the windows 10 one (so the installer could update the path), and it worked.
