### ISSUE TITLE
Submitting multiple command encoders per frame causes hang on Vulkan

### ISSUE THREAD

**Issue by PWhiddy** [gfx-rs/wgpu#5693]
**Description**
Frames hanging for 5-10 seconds (presumably until timeout).
I bisected the issue and found it was introduced in #4967.

Possibly related to https://github.com/gfx-rs/wgpu/issues/5662

**Repro steps**
It only happens for me when submitting multiple command encoders with render passes in a single frame. 
I don't have a minimal reproduction yet, but I wanted to share in case anyone else has encountered the same issue. 

**Platform**
Ubuntu 22.04, nvidia 4090 - 535.86.10

**Comment by Wumpf** [comment]
@PWhiddy can you try on
* #5681

this specifically addresses Vulkan submission

**Comment by PWhiddy** [comment]
@Wumpf 
That did indeed fix it, thanks!

**Comment by ggadwa** [comment]
I posted an earlier issue on this: #5663

That'll be a duplicate now and can be closed.

**Comment by teoxoy** [comment]
@ggadwa so, #5681 fixes the issue you reported in #5663?

**Comment by ggadwa** [comment]
> @ggadwa so, #5681 fixes the issue you reported in #5663?

Yes!  Didn't do a lot of testing -- but before it would immediately freeze and with that branch it behaves as it always did.

**Comment by ggadwa** [comment]
Delete if too OT, but my game on steam that uses wgpu if you want to include it in your uses wpgu list (released in a couple days, uses the previous wgpu version for obvious reasons): https://store.steampowered.com/app/2933470/Atomite/

**Comment by cwfitzgerald** [comment]
Cool! We have a list over on https://github.com/gfx-rs/wgpu-rs.github.io if you want to add it it!
