### ISSUE TITLE
"ReadWrite is not available" error when using read_write storage textures in wasm build for WebGPU

### ISSUE THREAD

**Issue by Rakeshvcr** [gfx-rs/wgpu#5706]
In my wgpu application, I utilize storage textures with read_write access, which works as intended in native environments. However, when building for wasm and running on the web, I encounter an error stating "ReadWrite is not available". According to the [Chrome Developer Blog on WebGPU updates](https://developer.chrome.com/blog/new-in-webgpu-124), Chrome 124 now supports read_write storage textures. I'm seeking guidance on adapting my wgpu code to support this functionality on the web.

**Comment by teoxoy** [comment]
As of https://github.com/gfx-rs/wgpu/pull/5434, this should work. Are you on the latest wgpu version?

**Comment by Rakeshvcr** [comment]
I'm using 0.19.4v, I'll check with the latest version. Thank you.

**Comment by Rakeshvcr** [comment]
After updating to the latest version, I'm getting this issue. 
TextureFormat::RGBA32Float does not support storage texture access StorageTextureAccess::ReadWrite

I tried changing my TextureFormat type to RGBA16Float but still got the same error.

**Comment by teoxoy** [comment]
Closing, as this was answered in https://github.com/gpuweb/gpuweb/discussions/4651.
