### ISSUE TITLE
wgpu does not map all OutOfMemory errors to wgpu::Error::OutOfMemory

### ISSUE THREAD

**Issue by sagudev** [gfx-rs/wgpu#5718]
Here https://github.com/gfx-rs/wgpu/blob/18b758e3889bdd6ffa769085de15e2b96a0c1eb5/wgpu/src/backend/wgpu_core.rs#L286 only `wgc::device::DeviceError::OutOfMemory` error is mapped to `wgpu::Error::OutOfMemory`, while https://docs.rs/wgpu/latest/wgpu/?search=OutOfMemory lists more way `OutOfMemory` variants.

**Comment by ErichDonGubler** [comment]
The problem statement here is pretty vague. It's unclear what action items should result from this. Is there a concrete test case or application in which you've found this results in issues? I don't doubt there _are_ issues, but we should try to make this as easy for contributors to act upon as we can.

**Comment by sagudev** [comment]
> The problem statement here is pretty vague. It's unclear what action items should result from this. Is there a concrete test case or application in which you've found this results in issues? I don't doubt there _are_ issues, but we should try to make this as easy for contributors to act upon as we can.

I noticed this in when using similar error mapping code in servo, but it didn't catch all OOM errors. IIRC create_texture returned such error.

**Comment by sagudev** [comment]
related https://github.com/gfx-rs/wgpu/pull/6547

**Comment by teoxoy** [comment]
I think this has been resolved with a combination of mapping all OOMs in hal to `hal::DeviceError::OutOfMemory` + removing all other unused wgpu-core OOM variants (#6550).
