### ISSUE TITLE
`Features::SHADER_INT64` enables 64-bit atomic types

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#5735]
When Vulkan sets `VkPhysicalDeviceFeatures::shaderInt64`, wgpu offers `Features::SHADER_INT64`, which, if enabled, causes Naga to permit 64-bit atomic types, even though those are covered by the separate `VkPhysicalDeviceVulkan12Features::shaderSharedInt64Atomics` and `shaderBufferInt64Atomics` features.

This seems to be fixed by #5383.

**Comment by teoxoy** [comment]
I don't think that's the case.

https://github.com/gfx-rs/wgpu/blob/aaefc7c10dabeed7aaa5ef614735bc15c4cc46cf/naga/src/valid/type.rs#L362

**Comment by jimblandy** [comment]
Okay, I see. I was only looking at the validation of `Statement::Atomic` and `Expression::AtomicResult`. But `validate_atomic` does verify that `Statement::Atomic::pointer` is a pointer to an atomic type, so the validation of the type itself effectively covers the statements.

This means that the call to `Validator::check_width` when validating `Expression::AtomicResult` is redundant - but #5742 covers that and more.
