### ISSUE TITLE
Unable to render a simple mesh for certain grayscale texture formats

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu#575]
Hi!

First off, thanks for all the great work on this project! I've just updated wgpu-py to use v0.5.1 and it's really nice to see how things are evolving and getting more and more inline with WebGPU :)

In wgpu-py we have some [tests](https://github.com/almarklein/wgpu-py/blob/master/tests/test_rs_render_tex.py) that render a yellow square (with a bit of a gradient) using a 2x2 texture. The rendered-result is always the same, but we test it multiple times, using different texture formats.

These all work fine:
* RGBA: rgba8unorm, rgba8uint, rgba16sint, rgba32float
* RG: rg8unorm, rg8uint, rg16sint, rg32float, 
* R: r8unorm, r8uint

But these fail:
* R: r16sint, r32sint, r32float

Some notes:
  * I'm on Windows 10 using Vulkan. The behavior is the same whether for NVidia/integrated graphics.
  * Also tried on Linux (same machine). Same behavior on NVidia. BUT ... it does work with integrated graphics.
  * Using 0.5.1 / master.
  * These tests share a lot of code, so it can hardly be a typo.
  * We have some [similar tests](https://github.com/almarklein/wgpu-py/blob/master/tests/test_rs_compute_tex.py) that does a similar iteration over the same formats, but doing a bit of compute. In this case it works fine on all formats.
  * RenderDoc does not give warnings. (it actually did give a warning for one of the formats for which it *does* work, not sure if this is relevant).
  * The RenderDoc status looks fine as far as I can tell. The texture does have content and seems to be bound correctly.

Any ideas? Or is there an example somewhere that uses texture mapping with r16sint, r32sint or r32float?

This is not a stopper for us right now, but eventually these texture formats will be important to load up medical image data (e.g. CT is typically single-channel 16 bit).

**Comment by kvark** [comment]
Thank you for filing this! Things we could do:
  - sharing a few RenderDoc captures with us (e.g. by attaching here or sending me via Firefox Send)
  - explaining how to run your tests locally
  - making sure `env_logger` is initialized to see Vulkan validation messages

**Comment by almarklein** [comment]
So I did some more testing. On Linux, with integrated graphics, which are supposedly incomplete, it surprisingly *does* work ... not sure how to interpret that.

Here are some RenderDoc captures:
* [tex_r8unorm.rdc](https://www.dropbox.com/s/shw9nkskhnfrt8n/tex_r8unorm.rdc?dl=1) Works fine.
* [tex_r16sint.rdc](https://www.dropbox.com/s/1kdgvruchjp33h6/tex_r16sint.rdc?dl=1) Works fine.
* [tex_rg16sint.rdc](https://www.dropbox.com/s/dd8a4kbt6sbj760/tex_rg16sint.rdc?dl=1) Black output.

I can explain how to run the tests locally, but I'd probably do a release first and prep a file that's easier to work with.

Is RenderDoc supposed to capture all validation errors, also if `env_logger` is not set up?

Is there an existing example in wgpy-native or wgpu-rs that can easily be modified to use any of these texture formats?

**Comment by kvark** [comment]
> Is RenderDoc supposed to capture all validation errors, also if env_logger is not set up?

evn_logger just outputs the log to the console, it technically has no direct relation to validation. We unconditionally enable validation in Debug builds, but the layers have to be set up in the system. RenderDoc would report all the same errors as our log.

> Is there an existing example in wgpy-native or wgpu-rs that can easily be modified to use any of these texture formats?

The Cube example from wgpu-rs could easily be modified to use a different format.

**Comment by almarklein** [comment]
> The Cube example from wgpu-rs could easily be modified to use a different format.

Ok, I'll have a stab at that.

> [...] but the layers have to be set up in the system.

What does this mean? That the Lunar SDK must be installed? Or do we need to do some more calls in Rust? :)

**Comment by kvark** [comment]
Yes, LunarG SDK has the validation layers, and it just needs to be installed in the system.

**Comment by kvark** [comment]
Sadly, none of my machines are able to open these renderdoc captures. We'll have to find a good repro case.

**Comment by almarklein** [comment]
With a few changes to the [cube example](https://github.com/gfx-rs/wgpu-rs/blob/master/examples/cube/main.rs) ... changing the texture format to `wgpu::TextureFormat::R16Sint`.
```
and the corresponding fragment shader:
```glsl
#version 450

layout(location = 0) in vec2 v_TexCoord;
layout(location = 0) out vec4 o_Target;
layout(set = 0, binding = 1) uniform itexture2D t_Color;
layout(set = 0, binding = 2) uniform sampler s_Color;

void main() {
    ivec4 itex = texture(isampler2D(t_Color, s_Color), v_TexCoord);
    vec4 tex = vec4(itex) / 255.0;
    float mag = length(v_TexCoord-vec2(0.5));
    o_Target = mix(tex, vec4(0.0), mag*mag);
}
```
R16 and R32 seem to work just fine:

![afbeelding](https://user-images.githubusercontent.com/3015475/79272380-a6b5fb00-7ea1-11ea-9a1c-3e50de3032c0.png)

So this is starting to look like an issue on our side.

**Comment by almarklein** [comment]
Ok, I finally managed to trace the issue down:

It's this line (in Rust):
```rust
let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
          ...
            compare: wgpu::CompareFunction::Undefined,
        });
```

I was using "never" for the compare function. I think I picked that from another example somewhere. When I set it to zero/undefined, all our tests that previously would fail now work! So, hooray!

Now I'm left with two questions. First, the WebGPU spec does not have `CompareFunction.undefined`. Shouldn't it have it too? (In wgpu-py we're following WebGPU for our user-facing API, so our enums are the same (strings) as in JS. Fortunately we can also pass an integer as a workaround for now.)

Second, my understanding was that the `compare` arg applied only to depth textures. What is it's meaning for normal texture sampling? And is there an explanation why using "never" worked for most texture formats, but not for a few grayscale ones?

**Comment by kvark** [comment]
Great that you figured this out! Your experience makes sense, I filed #588 to follow up with validation on that front.

>  First, the WebGPU spec does not have CompareFunction.undefined. Shouldn't it have it too? 

The `compare` field is optional (nullable) in the [spec](https://gpuweb.github.io/gpuweb/#dictdef-gpusamplerdescriptor). Null corresponds to our Undefined.

> What is it's meaning for normal texture sampling?

I don't remember out of my head if you could use comparison sampling with non-depth, need to double-check that.

> And is there an explanation why using "never" worked for most texture formats, but not for a few grayscale ones?

I think you just hit an undefined behavior that wasn't validated by Vulkan validation even. Your sampler was a comparison one, but the shader binding was a non-comparison, so there was a mismatch nobody expected.

**Comment by almarklein** [comment]
Thanks for the explanations!

> The compare field is optional (nullable) in the spec. Null corresponds to our Undefined.

Aah, now I also see my mistake. At some point I started assuming that any value that does not have a default value (in IDL) is required. I guess this is because this is how Python usually works :)
