### ISSUE TITLE
Crash on vulkan when multiple command encoders are used after #5681.

### ISSUE THREAD

**Issue by Elabajaba** [gfx-rs/wgpu#5774]
**Description**
Since https://github.com/gfx-rs/wgpu/pull/5681, wgpu now crashes with "More than one surface texture is being used from the same swapchain. This will cause a deadlock in release." if more than 1 command encoder (with a renderpass that has a texture view of your `Surface` texture) is used.

**Repro steps**
Create and submit a 2nd command encoder with a renderpass that uses a view of your surface texture (can create a new texture view or just re-use an existing one) when running on Vulkan.
Run https://github.com/Elabajaba/wgpu-vk-surface-crash

**Expected vs observed behavior**
Expected: Doesn't crash
Observed: 
```
thread 'main' panicked at E:\temp\wgpu\wgpu-hal\src\vulkan\mod.rs:966:9:
More than one surface texture is being used from the same swapchain. This will cause a deadlock in release.
```

**Platform**
Happens on both Windows 11 + AMD gpu and Linux+Mesa RADV (amd) + Wayland.

**Comment by ErichDonGubler** [comment]
@cwfitzgerald indicated he was investigating this last week.

**Comment by cwfitzgerald** [comment]
We know the problem, just need to solve it:

If multiple command buffers are involved, the surface texture gets added to the surface texture list in hal::Queue::submit more than once, which is a violation of hal's contract.
