### ISSUE TITLE
Vertexes start jittering when far from origin

### ISSUE THREAD

**Issue by Khalzz** [gfx-rs/wgpu#5783]
Im making a game with WGPU, the thing is that when im far from the origin (0,0,0) some vertexes start jittering randomly, is there a reason of why this happens, and is there someone who had this same problem?.

The code is done with wgpu v0.18.0 and SDL2 v0.36.0

The code is here: https://github.com/Khalzz/Project-Skies

https://github.com/gfx-rs/wgpu/assets/63627567/d2c1106b-c0f0-4085-a071-6d25f0f337c1

**Comment by Wumpf** [comment]
You're running into floating point inaccuracies, this is to be expected when numbers get too large or too small. Vertex processing is always done with 32bit floats so at a certain point things start breaking down.
Large open world games avoid this usually by having some underlying double precision or integer chunk coordinate system into in which things are expressed on the cpu side such that camera & gpu world space are inside a more managable floating point range. The important part really is that your world/view/projection math doesn't blow up.
