### ISSUE TITLE
Should error when shader has multiple group-bindings with the same values

### ISSUE THREAD

**Issue by stefnotch** [gfx-rs/wgpu#5787]
**Description**

When I write a shader like
```
@group(0) @binding(0)
var<storage,read_write> foo: array<u32>;
        
@group(0) @binding(0)
var<storage,read_write> bar: array<u32>;
```
then I would expect that to result in an error. After all, the WGSL specification says
> Two different resource variables in a [shader](https://www.w3.org/TR/WGSL/#shader) [must not](https://www.w3.org/TR/WGSL/#shader-creation-error) have the same [group](https://www.w3.org/TR/WGSL/#attribute-group) and [binding](https://www.w3.org/TR/WGSL/#attribute-binding) values, when considered as a pair.
> https://www.w3.org/TR/WGSL/#resource-interface

**Repro steps**
The shader above.

**Expected vs observed behavior**
I expect a shader creation error. The actual behaviour is that naga happily accepts this.

Amusingly, Chrome also seems to accept it. (At least the version of Microsoft Edge that I tested does accept this.)

**Platform**
- Windows 11
- WGSL trunk on commit 583cc6ab04796b8ab29a84920ff5bd42d9736e7a (one of the latest commits)

**Comment by stefnotch** [comment]
(Yes I was trying out all the forbidden edge cases while writing unit tests for my https://github.com/gfx-rs/wgpu/issues/5713 😆 )

**Comment by teoxoy** [comment]
> The resource interface of a shader is the set of module-scope resource variables [statically accessed](https://www.w3.org/TR/WGSL/#statically-accessed) by [functions in the shader stage](https://www.w3.org/TR/WGSL/#functions-in-a-shader-stage).

Could you try to add an entry-point using those 2 bindings and see if it still works?

**Comment by stefnotch** [comment]
Ah, I clearly didn't read the spec properly. Yes, it works as expected when one uses the bindings

`naga/tests/wgsl_errors.rs`
```rust
#[test]
fn duplicated_group_binding() {
    check_validation! {
        "@group(0) @binding(0)
        var<storage,read_write> foo: array<f32>;
                
        @group(0) @binding(0)
        var<storage,read_write> bar: array<f32>;
        
        @vertex
        fn main() -> @builtin(position) vec4<f32> {
            let a = foo[0];
            let b = bar[0];
            return vec4<f32>(a, b, 0.0, 1.0);
        }":
        Err(naga::valid::ValidationError::EntryPoint {
            stage: naga::ShaderStage::Vertex,
            source: naga::valid::EntryPointError::BindingCollision(..),
            ..
        })
    }
}
```

And there are also tests in the official testing suite
https://github.com/gpuweb/cts/blob/b0f5b1839f40f8f793ec2e4a6eecae41a273e0b3/src/webgpu/shader/validation/shader_io/group_and_binding.spec.ts#L135-L138

So I can safely close this.
