### ISSUE TITLE
Keep pipeline layouts alive

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#580]
We currently allow the user to drop them. However, pipelines still need to consider their layouts when used, same goes for bind group layouts. The difference, I suppose, is that bind group layout IDs are not accessed ever, just compared.

Perhaps, we could get away by simply storing the contents of pipeline layouts within our pipelines?

**Comment by grovesNL** [comment]
> The difference, I suppose, is that bind group layout IDs are not accessed ever, just compared.

Won't this change once we fix #335?

**Comment by kvark** [comment]
@grovesNL it depends... We may implement it as bind groups are created separately and compared by value. OR, we can track bind group layouts in the same style as we do pipeline layouts, and just return a reference to an existing object when the user *creates* a new one. This second choice seems better to me, on the surface.
