### ISSUE TITLE
Validation error regression when loading GLB model

### ISSUE THREAD

**Issue by IDEDARY** [gfx-rs/wgpu#5852]
**Description**
Validation error regression from WGPU `0.19.3` (Bevy 0.13.2) to `0.20` (Bevy 0.14.0-rc.3) when loading GLB model.
The error was fixed by importing the downloaded model into Blender and re-exporting it. But I figured I would still report this as this is a regression, because previous version was able to load it.

```
2024-06-20T14:43:01.620729Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (1)' panicked at /home/dominik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `morphed_skinned_mesh_bind_group`
    Number of bindings in bind group descriptor (4) does not match the number of bindings defined in the bind group layout (6)


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_pbr::render::mesh::prepare_mesh_bind_group`!
```

**Repro steps**
Reproducible app:
[reproducible.zip](https://github.com/user-attachments/files/15916066/reproducible.zip)

**Extra materials**
The model that crashes after update: 
[female1.zip](https://github.com/user-attachments/files/15915870/female1.zip)

**Platform**
Linux mint, NVIDIA, Vulkan, Bevy 0.14.0-rc.3

**Comment by cwfitzgerald** [comment]
This is an issue that should be reported to bevy instead of wgpu.
