### ISSUE TITLE
Properly configure the memory allocators

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#5869]
The vulkan backend uses the `gpu-alloc` crate and [sets the memory allocator to the `i_am_prototyping` configuration](https://source.chromium.org/chromium/chromium/src/+/main:third_party/dawn/src/dawn/native/vulkan/ResourceMemoryAllocatorVk.cpp) which is explicitly not meant to make it to production. The starting device memory chunk size for that config is 8 MiB and doubles every time a new chunk must be allocated.

The d3d12 backend uses the default settings provided by `gpu-allocator` (different crate), which is fixed 256 MiB memory chunks for device memory and 64 MiB for host memory. 256 MiB appears to also be the default size for VMA.

For reference, it looks like Dawn uses a fixed memory chunk size of 8MiB with a buddy allocator.

I think that wgpu should expose this configuration to the outside while providing some reasonable defaults. Firefox (which may create many devices at the same time) will want much smaller chunk sizes by default than a typical big game.

**Comment by teoxoy** [comment]
Closing since https://github.com/gfx-rs/wgpu/pull/5875 landed.
