### ISSUE TITLE
Window surface texture bleeds out of the Windows 11 window borders

### ISSUE THREAD

**Issue by SKPG-Tech** [gfx-rs/wgpu#5877]
**Description**
The surface texture seems to be bleeding out of the window borders

**Repro steps**
Be on Windows 11. Simply keep resizing the window, happens with the hello triangle example. Mostly occurs when there is a window behind it as well.

**Expected vs observed behavior**
Observed: The corners on Windows 11 are rounded, and it is possible to sometimes see the surface texture bleed out and show over the rounded border.
Expected: The surface doesn't bleed out from the inside of the window.

**Extra materials**
Observed:
<img src="https://github.com/gfx-rs/wgpu/assets/42890752/75481c40-a685-41a2-9688-987180973291" width="400" >
<img src="https://github.com/gfx-rs/wgpu/assets/42890752/c6d1ab4c-d95b-4a41-9060-37cc2bc5e935" width="400">
Expected:
<img src="https://github.com/gfx-rs/wgpu/assets/42890752/5223e30f-e398-4832-8395-700c446bd279" width="400">

**Platform**
Windows 11 23H2
git cloned repository from the trunk branch at e92e543

**Comment by Wumpf** [comment]
doesn't repro for me. Anything particular you did other than resizing? In any case it's likely this would be a `winit` bug then
![image](https://github.com/gfx-rs/wgpu/assets/1220815/32d91749-b559-4efc-bab9-e35d42d22258)

**Comment by SKPG-Tech** [comment]
Hmm, no. Just resizing should do it 😕

**Comment by teoxoy** [comment]
I've seen this issue with other apps on W11. I don't think it's a wgpu issue since the rounded corners are implemented in the compositor.

**Comment by SKPG-Tech** [comment]
Interesting.
I apologize for my ignorance, but I haven't noticed that with other apps. Perhaps it is a Windows 11 bug. In that case, should I close this issue?

**Comment by Wumpf** [comment]
Yeah I think in any case there's nothing we can do on the wgpu side here.
