### ISSUE TITLE
Validate comparison property of samplers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#588]
To start, when a bind group is created, we need to check that a comparison sampler is provided where it's expected.

**Comment by GabrielMajeri** [comment]
This should be implemented in `device_create_bind_group`, right?
https://github.com/gfx-rs/wgpu/blob/a02a56684114da702a64e30af49d0167e273402b/wgpu-core/src/device/mod.rs#L1396-L1401
And panic if it's invalid.

**Comment by kvark** [comment]
Yes, the check would go into `device_create_bind_group`, but we really need to convert it to return Err() instead of panicking. See how `create_compute_pipeline` does it, for example.
