### ISSUE TITLE
Check for conflicting bind group usages inside compute passes

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#589]
We are currently treating each individual operation in a compute pass as a separate scope, and we insert appropriate transitions right as `set_bind_group` is called. The problem is that we aren't properly detecting a case where different bind groups use the same resource mutably: we'd just transition it to the first usage, then to the second, and not issue an error. A similar problem is having different read-only usages that we don't end up combining.

A lazy solution would be to defer any transitions up until `dispatch()`, where we'd combine together all the bind group usages and try to transition into them. Historically, we were very careful to avoid this laziness in our implementations down to gfx-rs backends.

**Comment by cwfitzgerald** [comment]
This should have been solved by validation unification.
