### ISSUE TITLE
Building a new Fullscreen exclusive window on Windows creates undesirable visual artifacts.

### ISSUE THREAD

**Issue by antonmarsden** [gfx-rs/wgpu#592]
When creating a Window (on Windows) as per below, I notice that a smaller (non-exclusive) window seems to appear, then the window seems to expand into a fullscreen state. Similarly, shutting down the app causes a similar visual artifact (in reverse).

```
    WindowBuilder::new()
        .with_title(title)
        .with_fullscreen(Some(Fullscreen::Exclusive(videoMode)));
```
There is a workaround for this, but ideally the library should Just Work, and work pretty well :)  The workaround is to add:
```
   .with_visible(false)
```
to the WindowBuilder, then call:
```
 window.set_visible(true)
```

Similarly, when shutting down the app, use window.set_visible(false) before exiting.

**Comment by antonmarsden** [comment]
Wrong project!

**Comment by kvark** [comment]
You can move the issues between projects, I think.
