### ISSUE TITLE
[glsl-in] Parent device is lost in for loop with uniform

### ISSUE THREAD

**Issue by Vipitis** [gfx-rs/wgpu#5926]
**Description**
I came across a really odd case. This is with wgpu-native 0.19.4.1 so it might already be fixed, but couldn't find any relevant closed issues/PRs.

**Repro steps**
`iTime` is a float uniform that starts at zero and then increments to keep track of the runtime. it gets passed via a uniform buffer.

```glsl
for (float i = 0.5; i < 3.0; i += iTime) {
   continue;
}
```

This means the initial frame is 0.0 so this for loop would be infinite. We get an error here (related to surface?)
```sh
thread '<unnamed>' panicked at src\lib.rs:586:5:
Error in wgpuQueueSubmit: Validation Error

Caused by:
    Parent device is lost

```

**Expected vs observed behavior**
incrementing by a negative numbers causes the same crash.
incrementing by 0.0 does not crash (although this is equal to the evaluation where `iTime` is 0.0) - it's also an infinite loop that maybe gets compiled away.
incrementing by a positive number works just fine as expected.

Where does such a situation actually happen? I came across [this Shadertoy](https://www.shadertoy.com/view/ttcXD2) that uses such a variable for a motion blur implementation. When running it through [wgpu-shadertoy](https://github.com/pygfx/shadertoy) I get such a panic. Changing the `<=` to a `<` in L101 avoids this issue. I reduced it to the example above.
I think a validation error regarding the infinite loop would be preferred over this panic.

**Platform**
**wgpu-native 0.19.4.1** in wgpu-py@main

**Comment by teoxoy** [comment]
I think this is to be expected, if a shader takes too long to run it can cause device loss.

> I think a validation error regarding the infinite loop would be preferred over this panic.

If `iTime` is coming from an uniform buffer, we can't easily tell that this is an infinite loop for sure.

You should register a handler with `.on_uncaptured_error()` to avoid the panic.
