### ISSUE TITLE
Buffer leaks

### ISSUE THREAD

**Issue by xiaopengli89** [gfx-rs/wgpu#5940]
**Description**
Memory leaks when creating and writing buffers.

**Repro steps**
```rust
use std::{thread, time::Duration};

async fn run() {
    let ins = wgpu::Instance::new(wgpu::InstanceDescriptor {
        backends: wgpu::Backends::DX12,
        ..Default::default()
    });
    let adp = ins
        .request_adapter(&wgpu::RequestAdapterOptions::default())
        .await
        .unwrap();
    let info = adp.get_info();
    println!("Using {} ({} {})", info.name, info.backend, info.driver);
    let (dev, que) = adp
        .request_device(
            &wgpu::DeviceDescriptor {
                memory_hints: wgpu::MemoryHints::MemoryUsage,
                ..Default::default()
            },
            None,
        )
        .await
        .unwrap();
    let buf_src = vec![255u8; 4 << 10];
    loop {
        let buf = dev.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: 4 << 10,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::UNIFORM,
            mapped_at_creation: false,
        });
        que.write_buffer(&buf, 0, &buf_src);
        dev.poll(wgpu::Maintain::Wait);
        que.submit(None);
        thread::sleep(Duration::from_secs_f32(1. / 60.));
    }
}
pub fn main() {
    pollster::block_on(run());
}
```

**Extra materials**
<img width="1012" alt="image" src="https://github.com/gfx-rs/wgpu/assets/11287532/0b3df592-4f79-4e77-96e4-29a74cd25bd8">
![img_v3_02cm_0f3a2369-5a8c-4abc-bc40-6601fb55a78g](https://github.com/gfx-rs/wgpu/assets/11287532/b8171e9c-ab52-4396-8a32-68403692e97d)

**Platform**
Windows 10, wgpu@ef0ce05d3a6ffae396c3335d71ef76069a2d480d

**Comment by teoxoy** [comment]
Are the `StagingBuffer`s not getting destroyed? Or both the `Buffer`s and the `StagingBuffer`s?

**Comment by teoxoy** [comment]
The issue might also be that we don't unmap the staging buffer once we are done with it

https://github.com/gfx-rs/wgpu/blob/9796766e8e08bd81254b4dbfa83193f8e8a426e1/wgpu-core/src/resource.rs#L673-L679

We could call `.flush()` on it like in all the other places

https://github.com/gfx-rs/wgpu/blob/9796766e8e08bd81254b4dbfa83193f8e8a426e1/wgpu-core/src/device/queue.rs#L342-L353

**Comment by xiaopengli89** [comment]
> Are the `StagingBuffer`s not getting destroyed? Or both the `Buffer`s and the `StagingBuffer`s?

It all seems to have leaked.

> The issue might also be that we don't unmap the staging buffer once we are done with it

If we drop the resource before free suballocation, the leak is gone, which maybe cause by internal mechanism of `gpu-allocator`.
