### ISSUE TITLE
Surface with only texture usage `COPY_DST` attempts to create a `VkImageView`

### ISSUE THREAD

**Issue by pengiie** [gfx-rs/wgpu#5951]
**Description**
When creating a Surface with the only texture usage being `COPY_DST` with the vulkan backend, an image view is still attempted to be made with `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT` which causes a validation error.

**Repro steps**
```rust
surface.configure(&device, &wgpu::SurfaceConfiguration {
    usage: wgpu::TextureUsages::COPY_DST,
    view_formats: vec![],
    ...
});
```

**Expected vs observed behavior**
When the surface textures are created with just `COPY_DST`, I expect a VkImageView not to be created since there is no reason to due to the only VkImageUsage being `VK_IMAGE_USAGE_TRANSFER_DST_BIT`.

What actually happens is the image view is attempted to be created with the `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT` even though I didn't set `wgpu::TextureUsages::RENDER_ATTACHMENT`.

**Extra materials**
Vulkan validation errors:
```
[2024-07-13T19:08:13Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkImageViewCreateInfo-image-04441 (0xb75da543)]
    	Validation Error: [ VUID-VkImageViewCreateInfo-image-04441 ] Object 0: handle = 0xcfef35000000000a, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xb75da543 | vkCreateImageView(): pCreateInfo->image (VkImage 0xcfef35000000000a[]) was created with VK_IMAGE_USAGE_TRANSFER_DST_BIT but requires VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_STORAGE_BIT|VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT|VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT|VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT|VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR|VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT|VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR|VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR|VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR|VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR|VK_IMAGE_USAGE_SAMPLE_WEIGHT_BIT_QCOM|VK_IMAGE_USAGE_SAMPLE_BLOCK_MATCH_BIT_QCOM. The Vulkan spec states: image must have been created with a usage value containing at least one of the usages defined in the valid image usage list for image views (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-image-04441)
[2024-07-13T19:08:13Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: IMAGE, hndl: 0xcfef35000000000a, name: ?)
[2024-07-13T19:08:13Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkImageViewCreateInfo-pNext-02662 (0xfcaee507)]
    	Validation Error: [ VUID-VkImageViewCreateInfo-pNext-02662 ] Object 0: handle = 0xcfef35000000000a, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xfcaee507 | vkCreateImageView(): pCreateInfo->pNext<VkImageViewUsageCreateInfo>.usage (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) must not include any bits that were not set in VkImageCreateInfo::usage (VK_IMAGE_USAGE_TRANSFER_DST_BIT) of the image. The Vulkan spec states: If the pNext chain includes a VkImageViewUsageCreateInfo structure, and image was not created with a VkImageStencilUsageCreateInfo structure included in the pNext chain of VkImageCreateInfo, its usage member must not include any bits that were not set in the usage member of the VkImageCreateInfo structure used to create image (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-pNext-02662)
[2024-07-13T19:08:13Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: IMAGE, hndl: 0xcfef35000000000a, name: ?)
```

**Platform**
wgpu v0.20.1
NixOS 24.05 using Vulkan
Nvidia drivers 555.42.02

**Comment by pengiie** [comment]
When I was searching around for if there was limitations for what usages surfaces can be made with I didn't check the docs (my bad), https://docs.rs/wgpu/latest/wgpu/type.SurfaceConfiguration.html. I see now that only `RENDER_ATTACHMENT` is supported.

**Comment by cwfitzgerald** [comment]
We should be validating this

**Comment by casey** [comment]
I think I just ran into this as well. On MacOS, I was able to configure the surface with `COPY_DST`, and then `copy_texture_to_texture` to write to it, which worked, but I gather from this comment I shouldn't be able to:

```rust
pub struct SurfaceConfiguration<V> {
    /// The usage of the swap chain. The only supported usage is `RENDER_ATTACHMENT`.
    pub usage: TextureUsages,
    …
}
```

**Comment by casey** [comment]
Could `usage` just be removed from `SurfaceConfiguration`, if it isn't configurable?

**Comment by casey** [comment]
Actually, maybe I'm confused about this. The comment seems to imply that only `RENDER_ATTACHMENT` is supported.

However, when I get the surface capabilities, they include COPY_DST:

```rust
let capabilities = surface.get_capabilities(&adapter);
assert!(capabilities.usages.contains(TextureUsages::COPY_DST));
````

Is the comment accurate that only `RENDER_ATTACHMENT` is supported? Or is it perhaps that only `RENDER_ATTACHMENT` is *guaranteed* to be supported?

**Comment by Wumpf** [comment]
@casey the comment was wrong, I actually also run into this a couple of days myself and fixed it https://github.com/gfx-rs/wgpu/pull/6668

The story is that ....
* on WebGPU more usages should be configurable but are not, see https://github.com/gfx-rs/wgpu/issues/6667
* on native it depends....
    * WebGL/GLES/OpenGL we only allow `RENDER_ATTACHMENT`, not sure if that's corrcet but I wage that's the safe option anyways
    * Vulkan it is runtime dependent
    * DX12 has copy src/dst as well
    * Metal has copy src/dst as well, but the Metal docs hint that there might be a perf penalty - guess that's something I should have put into the comment as well 🤔

**Comment by Wumpf** [comment]
~The actual error described in the issue desc was fixed here:~
~* https://github.com/gfx-rs/wgpu/pull/6007~

misread, the validation was added in some other PR that I can't find now (hidden behind code refactor), but unless I'm missing something this validates it:
https://github.com/gfx-rs/wgpu/blob/trunk/wgpu-core/src/device/global.rs#L1787
