### ISSUE TITLE
Halmark demo broken / only shows a blue screen

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#5965]
Nothing but clear color in it. Doesn't seem to be backend specific

**Comment by teoxoy** [comment]
It seems it only does something if you press space

https://github.com/gfx-rs/wgpu/blob/a3d2d31d3d9db6098d7842d2d76cd70e54fd12b0/wgpu-hal/examples/halmark/main.rs#L591-L593

A `println!` saying that at startup would have helped 😅.
