### ISSUE TITLE
wgpu-core docs fail to build.

### ISSUE THREAD

**Issue by andriyDev** [gfx-rs/wgpu#5990]
docs.rs fails to build the [wgpu-core docs](https://docs.rs/crate/wgpu-core/latest).

I am also trying to run `cargo doc` on a project of mine that uses wgpu-core, and it just hangs. It's sat here for >5m seemingly chewing up a whole core worth of performance in `rustdoc`. To be clear, it is not taking that long to document the whole lib. It is **just** sitting on `wgpu-core` trying to document it.

**Comment by Wumpf** [comment]
There's an upstream issue in cargo doc for this. Closing this as duplicate since already covered by
* https://github.com/gfx-rs/wgpu/issues/4905
