### ISSUE TITLE
Some bindgroups do not get deduplicated

### ISSUE THREAD

**Issue by sagudev** [gfx-rs/wgpu#6037]
**Description**
Discovered in https://github.com/gfx-rs/wgpu/pull/6012#issuecomment-2243511956, sometimes (compatible) bindgroups with same content are not deduplicated, therefore not detected as equal (I suspect the problem originates from layouts that come from `getBindGroupLayout`).

**Repro steps**
Repro is here: https://github.com/sagudev/wgpu-problem/tree/another-empty-bind-panic-2. This is [`webgpu:api,validation,encoding,programmable,pipeline_bind_group_compat:default_bind_group_layouts_never_match,render_pass:pipelineType="auto0";bindingType="auto0";swap=true;empty=false;renderCommand="draw"`](https://gpuweb.github.io/cts/standalone/?q=webgpu:api,validation,encoding,programmable,pipeline_bind_group_compat:default_bind_group_layouts_never_match,render_pass:pipelineType=%22auto0%22;bindingType=%22auto0%22;swap=true;empty=false;renderCommand=%22draw%22) but rewritten in rust (and to wgpu).

**Expected vs observed behavior**
Per CTS there should actually be no error (bind groups are the same in content): https://github.com/gpuweb/cts/blob/198d1770062c1a8aba86e7d6e001bb47bea028ee/src/webgpu/api/validation/encoding/programmable/pipeline_bind_group_compat.spec.ts#L960

When this is done it should be safe to revert https://github.com/gfx-rs/wgpu/pull/6012/commits/60b42f97dd679a5c45e7d871d062b7652eaeecd7 (ping me for CTS run on servo)

**Comment by teoxoy** [comment]
It turns out that we are not deduplicating derived BGLs at all.

**Comment by sagudev** [comment]
Why exactly BGL needs to work using deduplication, can't we just operate with duplicated bindgrops and check for compat by content, to me it seems like a big footgun.

**Comment by teoxoy** [comment]
I'm not sure that the underlying APIs allow that. I tried reducing potential misuse (forgetting to deduplicate) but it didn't work out since the other code-path that creates BGLs is quite different.
