### ISSUE TITLE
Queue::write_buffer seems to resize the buffer in question (?)

### ISSUE THREAD

**Issue by 9SMTM6** [gfx-rs/wgpu#6072]
I'm really not sure whats going in here, probably I'm misunderstanding something, or missing some context.

But it seems to me that in my project I'm able to resize a `Buffer` with `Queue::write_buffer`. Which conflicts with the statement in its doc and also on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/GPUQueue/writeBuffer). This has been observed both on native (Linux with Vulkan backend) as well as in the web (Chromium, so actual WebGPU runtime is not wgpu).

This is observed in the larger context of egui, so perhaps that is somehow enabling this, but I cant see directly how.

Here are some links to my project, sorry that its a mess, I currently think that I'm simply missing something obvious, and the project if far from ready:
* the only spot where the buffer is created, alongside its Buffer, set to an initial size (when you open it initially that should be pretty much 0): https://github.com/9SMTM6/mcmc-demo/blob/b5cd193c2568203094b29411bbf1daa190105e11/src/visualizations/shader_based/diff_display.rs#L47
* I write to the buffer here, which often is with a changed size of the elements I write: https://github.com/9SMTM6/mcmc-demo/blob/b5cd193c2568203094b29411bbf1daa190105e11/src/visualizations/shader_based/diff_display.rs#L225

So yeah. This buffer should expand drastically in size each time I increase the samples, and (massive performance issues aside) it seems to actually work that way, the visuals of the displaying shader change appropriately. The project is available at https://9smtm6.github.io/mcmc-demo/ with a webgpu enabled browser, to increase the samples click the "Batch step" button in the floating window (this is also required to happen once to get a display at all currently).

**Comment by teoxoy** [comment]
Resizing buffers shouldn't be possible. We have validation in `write_buffer` that makes sure the buffer is big enough for the given data.

You seem to always be calling `get_approx_triple` with `Some(approx_points)`, the 0 size buffer path is never taken.

**Comment by 9SMTM6** [comment]
Huh. I thought that was only called once. Evidently I was wrong, just checked. Sorry.
