### ISSUE TITLE
Setting a pipeline-overridable shader constant to `f64::INFINITY` results in a crash on certain platforms

### ISSUE THREAD

**Issue by polina4096** [gfx-rs/wgpu#6082]
**Description**
When setting a pipeline-overridable shader constant to `f64::INFINITY`, code fails with an error on certain platforms in various configurations. I've only been able to catch this on Windows as of now.

**Repro steps**
```
device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
  label: None,
  layout: Some(&pipeline_layout),
  vertex: wgpu::VertexState {
    module: &shader,
    entry_point: "vs_main",
    buffers: &[],
    compilation_options: wgpu::PipelineCompilationOptions {
      constants: &HashMap::new().tap_mut(|x| {
        x.insert(String::from("1000"), f64::INFINITY);
      }),
      ..Default::default()
    },
  },
  /* ... */
}
```

**Expected vs observed behavior**
This results in a crash with a message saying to report the issue. Not really sure which is the best way to handle this case otherwise, but at least it should not behave like that.

**Extra materials**
<img width="1512" alt="Screenshot 2024-08-06 at 05 07 51" src="https://github.com/user-attachments/assets/614465bb-1448-4162-9713-354ffff473d2">

**Platform**
Windows 11
wgpu = "22.1.0"

**Comment by teoxoy** [comment]
This is expected, as the validation error is saying, NaNs and Infinities are not supported.

There is this issue that tracks support for those though: https://github.com/gfx-rs/wgpu/issues/5128.

**Comment by polina4096** [comment]
I'm not sure the message to report it is expected.

**Comment by Wumpf** [comment]
@teoxoy the "please report this" bit in the log there is strange & confusing indeed. Do we have that tracked somewhere?

**Comment by teoxoy** [comment]
Ah yes, that's not intended. I'll open a PR.
