### ISSUE TITLE
Memory write concurrency guarantees

### ISSUE THREAD

**Issue by trbabb** [gfx-rs/wgpu#6096]
I think there might be an issue with the memory model on Metal, but I'm not sure— What guarantees does WGSL offer about writing to independent elements of a shared matrix from different invocations?

I would expect writes to non-overlapping matrix elements to be independent and not require synchronization. But I am seeing nondeterminism when I run something like this shader:

    @group(0) @binding(0) var<storage,read_write> mtxs: array<mat4x4f>;
    
    @compute @workgroup_size(16,4,4)
    fn main(@builtin(global_invocation_id) global_id: vec3u)
    {
        let i: u32 = global_id.x;
        let x: u32 = global_id.y;
        let y: u32 = global_id.z;
        let f: f32 = sin(f32(i) / 8.);
        mtxs[i][x][y] = f * (x + 1) * (y + 1);
    }

(I `dispatchWorkgroups(n, 1, 1)` to ensure the bounds of the matrix are not exceeded).

It looks like _only_ the final row or column of each matrix is actually stored (depending on how I factor the workgroup dimensions), which suggests to me that other invocations' results are getting clobbered by invocations that are writing to higher-index elements, suggesting the store might actually be implemented as a vector-store under the hood.

The [Vulkan memory model](https://registry.khronos.org/vulkan/specs/1.2-extensions/html/vkspec.html#memory-model-memory-location)— which [the WGSL spec says](https://www.w3.org/TR/WGSL/#memory-model) should be considered the reference model— suggests that memory locations as small as 8 bits can be considered independent locations.

Is the behavior above expected? (And if it is, exactly when is it safe to write to a location without synchronization?)

**Comment by teoxoy** [comment]
This is covered by this section of the WGSL spec:

> 8.5.1.3. Component Reference from Vector Memory View
>
> A write access to component of a vector may access all of the memory locations associated with that vector.
