### ISSUE TITLE
Support `first` and `either` sampling in `@interpolate(flat, …)`

### ISSUE THREAD

**Issue by ErichDonGubler** [gfx-rs/wgpu#6122]
The WebGPU spec. made some changes to WGSL with [`gpuweb`#4639](https://github.com/gpuweb/gpuweb/pull/4639) that we need to handle; it…

- [ ] …added the `first` and `either` interpolation sampling to the `flat` interpolation type, with `first` as the default.
- [ ] …added validation that `perspective` and `linear` interpolation types are constrained to the set of `{center,centroid,sample}`, to exclude the new interpolation sampling options.

**Comment by jimblandy** [comment]
It seems that the CTS was updated to cover this, causing quite a few "regressions" in Firefox.
