### ISSUE TITLE
Unable to pass a pointer to a struct field as a function argument

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#6131]
https://shader-playground.timjones.io/82ad65aaa26a4505fd207ece2407b216

**Description**
```wgsl
struct Foo {
	x: u32
}

fn foo(x: ptr<function, u32>) {
    *x = 1u;
}

var foo = Foo();
foo(&foo.x);
```

produces:
> thread 'main' panicked at 'internal error: entered unreachable code: Expression [3] is not cached!', naga\src\back\spv\block.rs:2095:45

**Expected vs observed behavior**
Expected to be valid.

**Extra materials**

**Platform**
SPV backend.

**Comment by teoxoy** [comment]
This is a duplicate of https://github.com/gfx-rs/wgpu/issues/4540.
