### ISSUE TITLE
The repository URL of the `d3d12` crate on crates.io is 404

### ISSUE THREAD

**Issue by LastExceed** [gfx-rs/wgpu#6154]
happened with the merge of #5956 

Is the `d3d12` crate being discontinued? If so, perhaps a disclaimer could be added to its README, and the URL updated to [its last release tag](https://github.com/gfx-rs/wgpu/blob/wgpu-v22.0.0/d3d12) (instead of `trunk`, where it no longer exists)?

I'll happily PR this myself, I just need to know what's going on and what should be done, since I am just getting started with the `gfx-rs` ecosystem

**Comment by cwfitzgerald** [comment]
Yeah it's been discontinued, at least for the time being, now that we're using windows-rs. It might be revitalized in the future if there is a use case for it.

It would be great to add both a disclaimer and to change the link, if you PR this onto the 'v22` branch, we can publish it

**Comment by LastExceed** [comment]
Probably a stupid question, but how does publishing this work exactly? Will it be its own minor version? If so, how do we prevent the URL from immediately being outdated?

**Comment by cwfitzgerald** [comment]
We can set the url to the tag before it exists, then set the tag, and publish (publishing is still done manually)

**Comment by LastExceed** [comment]
i see. what's going to be the exact version number?

**Comment by cwfitzgerald** [comment]
22.1.1, as it's just a documention change
