### ISSUE TITLE
Add `ExternalImageSource::VideoFrame`

### ISSUE THREAD

**Issue by jprochazk** [gfx-rs/wgpu#6167]
WebCodecs API introduces `VideoFrame` (https://w3c.github.io/webcodecs/#videoframe), which is a valid `ExternalImageSource` in both WebGL (`WebGLRenderingContext.texImage2D`) and WebGPU (`GPUQueue.copyExternalImageToTexture`) contexts.

**Comment by cwfitzgerald** [comment]
We'd love a PR for this, should just need to be added to the enum, like https://github.com/gfx-rs/wgpu/pull/5668 did
