### ISSUE TITLE
`Device::as_hal` crashes after ID removal in #6134

### ISSUE THREAD

**Issue by ErichDonGubler** [gfx-rs/wgpu#6169]
**Description**

@MarijnS95 noted in [this comment](https://github.com/gfx-rs/wgpu/pull/6134#issuecomment-2312485764) from <https://github.com/gfx-rs/wgpu/pull/6134> that `Device::as_hal` appears to have regressed to crashing when called in some (?) cases.

**Repro steps**

TBD by @MarijnS95.

**Expected vs observed behavior**

We should keep previous behavior, that is, `Device::as_hal` should not crash.

**Platform**

Windows on DX12.

**Comment by MarijnS95** [comment]
Platform is Windows. I was running a modified version of the `hello_triangle` sample while playing with `DirectComposition` (needed access to the `D3D12Device` for that).

Will push a repro branch soon.

**Comment by MarijnS95** [comment]
Try https://github.com/MarijnS95/wgpu/compare/repro-6169 with:

```console
$ WGPU_BACKEND=dx12 cargo r -p wgpu-examples hello_triangle
...
thread 'main' panicked at wgpu\src\context.rs:737:5:
assertion failed: data.is::<T>()
stack backtrace:
...
```

Note that in this caseit's already failing for `surface`, before even getting to `adapter` or `device` which also both fail. Only `instance.as_hal()` is successful.

**Comment by ErichDonGubler** [comment]
Confirmed locally on my M1 Mac that the [suggested repro](https://github.com/gfx-rs/wgpu/issues/6169#issuecomment-2313611497) crashes, and that latest `trunk` does not reproduce the crash. I did this on Mac, instead of Windows, by replacing `dx12` with `metal` in the tip commit of the suggested repro, i.e.:

```diff
diff --git a/examples/src/hello_triangle/mod.rs b/examples/src/hello_triangle/mod.rs
index 7c82d49cf0..0100b79024 100644
--- a/examples/src/hello_triangle/mod.rs
+++ b/examples/src/hello_triangle/mod.rs
@@ -12,7 +12,10 @@
 
     let instance = wgpu::Instance::default();
 
-    let surface = instance.create_surface(&window).unwrap();
+    unsafe { instance.as_hal::<wgpu::hal::metal::Api>() };
+
+    let mut surface = instance.create_surface(&window).unwrap();
+    unsafe { surface.as_hal::<wgpu::hal::metal::Api, _, _>(|s| ()) };
     let adapter = instance
         .request_adapter(&wgpu::RequestAdapterOptions {
             power_preference: wgpu::PowerPreference::default(),
@@ -22,6 +25,7 @@
         })
         .await
         .expect("Failed to find an appropriate adapter");
+    unsafe { adapter.as_hal::<wgpu::hal::metal::Api, _, _>(|a| ()) };
 
     // Create the logical device and command queue
     let (device, queue) = adapter
@@ -38,6 +42,7 @@
         )
         .await
         .expect("Failed to create device");
+    unsafe { device.as_hal::<wgpu::hal::metal::Api, _, _>(|d| ()) };
 
     // Load the shaders from disk
     let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
```

**Comment by MarijnS95** [comment]
Yep, the repro branch no longer crashes after rebasing, thanks!
