### ISSUE TITLE
FIFO not working with Metal backend

### ISSUE THREAD

**Issue by RobinWragg** [gfx-rs/wgpu#6172]
**Description**
I'm using Sonoma 14.1.1, wgpu 22.1.0 and winit 0.30.5 in a native window on an M2 Macbook Air. I've confirmed wgpu is using the Metal backend and I've confirmed the surface is being configured with PresentMode::Fifo, but I'm getting about 5000 frames per second. This is the same whether windowed, exclusive fullscreen, or borderless fullscreen. Are there any known issues with using FIFO on Mac?

Here is my project, the frame time is shown in the top left.
https://github.com/RobinWragg/game

Many thanks

**Comment by teoxoy** [comment]
Is this no longer an issue?

**Comment by RobinWragg** [comment]
Yes, no longer an issue, there was a bug in my instrumentation misreporting the framerate.
