### ISSUE TITLE
Unable to break out of the loop in SPIR-V

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#6220]
**Description**
Getting invalid SPIR-V out of Naga:
>error: line 36: Block '23[%23]' branches to the loop continue target '16[%16]', but is not contained in the associated loop construct '13[%13]'
  OpBranch %16

**Repro steps**
Program:
```wgsl
fn main() {
    for (var i = 0; i < 4; i += 1) {
      break;
    }
}
```

**Expected vs observed behavior**
Expected to produce valid SPIR-V

**Comment by jimblandy** [comment]
The bug here is that the end of the loop body isn't reachable, but we generate a block for it anyway that branches to the 'continue' block. Because the end-of-loop SPIR-V block isn't reachable, the validator considers it not to be part of the loop, and thus forbids it from jumping into the loop.
