### ISSUE TITLE
Limits on maximum buffer size (MaxBufferSize or MaxStorageBufferBindingSize) is not being correctly applied

### ISSUE THREAD

**Issue by rcoreilly** [gfx-rs/wgpu#6221]
**Description**

I tried to create a storage buffer of a size that is well within the Limits values reported for my GPU, but got an error that indicates it is enforcing a much lower limit:

```
Caused by:
    In wgpuDeviceCreateBuffer
      note: label = `Data_0`
    Buffer size 640000000 is greater than the maximum buffer size (268435456)
```

my limits for this Apple M3 Max GPU running under native mode are:

```
		"MaxStorageBufferBindingSize": 4294967295,
		"MaxBufferSize": 77309411328,
```

**Repro steps**

Should be easy enough with any simple test case -- this is running under a Go interface to wgpu_native so probably not the best for your testing.

**Expected vs observed behavior**

should have used the correct limits.

**Platform**

MacBook Pro with M3 Max chip, Sonoma 14.6.1 OS, using [v0.19.4.1](https://github.com/gfx-rs/wgpu-native/releases/tag/v0.19.4.1) 

I also filed another potentially-related issue under wgpu-native: https://github.com/gfx-rs/wgpu-native/issues/408 where there is inconsistency between the reported limits and what actually seems to be implemented.

**Comment by teoxoy** [comment]
268435456 is the default limit, you need to explicitly request higher limits via `required_limits` when you create the device.

**Comment by teoxoy** [comment]
I think that would resolve https://github.com/gfx-rs/wgpu-native/issues/408 as well?

**Comment by rcoreilly** [comment]
@teoxoy I'll check that out and close the issue if so.

Meanwhile, now that I'm actually requesting larger buffers, it is actually failing to run (after successfully giving me the device), with a "Validation Error" :(  I'll try to replicate on the latest compute example in wgpu_native and see how that goes.

**Comment by rcoreilly** [comment]
I have verified that it appears to be working correctly in the latest wgpu_native compute example.  We'll have to update our version to the latest and hopefully that fixes the issue.

Also note the question in the code comments below about how to set the RequiredLimits to all defaults except ones you specifically set -- I could not find that exposed in the C interface?

```C
  WGPUSupportedLimits sup;
  wgpuAdapterGetLimits(adapter, &sup);

  WGPULimits limits; // note: I could not find a call that sets all fields to the default "undefined" value: 0xffffffff
  // so I had to just use all the supported limits.  we have this DefaultLimits() function in our Go wrapper,
  // and I found this method in rust: https://docs.rs/wgpu/latest/wgpu/struct.Limits.html -- but nothing in the .h file.
  // how is anyone supposed to just specify a few limits to override in their requested limits??
  WGPURequiredLimits req;
  req.limits = sup.limits;
  req.limits.maxStorageBufferBindingSize = 0x1FFFFFFF; //  note: it doesn't seem to care about this
  req.limits.maxBufferSize = 0x1FFFFFFF; // this is the only one that mattered, relative to bufSize below.
  WGPUDeviceDescriptor desc;
  desc.requiredLimits = &req;
 
  WGPUDevice device = NULL;
  wgpuAdapterRequestDevice(adapter, &desc, handle_request_device,
                           (void *)&device);
  assert(device);

  WGPUQueue queue = wgpuDeviceGetQueue(device);
  assert(queue);

  WGPUShaderModule shader_module =
      frmwrk_load_shader_module(device, "shader.wgsl");
  assert(shader_module);

  WGPUBuffer staging_buffer = wgpuDeviceCreateBuffer(
      device, &(const WGPUBufferDescriptor){
                  .label = "staging_buffer",
                  .usage = WGPUBufferUsage_MapRead | WGPUBufferUsage_CopyDst,
                  .size = numbers_size,
                  .mappedAtCreation = false,
              });
  assert(staging_buffer);

  uint32_t bufSize = 0xFFFFFFFF; // this fails if > size specified above, works if <

  WGPUBuffer storage_buffer = wgpuDeviceCreateBuffer(
      device, &(const WGPUBufferDescriptor){
                  .label = "storage_buffer",
                  .usage = WGPUBufferUsage_Storage | WGPUBufferUsage_CopyDst |
                           WGPUBufferUsage_CopySrc,
                  .size = bufSize,
                  .mappedAtCreation = false,
              });
  assert(storage_buffer);
```

**Comment by teoxoy** [comment]
I would open an issue at https://github.com/webgpu-native/webgpu-headers.
