### ISSUE TITLE
Texture usages TextureUsages(STORAGE_BINDING) are not allowed on a texture of type R8Uint

### ISSUE THREAD

**Issue by CatCode79** [gfx-rs/wgpu#6222]
**Description**
When using the r8uint texture format in creating a storage texture I get the following error:

[2024-09-05T09:10:03Z ERROR wgpu_core::device::global] Device::create_texture error: Texture usages TextureUsages(STORAGE_BINDING) are not allowed on a texture of type R8Uint
[2024-09-05T09:10:03Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'main' panicked at C:\Users\Gatto\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-22.1.0\src\backend\wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_texture
    Texture usages TextureUsages(STORAGE_BINDING) are not allowed on a texture of type R8Uint

**Repro steps**
Changing the texture format of the storage_texture example to r8uint allows the bug to be reproduced.

**Expected vs observed behavior**
What I expected is to be able to use this format as well just like I normally use the Rgba8Unorm format.

**Platform**
Windows 11,  the wgpu release version is 22.1.0, i'm using the vulkan backend.

**Comment by teoxoy** [comment]
This is expected, see https://gpuweb.github.io/gpuweb/#plain-color-formats.
The capability will most likely come in a feature https://github.com/gpuweb/gpuweb/issues/3837.
If you want to get around this and are not targeting web you can use `Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES`.
