### ISSUE TITLE
Hook up player to RenderDoc

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#623]
Currently, I can't find a way to capture a workload with RenderDoc that doesn't operate on a swapchain. RenderDoc doesn't know when to stop. We could have a simple integration with its API to tell it where the submissions are, or at least when we are done.

**Comment by cwfitzgerald** [comment]
The renderdoc api is pretty easy to set up. You are probably looking for [`start_frame_capture`](https://docs.rs/renderdoc/0.7.1/renderdoc/struct.RenderDoc.html#method.start_frame_capture) and [`end_frame_capture`](https://docs.rs/renderdoc/0.7.1/renderdoc/struct.RenderDoc.html#method.end_frame_capture), to which you can just pass two nullptrs, you don't need the actual values. This works pretty well. 

The only quirk is that the renderdoc struct in the rust api is currently !Send and !Sync, so you basically need to reopen the DLL within every function you need it. I was working with the author in https://github.com/ebkalderon/renderdoc-rs/issues/79 to figure out a way to relax this requirement.
