### ISSUE TITLE
wgsl textureBarrier unsupported

### ISSUE THREAD

**Issue by mikialex** [gfx-rs/wgpu#6260]
**Description**

the wgsl textureBarrier is not supported. https://www.w3.org/TR/WGSL/#textureBarrier-builtin

**Expected vs observed behavior**

textureBarrier is in wgsl spec, so it should be supported. TextureBarrier should be used when reading after writing the storage texture.

**Comment by teoxoy** [comment]
This should be covered by https://github.com/gfx-rs/wgpu/issues/6204.
