### ISSUE TITLE
WebGPU backend unsound when compiling for wasm with `--target-feature=+atomics`?

### ISSUE THREAD

**Issue by BGR360** [gfx-rs/wgpu#6267]
The WebGPU backend forcibly implements `Send` and `Sync` on all JS handles to WebGPU objects:

https://github.com/gfx-rs/wgpu/blob/e4001a58bbbb8920742624b72738ed8b175d95d3/wgpu/src/backend/webgpu.rs#L25-L38

Today, it is possible to compile Rust to WebAssembly with features that enable multi-threading via web workers and shared Wasm memory.

Does that mean the WebGPU backend is currently unsound if you attempt to use it in a multi-threaded wasm project?

**Comment by cwfitzgerald** [comment]
Check the build script that sets up that cfg: https://github.com/gfx-rs/wgpu/blob/trunk/wgpu%2Fbuild.rs#L8-L11 - it only actually enables that on wasm if the atomics flag isn't specified _and_ you enable that feature. So we should be good :)

**Comment by BGR360** [comment]
Okay cool, I knew a similar thing was done in other parts of the wgpu code (the whole `WasmNotSend` business), but the comment gave me pause. Perhaps it could be updated.

**Comment by cwfitzgerald** [comment]
Yeah the comment is out of date, we'd appreciate a PR to update it!
