### ISSUE TITLE
Missing precondition for `slice::from_raw_parts` in gles backend

### ISSUE THREAD

**Issue by Imberflur** [gfx-rs/wgpu#6327]
We got a report on this here https://gitlab.com/veloren/veloren/-/issues/2015 where some debug assertions catch a missing precondition. However, note this is on an older version and the `get_data` method has changed a bit.

A quick look at the current version suggests that the alignment might not be checked and the function itself has a note about how it should be replaced: https://github.com/gfx-rs/wgpu/blob/e7f891bf2b455927b98e70301c707428c7adf62a/wgpu-hal/src/gles/queue.rs#L1608-L1609

**Comment by Wumpf** [comment]
This looks vaguely related to:
* https://github.com/gfx-rs/wgpu/issues/3508

**Comment by cwfitzgerald** [comment]
That's actually unrelated. This is getting the data for a push constant from a buffer full of push constant data in the queue.

**Comment by Imberflur** [comment]
If it is fine to just copy to the stack first, this could probably use https://docs.rs/bytemuck/latest/bytemuck/fn.pod_read_unaligned.html

**Comment by Imberflur** [comment]
I'm able to produce this on a couple tests in the `trunk` branch by running `cargo xtask test` with a recent enough nightly compiler (currently using `rustc 1.83.0-nightly (2bd1e894e 2024-09-26)`).

Both `wgpu_test::regression::issue_3349::multi_stage_data_binding` and `wgpu_test::shader::struct_layout::push_constant_input` hit this.
