### ISSUE TITLE
[naga spv-out] Indexing arrays by value causes unnecessary copies

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#6358]
Given code like this:

```wgsl
fn (aaa: array<array<array<f32, 3>, 3> 3>, i: i32, j: i32, k: i32) -> f32 {
    return aaa[i][j][k];
}
```

the changes in #6188 will copy each intermediate indexing result into a separate variable. It would be much nicer to simply spill the value into a variable the moment we know it will be indexed dynamically, and then always use it from there.

**Comment by sagudev** [comment]
More exact link to comment: https://github.com/gfx-rs/wgpu/pull/6188#discussion_r1746348184
