### ISSUE TITLE
Render pipeline creation failure with DX12

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/wgpu#642]
**Description**
A project that works well under both vulkan and metal is crashing when using DirectX12

**Repro steps**
The Repo is over at https://gitlab.com/veloren/veloren/-/tree/capucho/wgpu

**Extra materials**
[voxygen-2020-05-05-07.log](https://github.com/gfx-rs/wgpu/files/4579353/voxygen-2020-05-05-07.log)

**Platform**
Windows 10, Directx12, wgpu=0.5.0, wgpu-core=0.5.4

**Comment by kvark** [comment]
Here are the generated HLSL sources: [fluid-shaders.zip](https://github.com/gfx-rs/wgpu/files/4581280/fluid-shaders.zip)
Interesting bit is the structure on VS output:
```hlsl
```

**Comment by kvark** [comment]
I was pointed out that this is fixed in https://github.com/KhronosGroup/SPIRV-Cross/issues/1322
@grovesNL would you be able to update our spirv_cross with this fix?

**Comment by kvark** [comment]
We just published gfx-rs crates containing this fix. Please do `cargo update -p gfx-backend-dx12` and try again, and re-open this issue if needed.

**Comment by kvark** [comment]
Veloren reported to still have a problem.

**Comment by kvark** [comment]
The remaining problem is on the client side, the `flat` qualifier doesn't match between vertex and fragment stages. We will be validating this, of course, but the fix on their side still needs to be done:
https://gitlab.com/veloren/veloren/-/merge_requests/1028
