### ISSUE TITLE
Buffer slice method should panic when index is out of range (?)

### ISSUE THREAD

**Issue by beholdnec** [gfx-rs/wgpu#6428]
**Description**
The slice method on Buffer does not check whether the argument is in a valid range for the buffer. In order to be consistent with the Array and Vec slicing methods of Rust, attempting to take an out-of-range slice on a buffer should panic. The slice method is defined here: https://github.com/gfx-rs/wgpu/blob/b3f665be7d9127d8048ec3b556e2a50868e951df/wgpu/src/api/buffer.rs#L243-L250

**Repro steps**
Create a buffer of size 8, then try buffer.slice(0..16).

**Expected vs observed behavior**
The slice method should panic since the argument is out of range. Instead, it allows creating an out-of-range Buffer slice.

**Platform**
wgpu 22.1.0, Windows 11, Rust 1.82.0

**Comment by teoxoy** [comment]
Thanks for the report, could you put up a PR for this?

**Comment by microdou** [comment]
Likely related:
On Rust `1.82.0`, wgpu wasm results in runtime error `RangeError: WebAssembly.Table.grow(): failed to grow table by 4 at __wbindgen_init_externref_table`. Rust `1.81.0` works fine.

**Comment by beholdnec** [comment]
I have created a PR #6432 to address this issue.
