### ISSUE TITLE
`struct <fun>Output` conflicts with `fn <fun>` on Metal

### ISSUE THREAD

**Issue by Jengamon** [gfx-rs/wgpu#6439]
**Description**
Naga fails to rename a shader variable named "vsOutput", causing failures in shaders that use the name.

**Repro steps**
(at least, this works on latest MacOS, and does *not* repro on WASM)
(taken from https://webgpufundamentals.org/webgpu/lessons/webgpu-inter-stage-variables.html)
```wgsl
struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) color: vec4f,
};

@vertex fn vs(
    @builtin(vertex_index) vertexIndex : u32
) -> VertexOutput {
    var pos = array(
        vec2f( 0.0,  0.5), // top center
        vec2f(-0.5, -0.5), // bottom left
        vec2f( 0.5, -0.5)  // bottom right
    );
    var color = array<vec4f, 3>(
        vec4f(1, 0, 0, 1), // red
        vec4f(0, 1, 0, 1), // green
        vec4f(0, 0, 1, 1), // blue
    );

    var vsOutput: VertexOutput;
    vsOutput.position = vec4f(pos[vertexIndex], 0.0, 1.0);
    vsOutput.color = color[vertexIndex];
    return vsOutput;
}

@fragment fn fs(fsInput: VertexOutput) -> @location(0) vec4f {
    return fsInput.color;
}
```
1. setup a program using the above shader
2. attempt to run the program and observe the crash

**Expected vs observed behavior**
Expected for the shader to compile and run.

Observed an error due to invalid types in shader.

**Extra materials**
cwfitzgerald told me to make this issue so here I am.

**Platform**
OS: MacOS 15.0.1
wgpu: 22.1.0

**Comment by Jengamon** [comment]
After a bit more investigation, I've found that the actual thing problematic variable name is `<function name>Output`, and `vsOutput` is only problematic inside a function named `vs` (`vsyOutput` is problematic in function `vsy`, etc.)

**Comment by ErichDonGubler** [comment]
Literally just barely solved this in <https://github.com/gfx-rs/wgpu/pull/6438>. 🙌🏻😤

Also, welcome the community! Thanks for taking the time to file. 🙂
