### ISSUE TITLE
Software rendering

### ISSUE THREAD

**Issue by Korijn** [gfx-rs/wgpu#644]
What's the wgpu story with regards to software rendering? Would something like OSMesa work as a backend?

(Perhaps this question better belongs to the wgpu-native repo, I was unsure)

**Comment by kvark** [comment]
@Korijn Current story is to rely on the SW implementations of the native backends:
  - on Vulkan there is [swiftshader](https://swiftshader.googlesource.com/SwiftShader/)
  - on D3D there is a Warp adapter, which we could pick (already) if we had any sort of "software" flag in the adapter descriptor
  - on OpenGL there is OSMesa, but gfx/wgpu OpenGL backend is by itself pretty fragile still, so it needs to mature more before we can expose it and make usable.

**Comment by Korijn** [comment]
Alright, so on Linux, I should be able to build swiftshader and run wgpu-native with it. Would that require any special settings or compiler/linker options?

**Comment by kvark** [comment]
Assuming SwiftShader can be used via the Vulkan Loader ICD interface, you'd just run your app on Linux with `VK_ICD_FILENAMES=<path_to_swiftshader_icd.json>`. wgpu wouldn't necessarily know that it works with swiftshader.

**Comment by Korijn** [comment]
I'll see if I can find anything like that in their docs/source.

Thanks so far!

**Comment by kvark** [comment]
FWIW, last I heard, swiftshader assumes a very specific use by an application. It's not build (at least yet) as a general purpose Vulkan implementation. Rather, it's made to work well with Angle on Vulkan. So beware of dragons when you test this, but I'm following your work with anticipation :)

**Comment by Korijn** [comment]
We'll see! :)

**Comment by Korijn** [comment]
Just wondering if there has been any developments in this regard? :)

**Comment by kvark** [comment]
I don't think we have any actions to do here. If you want to test Mesa's LavaPipe today, you can do it. Since it's a regular Vulkan driver, no changes are needed on wgpu side.

**Comment by cwfitzgerald** [comment]
Closing as no-action needed

**Comment by mateli** [comment]
For performance emulators and game engines often use TinyGL on platforms where software rendering is faster than GPU rendering.
