### ISSUE TITLE
Naga's typechecker ignores scalar kind when casting matrices

### ISSUE THREAD

**Issue by cogumbreiro** [gfx-rs/wgpu#6441]
**Description**

I think that there's a bug in the `naga/src/proc/typifier.rs`. Notably, when casting with `As` the new scalar kind, variable `kind`, is not propagated to the output `scalar`, only the `width`.

```rust
                Ti::Matrix {
                    columns,
                    rows,
                    mut scalar,
                } => {
                    if let Some(width) = convert {
                        scalar.width = width;
                    }
                    TypeResolution::Value(Ti::Matrix {
                        columns,
                        rows,
                        scalar,
                    })
                }
```

Note a correct behavior on vectors where the kind is propagated to the generated vector:
```
                Ti::Vector {
                    size,
                    scalar: crate::Scalar { kind: _, width },
                } => TypeResolution::Value(Ti::Vector {
                    size,
                    scalar: crate::Scalar {
                        kind,
                        width: convert.unwrap_or(width),
                    },
                }), 
```

Source: https://github.com/gfx-rs/wgpu/blob/f669024eeb9e86e553eb955a02b18a7723fb64e1/naga/src/proc/typifier.rs#L881-L884

**Comment by cogumbreiro** [comment]
I've added an example that crashes in current naga.

**Comment by cogumbreiro** [comment]
I just realized that [according to the spec](https://www.w3.org/TR/WGSL/#matrix-types), a matrix can have f32 or f16. However, since [naga doesn't support f16](https://github.com/gfx-rs/wgpu/issues/4384), then perhaps this is not really a bug as of now.

However, here's a minimal example for posterity which I'm guessing would break once support for f16 is implemented:
```wgsl
@compute @workgroup_size(256, 1, 1) fn computeSomething() {
  let m1: mat2x2<f32> = mat2x2<f32>(
      vec2<f32>(1, 2),
      vec2<f32>(3, 4)
  );

  let m2: mat2x2<f16> = mat2x2<f16>(m1);
}
```

**Comment by jimblandy** [comment]
Since matrices are enforced to be `f32` by the validator, this isn't really a bug we can hit at the moment. When we add `f16` matrix support, this will become relevant.
