### ISSUE TITLE
wgpu-hal needs a no-op backend for fuzzing and benchmarking

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#6454]
It would be nice if there were a `wgpu-hal` backend that basically does nothing and returns `Ok` for every request. Even though buffer contents would never be right, and presentation would not happen, this would be useful for fuzzing and benchmarking `wgpu-core`.

**Comment by jimblandy** [comment]
The insight here is that the only time you can actually tell whether the GPU did anything at all is when you look at buffer contents. Many many tests don't even bother to do this. And it would be incredibly useful to have the option of cutting the driver and the GPU out of the picture when benchmarking and fuzzing.

**Comment by jimblandy** [comment]
Much of the work we'll be doing is actually entirely platform-independent, so this would be a portable and fast way to validate that work.

**Comment by DemiMarie** [comment]
> The insight here is that the only time you can actually tell whether the GPU did anything at all is when you look at buffer contents. Many many tests don't even bother to do this. And it would be incredibly useful to have the option of cutting the driver and the GPU out of the picture when benchmarking and fuzzing.

I expect there to be more security problems in the backend shader compilers (which are written in C and/or C++) than in wgpu (which is written in Rust).  Therefore, such fuzzing would be useful to find bugs in wgpu itself, but would not be a replacement for full-stack fuzzing that includes running the code.

**Comment by jimblandy** [comment]
Oh, I guess this is `wgpu_hal::empty::Api`. I had forgotten it existed.

**Comment by cwfitzgerald** [comment]
We probably should have an issue open for being able to access it. So being able to make an empty device.
