### ISSUE TITLE
wgpu supported @builtin(frag_coord) or not?

### ISSUE THREAD

**Issue by olejaaaaaaaa** [gfx-rs/wgpu#6455]
I'm using wgpu 22.0 and web compiler. I need to compile my shader from Shadertoy, but I can't use the built-in int(frag_coord) :(

**Comment by ErichDonGubler** [comment]
@olejaaaaaaaa: Please provide an example of what's not working; I'm guessing you'll want to provide a sample shader file and the invocation of Naga CLI (i.e., `cargo run -p naga --all-features -- …`) you're trying to use it with?

**Comment by olejaaaaaaaa** [comment]
```
struct VSOut {
    @builtin(position) Position: vec4f,
    @location(0) color: vec3f,
};

@vertex
fn vs_main(@location(0) inPos: vec3f,
           @location(1) inColor: vec3f) -> VSOut {
    var vsOut: VSOut;
    vsOut.Position = vec4f(inPos, 1.0);
    vsOut.color = inColor;

    return vsOut;
}

@fragment
fn fs_main(@builtin(frag_coord) frag_coord: vec4<f32>, inColor: vec3f) -> @location(0) vec4<f32> {
    // Получаем координаты текущего фрагмента (пикселя)
    let pixel_x = frag_coord.x;
    let pixel_y = frag_coord.y;

    // Применяем их для создания цвета, например, градиент по координатам
    let color = vec4<f32>(pixel_x / 640.0, pixel_y / 640.0, 0.5, 1.0); // используйте фактические размеры вашего рендеринга

    return color;
}
```

build --target web I dont know about naga

**Comment by grovesNL** [comment]
@olejaaaaaaaa I think `@builtin(position)` in the fragment shader might be what you're looking for:

```rust
fn fs_main(@builtin(position) frag_coord: vec4<f32>, /*...*/)
```

**Comment by ErichDonGubler** [comment]
I believe @grovesNL has the right answer; there is no `gl_FragCoord`/`frag_coord` built-in in standard WGSL. The `position` built-in does seem like what you want—see also the WGSL spec. for the `position` built-in: https://www.w3.org/TR/WGSL/#position-builtin-value

Closing, since this seems resolved. @olejaaaaaaaa, feel free to re-open if you feel like this doesn't satisfy your problem.

**Comment by olejaaaaaaaa** [comment]
Thank you for your time, you really helped me a lot
