### ISSUE TITLE
Use Loom for testing concurrency

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#646]
Since we have concurrency and quite a bit of synchronization in the logic, it would be great to have a better test coverage for this. [Loom](https://github.com/carllerche/loom/) looks very useful.
Should help with https://github.com/gfx-rs/wgpu/issues/150

**Comment by cwfitzgerald** [comment]
We've since removed loom from the codebase, and I'm not sure how much it will be immediately helpful. We will keep it in mind for the future if a use case comes up.
