### ISSUE TITLE
Invalid `dispatch_workgroups` arguments can crash MacOS

### ISSUE THREAD

**Issue by dfellis** [gfx-rs/wgpu#6467]
**Description**
If you set any of the workgroup sizes to 0, instead of just not running your compute shader, MacOS will freeze up and eventually the computer will reboot.

**Repro steps**
@cwfitzgerald said I didn't need to. 😉 

**Expected vs observed behavior**
On Windows and Linux, the shader execution simply does nothing, but on MacOS, the machine crashes. It should probably also just do nothing, or only exit the application.

**Extra materials**

Here's a picture of the crashing code being stopped from crashing the machine when metal debugging is enabled:

![IMG20241025141640](https://github.com/user-attachments/assets/ea45a408-c682-4081-a306-5492f93c0a4e)

**Platform**
Running on the latest commit of `wgpu` on macOS Monterrey 12.7.6 on an old 2014 Mac Mini I got for testing purposes. :)

**Comment by teoxoy** [comment]
I think this is a matter of adding an `if` here:

https://github.com/gfx-rs/wgpu/blob/f3db183f1b38f5f5d006e179b25d55c4e9c25f37/wgpu-hal/src/metal/command.rs#L1243-L1249

Could you open a PR for this?

**Comment by dfellis** [comment]
@teoxoy I can, but can you also point me to where the regression test needs to go?

**Comment by teoxoy** [comment]
`tests/tests/regression` would be appropriate.

**Comment by dfellis** [comment]
Okay, I have a change and a regression test written and confirmed the test works on my Linux machine, but when I try to run it on the Mac Mini, running the entire test suite also causes a full reboot of the machine, so then starting a run to get a `.gpuconfig` file, hitting `Ctrl+C`, and then running `cargo nextest run wgpu_test::regression::issue_6467` produces the seemingly nonsensical error of:

```
Could not find adapter with info Some(
    AdapterInfo {
        name: "Intel Iris Graphics",
        vendor: 0,
        device: 0,
        device_type: IntegratedGpu,
        driver: "",
        driver_info: "",
        backend: Metal,
    },
) in []
```

It's somehow not able to find the GPU at all in the regression test (perhaps because of how I'm invoking it, but this exact same command works fine on my Linux laptop).

Should I push the PR anyway, or do you have any idea how I can first validate the change before doing so?

**Comment by teoxoy** [comment]
Does it work with `cargo xtask test wgpu_test::regression::issue_6467`?

> the Mac Mini, running the entire test suite also causes a full reboot of the machine

That's concerning, can you narrow it down to a specific test that causes the reboot?

**Comment by dfellis** [comment]
I got a really weird error that one of the build artifacts was not an executable. Maybe the reboot caused it to fail to save the executable properly to disk so I just cleaned the git repo and I'm rebuilding everything from scratch.

This is a 10 year old Mac Mini so it's gonna be a while.

**Comment by dfellis** [comment]
I'm getting this:

```
    Starting 1 test across 19 binaries (455 tests skipped)
     SIGSEGV [   0.418s] wgpu-test::wgpu-test [Executed] [Metal/Intel Iris Graphics/0] wgpu_test::regression::issue_6467::zero_workgroup_size

--- STDOUT:              wgpu-test::wgpu-test [Executed] [Metal/Intel Iris Graphics/0] wgpu_test::regression::issue_6467::zero_workgroup_size ---

running 1 test

--- STDERR:              wgpu-test::wgpu-test [Executed] [Metal/Intel Iris Graphics/0] wgpu_test::regression::issue_6467::zero_workgroup_size ---
2024-11-04 12:38:40.293 wgpu_test-7a42ab7d97687daa[2907:33794] Metal API Validation Enabled
2024-11-04 12:38:40.309 wgpu_test-7a42ab7d97687daa[2907:33794] Metal GPU Validation Enabled

------------
     Summary [   0.544s] 1 test run: 0 passed, 1 failed, 455 skipped
     SIGSEGV [   0.418s] wgpu-test::wgpu-test [Executed] [Metal/Intel Iris Graphics/0] wgpu_test::regression::issue_6467::zero_workgroup_size
error: test run failed
Error: Tests failed

Caused by:
    command exited with non-zero code `cargo nextest run --benches --tests --no-fail-fast --all-features --retries 0 wgpu_test::regression::issue_6467`: 100
```

Re-running with `cargo nextest run wgpu_test::regression::issue_6467` returns the same result. With `cargo test wgpu_test::regression::issue_6467` I can see:

```
running 1 test
2024-11-04 12:55:17.465 wgpu_test-bafcc57776745030[3112:41606] Metal API Validation Enabled
2024-11-04 12:55:17.465 wgpu_test-bafcc57776745030[3112:41606] Metal GPU Validation Enabled
error: test failed, to rerun pass `-p wgpu-test --test wgpu-test`

Caused by:
  process didn't exit successfully: `/Users/damocles/oss/wgpu/target/debug/deps/wgpu_test-bafcc57776745030 'wgpu_test::regression::issue_6467'` (signal: 11, SIGSEGV: invalid memory reference)
```

But I'm not sure what's causing the invalid memory reference. I don't think my change is at fault.

```diff
     unsafe fn dispatch(&mut self, count: [u32; 3]) {
-        let encoder = self.state.compute.as_ref().unwrap();
-        let raw_count = metal::MTLSize {
-            width: count[0] as u64,
-            height: count[1] as u64,
-            depth: count[2] as u64,
-        };
-        encoder.dispatch_thread_groups(raw_count, self.state.raw_wg_size);
+        if count[0] > 0 && count[1] > 0 && count[2] > 0 {
+            let encoder = self.state.compute.as_ref().unwrap();
+            let raw_count = metal::MTLSize {
+                width: count[0] as u64,
+                height: count[1] as u64,
+                depth: count[2] as u64,
+            };
+            encoder.dispatch_thread_groups(raw_count, self.state.raw_wg_size);
+        }
     }
```

Just adding a check that everything is greater than zero or not. It simply doesn't dispatch if it doesn't.

**Comment by dfellis** [comment]
This sigsegv happens to multiple regression tests and I did a `-- --nocapture` run with some `println!`s sprinkled in there and even the println at the very beginning of the `run_async` closure does not print, so this error is occurring earlier in the process.

Still digging in.
