### ISSUE TITLE
wgpu/Naga requires an `f32`, Chrome expects a `u32`

### ISSUE THREAD

**Issue by BenjaminBrienen** [gfx-rs/wgpu#6473]
> This seems to be a bug in wgpu/Naga? The WGSL spec agrees with Chrome: the `level` parameter of `textureSampleLevel` when applied to a `texture_depth_2d_array` is `u32`. But wgpu/Naga requires that it be an `f32`, and this is what we supply. That breaks Chrome.

_Originally posted by @pcwalton in https://github.com/bevyengine/bevy/issues/16000#issuecomment-2431019495_

**Comment by ErichDonGubler** [comment]
Pretty sure that this is a duplicate of <https://github.com/gfx-rs/wgpu/issues/4400>.

**Comment by teoxoy** [comment]
It's a duplicate of https://github.com/gfx-rs/wgpu/issues/4548.
