### ISSUE TITLE
Update wgpu type names to match WGSL spec changes

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#6476]
In https://github.com/gpuweb/gpuweb/pull/4838, a bunch of names are going to change in the spec that do not affect JS, but that do appear in bindings for languages like C and Rust. wgpu should probably add type aliases, at least, for these new names, so that people can continue to use WebGPU as a model when using wgpu.

**Comment by teoxoy** [comment]
https://github.com/gfx-rs/wgpu/pull/6618 resolved this.
