### ISSUE TITLE
Multi threaded memory leak

### ISSUE THREAD

**Issue by cart** [gfx-rs/wgpu#648]
I encountered severe memory leaks when I added multi-threading to my project. Wgpu consumes a new 50MB every second. I was also able to reproduce this in the wgpu "cube" example, which I pushed here: https://github.com/cart/wgpu-rs/tree/multi-threaded-leak.

I run the render pass in a crossbeam_util thread and pass the CommandBuffer to the main thread via crossbeam channel.

![image](https://user-images.githubusercontent.com/2694663/81133616-0767af00-8f07-11ea-9906-feda58fb7175.png)

**Comment by kvark** [comment]
I believe I found the [root cause](https://github.com/gfx-rs/wgpu/blob/4c448c3fc583da6d22c62c7e92bbb74b53863357/wgpu-core/src/command/allocator.rs#L64):
```rust
#[derive(Debug)]
struct Inner<B: hal::Backend> {
    // TODO: Currently pools from threads that are stopped or no longer call into wgpu will never be
    // cleaned up.
    pools: HashMap<thread::ThreadId, CommandPool<B>>,
}
```
This applies to a case where you constantly create new threads.

**Comment by kvark** [comment]
Would you want to help with reviewing #649?

**Comment by cart** [comment]
sure thing!
