### ISSUE TITLE
type of X doesn't match..

### ISSUE THREAD

**Issue by rcoreilly** [gfx-rs/wgpu#6487]
The  latest https://github.com/gfx-rs/wgpu/releases/tag/v23.0.0 release highlights this naga WGSL parsing error:

```wgsl
fn gimme_a_float() -> f32 {
  return 42; // fails in Naga, but standard WGSL happily converts to `f32`
}
```

this is the single most annoying "feature" of the current framework, IMO. I couldn't find the issue that is tracking it. Any chance it could receive some urgent attention?  Thanks!

**Comment by rcoreilly** [comment]
ps. It occurs in simple direct assignments as well, e.g.,
```wgsl
var<storage, read_write> Neurons: array<f32>;
...
Neurons[x,y] = 0;
```

**Comment by ErichDonGubler** [comment]
The issue you're looking for is <https://github.com/gfx-rs/wgpu/issues/4400>. Said issue is one of Firefox contributors' highest priorities, though unassigned. I'm guessing we'll start work on it before the end of the year, but it's hard to provide estimates, with the volume of new issues coming in.

CC @jimblandy ☝🏻
