### ISSUE TITLE
[Experiment]: bundled with dxc (as a feature?)

### ISSUE THREAD

**Issue by CrazyboyQCD** [gfx-rs/wgpu#6499]
https://github.com/hexops/mach-dxcompiler (CC-BY-4.0) :
features(copied):
- Statically linked dxcompiler library and dxc executables.
- Zero dependency on proprietary dxil.dll code-signing blob (see: [Mach Siegbert Vogt DXCSA](https://github.com/hexops/DirectXShaderCompiler/blob/4190bb0c90d374c6b4d0b0f2c7b45b604eda24b6/tools/clang/tools/dxcompiler/MachSiegbertVogtDXCSA.cpp#L178))
- Built using build.zig instead of 10k+ LOC CMake build system.
- [Simple C API](https://github.com/hexops/mach-dxcompiler/blob/main/src/mach_dxc.h) bundled into library as an alternative to the traditional COM API.

**Comment by Wumpf** [comment]
given that mach-dxcompiler is very experimental itself that would be doubly so in wgpu.
But behind a feature flag why not, imho worth a shot if someone wants to pick it up and see how maintainable that would be.

Still rooting though for [SpirV in DX12](https://devblogs.microsoft.com/directx/directx-adopting-spir-v/) becoming a thing asap 😄
