### ISSUE TITLE
linker error with the latest gfx-backend-dx12

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/wgpu#652]
**Description**
After upgrading to the latest gfx-backend-12 I'm now getting a linker error when building

**Repro steps**
Compile a example on windows

**Extra materials**
[message.txt](https://github.com/gfx-rs/wgpu/files/4591473/message.txt)

**Platform**
Windows 10

**Comment by grovesNL** [comment]
Something seems wrong here — it looks like spirv_cross is being built twice.

Could you try cleaning your target directory and rebuilding?

**Comment by JCapucho** [comment]
A clean build didn't solve it

**Comment by grovesNL** [comment]
Could you try updating dx11 too (`cargo update -p gfx-backend-dx12`)?

**Comment by JCapucho** [comment]
Updating dx11 fixed the issue
