### ISSUE TITLE
in ohos  unable to instantiate OpenGL ES proprietary backend 

### ISSUE THREAD

**Issue by songhuaixu** [gfx-rs/wgpu#6543]
[debug.txt](https://github.com/user-attachments/files/17747063/debug.txt)

**Platform**

Device info:emulator
Build info:emulator 5.0.0.102(SP1DEVC00E102R4P11log)
Fingerprint:9560957db866f36bc6e5b5fc941d309e218820a29f144a7ccfeb9ab258fe62ff
Module name:com.example.example
Version:1.0.0
VersionCode:1000000
PreInstalled:No
Foreground:Yes
Timestamp:2024-11-14 17:44:26.610
Pid:19533
Uid:20020049
Process name:com.example.example
Process life time:1s
Reason:Signal:SIGSEGV(SEGV_MAPERR)@0xffffffffffffffff 
Fault thread info:
Tid:19533, Name:.example.example
#00 pc 000000000016b924 /system/lib64/libdgles.z.so(d_eglCreateDebugMessageBuffer(void*, void*, void*)+156)(512dc534107928290754023d2432c540)
#01 pc 0000000000169220 /system/lib64/libdgles.z.so(d_eglCreateContext_special(void*, void*, void*, void*, int const*)+936)(512dc534107928290754023d2432c540)
#02 pc 0000000000157cec /system/lib64/libdgles.z.so(eglCreateContext+492)(512dc534107928290754023d2432c540)
#03 pc 0000000000036c04 /system/lib64/libEGL.so(OHOS::EglWrapperDisplay::CreateEglContext(void*, void*, int const*)+132)(4d24f2c7e30b611905832888a879b1c5)
#04 pc 000000000002a790 /system/lib64/libEGL.so(eglCreateContext+256)(4d24f2c7e30b611905832888a879b1c5)

**Comment by teoxoy** [comment]
Looks like a segfault in the driver. I don't think we can do anything about it.
