### ISSUE TITLE
The d3d12 backend silently falls back to FXC if loading DXC fails

### ISSUE THREAD

**Issue by nical** [gfx-rs/wgpu#6568]
I think that this behavior is desirable for most people (prioritizing having something running in as many situations as possible), but it's likely not the behavior that Firefox needs (it should be a hard error), so we may want to add some way to optionally specify that DXC is required and to fail if it isn't available.

**Comment by nical** [comment]
Relevant part of the code: https://github.com/gfx-rs/wgpu/blob/0b827769476b40f03477cdb9b3cf947fd0e70e2d/wgpu-hal/src/dx12/instance.rs#L93

**Comment by Elabajaba** [comment]
I never liked the automatic fallback but it was requested when I implemented support for DXC over returning an error.

IMO automatically falling back to FXC doesn't really make sense for a lot of cases where you explicitly request DXC as you end up with miscompilations if you use shader model 6.0+ features, or if you just have code that FXC doesn't like.

**Comment by teoxoy** [comment]
Something else we need to do is avoid creating an adapter if it doesn't support SM6. This will fail later when the driver receives DXIL and can't deal with it.

https://github.com/gfx-rs/wgpu/blob/48cc33a0457ac9181738781d4b55ea8037bd37a0/wgpu-hal/src/dx12/adapter.rs#L229-L233

**Comment by cwfitzgerald** [comment]
Such an adapter shouldn't exist, DXIL support was required in launch of dx12 iirc

**Comment by teoxoy** [comment]
DXIL & SM6 are part of WDDM 2.1, D3D12 was initially released with WDDM 2.
