### ISSUE TITLE
Texture view leaks regression

### ISSUE THREAD

**Issue by xiaopengli89** [gfx-rs/wgpu#6573]
**Description**
Texture view leaks regression after https://github.com/gfx-rs/wgpu/commit/8ba5c828313d8564d3a16fa4ea7ce7c6a575bae8 

**Repro steps**
```rust
let tex = dev.create_texture(&wgpu::TextureDescriptor {
    label: None,
    size: wgpu::Extent3d {
        width: 200,
        height: 200,
        depth_or_array_layers: 1,
    },
    mip_level_count: 1,
    sample_count: 1,
    dimension: wgpu::TextureDimension::D2,
    format: wgpu::TextureFormat::Rgba8Unorm,
    usage: wgpu::TextureUsages::TEXTURE_BINDING,
    view_formats: &[],
});

loop {
    let _view = tex.create_view(&Default::default());

    que.submit(None);
    dev.poll(wgpu::Maintain::Wait);
    std::thread::sleep(std::time::Duration::from_secs_f32(1. / 60.));
}
```

**Extra materials**
<img width="1537" alt="图片" src="https://github.com/user-attachments/assets/721e54f9-2304-46a5-9379-793b07d54c6e">

**Comment by teoxoy** [comment]
I don't see how 8ba5c828313d8564d3a16fa4ea7ce7c6a575bae8 would have caused this, the new `WeakVec` stores only weak refs.

**Comment by xiaopengli89** [comment]
> I don't see how [8ba5c82](https://github.com/gfx-rs/wgpu/commit/8ba5c828313d8564d3a16fa4ea7ce7c6a575bae8) would have caused this, the new `WeakVec` stores only weak refs.

I think it is caused by the implementation of `WeakVec`, we should set `scan_slots_on_next_push = true` when `empty_slots` is empty:
<img width="1589" alt="图片" src="https://github.com/user-attachments/assets/45d51ef4-381a-49ac-8c71-d9c819a4893d">

<img width="1880" alt="图片" src="https://github.com/user-attachments/assets/16b86ae3-7617-43a7-97fc-6aa5fa5e50c1">

**Comment by teoxoy** [comment]
Ah yes, that's a good point, `empty_slots` can be empty after we popped the last element.
