### ISSUE TITLE
Use a separate context per origin

### ISSUE THREAD

**Issue by DemiMarie** [gfx-rs/wgpu#6582]
**Is your feature request related to a problem? Please describe.**
The Linux GPU driver developers have stated in no uncertain terms that sharing a GPU context between origins is a browser bug.  The GPU context is the unit of security and out of bounds accesses by a shader cannot access or tamper with other contexts.

**Describe the solution you'd like**
WGPU should use a separate context per web origin.  This is the GPU equivalent of CPU site isolation.

**Describe alternatives you've considered**
Continue relying on the correctness of shader compilers and Naga-inserted bounds checks.

**Additional context**
See dri-devel IRC archives for more information.

**Comment by cwfitzgerald** [comment]
This should be a bugzilla ticket then, this project doesn't control the integration with Firefox, just the actual validation and execution.
