### ISSUE TITLE
Expose minSubgroupSize and maxSubgroupSize on WebGPU

### ISSUE THREAD

**Issue by ArthurBrussee** [gfx-rs/wgpu#6594]
Currently, minSubgroupSize and maxSubgroupSize are reported as 0 on WebGPU. The standard is still in flux of course but it does seem Dawn exposes these as per the proposal. (https://dawn.googlesource.com/dawn.git/+/59db6d898ffb6a5c68c654262b67416f171b4e22%5E%21/)

**Comment by teoxoy** [comment]
We do expose those limits if the GPU supports subgroups. On what configuration do you see them as 0?

**Comment by teoxoy** [comment]
Subgroups are not yet part of the core spec. IIUC, what dawn exposes in that CL is for node.js.

**Comment by ArthurBrussee** [comment]
Subgroups show up as a supported feature in the adapter, but over here: https://github.com/gfx-rs/wgpu/blob/a9f14c7a9045c3519b37837cc1280601f8419dd6/wgpu/src/backend/webgpu.rs#L793

Are mapped to their default values which are 0. Totally fair that this isn't supported yet, but caused some slightly hard to track down bugs as they're now "partially" supported, I'm sucesfully using them in some other areas where I don't need the min/max size (which is great!).

But yeah not much to be done if the there's no web bindings exposing this yet.

**Comment by teoxoy** [comment]
Yes, I would say this is out of scope, unless the feature is standardized. As we can't keep track of all experimental features especially of other implementations.
