### ISSUE TITLE
Strange usage of TextureFormatFeatureFlags::STORAGE_READ_WRITE

### ISSUE THREAD

**Issue by atlv24** [gfx-rs/wgpu#6599]
idk whats going on here but it looks wrong. if its not wrong it needs docs. why is read_write needed for read_only? why is write_only never checked?

https://github.com/gfx-rs/wgpu/blob/c22c062b54857e0598c0cccfb4d589406e1393b0/wgpu-core/src/device/resource.rs#L2496-L2506

**Comment by teoxoy** [comment]
That does look wrong, we need a new `TextureFormatFeatureFlags::STORAGE_READ` flag and `TextureFormatFeatureFlags::STORAGE_READ_WRITE` should be renamed to `TextureFormatFeatureFlags::STORAGE_WRITE`.

**Comment by ErichDonGubler** [comment]
Question: Looking at the spec. section on [`Plain color formats`](https://www.w3.org/TR/webgpu/#plain-color-formats) in [`Texture format capabilities`](https://www.w3.org/TR/webgpu/#texture-format-caps), it seems that `STORAGE_READ` and `STORAGE_WRITE` should be called `STORAGE_READ_ONLY` and `STORAGE_WRITE_ONLY`, respectively, with a separate `STORAGE_READ_WRITE` flag being necessary for determining if a flag can actually be used in a read/write scenario. Should this not be the final shape of feature bits?

**Comment by nical** [comment]
> it seems that `STORAGE_READ` and `STORAGE_WRITE` should be called `STORAGE_READ_ONLY` and `STORAGE_WRITE_ONLY`, respectively, with a separate `STORAGE_READ_WRITE` flag being necessary for determining if a flag can actually be used in a read/write scenario. Should this not be the final shape of feature bits?

That sounds correct to me.

**Comment by teoxoy** [comment]
Ah yes, you are right, I forgot we can't treat the presence of both `read` & `write` as `read_write`.

**Comment by teoxoy** [comment]
Apparently I forgot to click "comment" 😅

**Comment by atlv24** [comment]
Yeah im aware, thats what i raised here: #6601

i thought that we could choose the semantics though, as long as their consistent. im not aware how much of this is spec defined. using 3 bits for this when 2 is enough to represent all states just feels a bit weird.

what happens when you set both `READ_ONLY` and `READ_WRITE`? or other invalid combinations?

i feel like read_write should be represented by `READ | WRITE`, write_only should be represented by only `WRITE` being set, same with read_only.

**Comment by teoxoy** [comment]
The problem is that a format can support `read-only` & `write-only` but not `read-write` ([see table](https://www.w3.org/TR/webgpu/#texture-format-caps)). We probably need another `enum` to encode this and it will depend on the context if we need to use the new `enum` or the `bitflags`.

**Comment by atlv24** [comment]
> The problem is that a format can support `read-only` & `write-only` but not `read-write` ([see table](https://www.w3.org/TR/webgpu/#texture-format-caps)). We probably need another `enum` to encode this and it will depend on the context if we need to use the new `enum` or the `bitflags`.

isnt that the same as not setting `read` or `write`?

`read` + `write` = `read_write`
`read` = `read_only`
`write` = `write_only`
none = `read_only` + `write_only`

**Comment by teoxoy** [comment]
No flag should mean that it doesn't support/use storage usage at all.

**Comment by atlv24** [comment]
ahh okay. i am convinced that we should mirror the spec as closely as possible then, i'll get some PRs up this weekend
