### ISSUE TITLE
Handle 2024-08 spec. renames in image copy APIs

### ISSUE THREAD

**Issue by ErichDonGubler** [gfx-rs/wgpu#6617]
The WebGPU spec. has recently had a bunch of changes to the naming of several APIs related, with no otherwise substantial changes: [`gpuweb`#4838](https://github.com/gpuweb/gpuweb/pull/4838)

Of particular note is that while this change is backwards compatible for a JS implementation of WebGPU, this is _definitely breaking_ for us. 

**Connections**

- Firefox downstream tracking: [bug 1933328](https://bugzilla.mozilla.org/show_bug.cgi?id=1933328)

**Comment by cwfitzgerald** [comment]
I was just wondering if we should take them in the `wgpu` api at all, it would feel like kinda useless churn. Maybe rename + type alias and deprecate the old?

**Comment by ErichDonGubler** [comment]
@cwfitzgerald: I disagree that changing to match upstream's identifiers is "useless" but having `type OldName = NewName;` aliases with a `#[deprecated(…)]` attribute sounds interesting!

**Comment by cwfitzgerald** [comment]
Sorry there was a "to our users" omitted in there 😅

I think we just need to be careful as there is a bit of standing frustration about churn.
