### ISSUE TITLE
CI failure on Nightly: "error: legacy asm! syntax is no longer supported"

### ISSUE THREAD

**Issue by paulkernfeld** [gfx-rs/wgpu#664]
This is from `cargo test`, apparently due to the `generator` crate, brought in via `loom`. [Example CI failure](https://github.com/gfx-rs/wgpu/pull/663/checks?check_run_id=699955850). This is because `asm!` is being renamed to `llvm_asm!` ([tracking issue](https://github.com/rust-lang/rust/issues/70173)).

Possible solutions:

1. Fix the `generator` crate
2. Figure out some way to `cfg` away the `asm!` code. I'm not sure if `loom` even uses that stuff.
3. Don't run `loom` on nightly
4. Ignore the CI failures for now

**Comment by kvark** [comment]
We should probably file it to the generator crate, unless it's filed already.

**Comment by paulkernfeld** [comment]
Fair enough. I made PR https://github.com/Xudong-Huang/generator-rs/pull/20 to fix the issue, so hopefully it should be a matter of waiting until that change is merged and propagated upwards.

**Comment by paulkernfeld** [comment]
Now that `generator` has released 0.6.21, this is fixed. 👍
