### ISSUE TITLE
Firefox nightly has a serious bug in mapAsync that makes compute shaders unusable

### ISSUE THREAD

**Issue by rcoreilly** [gfx-rs/wgpu#6660]
**Description**

I'm not sure exactly how things are coordinated between this repo and the issues reported on firefox bugzilla, but I didn't see much discussion or activity on this bug reported 6 months ago, which we just hit up against when trying our compute shaders on the browser:

https://bugzilla.mozilla.org/show_bug.cgi?id=1900273

This makes compute shaders effectively unusable on firefox. Note that everything runs fine on wgpu_native, so the issue is somewhere in the interface between the browser and wgpu, and perhaps it has fallen between the cracks in these two teams?

**Repro steps**

The above link has a reproducible example.

**Expected vs observed behavior**

details above.

**Platform**

Happens on MacOS and Linux, most recent Firefox Nightly build: 135.0a1

**Comment by sagudev** [comment]
I already answered there, but it's Firefox fault as it polls only every 100ms. Servo did migrate this a while ago by using separate thread for polling: https://github.com/servo/servo/pull/32266

**Comment by cwfitzgerald** [comment]
Going to close this here, as it's an downstream issue
