### ISSUE TITLE
Release naga-23.1

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#6695]
My crates depend on Naga, and I would like to publish some of them.
Currently blocked by https://github.com/gfx-rs/wgpu/pull/5429 functionality, which isn't present in naga-23.0

**Describe the solution you'd like**
Release naga-23.1 with my changes included

**Describe alternatives you've considered**
Forking naga and publishing it is not an exciting opportunity to me.

**Additional context**
https://github.com/kvark/blade/pull/220

**Comment by cwfitzgerald** [comment]
This should just need to be backported - if you can backport the PR, we can release it.

**Comment by kvark** [comment]
@cwfitzgerald which branch should I target? I see 23.0.1 corresponding to a few releases but it doesn't include Naga. Should I create a new 23.1.0 branch for this?

**Comment by cwfitzgerald** [comment]
This should target `v23` and be either `23.0.2` or `23.1.0`, depending on the size of the change. Releasing only naga.

**Comment by kvark** [comment]
ok, here we go - #6711

**Comment by cwfitzgerald** [comment]
Done.
