### ISSUE TITLE
[core] `PassChannel` is not expresive enough to match spec

### ISSUE THREAD

**Issue by sagudev** [gfx-rs/wgpu#6700]
**Is your feature request related to a problem? Please describe.**
Spec says that you either specify readonly: true or pass ops: 
> If format has a depth aspect and this.[depthReadOnly](https://www.w3.org/TR/webgpu/#dom-gpurenderpassdepthstencilattachment-depthreadonly) is false:
    this.[depthLoadOp](https://www.w3.org/TR/webgpu/#dom-gpurenderpassdepthstencilattachment-depthloadop) must [be provided](https://infra.spec.whatwg.org/#map-exists).
    this.[depthStoreOp](https://www.w3.org/TR/webgpu/#dom-gpurenderpassdepthstencilattachment-depthstoreop) must [be provided](https://infra.spec.whatwg.org/#map-exists).
Otherwise:
    this.[depthLoadOp](https://www.w3.org/TR/webgpu/#dom-gpurenderpassdepthstencilattachment-depthloadop) must not [be provided](https://infra.spec.whatwg.org/#map-exists).
    this.[depthStoreOp](https://www.w3.org/TR/webgpu/#dom-gpurenderpassdepthstencilattachment-depthstoreop) must not [be provided](https://infra.spec.whatwg.org/#map-exists).

and wgpu-core currently does not support not passing ops.

**Describe the solution you'd like**
Something that would match specs better:
```rust
pub struct PassChannel<V> {
    pub load_op: Option<LoadOp>,
    pub store_op: Option<StoreOp>,
    pub clear_value: V,
    pub read_only: bool,
}
```

**Describe alternatives you've considered**
We could use more high level solution, but that would be harder to use in browser impl (not expressive enough for invalid cases, so something like this would make more sense in wgpu):
```rust
enum Chan {
    ReadOnly,
    Ops {load_op: LoadOp, store_op: StoreOp}
}
```

**Additional context**
Relevant CTS tests: https://gpuweb.github.io/cts/standalone/?q=webgpu:api,validation,render_pass,render_pass_descriptor:depth_stencil_attachment,loadOp_storeOp_match_depthReadOnly_stencilReadOnly:*

**Comment by sagudev** [comment]
We need to do validation as part of pass creation (`beginRenderPass`), more specifically in `fill_arc_desc`, so my plan is to for Arc to have resolved Arc channel (readonly + ops) while unarced (public) desc will have new interface to match the spec.

**Comment by teoxoy** [comment]
Sounds good to me.

Related: https://github.com/gfx-rs/wgpu/issues/2944
