### ISSUE TITLE
-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:1293: failed assertion

### ISSUE THREAD

**Issue by wentao** [gfx-rs/wgpu#6714]
**Description**

I'm using bevy 0.14.2 for a game. The game runs fine on desktop and Android and iOS without XCode attached.

This assertion failure only happens on iOS (sim or phone) when XCode is attached to the binary in debug mode.

**Repro steps**

Unfortunately I can't create a small code sample or repo to reproduce the bug. My current game is quite big with 10k lines of rust code.

**Expected vs observed behavior**

The assertion failure happens when bevy game transition from one state to another with the following log

```ignore
-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:1293: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
```

The editor shows the following line that is hitting the failure at `command.rs#1214`

```rust
unsafe fn dispatch(&mut self, count: [u32; 3]) {
        let encoder = self.state.compute.as_ref().unwrap();
        let raw_count = metal::MTLSize {
            width: count[0] as u64,
            height: count[1] as u64,
            depth: count[2] as u64,
        };
        encoder.dispatch_thread_groups(raw_count, self.state.raw_wg_size);   // <<------ here is the line hitting the failure
}
```

**Platform**

version of `wgpu`

```ignore
➜  ios git:(main) ✗ cargo tree | grep wgpu
│       │   │   └── wgpu-types v0.20.0
│       │   │   └── wgpu v0.20.1
│       │   │       ├── wgpu-core v0.21.1
│       │   │       │   ├── wgpu-hal v0.21.1
│       │   │       │   │   └── wgpu-types v0.20.0 (*)
│       │   │       │   └── wgpu-types v0.20.0 (*)
│       │   │       ├── wgpu-hal v0.21.1 (*)
│       │   │       └── wgpu-types v0.20.0 (*)
│   │   │   └── wgpu-types v0.20.0 (*)
```

**Comment by cwfitzgerald** [comment]
Sometime between 0.20 and trunk this has been fixed. We check if any dimension is zero and don't make the metal call.

**Comment by wentao** [comment]
@cwfitzgerald do you know which PR fixed the issue? I'd like to patch my local branch to fix the issue. Thanks!

**Comment by cwfitzgerald** [comment]
[Blame](https://github.com/gfx-rs/wgpu/blame/trunk/wgpu-hal/src/metal/command.rs#L1243) says #6494
