### ISSUE TITLE
Update REPO_MSRV to 1.83

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#6757]
Home 0.5.11, brought in tree by deno, wants rust 1.81. We should upgrade the repo CI target to 1.84 (latest) while leaving the core/hal MSRV as 1.76 for ff.

@ErichDonGubler was there some problem previously preventing this?

See https://github.com/gfx-rs/wgpu/pull/6756 where dependabot wanted to boop it. Should be unignored once this issue is closed.

**Comment by ErichDonGubler** [comment]
@cwfitzgerald: The main concern here is the sheer number of warnings that will be emitted for maintainers with new versions of Rust (failing CI?), and possibly users that are using `path` dependencies for consuming WGPU. There are quite a few new warnings that they'll get from `wgpu-{hal,core,types},naga`.

Other than that, I'm happy to split out the work I've done at for `wgpu` and downstream-er layers in the repo at <https://github.com/erichdongubler-mozilla/wgpu/tree/rust-lints-with-1.83> so we can land something that uses Rust 1.83.

**Comment by ErichDonGubler** [comment]
Just a quick fact check: Rust 1.84 hasn't come out of beta yet. I presume we're talking about 1.83, and _not_ 1.84. Is that right?

**Comment by cwfitzgerald** [comment]
> The main concern here is the sheer number of warnings that will be emitted for maintainers with new versions of Rust (failing CI?), and possibly users that are using path dependencies for consuming WGPU.

That will have to be fixed before we land the upgrade - the repo msrv is what CI runs. The exception is the core MSRV jobs, which will continue running on 1.76.

If there are some warnings that cannot be fixed with core's msrv, I think it's fine to wholesale disable them until we can bump msrv. 

> Other than that, I'm happy to split out the work I've done at for wgpu and downstream-er layers in the repo at https://github.com/erichdongubler-mozilla/wgpu/tree/rust-lints-with-1.83 so we can land something that uses Rust 1.83. 

Yeah that'd be great. 

> Rust 1.84 hasn't come out of beta yet. 

Yup, pulled a number out of my butt that I thought was right.

**Comment by ErichDonGubler** [comment]
The list of lints I'm aware of that will fire for this repo in Rust 1.84 even with my fixes for `wgpu` and downstream:

* `unexpected_cfgs` for everything generated by `cfg_aliases`, along with our custom `wgpu_*` `cfg`s. I'm not sure if splitting this via MSRV is possible, but I guess we'll see!
* `clippy::manual_c_str_literals`, which will need to be suppressed until we reach MSRV 1.77 everywhere.
* `clippy::large_enum_variant` for `BindingLayoutSource::Derived`. I fixed this by `Box`'ing it, and if that sounds acceptable, I can file a PR for it right now.

**Comment by cwfitzgerald** [comment]
Alright, I'll see if I can give this a spin when I'm feeling particularly industrious
