### ISSUE TITLE
[core] remove validation errors from logging

### ISSUE THREAD

**Issue by sagudev** [gfx-rs/wgpu#6794]
**Is your feature request related to a problem? Please describe.**
wgpu-core is very spammy when running CTS or other invalid webgpu stuff via browser (servo), where our default logging level is warning. We know that errors happen, but we handle them by raising validation errors.

**Describe the solution you'd like**
Feature that would change all core/naga error into infos. There are already similar features in core: https://github.com/gfx-rs/wgpu/blob/53f40794f275329a48efc7d1c637c91b8e51327d/wgpu-core/Cargo.toml#L44-L45

**Describe alternatives you've considered**
We could set filters in servo, but that would make overriding them harder.

**Comment by ErichDonGubler** [comment]
TBH, I think that many of the errors we emit are completely unnecessary in the face of validation errors. Shader compilation errors, for instance, really ought to never show up in WGPU's `log`; applications should be responsible for doing that themselves, if they want.

Hot take: I suggest we instead _remove_ any logging that's redundant with reported errors wholesale.

☝🏻 CC @gfx-rs/wgpu, @gfx-rs/naga.

**Comment by nical** [comment]
Or maybe remove any error log that correspond to validation that is spelled out in the spec, but keep things that are a bit more unpredictable like OOMs or unexpected errors from the underlying API.

**Comment by jimblandy** [comment]
It sounds like we have general agreement that a lot of that logging could come out. I'd rather not add a feature to keep stuff that nobody actually wants. So maybe the fix here is to just take logging out, not make it conditional.

**Comment by sagudev** [comment]
https://github.com/gfx-rs/wgpu/pull/6817 removes errors I had in mind, someone should still reevaluate others.
