### ISSUE TITLE
Expose some of the Rusty types to the outside

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#684]
**Is your feature request related to a problem? Please describe.**
The descriptors, such as `RenderPipelineDescriptor` contain raw pointers for the ability to be called from C API. The problem is that there are places where we need pure Rust version of these structures. One of the places is the [trace module](https://github.com/gfx-rs/wgpu/blob/4c136418ff20ed52f4c56b6af3ec419d356a9ac4/wgpu-core/src/device/trace.rs#L110).
Another place is Servo's implementation - https://github.com/servo/servo/pull/26714

**Describe the solution you'd like**
Investigate if we can expose some of these types.

**Describe alternatives you've considered**
Each client defines their own types.

**Comment by GabrielMajeri** [comment]
I think this has been superseded by #689 and #765

**Comment by kvark** [comment]
And #851 :)
