### ISSUE TITLE
General direction on the API of exposed structures

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#689]
(this is a recap of a discussion on #wgpu:matrix.org with @cwfitzgerald). The question is - what kind of structures/API `wgpu-core` needs to have in order to provide minimum friction to all the clients:
  1. Gecko - main client, uses it's own C API wrapper (not wgpu-native)
  2. wgpu-rs
  3. Servo - uses the Rust API of wgpu-core
  4. wgpu-native
  5. wgpu's player

Currently, wgpu-core expose `#[repr(C)]` FFI-friendly structures in order to re-use them in both Rust and C clients. Re-using in Rust isn't possible whenever there are nested structures, and we have this case quite often. Another problem is extensions: in wgpu-native, the API has to be aligned to `webgpu-headers` (see https://github.com/gfx-rs/wgpu-native/issues/6), which has a Vulkan-style `pNext` chains of structs. All in all, there isn't a single representation that all the clients of `wgpu-core` will be happy about, and we need to rethink what we expose.

The discussion ended up with a plan to have all the API structures in wgpu-core to be Rusty. As such, they would have Rust references instead of pointers. They could have algebraic types. With some generic arguments we should be able to re-use them in:
  - wgpu-rs
  - wgpu's player
  - Servo's internal types (i.e used for serialization)

With regards to extensions, these wgpu types would have to include everything we potentially support (since we don't need to care about anything we don't support).

One property of this approach that I'm particularly excited is that it would allow us to have the Rust API in `wgpu-core` to be safe. Today, it was in a kinda weird state where the logic is safe, but formally we can't expose it safely because it works with raw pointers on the input.

wgpu-native would have to have its own types anyway, with the `pNext` chains and such. Gecko's `wgpu_bindings` would need to define its own types as well. I hope that doesn't get a push back from other Gecko engineers, we'll see how it turns out in practice.

If anybody has concerns about this, please shout out! Otherwise, let's start the conversion. Note: not marking this for 0.6 milestone, since this is a big task.

**Comment by GabrielMajeri** [comment]
Would it be possible to provide more detailed instructions, or break this up in multiple smaller tasks/issues?

I'm guessing the first step is to search for raw pointers in publicly exposed structs, and replace those with references + lifetimes?

**Comment by kvark** [comment]
Adding to the milestone as it affects the API, and even though we could postpone some of this to later releases, it would be weird to change the API right after we make one.

@GabrielMajeri thank you for asking for clarifications here, this is much needed!
First, you are right, we need to check the API and at least make a list of things that need to be converted. Roughly speaking, this will be all the descriptors (used to create objects).
Secondly, the more detailed instructions, I'll try to explain here.
 - We replace raw pointers by references.
 - If the structure *can be* C-compatible without compromising Rust aspect of it, we make it so. E.g. we put `repr(C)` and we use things like `Option<&'a Something>` and other C-compatible structs. Currently there is no way to verify that the C header is going to be successfully generated however - this requires hooking up `wgpu-native`, which got stuck with a few issues. Hopefully, we can reason about what can and what can't be C compatible in the review.
  - If the structure can be made generic over the type of ID it works with, we should make it generic. See [RenderPassColorAttachmentDescriptorBase](https://github.com/gfx-rs/wgpu/blob/43c67ac59c2dedaa4d78601bc460aab7c3257973/wgpu-types/src/lib.rs#L1128) for example. This allows all the clients to re-use these structures (player, wgpu-native, wgpu-rs, Servo, etc).

Example - #696
