### ISSUE TITLE
`Global<GlobalIdentityHandlerFactory>::drop` is very slow

### ISSUE THREAD

**Issue by AlexCharlton** [gfx-rs/wgpu#693]
**Description**
`Global<GlobalIdentityHandlerFactory>::drop` is very slow on master, whereas it was not in the 0.5 release. In particular, the call to `gfx_backend_dx12::device::destroy_swapchain` takes over 3 seconds on my computer.

From the commit history, this seems to have been introduced in https://github.com/gfx-rs/wgpu/commit/831d908663f232e992baec30aaa5ecd45d148da3

It seems likely that this was a latent issue with `gfx_backend_dx12` that only surfaced with that commit, but I'm filing this issue here because I'm not sure what the correct resolution is. All I can say is that 3s seems like an exceedingly long time to free a resource.

**Platform**
Windows 10

**Comment by kvark** [comment]
Thank you for the issue!
3 seconds is not expected there at all. Could be a problem with DX12 backend in particular. I think wgpu is doing the right thing here.

**Comment by AlexCharlton** [comment]
Just tried on master and `drop` is down to a perfectly unnoticeable 13ms. I suppose it was fixed upstream, so I'm closing this.
