### ISSUE TITLE
wgpu_render_pass_set_index_buffer and wgpu_render_pass_set_vertex_buffer do not support size = 0

### ISSUE THREAD

**Issue by DagAgren** [gfx-rs/wgpu#738]
The spec at https://gpuweb.github.io/gpuweb/#dom-gpurenderencoderbase-setindexbuffer says, for setIndexBuffer and setVertexBuffer, "If size is zero, the remaining size (after offset) of the GPUBuffer is used."

However, this seems to be currently unsupported in wgpu, and using 0 will cause draw commands to fail because indices are compared against the literal 0 value instead of the size of the buffer.

**Comment by kvark** [comment]
Strictly speaking, on `wgpu` size these receive `wgt::BufferSize` type. If you need the semantics of "0" to be "the remaining part", you should pass `wgt::BufferSize::WHOLE`. So currently, this is a problem with wgpu-native.

**Comment by kvark** [comment]
This has been changed now (again), and we use `Option<NonZero>` which effectively means that 0 == WHOLE_SIZE
