### ISSUE TITLE
draw_indirect_*_count Extension

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#742]
**Is your feature request related to a problem? Please describe.**

When using indirect rendering, there are two ways of culling draw calls. Either you can issue zero sized draws, which have a non-zero performance penalty, or you can compact away all the zero sized draws. However if you compact the draws, the cpu only knows the starting amount, not the amount of draws after culling. 

To remedy this, DX12 and VK have a way of specifying a "count" buffer which is a buffer which just contains the count of draws. This is unfortunately not supported on metal at all.

VK supports this as `VK_KHR_draw_indirect_count`'s [`vkCmdDrawIndirectCountKHR`](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdDrawIndirectCount.html). DX12 supports this as a (currently nulled out) pointer in ExecuteIndirect.

**Describe the solution you'd like**

An implementation of a `draw_indirect_count` and `draw_indexed_indirect_count` in wgpu and gfx-hal.

**Describe alternatives you've considered**

Zero sized draws. You can also ship the count back and forth, but that's high latency on non-uma systems.

**Additional context**

I believe this could be implemented in gfx-hal as a non-breaking change in the HAL as long as we provide a `unimplemented!()` default implementation to prevent breaking any downstream crates, we can remove that on master for 0.6.

I also need to see what kind of buffer types the count buffer needs to be, and we would need to enforce this in wgpu.

These might have to be made unsafe, as if the count is massive it'll probably cause out of range accesses.

**Comment by kvark** [comment]
Metal has a thing called [Indirect Command Buffers](https://developer.apple.com/documentation/metal/indirect_command_buffers?language=objc), which can be recorded from the GPU. We plan to use them in wgpu for backing `RenderBundle`, but I wonder if they'll also help in your case?

**Comment by cwfitzgerald** [comment]
Unfortunately that's a bit too platform specific to be of use, kinda like `VK_NV_device_generated_commands`. Both are amazingly awesome, but would require specializing for each platform due to each one having a different format in memory, and the compute shaders have to write them directly.

**Comment by kvark** [comment]
I mean, what if gfx-backend-metal would implement `VK_KHR_draw_indirect_count` by internally recording an indirect command buffer from a compute shader (that loads the counts buffer)? Anyhow, I'm just hypothesizing. It's totally fine for an extension to be unsupported on Metal.

**Comment by cwfitzgerald** [comment]
Now that's an idea! I would really love for this extension to be supported on all platforms, so that definitely sounds like a good idea to pursue!
