### ISSUE TITLE
Unify / remove duplication between public API and `trace` types

### ISSUE THREAD

**Issue by GabrielMajeri** [gfx-rs/wgpu#765]
There are some types being duplicated in order to implement the API call tracing and replay features.

## Example

The descriptors used in pipeline creation, which borrow their data
https://github.com/gfx-rs/wgpu/blob/438ac00115ab433fcda84ac089837dee273ba460/wgpu-core/src/pipeline.rs#L28-L32
are duplicated as owned variants
https://github.com/gfx-rs/wgpu/blob/438ac00115ab433fcda84ac089837dee273ba460/wgpu-core/src/device/trace.rs#L68-L73

## Solution

@kvark mentioned in a [comment](https://github.com/gfx-rs/wgpu/pull/763#issuecomment-654440980), it might be interesting to try using `Cow` in the API, and remove the duplication:
```rust
pub struct VertexStateDescriptor<'a> {
    pub index_format: IndexFormat,
    pub vertex_buffers: Cow<'a, [VertexBufferLayoutDescriptor<'a>]>,
}
```

This should probably be done after progress happens on #689, since the public API types will undergo some changes.

**Comment by GabrielMajeri** [comment]
PR https://github.com/gfx-rs/wgpu/pull/822 is a good example of how `Cow` can be used to unify the API and trace types.

**Comment by kvark** [comment]
@GabrielMajeri it's this done now, basically? Looking at the `trace.rs`, it no longer defines any structures

**Comment by GabrielMajeri** [comment]
@kvark You're right, I didn't realize the extent of that PR. The redundancies between the public API and trace types are gone!
