### ISSUE TITLE
Define and Test MSRV

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#780]
**Is your feature request related to a problem? Please describe.**

Due to our ties with gecko and servo, we do have a MSRV, we just do not define it formally or test for it.

**Describe the solution you'd like**

Define a MSRV in readme and add CI for it.

**Describe alternatives you've considered**

As of right now our MSRV is sorta just "stable" as we don't test older versions.

**Additional context**

Discussion re #774.

**Comment by cwfitzgerald** [comment]
Poked this a bit, a minor implementation issue will be that we assume limit < adapter.limit is fine, but this limit will break that assumption.

**Comment by cwfitzgerald** [comment]
The above comment was posted to the wrong issue :\

@kvark what I need from you is what the MSRV is, and I can tackle the implementation of this.

**Comment by kvark** [comment]
Based on https://github.com/ron-rs/ron/issues/256#issuecomment-657999081, it seems like choosing 1.34 or 1.41 would be reasonable for now.

**Comment by cwfitzgerald** [comment]
Alright, let's go with 1.41, master compiles on it, and I think it's generally reasonably new for our purposes.

**Comment by cwfitzgerald** [comment]
Just a status update: we currently require 1.46 to build due to our use of `matches!` and `const`.

**Comment by cwfitzgerald** [comment]
Currently up to 1.48 due to the use of `std::future::ready` in wgpu-rs.
