### ISSUE TITLE
Expose Max Sample Count

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#804]
**Is your feature request related to a problem? Please describe.**
Different platforms have strange MSAA requirements, so there needs to be some way of exposing this through wgpu so programs can not crash. This ultimately needs to be a problem that is solved by WebGPU for exposing properly, but we can lead off with a temporary api which can be adjusted later. https://github.com/gpuweb/gpuweb/issues/108 is mildly related, though old.

**Describe the solution you'd like**
Pass forward framebufferColorSampleCounts, framebufferDepthSampleCounts, and framebufferStencilSampleCounts from gfx-hal as native-only limits.

**Describe alternatives you've considered**
Not supporting this isn't ideal as it requires the developer to accurately know what hardware they are on, and what features it supports. This is a little silly when we can just ask the api.

**Additional context**
OSX seems to not support > 4x at least on macbook pros. Phones may also have strange requirements.

**Comment by kvark** [comment]
Thank you for filing this! Let's not rush into exposing all the nasty gfx-rs/Vulkan limits. This would negatively affect our user's ability to write portable applications.
I suggest we expose a simple limit, and it's a mask of supported (power of two) sample counts (similar to vulkan).
I wrote the spec proposal for that in https://github.com/gpuweb/gpuweb/pull/932

**Comment by cwfitzgerald** [comment]
Poked this a bit, a minor implementation issue will be that we assume limit < adapter.limit is fine, but this limit will break that assumption. Nothing we can't work around, just needs a nice setup.

**Comment by kvark** [comment]
yeah, it's not a number, it's a mask, so the "better" rule for the limit is different
