### ISSUE TITLE
Metal backend compile error: ^ expected struct `cocoa::foundation::NSRange`, found a different struct `cocoa::foundation::NSRange`

### ISSUE THREAD

**Issue by johnnyw** [gfx-rs/wgpu#820]
**Description**
Trying to build wgpu examples on macOS results in cocoa version conflict build errors.

**Repro steps**
On macOS, clone the master repo and run:
```
cargo run --example cube
```

**Expected vs observed behavior**
Expected: should run cube demo
Observed: Failed to compile with errors:
```
...command.rs:2741:25
     |
2741 | /                         NSRange {
2742 | |                             location: 0,
2743 | |                             length: raw.mipmap_level_count(),
2744 | |                         },
     | |_________________________^ expected struct `cocoa::foundation::NSRange`, found a different struct `cocoa::foundation::NSRange`
     |
     = note: perhaps two different versions of crate `cocoa` are being used?
```

Can confirm by observing `Cargo.lock` that two versions of `cocoa` crate are being imported.

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
cargo 1.44.1 (88ba85757 2020-06-11)
rustc 1.44.1 (c7087fe00 2020-06-17)
macOS 10.15.5
Attempted with wgpu 0.5.2 and master

**Comment by kvark** [comment]
Sorry about that! It was caused by https://github.com/gfx-rs/metal-rs/pull/160 , and metal-0.18.1 is now yanked
