### ISSUE TITLE
Validation error DescriptorSetNotBound when using (compute-)pipline without push constants after one with

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/wgpu#821]
The moment I start using push constants in a compute pipeline, some (unclear what's necessary for that) following compute pipelines (in the same pass) that don't use push constants will give me this validation error:

```
  VALIDATION [UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound (-840888189)] : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x1928a4a6530, name = Encoder: Frame Main, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | VkPipeline 0xa7e05300000000d6[] uses set gfx-rs/wgpu-rs#1 but that set is not bound.
    object info: (type: COMMAND_BUFFER, hndl: 1728896984368, name: Encoder: Frame Main)
```
everything else equal, the moment I stop using push constants the problem goes away again

After the validation error the app gets stuck.
I created a trace by running it in an optimized build (no validation error) which seems to run fine. Resulting trace has a lot of noise, but the player is able to repro the issue for me (using wgpu-core a0ed09a6a83dc0d16c6ad711cf139a5fcfbb9c35)

[trace.zip](https://github.com/gfx-rs/wgpu-rs/files/4943384/trace.zip)

**Comment by cwfitzgerald** [comment]
Whoops this shouldn't have closed it.

**Comment by Wumpf** [comment]
Fix confirmed with the latest incarnation of @cwfitzgerald fix PR!
