### ISSUE TITLE
Spamming `queue.write_texture` can result in an OOM error.

### ISSUE THREAD

**Issue by StarArawn** [gfx-rs/wgpu#828]
**Description**
Spamming calls to `queue.write_texture` in a thread pool causes OOM errors.

**Repro steps**
The code can be found here:
https://github.com/StarArawn/harmony

To run:
  1. Download GLTF file from: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza/glTF
  2. Run hello-cube example after changing the hello-cube.rs file to load the sponza mesh.

**Expected vs observed behavior**
`write_texture` shouldn't cause OOM issues when there is plenty of memory left. It also appears to create larger buffers than what is required to upload the texture data.

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.
- Macos(AMD Radeon Pro 5300M 4 GB)/Windows 10(geforce 970)
- wgpu master(0c7c3afebb12bf411d6964887b85e5fd152057f5)

**Extra materials**

I essentially have something like: 
```rust
pool.spawn_ok(async move {
  let data = load_image_data().await;
  let texture = create_texture(data);
  cache.insert(texture);
});
```

I see these errors in the console:
```
All suitable heaps are exhausted.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: AllocationError(OutOfMemory(Device))'
```

Gist of memory:
https://gist.github.com/StarArawn/86144cdd31b7f09ef09554db7daaff8d

One soultion was to try and block until `write_texture` is complete I used this code right after `write_texture`:
```rust
queue.submit(None);
device.poll(wgpu::Maintain::Wait);
```

However this appeared to only have a 50% chance of working on metal. When it fails it just hangs the entire app without any errors. On vulkan there is a similar situation but even when waiting on `write_texture` I'm unable to get it to run successfully.

**Comment by StarArawn** [comment]
I was only able to reproduce by creating a texture right before calling write_buffer in the same scenario above. I did some debugging and this is some of the info I found:

It fails here:
```rust
let memory = self
            .mem_allocator
            .lock()
            .allocate(
                &self.raw,
                &requirements,
                gfx_memory::MemoryUsage::Staging { read_back: false },
                gfx_memory::Kind::Linear,
            )
            .unwrap();
```

Staging Requirements:
```rust
size:4194304
alignment:256
type_mask:15
```

Buffer:
```rust
size:4194304
usage:{bits:1}
```

**Comment by cwfitzgerald** [comment]
Is this still a problem on master? In addition, are you sure you're not running out of memory?

**Comment by kvark** [comment]
We moved to gpu-alloc since then. Please re-open if this is still a problem!
