### ISSUE TITLE
Make VertexFormat::size() a const fn when rust 1.46 drops

### ISSUE THREAD

**Issue by bootra-dev** [gfx-rs/wgpu#836]
Original issue: https://github.com/gfx-rs/wgpu/issues/801 

When I implemented https://github.com/gfx-rs/wgpu/pull/802 I did not consider that the vertex_attr_array macro could not longer be used in a const environment. Rust 1.46 will allow match in const functions, so this can be resolved then.

**Comment by cwfitzgerald** [comment]
Related #780

**Comment by cwfitzgerald** [comment]
Solved by #1048
