### ISSUE TITLE
Labels sometimes don't show up in xcode.

### ISSUE THREAD

**Issue by StarArawn** [gfx-rs/wgpu#837]
**Description**
When setting a label on a `wgpu::CommandEncoderDescriptor` it's seemingly random which ones will show up with a label in xcode. 

**Repro steps**
Any of the examples here:
https://github.com/StarArawn/harmony/

**Expected vs observed behavior**
The label to show up in xcode frame debugger.

**Extra materials**
<img width="274" alt="Screen Shot 2020-07-24 at 11 11 23 AM" src="https://user-images.githubusercontent.com/6656977/88408928-3d982a80-cda2-11ea-95aa-9a60395d7c24.png">

**Platform**
Master wgpu
macos 10.15.4
xcode 11.6

**Comment by cwfitzgerald** [comment]
Going to close as stale, if this is still a problem, please refile!
