### ISSUE TITLE
I want to enable serialization and deserialization without the runtime overhead of trace and replay.

### ISSUE THREAD

**Issue by bootra-dev** [gfx-rs/wgpu#842]
Perhaps this is already possible, but not from what I can see. (reference issue: https://github.com/gfx-rs/wgpu-rs/issues/284 and https://github.com/gfx-rs/wgpu/pull/619#discussion_r417727801) 

In an ideal world, I could enable the serde feature in wgpu-rs, and just have serialization/deserialization on my types, without any runtime code added. 

To resolve this issue, I would add the serde feature back to wgpu (in addition to trace and replay). You could also resolve this issue by adding a initialization option at runtime to disable replacy and trace features so you could effectively just have serialization/deserialization.

**Comment by kvark** [comment]
There is zero run-time overhead for `trace`/`replay` features enabled in `wgpu`. Overhead only comes into play when the tracing is *enabled*, i.e. when the device gets a path of a folder in the parameters.

**Comment by bootra-dev** [comment]
I see. To clarify, you're referring to the trace_path parameter in https://wgpu.rs/doc/wgpu/struct.Adapter.html#method.request_device?

**Comment by kvark** [comment]
Correct, this one
