### ISSUE TITLE
Compressed Textures

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu#852]
Per https://github.com/gpuweb/gpuweb/issues/144#issuecomment-456897457, compressed textures will be included in the WebGPU spec. However, I can't find much else referencing them. Are there plans to add support to wgpu-rs/wgpu-core in the near term? Or even a sense of what form they may take?

**Comment by kvark** [comment]
@FuriouZz sorry, looks like I missed your comment 😓  See https://github.com/gfx-rs/wgpu-rs/issues/491 for the basis issue.
