### ISSUE TITLE
Reduce size of storage Element

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#858]
**Is your feature request related to a problem? Please describe.**
With the introduction of `Error` variant in #776 , we transitioned the element from an `Option<(T, Epoch)>` into a separate `enum Element` with 3 variants. Now it consumes more space, as demonstrated by [the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9ee2cff0f2556c2de1e95ceb8ef290eb).

**Describe the solution you'd like**
It appears that currently `Option` works better than a user-space enum, because it automatically supports non-zero types. Thus, if `T` happens to have a non-zero-typed member, `Option<T>` has the same size as `T`, essentially being free.
One way to tackle this would be to wait till Rust becomes smarter when it comes to enums.
Another - to heavily rely on `Option` type internally, and it requires two steps:
  1. Use `Option<(Epoch, Option<T>)>` instead of `Element`
  2. Switch `Epoch` to be `NonZeroU32`

**Describe alternatives you've considered**
We could also hide all the error-related logic behind an `error` feature. `wgpu-rs` would build and run without it, but browsers would still use it. I like that solution less because it doesn't help the browsers, and diverging code paths are not desired.

**Additional context**
This may not be such a big deal at all, just something to keep an eye on.

**Comment by cwfitzgerald** [comment]
We basically never bottleneck ourselves in the storage, so I'm going to mark this as stale, especially considering the upcoming storage upgrade.
