### ISSUE TITLE
Remove the battery dependency

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#859]
**Is your feature request related to a problem? Please describe.**
We currently don't use this dependency, and we can't find a nice way to expose it. It has quite a few dependencies.

**Describe the solution you'd like**
Let's remove the dependency completely. The users can hook it up and select the proper adapter preference themselves.

**Describe alternatives you've considered**
Propagating `battery` dependency to `wgpu-rs`.

**Additional context**
Related to #463, #446, and https://github.com/gfx-rs/wgpu-rs/pull/406

**Comment by GabrielMajeri** [comment]
Does this involve the removal of the `power.rs` module?

**Comment by kvark** [comment]
Correct!
