### ISSUE TITLE
API traces of crashed applications are not closed properly

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#861]
**Is your feature request related to a problem? Please describe.**
A trace is a sequence of actions. The sequence must end with "]". If an application crashed, it doesn't properly close the trace. See https://github.com/gfx-rs/wgpu/issues/785#issuecomment-667682847

**Describe the solution you'd like**
~~In `player`, if RON is failed to load, we should attempt to just add the trailing "]" and load again.~~
We should ensure that "]" is inserted on the drop of the tracing logic. There shouldn't be any manual patching on the player side.

**Describe alternatives you've considered**
~~Not doing anything - that's annoying to the users.~~
Do the patching on the player side.

**Additional context**
The `Drop` is already implemented, but not called because of https://github.com/rust-windowing/winit/issues/1850
Patching the RON is also related to backend substitution. The playtesting infra replaces the backend of a capture with the current one, and the player could do that too, automatically.

**Comment by Kriyszig** [comment]
Can I give this issue a try?
I can create a preliminary patch which adds a trailing ']' if the RON loading fails and tries to load it again.
If there is a more novel way to go about this maybe we can discuss it over the patch?
Thank you

**Comment by kvark** [comment]
Something I missed previously - we need to double-check if `]` can be inserted during writing. Maybe in a `drop()` implementation for something?

**Comment by kvark** [comment]
I looked at this some more. I believe the current logic we have is already correct, and traces should be auto-closed. What's blocking is behavior, however, are these upstream issues:
  - https://github.com/zakarumych/gpu-descriptor/pull/11
  - https://github.com/rust-windowing/winit/issues/1850 (Apple systems only)

**Comment by kvark** [comment]
The descriptor update has been published in https://crates.io/crates/gpu-descriptor/0.1.1. That should get us the desired behavior on Windows and Linux.
The fix for the winit issue on Apple is coming in https://github.com/rust-windowing/winit/pull/1853
We can consider this addressed (since we don't depend on `winit`).
