### ISSUE TITLE
Use a new ID on command_encoder_finish()

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#867]
**Is your feature request related to a problem? Please describe.**
When implementing the error model in Servo, @kunalmohan faced a problem of tracking which encoders are error encoders, and how to work with the corresponding command buffers.

**Describe the solution you'd like**
Instead of re-using the same ID for command encoder and command buffer, we can always accept a new ID, and just move the entry over (possibly marking the old entry as Error).

**Describe alternatives you've considered**
Don't do anything, let Servo handle it. That's the temporary plan for now until this issue is resolved.

**Additional context**

**Comment by cwfitzgerald** [comment]
Given servo's status and the age of this issue, I'm going to close this. Please reopen if this is stilla  problem.
