### ISSUE TITLE
create_texture with too many mip levels triggers validation error

### ISSUE THREAD

**Issue by benfrankel** [gfx-rs/wgpu#894]
**Description**
Calling `Device::create_texture` with a `TextureDescriptor` that has `mip_level_count > 32 - width.min(height).min(depth).leading_zeros()` (aka number of times you can do `width >>= 1; height >>= 1; depth >>= 1;` before they all reach `0`) triggers a validation error (`VUID-VkImageCreateInfo-mipLevels-00958`).

**Repro steps**
1. Patch `wgpu-rs`'s mipmap example in `examples/mipmap/main.rs` with `let size = 1 << (mip_level_count - 1) - 1;` so the generated texture is too small for `9` mipmap levels.
2. Run the example (`cargo run --example mipmap`).

**Expected vs observed behavior**
- **Expected:** Error or panic.
- **Observed:** Validation error.

**Platform**
- Linux 5.7.12-arch1-1
- X11
- wgpu v0.6.0

**Comment by benfrankel** [comment]
Tried passing `mip_level_count` of `0`, got `VUID-VkImageCreateInfo-mipLevels-00947` and a segfault.

**Comment by kvark** [comment]
If we are computing the mipmap level count incorrectly, it should be easy to fix! Would you want to try making a patch?

**Comment by benfrankel** [comment]
I took a closer look at #893, specifically this line:

```rust
if mip_level_count == 0 && mip_level_count > kind.compute_num_levels() as u32 {
```

The `&&` should be an `||`, but otherwise, that should actually fix this issue completely (mipmap level count seems to be computed correctly). I'll make a patch to fix the `&&` and improve the `InvalidMipLevelCount` error message.
