### ISSUE TITLE
Should Sampler allowed_usage be LOAD instead of empty()?

### ISSUE THREAD

**Issue by crsaracco** [gfx-rs/wgpu#899]
**Disclaimer**

I'm quite new to low-level graphics stuff, so I might have 0% idea what I'm talking about.

I'm also following along with https://sotrh.github.io/learn-wgpu/, which seems to be using an older version of `wgpu`. The tutorial itself may be wrong, or my slight fixes to migrate to wgpu 0.6.0 may be wrong, etc. etc.

**Description**

I'm currently working on the ["Textures and bind groups"](https://sotrh.github.io/learn-wgpu/beginner/tutorial5-textures/) chapter, and it seems like the validation stage doesn't like something about either my shader, or the code binding the sampler to that shader:

`thread 'main' panicked at 'error in stage FRAGMENT: error matching global binding at index 1 in set 0 against the pipeline layout: load/store access flags LOAD don't match the shader'`

(set 0, index 1 is my texture sampler, following along with [the tutorial](https://sotrh.github.io/learn-wgpu/beginner/tutorial5-textures/#the-bindgroup).)

With some light debugging, I think the relevant areas of code are:

 - the error comes from [here](https://github.com/gfx-rs/wgpu/blob/5b67fe71f8a5160f2b4e5d3bce0eef0575c12579/wgpu-core/src/validation.rs#L57),
 - because [this](https://github.com/gfx-rs/wgpu/blob/5b67fe71f8a5160f2b4e5d3bce0eef0575c12579/wgpu-core/src/validation.rs#L798-L804) determined that `usage` isn't supported by `allowed_usage`,
 - because [samplers seemingly don't support any usage types?](https://github.com/gfx-rs/wgpu/blob/5b67fe71f8a5160f2b4e5d3bce0eef0575c12579/wgpu-core/src/validation.rs#L204-L213), and I guess my shader / bind group wants `LOAD` instead for some reason?

If I change `Ok(naga::GlobalUse::empty())` to `Ok(naga::GlobalUse::LOAD)` [here](https://github.com/gfx-rs/wgpu/blob/5b67fe71f8a5160f2b4e5d3bce0eef0575c12579/wgpu-core/src/validation.rs#L207), though, it seems to work fine.

**Repro steps**

My code's super messy, I can clean it up and make a gist if it turns out I might in fact be doing something wrong. :)

**Expected vs observed behavior**

If I change `Ok(naga::GlobalUse::empty())` to `Ok(naga::GlobalUse::LOAD)` [here](https://github.com/gfx-rs/wgpu/blob/5b67fe71f8a5160f2b4e5d3bce0eef0575c12579/wgpu-core/src/validation.rs#L207), my code seems to work and shows me the texture. I'm not sure if that's what the fix *should* be, or if my code is wrong -- but I don't see any user-accessible APIs to change what my sampler's usage should be?

**Platform**

 - Arch Linux (targeting Vulkan, I imagine)
 - `wgpu` 0.6.0 (also tried checking out the repo and using that, both give the same error)
 - GTX 980 Ti

**Comment by kvark** [comment]
Yes. This is already addressed in #898
We'll make a patch version with updated Naga once we have a better picture of how the validation is looking.

**Comment by crsaracco** [comment]
Ahhh! ok, sweet. Thanks!
