### ISSUE TITLE
Vulkan queue is signaling a semephore already signaled by itself

### ISSUE THREAD

**Issue by PENGUINLIONG** [gfx-rs/wgpu#913]
I found that if I `poll` the device after I submit a command buffer to the queue affiliated to the device, I would receive the following error.

```
[2020-08-31T16:21:19Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress (0)] : VkQueue 0x18d8da75e08[] is signaling VkSemaphore 0xe81828000000000d[] that was previously signaled by 
VkQueue 0x18d8da75e08[] but has not since been waited on by any queue.
    object info: (type: SEMAPHORE, hndl: 16724161196705447949)
```

I guess the backend has cleared some semaphore states while wgpu is unaware of it. Probably the backend should reset the semaphore during the `poll`?

**Comment by cwfitzgerald** [comment]
Closing as out of date.
