### ISSUE TITLE
Storage buffer is almost all zeros on Windows for a mat4 array

### ISSUE THREAD

**Issue by tuzz** [gfx-rs/wgpu#914]
**Description**

Hello, I've noticed some strange behaviour with storage buffers on Windows. I don't know if there's a bug with my code (there probably is) or if it's something in `wgpu`. 

In short, I have a storage buffer containing `mat4` elements:

```glsl
#version 310 es

layout(set=0, binding=0) buffer _0 { mat4 i_offset[]; };
```

On macOS, it's working fine. I can write data to the buffer and read it out in the shader.

On Windows, it seems to set data in the first row of the first matrix element only. All other rows contain zeros.

Setting `std140` or `std430` doesn't seem to help. Setting an explicit array size doesn't seem to help.

I think the alignment is correct since I'm using `mat4`.

**Repro steps**

I have a branch of some rendering code I wrote that exhibits the problem [here](https://github.com/tuzz/renderer/tree/macosx-windows-bug).

You can run it with:

```sh
$ git clone https://github.com/tuzz/renderer.git
$ cd renderer
$ git checkout macosx-windows-bug
$ cargo run --example quads --features shader_compilation
```

The vertex shader code that uses the `mat4` is [here](https://github.com/tuzz/renderer/blob/macosx-windows-bug/examples/quads/hello.vert).

I'm setting the data in the storage buffer [here](https://github.com/tuzz/renderer/blob/macosx-windows-bug/examples/quads.rs#L96-L106).

(I would obviously use a `vec2` for this normally but I'm trying to demonstrate the problem.)

**Expected vs observed behavior**

On macOS it does the correct thing. Two quads bounce around the screen and their x- and y-coordinates are changed over time:

![macosx](https://user-images.githubusercontent.com/892251/91879745-fee67180-ec77-11ea-8ce5-ff36d34fe24f.gif)

On Windows, it is incorrect. Only the x-coordinate of the first quad is changed and the second quad doesn't move at all:

![windows](https://user-images.githubusercontent.com/892251/91880184-1cb3d680-ec78-11ea-8895-c452131e33b2.gif)

**Platforms**

- macOS Catalina 10.15.6, Intel Iris 640
- Window 10, Nvidia GTX 950

Thanks

**Comment by cwfitzgerald** [comment]
On my 1080ti on Windows 10 using the vulkan backend, none of the boxes move at all. Using the DX12 backend I get the result you get. I can't easily see any issues from the surface or from renderdoc.

You are currently using an older version of `wgpu`, so it might be advantageous to upgrade to 0.6 as it adds a lot of validation.

On further poking of renderdoc, it appears you are only binding the first 8 bytes of your buffer. Metal doesn't care about the size of a buffer binding, so that could explain why it's working on metal.

**Comment by kvark** [comment]
To clarify: your buffer range provided in `BindGroupEntry` doesn't cover the 2 matrices, it's too small.
In the future, we'll be doing shader sanitation, so the behavior will be exactly the same on all platforms.

**Comment by tuzz** [comment]
Ahh, thank you both! It all makes sense now.

I'm going to have to learn how to use renderdoc as I'm hopeless at debugging these things. I'll definitely upgrade. More validations sounds great.

Apologies for opening an issue due to my carelessness. Will close now.

Thanks again

**Comment by tuzz** [comment]
Quick follow up: I upgraded to 0.6.0 which wasn't too difficult and everything is working as expected.
