### ISSUE TITLE
Maybe missing a validation on buffer/uniform bindings?

### ISSUE THREAD

**Issue by tuzz** [gfx-rs/wgpu#915]
**Description**
Hello, I noticed a small discrepancy between macOS and Windows.

Basically, if you write a shader that uses a buffer, like this:

```glsl
#version 310 es

layout(set=0, binding=0) buffer _0 { float u_something; };
```

You can read out of it on macOS if you set `wgpu::BufferUsage::UNIFORM` on the `wgpu::Buffer`.

You can try to read out of it on Windows but it will always return 0. No warnings/panics occur.

You must change the word `buffer` to `uniform` for it to work (correctly) in both places.

**Expected vs observed behavior**
I suppose I'd expect it to panic when you create the pipeline if the buffer usages don't map correctly to the shader code.

**Platform**
- macOS Catalina, Intel Iris 640
- Windows 10, GTX 950

Thanks

**Comment by kvark** [comment]
We have the validation code for shader interface in place. However, it's only active when `Naga` is able to parse your whole SPIR-V module, and this is where more progress is needed. It may very well be that after the next Naga update, the wgpu-rs from master will properly validate your case.

**Comment by cwfitzgerald** [comment]
Closed as we're now 100% naga
