### ISSUE TITLE
Minor typo in wgpu-core

### ISSUE THREAD

**Issue by Fruup** [gfx-rs/wgpu#937]
I was debugging some code and stumbled on this line. I figured it is most likely a typo, but with no major consequences.
The last condition in the if statement is probably supposed to be `size.depth == 0`.

https://github.com/gfx-rs/wgpu/blob/e72724a6e393503c73f37e86aa9317a5c62e32b8/wgpu-core/src/device/queue.rs#L297

**Comment by kvark** [comment]
Uh oh, nice find! could you make a PR?

**Comment by Fruup** [comment]
Done! https://github.com/gfx-rs/wgpu/pull/940
