### ISSUE TITLE
`PowerPreference::Default` description no longer applies

### ISSUE THREAD

**Issue by lberrymage** [gfx-rs/wgpu#943]
**Description**
The [doc comment](https://github.com/gfx-rs/wgpu/blob/49cf466dc4d8f04466fcf74214b577dbed888253/wgpu-types/src/lib.rs#L60) for `PowerPreference::Default` is as follows:
```
/// Prefer low power when on battery, high performance when on mains.
```
This statement is no longer true since #864 was merged.

**Expected vs observed behavior**
If a user's device has both a discrete and an integrated GPU and is plugged in, any application they run with `PowerPreference::Default` will use the integrated GPU, which is behavior contrary to the docs.

It is expected that either
1. `PowerPreference::Default` documents its equivalent behavior to `PowerPreference::LowPower`
2. `PowerPreference::Default` doesn't exist to prevent confusion

although I don't know if the second option is feasible or reasonable according to the [WebGPU spec](https://gpuweb.github.io/gpuweb/#enumdef-gpupowerpreference).

**Comment by grovesNL** [comment]
Fixed by #973 (`Default` doesn't exist anymore)
