### ISSUE TITLE
Buffer::map_write_async is buggy and may be unsound

### ISSUE THREAD

**Issue by aloucks** [gfx-rs/wgpu#95]
I'm having issues getting `Buffer::map_write_async` to work. If I use `fill_from_slice(vertices)`, everything works fine, but `map_write_async` is problematic. It also seems to be unsound. 

More often than not, my triangle does not render. I've tested with both the vulkan and the dx12 backends. 

I think adding `'static` to `F: FnOnce(BufferMapAsyncResult<&mut [T]>)` of `map_write_async` might fix the soundness issue, but I still was seeing buggy results even when I tried moving a clone of the vertices into the closure. 

The code that I was testing with roughly looks like this:

```rust
let flags = BufferUsageFlags::TRANSFER_SRC | BufferUsageFlags::MAP_WRITE;
let temp = device.create_buffer_mapped::<[f32; 3]>(vertices.len(), flags).finish();

temp.map_write_async(0, vertices_byte_length, |buffer| {
    match buffer {
        BufferMapAsyncResult::Success(mapped) => {
            for i in 0..mapped.len() {
                mapped[i] = vertices[i];
            }
            println!("wrote vertices");
        }
        BufferMapAsyncResult::Error => {
            panic!("map failed");
        }
    }
});
// adding this still compiles and the console shows the drop before the write
println!("dropped vertices");
drop(vertices);

encoder.copy_buffer_to_buffer(&temp, 0, &vertex_buffer, 0, vertices_byte_length);
device.get_queue().submit(&[encoder.finish()]);
```

Edit:

I was able to force synchronization by submitting an empty command buffer prior to submitting the buffer copy. I was previously under the impression that although the map operation was asynchronous, that the order of operations would be preserved. 

 With that said, I think this may be working as intended, with the exception of the soundness hole.

**Comment by kvark** [comment]
I can tell you for sure that `map_write_async` isn't functioning correctly. There is a simple workaround: just `create_buffer_mapped` for any transfer you need, fill it in place, and issue a copy operation. That's what the examples do anyway.

That is to say, `map_write_async` definitely needs to be fixed. In your example code `vertices` should be captured by the closure, and we need to convince the compiler that it's not OK to use it afterwards in the code. I think `FnOnce` would do.
