### ISSUE TITLE
Result::unwrap() failed at wgpu-core-0.5.6\src\instance.rs:552

### ISSUE THREAD

**Issue by casperstorm** [gfx-rs/wgpu#951]
**Description**
I am currently developing a app called [Ajour](https://github.com/casperstorm/ajour/) which uses the GUI framework [Iced](https://github.com/hecrj/iced/) which depends on `wgpu` (Yeah – thats a long way but im trying my luck here).

So I have a small group of users who are experiencing a crash on boot, and the panic they get is this:

```sh
09:50:21.959 [panic][ERROR] thread 'main' panicked at 'called Result::unwrap() on an Err value: InitializationFailed': C:\Users\Casper.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.6\src\instance.rs:552
   0: <unknown>
   1: <unknown>
  [...]
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
```

What stands out is [wgpu-core-0.5.6\src\instance.rs:552](https://docs.rs/wgpu-core/0.5.6/src/wgpu_core/instance.rs.html#538-552) which is why I am reaching out to you guys.
Do you have any clue what could be the case here?

From what i know it has happened on both Windows 10, with RTX 2070 and GTX 1080.
Both tells me they have the latest drivers installed.

Unfortunately I can't reproduce this my self.

**Platform**
Windows 10

**Comment by kvark** [comment]
It would help to get a normal stack trace from a debug run. Also, maybe we can ask the users to try running `wgpu-rs` examples? They have logging set up, could give us more info.

Do you know if the users have Vulkan installed?

**Comment by cwfitzgerald** [comment]
Without more information there's very little we can do to help this, so for now I'm going to close this. The biggest thing would be if it can be reproduced on 0.6 master. Feel free to re-open if there's more information.
