### ISSUE TITLE
Enabling shaderFloat64

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#961]
With my [Mandlebrot example](https://github.com/kas-gui/kas/blob/master/kas-wgpu/examples/mandlebrot.rs), I get a validation error:
```
[2020-10-06T10:08:44Z ERROR gfx_backend_vulkan] 
    VALIDATION [UNASSIGNED-CoreValidation-Shader-FeatureNotEnabled (-1940616195)] : Validation Error: [ UNASSIGNED-CoreValidation-Shader-FeatureNotEnabled ] Object 0: handle = 0x555c49b5b750, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x8c548bfd | Shader requires VkPhysicalDeviceFeatures::shaderFloat64 but is not enabled on the device
    object info: (type: DEVICE, hndl: 93854861997904)
```
Is there a way of enabling `shaderFloat64`? I don't see how. (This is probably one of the few graphical applications where f32 really doesn't provide enough precision.)

**Comment by dhardy** [comment]
I see; well don't let me tell you how best to solve this.

I notice that if it is an optional auto-enabled feature then users will not get any validation error / warning if using it without first checking its availability; apps will either work fine or crash/misbehave depending on the platform. Not ideal but I don't see a better solution.

**Comment by cwfitzgerald** [comment]
Once shader introspection further matures to be able to check the bodies of shaders, we should be able to detect use of 64 bit data and validate appropriately.

**Comment by cwfitzgerald** [comment]
Should be working now.
