### ISSUE TITLE
Implement buffer and texture destroy()

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#964]
**Is your feature request related to a problem? Please describe.**
WebGPU upstream has that: in a lot of cases we want to free the GPU memory right away, even if some CPU objects still refer to it. Using any of these objects is invalid after that happens.

**Describe the solution you'd like**
This is what `destroy()` would do on buffers and textures.

**Describe alternatives you've considered**
Rely on GC.

**Additional context**
Would help DungeonFog (cc @krupitskas ) - they resize textures and rely on internal GC to clean up memory.

**Comment by krupitskas** [comment]
I can take it, because anyway I need to fix this problem on our side :)
