### ISSUE TITLE
Fallback to OpenGL if Vulkan not available

### ISSUE THREAD

**Issue by enfipy** [gfx-rs/wgpu#972]
**Description**
Currently, it's not possible to run examples of WGPU on an Android emulator (tested on [official](https://developer.android.com/studio/run/emulator) android emulators on windows 10/mac 10.15) due to lack of Vulkan support. But it works well on real Android smartphones (currently, tested on Mi only).

The error may differ but here is one from my Mac Android emulator:
```
10-12 11:14:42.902  5395  5420 D vulkan  : searching for layers in '/data/app/~~FEEqvpvQbJT0JSo8apm6hg==/rust.app-8dgkmZZJTxv2FVxgPqeUyw==/lib/x86'
10-12 11:14:42.902  5395  5420 D vulkan  : searching for layers in '/data/app/~~FEEqvpvQbJT0JSo8apm6hg==/rust.app-8dgkmZZJTxv2FVxgPqeUyw==/base.apk!/lib/x86'
10-12 11:14:42.903  5395  5420 I gfx_backend_vulkan: Unable to find extension: VK_EXT_debug_utils
10-12 11:14:42.903  5395  5420 I gfx_backend_vulkan: Unable to find extension: VK_KHR_get_physical_device_properties2
10-12 11:14:42.903  5395  5420 W gfx_backend_vulkan: Unable to find layer: VK_LAYER_KHRONOS_validation
```

Is it possible to fall back to OpenGL ES when Vulkan failed to load? Some [researches](https://gist.github.com/zeux/7d3ff56568c6b02de3a87cc69899d949) shows that currently there's more than 50% of smartphones don't support Vulkan. What current blockers to support fallback?

**Repro steps**
All I did is created an empty cargo project and recreated WGPU `hello-triangle` example, then run on Android with `emulator -avd Pixel_XL_API_30`.

**Expected vs observed behavior**
Got errors while waited to see the example result as on my real smartphone.

**Platform**
Crates:
```
wgpu = { version = "0.6.0" }
ndk-glue = { version = "0.2" }
```

Platform:
MacOS Catalina Version 10.15.6

**Comment by kvark** [comment]
OpenGL is currently not supported. We are working on getting the gfx-backend-gl to work first, there is an issue with presentation. Also related - #450

**Comment by enfipy** [comment]
Sorry, I didn't notice! I think this issue can be closed if you want to.
