### ISSUE TITLE
Remove colors from debug markers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#975]
`push_debug_group` and friends don't have colors in WebGPU proper: https://gpuweb.github.io/gpuweb/#dom-gpucommandencoder-pushdebuggroup

**Comment by cwfitzgerald** [comment]
This appears to have been fixed at some point.

**Comment by kvark** [comment]
Colors are still in wgpu-core, but not in wgpu-rs. I think it's fine to keep it.
