### ISSUE TITLE
`hello_triangle` example makes computer run sluggishly.

### ISSUE THREAD

**Issue by VioletasTheThird** [gfx-rs/wgpu#98]
Hey, so I was running the `hello_triangle` example (well, I modified the shaders, but at the moment I'm not drawing anything at all so that shouldn't effect performance, and I have also tried with the plain example as it was as well) and the program seems to be slowing down my whole DE by a considerable amount. I can only assume this is not normal, so I decided to create this issue.

For info: 
OS: Pop!_OS (Linux kernel version 4.18.0-15-generic)
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz
GPU: NVIDIA GeForce GT 1030
RAM: 8GiB DDR4

Video:
https://www.youtube.com/watch?v=V8RmLH4z2Ec

**Comment by kvark** [comment]
Interesting issue, thank you for filing!
I double checked the cube example on my Linux+NV configuration, and I'm not seeing any DE slowdowns. There are some validation errors though that could be related to the misbehavior.
Could you run `make gfx name=cube` for the clean experiment?

**Comment by VioletasTheThird** [comment]
Still seem to get the same slowdowns, though it isn't any worse than before.

**Comment by eldyer** [comment]
Same here, also with Pop!_OS, GeForce GT 650M + latest proprietary Nvidia driver.
Also occurs when running gfx-hal examples.

**Comment by kvark** [comment]
@eldyer do you see the same for things like `vkCube`?

**Comment by eldyer** [comment]
@kvark Yep, just tried that. Seems like a driver problem then?

**Comment by kvark** [comment]
Yep, to be resolved upstream with either the compositor used, the drivers, or some parts of an OS. It's sad, but not something we could fix without distracting from the project too much.
