### ISSUE TITLE
Dispatch the backend internally in wgpu-core

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#985]
**Is your feature request related to a problem? Please describe.**
We have all the `wgpu` clients using `gfx_select!` . This is very inconvenient for all. Maybe it's not necessary?

**Describe the solution you'd like**
We could have a sub-layer in wgpu-core that is generic over `B: hal::Backend`. To some extent, we already do have that.
Then the dispatch will happen within `impl Global {..}` methods.

**Describe alternatives you've considered**
Keep it the way it is now.

**Additional context**
Was hit in #869

**Comment by cwfitzgerald** [comment]
I don't think there's much reason to do this at this point, and it allows some great inlining between wgpu-hal and wgpu-core.
