### ISSUE TITLE
Ecosystem: cargo plugin to run something from Visual Studio

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#996]
**Is your feature request related to a problem? Please describe.**
When developing on Windows, there is very often a need to run something from Visual Studio:
  - to see D3D12 debug messages
  - to be able to debug Rust code step-by-step

**Describe the solution you'd like**
`cargo-vs run xxx` - a cargo plugin to run something from within Visual Studio

**Describe alternatives you've considered**
Currently, we do this manually by going into VS's "Open Project", selecting the EXE, setting up the working dir and parameters, etc.

**Additional context**

**Comment by kvark** [comment]
@scoopr suggested that [devenv](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2019) could be helpful here, i.e.:
```
devenv /DebugExe ?
```

**Comment by cwfitzgerald** [comment]
Closing as out of scope, especially now as we get debug error messages on dx12
