### ISSUE TITLE
Unable to compile shaders on dx11 - UAV register conflict

### ISSUE THREAD

**Issue by Dinnerbone** [gfx-rs/wgpu#997]
**Description**
When trying to run our application on dx11 backend, compiling the shaders will throw the following error message and panic:

>UAV registers live in the same name space as outputs, so they must be bound to at least u1, manual bind to slot u0 failed

Our application works on dx12, vulkan and metal - dx11 just wants to be special ❤️

**Repro steps**
To repro in our project:
- Grab [this swf](https://github.com/ruffle-rs/visual-tests/raw/master/tests/drawing_api/fills_and_lines/test.swf)
- Clone [Ruffle](https://github.com/ruffle-rs/ruffle/)
- `cargo run --package=ruffle_desktop -- test.swf -g dx11`
- Cry over the millions of beautiful pixels that could have been, but weren't.

**Expected vs observed behavior**
I'll be honest, my expected behaviour was that this is a bug in our shader, but @cwfitzgerald seems willing to take sole responsibility for this one.

**Extra materials**
Specific shaders in this pipeline:
- [Vertex shader](https://github.com/ruffle-rs/ruffle/blob/8465638939a8ccd85159b45bc7ac716f53cfe77b/render/wgpu/shaders/texture.vert)
- [Fragment shader](https://github.com/ruffle-rs/ruffle/blob/8465638939a8ccd85159b45bc7ac716f53cfe77b/render/wgpu/shaders/gradient.frag)

Panic:
```
thread 'main' panicked at 'failed to create graphics pipeline: Failed to create pipeline: Shader error: Compilation failed: W:\personal\ruffle\Shader@0x00000166197C6690(25,17-62): warning X3571: pow(f, e) will not work for negative f, use abs(f) or conditionally handle negative values if you expect them
W:\personal\ruffle\Shader@0x00000166197C6690(1,21-23): error X4509: UAV registers live in the same name space as outputs, so they must be bound to at least u2, manual bind to slot u0 failed
 ', C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:3102:30
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
   1: std::panicking::begin_panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:429
   2: wgpu_core::device::{{impl}}::device_create_render_pipeline::{{closure}}<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx11::Backend>
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:3102
   3: core::result::Result<gfx_backend_dx11::GraphicsPipeline, gfx_hal::pso::CreationError>::map_err<gfx_backend_dx11::GraphicsPipeline,gfx_hal::pso::CreationError,wgpu_core::device::DeviceError,closure-10>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:595
   4: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_render_pipeline<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx11::Backend>
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:3097
   5: wgpu::backend::direct::{{impl}}::device_create_render_pipeline
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\backend\direct.rs:814
   6: wgpu::Device::create_render_pipeline
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\lib.rs:1498
   7: ruffle_render_wgpu::pipelines::create_gradient_pipeline::{{closure}}
             at .\render\wgpu\src\pipelines.rs:559
```

**Platform**
Windows 10 x64
DirectX 11 backend only

**Comment by cwfitzgerald** [comment]
Fixed in gfx-backend-dx11 v0.6.10

Also this didn't auto-close.
