### ISSUE TITLE
TextureFormat R16Unorm?

### ISSUE THREAD

**Issue by eseaflower** [gfx-rs/wgpu#999]
I am trying to sample a 16-bit (unsigned int) texture in a shader using texture format R16Uint. This works great with the Vulkan backend, however when I try to use the DX12 backend I get an error informing me that HLSL does not support sampling from non-integer textures. So I thought I'd change the texture format to R16Unorm, but this format seems to have disapeared? When googling for it I find a reference in wgpu-types v. 0.4.0 but it seems to have disapeared in a later update.

Why has the R16Unorm format disapeared, has it been replaced by another format?

**Comment by eseaflower** [comment]
Moved this issue to wgpu-rs where it belongs.

**Comment by kvark** [comment]
Note: we can move issues around, no need to close and open new ones

**Comment by kvark** [comment]
> This works great with the Vulkan backend, however when I try to use the DX12 backend I get an error informing me that HLSL does not support sampling from non-integer textures.

Please provide the concrete error you got. Technically, sampling from integer textures should be allowed, I think, but the only aspects of samplers that it would use are:
  - normalized coordinates
  - wrapping modes

All the other properties of samplers don't apply to integer textures.

> Why has the R16Unorm format disapeared, has it been replaced by another format?

It's not portable, hence it's gone.

**Comment by eseaflower** [comment]
Problem:
I have a 16-bit monochrome (single channel) image that I want to sample in a fragment shader.
The texture, view and sampler is created according to:
```
        let texture = device.create_texture(&wgpu::TextureDescriptor {
            size: texture_size,
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::R16Uint,
            usage: wgpu::TextureUsage::SAMPLED | wgpu::TextureUsage::COPY_DST,
            label: Some("MyTexture"),
        });

        // Create a texture view
        let texture_view = texture.create_view(&wgpu::TextureViewDescriptor::default());
        let texture_sampler = device.create_sampler(&wgpu::SamplerDescriptor {
            address_mode_u: wgpu::AddressMode::ClampToEdge,
            address_mode_v: wgpu::AddressMode::ClampToEdge,
            address_mode_w: wgpu::AddressMode::ClampToEdge,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            lod_min_clamp: -100.0,
            lod_max_clamp: 100.0,
            compare: None,
            anisotropy_clamp: None,
            mipmap_filter: wgpu::FilterMode::Nearest,
            label: Some("MySampler"),
        });
```
The bind group layout as:
```
        // Create a bind group for the texture.
        device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("MyBindgroupLayout"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStage::FRAGMENT,
                    ty: wgpu::BindingType::SampledTexture {
                        multisampled: false,
                        dimension: wgpu::TextureViewDimension::D2,
                        component_type: wgpu::TextureComponentType::Uint,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStage::FRAGMENT,
                    ty: wgpu::BindingType::Sampler { comparison: false },
                    count: None,
                },
            ],
        })
```
The shader is something like:
```
#version 450

layout(location=0) out vec4 f_color;
layout(location=0) in vec2 v_tex;

layout(set=0, binding=0) uniform utexture2D t_tex;
layout(set=0, binding=1) uniform sampler s_tex;

void main() {
    uint stored_value = texture(usampler2D(t_tex, s_tex), v_tex).r;
    float normalized = float(stored_value) / 65535.0;
    f_color = vec4(vec3(normalized), 1.0);
}
```
The shader is compiled from GLSL to SPIR-V with `shaderc`.

This works when running with the Vulkan backend. When I run with the DX12 backend I get the following error:

```
2020-10-21 17:38:39,249 INFO  [gfx_backend_dx12::device] Creating a pipeline layout with 1 sets and 0 root constants
There was a compiler error: Sampling non-float textures is not supported in HLSL.
```

Googling for the error it seems that the error comes from the SPIRV Cross library. The error itself is very clear,
I am not allowed to sample a non-float texture. This is the point where wanted to find a 16-bit texture format that
I am allowed to sample from. I found the format `DXGI_FORMAT_R16_UNORM` that I thought would suit my purposes, hence my question regarding support for this format in wgpu.

The only 16-bit float mono format seems to be `R16Float`, but it is not clear to me how I convert my `Vec<u16>` into something that is expected by the texture format. I assume that the texture expects IEEE 754 (s10e5) floats, which is non-trivial to convert to.

That is my actual problem, but I have gotten the answer to why `R16Unorm` is not there anymore, portabillity.

**Comment by kvark** [comment]
Thank you for the detailed issue writeup! I can confirm that this is a problem with WebGPU upstream, we are going to figure out a solution in https://github.com/gpuweb/gpuweb/issues/1162 .
For your case, I recommend changing `texture` to `texelFetch`, and that should work on integer textures.

**Comment by kvark** [comment]
I believe this is addressed now. Naga has the necessary validation in place.
